### ISSUE TITLE
config issue

### ISSUE THREAD

**Issue by johnlanbor** [open-mmlab/mmpose#10]
configs/top_down/resnet/coco/res50_coco_256x192.py
missed
`test_pipeline = valid_pipeline`

**Comment by innerlee** [comment]
thanks for the report!

**Comment by Canwang-sjtu** [comment]
thanks, I will make the corresponding changes.

**Comment by innerlee** [comment]
Fixed by https://github.com/open-mmlab/mmpose/pull/12
