### ISSUE TITLE
发现UDP 论文的一处推导过程有问题，不知道这个对最终的结果有影响没

### ISSUE THREAD

**Issue by canghaiyunfan** [open-mmlab/mmpose#1002]
![image](https://user-images.githubusercontent.com/21115878/140011717-c8c9cc58-cfdb-4645-80ca-e0c5dd20fd18.png)

标红框的地方是不是计算有误，这个对最终的结果有影响吗

另外，为啥只对resize 过程采用像素表示，而flip 还是原来的表示方式？

**Comment by jin-s13** [comment]
How about also raising an issue in [UDP](https://github.com/HuangJunJie2017/UDP-Pose)?

**Comment by jin-s13** [comment]
@HuangJunJie2017 Could you please help offer some help about this question?

**Comment by canghaiyunfan** [comment]
@jin-s13 我知道为什么了，作者没有错，感谢
