### ISSUE TITLE
Question on how to restore original image from heatmap output

### ISSUE THREAD

**Issue by kcs6568** [open-mmlab/mmpose#1008]
Hello.
First of all, thank you for providing this wonderful project.

Also, I ask for your understanding in advance for my lack of English skills.

I'm investigating how to restore the heatmap output by the model to the original image.

I am using the top-down HRNet. I was investigating how to extract the location with the maximum probability from the single-person heatmap predicted by HRNet and use it to map the pixel location of the original input image.

The first thing I tried was to apply the heatmap output to the transform function.
I applied many different transformation functions provided by mmpose (e.g. transform_preds and flip_back in post_transforms.py) and tested whether the result was mapped with ground-truth location.

However, due to the image augmentation process, the original image was deformed, and as a result, the location was also printed as a modified value.

So I thought about applying the data augmentation methods in reverse order and recovering them, but I'm not sure if there's a method for this.

Is there a method defined that can restore the augmented heatmap location to the original image location?

If not, can I ask for a simple idea to do this through mmpose?

Thank you in advance for your help.

**Comment by jin-s13** [comment]
How about simply disabling the data augmentation pipeline (scaling/rotation)?  Like what we have done during inference.

**Comment by kcs6568** [comment]
Thanks for the reply.

The research I am going to do is to utilize the output of the existing PoseNet.
So, I wanted to maintain the training performance or testing performance of the existing PoseNet as much as possible.

Doesn't the disabling augmentation pipeline degrade performance?

Thanks in advance for your help.

**Comment by jin-s13** [comment]
The data augmentation is only used during training and not used during evaluation.

**Comment by kcs6568** [comment]
Thank you for your help!

I understand that the TopDownAffine module is responsible for cropping the bounding box area and resizing the area to the input size (e.g. [288, 384]).
Is my understanding correct?

**Comment by jin-s13** [comment]
During inference, yes.

**Comment by kcs6568** [comment]
Thank you jin!

Your advice has been very helpful. Thank you very much.

**Comment by mgcyung** [comment]
> TopDownAffine

Is there a detailed code for applying the TopDownAffine?
