### ISSUE TITLE
Did AEHigherResolutionHead change?

### ISSUE THREAD

**Issue by wuyuuu** [open-mmlab/mmpose#1012]
Hi,

recently, I'm reimplementing my previous mmpose-based network.

I noticed that previous names such as model type like 'BottomUp' and keypoint head type like 'BottomUpHigherResolutionHead' changed so I just renamed those names in configs and kept others unchanged.

However, I found the training process did not work as before and also the network flops changed given by the get_flops.py.

The previous one got Flops: 3.65 GFLOPs Params: 5.36 M and the current one shows Flops: 1.69 GFLOPs Params: 5.36 M (obvious GFLOPs is not the same). It seems to me the reduced GFLOPS comes from HigherResolutionHead.

So I'm wondering if you changed something in BottomUpHigherResolutionHead or it is me that modified some codes but then I just forgot what I did.

Looking forward to your reply,
Thanks!

**Comment by jin-s13** [comment]
We don't seem to have changed this part of the code recently.

**Comment by wuyuuu** [comment]
> We don't seem to have changed this part of the code recently.

Yes, I've figured out where my mistake was (it turns out that I commented part of my code so the network forward propagation stops earlier than expected😂).
Thanks for your reply!
