### ISSUE TITLE
About the files needed in 2D-to-3D-pose lifting

### ISSUE THREAD

**Issue by Huhaowen0130** [open-mmlab/mmpose#1013]
Hello, I'm trying to use mmpose to convert my already detected 2D poses into 3D. And it seems to require a .pkl file. May I ask what it is and how to get it? Thank you!
![捕获](https://user-images.githubusercontent.com/54608650/141710590-465cad58-88f2-42a5-9195-7482f7da6fba.PNG)

**Comment by ly015** [comment]
`--only-second-stage` means the input is detected or ground-truth 2D keypoints, and the demo script only performs the pose lifting part (namely the second stage). Alternatively, if you wish to inference 3D keypoints from an image, `--only-second-stage` should not be set, and the script will inference a 2D keypoint detection model and then a 2D-to-3D lifting model.

`--camera-param-file` should be a file containing camera parameters. It should be set according to the training data of the model you use. So if you plan to use the h36m model we provided, we suggested using the default h36m camera parameters, which are extracted from the original data file.

**Comment by Huhaowen0130** [comment]
> `--only-second-stage` means the input is detected or ground-truth 2D keypoints, and the demo script only performs the pose lifting part (namely the second stage). Alternatively, if you wish to inference 3D keypoints from an image, `--only-second-stage` should not be set, and the script will inference a 2D keypoint detection model and then a 2D-to-3D lifting model.
> 
> `--camera-param-file` should be a file containing camera parameters. It should be set according to the training data of the model you use. So if you plan to use the h36m model we provided, we suggested using the default h36m camera parameters, which are extracted from the original data file.

Thank you for your reply. If I'm going to test with my own image data, what should I do? Do I need to retrain the model with my dataset and get new camera parameters, or I can simply use default model and camera parameters?

**Comment by ly015** [comment]
I think you can try the models trained on datasets like h36m or mpi-inf-3dhp and see if they meet your requirements. These models can be found in mmpose model zoo. It could be difficult to build a dataset with ground-truth 3D keypoints.

**Comment by Huhaowen0130** [comment]
> I think you can try the models trained on datasets like h36m or mpi-inf-3dhp and see if they meet your requirements. These models can be found in mmpose model zoo. It could be difficult to build a dataset with ground-truth 3D keypoints.

Thank you, I will try in default mode first.
