### ISSUE TITLE
one-stage 3d human body pose estimation

### ISSUE THREAD

**Issue by sunmengnan** [open-mmlab/mmpose#1016]
will you release one-stage 3d human body pose estimation model and demo in the near future?

**Comment by ly015** [comment]
Thanks for your interest. We have a plan to support [Coarse-to-Fine Volumetric Prediction for Single-Image 3D Human Pose](https://arxiv.org/abs/1611.07828) in late December. If you have any suggested work to support in mmpose, please leave a comment on the [roadmap page](https://github.com/open-mmlab/mmpose/issues/9).
