### ISSUE TITLE
Details of VideoPose3D Results

### ISSUE THREAD

**Issue by diwgan32** [open-mmlab/mmpose#1021]
Hello! In the results of the VideoPose3D experiments [here](https://github.com/open-mmlab/mmpose/blob/master/configs/body/3d_kpt_sview_rgb_vid/video_pose_lift/h36m/videopose3d_h36m.md) there are MPJPE's reported for various model configurations. However, I'm not able to quite replicate the results reported here using the mmpose codebase. As a clarification, for the models with receptive fields > 1, were the input 2D frames provided at the original 50fps that H36M comes in, or at the downsampled 10fps? I notice a significant hit in performance when running the 243-Receptive-Field model at 10fps, so I was wondering if it had to be run at the original 50 to get the results reported above. Thanks in advance!

**Comment by ly015** [comment]
50 fps h36m data were used in videopose3d experiments.
