### ISSUE TITLE
how to train hornet_32 on imagenet ?

### ISSUE THREAD

**Issue by daixiangzi** [open-mmlab/mmpose#1022]
for example ,I want to get hrnet_w32-36af842e.pth pre_model

**Comment by daixiangzi** [comment]
can you offer a network structure file for me?

**Comment by ly015** [comment]
We use the pretrained checkpoint released by the author of HRNet, thus we don't have a complete config file for the model, only the backbone part.

**Comment by daixiangzi** [comment]
Thank you.but i only get backbone structure file.you can offer a file for me?



我没有什么天赋，我只是生而由来的执着。


------------------ Original ------------------
From: Yining Li ***@***.***&gt;
Date: Wed,Nov 17,2021 11:49 AM
To: open-mmlab/mmpose ***@***.***&gt;
Cc: daixiangzi ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [open-mmlab/mmpose] how to train hornet_32 on imagenet ? (Issue#1022)





 
We use the pretrained checkpoint released by the author of HRNet, thus we don't have a complete config file for the model, only the backbone part.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ly015** [comment]
You can refer to any config file using hrnet for the backbone part, for example [here](https://github.com/open-mmlab/mmpose/blob/4a3b12a403d78d538cb1b801112c431ae0f5060e/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w32_coco_256x192.py#L45-L72). The download link of the pretrained hrnet can also be found in the config.

**Comment by daixiangzi** [comment]
> You can refer to any config file using hrnet for the backbone part, for example [here](https://github.com/open-mmlab/mmpose/blob/4a3b12a403d78d538cb1b801112c431ae0f5060e/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w32_coco_256x192.py#L45-L72). The download link of the pretrained hrnet can also be found in the config.

ok, thank you
