### ISSUE TITLE
keypoint mAP

### ISSUE THREAD

**Issue by alicera** [open-mmlab/mmpose#1023]
Do you know how to valuate the keypoint mAP like general coco mAP?

**Comment by jin-s13** [comment]
Here it is  https://github.com/open-mmlab/mmpose/blob/4a3b12a403d78d538cb1b801112c431ae0f5060e/mmpose/datasets/datasets/top_down/topdown_coco_dataset.py#L362

**Comment by alicera** [comment]
How can I run the sample ?

Thanks for your help.

**Comment by jin-s13** [comment]
Please follow this instruction to evaluate the model.

https://mmpose.readthedocs.io/en/latest/getting_started.html#test-a-dataset

**Comment by alicera** [comment]
I have some question about the score. The score is the person confidence not the keypoint score. So the score is not used on here. Instead, it use the v = 2  of key_point.tolist()?
 
https://github.com/open-mmlab/mmpose/blob/4a3b12a403d78d538cb1b801112c431ae0f5060e/mmpose/datasets/datasets/top_down/topdown_coco_dataset.py#L353



ref : 
https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocoEvalDemo.ipynb
https://github.com/cocodataset/cocoapi/blob/master/results/person_keypoints_val2014_fakekeypoints100_results.json

**Comment by alicera** [comment]
https://github.com/open-mmlab/mmpose/blob/master/demo/docs/2d_face_demo.md

Is your face  also use the format (x,y,v) to _do_python_keypoint_eval?
https://github.com/cocodataset/cocoapi/blob/8c9bcc3cf640524c4c20a9c40e89cb6a2f2fa0e9/results/person_keypoints_val2014_fakekeypoints100_results.json#L1

**Comment by jin-s13** [comment]
1.The person confidence score is calculated, as follows:

https://github.com/open-mmlab/mmpose/blob/4a3b12a403d78d538cb1b801112c431ae0f5060e/mmpose/datasets/datasets/top_down/topdown_coco_dataset.py#L302

The person score is used during evaluation for matching & ranking. 

2. Is your face also use the format (x,y,v) to _do_python_keypoint_eval?

Yes. See https://github.com/open-mmlab/mmpose/blob/59c5cc17e9d722be23854bd291bf3dccd8be59e0/mmpose/datasets/datasets/base/kpt_2d_sview_rgb_img_top_down_dataset.py#L263

**Comment by alicera** [comment]
For WFLW
what is the mean 60, 72
gts[:, 60, :] - gts[:, 72, :]

https://github.com/open-mmlab/mmpose/blob/59c5cc17e9d722be23854bd291bf3dccd8be59e0/mmpose/datasets/datasets/face/face_wflw_dataset.py#L123

![image](https://user-images.githubusercontent.com/59388989/144187848-517205fe-f720-4b0e-97b8-d80f88a61603.png)

**Comment by jin-s13** [comment]
Normalized Mean Error (NME) is one of the most popular evaluation metrics in facial landmark detection benchmark.
NME will use the distance of the "outer eye corners"  as the normalization factor.
60 and 72 are two corners.

**Comment by alicera** [comment]
The widerface have 5 landmark. Should I set the  the distance of the "2 eye " as the normalization factor ?

![image](https://user-images.githubusercontent.com/59388989/144195453-4ed3f166-6cbd-4e3f-9414-5993c6044637.png)

Thanks for your help.

**Comment by jin-s13** [comment]
I am not sure what is the common practice for widerface. 
But I think it is ok to use the distance of the "2 eye " as the normalization factor.

**Comment by alicera** [comment]
These eval is based on one image has only one face.
Do you use the iou method to compare pred and gt for face landmark ?

**Comment by jin-s13** [comment]
No. For face keypoint localization, we only support top-down methods, and gt bounding boxes are given. So each gt face is associated with all the pred face kpts. We do not need to match the pred and gt faces again.

**Comment by jin-s13** [comment]
If you also want to evaluate the multi-face cases, you may refer to COCO dataset, where mAP is adopted as the evaluation metric.
