### ISSUE TITLE
model zoo link is dead

### ISSUE THREAD

**Issue by twmht** [open-mmlab/mmpose#1037]
The link to all the pretrained face keypoints models is dead

https://mmpose.readthedocs.io/en/latest/face_models.html#face-models

Any idea?

**Comment by jin-s13** [comment]
Hi, where did you find this link? https://mmpose.readthedocs.io/en/latest/face_models.html#face-models


Now, the models can be found in the link below.
https://mmpose.readthedocs.io/en/latest/topics/face.html

**Comment by twmht** [comment]
you can find the dead link here https://github.com/open-mmlab/mmpose/blob/master/demo/docs/2d_face_demo.md

**Comment by jin-s13** [comment]
Thanks, I will fix it soon.
