### ISSUE TITLE
What is the meaning of scale / 200.0

### ISSUE THREAD

**Issue by qtboi** [open-mmlab/mmpose#1042]
Data pipeline operating with bboxes of the format `center, scale`;
In docs i found no information about what the `scale` parameter is and when tried to figure it out from code come across the [following](https://github.com/open-mmlab/mmpose/blob/538d92a2190b5b49a040b4fc80f92c0b787e08cf/mmpose/datasets/datasets/base/kpt_2d_sview_rgb_img_top_down_dataset.py#L153):
```
# pixel std is 200.0
scale = np.array([w / 200.0, h / 200.0], dtype=np.float32)
``` 
For me comment "pixel std is 200.0" means nothing. Also in other places, when using a scale, it is multiplied by 200 with the same comment.
Could someone explain the meaning of it to me and i suspect for many other mmpose new users?

**Comment by jin-s13** [comment]
Why do we need pixel_std?
Some datasets (such as mpii, mpii-trb) do not provide w and h, they simply provide center/scale. And their scales are calculated by w/200 and h/200. In order to be compatible to both cases, we also set pixel_std=200.

**Comment by qtboi** [comment]
thanks for the quick response
