### ISSUE TITLE
The loss for topdown res50 model does not decrease for ATRW dataset

### ISSUE THREAD

**Issue by maicoa** [open-mmlab/mmpose#1073]
**acc_pose** gradually **decreases** during training, but **loss did not decrease:**:

{"mode": "train", "epoch": 1, "iter": 86, "lr": 9e-05, "memory": 3665, "data_time": 0.00103, "mse_loss": 0.00145, "acc_pose": 0.11543, "loss": 0.00145, "time": 0.33785}
{"mode": "train", "epoch": 1, "iter": 87, "lr": 9e-05, "memory": 3665, "data_time": 0.00102, "mse_loss": 0.00176, "acc_pose": 0.14124, "loss": 0.00176, "time": 0.37669}
......
{"mode": "train", "epoch": 4, "iter": 259, "lr": 0.0005, "memory": 3665, "data_time": 0.00085, "mse_loss": 0.00165, "acc_pose": 0.08232, "loss": 0.00165, "time": 0.33637}
{"mode": "train", "epoch": 4, "iter": 260, "lr": 0.0005, "memory": 3665, "data_time": 0.0008, "mse_loss": 0.00173, "acc_pose": 0.03979, "loss": 0.00173, "time": 0.33305}
{"mode": "train", "epoch": 4, "iter": 261, "lr": 0.0005, "memory": 3665, "data_time": 0.00082, "mse_loss": 0.00179, "acc_pose": 0.04054, "loss": 0.00179, "time": 0.33771}
{"mode": "train", "epoch": 4, "iter": 262, "lr": 0.0005, "memory": 3665, "data_time": 0.00081, "mse_loss": 0.00177, "acc_pose": 0.06421, "loss": 0.00177, "time": 0.33103}
......

**Comment by maicoa** [comment]
Run according to MMPose's guide: 
**python tools/train.py configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/atrw/res50_atrw_256x256.py,**
**The following results appear:**
{"mode": "train", "epoch": 10, "iter": 13, "lr": 0.00033, "memory": 8570, "data_time": 0.00687, "mse_loss": 0.00219, "acc_pose": 0.00294, "loss": 0.00219, "time": 0.5869}
{"mode": "train", "epoch": 10, "iter": 14, "lr": 0.00033, "memory": 8570, "data_time": 0.00714, "mse_loss": 0.00192, "acc_pose": 0.01183, "loss": 0.00192, "time": 0.58531}
{"mode": "train", "epoch": 10, "iter": 15, "lr": 0.00033, "memory": 8570, "data_time": 0.00632, "mse_loss": 0.00198, "acc_pose": 0.00607, "loss": 0.00198, "time": 0.56683}
{"mode": "train", "epoch": 10, "iter": 16, "lr": 0.00033, "memory": 8570, "data_time": 0.00652, "mse_loss": 0.00218, "acc_pose": 0.0028, "loss": 0.00218, "time": 0.56398}
{"mode": "train", "epoch": 10, "iter": 17, "lr": 0.00033, "memory": 8570, "data_time": 0.00677, "mse_loss": 0.00208, "acc_pose": 0.00152, "loss": 0.00208, "time": 0.57663}
{"mode": "train", "epoch": 10, "iter": 18, "lr": 0.00033, "memory": 8570, "data_time": 0.00811, "mse_loss": 0.00216, "acc_pose": 0.00392, "loss": 0.00216, "time": 0.60031}
{"mode": "train", "epoch": 10, "iter": 19, "lr": 0.00033, "memory": 8570, "data_time": 0.00731, "mse_loss": 0.00203, "acc_pose": 0.00979, "loss": 0.00203, "time": 0.54564}
{"mode": "train", "epoch": 10, "iter": 20, "lr": 0.00033, "memory": 8570, "data_time": 0.00661, "mse_loss": 0.00211, "acc_pose": 0.00518, "loss": 0.00211, "time": 0.58729}
{"mode": "train", "epoch": 10, "iter": 21, "lr": 0.00034, "memory": 8570, "data_time": 0.00661, "mse_loss": 0.00193, "acc_pose": 0.003, "loss": 0.00193, "time": 0.57572}
{"mode": "train", "epoch": 10, "iter": 22, "lr": 0.00034, "memory": 8570, "data_time": 0.00608, "mse_loss": 0.00213, "acc_pose": 0.00556, "loss": 0.00213, "time": 0.60592}
{"mode": "train", "epoch": 10, "iter": 23, "lr": 0.00034, "memory": 8570, "data_time": 0.00824, "mse_loss": 0.00225, "acc_pose": 0.00418, "loss": 0.00225, "time": 0.59416}
{"mode": "train", "epoch": 10, "iter": 24, "lr": 0.00034, "memory": 8570, "data_time": 0.00683, "mse_loss": 0.00203, "acc_pose": 0.0055, "loss": 0.00203, "time": 0.61403}
{"mode": "train", "epoch": 10, "iter": 25, "lr": 0.00034, "memory": 8570, "data_time": 0.00757, "mse_loss": 0.00223, "acc_pose": 0.00682, "loss": 0.00223, "time": 0.57173}
{"mode": "train", "epoch": 10, "iter": 26, "lr": 0.00034, "memory": 8570, "data_time": 0.00669, "mse_loss": 0.00207, "acc_pose": 0.0047, "loss": 0.00207, "time": 0.59099}
{"mode": "train", "epoch": 10, "iter": 27, "lr": 0.00034, "memory": 8570, "data_time": 0.00822, "mse_loss": 0.00219, "acc_pose": 0.00975, "loss": 0.00219, "time": 0.58594}
{"mode": "train", "epoch": 10, "iter": 28, "lr": 0.00034, "memory": 8570, "data_time": 0.00723, "mse_loss": 0.00204, "acc_pose": 0.00314, "loss": 0.00204, "time": 0.60098}
{"mode": "train", "epoch": 10, "iter": 29, "lr": 0.00034, "memory": 8570, "data_time": 0.00639, "mse_loss": 0.00206, "acc_pose": 0.00895, "loss": 0.00206, "time": 0.57133}
{"mode": "train", "epoch": 10, "iter": 30, "lr": 0.00034, "memory": 8570, "data_time": 0.007, "mse_loss": 0.00194, "acc_pose": 0.00661, "loss": 0.00194, "time": 0.59834}
{"mode": "train", "epoch": 10, "iter": 31, "lr": 0.00035, "memory": 8570, "data_time": 0.00704, "mse_loss": 0.00209, "acc_pose": 0.00431, "loss": 0.00209, "time": 0.60087}
{"mode": "train", "epoch": 10, "iter": 32, "lr": 0.00035, "memory": 8570, "data_time": 0.00769, "mse_loss": 0.00201, "acc_pose": 0.00551, "loss": 0.00201, "time": 0.57769}
{"mode": "train", "epoch": 10, "iter": 33, "lr": 0.00035, "memory": 8570, "data_time": 0.00685, "mse_loss": 0.00194, "acc_pose": 0.01165, "loss": 0.00194, "time": 0.59468}
{"mode": "train", "epoch": 10, "iter": 34, "lr": 0.00035, "memory": 8570, "data_time": 0.00762, "mse_loss": 0.00215, "acc_pose": 0.00555, "loss": 0.00215, "time": 0.588}
{"mode": "train", "epoch": 10, "iter": 35, "lr": 0.00035, "memory": 8570, "data_time": 0.0073, "mse_loss": 0.0032, "acc_pose": 0.0, "loss": 0.0032, "time": 0.21082}
{"mode": "val", "epoch": 10, "iter": 11, "lr": 0.00035, "AP": 0.0, "AP .5": 0.0, "AP .75": 0.0, "AP (M)": -1.0, "AP (L)": 0.0, "AR": 0.0, "AR .5": 0.0, "AR .75": 0.0, "AR (M)": -1.0, "AR (L)": 0.0}

**Comment by jin-s13** [comment]
@liqikai9 Could you please help check this issue?

**Comment by liqikai9** [comment]
> @liqikai9 Could you please help check this issue?

OK,  I will rerun this config and check it.

**Comment by liqikai9** [comment]
@maicoa Thanks for your error report and we appreciate it a lot. But we still need more information about the command your run to locate the problem. So could you please offer us detail about the following questions?

- Did you make any modifications on the code or config?

- About the environment. Please run `PYTHONPATH=${PWD}:$PYTHONPATH python mmpose/utils/collect_env.py` to collect necessary environment information and paste it here.

**Comment by jin-s13** [comment]
Hi @maicoa , 
Did you solve this problem?

**Comment by jin-s13** [comment]
I will close this issue for now due to inactivity.
