### ISSUE TITLE
Combine multi object object detection and keypoint regression with a single backbone

### ISSUE THREAD

**Issue by joihn** [open-mmlab/mmpose#1075]
I want to train both keypoint regresion and bounding box at the same time with a single backbone, having 2 separate head.
Is it possible with this tool ? 
From my understanding one need first to compute BBox with MMdetection, **THEN** give the BBox to MMPose and train a fully separate net just for kepoints. Is it correct ?

**Comment by ly015** [comment]
For now, MMPose doesn't support a unified model for bbox and keypoint regression with a single backbone. To predict both bboxes and keypoints from images, you could:

- Combine a bbox detector from MMDetection and a top-down keypoint detector from MMPose, or
- Use a bottom-up keypoint detector (e.g. Associative Embedding) from MMPose, and estimate the person bbox from the detected keypoints .

If a unified bbox and keypoint detector (single backbone with multiple heads) is what you need, I think the best way is to derive it from an MMDetection detector (e.g. Mask R-CNN) and add a keypoint head to it.  Also, we have a long-range plan to support this type of model in MMPose by implementing an MMDetection wrapper, which encapsulates bbox detection parted and can be integrated with keypoint heads.

**Comment by joihn** [comment]
I've added a new keypoint head to MMdetection (derivated from mask rcnn), it was rather easy.

However I'm having a lot of trouble binding it to the COCO metrics, 
I've tried to look at the eval metrics implementation of MMPose, MMdetection and detectron2  but they all use different binding to pycocotool and I'm a bit lost. 

Any tipps for metrics eval ? Thanks

**Comment by jin-s13** [comment]
1. You may refer to https://github.com/open-mmlab/mmpose/blob/master/mmpose/datasets/datasets/top_down/topdown_coco_dataset.py#L284-L309 for keypoint NMS.
2. xtcocotools is an improved version of pycocotools to support different datasets besides COCO. It is compatible with pycocotools. And you can choose either one, if you want to evaluate on the COCO dataset.

**Comment by joihn** [comment]
thanks for your response, in the end I did the nms on the BBox (already implemented in mmdetection), then I take their associated Keypoint and directly use them :)
