### ISSUE TITLE
TopDownAicDataset: annotation file format <class 'list'> not supported

### ISSUE THREAD

**Issue by APeiZou** [open-mmlab/mmpose#1078]
python3   tools/train.py   configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/aic/litehrnet_aic_256x192.py    --gpu-ids  3
编译正确，训练的时候报错说不支持TopDownAicDataset类型的数据
Traceback (most recent call last):
  File "tools/train.py", line 170, in <module>
    main()
  File "tools/train.py", line 145, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/sa/workspace/zml/pose_code/mmpose/mmpose/datasets/builder.py", line 44, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/sa/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
AssertionError: TopDownAicDataset: annotation file format <class 'list'> not supported

**Comment by ly015** [comment]
Could you please provide the full config?

**Comment by jin-s13** [comment]
Hi, @APeiZou 
Did you solve this problem?

**Comment by APeiZou** [comment]
解决了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年12月28日 14:43 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [open-mmlab/mmpose] TopDownAicDataset: annotation file format <class 'list'> not supported (Issue #1078) |

Hi, @APeiZou
Did you solve this problem?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by alaa-shubbak** [comment]
can you please tell me how did you solve it. 
thanks

**Comment by alaa-shubbak** [comment]
can any one explain how to solve such issue ? i would like to open this issue and give more explanation that help in solve it. 

many thanks for your support.
