### ISSUE TITLE
[Slow validation during traning] Why do you set samples_per_gpu as 1 and do not give a interface in the function?

### ISSUE THREAD

**Issue by igodogi** [open-mmlab/mmpose#1081]
https://github.com/open-mmlab/mmpose/blob/228747c298c0801dea093371abeca539d41a7584/mmpose/apis/train.py#L173

**Comment by ly015** [comment]
The parameter `samples_per_gpu` can be set in config files. The code snippet you quoted only serves as a default setting, which will be used when these parameters are not given in the config. Please check https://github.com/open-mmlab/mmpose/blob/228747c298c0801dea093371abeca539d41a7584/mmpose/apis/train.py#L180

**Comment by igodogi** [comment]
Is it better set the default cfg of val_dataloader as the loader_cfg from the global cfg.data?
https://github.com/open-mmlab/mmpose/blob/228747c298c0801dea093371abeca539d41a7584/mmpose/apis/train.py#L81-L104
