### ISSUE TITLE
About change Gray image have some problems.

### ISSUE THREAD

**Issue by NeekHua** [open-mmlab/mmpose#1093]
I want use gray image retrain hand pose estimation some models.And want through copy channel single channel expand three channel.I read config py file ,and know train_pipeline have  data preprocess methd,I want to know whether have method in mmpose frame.
Any response with suggestions is to be expected!

**Comment by jin-s13** [comment]
Currently, we do not have a specific pipeline for training models with gray images as the input. 
By default, opencv reads gray images as 3-channel images does not it? So maybe you can try to use the common RGB pipeline for your training, possibly with some small modifications to `NormalizeTensor` (the mean and std are for RGB images).

**Comment by NeekHua** [comment]
@jin-s13 ok,I get it .Thanks your reply.

**Comment by NeekHua** [comment]
@jin-s13 I have another question.It is that whether have mmpose frame supported data prepocess file?I haven't find it.If have,hope share with me.Thanks a lot.

**Comment by NeekHua** [comment]
@jin-s13 I have another question.It is whether have introduce mmpose frame included data preprocess methods document.If have,hope share with me.Thx a lot

**Comment by NeekHua** [comment]
I got it https://github.com/open-mmlab/mmpose/blob/master/docs/en/tutorials/3_data_pipeline.md
