### ISSUE TITLE
请问把自己的数据集制作成coco关键点数据格式？

### ISSUE THREAD

**Issue by Dandelion111** [open-mmlab/mmpose#1095]

**Comment by jin-s13** [comment]
Please refer to https://github.com/open-mmlab/mmpose/blob/master/tools/dataset/parse_macaquepose_dataset.py

**Comment by Dandelion111** [comment]
> Please refer to https://github.com/open-mmlab/mmpose/blob/master/tools/dataset/parse_macaquepose_dataset.py

谢谢，请问一下“skeleton”这个东西必须要有吗？这个在训练的时候有用吗？

**Comment by jin-s13** [comment]
skeleton 不需要有，这个原本是为了可视化用的。
最近mmpose更新了，改用  https://github.com/open-mmlab/mmpose/tree/master/configs/_base_/datasets ，你需要为你的数据集加一个 数据集config

**Comment by Dandelion111** [comment]
> skeleton 不需要有，这个原本是为了可视化用的。 最近mmpose更新了，改用 https://github.com/open-mmlab/mmpose/tree/master/configs/_base_/datasets ，你需要为你的数据集加一个 数据集config

谢谢大佬
