### ISSUE TITLE
关于用aic格式的模型做demo的时候出现奇怪的可视化的过程出现box框之外的关键点。

### ISSUE THREAD

**Issue by APeiZou** [open-mmlab/mmpose#1097]
关于用aic格式的模型做demo的时候出现奇怪的可视化的过程出现box框之外的关键点。
![vis_610](https://user-images.githubusercontent.com/49524647/147180110-bb168807-56d0-421e-b634-a9de49000619.jpg)
demo执行以下命令，输入的json为coco的原始验证集上的coco文件

python3 demo/top_down_img_demo.py \
        configs/hrnet_w32_aic_256x192.py   \
        work_dirs/epoch_100.pth  \
        --img-root data/coco/val2017 --json-file  data/coco/annotations/person_keypoints_val2017.json \
        --out-img-root vis_results_14kp

**Comment by APeiZou** [comment]
@ly015 , 哈喽， 您好，关于上面的问题，您知道是怎么导致的吗？

**Comment by jin-s13** [comment]
Please refer to https://github.com/open-mmlab/mmpose/issues/665

**Comment by jin-s13** [comment]
由于mmpose没有直接把bbox crop下来，而是计算 center，scale 再进行crop （h：w=4:3），所以是有可能把框外的图片包含进来的。尤其是当框是比较宽的情况（w>h），要扩充成 h:w = 4：3.

如果不想要框外的点，最简单的方法是加一个后处理，把框外的点删掉。
