### ISSUE TITLE
benchmark

### ISSUE THREAD

**Issue by leoxiaobin** [open-mmlab/mmpose#11]
A very nice work!

I have some questions about the [benchmark](https://github.com/open-mmlab/mmpose/blob/master/docs/benchmark.md).

1.  In the benchmark table, I found that with the same input size, all the models of res50, 101, 152, hrnet-w32, and hrnet-w48 have almost the same speed. However, all these models have different GFLOPs. Could you explain why this happens?
2. Comparing with the implementation of  HRNet, the training speed of hrnet serious backbone has a big improvement. Could you provide more details about where the improvement comes from?

Another suggestion about the benchmark. Maybe you can consider also provide the inference speed.

**Comment by innerlee** [comment]
For the first question,

* GFLOPs does not necessarily linearly corresponds to speed. Parallelism, IO, pre-processing, CPU-GPU data transfer, GPUs communication, all affect the speed.

**Comment by leoxiaobin** [comment]
@innerlee , thx for your reply. I know that GFLOPs does not necessarily linearly corresponds to speed. In the table, res50 and res152 have almost the same speed (1.10 s/iter vs 1.11 s/iter).  However, the GFLOPs of res50 is 3.8 GFLOPs, and res152 is 11.3 GLOPs. The GFLOPs of res152 is almost 3 times larger than res50. It is a little wired, that they have the same training speed.

According to these results, is it means that when training res50, there is a bottleneck in parallelism, IO, pre-processing, and et al?

**Comment by innerlee** [comment]
Yea it seems like the case. We will diagnose if there are issues with IO. @Canwang-sjtu will share more details later

**Comment by innerlee** [comment]
We double checked the benchmark environment and identified that the disk IO is the bottleneck. We will resolve the IO issue and update the benchmark shortly
