### ISSUE TITLE
Add SmoothNet 

### ISSUE THREAD

**Issue by ailingzengzzz** [open-mmlab/mmpose#1117]
**Describe the feature**
Smoothing the outputs of existing 2d/3d pose backbones. 
SmoothNet is a plug-and-play network for refining human poses in videos.

**Motivation**
When analyzing human motion videos, the output jitters from existing pose estimators are highly-unbalanced. Most frames only suffer from slight jitters, while significant jitters occur in those frames with occlusion or poor image quality. Such complex poses often persist in videos, leading to consecutive frames with poor estimation results and large jitters. Existing pose smoothing solutions based on temporal convolutional networks, recurrent neural networks, or lowpass filters cannot deal with such a long-term jitter problem without considering the significant and persistent errors within the jittering video segment.

**Related resources**

https://ailingzeng.site/smoothnet
https://arxiv.org/pdf/2112.13715.pdf

**TODO**

1. 3D pose estimation (Human3.6M)
2. 2D pose estimation (Posetrack)

**Comment by ly015** [comment]
Finished in #1274
