### ISSUE TITLE
Do I need to change the cfg_channel

### ISSUE THREAD

**Issue by zzz731621** [open-mmlab/mmpose#1118]
If I use my own data, do I need to change channel_cfg or somewhere else?

Because I only modify coco's annotations file, the program can also run.

I remember having to change flip_pairs and other parts before

But I recently came back to see the program seems to have some changes

**Comment by jin-s13** [comment]
The definition of the dataset is now in https://github.com/open-mmlab/mmpose/blob/master/configs/_base_/datasets/coco.py

**Comment by jin-s13** [comment]
You may need to add a new base config for your customized dataset.

**Comment by jin-s13** [comment]
Yes, you also need to change channel_cfg.

**Comment by zzz731621** [comment]
appreciated.
