### ISSUE TITLE
onehand10k vis results?

### ISSUE THREAD

**Issue by pablovela5620** [open-mmlab/mmpose#112]
Looking at the viz_pose_results funciton used in topdown image demo it looks like this is specifically for 17 keypoint pose estimation. Is there another function that needs to be used to visualize hand poses or is this not implemented yet?

**Comment by jin-s13** [comment]
Yes. Currently, the `vis_pose_result` function only supports COCO 17-kpt models. 
To visualize the hand poses, one should define the `skeleton` (which keypoints should be linked together) & pose_limb_color & pose_kpt_color.

**Comment by pablovela5620** [comment]
Great thanks, saw you just pushed a new commit to solve this. Appreciate it!
