### ISSUE TITLE
about config load_from and resume_from parameter

### ISSUE THREAD

**Issue by NeekHua** [open-mmlab/mmpose#1122]
In config file,load_from and resume_from parameter.How are two parameters used?

**Comment by jin-s13** [comment]
Please check https://github.com/open-mmlab/mmpose/blob/93c3a742c540dfb4ca515ad545cef705a07d90b4/docs/en/getting_started.md

Difference between resume-from and load-from: resume-from loads both the model weights and optimizer status, and the epoch is also inherited from the specified checkpoint. It is usually used for resuming the training process that is interrupted accidentally. load-from only loads the model weights and the training epoch starts from 0. It is usually used for finetuning.

**Comment by NeekHua** [comment]
@jin-s13 I see. Thank you very much for your reply
