### ISSUE TITLE
每个数据集的sigmas是如何计算出来的？

### ISSUE THREAD

**Issue by APeiZou** [open-mmlab/mmpose#1123]
每个数据集的sigmas是如何计算出来的？
sigmas=[
        0.026, 0.025, 0.025, 0.035, 0.035, 0.079, 0.079, 0.072, 0.072, 0.062,
        0.062, 0.107, 0.107, 0.087, 0.087, 0.089, 0.089]

**Comment by APeiZou** [comment]
@jin-s13

**Comment by jin-s13** [comment]
The following section is copied from [mscoco dataset](https://cocodataset.org/#keypoints-eval).

We tune the κi such that the OKS is a perceptually meaningful and easy to interpret similarity measure. First, using 5000 redundantly annotated images in val, for each keypoint type i we measured the per-keypoint standard deviation σi with respect to object scale s. That is we compute σi2=E[di2/s2]. σi varies substantially for different keypoints: keypoints on a person's body (shoulders, knees, hips, etc.) tend to have a σ much larger than on a person's head (eyes, nose, ears).

**Comment by APeiZou** [comment]
有计算自定义数据集的sigma的代码吗？@jin-s13

**Comment by jin-s13** [comment]
可以根据定义，简单实现下。大概是同一个点，请不同标注员来标；计算标准差，再除scale归一化。具体细节可以看mscoco的paper定义。

**Comment by EbenezerO** [comment]
> 可以根据定义，简单实现下。大概是同一个点，请不同标注员来标；计算标准差，再除scale归一化。具体细节可以看mscoco的paper定义。

是这篇 《Microsoft COCO: Common Objects in Context》吗？没有找到这块的计算细节
