### ISSUE TITLE
How is the results['scale'] generated?

### ISSUE THREAD

**Issue by zzz731621** [open-mmlab/mmpose#1128]
How is the results['scale'] generated?
I check the value in the program is 1.19375 and it is annotated with the scale of bbox
I don't quite understand what it means

**Comment by ly015** [comment]
It is firstly generated in the dataset (e.g. [here](https://github.com/open-mmlab/mmpose/blob/0376d51efdd93b3c8f3338211130753fed808bb9/mmpose/datasets/datasets/top_down/topdown_coco_dataset.py#L164)) when converting the bbox format from `xyhw` to `center + scale`. This is mainly for efficient preprocessing and augmentation in data pipelines.

**Comment by zzz731621** [comment]
appreciated!!
