### ISSUE TITLE
How to make Human pose 3d demo run for live camera or webcom?

### ISSUE THREAD

**Issue by chandelarvind** [open-mmlab/mmpose#1129]
I want to run it on live rtsp cam link or webcom so how to get it done?

**Comment by ly015** [comment]
For now, our [webcam demo](https://github.com/open-mmlab/mmpose/blob/master/demo/webcam_demo.py) only supports 2D models, while [body3d_two_stage_video_demo.py](https://github.com/open-mmlab/mmpose/blob/master/demo/body3d_two_stage_video_demo.py) gives an example of 3D pose inference from consecutive video frames. You may consider adding the 2D-to-3D pose inference part to `webcam_demo.py` following `body3d_two_stage_video_demo.py`.

**Comment by chandelarvind** [comment]
sure, will try. Thanks a lot.
