### ISSUE TITLE
segmentation label

### ISSUE THREAD

**Issue by alicera** [open-mmlab/mmpose#1134]
If I want to train my custom, what do I need to label info ?

I know human pose need to label the keypoint and person box.
Does it must be have the  segmentation for training?

![image](https://user-images.githubusercontent.com/59388989/149064998-1475b2f0-dd97-4bb2-9cbf-c82cbdd5cd60.png)

image ref:
https://www.v7labs.com/blog/human-pose-estimation-guide

**Comment by jin-s13** [comment]
We do not need segmentation labels. 
Please refer to https://github.com/open-mmlab/mmpose/blob/master/docs/en/faq.md for more details.

**Comment by alicera** [comment]
Thks.
