### ISSUE TITLE
Test error in MPII

### ISSUE THREAD

**Issue by imsotable** [open-mmlab/mmpose#1137]
Hello! I trained Lite HRNet on MPII,I meet a similar question as #300  but still can't sovle it, I can train it but when I evaluate the model，error occurs. I’d really appreciate it if you could help me
**ValueError: operands could not be broadcast together with shapes (16,2,2) (16,2,2958)**

I run
**python ./tools/test.py /home/sxy/lite-HRNet/lite-hrnet/configs/top_down/lite_hrnet/mpii/litehrnet_18_mpii_256x256.py \/home/sxy/lite-HRNet/lite-hrnet/work_dirs/epoch_170.pth \--eval PCKh

/home/sxy/anaconda3/envs/deeplearning/lib/python3.7/site-packages/mmpose/models/registry.py:13: DeprecationWarning: Registries (BACKBONES, NECKS, HEADS, LOSSES, POSENETS) have been moved to mmpose.models.builder. Importing from mmpose.models.registry will be deprecated in the future.
  DeprecationWarning)
=> num_images: 2
=> load 2 samples
/home/sxy/anaconda3/envs/deeplearning/lib/python3.7/site-packages/mmpose/models/detectors/top_down.py:65: DeprecationWarning: `loss_pose` for TopDown is deprecated, use `loss_keypoint` for heads instead. See https://github.com/open-mmlab/mmpose/pull/382 for more information.
  ' for more information.', DeprecationWarning)
Use load_from_local loader
[                                                  ] 0/2, elapsed: 0s, ETA:/home/sxy/anaconda3/envs/deeplearning/lib/python3.7/site-packages/mmpose/core/evaluation/top_down_eval.py:553: DeprecationWarning: post_process=True, unbiased=False is deprecated, please use post_process='default' instead
  DeprecationWarning)
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 2/2, 2.1 task/s, elapsed: 1s, ETA:     0s/home/sxy/anaconda3/envs/deeplearning/lib/python3.7/site-packages/scipy/io/matlab/mio5.py:809: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  self.file_stream.write(hdr.tostring())
Traceback (most recent call last):
  File "./tools/test.py", line 145, in <module>
    main()
  File "./tools/test.py", line 141, in main
    print(dataset.evaluate(outputs, args.work_dir, **eval_config))
  File "/home/sxy/anaconda3/envs/deeplearning/lib/python3.7/site-packages/mmpose/datasets/datasets/top_down/topdown_mpii_dataset.py", line 214, in evaluate
    uv_error = pos_pred_src - pos_gt_src
ValueError: operands could not be broadcast together with shapes (16,2,2) (16,2,2958) **

**Comment by liqikai9** [comment]
Thanks for your error report and we appreciate it a lot. But we still need more information to locate the problem, so could you please offer us the following information?

- What config did you run?
- Did you make any modifications on the code or config? If you use your own config, could you attach it here?

**About the environment**

- Please run `PYTHONPATH=${PWD}:$PYTHONPATH python mmpose/utils/collect_env.py` to collect necessary environment information and paste it here.

**Comment by imsotable** [comment]
Thank you for your attention！
I run **litehrnet_18_mpii_256x256.py**
I just change the learning rate in the config, and add a CBAM in the backbone of litehrnet(the size of the output do not change) 
my environment:
TorchVision: 0.8.0
OpenCV: 4.2.0
MMCV: 1.3.16
MMCV Compiler: GCC 5.5
MMCV CUDA Compiler: 11.0
MMPose: 0.20.0+

**Comment by jin-s13** [comment]
Have you tried the official config & models on MPII?

**Comment by imsotable** [comment]
Oh thank you! The problem has been solved,  there is something wrong with my dataset.
