### ISSUE TITLE
How can I obtain the mAP indicator value of every keypoint seperately, instead of the total mAP of all keypoints ?

### ISSUE THREAD

**Issue by August0424** [open-mmlab/mmpose#1138]

**Comment by jin-s13** [comment]
Maybe you have to modify the [xtcocotools](https://github.com/jin-s13/xtcocoapi)

**Comment by August0424** [comment]
> Maybe you have to modify the [xtcocotools](https://github.com/jin-s13/xtcocoapi)

Could you please, if possible, share me a couple of related projects where maybe some others had already made similar efforts? I haven't found such avaiable resource up to now.

**Comment by jin-s13** [comment]
Maybe [this](https://github.com/matteorr/coco-analyze) works.
