### ISSUE TITLE
updown

### ISSUE THREAD

**Issue by alicera** [open-mmlab/mmpose#1142]
Updown the person is the good method ?
I have tried the case that the face with landmark doesn't fit the updown method. 
But the general object detections have the updown or right-left data augmentation.

![image](https://user-images.githubusercontent.com/59388989/149609642-6ad62b40-752b-41c5-89ec-9a34d7aabe0b.png)

**Comment by jin-s13** [comment]
It depends. If your dataset (especially test set) contains some people standing upside-down, this may be useful.

**Comment by alicera** [comment]
Where are the code

**Comment by jin-s13** [comment]
It is not available now. But I think you can easily implement it yourself ：）

**Comment by alicera** [comment]
I will do my best
