### ISSUE TITLE
[WebcamAPI] Resources for WebcamAPI

### ISSUE THREAD

**Issue by liqikai9** [open-mmlab/mmpose#1144]
Here, we can add all the needed fancy resources for WebcamAPI, including pictures and demo gifs.
You can upload other resources in the comments and get the link for images or gifs in the docs.

**Comment by jin-s13** [comment]
![background](https://user-images.githubusercontent.com/11788150/149731957-abd5c908-9c7f-45b2-b7bf-821ab30c6a3e.jpg)

**Comment by liqikai9** [comment]
The red heart and elkhorn image, and demo gif for webcam matchstick man and elkhorn effect. See #1091 

![heart](https://user-images.githubusercontent.com/87690686/149731850-ea946766-a4e8-4efa-82f5-e2f0515db8ae.png)

![elk_horn](https://user-images.githubusercontent.com/87690686/149731877-1a7ff0f3-fc5a-4fd5-b330-7f35e2930f02.jpg)


![webcam_matchstickman_elk_horn mp4](https://user-images.githubusercontent.com/87690686/149731547-7488bd89-3e35-4f76-be1c-8623b3b7d52f.gif)

**Comment by jin-s13** [comment]
https://user-images.githubusercontent.com/11788150/149732080-ea6cfeda-0dc5-4bbb-892a-3831e5580520.mp4

**Comment by jin-s13** [comment]
![saiyan](https://user-images.githubusercontent.com/11788150/149732117-fcd2d804-dc2c-426c-bee7-94be6146e05c.png)

**Comment by jin-s13** [comment]
![moustache](https://user-images.githubusercontent.com/11788150/149732141-3afbab55-252a-428c-b6d8-0e352f432651.jpeg)

**Comment by zengwang430521** [comment]
![hat](https://user-images.githubusercontent.com/28900607/149766271-2f591c19-9b67-4d92-8f94-c272396ca141.png)
![firecracker](https://user-images.githubusercontent.com/28900607/149766281-6376055c-ed8b-472b-991f-60e6ae6ee1da.gif)

**Comment by mzr1996** [comment]
![touhou](https://user-images.githubusercontent.com/26739999/151532276-33f968d9-917f-45e3-8a99-ebde60be83bb.png)

**Comment by ly015** [comment]
bing_dwen_dwen1.jpg
![bing_dwen_dwen1](https://user-images.githubusercontent.com/15977946/152742677-35fe8a01-bd06-4a12-a02e-949e7d71f28a.jpg)

bing_dwen_dwen2.jpg
![bing_dwen_dwen2](https://user-images.githubusercontent.com/15977946/152742707-c0c51844-e1d0-42d0-9a12-e369002e082f.jpg)

bing_dwen_dwen3.jpg
![bing_dwen_dwen3](https://user-images.githubusercontent.com/15977946/152742728-99392ecf-8f5c-46cf-b5c4-fe7fb6b39976.jpg)

bing_dwen_dwen4.jpg
![bing_dwen_dwen4](https://user-images.githubusercontent.com/15977946/152742755-9dc75f89-4156-4103-9c6d-f35f1f409d11.jpg)

**Comment by liqikai9** [comment]
flying-heart.png
![flying-heart](https://user-images.githubusercontent.com/87690686/153554948-937ce496-33dd-49ab-9829-0433fd7c13c4.png)

**Comment by ly015** [comment]
Resource video for horse pose estimation (original video: https://www.youtube.com/watch?v=WnRZKBIfcPc&ab_channel=CittaslowInternational)

https://user-images.githubusercontent.com/15977946/173124855-c626835e-1863-4003-8184-315bc0b7b561.mp4

Result:

**Comment by ly015** [comment]
![vis_horse](https://user-images.githubusercontent.com/15977946/173134365-ac48bf1d-ea64-4305-9811-07b2b6dcb826.gif)

**Comment by ly015** [comment]
Monkey (Original video: https://www.youtube.com/watch?v=otrAElbSJfs)

https://user-images.githubusercontent.com/15977946/173135633-1c54a944-4f01-4747-8c2e-55b8c83be533.mp4

Result:

![vis_173135633-1c54a944-4f01-4747-8c2e-55b8c83be533](https://user-images.githubusercontent.com/15977946/173139730-32ce89a0-9a09-4f07-b39f-8e794a8b2630.gif)
