### ISSUE TITLE
关于数据集标注的相关问题

### ISSUE THREAD

**Issue by ShaneCan** [open-mmlab/mmpose#1150]
mmpose团队的大神好，本人想请教一下对于被遮挡关键点的标注问题：
       jin-s13大神您之前提到可以标为(x,y,1)，请问这个坐标的意思是说可以直接脑补一个被遮挡关键点的位置标注上去？此外还提到了可以标注为(0,0,0),本人所使用的是labelme软件，并不知道如何才能实现这样的操作？或者是labelbee软件可以实现此类标注？亦或者是标注完可见点后 转换为coco格式后再在文本文件内修改？恳请您的回答，感谢！

**Comment by ShaneCan** [comment]
还想请问在训练过后检测关键点时能否显示关键点的坐标？应如何实现？感谢大神~~~

**Comment by jin-s13** [comment]
1. _请问这个坐标的意思是说可以直接脑补一个被遮挡关键点的位置标注上去？_
是的。可以脑补点的位置

2. _此外还提到了可以标注为(0,0,0),_

标注为(0,0,0)的意思是可以跳过这个点。

3. _本人所使用的是labelme软件，并不知道如何才能实现这样的操作？或者是labelbee软件可以实现此类标注？亦或者是标注完可见点后 转换为coco格式后再在文本文件内修改？_

我对这些标注工具不太熟悉。标注完成后，用脚本来处理吧。

4. _请问在训练过后检测关键点时能否显示关键点的坐标？_

你可能需要修改下可视化代码。https://github.com/open-mmlab/mmpose/blob/e22b871f0675cdfdc35e0385db13dbfd4a9f1bcf/mmpose/apis/inference.py#L833

**Comment by ShaneCan** [comment]
太感谢jin-s13大神了！！！！
可视化代码我只需要修改img=model.show_result这个函数吗？能更加具体一些吗？麻烦您了我是纯纯的小白hhhh，再次感谢大神的耐心解答，衷心祝愿mmpose越来越牛

**Comment by jin-s13** [comment]
https://github.com/open-mmlab/mmpose/blob/e22b871f0675cdfdc35e0385db13dbfd4a9f1bcf/mmpose/core/visualization/image.py#L149

在这个前面 加一个 cv2.putText() 放需要展示的关键点坐标吧

**Comment by ShaneCan** [comment]
再次感谢jins13大神！！！
