### ISSUE TITLE
Questions about why 200?

### ISSUE THREAD

**Issue by jinfagang** [open-mmlab/mmpose#1158]
at this line code: https://github.com/open-mmlab/mmpose/blob/dca589a0388530d4e387d1200744ad35dd30768d/mmpose/core/post_processing/post_transforms.py#L181

it was using 200 convert back, but why using 200? why not 224?

**Comment by jin-s13** [comment]
It follows the definition of the MPII dataset

**Comment by jinfagang** [comment]
what difinition?

**Comment by ly015** [comment]
See `scale` in http://human-pose.mpi-inf.mpg.de/#download

**Comment by jinfagang** [comment]
thanks, does the wdith also scaled?
