### ISSUE TITLE
Data preparation for inference using VoxelPose

### ISSUE THREAD

**Issue by KulkarniKaustubh** [open-mmlab/mmpose#1166]
Hey, I was looking to use VoxelPose for inference of 3D pose estimation using two camera feeds. The README at https://github.com/open-mmlab/mmpose/tree/master/configs/body/3d_kpt_mview_rgb_img contains a link to data preparation and this link seems to be invalid.

Where can I find the right way to prepare my data and is a 2 camera stream supported by mmpose?

Thanks.

**Comment by wusize** [comment]
Hi! I have fixed the incorrect path in the docs (see this [branch](https://github.com/open-mmlab/mmpose/tree/voxelpose_doc)). For the 2-camera setting, modify L46~L47 in the [cfg](https://github.com/open-mmlab/mmpose/blob/voxelpose_doc/configs/body/3d_kpt_mview_rgb_img/voxelpose/panoptic/voxelpose_prn64x64x64_cpn80x80x20_panoptic_cam5.py).

**Comment by KulkarniKaustubh** [comment]
Thank you! I am sorry I am not able to understand the data preparation steps and I have some questions. I have two cameras recording at the same time. I have images as well as videos recorded from both perspectives. To run inference and get 3D coordinates using VoxelPose, what exactly must the structure be in `$MMPOSE/data`?

Thank you once again for updating the docs.

**Comment by wusize** [comment]
L46 chooses the panel id and node id of the cameras in CMU panoptic dataset. You can refer to the dataset [website](http://domedb.perception.cs.cmu.edu/) and their [github](https://github.com/CMU-Perceptual-Computing-Lab/panoptic-toolbox) for clearer understanding of its structure.

For your own 2-camera data, I recommend customizing your own dataset by refering to the code structure of  [body3d_mview_direct_panoptic_dataset.py](https://github.com/open-mmlab/mmpose/blob/master/mmpose/datasets/datasets/body3d/body3d_mview_direct_panoptic_dataset.py).

**Comment by gokcergun** [comment]
> hi, could you figure it out? 
I have the same problem. I want to inference my own two view images using voxelpose, but I couldn't understand the required structure. 
Also, I didn't understand where we give our camera parameters for camera calibration. 
I would appreciate any help. 

Thanks

**Comment by KulkarniKaustubh** [comment]
Hey @gokcergun, no I could not quickly figure it out unfortunately. But I also have not given it a lot of time since I was busy with other things. I will definitely let you know if I am able to figure it out soon!

Meanwhile, please do let me know if you are able to do so!

**Comment by gokcergun** [comment]
> Hey @gokcergun, no I could not quickly figure it out unfortunately. But I also have not given it a lot of time since I was busy with other things. I will definitely let you know if I am able to figure it out soon!
> 
> Meanwhile, please do let me know if you are able to do so!

Great, thanks for quick reply. Sure, I will let you know if I can figure it out.
