### ISSUE TITLE
mAP results comparison based on OKS and IoU

### ISSUE THREAD

**Issue by rubeea** [open-mmlab/mmpose#1168]
Hi,
Can we compare the mAP results based on OKS COCO evaluation metrics with mAP results of another technique based on IoU of bounding boxes? Note that both the techniques use key points for detecting thin lines from images. Any help will be highly appreciated. 

Thanks in advance.

**Comment by rubeea** [comment]
Guys any help in this regard will be highly appreciated.

**Comment by jin-s13** [comment]
Sorry for the late reply. 
Let me try to understand your question. 
（1）Your use case is to detect **lines** from images. And you want to use mmpose to achieve this. So a line is represented by  two end points, right?
（2）You also use object detection for this task. And a line is represented by a bounding box, closely bounding these two end points, right? 
（3）You want to compare these two techniques, using the same metric. 

If my understanding is correct, I will suggest you to make the two techniques have the same type of output. 
For example, you may use technique1 to detect keypoints. You may also use post-processing to convert keypoints into bounding boxes. So this way you can easily compare the accuracy of bounding boxes of technique1 and technique2.
