### ISSUE TITLE
Is videopose3d use root-relative estimation?

### ISSUE THREAD

**Issue by fang-h** [open-mmlab/mmpose#1174]
In videopose3d config,train_pipeline contain 'GetRootCenteredPose' transform,but not remove root joint, target at root_index is （0， 0， 0），so model is to predict (0, 0, 0)?

**Comment by ly015** [comment]
Yes, that is correct. We follow the practice in the official code.

**Comment by fang-h** [comment]
So why the parameter 'remove_root’ is False  in 'GetRootCenteredPose' transform? This means model predict the root-joint but actually don't use it?
