### ISSUE TITLE
Mistake in one_euro_filter.py

### ISSUE THREAD

**Issue by pallgeuer** [open-mmlab/mmpose#1176]
I am using the API call `mmpose.apis.get_track_id` to perform tracking on the results of a top-down 2D keypoint pose model. I enabled filtering using `use_one_euro=True` and was surprised by there being almost no visible difference. After debugging this issue I noticed that the smoothing factor is incorrectly calculated for the One Euro Filter.

In the implementation, the function `smoothing_factor` (line 10 in `one_euro_filter.py`) is called twice, once with `self.d_cutoff` (which should be the 'input data fps', thus a frequency in Hz) and once with `cutoff` (same units as `self.min_cutoff`, which I assume should thus also be Hz).

The calculation of the smoothing factor according to the One Euro Filter paper is `alpha = 1 / (1 + tau / Te)`.

In the code, `t_e` is in units of frames, and is thus almost always 1. Thus `tau` should be expressed also in units of frames in order for the calculation to be correct, which would be `tau = fps / (2 * pi * fc)`. Thus, the `smoothing_factor` function should return:
```
alpha = 1 / (1 + tau / Te)
      = 1 / (1 + fps / (2 * pi * fc * Te))
      = r / (r + fps) for r = 2 * pi * fc * Te
```
Line 11 calculates exactly this r already:
```
r = 2 * np.pi * cutoff * t_e
```
So to fix the mistake, only line 12 (`return r / (r + 1)`) would need to be modified to return `r / (r + fps)`. Alternatively, the value of `cutoff` or `t_e` passed to all calls of `smoothing_factor` could be divided by `fps`. Either way.

**Comment by ly015** [comment]
Thank you very much for reporting this issue with such a detailed explanation. It helps a lot.

BTW, would you be interested in opening a pull request to fix this bug? (Of course, if you are not interested, we will fix it asap) It would be just great for this project to have more contributors from the community.

**Comment by pallgeuer** [comment]
I had a look at the code and I'm not sure how to best fix it so that it works for everyone, because somehow the fps are sometimes taken from `fps` and sometimes from `d_cutoff`, but what happens if you want a `d_cutoff` different than the fps? The current arguments are a little misleading, even if there is a comment in the source code to the effect that `d_cutoff` should actually be the fps, despite `fps` also being an argument. I think the whole thing needs a bit of a redesign, and that's more than I'm confident doing as an outsider.

Sorry for the weird notation (this was actually just notes I made to myself about what I changed), but this is what I changed so that at least it works right for me now:
```
After: self.skip_frame_factor = d_cutoff
Add:   self.fps = d_cutoff
After: self.d_cutoff = np.full(x0.shape, float(fps))
Add:   self.fps = float(fps)
Change: a_d = smoothing_factor(t_e, self.d_cutoff)
To:     a_d = smoothing_factor(t_e / self.fps, self.d_cutoff)
Change: a = smoothing_factor(t_e, cutoff)
To:     a = smoothing_factor(t_e / self.fps, cutoff)
```

**Comment by ly015** [comment]
Thank you very much. We will fix it following your suggestions. If you don't mind, we will inform you here once the PR is ready to review and it would be great if you can leave some comments on the PR.

**Comment by pallgeuer** [comment]
Yes, sure

**Comment by ly015** [comment]
@pallgeuer We have modified the OneEuro implementation in #1127 following your suggestions. Would you mind taking a look at the fix? 

This PR involves some interface refactoring, so you may want to go straight to:
- New version: https://github.com/open-mmlab/mmpose/pull/1127/files#diff-bc3bb0a7ce0b88b886375d53cb74fc3bcc5f035ec82685900129de20bb5e6922
- Old version (retained for compatibility, will be deprecated in the future): https://github.com/open-mmlab/mmpose/pull/1127/files#diff-bc3bb0a7ce0b88b886375d53cb74fc3bcc5f035ec82685900129de20bb5e6922

Thank you very much.

**Comment by pallgeuer** [comment]
I haven't cloned and executed the new code, but the fixed old version of the one euro filter looks definitely correct now to me.

In terms of the new implementation, there are a few things that I'm not so sure about yet. For instance that the time passed to `smoothing_factor` seems to be in units of either frames or seconds, or is it always supposed to be relative to frame index even if manually specified? Also, the new default `min_cutoff` value seems to suggest that the cutoff frequency is now not supposed to be expressed in Hz anymore, but relative to frame index? There is also no way to pass a custom `d_cutoff` to the underlying implementation (I don't think 1.0 will necessarily be optimal in enough cases).

It would help a lot if documentation was added to the `OneEuro` and `OneEuroFilter` classes about what exact units the inputs should be in, and not just whether increasing or decreasing them should have a particular effect.

I would also recommend coding a test that verifies that the output of the old and new versions are identical. That would vastly increase the certainty about the new implementation, and is better than anyone looking at the code and saying yes or no.

**Comment by ly015** [comment]
@pallgeuer Thank you very much for your suggestions. We will verify the output of the new version OneEuroFilter, and rethink the design of the interface. And the documents and unit tests will also be refined in the next release.

Thanks again for your help. Please stay tuned for our updates.
