### ISSUE TITLE
jhmdb topdown heatmap models do not work

### ISSUE THREAD

**Issue by pallgeuer** [open-mmlab/mmpose#1186]
The jhmdb topdown heatmap models raise a `KeyError` for `bbox` when inferencing them the standard way. These ones:
https://github.com/open-mmlab/mmpose/tree/master/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/jhmdb

The problem seems to be that their pipelines try to collect the meta key `bbox`, which should rather be `bbox_score`. After changing that the models work for me as expected.

I made the changes that fixed it for me using:
```
find configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/jhmdb -maxdepth 1 -type f -name "*.py" -print0 | xargs -0 sed -i "s/'bbox'/'bbox_score'/g"
```
Just a simple find-replace operation...

**Comment by ly015** [comment]
Thanks for the feedback. We will fix it asap.

**Comment by ly015** [comment]
@jin-s13 Could you please help take a look at this issue?

**Comment by jin-s13** [comment]
Yes, this is a bug. I will fix it.
