### ISSUE TITLE
How to get result data rather than image after infer?

### ISSUE THREAD

**Issue by zhouhang95** [open-mmlab/mmpose#119]
在推断完成后，该如何拿到处理后的结果数据，而不仅仅是一张图片？

**Comment by innerlee** [comment]
Hi! could you be more specific? 

* which script is used
* which config is used 
* what kind of result are expected, and any concrete examples?

**Comment by zhouhang95** [comment]
I want to use it as the repalcement of OpenPose, get the same format result.

我想把他当作OpenPose的代替品，希望能拿到跟OpenPose处理后相同格式的结果。

**Comment by jin-s13** [comment]
Take `mmpose/demo/top_down_img_demo.py` for example, you can just save `pose_results (line72)` to a json file.
For val/testing, the results will be saved in the work_dirs. Please check that.

**Comment by zhouhang95** [comment]
Thank you!

**Comment by innerlee** [comment]
maybe we can support this output format in the demo script?
