### ISSUE TITLE
Error calculating flops

### ISSUE THREAD

**Issue by lawo123** [open-mmlab/mmpose#1190]
/tools/analysis/get_flops.py refer to https://github.com/sovrasov/flops-counter.pytorch ,which is calculating MACs.FLOPs=2*MACs.
The result of  FLOPs is wrong.

**Comment by jin-s13** [comment]
Most papers (including the well-known ResNet paper)/toolboxes do not differentiate MACs and FLOPs. I think it is a common practice...

**Comment by lawo123** [comment]
Thank you very much for your reply, I understand.
