### ISSUE TITLE
How to train backbone for Voxelpose

### ISSUE THREAD

**Issue by wuyuuu** [open-mmlab/mmpose#1192]
Hi there,

First thanks for your great work!

Recently I'm using your work voxelpose. I found that a pretrained resnet with 15-heatmap output was used.

However, as I read in [voxelpose paper](https://www.ecva.net/papers/eccv_2020/papers_ECCV/papers/123460188.pdf), the 2D detector was trained on COCO which contains 17 keypoints.

So I wonder how could I trained a backbone for voxelpose?

Thanks!

**Comment by jin-s13** [comment]
MMPose has provided a lot of 2D detectors, e.g. https://github.com/open-mmlab/mmpose/blob/master/configs/body/2d_kpt_sview_rgb_img/associative_embedding/coco/res50_coco_512x512.py

**Comment by wuyuuu** [comment]
> MMPose has provided a lot of 2D detectors, e.g. https://github.com/open-mmlab/mmpose/blob/master/configs/body/2d_kpt_sview_rgb_img/associative_embedding/coco/res50_coco_512x512.py

Thanks for your quick reply!

But a general COCO keypoint detector is different from the one in voxelspace.py by 1. the number of output keypoint heatmap (17 in COCO vs 15 in voxelspace) and 2. including AE output.

The AE output can be easily disabled by modifying config but what should I do to change the heatmap output?

**Comment by wusize** [comment]
The backbone voxelpose used was pre-trained on COCO and finetuned on CMU panoptic. For finetuning, you can manually modify the parameters of the last layer of the pre-trained model or directly load it by specifying **load-from='path/of/your/pre-trained/model'** in the config. In the latter case, the parameters of the last layer will be discarded.

You can also directly use the model trained on COCO by manually modifying the model parameters.

**Comment by wuyuuu** [comment]
> The backbone voxelpose used was pre-trained on COCO and finetuned on CMU panoptic. For finetuning, you can manually modify the parameters of the last layer of the pre-trained model or directly load it by specifying **load-from='path/of/your/pre-trained/model'** in the config. In the latter case, the parameters of the last layer will be discarded.
> 
> You can also directly use the model trained on COCO by manually modifying the model parameters.

Thanks for your advice. I'll try it!
