### ISSUE TITLE
What's wrong with H36m case?

### ISSUE THREAD

**Issue by denred0** [open-mmlab/mmpose#1198]
**Checklist**

1. I have searched related issues but cannot get the expected help.
1. The bug has not been fixed in the latest version.

**Describe the bug**

I want to get 3d keypoints for person but configs+weights for h36m dataset return incorrect keypoints. I decided to get a right results for keypoints and then try 3d keypoints. 
I run a demo example mmpose/demo/top_down_img_demo_with_mmdet.py for h36m dataset and got strange results. I especially created a new clear project and installed mmpose and mmdetection. 

**Reproduction**

```
python mmpose/demo/top_down_img_demo_with_mmdet.py \
mmdetection/configs/cascade_rcnn/cascade_mask_rcnn_r50_fpn_1x_coco.py \
weights/mmdet/cascade_mask_rcnn_r50_fpn_1x_coco_20200203-9d4dcb24.pth \
mmpose/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/h36m/hrnet_w32_h36m_256x256.py \
weights/mmpose/hrnet_w32_h36m_256x256-d3206675_20210621.pth \
--img-root data/input \
--out-img-root data/output \
--img istockphoto-1124393111-612x612.jpg
```
Result - only one keypoint with a good confidence and other keypoints with very small confidence. 
![vis_istockphoto-1124393111-612x612](https://user-images.githubusercontent.com/8546089/154267011-d0f138d6-ce0a-473e-afae-b9606defb0d9.jpg)

- What config did you run?

```
# for detection
mmdetection/configs/cascade_rcnn/cascade_mask_rcnn_r50_fpn_1x_coco.py 

# for keypoints
mmpose/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/h36m/hrnet_w32_h36m_256x256.py 
```

- I didn't do any modifications in configs and script code.
- I used pretrained model for h36m dataset.

**Environment**

TorchVision: 0.11.3+cu113
OpenCV: 4.5.5
MMCV: 1.4.5
MMCV Compiler: GCC 9.3
MMCV CUDA Compiler: 11.1
MMPose: 0.23.0+

**Comment by jin-s13** [comment]
h36m is a dataset collected in the indoor laboratory environment. So the model trained on h36m may lack generalization ability and can not produce good results on the test image.

**Comment by denred0** [comment]
Yes, I know, h36m trained on Indoor persons. I tried different images and different cases but always get random results. It's strange. I am waited some results but not so bad.

**Comment by denred0** [comment]
I checked results. It looks good. 
In any case I have a problem with getting body landmarks with h36m pretrained model.

**Comment by ly015** [comment]
We have noticed that the 2D keypoint model trained on h36m data can not generalize well. For this reason, in [2-stage 3D keypoint demo](demo/body3d_two_stage_video_demo.py) we use a COCO pretrained model for the 1st stage and manually convert its output to h36m format for the 2nd stage. We would recommend using models trained on unconstrained data (e.g. COCO) instead of h36m for general purposes.

**Comment by denred0** [comment]
Thanks for your advice! I thought about this way. You can close the issue.
