### ISSUE TITLE
joint_2d_det_files share 

### ISSUE THREAD

**Issue by flynnamy** [open-mmlab/mmpose#1199]
Hi,could you please share joint_2d_det_files of videopose3d? @ly015

**Comment by ly015** [comment]
Please follow this [markdown](https://github.com/open-mmlab/mmpose/blob/master/configs/body/3d_kpt_sview_rgb_vid/video_pose_lift/h36m/videopose3d_h36m.md) to download the detection results from the CPN official repo, or download our reformatted version.
