### ISSUE TITLE
Multiple samples per GPU while testing

### ISSUE THREAD

**Issue by MaxHuerlimann** [open-mmlab/mmpose#120]
Hi everybody

Currently only one sample per GPU is possible while executing tests, which leads to very slow validation and testing for me. I assume to fix this the `forward_test` methods for the `TopDown` and `BottomUp` classes would need to be updated. Is this planned anytime soon or should I give it a try myself to contribute?

**Comment by jin-s13** [comment]
Yes. Currently, it does not support multi-sample per gpu for inference. 
Thanks for pointing out this issue. We will check this later, but it is not planned in the next version (v0.7).
It would be appreciated if you could contribute. Thank you!

**Comment by MaxHuerlimann** [comment]
Okay, I already implemented something for the `TopDown` models, will see what I can come up with for `BottomUp` when I find some time and then open a PR.
