### ISSUE TITLE
What's the difference between "image_size" and "base_size" in config

### ISSUE THREAD

**Issue by chenxinfeng4** [open-mmlab/mmpose#1201]
I saw the config file of mmpose, which like this
```
data_cfg = dict(
    image_size=512,
    base_size=256,
    base_sigma=2,
    ...
}
```
What do "image_size" and "base_size"  mean? Given an input image 800x600, what's the real feature size into the CNN?

**Comment by jin-s13** [comment]
`base_size` is used for multi-scale settings & HigherHRNet models. You may check the codes for more details.
`image_size` is the input resolution. 

> what's the real feature size into the CNN?

521
