### ISSUE TITLE
Where can metadata.xml in human 3.6m be downloaded from?

### ISSUE THREAD

**Issue by ZhangRenkai** [open-mmlab/mmpose#1202]
In this link https://github.com/open-mmlab/mmpose/blob/master/docs/en/tasks/3d_body_keypoint.md ,metadata.xml is mentioned, and I don't know where to download it and how it's used

**Comment by ly015** [comment]
It's a file you can download from Human3.6M official website, and will be used by our h36m preprocess script to extract information like camera parameters.

**Comment by ZhangRenkai** [comment]
> It's a file you can download from Human3.6M official website, and will be used by our h36m preprocess script to extract information like camera parameters.

Okay，thank you so much
