### ISSUE TITLE
fashion landmarks

### ISSUE THREAD

**Issue by maylad31** [open-mmlab/mmpose#1210]
Can you add a demo for fashion landmarks or help me how could i use the model?

**Comment by jin-s13** [comment]
You can use this demo.
https://mmpose.readthedocs.io/en/latest/demo.html#d-human-pose-top-down-image-demo

And for testing image/json, you can simply use https://github.com/open-mmlab/mmpose/tree/master/tests/data/fld

**Comment by msverma101** [comment]
can you tell me where is the model_conf file
