### ISSUE TITLE
预训练模型权重很小，训练完很大

### ISSUE THREAD

**Issue by Eatzhy** [open-mmlab/mmpose#1216]
![cab8ed8a624e4a8726f49c39ec5ad1b5](https://user-images.githubusercontent.com/32692556/156685707-a0b33779-27e0-42dc-b004-58c0382b4982.png)
![d0e5c277e78ea0e8a9fb06a8fff87a55](https://user-images.githubusercontent.com/32692556/156685717-7abf5cab-2df2-445e-a494-69d220a7e3b9.png)
第一个问题：一个图是coco预训练权重，基本都是小数。一个是训练完的权重，很多指数级别。训练过程中loss和最后的map都正常。对不同的数据集尝试了很多次训练，都是这种规律；第二个问题：用mmpose和hrnet原作者工程训练同一个数据集同一个模型配置，训练完用netron对比两个模型的权重，第一层看到的权重数值一模一样（只看了一点）。

**Comment by jin-s13** [comment]
我们modelzoo里面提供的模型，也有 训练完的权重很大 的情况吗？能不能帮忙指出来，是哪个模型有问题呢？我们后续调查下原因。

**Comment by Eatzhy** [comment]
@jin-s13 抱歉，Netron可视化模型权重软件有bug，打印出来的模型权重还是小数。
