### ISSUE TITLE
Problems on .pth file download

### ISSUE THREAD

**Issue by Zhixuan-Jing** [open-mmlab/mmpose#1218]
Hi,
I am a student using this model the first time. When I want to download the .pth file and test it, the web page crashed with error 404. Do you have any idea about it?

**Comment by jin-s13** [comment]
Which web page are you talking about? Could you please give us the link?

**Comment by Zhixuan-Jing** [comment]
I have just checked the link and found that it is in v0.8.0/getting_started.md and the link is: https://mmpose.readthedocs.io/en/latest/pretrained.html
Thanks.
