### ISSUE TITLE
Does buttom-up need 1:1 clip  before infer manually for best performance？

### ISSUE THREAD

**Issue by zhouhang95** [open-mmlab/mmpose#122]
用自底向上的方法，是否需要手工对待测试的视频裁成正方形，才能得到更好的性能？

**Comment by jin-s13** [comment]
Not really. During inference, it does not require input images to be squared (1:1 ratio).
测试时，不需要裁剪成正方形输入。
For better performance, one can choose to use multi-scale inference.
您可以使用多尺度测试的方法，来提升模型精度。
