### ISSUE TITLE
Inference using VoxelPose

### ISSUE THREAD

**Issue by gokcergun** [open-mmlab/mmpose#1222]
Hi guys, 
Thanks for the great tool. 
I want to inference with VoxelPose using my own data, but I am a bit confused. 
With which function do I need to make an inference? I couldn't find a demo code for that. Is there any? 
Also, it seems that the functions like inference_top_down_pose_model() doesn't work here. 
Any help would be appreciated.

**Comment by jin-s13** [comment]
For now, we do not have a demo code for VoxelPose. It is still in development.
