### ISSUE TITLE
Question  about InterHand2.6M annotation

### ISSUE THREAD

**Issue by dephaniehe** [open-mmlab/mmpose#1223]
Hello, the InterHand2.6M website says the structure of the annotation folder is like:
|-- annotations
|   |-- skeleton.txt
|   |-- subject.txt
|   |-- train
|   |-- val
|   |-- test
The train, val, and test folder structure is different from your doc:
|── annotations
        |   |── all
        |   |── human_annot
        |   |── machine_annot
        |   |── skeleton.txt
        |   |── subject.txt
Should I change anything in the scripts when preparing the InterHand dataset?

**Comment by ly015** [comment]
Please refer to https://github.com/open-mmlab/mmpose/blob/master/docs/en/tasks/3d_hand_keypoint.md for the preparation of the InterHand2.6M dataset.
