### ISSUE TITLE
The provided dataset is impatible with the given annotation file in the tutoring

### ISSUE THREAD

**Issue by Xinyi-Adv** [open-mmlab/mmpose#1224]
**Checklist**

1. I have searched related issues but cannot get the expected help.
1. The bug has not been fixed in the latest version.

**Describe the bug**

[tutoring file link](https://mmpose.readthedocs.io/en/latest/tasks/2d_animal_keypoint.html)

The tutoring file provides VOC2011 dataset, but gives the annotations that uses VOC2022

![image](https://user-images.githubusercontent.com/67937203/157163730-f7c2c9eb-827e-4513-8467-97edc55875b9.png)
![middle_img_v2_3826604d-abe9-4dee-9a9b-90adb9fb51ag](https://user-images.githubusercontent.com/67937203/157183342-9b8497bf-364f-4e08-85bb-2bc3b7ba47d5.png)

**Comment by jin-s13** [comment]
Thanks, we should better use the Pascal VOC2012 link.
In fact, the images of the 2012 dataset are the same as that used in 2011.
