### ISSUE TITLE
Visualization fails when joints are set hidden

### ISSUE THREAD

**Issue by womeier** [open-mmlab/mmpose#1227]
I'm using a standard COCO dataset but don't care about the eyes and ears.
So I created my custom ```_base_``` dataset_info:

According to 
https://github.com/open-mmlab/mmpose/blob/c09a6930a2e699722ec3bd6142c6ad334d32b469/mmpose/core/visualization/image.py#L126

I set color=None for the keypoints I don't want:

```
dataset_info = dict(
   ...,
    keypoint_info={
        0: dict(name="nose", id=0, color=[51, 153, 255], type="upper", swap=""),
        1: dict(name="left_eye", id=1, color=None, type="upper", swap="right_eye"),
        2: dict(name="right_eye", id=2, color=None, type="upper", swap="left_eye"),
        3: dict(name="left_ear", id=3, color=None, type="upper", swap="right_ear"),
        4: dict(name="right_ear", id=4, color=None, type="upper", swap="left_ear"),
    ...
  },

    joint_weights=[
        1.0,
        0.0,  # eyes, ears 1-4, don't matter
        0.0,
        0.0,
        0.0,
        1.0,
       ...,
    ],
)
```

This fails, because when drawing, it's not checked if the color is None.

**Comment by jin-s13** [comment]
Thanks for reporting this issue. And I notice that you have already create a PR for this. We will review it ASAP.
Thank you again!
