### ISSUE TITLE
How to use an exported HRNet onnx model with OpenCV in C++ ?

### ISSUE THREAD

**Issue by saimanoj18** [open-mmlab/mmpose#1233]
Hi all,

Is it possible to use an exported onnx hrnet keypoint detection model in opencv c++ for inference?

I have trained a keypoint detection model using hrnet backbone in top down framework. I pass the bounding boxes from a yolo v5 model as input and it works in pytorch environment. I would like to use it for inference in OpenCV using C++.

Is this possible ? Can you please point me to any existing code to follow and adapt ?

**Comment by ly015** [comment]
I think the MMDeploy community may help. You may consider raising an issue at https://github.com/open-mmlab/mmdeploy.

**Comment by jin-s13** [comment]
Temporarily closed due to inactivity.
