### ISSUE TITLE
a detection model bug in webcam demo

### ISSUE THREAD

**Issue by 674106399** [open-mmlab/mmpose#1237]
**Describe the bug**

the data type of 'CLASSES' in hand detector 'cascade_rcnn_x101_64x4d_fpn_20e_onehand10k-dac19597_20201030.pth' is wrong: it is 'hand' instead of ('hand',), which leads to an AssertError in mmdet_node.py:
> Exception in thread Detector:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\jt\lib\threading.py", line 917, in _bootst
rap_inner
    self.run()
  File "E:\project\mmpose\tools\webcam\webcam_apis\nodes\node.py", line 361, in
run
    output_msg = self.process(input_msgs)
  File "E:\project\mmpose\tools\webcam\webcam_apis\nodes\mmdet_node.py", line 52
, in process
    det_result = self._post_process(preds)
  File "E:\project\mmpose\tools\webcam\webcam_apis\nodes\mmdet_node.py", line 65
, in _post_process
    assert len(dets) == len(self.model.CLASSES)
AssertionError

**Reproduction**

I want to try webcam demo of hand pose estimation, so I modify pose_estimation.py as follow:

```
        dict(
            type='DetectorNode',
            name='Detector',
            model_config='demo/mmdetection_cfg/cascade_rcnn_x101_64x4d_fpn_1class.py',
            model_checkpoint='https://download.openmmlab.com/mmpose/mmdet_pretrained/cascade_rcnn_x101_64x4d_fpn_20e_onehand10k-dac19597_20201030.pth',
            input_buffer='_input_',  # `_input_` is a runner-reserved buffer
            output_buffer='det_result'),
        dict(
            type='TopDownPoseEstimatorNode',
            name='Human Pose Estimator',
            model_config='configs/hand/2d_kpt_sview_rgb_img/deeppose/onehand10k/res50_onehand10k_256x256.py',
            model_checkpoint='https://download.openmmlab.com/mmpose/hand/deeppose/deeppose_res50_onehand10k_256x256-cbddf43a_20210330.pth',
            cls_names=['hand'],
            input_buffer='det_result',
            output_buffer='human_pose'),
```

I run the command following instruction:

```
python tools/webcam/run_webcam.py --config tools/webcam/configs/examples/pose_estimation.py
```

**Environment**

-

**Error traceback**

-

**Bug fix**

I fix this bug via adding
```python3
if isinstance(self.model.CLASSES, str):
    self.model.CLASSES = (self.model.CLASSES, )
```
to \_\_init\_\_() of DetectorNode

I'm not sure wether this is a good solution, maybe it's better to modify 'CLASSES' in model checkpoint. But I think it is necessary to check the data type in mmpose class to improve the robustness of codes.

I'm glad to create a PR if you guys agree.

**Comment by ly015** [comment]
@674106399 Thank you very much for reporting this issue. And it would be great if you could create a PR for this. Contributions from the community are very much appreciated.

As for the solution, I think it's probably better to solve this problem in [`process_mmdet_results()`](https://github.com/open-mmlab/mmpose/blob/2f9829ed84553f9aad955e784692d56119f7cc12/demo/webcam_demo.py#L158), instead of directly override the `CLASSES` attribute of detection model, since it's part of MMDetection and overriding it may have some risks.

**Comment by 674106399** [comment]
@ly015 Thanks for your reply and suggestion.
But the error occurs in \_post\_process() in mmdet_node.py, which runs before process_mmdet_results() you mentioned.
I agree that it's not a good solution to override CLASSES directly. How about modify \_post\_process() as follow:

```python3
    def _post_process(self, preds):
        if isinstance(preds, tuple):
            dets = preds[0]
            segms = preds[1]
        else:
            dets = preds
            segms = [None] * len(dets)

        det_model_classes = self.model.CLASSES                   # code I modified
        if isinstance(det_model_classes, str):                           # 
            det_model_classes = (det_model_classes, )            #

        assert len(dets) == len(det_model_classes)                #
        assert len(segms) == len(det_model_classes)            #
        result = {'preds': [], 'model_cfg': self.model.cfg.copy()}

        for i, (cls_name, bboxes,
                masks) in enumerate(zip(det_model_classes, dets, segms)):
            if masks is None:
                masks = [None] * len(bboxes)
            else:
                assert len(masks) == len(bboxes)
```

meanwhile, a type checking in precess_mmdet_results() is needed:
```python3
if isinstance(class_names, str):
        class_names = (class_names, )
```

because it used the det_model.CLASSES as a param in line 277:
[
                    class_names=det_model.CLASSES,](https://github.com/open-mmlab/mmpose/blob/0376d51efdd93b3c8f3338211130753fed808bb9/demo/webcam_demo.py#L277)

**Comment by ly015** [comment]
It's great to know that you are using our new WebcamAPI :). Sorry, I thought it was `demo/webcam_demo.py`.

I agree with your solution. Welcome to create a PR at your convenience.

**Comment by 674106399** [comment]
Thx for your quick reply. I've created a PR.

I'm a cv algorithm engineer working on pose estimation tasks. I notice that there is few regression-based methods in mmpose, and you know, there are some great regression-based methods available recently, e.g. RLE, SimDR, sampling-argmax etc.

I'm still learning to use mmpose rn, maybe I will PR later to add these works to mmpose.

good day :)
