### ISSUE TITLE
bbox score must be saved as float in coco json file

### ISSUE THREAD

**Issue by fisheess** [open-mmlab/mmpose#124]
Thanks for the extraordinary work!

As I am trying to test on my own data, I have found that if the bounding box scores in coco format json is saved as 1 (instead of 1.0), there will be the info `=> Total boxes after filter low score@0.0: 0` and test does not start. I changed the scores to 0.999 and it works.

Is this deliberate, or is it inherited from pycocotools?

**Comment by jin-s13** [comment]
Thanks for reporting. We will check this problem soon.

**Comment by jin-s13** [comment]
Hi fisheess,

I have tried to change the score of bbox in `tests/data/coco/test_coco_det_AP_H_56.json` to 1 (not 1.0); and run the `test_top_down_COCO_wholebody_dataset()` in `tests/test_datasets/test_top_down_dataset.py`.

But I did not meet the reported problem, it said:
`=> Total boxes: 118
=> Total boxes after filter low score@0.0: 118`

Can you provide more information?

**Comment by innerlee** [comment]
kindly ping @fisheess

**Comment by jin-s13** [comment]
I'm closing this issue because it has been inactive for a month. Feel free to reopen it, if needed.
