### ISSUE TITLE
Wanna show bbox centerpoint and keypoints coordinate in webcam_demo.py

### ISSUE THREAD

**Issue by hatecodes** [open-mmlab/mmpose#1244]
Hi,the developers of mmpose~~
I wanna know the bbox centerpoint and keypoints coordinate when i use the webcam_demo.py, it would be better if coordinate could be displayed in real time...how could i modify codes ?
hope for answering when you see that~~~~and thx again~~~~~~

**Comment by ly015** [comment]
The bboxes and keypoints are drawn here:

**Comment by hatecodes** [comment]
for pose in pose_results:
                        bbox = pose['bbox']
                        xcc=int((bbox[0]+bbox[2])/2)
                        ycc=int((bbox[1]+bbox[2])/2)
                        kpts = pose['keypoints']
                        kpt1_x=kpts[0][0]
                        kpt1_y = kpts[0][1]
                        kpt2_x = kpts[1][0]
                        kpt2_y = kpts[1][1]
                        kpt3_x = kpts[2][0]
                        kpt3_y = kpts[2][1]
                        kpt4_x = kpts[3][0]
                        kpt4_y = kpts[3][1]

                        print('------------')
                        print(xcc,ycc)
                        print('============')
                        print(kpt1_x,kpt1_y)
                        print(kpt2_x, kpt2_y)
                        print(kpt3_x, kpt3_y)
                        print(kpt4_x, kpt4_y)
                        img_copy = img.copy()
                        cv2.putText(img_copy, (int(xcc), int(ycc)), (int(xcc), int(ycc)), cv2.FONT_HERSHEY_SIMPLEX,
                                    0.75, (0, 0, 255), 2)



i added this but got error

**Comment by ly015** [comment]
The second parameter of cv2.putText should be a str value, instead of a tuple. Please refer to OpenCV docs for details.

**Comment by hatecodes** [comment]
> The second parameter of cv2.putText should be a str value, instead of a tuple. Please refer to OpenCV docs for details.

thank you very much, all done!~~~
