### ISSUE TITLE
topdown target generate疑问？

### ISSUE THREAD

**Issue by FDInSky** [open-mmlab/mmpose#1246]
1. 请问https://github.com/open-mmlab/mmpose/blob/master/mmpose/datasets/pipelines/top_down_transform.py#L555 这里的joint_3d是一个obj的结果吗？
2. 如果1成立，那是在哪里循环遍历一张图片的所有的obj的结果的？
3. 是一个box对应一个heatmap吗？
谢谢

**Comment by jin-s13** [comment]
1. 是一个obj （一个人）的结果
2. 在dataset里面写的 https://github.com/open-mmlab/mmpose/blob/d66c4445c979e24685153c1cf73f2f3bb905279f/mmpose/datasets/datasets/top_down/topdown_coco_dataset.py#L151

**Comment by FDInSky** [comment]
https://github.com/open-mmlab/mmpose/blob/master/mmpose/datasets/datasets/base/kpt_2d_sview_rgb_img_top_down_dataset.py#L270 这里生成器返回一张图片的结果；
https://github.com/open-mmlab/mmpose/blob/master/mmpose/datasets/datasets/top_down/topdown_coco_wholebody_dataset.py#L153 一张图片的结果是一个[dict1, dict2, dict3];
https://github.com/open-mmlab/mmpose/blob/master/mmpose/datasets/pipelines/top_down_transform.py#L32 这里做transform是，怎么就直接拿到了results['joints_3d'], 不应该是for i in results去遍历每个实例作转换吗？

**Comment by FDInSky** [comment]
TopDown是按照一个box中实例去处理的吗？

**Comment by FDInSky** [comment]
https://github.com/open-mmlab/mmpose/blob/master/mmpose/datasets/datasets/top_down/topdown_coco_dataset.py#L97
https://github.com/open-mmlab/mmpose/blob/master/mmpose/datasets/datasets/base/kpt_2d_sview_rgb_img_top_down_dataset.py#L272 
这里db[i]怎么变成了dict了？这里不是一张图片的结果吗？一张图片的结果是个list，里面每个obj是dict

**Comment by jin-s13** [comment]
topdown的时候，每次处理并不是以“图片”为单位，是以“人”为单位。

**Comment by FDInSky** [comment]
https://github.com/open-mmlab/mmpose/blob/master/mmpose/models/heads/topdown_heatmap_simple_head.py#L171 这里输入的taget是一个batch的结果，是在哪里汇总的每个obj的结果

**Comment by jin-s13** [comment]
没太懂你的问题。
你的问题是，怎么把sample，组合成一个batch吗？这个是Dataloader的功能。
还是问，batch的数据是如何传给model的？  这个要去看 mmcv/runner/epoch_based_runner.py

**Comment by jin-s13** [comment]
Temporarily closed due to inactivity.
