### ISSUE TITLE
How to test on custom video

### ISSUE THREAD

**Issue by fedorenchik** [open-mmlab/mmpose#1252]
I've prepared animalpose dataset according to documentation. But I seem can't run video demo with custom video. Result is original video or video with one dot without any pose.

Video: https://www.youtube.com/watch?v=Hzt18V3Uaxc

How I tried to run:

1.

```sh
python demo/top_down_video_demo_full_frame_without_det.py \
  configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/fly/res152_fly_192x192.py \
  https://download.openmmlab.com/mmpose/animal/resnet/res152_fly_192x192-fcafbd5a_20210407.pth \
  --video-path demo/resources/Cat\ Walking-Hzt18V3Uaxc.f134.mp4 --out-video-root vis_results
```

2.

```sh
python demo/top_down_video_demo_full_frame_without_det.py \
  configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/animalpose/hrnet_w32_animalpose_256x256.py \
  https://download.openmmlab.com/mmpose/animal/resnet/res152_fly_192x192-fcafbd5a_20210407.pth \
  --video-path demo/resources/Cat\ Walking-Hzt18V3Uaxc.f134.mp4 --out-video-root vis_results
```

Please, help.

**Comment by ly015** [comment]
It seems that the model you are using is trained on the Vinegar Fly dataset, which is not suitable for the video which contains a cat. You can use a model from [Animal Pose Dataset](https://mmpose.readthedocs.io/en/latest/papers/datasets.html#animal-pose-iccv-2019) or [AP-10K Dataset](https://mmpose.readthedocs.io/en/latest/papers/datasets.html#ap-10k-neurips-2021).
