### ISSUE TITLE
how to finetune/train on all dataset in just one config

### ISSUE THREAD

**Issue by tiger990111** [open-mmlab/mmpose#1256]
I want to finetune model in all dataset of 2d hand pose. However, I don't want to finetune on those public dataset one by one. How can I just use one config file to concat all the setting of dataset, and finetune/train on all those dataset?

**Comment by ly015** [comment]
To train a model on multiple datasets with the same keypoint definition, you may consider using `ConcatDataset`. It will be automatically built if you set multiple dataset configs for training in your config file like:

```python
# Option 1: multiple dataset configs
data=dict(
    train=[
        dict(type='TopDownCocoDataset', ann_file=...),  # config of 1st dataset
        dict(type='TopDownCocoDataset', ann_file=...),  # config of 2nd dataset
        ...
    ],
    ...
)

# Option 2: one dataset config with multiple annotation files
data=dict(
    train=dict(
        type='TopDownCocoDataset',
        ann_file=[file_path_1, file_path_2]
        ...),
    ...
)
```
We are working on the document of this part. For now, you can refer to the code of the [dataset builder](https://github.com/open-mmlab/mmpose/blob/503cd03896e0bcd8cc8351f365123a5dee7615df/mmpose/datasets/builder.py#L62-L87).

If you mean to train a model using datasets with different keypoint definitions, please refer to #662 and #757 .

**Comment by tiger990111** [comment]
Thank you sooo much!

**Comment by YuktiADY** [comment]
> Thank you sooo much!

Hello,

Did you try to train multiple datasets and did you used build_dataset function?
Variable 'c' is used but not defined anywhere ??

**Comment by darcula1993** [comment]
how do I train a model on multiple datasets with the same keypoint definition in mmpose 1.x version? seems that the config for dataset is different.
