### ISSUE TITLE
2d hand keypoint order problem of RHD dataset

### ISSUE THREAD

**Issue by tiger990111** [open-mmlab/mmpose#1261]
I am now trying to finetune 2d hand pose model on coco_hand, freihand, rhd. But I find that the keypoint order of rhd is different.

here is my finetune config setting of dataset.

```
_base_ = [
    '../../../../_base_/default_runtime.py',
    '../../../../_base_/datasets/coco_wholebody_hand.py'
]

data_root = [
             '/data/pose/hand2d/coco',
             '/data/pose/hand2d/rhd',
             '/data/pose/hand2d/freihand'
             ]
data = dict(
    samples_per_gpu=64,# Batch size of each single GPU during training
    workers_per_gpu=8, # Workers to pre-fetch data for each single GPU
    val_dataloader=dict(samples_per_gpu=32),# Batch size of each single GPU during validation
    test_dataloader=dict(samples_per_gpu=32),
    train=[
        dict(
            type='HandCocoWholeBodyDataset',  # Name of dataset
            ann_file=f'{data_root[0]}/annotations/coco_wholebody_train_v1.0.json',
            img_prefix=f'{data_root[0]}/train2017/',
            data_cfg=data_cfg,
            pipeline=train_pipeline,
            dataset_info={{_base_.dataset_info}}
        ),

        dict(
            type='Rhd2DDataset',
            ann_file=f'{data_root[1]}/annotations/rhd_train.json',
            img_prefix=f'{data_root[1]}/',
            data_cfg=data_cfg,
            pipeline=train_pipeline,
            dataset_info={{_base_.dataset_info}}),

        dict(
            type='FreiHandDataset',
            ann_file=f'{data_root[2]}/annotations/freihand_train.json',
            img_prefix=f'{data_root[2]}/',
            data_cfg=data_cfg,
            pipeline=train_pipeline,
            dataset_info={{_base_.dataset_info}})
    ],

    val=dict(
        type='HandCocoWholeBodyDataset',
        ann_file=f'{data_root[0]}/annotations/coco_wholebody_val_v1.0.json',
        img_prefix=f'{data_root[0]}/val2017/',
        data_cfg=data_cfg,
        pipeline=val_pipeline,
        dataset_info={{_base_.dataset_info}}
        ),
    test=dict(
        type='HandCocoWholeBodyDataset',
        ann_file=f'{data_root[0]}/annotations/coco_wholebody_val_v1.0.json',
        img_prefix=f'{data_root[0]}/val2017/',
        data_cfg=data_cfg,
        pipeline=val_pipeline,
        dataset_info={{_base_.dataset_info}}
        ),
)
```

I inference the rhd pretrained model by res50_rhd2d_256x256.py & deeppose_res50_rhd2d_256x256-37f1c4d3_20210330.pth.
Then I got the mistake order of hand keypoints.
![rhd_issue](https://user-images.githubusercontent.com/54582916/160080648-34357190-749d-46f0-91dc-e757b0cb09f0.png)
 
My visualizing code is base on the order of :
```
kpts_selected = list(range(92-1, 112)) + list(range(113-1, 133)) + [5,6,7,8]
connectivity = [
        # left hand
        (0,1), (1,2), (2,3), (3,4),
        (0,5), (5,6), (6,7), (7,8),
        (0,9), (9,10), (10,11), (11,12),
        (0,13), (13,14), (14,15), (15,16),
        (0,17), (17,18), (18,19), (19,20),
        # right hand
        (21,22), (22,23), (23,24), (24,25),
        (21,26), (26,27), (27,28), (28,29),
        (21,30), (30,31), (31,32), (32,33),
        (21,34), (34,35), (35,36), (36,37),
        (21,38), (38,39), (39,40), (40,41),
    ]
```

Also, I have tried to modify the keypoint_info of mmpose/configs/_base_/datasets/rhd2d.py.
1. I tried to modify the parameter 'name'.
2. I tried to modify the parameter 'id'.
3. I tried to modify both on 1 and 2.
But the error is still there.

So, I think the problem is simple, and I want to know how to reorder the 2d hand keypoint order of rhd.

**Comment by tiger990111** [comment]
btw, the keypoint_info of mmpose/configs/base/datasets/rhd2d.py is same as coco_hand and freihand.

**Comment by liqikai9** [comment]
I think the problem is due to the `skeleton_info` defined in `mmpose/configs/_base_/datasets/rhd2d.py`. The fieldlike this `link=('wrist', 'thumb1')` should change to `link=('wrist', 'thumb4')`.

So I will fix the dataset info of rhd2d by these modifications:

1.`link=('wrist', 'thumb1') `->` link=('wrist', 'thumb4')`

2.`link=('wrist', 'forefinger1')` -> `link=('wrist', 'forefinger4')`

3.l`ink=('wrist', 'middle_finger1') `-> `link=('wrist', 'middle_finger4')`

4.`link=('wrist', 'ring_finger1') `-> `link=('wrist', 'ring_finger4')`

5.`link=('wrist', 'pinky_finger1')` -> `link=('wrist', 'pinky_finger4')`

These modifications are minor, which will not affect the trained models.

See Pull Resuest #1264 for more detail.

**Comment by liqikai9** [comment]
With these modifications, I have checked the demo script using these commands:

`python demo/top_down_img_demo.py configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/rhd2d/res50_rhd2d_256x256.py checkpoints/res50_rhd2d_256x256-5dc7e4cc_20210330.pth --img-root tests/data/rhd/ --json-file tests/data/rhd/test_rhd.json --out-img-root vis_results_th_rhd`

and 

`python demo/top_down_img_demo.py configs/hand/2d_kpt_sview_rgb_img/deeppose/rhd2d/res50_rhd2d_256x256.py checkpoints/deeppose_res50_rhd2d_256x256-37f1c4d3_20210330.pth --img-root tests/data/rhd/ --json-file tests/data/rhd/test_rhd.json --out-img-root vis_results_dp_rhd`.

And here are the visualization results, respectively.

![topdown_heatmap_rhd_vis_0](https://user-images.githubusercontent.com/87690686/160515826-ba116762-0aa7-418d-a7e8-d4110412f2d7.jpg)   ![deeppose_rhd_vis_0](https://user-images.githubusercontent.com/87690686/160515841-a104b7c6-36ff-4591-9a2a-db8436f9a8c6.jpg)

The visualization results look just fine.

**Comment by liqikai9** [comment]
Also, here is the definition of keypoint indices of [RHD dataset](https://lmb.informatik.uni-freiburg.de/resources/datasets/RenderedHandpose/README). 
It says, `1-4: left thumb [tip to palm]`, in which the finger is from tip to palm, so I think the `wrist` should be connected to `finger4`. 

Maybe it is different from the other hand datasets like freihand and coco_wholebody_hand.

**Comment by tiger990111** [comment]
I didn't use the visualization of mmpose. And I found that skeleton_info is used when we want to visualization in mmpose.
My visulization code is like:
```
pose_results, returned_outputs = inference_top_down_pose_model(
                    pose_model,
                    img_path,
                    person_results = hand_box_list,
                    )

pose_res[0:21]= pose_results[0]['keypoints'].tolist()
pose_res[21:42] = pose_results[1]['keypoints'].tolist()

```

Then i use the 'connectivity' defined below to plot the result
    ```
connectivity = [
        # left hand
        (0,1), (1,2), (2,3), (3,4),
        (0,5), (5,6), (6,7), (7,8),
        (0,9), (9,10), (10,11), (11,12),
        (0,13), (13,14), (14,15), (15,16),
        (0,17), (17,18), (18,19), (19,20),
        # right hand
        (21,22), (22,23), (23,24), (24,25),
        (21,26), (26,27), (27,28), (28,29),
        (21,30), (30,31), (31,32), (32,33),
        (21,34), (34,35), (35,36), (36,37),
        (21,38), (38,39), (39,40), (40,41),
    ]
```

But thing goes wrong
![image](https://user-images.githubusercontent.com/54582916/160517199-b93aee1a-5ccd-42bb-b747-705692905436.png)

So I think you just fixed the visualizaiton code by change the skeleton_info ?
But the order of keypoint definition didn't change, which may make mistake when i want to fine-tune the model on multi-dataset. Like, I am now fine-tuning the model on coco, freihand, panoptic and RHD.

**Comment by jin-s13** [comment]
The problem is that RHD and coco have different keypoint definition.
In RHD, 1-4: left thumb [tip to palm], in which the finger is from tip to palm. But in COCO-WholeBody, FreiHand, Panoptic, it is in inverse order.
So we cannot simply combine all these datasets for training without modifying the keypoint order of RHD.

**Comment by tiger990111** [comment]
Yeah, I have known that the definition of RHD is different, and thank you guys so patient to figure it out.
But I am now need to fine-tune with RHD dataset, and I found that the keypoint definition is set in:
`mmpose\configs\_base_\datasets\rhd2d.py`
with the key 'keypoint_info'
However, like I mention in the beginning, I have tried to modify the keypoint_info of mmpose/configs/base/datasets/rhd2d.py.

I tried to modify the parameter 'name'.
I tried to modify the parameter 'id'.
I tried to modify both on 1 and 2.
But the error is still there.

**Comment by jin-s13** [comment]
I think you should also modify the key in `keypoint_info`. 
https://github.com/open-mmlab/mmpose/blob/6af21d98581aa3b0979f887e32e79801b64b96bd/configs/_base_/datasets/rhd2d.py#L14

**Comment by jin-s13** [comment]
Note that 'keypoint_info' will not directly affect the order of the keypoint in the dataset. It is mostly for visualization & storing information about flip_pair.

You may need to modify this line,
https://github.com/open-mmlab/mmpose/blob/6af21d98581aa3b0979f887e32e79801b64b96bd/mmpose/datasets/datasets/hand/rhd2d_dataset.py#L108
to reorder its keypoints. Add a keypoint mapping there.

**Comment by tiger990111** [comment]
you mean like these ?
```
map = [0,
             4,3,2,1,
             8,7,6,5,
             12,11,10,9,
             16,15,14,13,
             20,19,18,17
             ]
keypoints = keypoints[map]
```

**Comment by liqikai9** [comment]
> you mean like these ?
> 
> ```
> map = [0,
>              4,3,2,1,
>              8,7,6,5,
>              12,11,10,9,
>              16,15,14,13,
>              20,19,18,17
>              ]
> keypoints = keypoints[map]
> ```

@tiger990111 
Yes, using the map, you can use the results predicted by the model pre-trained on other datasets and then fine-tune on RHD dataset.

**Comment by tiger990111** [comment]
ok, thank you guys sooo much! You guys are responsible and patient!
