### ISSUE TITLE
The model trained by myself is much larger than the official website

### ISSUE THREAD

**Issue by erpingzi** [open-mmlab/mmpose#1263]
For example, hrnet_w48_coco_256*192, the official website is 264M, but the size of the model I trained is 729.3M

**Comment by jin-s13** [comment]
use https://github.com/open-mmlab/mmpose/blob/master/tools/misc/publish_model.py to remove unnecessary contents in the model pth

**Comment by erpingzi** [comment]
That's it, thank you！
