### ISSUE TITLE
sigmas对训练结果影响大吗？

### ISSUE THREAD

**Issue by hatecodes** [open-mmlab/mmpose#1266]
hello，我想问一下dataset中的sigmas对训练结果影响大吗？因为我是自己训练的模型，所以没有sigmas数据，是否能直接套用其他模型的sigmas呢，感谢感谢~~~

**Comment by jin-s13** [comment]
sigmas影响测试结果，不影响训练结果。

**Comment by hatecodes** [comment]
> 

感谢感谢~~~
