### ISSUE TITLE
[Enhance] replace length-indexing with os.path.split

### ISSUE THREAD

**Issue by Indigo6** [open-mmlab/mmpose#1267]
Minor suggestion.
https://github.com/open-mmlab/mmpose/blob/6af21d98581aa3b0979f887e32e79801b64b96bd/mmpose/datasets/datasets/top_down/topdown_coco_dataset.py#L284
Would it be more robust to replace the above line with the following code?:
```
image_id = self.name2id[os.split(image_paths[i])[1]] 
```
Since one(like me...) could somehow enter "img_prefix=f'{data_root}/images/train"(missing '/' at end) in configs, and the evaluation breakdowns after long time training

**Comment by ly015** [comment]
Thanks for your suggestion. I am afraid we can not directly split the full path to obtain the image name, cause the image name may contain folder names. I think we can do this by manually adding the separator `/` to the end of the img_prefix if it's missing. This will be fixed soon.

**Comment by Indigo6** [comment]
ok, thank you for your reply
