### ISSUE TITLE
when i use sun_glass effect in  web_camera.py, i found i couldnt use png img to replace jpg img....

### ISSUE THREAD

**Issue by hatecodes** [open-mmlab/mmpose#1272]
hello, i wanna replace the original sunglasses jpg to my own png img,which have transparent effect.but i found it doesnt work... how could i add png img in sun_glass effect? thank you !!!

**Comment by ly015** [comment]
If you are using `demo/webcam_demo.py`, please refer to the code for applying the sunglasses effect: https://github.com/open-mmlab/mmpose/blob/master/mmpose/core/visualization/effects.py#L60. It is designed for the RGB sunglasses picture, so you may need to modify it to support RGBA.

Also please not that we using the anchors adjusted on the original sunglasses image, so you may need to update the anchor annotation according to your own image:

**Comment by hatecodes** [comment]
> 
thank you sir, and i wanna ask about 'orthogonal vector to the left-to-right eyes',why use this vector to calculate the new  anchor points, i cant understand that..... may you tell me some detail? really appreciate that....

**Comment by ly015** [comment]
Please refer to https://github.com/open-mmlab/mmpose/blob/master/tools/webcam/docs/example_cn.md for details.

**Comment by hatecodes** [comment]
> Please refer to https://github.com/open-mmlab/mmpose/blob/master/tools/webcam/docs/example_cn.md for details.

thank you really much
