### ISSUE TITLE
How to convert mmpose model with mmdection result to onnx?

### ISSUE THREAD

**Issue by lovelyfrog** [open-mmlab/mmpose#1281]
I tried to convert mmpose model to onnx which use mmdet to detect the box first, and then the mmpose model need the img_meta and img as input. However, the img_meta is a list and can not be put into onnx. Can someone please give a guide on that?

**Comment by ly015** [comment]
The exported onnx model only contains the network, so you may need to implement the pre-processing and post-processing in your application.

Our model deployment toolbox [MMDeploy](https://github.com/open-mmlab/mmdeploy) has supported both MMDetection and MMPose. You can refer to the solutions provided in MMDeploy.

**Comment by lovelyfrog** [comment]
Ok, thanks a lot.
