### ISSUE TITLE
Incorrect topdown target generation

### ISSUE THREAD

**Issue by kuaitoukid** [open-mmlab/mmpose#1284]
I tried to output the img and target in training, but found the result seems incorrect (with an offset).
image_id: 000000319100.jpg
config file: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/res50_coco_384x288.py, with no TopDownRandomFlip, TopDownHalfBodyTransform, TopDownGetRandomScaleRotation in train pipeline.
generated image and keypoint (colored dot)
![test](https://user-images.githubusercontent.com/8719112/161383474-a186011e-6a86-4f3b-9837-8c76c6bc6352.jpg)

Can anybody know the reason?

**Comment by ly015** [comment]
Thanks for your feedback. Could you please further describe the process of the visualization? For example, how is the keypoint coordinate and bbox (if it's an image crop) obtained?

For now, I am not sure about the cause of the shift. But please note that the training dataset will add a small random shift to the bbox center (as an augmentation, please see [here](https://github.com/open-mmlab/mmpose/blob/master/mmpose/datasets/datasets/top_down/topdown_coco_dataset.py#L165) and [here](https://github.com/open-mmlab/mmpose/blob/master/mmpose/datasets/datasets/base/kpt_2d_sview_rgb_img_top_down_dataset.py#L144-L145)). And for top-down, the keypoint target is calculated in the shifted bbox. If you draw the pre-processed keypoint in the original bbox region or calculate the keypoints' global coordinates in the image via the original bbox, the result can be incorrect. It's just a possible cause of this issue and you can set the `self.test_mode=True` for a quick test (testing dataset won't do the shift).

**Comment by kuaitoukid** [comment]
I doubt that this is a problem abount deepcopy?
Here is the config file and debug json in zip.
[debug.zip](https://github.com/open-mmlab/mmpose/files/8403779/debug.zip)
add an exit as the snapshot below
![1648928413(1)](https://user-images.githubusercontent.com/8719112/161410324-e6939236-ec1a-444b-933e-7eb60244e90b.png)
