### ISSUE TITLE
v0.25.0 distributed training incompatible with torch.distributed.launch

### ISSUE THREAD

**Issue by zwfcrazy** [open-mmlab/mmpose#1287]
The argument --local-rank in ./tools/train.py is not compatible with torch.distributed.launch as the latter provides --local_rank instead of --local-rank.
Before v0.25.0, this is correct, why is this changed in the latest version?

**Comment by ly015** [comment]
We have a plan to use hyphens instead of underscores in the argument name. To resolve the incompatibility, we have added `--local_rank` back as an alias to `--local-rank`. Sorry for the inconvenience it caused.

**Comment by zwfcrazy** [comment]
> We have a plan to use hyphens instead of underscores in the argument name. To resolve the incompatibility, we have added `--local_rank` back as an alias to `--local-rank` in #1288 . Sorry for the inconvenience it caused.

Thanks for the quick fix. Closing this issue now.
