### ISSUE TITLE
Adversarial training in mmpose

### ISSUE THREAD

**Issue by whffams2** [open-mmlab/mmpose#1291]
Hello, I tried to use adversarial training in 2d human pose estimation, but I don't quite understand how to do it.

**Comment by ly015** [comment]
A typical [detector](https://github.com/open-mmlab/mmpose/tree/master/mmpose/models/detectors) in mmpose includes modules like backbone, neck, and head. You may need to implement a new detector (e.g. based on the existing top-down detector) that also includes the generator and discriminator, and properly defines the forward process and loss computation in the `forward_train` method. Also, a new dataset may be needed to generate synthetic samples.

**Comment by ly015** [comment]
You can refer to the [mesh](https://github.com/open-mmlab/mmpose/blob/master/mmpose/models/detectors/mesh.py) model in mmpose, which involves adversarial learning. However, please note that it's a quite different task than 2D pose estimation, and this part is being deprecated in mmpose and the code is no longer maintained.

**Comment by whffams2** [comment]
> You can refer to the [mesh](https://github.com/open-mmlab/mmpose/blob/master/mmpose/models/detectors/mesh.py) model in mmpose, which involves adversarial learning. However, please note that it's a quite different task than 2D pose estimation, and this part is being deprecated in mmpose and the code is no longer maintained.

Thank you very much for your help. I will try later. Thank you again for your help
