### ISSUE TITLE
best annotator software for create poses 

### ISSUE THREAD

**Issue by alaa-shubbak** [open-mmlab/mmpose#1293]
Hello , 
I am new in the field of pose estimation, and have my own dataset which is objects that are not mentioned in your pose estimator. 

I would like to ask about a software that could help me in annotation my dataset in a COCO format ,so i can place the keypoints as well as the bounding boxes over my objects. 

any help will be so appreciated

**Comment by ly015** [comment]
I would recommend [LabelBee](https://github.com/open-mmlab/labelbee-client), which is also part of the OpenMMLab project. [LabelMe](https://github.com/wkentaro/labelme) is another popular tool that has been widely used for keypoint annotation.

**Comment by alaa-shubbak** [comment]
many thanks , the LablMe seems to have some buges and still under some updating , but i will try the LabelBee.
