### ISSUE TITLE
body 25 or 26 keypoints?

### ISSUE THREAD

**Issue by jinfagang** [open-mmlab/mmpose#1297]
I searched a little bit on documentation, seems there is no such option that body keypoints model include foot points.

if there is a pretrained body model with foot points supported, it would benifit a lot for **real world** applications. Such as 3d pose and motion capture, foot keypoints are really needed.

**Comment by ly015** [comment]
For 2D keypoint models that include foot points, you can check out our whole-body models at https://github.com/open-mmlab/mmpose/blob/master/docs/en/tasks/2d_wholebody_keypoint.md

**Comment by jinfagang** [comment]
@ly015 Oh, of course, but I forgot to mention that sometimes we don't want whole body model, on one hand, the model is not as accurate as less keypoints model, on the other hand, some keypoints we might not really needed and effect speed. My original proposal was exactly 25 or 26 keypoints model which only 17 coco + 8 + (1), not whole body models.

**Comment by ly015** [comment]
Currently, we don't have pretrained models that fulfill your need. I think maybe you can train a model using a subset of coco-wholebody dataset (or other wholebody datasets) that only includes the keypoints you need.

**Comment by jinfagang** [comment]
@ly015 I switched to alphapose.

**Comment by ChawDoe** [comment]
> @ly015 Oh, of course, but I forgot to mention that sometimes we don't want whole body model, on one hand, the model is not as accurate as less keypoints model, on the other hand, some keypoints we might not really needed and effect speed. My original proposal was exactly 25 or 26 keypoints model which only 17 coco + 8 + (1), not whole body models.

Yes I need it too! But I found some bugs in installing alpha pose...
