### ISSUE TITLE
when i use analyze_logs.py, i met a error

### ISSUE THREAD

**Issue by hatecodes** [open-mmlab/mmpose#1301]
hello, when i use
python tools/analysis/analyze_logs.py plot_curve tools/logs/f_airplane_hrnet/20220328_210553.log.json --keys loss , 

it gave me:
 File "tools/analysis/analyze_logs.py", line 55, in plot_curve
    f'{args.json_logs[i]} does not contain metric {metric}')
KeyError: 'tools/logs/f_airplane_hrnet/20220328_210553.log.json does not contain metric loss'

 But the json have loss column, whats goin on, plz help, thx!~~~~~

**Comment by hatecodes** [comment]
[20220328_210553.log.zip](https://github.com/open-mmlab/mmpose/files/8447751/20220328_210553.log.zip)

here it is , thx~~~

**Comment by jin-s13** [comment]
Have you modified the log file? The log (especially the first line) looks a little bit strange. 
Please manually delete the first line of the log, and rerun the tool.

**Comment by hatecodes** [comment]
> Have you modified the log file? The log (especially the first line) looks a little bit strange. Please manually delete the first line of the log, and rerun the tool.

i deleted the first line, it works! thx a lot~~

**Comment by zeckireck** [comment]
![image](https://user-images.githubusercontent.com/81000191/187822183-47c146fe-d3d7-408c-93e9-50fefb7d6880.png)
[20220831_195436.log.zip](https://github.com/open-mmlab/mmpose/files/9466482/20220831_195436.log.zip)
我也遇到相同的问题
