### ISSUE TITLE
README.md更新

### ISSUE THREAD

**Issue by Nothing1024** [open-mmlab/mmpose#1304]
**发现时间：2022/4/9 9:40**
官方[README.md](https://github.com/open-mmlab/mmpose/blob/master/README.md)和[README_CN.md](https://github.com/open-mmlab/mmpose/blob/master/README_CN.md)

中的
文档链接均无法访问
[📘Documentation](https://mmpose.readthedocs.io/en/v0.25.0/) | [🛠️Installation](https://mmpose.readthedocs.io/en/v0.25.0/install.html) | [👀Model Zoo](https://mmpose.readthedocs.io/en/v0.25.0/modelzoo.html) | [📜Papers](https://mmpose.readthedocs.io/en/v0.25.0/papers/algorithms.html) | [🆕Update News](https://mmpose.readthedocs.io/en/v0.25.0/changelog.html) |

[📘文档](https://mmpose.readthedocs.io/en/v0.25.0/) | [🛠️安装](https://mmpose.readthedocs.io/en/v0.25.0/install.html) | [👀模型库](https://mmpose.readthedocs.io/en/v0.25.0/modelzoo.html) | [📜论文库](https://mmpose.readthedocs.io/en/v0.25.0/papers/algorithms.html) | [🆕更新日志](https://mmpose.readthedocs.io/en/v0.25.0/changelog.html)

直接访问文档https://mmpose.readthedocs.io 正常（  自动跳转至https://mmpose.readthedocs.io/en/latest/   ）

可能是0.25.0文档被删除或暂未更新

**Comment by ly015** [comment]
Thanks for reporting this issue. We will fix it asap.

**Comment by ly015** [comment]
Fixed in #1305
