### ISSUE TITLE
Pretrained voxelpose with custom data

### ISSUE THREAD

**Issue by Westerby** [open-mmlab/mmpose#1310]
I would like to use pretrained voxelpose model with custom data from 4 cameras.

My setup and experiments:
To the inference I supply 4 frames and 4 sets of camera parameters (extrinsic, intrinsic, distortion coefficients) from 4 calibrated Kinect cameras.
 
My initial camera rotation and translation are different (much smaller scale, and 90 degrees rotation wrt. world origin, with “master” camera being in the scene origin). I rotate and translate each of cameras to roughly be in the same space as in CMU Panoptic. Next I follow cam parameter recalculation from _get_cam method.

Illustration below. Marked green are my cameras, - other are HD cameras from CMU Panoptic.

![obraz](https://user-images.githubusercontent.com/25503253/162912589-ea7e7009-f534-4381-be5e-c61c00f71be0.png)

As I don’t have 5 cameras I supply 4th image and 4th cam parameters as 5th sample. With this setup I get no valid predictions.

For another experiment - just to check what will be the result - I do is the following: I supply frames from my camera and get original camera parameters from CMU Panoptic dataset. The pose estimation is obviously wrong, as camera parameters are from different devices, but at least I get some detections.

![obraz](https://user-images.githubusercontent.com/25503253/162912641-a713a745-18eb-42ae-a3f2-ddbdaf4b90b3.png)

I also explored heatmaps that come out of the pretrained backbone and they look fine – detection blobs seem to be in respective body joints positions. I checked visually the heatmaps 3D projections as well but I couldn't interpret those.

Do you have any idea what can be wrong when other camera parameters are supplied? Perhaps the pretrained model simply doesn’t work with other cameras, as it is to much fixed to the CMU cameras? 

I can provide more information if that will be helpful.

**Comment by liqikai9** [comment]
Have you tried the [VoxelPose demo](https://github.com/open-mmlab/mmpose/blob/master/demo/docs/3d_multiview_human_pose_demo.md) and check the visualization results? 

> I rotate and translate each of cameras to roughly be in the same space as in CMU Panoptic.

And I wonder how did you do to translate your camera parameters to fit in the CMU Panoptic format? 
After translating the camera, how did you do to translate the images captured by these cameras accordingly?

**Comment by Westerby** [comment]
Thanks for the answer.
No I haven't tried the demo, I will check it.
Translation - simply multiplied by some factor, like 100.
No - I haven't manipulate the images by any way. I didn't think it'll have any effect, since paramers camera parameters are applied to 2d detection heatmaps, and just warped. 

I also changed the rotation and translation only after original camera parameters returned no valid predictions.

**Comment by Westerby** [comment]
Hello,
a follow-up to what I wrote above. I tested the demo, now only on data from CMU:
- scene: 161029_build1
- cameras: (0, 25), (0, 9), (0, 15), (0, 5), (0, 24)
- frames: 00_05_00002272.jpg  00_05_00004565.jpg  00_05_00009190.jpg

I get valid predictions only on one frame: _00004565. 
I wonder what is the reason for that? Does the model have problems to generalize to other cameras?

**Comment by wusize** [comment]
> Hello, a follow-up to what I wrote above. I tested the demo, now only on data from CMU:
> 
> Checked the 161029_build1, on +200 frames with demo script Works good. Checked demo script with my +1000 frames, single movie, original camera parameters after calibration. Unfortunately didn't work. Any more hints?

As far as I know, current multiview 3d pose estimation methods like VoxelPose cannot perform well in a new scene, sometimes may fail in the same scene with a different camera setting. So I recommend you to train a your model from scratch. Given that GT 3d poses cannot be easily obtained, you can follow the setting on [campus/shelf](https://github.com/open-mmlab/mmpose/tree/master/configs/body/3d_kpt_mview_rgb_img/voxelpose/shelf), where you can artificially generate the training data.
