### ISSUE TITLE
Speedup the 'TopDownAffine' by give short cut to rotation=0

### ISSUE THREAD

**Issue by chenxinfeng4** [open-mmlab/mmpose#1316]
The `TopDownAffine` is a **disaster** for cpu load. Because in most case of inference, there is no ROTATION at all. Please give a shortcut when rotation==0. The cv2.warpAffine is so laborious.
```
# mmpose/datasets/pipelines/top_down_transform.py
@PIPELINES.register_module()
class TopDownAffine:
      ...
        c = results['center']
        s = results['scale']
        r = results['rotation']
         ....
        img = [
                    cv2.warpAffine(
                        i,
                        trans, (int(image_size[0]), int(image_size[1])),
                        flags=cv2.INTER_LINEAR) for i in img
                ]
```

the configure file 
```
#configs/wholebody/2d_kpt_sview_rgb_img/topdown_heatmap/coco-wholebody/res152_coco_wholebody_384x288.py
val_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='TopDownAffine'),
    dict(type='ToTensor'),
    dict(
        type='NormalizeTensor',
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]),
    dict(
        type='Collect',
        keys=['img'],
        meta_keys=[
            'image_file', 'center', 'scale', 'rotation', 'bbox_score',
            'flip_pairs'
        ]),
]
```
I used GPU to do inference of a video by `demo/top_down_video_demo_full_frame_without_det.py`. However, the cpu workload is surprising 2000%. Part of the result own to that I used 1280x800 resolution video and 512x512 feature size, but the most because of this laborious `TopDownAffine`.

**Comment by jin-s13** [comment]
Thanks. It is indeed a good idea. Would you like to raise a PR (pull request) to fix it yourself?

**Comment by chenxinfeng4** [comment]
I will try.

**Comment by chenxinfeng4** [comment]
There may be a bug in `mmpose/mmpose/core/post_processing/post_transforms.py > get_affine_transform`

```
    src_dir = rotate_point([0., src_w * -0.5], rot_rad) 
    src = np.zeros((3, 2), dtype=np.float32)
    src[0, :] = center + scale_tmp * shift
    src[1, :] = center + src_dir + scale_tmp * shift
    src[2, :] = _get_3rd_point(src[0, :], src[1, :]) #maybe a bug when `scale[0] != scale[1]` 
    

    dst = np.zeros((3, 2), dtype=np.float32)
    dst[0, :] = [dst_w * 0.5, dst_h * 0.5]
    dst[1, :] = np.array([dst_w * 0.5, dst_h * 0.5]) + dst_dir
    dst[2, :] = _get_3rd_point(dst[0, :], dst[1, :])  
```

**Comment by jin-s13** [comment]
> src[2, :] = _get_3rd_point(src[0, :], src[1, :])

This is intended. Not a bug actually.

**Comment by chenxinfeng4** [comment]
CPU占用率高的问题找到了，因为 mmpose 在数据加载 pipeline 中有大量的低效numpy数组拷贝（索引赋值、padding等），以及格式转换为 tensor 的方法选择。而不仅仅是 图片rotation 问题。找到这个问题花了很长时间。

![ba290024a4840a02d1a0b0417826c14](https://user-images.githubusercontent.com/17546446/163511072-b9e769c5-6899-4446-b591-382f539ba671.png)

这个可以参考 mmdetection 
![image](https://user-images.githubusercontent.com/17546446/163511043-f7dd8377-c3c7-4f6d-8b63-f7dbb50b9330.png)

第二个问题在于，Normalize 的计数量很大，其实应该放在 GPU 上做，而不是cpu。也就是 ToTensor 应该就把数据转到GPU上来，然后做 Normalize。
目前我可以将 CPU占用率从3千%降低到2百%，推测速度40fps 提升到80fps。多卡的提升会更显著。

**Comment by chenxinfeng4** [comment]
Could you allow me to update the features:
1. Optomize the `ToTensor` function, which will load the image more efficient
2. Allow the `ToTensor` to upload image to GPU

**Comment by jin-s13** [comment]
> 

Thanks a lot for your help in investigating this problem. Please feel free to raise an PR to fix them!
We will conduct more comprehensive tests.
