### ISSUE TITLE
2d and 3d joints order

### ISSUE THREAD

**Issue by HaozhouPang** [open-mmlab/mmpose#1318]
Hi,

In the demo of estimation of 3d pose from a given video, if I understand correctly, the 2d points detector detects 17 points, and the lifting model then converts the point into 3-dimensional space.

I am trying test the lifting model with 2d points detected by my own model, could someone help with the joints order? (the index : name pair)

I used the following ,

        0: 'root (pelvis)',
        1: 'right_hip',
        2: 'right_knee',
        3: 'right_foot',
        4: 'left_hip',
        5: 'left_knee',
        6: 'left_foot',
        7: 'spine',
        8: 'thorax',
        9: 'neck_base',
        10: 'head',
        11: 'left_shoulder',
        12: 'left_elbow',
        13: 'left_wrist',
        14: 'right_shoulder',
        15: 'right_elbow',
        16: 'right_wrist'

but the result looks like the index was wrong...
![image](https://user-images.githubusercontent.com/16600283/163361268-ab2ff7b2-73fb-4b17-8c72-65225aed979b.png)

**Comment by ly015** [comment]
Hi, there are 2 types of 2D keypoint inputs supported for the pose lifting model, namely [h36m keypoints](https://github.com/open-mmlab/mmpose/blob/4853b4bcd1238ef559c0f341ed2402c5a3605316/mmpose/datasets/datasets/top_down/topdown_h36m_dataset.py#L26-L42) and [coco keypoints](https://github.com/open-mmlab/mmpose/blob/4853b4bcd1238ef559c0f341ed2402c5a3605316/mmpose/datasets/datasets/top_down/topdown_coco_dataset.py#L30-L46). The demo script will processes the 2D keypoint detection according to the dataset type [here](https://github.com/open-mmlab/mmpose/blob/4853b4bcd1238ef559c0f341ed2402c5a3605316/demo/body3d_two_stage_video_demo.py#L25-L54). The 2d keypoint detection results from your model seems to follow the h36m definition, so you may want to check if the dataset type is set properly as `TopDownH36MDataset`.

And the domain gap between the training and testing data can also lead to pool results. Could you please share the image and 2d keyponit results as well?

**Comment by HaozhouPang** [comment]
Hi, the 2d detector I used follow the body-25 joint names convention, which is defined as follow:
   ```
    'Nose',
    'Neck',
    'RShoulder',
    'RElbow',
    'RWrist',
    'LShoulder',
    'LElbow',
    'LWrist',
    'MidHip',
    'RHip',
    'RKnee',
    'RAnkle',
    'LHip',
    'LKnee',
    'LAnkle',
    'REye',
    'LEye',
    'REar',
    'LEar',
    'LBigToe',
    'LSmallToe',
    'LHeel',
    'RBigToe',
    'RSmallToe',
    'RHeel',
```

So I map the 25points to the 17 points as defined by TopDownH36M by their names. The order that I used for the 17 points was taken from line 27 of https://github.com/open-mmlab/mmpose/blob/4853b4bcd1238ef559c0f341ed2402c5a3605316/mmpose/datasets/datasets/body3d/body3d_h36m_dataset.py

The visualization result looks like some joints are mismatched, could you please confirm the order that I used for the 17 points was correct or not? 

Much appreciated,
Haozhou

**Comment by HaozhouPang** [comment]
Please ignore my previous post and thanks for your time and patience.

It turns out that I made a mistake when working with the indices...

I am closing this issue and have a great day!
Haozhou
