### ISSUE TITLE
training visualization

### ISSUE THREAD

**Issue by Joyako** [open-mmlab/mmpose#1319]
Hi, thanks for your excellent project. what do you suggest if I want to add visualization training?

**Comment by ly015** [comment]
Hi, thanks for your interest. If you mean visualizing loss curves or validation results during training, you can register logger hooks by adding them in your configs like:
```python
log_config=dict(
    interval=5,
    hooks=[
        # The default hook to output information to screen and local files
        dict(type='TextLoggerHook'),  
        # You can add the following hook to visualize with Tensorboard
        dict(type='TensorboardLoggerHook')
    ])
```

You can find all logger hooks supported in mmcv at: https://github.com/open-mmlab/mmcv/tree/master/mmcv/runner/hooks/logger

**Comment by Joyako** [comment]
Hi @ly015 , thanks a lot!
