### ISSUE TITLE
when ‘python setup.py develop’, no such file or directory:'mmpose/VERSION'

### ISSUE THREAD

**Issue by FrankYoungchen** [open-mmlab/mmpose#132]
when ‘python setup.py develop’, no such file or directory:'mmpose/VERSION'

**Comment by innerlee** [comment]
we have this file https://github.com/open-mmlab/mmpose/blob/master/mmpose/VERSION

**Comment by FrankYoungchen** [comment]
thx,but I want to run demo/top_down_video_with_mmdet.py, it will appear `ModuleNotFoundError：No module named ‘mmpose.apis’`

**Comment by innerlee** [comment]
check
1. mmpose is installed successfully. 
2. running the above script at the correct folder.

could you give info about the above two items?

**Comment by FrankYoungchen** [comment]
sorry，what some bug may have appeared  in git or I made some mistakes so that I have no `mmpose` file
I have already solve it
thx.

**Comment by innerlee** [comment]
good to hear that!
