### ISSUE TITLE
Train smoothnet using 3D pose data in mmpose

### ISSUE THREAD

**Issue by qinb** [open-mmlab/mmpose#1322]
Thanks for your open-sourcing smoothnet!  I already read the smoothnet paper, and find it inputs the pose data produced by SPIN/VIBE. So,  I want to how to retrain smoothnet in mmpose using 3dpw or amass data? Thanks again

**Comment by ly015** [comment]
Thanks for your interest. The training of SmoothNet has not been supported in MMPose yet. We are considering providing SmoothNet checkpoints on more datasets in the future. You can also leave a comment in our [roadmap](https://github.com/open-mmlab/mmpose/issues/9) to tell us the model or feature you would like to see in MMPose.
