### ISSUE TITLE
A question on 3D hand pose estimation

### ISSUE THREAD

**Issue by HaozhouPang** [open-mmlab/mmpose#1323]
Hello,

I have a question regarding the 3d hand pose estimation model. If I understand the code correctly, the model takes images (with bounding boxes) as input, and output the 3d coordinates. And the 2D keypoints on the left of the following picture were generated by projecting the preds into 2d space.

![image](https://user-images.githubusercontent.com/16600283/163751998-3a155e72-2a24-4938-8588-0016ff2f0de9.png)

Can I  test the model like the 2d to 3d pose lifting model?  More precisely, can I test the model with 2d keypoints as input (instead of the pixel values) and outputs 3d coordinates?

Much appreciated,
Haozhou.

**Comment by ly015** [comment]
I think it is feasible. Please refer to the 2d-to-3d pose lifting models supported in MMPose like [SimpleBaseline3D](https://github.com/open-mmlab/mmpose/tree/master/configs/body/3d_kpt_sview_rgb_img/pose_lift) and [VideoPose3D](https://github.com/open-mmlab/mmpose/tree/master/configs/body/3d_kpt_sview_rgb_vid/video_pose_lift).

To apply such a model on new datasets like Interhand2.6M, you may need to prepare the dataset class like [Human3.6M Dataset](https://github.com/open-mmlab/mmpose/blob/master/mmpose/datasets/datasets/body3d/body3d_h36m_dataset.py). The core is to project 3D keypoints with camera parameters to obtain 2D groundtruth, which you can either do offline by a script, or online by properly config data transforms in the pipeline (please see [CameraProjection](https://github.com/open-mmlab/mmpose/blob/3336abfe7983e87dd64770f433918b7de24a6c5e/mmpose/datasets/pipelines/pose3d_transform.py#L234) and other related transforms, and the configs like [here](https://github.com/open-mmlab/mmpose/blob/3336abfe7983e87dd64770f433918b7de24a6c5e/configs/body/3d_kpt_sview_rgb_vid/video_pose_lift/h36m/videopose3d_h36m_243frames_fullconv_supervised.py#L73-L114)).
