### ISSUE TITLE
where is the eval pck ap code?

### ISSUE THREAD

**Issue by yuan243212790** [open-mmlab/mmpose#1327]
how to translate heatmap to keypoints  in order to use coco eval api

**Comment by jin-s13** [comment]
see https://github.com/open-mmlab/mmpose/blob/3336abfe7983e87dd64770f433918b7de24a6c5e/mmpose/models/heads/topdown_heatmap_base_head.py#L40

**Comment by yuan243212790** [comment]
hi,my model predict output is heatmaps ,how can i transform to keypoints?you know？please




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月20日(星期三) 下午2:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [open-mmlab/mmpose] where is the eval pck ap code? (Issue #1327)





 
see https://github.com/open-mmlab/mmpose/blob/3336abfe7983e87dd64770f433918b7de24a6c5e/mmpose/models/heads/topdown_heatmap_base_head.py#L40

**Comment by jin-s13** [comment]
in the decode function, the heatmaps will be transformed to keypoints. Please take a look.
