### ISSUE TITLE
Question about SmoothNet Implementation

### ISSUE THREAD

**Issue by vra** [open-mmlab/mmpose#1330]
Hi all,

Thanks for sharing the implementation of SmoothNet in this repo. In the paper, the author proposed a motion-aware SmoothNet, which explicitly modeled the velocity and acceleration by another two branches like the main branch. I found the implementation of SmoothNet at current only has one branch. Could you give any hints that is extra two branches necessary or just one path is fine even for different tasks(2D/3D pose estimation and human mesh recovery)?

**Comment by ly015** [comment]
@ailingzengzzz Could you please help with this question?

**Comment by ailingzengzzz** [comment]
Hi @vra,

In this implementation, I only provided the Basic SmoothNet with one branch. Motion-aware SmoothNet may be provided further. Visually, their smoothed results are similar. One path is also fine for 2d,3d, and 6d (arbitrary continuous modality) smoothness.

**Comment by vra** [comment]
Hi @ailingzengzzz Thanks for your clear explanation.  My concern resolved and I will close this thread now.
