### ISSUE TITLE
pipeline detail

### ISSUE THREAD

**Issue by zyc573823770** [open-mmlab/mmpose#1333]
https://github.com/open-mmlab/mmpose/blob/3336abfe7983e87dd64770f433918b7de24a6c5e/mmpose/datasets/datasets/top_down/topdown_coco_dataset.py#L145

after doing that, I get a new width value ‘w-1’ at obj['clean_bbox'][2] rather than the original value 'w', I wonder if that makes noise?

**Comment by jin-s13** [comment]
Thanks for reporting this issue. It is a bug. We will fix this issue soon.

BTW, I guess it will not affect the model training too much.
