### ISSUE TITLE
合并coco和mpii数据训练关键点模型

### ISSUE THREAD

**Issue by Eatzhy** [open-mmlab/mmpose#1334]
请问，想要合并coco和mpii数据训练，怎么去整合两个数据集有差异的关键点。比如coco是17点，如何转到mpii16点。直接把coco上多的点忽略掉吗？

**Comment by jin-s13** [comment]
One way to combine coco and mpii is to make the total output channel as 17+16=33, where the first 17 channels are used for training coco dataset and the remainings are used for mpii dataset.

**Comment by Eatzhy** [comment]
谢谢回复，我可以把coco上的某些点（mpii上没有标注的关键点）去掉吗，因为想让模型输出16个关键点，且输出的关键点类别和MPII一样。

**Comment by jin-s13** [comment]
也可以
