### ISSUE TITLE
There seems to be a bug in human grouping processing

### ISSUE THREAD

**Issue by daixinghome** [open-mmlab/mmpose#1336]
Hello! When I'm checking the code of 2D human body skeleton, the grouping process for associate embedding here may have some problems:
https://github.com/open-mmlab/mmpose/blob/master/mmpose/core/post_processing/group.py#L81
![image](https://user-images.githubusercontent.com/11656928/165274229-075f6f8b-8461-4e83-ae12-0068cc8a1a98.png)

When `params.ignore_too_much` is set to True, the matching process will skip, for the length of `joint_dict` (`joints` above) is already set to `params.max_num_people` in top_k process here:
https://github.com/open-mmlab/mmpose/blob/master/mmpose/core/post_processing/group.py#L221
![image](https://user-images.githubusercontent.com/11656928/165273452-8d7639f8-101e-44ad-b766-b923db2acfe8.png)

May be possible solution:
1. Delete the code from L81 to L83 in group.py;
2. Change the code here:
https://github.com/open-mmlab/mmpose/blob/master/mmpose/core/post_processing/group.py#L78
to 
    ```
    if params.ignore_too_much:
        grouped_keys = list(joint_dict.keys()[:params.max_num_people])
    else:
        grouped_keys = list(joint_dict.keys())
    ```
4. Change the code here:
https://github.com/open-mmlab/mmpose/blob/master/mmpose/core/post_processing/group.py#L115
to
    ```
    joint_dict_keys = list(joint_dict.keys())
    if params.ignore_too_much:
        joint_dict_keys = joint_dict_keys[:params.max_num_people])
    results = np.array([joint_dict[i] for i in joint_dict_keys]).astype(np.float32)
    ```
Because the `dict` after python 3.6 is ordered, so the extra person will be ignored.

The goal is to allow new person in `joint_dict` to take part in matching when `params.ignore_too_much` is False, and ignore them when `params.ignore_too_much` is set to True. Is that right?

**Comment by jin-s13** [comment]
The fix looks reasonable to me. Would you like to raise a PR to fix it by yourself?

**Comment by daixinghome** [comment]
> The fix looks reasonable to me. Would you like to raise a PR to fix it by yourself?

Sure, I've already raise a PR for this bug.
