### ISSUE TITLE
框架有很多没有通过测试的Bug

### ISSUE THREAD

**Issue by Ironteen** [open-mmlab/mmpose#1337]
在我运行res50_freihand2d_224x224.py的过程中就碰到了两个问题

1. tools/dist_train.sh里面没有定义$MASTER_ADDR

2. res50_freihand2d_224x224.py 没有定义runner = dict(type='EpochBasedRunner', max_epochs=total_epochs)

其他的还没有跑，但感觉会有很多小问题

发布的版本有点粗糙呀，期待把这些小Bug尽快解决，后续很期待在这个框架上做更多实验

**Comment by Ironteen** [comment]
I met two problems when I run the res50_freihand2d_224x224.py

1. $MASTER_ADDR is not defined in tools/dist_train.sh

2. res50_freihand2d_224x224.py does not define "runner = dict(type='EpochBasedRunner', max_epochs=total_epochs)"

I haven't run the other models yet, but I feel like there will be a lot of small problems

The released version is a bit rough. hope to solve these small bugs as soon as possible. I would like to conduct more experiments on this framework in the future.

**Comment by jin-s13** [comment]
Thanks for reporting these issues. 

Q1: $MASTER_ADDR is not defined in tools/dist_train.sh
A1: Yes. This is missing. We will fix it soon. BTW, if you would like to fix the bugs yourself, please feel free to raise a PR.

Q2: res50_freihand2d_224x224.py does not define "runner = dict(type='EpochBasedRunner', max_epochs=total_epochs)"
A2: I think this is not necessary. Does it cause any errors?
