### ISSUE TITLE
使用相机API的过程中遭遇BUG，请求支援

### ISSUE THREAD

**Issue by ShaneCan** [open-mmlab/mmpose#1340]
当我使用相机api时，如果有两个不同种类的目标同时出现在画面，那么其中一个目标的检测框就会开始闪烁，也就是说这个目标不能被持续的检测，而是间断性的被检测。当我移走一个种类的目标时只剩下另一种种类时，该目标又可以被持续检测了，请问应该如何解决呢，感谢感谢！！！

**Comment by ly015** [comment]
你好，谢谢反馈。可以提供一下你使用的指令和config么，我们排查一下。

**Comment by ShaneCan** [comment]
> 你好，谢谢反馈。可以提供一下你使用的指令和config么，我们排查一下。

所使用的det-config为yolox\yolox_s_8x8_300e_coco.py，checkpoint是自己训练的权重。
animal-pose-config为animal\2d_kpt_sview_rgb_img\topdown_heatmap\airplane\hrnet_w48_airplane_256x256.py，checkpoint为自己训练的权重。
human-pose-config所使用的是animal\2d_kpt_sview_rgb_img\topdown_heatmap\animalpose\hrnet_w32_animalpose_256x256.py（这里我使用了不对应的config因为我不想让其识别关键点但是想让其显示检测框）,human-pose-checkpoint使用的是vipnas_res50_wholebody_256x192_dark-67c0ce35_20211112.pth（默认的，实际上我并不需要这个权重，因为我不需要human目标的关键点检测）

是否还需要其他信息呢？感谢回复~~~~

**Comment by ly015** [comment]
你这里用了一个正常的animal pose的模型，和一个dummy human pose的模型，后者只是为了显示人的bbox，对么？请问一下发生闪烁的是人的框，还是动物的框，还是两者都会呢？如果所有模型都用默认设置，会发生这种闪烁么？

**Comment by ShaneCan** [comment]
> 

是的，只是为了显示人的bbox。发生闪烁的是人的框，动物的框不会发生闪烁。如果将人的config替换回原来的config，仍然发生闪烁

**Comment by ShaneCan** [comment]
> 你这里用了一个正常的animal pose的模型，和一个dummy human pose的模型，后者只是为了显示人的bbox，对么？请问一下发生闪烁的是人的框，还是动物的框，还是两者都会呢？如果所有模型都用默认设置，会发生这种闪烁么？

ly大神 请问有进展吗:)

**Comment by ly015** [comment]
我也观察到了这个现象，不过还没有找到原因。你可以试用一下我们的新版 webcam demo，应该是没有这个问题的。
https://github.com/open-mmlab/mmpose/tree/master/tools/webcam/configs/examples

**Comment by ShaneCan** [comment]
> 我也观察到了这个现象，不过还没有找到原因。你可以试用一下我们的新版 webcam demo，应该是没有这个问题的。 https://github.com/open-mmlab/mmpose/tree/master/tools/webcam/configs/examples

使用新版webcam_demo出现了报错：
File "F:\mmpose-new\mmpose\datasets\pipelines\top_down_transform.py", line 289, in __call__
    c = results['center']
KeyError: 'center'

经过查看发现新版本results中不含有center和scale这两项，而是被bbox一项代替了，请问如何解决呀 感谢ly大神！！！所使用的det为YOLOX-s
![微信截图_20220510192701](https://user-images.githubusercontent.com/95410252/167620493-0c6b1a36-a4a0-4dd2-bad5-ed7b5dfa1c9b.png)

**Comment by ly015** [comment]
是的，在新版本中部分 dataset 的 annotation 中只包含 bbox，而在 pipeline 中由 `TopDownGetBboxCenterScale` 生成 center 和 scale。我们更新了 model zoo 里的相关 config，但对用户自己的 config 可能会有 bc-breaking，因此我们在 v0.26.0 的 release note 里做了相关说明：https://github.com/open-mmlab/mmpose/releases/tag/v0.26.0

如果你用的是自己的 config，请参上面 release note 中的说明，简单修改一下 pipeline，应该就可以了

**Comment by ShaneCan** [comment]
> 

已经针对train_pipeline和val_pipeline进行了更改，但是只要摄像头没有识别到目标或者目标移动了，还是会报这个错误QAQ

**Comment by ShaneCan** [comment]
> 是的，在新版本中部分 dataset 的 annotation 中只包含 bbox，而在 pipeline 中由 `TopDownGetBboxCenterScale` 生成 center 和 scale。我们更新了 model zoo 里的相关 config，但对用户自己的 config 可能会有 bc-breaking，因此我们在 v0.26.0 的 release note 里做了相关说明：https://github.com/open-mmlab/mmpose/releases/tag/v0.26.0
> 
> 如果你用的是自己的 config，请参考上面 release note 中的说明，简单修改一下 pipeline，应该就可以了

已经针对train_pipeline和val_pipeline进行了更改，但是只要摄像头没有识别到目标或者目标移动了，还是会报这个错误QAQ

**Comment by ly015** [comment]
我们复现不了这个错误，可能需要请你提供一下你使用的 webcam config 和 model config

**Comment by ShaneCan** [comment]
> 我们复现不了这个错误，可能需要请你提供一下你使用的 webcam config 和 model config

F:\mmpose-new\configs\animal\2d_kpt_sview_rgb_img\topdown_heatmap\airplane\hrnet_w48_airplane_256x25
6.py 如下：
[hrnet_w48_airplane_256x256.txt](https://github.com/open-mmlab/mmpose/files/8667520/hrnet_w48_airplane_256x256.txt)


F:\mmpose-new\configs\_base_\datasets\fly.py 如下（该文件被我修改过）：
[fly.txt](https://github.com/open-mmlab/mmpose/files/8667526/fly.txt)

webcam_demo.py如下
[webcam_demo.txt](https://github.com/open-mmlab/mmpose/files/8667530/webcam_demo.txt)

**Comment by ly015** [comment]
1. 请问这个报错是发生在旧版 `demo/webcam_demo.py`，还是新版 `tools/webcam/run_webcam.py`？如果是旧版报错，请试用新版 (https://github.com/open-mmlab/mmpose/tree/master/tools/webcam/configs/examples)。这里新版不是指 mmpose v0.26.0 版本，而是我们提供的一个新的 webcam 工具。
2. 如果还是报错，麻烦请提供一下 AnimalAirplaneDataset 的实现
