### ISSUE TITLE
how to use smoothnet in video pose estimation frame by frame?

### ISSUE THREAD

**Issue by kongyan66** [open-mmlab/mmpose#1344]
I am very interesting in your excellenct work! i have a request: i use 2d pose estimation net to detect motion video frame by frame, leading to the Instability of the skeleton in current frame at times, so ,can smoothnet  solve this proplem? i should how to use it. Looking forward to your reply.

**Comment by ly015** [comment]
Thanks for your interest. In MMPose v0.25.0 we introduced [Smoother module](https://github.com/open-mmlab/mmpose/blob/master/mmpose/core/post_processing/smoother.py) for temporal refinement of the consecutive pose results using configurable filters. Currently, supported filter types include Gaussian, Savizky-Golay, OneEuro, and SmoothNet (see [here](https://github.com/open-mmlab/mmpose/tree/master/mmpose/core/post_processing/temporal_filters)). The documentation of Smoother is in preparation, so you may refer to our [pose tracking demo](https://github.com/open-mmlab/mmpose/blob/master/demo/top_down_pose_tracking_demo_with_mmdet.py#L148) for the use case.

For SmoothNet, currently, we only provide SmoothNet checkpoints trained on Human3.6M for 3D keypoint sequence smoothing. For 2D pose estimation, we would recommend Gaussian filter for offline smoothing and OneEuro filter for online smoothing.

**Comment by kongyan66** [comment]
Thanks a lot!

**Comment by A-qingtongxiaoyou** [comment]
您好，请问我该如何在demo中添加smooth的效果呢？我的命令行似乎没有启动smoothNet的模块。
命令：
`python demo/top_down_pose_tracking_demo_with_mmdet.py \
        demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py \
        https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \
        configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/res50_coco_256x192.py \
        https://download.openmmlab.com/mmpose/top_down/resnet/res50_coco_256x192-ec54d7f3_20200709.pth \
        --video-path data/ex-situ1.mp4 \
        --out-video-root outputs/D1/D1_1_top_down_tracking_single_frame
        --smooth
        --smooth-filter-cfg`

报错：
--smooth：未找到命令
--smooth-filter-cfg：未找到命令
![image](https://user-images.githubusercontent.com/80896381/195040346-5582ec92-4abf-4196-8dbf-ee9503b74080.png)
