### ISSUE TITLE
name '_ctm_lib_name' is not 'defined'

### ISSUE THREAD

**Issue by wz1114841863** [open-mmlab/mmpose#1352]
使用自己的数据集按mmpose官方教程中的配置，在训练到第41个epoch时发生如下错误，定位到发现是tremish包中有错，但是我不明白为什么会发生这种错，而且只有在第40个epoch会发生错误，默认配置中每10个epoch进行val。

![01](https://user-images.githubusercontent.com/60866264/166613297-d4f543ba-d812-4fc2-8858-4a453fa18978.jpg)

**Comment by ly015** [comment]
@zengwang430521 Could you please help check this issue? Is it possible to be caused by an incompatible trimesh version?

**Comment by zengwang430521** [comment]
@wz1114841863 请问可以提供一下你的训练参数和log文件吗?

**Comment by wz1114841863** [comment]
我删除了前四十轮的权重文件和日志，又重新重头开始训练后，没再次碰到这个问题。
