### ISSUE TITLE
Inquiring of image dimensions for the Macaque dataset config

### ISSUE THREAD

**Issue by rubeea** [open-mmlab/mmpose#1353]
Hi,

The image settings in the macaque dataset configs is: image_size=[192, 256]. Can you kindly specify which one is the width and which one is the height. I have images of 256x128 widthxheight respectively so wanted to clarify this step for creating the config for my dataset.

Thanks in advance

**Comment by liqikai9** [comment]
Hi. [192, 256] means [width, height] respectively.

**Comment by liqikai9** [comment]
You can also see another related issue here: https://github.com/open-mmlab/mmpose/issues/968

**Comment by rubeea** [comment]
> Hi. [192, 256] means [width, height] respectively.

Hi,
Ok noted with thanks :)
