### ISSUE TITLE
which smpl model should I download? 

### ISSUE THREAD

**Issue by mls1999725** [open-mmlab/mmpose#1359]
Hi, I'm interested in running demo of 3D body mesh, but I confused about which SMPL model should I download in https://github.com/open-mmlab/mmpose/blob/master/docs/en/tasks/3d_body_mesh.md.
I downloaded the basicModel_neutral_lbs_10_207_0_v1.0.0.pkl and rename it to SMPL_NEUTRAL.pkl, but I got the error

![image](https://user-images.githubusercontent.com/43207078/167102709-7af2328d-c65b-40d6-8bd8-bf26a6f831ba.png)

![image](https://user-images.githubusercontent.com/43207078/167103004-7fc9e1b5-3090-4b59-adfe-f35ec97bb994.png)

**Comment by ly015** [comment]
@zengwang430521 Could you please help with this issue?

**Comment by ly015** [comment]
@mls1999725 Thanks for your interest. Please note that mesh recovery will no longer be supported in MMPose. We have a new codebase [MMHuman3D](https://github.com/open-mmlab/mmhuman3d) that focuses on human shape and pose estimation based on parametric models like SMPL.

**Comment by mls1999725** [comment]
Got it ! Thanks a lot !

**Comment by mls1999725** [comment]
Thanks~
