### ISSUE TITLE
训练收敛过快

### ISSUE THREAD

**Issue by yuan243212790** [open-mmlab/mmpose#1361]
我使用来训练自己数据集，大概1w张图片，为什么在第一个epoch中间突然提高acc，一个epoch后差不多98%acc 就收敛了？请问怎么解决该问题，谢谢。

**Comment by yuan243212790** [comment]
I used to train my own dataset, about 1w images, why did it converge after the first epoch, about 98%acc after one epoch? Please tell me how to solve this problem, thanks.

**Comment by jin-s13** [comment]
What is the test accuracy in epoch1?

**Comment by jin-s13** [comment]
If the test accuracy is also good, then I think you do not need to worry about it.

**Comment by yuan243212790** [comment]
> 如果测试准确度也不错，那我想你不用担心。

first epoch test ap=90%     then i set 10 epoch ,it up to 95%
question is when i train coco datasets it just 70%

**Comment by ly015** [comment]
I think the convergence rate highly depends on the dataset size, pose diversity, and scene complexity. The test accuracy seems good so it's not likely to be an overfitting issue. Maybe you can visualize the model inference results and check if they look good.
