### ISSUE TITLE
请问MMpose未来会和MMtracking做一个融合吗

### ISSUE THREAD

**Issue by ShaneCan** [open-mmlab/mmpose#1365]
比如在topdown算法中加上deepsort跟踪算法等等。。

**Comment by jin-s13** [comment]
see https://github.com/open-mmlab/mmpose/blob/master/demo/top_down_pose_tracking_demo_with_mmtracking.py

**Comment by ShaneCan** [comment]
> see https://github.com/open-mmlab/mmpose/blob/master/demo/top_down_pose_tracking_demo_with_mmtracking.py

谢谢，未来在webcam API中会加入吗？因为我发现在识别同一种类的目标时，无法分辨他们的ID，而是将他们的pose_results信息均放入了一个列表中（label相同），导致无法分离单个目标的具体数据

**Comment by jin-s13** [comment]
有这个计划
