### ISSUE TITLE
关于voxelpose的demo中关于相机外参的变量‘c2w’和‘w2c’不一致。

### ISSUE THREAD

**Issue by helcpp** [open-mmlab/mmpose#1369]
您好，非常感谢您的demo！
我发现两个地方的变量命名出现了不一致的现象：
（1）body3d_multiview_detect_and_regress_img_demo.py文件下的get_panoptic_camera_parameters()函数。从json文件中读入的是‘外参是w2c’，保存到内存中的是’c2w‘。
（2）在mmpose\core\camera\single_camera.py 和 mmpose\core\camera\single_camera_torch.py中，从内存中读取的也应该是“c2w”，可这里的代码却是R.T，即“w2c”：
self.param['R_c2w'] = R.T

请问这里是我的理解出现了偏差，还是命名出现了问题。

**Comment by ly015** [comment]
你好。在 (1) 和 (2) 中分别使用了 [`SimpleCamera`](https://github.com/open-mmlab/mmpose/blob/master/mmpose/core/camera/single_camera.py) 和 [`SimpleCameraTorch`](https://github.com/open-mmlab/mmpose/blob/master/mmpose/core/camera/single_camera_torch.py)，它们对相机参数的定义是一致的，即 ‘c2w’ 表示从相机系到世界系的变换，‘w2c’ 反之。
`self.param['R_c2w'] = R.T` 中的转置，在(1)(2)使用的两种 camera 接口中都有，其意义不是指变换方向取反，而是因为关键点通常表示为行向量，为了避免每次坐标转换时需要转置坐标矩阵，我们提前将变换矩阵转置，并用 X @ M + T 的方式做坐标变换。这在 `SimpleCamera` 和 `SimpleCameraTorch` 中也是一致的。

**Comment by helcpp** [comment]
> 你好。在 (1) 和 (2) 中分别使用了 [`SimpleCamera`](https://github.com/open-mmlab/mmpose/blob/master/mmpose/core/camera/single_camera.py) 和 [`SimpleCameraTorch`](https://github.com/open-mmlab/mmpose/blob/master/mmpose/core/camera/single_camera_torch.py)，它们对相机参数的定义是一致的，即 ‘c2w’ 表示从相机系到世界系的变换，‘w2c’ 反之。 `self.param['R_c2w'] = R.T` 中的转置，在(1)(2)使用的两种 camera 接口中都有，其意义不是指变换方向取反，而是因为关键点通常表示为行向量，为了避免每次坐标转换时需要转置坐标矩阵，我们提前将变换矩阵转置，并用 X @ M + T 的方式做坐标变换。这在 `SimpleCamera` 和 `SimpleCameraTorch` 中也是一致的。

谢谢回复，我明白了，是我将转置和变换方向取反这两种操作搞混了。
主要原因是我用了M@X+T的方式来理解坐标变换。我将代码修改为了M@X+T的方式运行，在这种方式下M是不需要转置，但是需要对关键点进行转置。两种方式最终的结果是一致的。
