### ISSUE TITLE
How to use smoothnet on 3D mesh data like smpl

### ISSUE THREAD

**Issue by JiahongWu1995** [open-mmlab/mmpose#1370]
Hello,I am very interesting in your excellenct work!  i would like to know how to use smoothnet on smpl data, can you provide a demo?thank you!

**Comment by ly015** [comment]
Thanks for your interest. Mesh recovery in MMPose is no longer maintained and will be deprecated in the future. We have released [MMHuman3d](https://github.com/open-mmlab/mmhuman3d) for human mesh recovery and other pose and shape estimation tasks based on parametric models like SMPL. And the support of SmoothNet for 3D mesh is underway in MMHuman3D. Please stay tuned for their updates :)

**Comment by JiahongWu1995** [comment]
thank you!
