### ISSUE TITLE
想用文件记录相机检测中的fps,result_lag应该如何操作呢？

### ISSUE THREAD

**Issue by ShaneCan** [open-mmlab/mmpose#1371]
发现fps,result_lag位于helper_nodes中，我在ModelResultBindingNode中加入print语句打印self.frame_fps，self.result_lag，发现运行run_webcam.py时没有任何效果，想请问大神如何才能记录下来呢？感谢万分！！

**Comment by ly015** [comment]
建议在 ``MonitorNode`` 中尝试把 ``route_info`` print 出来或者保存在文件里。

**Comment by ShaneCan** [comment]
谢谢
