### ISSUE TITLE
[GLCC] GitLink Code Camp (首届 CCF GitLink 开源编程夏令营)

### ISSUE THREAD

**Issue by ly015** [open-mmlab/mmpose#1387]
The issue is about the first GitLink Code Camp activity.
Related link: https://mp.weixin.qq.com/s/upVI-2TQ0ezQGpzhDiF3Pg

# 题目名称

基于 MMPose 实现前沿姿态估计算法

# 题目描述

## 题目简介

MMPose 是 OpenMMLab 中的姿态估计算法库，目前已经支持了近 30 个算法和 300+ 预训练模型，涵盖了人体、人脸、人手、动物等多类目标的姿态估计。秉承 OpenMMLab 系列的结构化框架设计，MMPose 很适合作为姿态估计算法复现和创新的平台。 通过在 MMPose 中实现前沿姿态估计算法，你将可以了解姿态估计领域的最新进展，熟练掌握 MM 系列框架使用和开发，并积累深度学习相关的学术及工程经验。

## 编码任务

复现姿态估计前沿算法，包括但不限于：
- 2D 关键点检测
- 3D 关键点检测
- 轻量化姿态估计算法
- 多视角姿态估计
- DensePose

## 技能要求和编程语言
- Python
- PyTorch
- 一定的论文阅读能力
- 对姿态估计有一定的了解

# 预期成果

- 完成算法复现工作，达到论文精度
- 完成算法可视化 demo

# 导师及联系方式

GitHub ID：[ly015](https://github.com/ly015)
Email：openmmlab@gmail.com
活动微信交流群：

<div align="center">
<img src="https://user-images.githubusercontent.com/15977946/169828574-a67d2692-a67d-4b8f-9297-84bd87626e59.png" width="250"/>
</div>

**Comment by zhikai-zhao-chn** [comment]
您好，二维码失效了。

**Comment by txytju** [comment]
Densepose算法复现完成了吗?

**Comment by ly015** [comment]
@txytju 你好，DensePose 是可选课题之一，不过最终参加活动同学并未选择 DensePose。我们有计划未来在 MMPose 中支持 DensePose，具体时间还未确定，欢迎关注 MMPose 更新信息
