### ISSUE TITLE
Causal Mode for VideoPose3D

### ISSUE THREAD

**Issue by darcula1993** [open-mmlab/mmpose#1391]
I would like to try causal mode training for videoPose3D, specifically, using past 27 frames to predict last frame 3d pose.
I found parameter "casual"  could be set in data_cfg and tcn backbones. Which one of them should be set to "True"?

My understanding is,data_cfg control the data flow, so if I set causal = True in data_cfg,  the preprocessing pipeline will output 
sequence like [i-27,i-26,...,i-1] to predict frame i.  In this case, I  should not set causal = True in Tcn block. Is that correct?

**Comment by darcula1993** [comment]
Thank you for reply!
Yes I found the illustration, and here is my understanding: at time i, my input sequence only include past frames [i-26,i-25,i-24,...,i-1,i] ( which all have been observed) , it doesn't matter if previous frame i - k can "see"  future frame or not, since there is no future frame in the input sequence.

One inference will take one sequence and ouput one frame 3d pose,right? So, if input sequence only include past frames info, seems that both symmetric conv and causal conv can do online inference.

**Comment by ly015** [comment]
Yes, the causal mode of TCN is not exactly about the constraint of not seeing future frames, but the model architecture. Specifically, It determines the temporal alignment of the input and output sequences of convolutional layers. For example, assume a convolution layer has a kernel size of 3, and its input is $[x_1, x_2, x_3]$ and output is $y$. In the causal mode, `y` will be added to $x_3$ when calculating the summation of input and residual. However, in the symmetric mode, $y$ will be added to $x_2$.

**Comment by darcula1993** [comment]
get it! thank you very much!
