### ISSUE TITLE
Any ONNX model exported  method of litehrnet or some demo related？

### ISSUE THREAD

**Issue by 2050airobert** [open-mmlab/mmpose#1400]
hi，
     请问下，是否有litehrnet的demo，以及相关导出为onnx模型的例子？
     具体是哪个版本里面会有？ 我只看到了hrnet，但是必须litehrnet才行。多谢

BR

**Comment by jin-s13** [comment]
demo 可以照着这个  https://github.com/open-mmlab/mmpose/blob/master/demo/docs/2d_human_pose_demo.md  改一下

onnx模型导出，可以试一下 mmdeploy

**Comment by 2050airobert** [comment]
不需要重新训练吧？

**Comment by 2050airobert** [comment]
hi，
Do we need retraining the model like litehrnet etc after changing the code as what you did？
I have changed the code of litehrnet.py ，yet still the same error？ what was wrong ？
what should I do after change the code as you said above？ It did not work at all！
Maybe I should build it or any other operation to make the change effective？
BR

**Comment by 2050airobert** [comment]
hi，
如果我想改变litehrnet.py内容比如模型结构，那我怎样做才能重新把litehrnet模型build 进mmpose？
然后使用from mmpose import xxx的时候，就不是之前的litehrnet结构，而是我刚才更改的结构呢？
多谢

**Comment by jin-s13** [comment]
可以参考教程 https://github.com/open-mmlab/mmpose/blob/master/docs/zh_cn/tutorials/4_new_modules.md
