### ISSUE TITLE
MMPose 姿态估计创意 Demo 大赛结果提交

### ISSUE THREAD

**Issue by zhaoxiaoliu** [open-mmlab/mmpose#1407]
# 结果提交
参赛的小伙伴们需要将结果按照格式要求填写在下方表格中。

|    [1. 项目名称](项目链接)           |  [2. 项目名称](项目链接)          |   [3. 项目名称](项目链接)         | [4. 项目名称](项目链接)              |
| ---------- | ---------------- | -------------------| ----------------------- |
|                 |                         |                             |                                   |
|  [5. 项目名称](项目链接)     |  [6. 项目名称](项目链接)     |  [7. 项目名称](项目链接)        |   [8. 项目名称](项目链接)         |
|                 |                         |                             |                                   |

**Comment by kevinfu1717** [comment]
基于实时手部关键点识别实现在平面上弹钢琴 https://github.com/open-mmlab/mmpose/issues/1407

**Comment by tempstudio** [comment]
项目名称：搭砖块XR / 节奏太极XR：通过MMPOSE和姿态估计实现体感游戏
演示视频：

https://user-images.githubusercontent.com/49735574/178384644-58a2270a-065b-4cf6-98fd-024705d3d805.mov

[高清地址](https://raw.githubusercontent.com/tempstudio/mmpose-contest-brickbuilder-xr/main/video/Brickbuilder%20XR%20HD.mp4)


https://user-images.githubusercontent.com/49735574/178384658-828e188e-267f-4bb0-a460-3c14fa1de9a5.mp4

[高清地址](https://raw.githubusercontent.com/tempstudio/mmpose-contest-brickbuilder-xr/main/video/Rhythm%20Taichi%20XR%201%20HD.mp4)

使用文档：https://github.com/tempstudio/mmpose-contest-brickbuilder-xr/blob/main/README_zh.md 
主连接：https://github.com/tempstudio/mmpose-contest-brickbuilder-xr

**Comment by lufeili** [comment]
项目名称：双人武术格斗

项目地址：https://github.com/lufeili/kungfu

B站视频链接：https://www.bilibili.com/video/BV12t4y147Tw?p=1

**Comment by WINDSKY45** [comment]
项目名称：基于手部关键点识别的打地鼠游戏

项目地址：https://github.com/WINDSKY45/mmpose-demo

**Comment by xiaoliuzz** [comment]
1
