### ISSUE TITLE
Demo: Human Pose vs Pose Tracking 

### ISSUE THREAD

**Issue by yepw** [open-mmlab/mmpose#1409]
Hi, I was wondering what the differences are between [Human Pose Demos](https://mmpose.readthedocs.io/en/latest/demo.html#d-human-pose-demo) and  [Pose Tracking Demos](https://mmpose.readthedocs.io/en/latest/demo.html#d-pose-tracking-demo). The results look pretty similar. Does Pose Tracking have better accuracy for videos?

**Comment by ly015** [comment]
They both perform object detection and pose estimation for each frame.
Pose tracking will track the identities of the objects over frames so you can get a tracked let of a person or object. Besides, the pose tracking demo uses a smoother to refine the pose estimation result so it will be more stable.
