### ISSUE TITLE
incorrect pre-trained model link

### ISSUE THREAD

**Issue by khanhha** [open-mmlab/mmpose#141]
Hello,

Thank you very much for training the whole body COCO model.

Could you please check if the link to [dark_pose_hrnet_w48+](https://github.com/open-mmlab/mmpose/blob/master/configs/top_down/darkpose/coco-wholebody/hrnet_w48_coco_wholebody_384x288_dark.py) is correct?

Here is the [download link](https://openmmlab.oss-accelerate.aliyuncs.com/mmpose/top_down/hrnet/hrnet_w32_coco_256x192-c78dce93_20200708.pth) I found in https://mmpose.readthedocs.io/en/latest/top_down_models.html

The config name is **hrnet_w48_coco_wholebody_384x288_dark**, but the model name that I got is **hrnet_w32_coco_256x192-c78dce93_20200708.pth**

Thanks

**Comment by jin-s13** [comment]
Thanks for reporting. I will update the download link.

**Comment by khanhha** [comment]
You guys are so generous. 
Your work is very helpful for me.
Thanks again.
Best

**Comment by innerlee** [comment]
thanks for the kind words :smiley: 
have you stared the repo?

**Comment by khanhha** [comment]
oh right. I completely forgot about that. sorry :dancers:
