### ISSUE TITLE
About the bounding boxes in WFLW dataset

### ISSUE THREAD

**Issue by biyoml** [open-mmlab/mmpose#1415]
Hello,
I found that the face bounding boxes in your WFLW annotations are different from the ones provided by the official annotations.
How did you generate those boxes?

**Comment by jin-s13** [comment]
Could you please describe the difference in more details?
We follow the setting of https://github.com/HRNet/HRNet-Facial-Landmark-Detection for data preparation.

**Comment by biyoml** [comment]
I figure it out. It is answered in https://github.com/HRNet/HRNet-Facial-Landmark-Detection/issues/3
They computed the box by finding a smallest box that can include all the landmarks.
Thank you!
