### ISSUE TITLE
Model Zoo for hand keypoints not linked.

### ISSUE THREAD

**Issue by parthapn98** [open-mmlab/mmpose#1417]
Could you please provide or guide me on how to download the checkpoints for the hand kepoint detection models

The checkpoints files for most of the hand keypoint detectors are not linked in the zoo.

![image](https://user-images.githubusercontent.com/77120537/172327905-8c5a4bfb-55f0-4f90-b174-e116b62ca605.png)

The overview page doesnot contain links for download , just mentions 29 checkpoints are available

![image](https://user-images.githubusercontent.com/77120537/172328263-3c49b1db-c917-421e-a0f9-f1c8b938d785.png)

I was only able to download the onehand10k checkpoint from the link provided in the demo md file.
![image](https://user-images.githubusercontent.com/77120537/172328578-e5525851-626f-42a4-9233-495fb15b4e6a.png)

**Comment by parthapn98** [comment]
Thank you this helped. I was able to trace the required checkpoint files in readthedocs under 'modelzoo by paper'

**Comment by ly015** [comment]
Fixed in #1416
