### ISSUE TITLE
Custom Dataset: 'xxxDataset is not in the dataset registry'

### ISSUE THREAD

**Issue by amartincirera** [open-mmlab/mmpose#1429]
Hi,

Thank you so much for your work.

After to move the last version of mmpose (0.27.0). I have the following issue:

'xxxDataset is not in the dataset registry'

But it is working with 0.25.1 version.

To add a new dataset I did the following steps:

- New dataset file: mmpose/configs/_base_/new_dataset.py 
- Config file: mmpose/configs/hrnet_w32_new_data_512x512.py
- Created mmpose/mmpose/datasets/datasets/new_dataset/ __init__.py
- Created mmpose/mmpose/datasets/datasets/new_dataset/ new_dataset.py
- Add class into mmpose/mmpose/datasets/datasets: __init__.py
- Add class into mmpose/mmpose/datasets: __init__.py

I don't know if I did something wrong, but after updating to the latest version, I can't add the new dataset.

Thank you so much.

**Comment by liqikai9** [comment]
It seems that your procedures are just right. 

> But it is working with 0.25.1 version.

Did you do the same modifications to the 0.25.1 and 0.27.0 versions? Could you please provide more information? 

For example, did you add this line `@DATASETS.register_module()` upon the definition of your custom dataset like this:

```python
@DATASETS.register_module()
class TopDownCocoDataset(Kpt2dSviewRgbImgTopDownDataset):
```

FYI, you can double-check the tutorial [here](https://github.com/open-mmlab/mmpose/blob/master/docs/en/tutorials/2_new_dataset.md).

**Comment by amartincirera** [comment]
Sure!

- New dataset file: mmpose/configs/base/horse.py

`dataset_info = dict(
    dataset_name='horse10',
    paper_info=dict(
        author='Albert Martin Cirera',
        title='Pose estimation in horses' ,
        container='',
        year='2022',
        homepage='',
    ),
    keypoint_info={
        0:
        dict(name='Nose', id=0, color=[0,140,255], type='upper', swap=''),
        1:
        dict(name='Withers', id=1, color=[0,255,255], type='upper', swap=''),
        2:
        dict(name='Tail', id=2, color=[180,105,255], type='upper', swap=''),
        3:
        dict(name='Right_ear', id=3, color=[144,238,144], type='upper', swap=''),
        4:
        dict(name='Left_ear', id=4, color=[0,100,0], type='upper', swap=''),
        5:
        dict(name='Right_front', id=5, color=[128,128,180], type='lower', swap=''),
        6:
        dict(name='Left_front', id=6, color=[0,0,139], type='lower', swap=''),
        7:
        dict(name='Right_hind', id=7, color=[230,216,173], type='lower', swap=''),
        8:
        dict(name='Left_hind', id=8, color=[139,0,0], type='lower', swap='')
    },
    skeleton_info={
        0:
        dict(link=('Nose', 'Withers'), id=0, color=[0, 0, 0]),
        1:
        dict(link=('Withers', 'Tail'), id=1, color=[0, 0, 0]),
        2:
        dict(link=('Withers', 'Right_ear'), id=2, color=[0, 0, 0]),
        3:
        dict(link=('Withers', 'Left_ear'), id=3, color=[0, 0, 0]),
        4:
        dict(link=('Withers', 'Right_front'), id=4, color=[0, 0, 0]),
        5:
        dict(link=('Withers', 'Left_front'), id=5, color=[0, 0, 0]),
        6:
        dict(link=('Tail', 'Right_hind'), id=6, color=[0, 0, 0]),
        7:
        dict(link=('Tail', 'Left_hind'), id=7, color=[0, 0, 0])
    },
    joint_weights=[1.] * 9,
    sigmas=[])`

- Config file: mmpose/configs/hrnet_w32_horse_512x512.py

`_base_ = [
    '_base_/default_runtime.py',
    '_base_/datasets/horse.py'
]
checkpoint_config = dict(interval=10)
evaluation = dict(interval=500, metric='mAP', save_best='AP')

work_dir = 'work_dirs/hrnet_regression'

gpu_ids = range(1)

create_symlink = False

optimizer = dict(
    type='Adam',
    lr=0.0015,
)
optimizer_config = dict(grad_clip=None)
# learning policy
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.001,
    step=[200, 260])
total_epochs = 300
channel_cfg = dict(
    dataset_joints=9,
    dataset_channel=[
        [0, 1, 2, 3, 4, 5, 6, 7, 8],
    ],
    inference_channel=[
        0, 1, 2, 3, 4, 5, 6, 7, 8
    ])

data_cfg = dict(
    image_size=512,
    base_size=256,
    base_sigma=2,
    heatmap_size=[128],
    num_joints=channel_cfg['dataset_joints'],
    dataset_channel=channel_cfg['dataset_channel'],
    inference_channel=channel_cfg['inference_channel'],
    num_scales=1,
    scale_aware_sigma=False,
)

# model settings
model = dict(
    type='AssociativeEmbedding',
    pretrained='https://download.openmmlab.com/mmpose/'
    'pretrain_models/hrnet_w32-36af842e.pth',
    backbone=dict(
        type='HRNet',
        in_channels=3,
        extra=dict(
            stage1=dict(
                num_modules=1,
                num_branches=1,
                block='BOTTLENECK',
                num_blocks=(4, ),
                num_channels=(64, )),
            stage2=dict(
                num_modules=1,
                num_branches=2,
                block='BASIC',
                num_blocks=(4, 4),
                num_channels=(32, 64)),
            stage3=dict(
                num_modules=4,
                num_branches=3,
                block='BASIC',
                num_blocks=(4, 4, 4),
                num_channels=(32, 64, 128)),
            stage4=dict(
                num_modules=3,
                num_branches=4,
                block='BASIC',
                num_blocks=(4, 4, 4, 4),
                num_channels=(32, 64, 128, 256))),
    ),
    keypoint_head=dict(
        type='AESimpleHead',
        in_channels=32,
        num_joints=9,
        num_deconv_layers=0,
        tag_per_joint=True,
        with_ae_loss=[True],
        extra=dict(final_conv_kernel=1, ),
        loss_keypoint=dict(
            type='AdaptiveWingLoss',
            num_joints=9,
            num_stages=1,
            ae_loss_type='exp',
            with_ae_loss=[True],
            push_loss_factor=[0.001],
            pull_loss_factor=[0.001],
            with_heatmaps_loss=[True],
            heatmaps_loss_factor=[1.0])),
    train_cfg=dict(),
    test_cfg=dict(
        num_joints=channel_cfg['dataset_joints'],
        max_num_people=2,
        scale_factor=[1],
        with_heatmaps=[True],
        with_ae=[True],
        project2image=True,
        align_corners=False,
        nms_kernel=5,
        nms_padding=2,
        tag_per_joint=True,
        detection_threshold=0.1,
        tag_threshold=1,
        use_detection_val=True,
        ignore_too_much=False,
        adjust=True,
        refine=True,
        flip_test=True))

train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='BottomUpRandomAffine',
        rot_factor=30,
        scale_factor=[0.75, 1.5],
        scale_type='short',
        trans_factor=40),
    dict(type='BottomUpRandomFlip', flip_prob=0.5),
    dict(type='ToTensor'),
    dict(
        type='NormalizeTensor',
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]),
    dict(
        type='BottomUpGenerateTarget',
        sigma=2,
        max_num_people=30,
    ),
    dict(
        type='Collect',
        keys=['img', 'joints', 'targets', 'masks'],
        meta_keys=[]),
]

val_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='BottomUpGetImgSize', test_scale_factor=[1]),
    dict(
        type='BottomUpResizeAlign',
        transforms=[
            dict(type='ToTensor'),
            dict(
                type='NormalizeTensor',
                mean=[0.485, 0.456, 0.406],
                std=[0.229, 0.224, 0.225]),
        ]),
    dict(
        type='Collect',
        keys=['img'],
        meta_keys=[
            'image_file', 'aug_data', 'test_scale_factor', 'base_size',
            'center', 'scale', 'flip_index'
        ]),
]

test_pipeline = val_pipeline

data_root = '/home/martina/samba_shareGPU/KBPDetector/data'
data = dict(
    workers_per_gpu=2,
    train_dataloader=dict(samples_per_gpu=24),
    val_dataloader=dict(samples_per_gpu=1),
    test_dataloader=dict(samples_per_gpu=1),
    train=dict(
        type='BottomUpHorseDataset',
        ann_file=f'{data_root}/json_files/horses_skeleton3.json',
        img_prefix=f'{data_root}/datasets/horses/',
        data_cfg=data_cfg,
        pipeline=train_pipeline,
        dataset_info={{_base_.dataset_info}}),
    val=dict(
        type='BottomUpHorseDataset',
        ann_file=f'{data_root}/json_files/test.json',
        img_prefix=f'{data_root}/datasets/test/',
        data_cfg=data_cfg,
        pipeline=val_pipeline,
        dataset_info={{_base_.dataset_info}}),
    test=dict(
        type='BottomUpHorseDataset',
        ann_file=f'{data_root}/json_files/test.json',
        img_prefix=f'{data_root}/datasets/test/',
        data_cfg=data_cfg,
        pipeline=test_pipeline,
        dataset_info={{_base_.dataset_info}}),
)`

- Created mmpose/mmpose/datasets/datasets/horse/ init.py

`# Copyright (c) OpenMMLab. All rights reserved.
from .bottom_up_horse import BottomUpHorseDataset

__all__ = [
    'BottomUpHorseDataset'
]# Copyright (c) OpenMMLab. All rights reserved.
import os.path as osp
import tempfile
import warnings
from collections import OrderedDict, defaultdict

import json_tricks as json
import numpy as np
from mmcv import Config, deprecated_api_warning
from xtcocotools.cocoeval import COCOeval

from mmpose.core.post_processing import oks_nms, soft_oks_nms
from mmpose.datasets.builder import DATASETS
from mmpose.datasets.datasets.base import Kpt2dSviewRgbImgBottomUpDataset


@DATASETS.register_module(name='BottomUpHorseDataset')
class BottomUpHorseDataset(Kpt2dSviewRgbImgBottomUpDataset):
    """Horse dataset for bottom-up pose estimation.

    The dataset loads raw features and apply specified transforms
    to return a dict containing the image tensors and other information.

    horse keypoint indexes::

        0: 'Nose',
        1: 'Withers',
        2: 'Tail',
        3: 'Right_ear',
        4: 'Left_ear',
        5: 'Right_front',
        6: 'Left_front',
        7: 'Right_hind',
        8: 'Left_hind',

    Args:
        ann_file (str): Path to the annotation file.
        img_prefix (str): Path to a directory where images are held.
            Default: None.
        data_cfg (dict): config
        pipeline (list[dict | callable]): A sequence of data transforms.
        dataset_info (DatasetInfo): A class containing all dataset info.
        test_mode (bool): Store True when building test or
            validation dataset. Default: False.
    """

    def __init__(self,
                 ann_file,
                 img_prefix,
                 data_cfg,
                 pipeline,
                 dataset_info=None,
                 test_mode=False):

        if dataset_info is None:
            warnings.warn(
                'dataset_info is missing. '
                'Check https://github.com/open-mmlab/mmpose/pull/663 '
                'for details.', DeprecationWarning)
            cfg = Config.fromfile('configs/_base_/datasets/horse.py')
            dataset_info = cfg._cfg_dict['dataset_info']

        super().__init__(
            ann_file,
            img_prefix,
            data_cfg,
            pipeline,
            dataset_info=dataset_info,
            test_mode=test_mode)

        self.ann_info['use_different_joint_weights'] = False
        print(f'=> num_images: {self.num_images}')

    def _get_single(self, idx):
        """Get anno for a single image.

        Args:
            idx (int): image idx

        Returns:
            dict: info for model training
        """
        coco = self.coco
        img_id = self.img_ids[idx]
        ann_ids = coco.getAnnIds(imgIds=img_id)
        anno = coco.loadAnns(ann_ids)

        mask = self._get_mask(anno, idx)
        anno = [
            obj.copy() for obj in anno
            if obj['iscrowd'] == 0 or obj['num_keypoints'] > 0
        ]

        joints = self._get_joints(anno)
        mask_list = [mask.copy() for _ in range(self.ann_info['num_scales'])]
        joints_list = [
            joints.copy() for _ in range(self.ann_info['num_scales'])
        ]

        db_rec = {}
        db_rec['dataset'] = self.dataset_name
        db_rec['image_file'] = osp.join(self.img_prefix, self.id2name[img_id])
        db_rec['mask'] = mask_list
        db_rec['joints'] = joints_list

        return db_rec

    def _get_joints(self, anno):
        """Get joints for all people in an image."""
        num_people = len(anno)

        if self.ann_info['scale_aware_sigma']:
            joints = np.zeros((num_people, self.ann_info['num_joints'], 4),
                              dtype=np.float32)
        else:
            joints = np.zeros((num_people, self.ann_info['num_joints'], 3),
                              dtype=np.float32)

        for i, obj in enumerate(anno):
            joints[i, :, :3] = \
                np.array(obj['keypoints']).reshape([-1, 3])
            if self.ann_info['scale_aware_sigma']:
                # get person box
                box = obj['bbox']
                size = max(box[2], box[3])
                sigma = size / self.base_size * self.base_sigma
                if self.int_sigma:
                    sigma = int(np.ceil(sigma))
                assert sigma > 0, sigma
                joints[i, :, 3] = sigma

        return joints

    @deprecated_api_warning(name_dict=dict(outputs='results'))
    def evaluate(self, results, res_folder=None, metric='mAP', **kwargs):
        """Evaluate coco keypoint results. The pose prediction results will be
        saved in ``${res_folder}/result_keypoints.json``.

        Note:
            - num_people: P
            - num_keypoints: K

        Args:
            results (list[dict]): Testing results containing the following
                items:

                - preds (list[np.ndarray(P, K, 3+tag_num)]): \
                    Pose predictions for all people in images.
                - scores (list[P]): List of person scores.
                - image_path (list[str]): For example, ['coco/images/\
                    val2017/000000397133.jpg']
                - heatmap (np.ndarray[N, K, H, W]): model outputs.

            res_folder (str, optional): The folder to save the testing
                results. If not specified, a temp folder will be created.
                Default: None.
            metric (str | list[str]): Metric to be performed. Defaults: 'mAP'.

        Returns:
            dict: Evaluation results for evaluation metric.
        """
        metrics = metric if isinstance(metric, list) else [metric]
        allowed_metrics = ['mAP']
        for metric in metrics:
            if metric not in allowed_metrics:
                raise KeyError(f'metric {metric} is not supported')

        if res_folder is not None:
            tmp_folder = None
            res_file = osp.join(res_folder, 'result_keypoints.json')
        else:
            tmp_folder = tempfile.TemporaryDirectory()
            res_file = osp.join(tmp_folder.name, 'result_keypoints.json')

        preds = []
        scores = []
        image_paths = []

        for result in results:
            preds.append(result['preds'])
            scores.append(result['scores'])
            image_paths.append(result['image_paths'][0])

        kpts = defaultdict(list)
        # iterate over images
        for idx, _preds in enumerate(preds):
            str_image_path = image_paths[idx]
            image_id = self.name2id[osp.basename(str_image_path)]
            # iterate over people
            for idx_person, kpt in enumerate(_preds):
                # use bbox area
                area = (np.max(kpt[:, 0]) - np.min(kpt[:, 0])) * (
                    np.max(kpt[:, 1]) - np.min(kpt[:, 1]))

                kpts[image_id].append({
                    'keypoints': kpt[:, 0:3],
                    'score': scores[idx][idx_person],
                    'tags': kpt[:, 3],
                    'image_id': image_id,
                    'area': area,
                })

        valid_kpts = []
        for img in kpts.keys():
            img_kpts = kpts[img]
            if self.use_nms:
                nms = soft_oks_nms if self.soft_nms else oks_nms
                keep = nms(img_kpts, self.oks_thr, sigmas=self.sigmas)
                valid_kpts.append([img_kpts[_keep] for _keep in keep])
            else:
                valid_kpts.append(img_kpts)

        self._write_coco_keypoint_results(valid_kpts, res_file)

        info_str = self._do_python_keypoint_eval(res_file)
        name_value = OrderedDict(info_str)

        if tmp_folder is not None:
            tmp_folder.cleanup()

        return name_value

    def _write_coco_keypoint_results(self, keypoints, res_file):
        """Write results into a json file."""
        data_pack = [{
            'cat_id': self._class_to_coco_ind[cls],
            'cls_ind': cls_ind,
            'cls': cls,
            'ann_type': 'keypoints',
            'keypoints': keypoints
        } for cls_ind, cls in enumerate(self.classes)
                     if not cls == '__background__']

        results = self._coco_keypoint_results_one_category_kernel(data_pack[0])

        with open(res_file, 'w') as f:
            json.dump(results, f, sort_keys=True, indent=4)

    def _coco_keypoint_results_one_category_kernel(self, data_pack):
        """Get coco keypoint results."""
        cat_id = data_pack['cat_id']
        keypoints = data_pack['keypoints']
        cat_results = []

        for img_kpts in keypoints:
            if len(img_kpts) == 0:
                continue

            _key_points = np.array(
                [img_kpt['keypoints'] for img_kpt in img_kpts])
            key_points = _key_points.reshape(-1,
                                             self.ann_info['num_joints'] * 3)

            for img_kpt, key_point in zip(img_kpts, key_points):
                kpt = key_point.reshape((self.ann_info['num_joints'], 3))
                left_top = np.amin(kpt, axis=0)
                right_bottom = np.amax(kpt, axis=0)

                w = right_bottom[0] - left_top[0]
                h = right_bottom[1] - left_top[1]

                cat_results.append({
                    'image_id': img_kpt['image_id'],
                    'category_id': cat_id,
                    'keypoints': key_point.tolist(),
                    'score': img_kpt['score'],
                    'bbox': [left_top[0], left_top[1], w, h]
                })

        return cat_results

    def _do_python_keypoint_eval(self, res_file):
        """Keypoint evaluation using COCOAPI."""

        stats_names = [
            'AP', 'AP .5', 'AP .75', 'AP (M)', 'AP (L)', 'AR', 'AR .5',
            'AR .75', 'AR (M)', 'AR (L)'
        ]

        with open(res_file, 'r') as file:
            res_json = json.load(file)
            if not res_json:
                info_str = list(zip(stats_names, [
                    0,
                ] * len(stats_names)))
                return info_str

        coco_det = self.coco.loadRes(res_file)
        coco_eval = COCOeval(self.coco, coco_det, 'keypoints', self.sigmas)
        coco_eval.params.useSegm = None
        coco_eval.evaluate()
        coco_eval.accumulate()
        coco_eval.summarize()

        info_str = list(zip(stats_names, coco_eval.stats))

        return info_str`

- Created mmpose/mmpose/datasets/datasets/horse/ new_dataset.py

``

- Add class into mmpose/mmpose/datasets/datasets: init.py

`# Copyright (c) OpenMMLab. All rights reserved.
from ...deprecated import (TopDownFreiHandDataset, TopDownOneHand10KDataset,
                           TopDownPanopticDataset)
from .animal import (AnimalATRWDataset, AnimalFlyDataset, AnimalHorse10Dataset,
                     AnimalLocustDataset, AnimalMacaqueDataset,
                     AnimalPoseDataset, AnimalZebraDataset)
from .body3d import (Body3DH36MDataset, Body3DMviewDirectCampusDataset,
                     Body3DMviewDirectPanopticDataset,
                     Body3DMviewDirectShelfDataset)
from .bottom_up import (BottomUpAicDataset, BottomUpCocoDataset,
                        BottomUpCocoWholeBodyDataset, BottomUpCrowdPoseDataset,
                        BottomUpMhpDataset)
from .face import (Face300WDataset, FaceAFLWDataset, FaceCocoWholeBodyDataset,
                   FaceCOFWDataset, FaceWFLWDataset)
from .fashion import DeepFashionDataset
from .gesture import NVGestureDataset
from .hand import (FreiHandDataset, HandCocoWholeBodyDataset,
                   InterHand2DDataset, InterHand3DDataset, OneHand10KDataset,
                   PanopticDataset)
from .mesh import (MeshAdversarialDataset, MeshH36MDataset, MeshMixDataset,
                   MoshDataset)
from .top_down import (TopDownAicDataset, TopDownCocoDataset,
                       TopDownCocoWholeBodyDataset, TopDownCrowdPoseDataset,
                       TopDownH36MDataset, TopDownHalpeDataset,
                       TopDownJhmdbDataset, TopDownMhpDataset,
                       TopDownMpiiDataset, TopDownMpiiTrbDataset,
                       TopDownOCHumanDataset, TopDownPoseTrack18Dataset,
                       TopDownPoseTrack18VideoDataset)
from .horse import (BottomUpHorseDataset)

__all__ = [
    'TopDownCocoDataset', 'BottomUpCocoDataset', 'BottomUpMhpDataset',
    'BottomUpAicDataset', 'BottomUpCocoWholeBodyDataset', 'TopDownMpiiDataset',
    'TopDownMpiiTrbDataset', 'OneHand10KDataset', 'PanopticDataset',
    'HandCocoWholeBodyDataset', 'FreiHandDataset', 'InterHand2DDataset',
    'InterHand3DDataset', 'TopDownOCHumanDataset', 'TopDownAicDataset',
    'TopDownCocoWholeBodyDataset', 'MeshH36MDataset', 'MeshMixDataset',
    'MoshDataset', 'MeshAdversarialDataset', 'TopDownCrowdPoseDataset',
    'BottomUpCrowdPoseDataset', 'TopDownFreiHandDataset',
    'TopDownOneHand10KDataset', 'TopDownPanopticDataset',
    'TopDownPoseTrack18Dataset', 'TopDownJhmdbDataset', 'TopDownMhpDataset',
    'DeepFashionDataset', 'Face300WDataset', 'FaceAFLWDataset',
    'FaceWFLWDataset', 'FaceCOFWDataset', 'FaceCocoWholeBodyDataset',
    'Body3DH36MDataset', 'AnimalHorse10Dataset', 'AnimalMacaqueDataset',
    'AnimalFlyDataset', 'AnimalLocustDataset', 'AnimalZebraDataset',
    'AnimalATRWDataset', 'AnimalPoseDataset', 'TopDownH36MDataset',
    'TopDownHalpeDataset', 'TopDownPoseTrack18VideoDataset',
    'Body3DMviewDirectPanopticDataset', 'Body3DMviewDirectShelfDataset',
    'Body3DMviewDirectCampusDataset', 'NVGestureDataset', 'BottomUpHorseDataset'
]`

- Add class into mmpose/mmpose/datasets: init.py

`# Copyright (c) OpenMMLab. All rights reserved.
from .builder import DATASETS, PIPELINES, build_dataloader, build_dataset
from .dataset_info import DatasetInfo
from .pipelines import Compose
from .samplers import DistributedSampler

from .datasets import (  # isort:skip
    AnimalATRWDataset, AnimalFlyDataset, AnimalHorse10Dataset,
    AnimalLocustDataset, AnimalMacaqueDataset, AnimalPoseDataset,
    AnimalZebraDataset, Body3DH36MDataset, BottomUpAicDataset,
    BottomUpCocoDataset, BottomUpCocoWholeBodyDataset,
    BottomUpCrowdPoseDataset, BottomUpMhpDataset, DeepFashionDataset,
    Face300WDataset, FaceAFLWDataset, FaceCocoWholeBodyDataset,
    FaceCOFWDataset, FaceWFLWDataset, FreiHandDataset,
    HandCocoWholeBodyDataset, InterHand2DDataset, InterHand3DDataset,
    MeshAdversarialDataset, MeshH36MDataset, MeshMixDataset, MoshDataset,
    OneHand10KDataset, PanopticDataset, TopDownAicDataset, TopDownCocoDataset,
    TopDownCocoWholeBodyDataset, TopDownCrowdPoseDataset,
    TopDownFreiHandDataset, TopDownH36MDataset, TopDownJhmdbDataset,
    TopDownMhpDataset, TopDownMpiiDataset, TopDownMpiiTrbDataset,
    TopDownOCHumanDataset, TopDownOneHand10KDataset, TopDownPanopticDataset,
    TopDownPoseTrack18Dataset, TopDownPoseTrack18VideoDataset,
    Body3DMviewDirectPanopticDataset, Body3DMviewDirectShelfDataset,
    Body3DMviewDirectCampusDataset, NVGestureDataset, BottomUpHorseDataset)

__all__ = [
    'TopDownCocoDataset', 'BottomUpCocoDataset', 'BottomUpMhpDataset',
    'BottomUpAicDataset', 'BottomUpCocoWholeBodyDataset', 'TopDownMpiiDataset',
    'TopDownMpiiTrbDataset', 'OneHand10KDataset', 'PanopticDataset',
    'HandCocoWholeBodyDataset', 'FreiHandDataset', 'InterHand2DDataset',
    'InterHand3DDataset', 'TopDownOCHumanDataset', 'TopDownAicDataset',
    'TopDownCocoWholeBodyDataset', 'MeshH36MDataset', 'MeshMixDataset',
    'MoshDataset', 'MeshAdversarialDataset', 'TopDownCrowdPoseDataset',
    'BottomUpCrowdPoseDataset', 'TopDownFreiHandDataset',
    'TopDownOneHand10KDataset', 'TopDownPanopticDataset',
    'TopDownPoseTrack18Dataset', 'TopDownJhmdbDataset', 'TopDownMhpDataset',
    'DeepFashionDataset', 'Face300WDataset', 'FaceAFLWDataset',
    'FaceWFLWDataset', 'FaceCOFWDataset', 'FaceCocoWholeBodyDataset',
    'Body3DH36MDataset', 'AnimalHorse10Dataset', 'AnimalMacaqueDataset',
    'AnimalFlyDataset', 'AnimalLocustDataset', 'AnimalZebraDataset',
    'AnimalATRWDataset', 'AnimalPoseDataset', 'TopDownH36MDataset',
    'TopDownPoseTrack18VideoDataset', 'build_dataloader', 'build_dataset',
    'Compose', 'DistributedSampler', 'DATASETS', 'PIPELINES', 'DatasetInfo',
    'Body3DMviewDirectPanopticDataset', 'Body3DMviewDirectShelfDataset',
    'Body3DMviewDirectCampusDataset', 'NVGestureDataset', 'BottomUpHorseDataset'
]`

I got the following error:

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Input In [3], in <cell line: 2>()
      1 # build dataset
----> 2 datasets = [build_dataset(cfg.data.train)]

File ~/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmpose-0.27.0-py3.8.egg/mmpose/datasets/builder.py:87, in build_dataset(cfg, default_args)
     85     dataset = _concat_dataset(cfg, default_args)
     86 else:
---> 87     dataset = build_from_cfg(cfg, DATASETS, default_args)
     88 return dataset

File ~/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/utils/registry.py:58, in build_from_cfg(cfg, registry, default_args)
     56     obj_cls = registry.get(obj_type)
     57     if obj_cls is None:
---> 58         raise KeyError(
     59             f'{obj_type} is not in the {registry.name} registry')
     60 elif inspect.isclass(obj_type) or inspect.isfunction(obj_type):
     61     obj_cls = obj_type

KeyError: 'BottomUpHorseDataset is not in the dataset registry'

With 0.25.1 version:

`# build dataset
datasets = [build_dataset(cfg.data.train)]
loading annotations into memory...
Done (t=1.23s)
creating index...
index created!`

**Comment by liqikai9** [comment]
I think this may because you have multiple versions of mmpose installed in the current environment `open-mmlab`. 

Is that in your environment that the 0.27.0 version is installed in the **`site-packages`**, while the 0.25.1 version is installed in the editable mode? So that the dataset you add may not be able to take effect~

You may also refer to [this](https://github.com/open-mmlab/mmpose/blob/master/docs/en/faq.md#coding).

**Comment by amartincirera** [comment]
Thanks for your quick response! 

You are right, the new dataset was not saved in the environment. Once added the problem was solved!

Tank you so much.

**Comment by liqikai9** [comment]
It is glad to help you. Please don't hesitate to ask questions. We are willing to help~

**Comment by alaa-shubbak** [comment]
I apply all such steps, unfortunatily i got an error message of 

`TypeError: xxxxxxxx: string indices must be integers`

i create my dataset to have similar format of coco , with another class type rather than human and less keypoints. 

I don't know what will be the problem and where should i modify. 
shall i modify any of cocotool or builder.py or something else? 

please help me.
