### ISSUE TITLE
How to show training result

### ISSUE THREAD

**Issue by AIceDog** [open-mmlab/mmpose#1431]
Hi, I am new to mmpose. I pre-processed mpi-inf-3dhp dataset and trained_video_pose lift model for 3d body keypoint estimation. 
I used videopose3d_mpi-inf-3dhp_1frame_fullconv_supervised_gt.py as my config file.

I would like to know how to test my trained model and show the testing result like this?

![1655327004889](https://user-images.githubusercontent.com/16275289/173929650-0bffd6da-0be5-48f6-a2cc-f620ce174d5c.png)

**Comment by liqikai9** [comment]
You can refer to [this ](https://github.com/open-mmlab/mmpose/blob/master/demo/docs/3d_human_pose_demo.md#3d-human-pose-two-stage-estimation-video-demo) to run inference with the trained model and generate the visualization results.

**Comment by AIceDog** [comment]
Thanks!
