### ISSUE TITLE
关于如何修改HRNet的backbone

### ISSUE THREAD

**Issue by ShaneCan** [open-mmlab/mmpose#1435]
由于网络轻量化的需求，想要删除hrnet中的第四阶段即stage4。在config文件中直接将backbone中的stage4删除后运行训练train.py，报错：
File "F:\Anaconda\envs\mmpose\lib\site-packages\mmcv\utils\registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: 'TopDown: "HRNet: \'stage4\'"'

请问应当如何正确修改网络结构呢？感谢回答

**Comment by jin-s13** [comment]
只改config是不够的，得去照着源码来改。
https://github.com/open-mmlab/mmpose/blob/16027f633431491b299cac5d2350f8753b0dfdce/mmpose/models/backbones/hrnet.py#L366
