### ISSUE TITLE
How to set sigmas for My custom dataset?

### ISSUE THREAD

**Issue by EbenezerO** [open-mmlab/mmpose#1443]
hello! When calculating OKS, I need the new value of sigma that matches my own dataset. But  I don't konw how to set the value of sigmas for My custom dataset?  
The reason for setting the new sigma value:
1.The sample of the dataset is completely different from coco. (image resolution, human body region, number of human bodies per image)
2. After eliminating the annotation problem of validation set, I tried many different models, and their AP was at 26%, but the actual detection effect was good.

I found the definition of sigma from the [official website  Sec 1.3. Tuning OKS.](https://cocodataset.org/#keypoints-eval)
σi2=E[di2/s2]. How is it calculated？

During the process of using MMPose, I also learned that there are many different datasets in configs/_base_/datasets/ directory. I would like to know how you set the values of these sigma.please!

**Comment by EbenezerO** [comment]
@jin-s13  大佬，I need you help！

**Comment by jin-s13** [comment]
sigma represents the error/variance of the human annotators. 
The sigma is usually provided along with the dataset.

**Comment by jin-s13** [comment]
This issue is duplicated with https://github.com/open-mmlab/mmpose/issues/1123
