### ISSUE TITLE
heatmap visualization

### ISSUE THREAD

**Issue by feelme0461** [open-mmlab/mmpose#1445]
How to visualize the heatmap when using the simple baseline method？

**Comment by liqikai9** [comment]
Hi. You can run the demo with the `return_heatmap` option like this example: https://github.com/open-mmlab/mmpose/blob/master/demo/top_down_img_demo_with_mmdet.py#L101. Then you can visualize the returned heatmap using other tools like `matplotlib` .

**Comment by ustbwanglu** [comment]
When visualizing the heat map, the visualization result of the heat map does not match the gt point. Is there any solution?

**Comment by liqikai9** [comment]
You can generate the target heatmap using the gt point and compare it with the result heatmap.

**Comment by feelme0461** [comment]
> 你好。您可以使用以下示例的`return_heatmap`选项运行演示：[https](https://github.com/open-mmlab/mmpose/blob/master/demo/top_down_img_demo_with_mmdet.py#L101) ://github.com/open-mmlab/mmpose/blob/master/demo/top_down_img_demo_with_mmdet.py#L101 。然后，您可以使用其他工具（如`matplotlib`.

I got it,thank you!

**Comment by feelme0461** [comment]
> Hi. You can run the demo with the `return_heatmap` option like this example: https://github.com/open-mmlab/mmpose/blob/master/demo/top_down_img_demo_with_mmdet.py#L101. Then you can visualize the returned heatmap using other tools like `matplotlib` .

I'm sorry,this time,I perform as you say, thougn i got the pose_result,  i can't get the heatmap result again,I printed the returned_outputs,I got an array as a result.Why is there no visual heat map generated？BY the way ,how to choose the different 'output_layer_names' excep for the('backbone',)

**Comment by hsp2454** [comment]
hello, i also got the returned_outputs in top_down_img_demo_with_mmdet.py, did you draw the heatmap?
