### ISSUE TITLE
Saving Inference Results on VoxelPose

### ISSUE THREAD

**Issue by YoussefFathi** [open-mmlab/mmpose#1446]
I have tried running the demo file for the multiview 3D keypoints detection using voxel pose, but could only see the predicted keypoints as visualizations on the images. Is there a way to extract the predicted keypoints themselves in raw JSON format for example?

**Comment by wusize** [comment]
Hi! You can save the keypoints in .json file in the evaluation process. Add _evaluation=dict(res_folder='path/to/save')_ in the cfg file and run [test](https://github.com/open-mmlab/mmpose/blob/master/docs/en/get_started.md#test-a-dataset), the keypoints will be saved under 'path/to/save'.

**Comment by fxyQAQ** [comment]
Hi, I have added evaluation=dict(res_folder='path/to/save') in the '\configs\body\3d_kpt_mview_rgb_img\voxelpose\panoptic\voxelpose_prn64x64x64_cpn80x80x20_panoptic_cam5.py', but it doesn't work. Is there an update?
