### ISSUE TITLE
Error in evaluating 13 keypoints

### ISSUE THREAD

**Issue by YuktiADY** [open-mmlab/mmpose#1453]
Hallo,

I have already discussed this issue in #1357 but since one issue focus on one problem i am opening this as new issue.
I am evaluating 13 keypoints excluding the eyes,ears since my custom dataset doesnot contains those keypoints.
So i did changes in cocoeval.py and dataset info adding some slicing and sigma value for 13 keypoints.

But i am still getting this error for 
File "./mmpose/tools/test.py", line 168, in main
    results = dataset.evaluate(outputs, cfg.work_dir, **eval_config)
  File "/home/yukti/mmpose/mmpose/mmpose/datasets/datasets/top_down/topdown_coco_dataset.py", line 311, in evaluate
    keep = nms(img_kpts, oks_thr, sigmas=self.sigmas)
  File "/home/yukti/mmpose/mmpose/mmpose/core/post_processing/nms.py", line 116, in oks_nms
    sigmas, vis_thr)
  File "/home/yukti/mmpose/mmpose/mmpose/core/post_processing/nms.py", line 81, in oks_iou
    e = (dx**2 + dy**2) / vars / ((a_g + a_d[n_d]) / 2 + np.spacing(1)) / 2
ValueError: operands could not be broadcast together with shapes (17,) (13,)

As suggested by you i tried giving the sigmas values directly into compute oks function but error still persists.
I tried changing the coco.py as error comes in that file as well from above.

Unable to get from why this is taking 17, 13 as i have already changed the 13 sigma values in cocoeval.py and dataset info file.

Please give your valuable suggestions as I am facing this issue. Also please let me know if you any other information from my side.I have already shared the code changes that i did in #1357 (last) but still if you want i can share again here for your kind convenience.

Regards
Yukti

**Comment by jin-s13** [comment]
Please take a look at https://github.com/open-mmlab/mmpose/issues/902
looks like a similar problem.

**Comment by jin-s13** [comment]
channel_cfg = dict(
num_output_channels=17,
dataset_joints=17,
dataset_channel=[
list(range(17)),
],
inference_channel=list(range(17)))

**Comment by YuktiADY** [comment]
> ```
> channel_cfg = dict(
> num_output_channels=17,
> dataset_joints=17,
> dataset_channel=[
> list(range(17)),
> ],
> inference_channel=list(range(17)))
> ```
> 
> Also why 17 here?

Because I have trained on merged dataset consiting of COCO and Theodore dataset.
But in our Theodore we are training from scratch or finetuning and it contains 13 keypoints only . SO evaluating on 13 keypints rather than 17.
I already tried giving the same sigmas values (#902) before that i gave in cocoeval.py but still same error.

Traceback below:

 File "./mmpose/tools/test.py", line 174, in <module>
    main()
  File "./mmpose/tools/test.py", line 168, in main
    results = dataset.evaluate(outputs, cfg.work_dir, **eval_config)
  File "/home/yukti/mmpose/mmpose/mmpose/datasets/datasets/top_down/topdown_coco_dataset.py", line 311, in evaluate
    keep = nms(img_kpts, oks_thr, sigmas=self.sigmas)
  File "/home/yukti/mmpose/mmpose/mmpose/core/post_processing/nms.py", line 117, in oks_nms
    sigmas, vis_thr)
  File "/home/yukti/mmpose/mmpose/mmpose/core/post_processing/nms.py", line 82, in oks_iou
    e = (dx**2 + dy**2) / vars / ((a_g + a_d[n_d]) / 2 + np.spacing(1)) / 2
ValueError: operands could not be broadcast together with shapes (17,) (13,)

**Comment by jin-s13** [comment]
So the model outputs 17 kpts, how do you choose the 13 desired keypoints for evaluation?

**Comment by YuktiADY** [comment]
Omitting the eyes and ears.Thats wat i gave slicing in cocoeval.py

g = np.array(gt['keypoints'][0:3] + gt['keypoints'][15:])
d = np.array(dt['keypoints'][0:3] + dt['keypoints'][15:])
self.sigmas = np.array(
                [.26, .79, .79, .72, .72, .62,.62, 1.07, 1.07, .87, .87, .89, .89])/10.0

**Comment by YuktiADY** [comment]
I have also observed that there is one more xcocotools outside the environment /home/yukti/anaconda3/lib/python3.7/site-packages/xtcocotools/..
while installing mmcv xcocotools was installed but only inside environment .from where one more xcocotools outside the environment.

**Comment by jin-s13** [comment]
https://github.com/open-mmlab/mmpose/blob/ca26778e503678b3b82acd054260c1a51f183903/mmpose/datasets/datasets/top_down/topdown_coco_dataset.py#L312

We will use keypoints for NMS. Here you have 17 keypoints in `img_kpts`, but `sigmas=self.sigmas` only have 13 keypoints. 
I think, you need to filter the output keypoints and only keep 13 keypoints, before Line 312.

**Comment by YuktiADY** [comment]
> https://github.com/open-mmlab/mmpose/blob/ca26778e503678b3b82acd054260c1a51f183903/mmpose/datasets/datasets/top_down/topdown_coco_dataset.py#L312
> 
> We will use keypoints for NMS. Here you have 17 keypoints in `img_kpts`, but `sigmas=self.sigmas` only have 13 keypoints. I think, you need to filter the output keypoints and only keep 13 keypoints, before Line 312.

Can you explain what changes i should do in topdown_coco_dataset.py ??

**Comment by Dipankar1997161** [comment]
@jin-s13 
Hello, 
It is true that the img_kpts is providing 17 keypoint as a list. 

I believe, it should be possible to slice out the unwanted key points from that list, which according to @YuktiADY are eyes and ears. 

Thus in the nms.py,  the "kpts" variable stores a flattened list of the 17 key points. Therefore, a slicing of that flattened list might possibly resolve the broadcasting error.

What do you think??

**Comment by YuktiADY** [comment]
I tried this in nms.py but since i have remove some of the keypoints from between. Do you have an idea how to slice using flatten method.

 kpts = np.array([k['keypoints'][0] + k['keypoints'][5:13].flatten() for k in kpts_db])
with this slicing using '+' operator it doesnt work.

Traceback 
ValueError: operands could not be broadcast together with shapes (3,) (24,)

**Comment by jin-s13** [comment]
How about slicing this after np.array()?

**Comment by YuktiADY** [comment]
Hello

We dont have the folder named "pycocoai " in the below path.
conda/envs/mmpose/python3.x/site-packages/pycocoapi/cocoeval.py

Are we not using pycocotools in mmpose ? I mean only Xtcocotools folder is there inside this folder cocoeval.py.
So everytime we run the evaluation the cocoeval is called ??

**Comment by jin-s13** [comment]
> Hello
> 
> We dont have the folder named "pycocoai " in the below path. conda/envs/mmpose/python3.x/site-packages/pycocoapi/cocoeval.py
> 
> Are we not using pycocotools in mmpose ? I mean only Xtcocotools folder is there inside this folder cocoeval.py. So everytime we run the evaluation the cocoeval is called ??
> 
> If i am evaluating on 13 keypoints then changes have to be done in cocoeval.py
> 
> 1. changing the sigmas values from 13
> 2. adding slicing as mentioned above.

We do not use pycocotools in mmpose. Instead we will use xtcocotools. 
Actually, I think you do not need to modify xtcocotools itself. Since it already supports different numbers of keypoints, just provide sigmas as the input.

**Comment by jin-s13** [comment]
> > How about slicing this after np.array()?
> 
> Hello,
> 
> I tried giving the slicing after np.array kpts = np.array(kpts[0:3] + kpts[15:]) but still get this error ValueError: operands could not be broadcast together with shapes (3,51) (0,51)
> 
> please suggest !

It seems that the problem is (0,51). Can you figure out what value is shaped (0,51)?

**Comment by Dipankar1997161** [comment]
> > > How about slicing this after np.array()?
> > 
> > 
> > Hello,
> > I tried giving the slicing after np.array kpts = np.array(kpts[0:3] + kpts[15:]) but still get this error ValueError: operands could not be broadcast together with shapes (3,51) (0,51)
> > please suggest !
> 
> It seems that the problem is (0,51). Can you figure out what value is in shape (0,51)?

Yea I think so as well. Maybe after printing the values, it will be clear, what can possibly lead to an error. 

Thank you @jin-s13 for the update

**Comment by YuktiADY** [comment]
Thank you for the suggestions.
It is working now..

The changes have to be done on cocoeval.py by slicing the 'd' and 'g' ground truth keypoints.
Passing sigma values as per your evaluation of keypoints.
