### ISSUE TITLE
why smooth "keypoints" but not "keypoints3d" in body3d_two_stage_video_demo.py?

### ISSUE THREAD

**Issue by darcula1993** [open-mmlab/mmpose#1455]
Line 300 in body3d_two_stage_video_demo.py
`
smoother = Smoother(filter_cfg=args.smooth_filter_cfg, keypoint_dim=3)
`
set keypoints_dim = 3 but do not set  keypoint_key which has default value 'keypoints'.

It seems that we should smooth "keypoints_3d" but not "keypoints".Something wrong here?

**Comment by ly015** [comment]
Yes, the keypoint_key should be set as "keypoints_3d" here. Thanks for pointing it out, we will fix it asap.

**Comment by darcula1993** [comment]
actually I found smooth 2d keypoints give me better results, since noise in 2d keypoints may be amplified by 2d-to-3d lift process. So I suggest do smooth for "keypoints" rather than "keypoints_3d" here.
