### ISSUE TITLE
如何测试自己数据集上训练出来的权重的性能呢？

### ISSUE THREAD

**Issue by ShaneCan** [open-mmlab/mmpose#1459]
想对MAP,AP,AR,GFLOPS等性能进行测试，但是发现在训练过程中的测试环节，出现下列状况：

[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 37/37, 0.7 task/s, elapsed: 54s, ETA:     0sLoading and preparing results...
2022-07-03 11:12:43,314 - mmpose - INFO - Epoch(val) [10][2]	AP: 0.0000, AP .5: 0.0000, AP .75: 0.0000, AP (M): -1.0000, AP (L): -1.0000, AR: 0.0000, AR .5: 0.0000, AR .75: 0.0000, AR (M): -1.0000, AR (L): -1.0000
DONE (t=0.01s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *keypoints*
DONE (t=0.01s).
Accumulating evaluation results...
DONE (t=0.00s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] =  0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets= 20 ] =  0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets= 20 ] =  0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] =  0.000
 Average Recall     (AR) @[ IoU=0.50      | area=   all | maxDets= 20 ] =  0.000
 Average Recall     (AR) @[ IoU=0.75      | area=   all | maxDets= 20 ] =  0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = -1.000

请问大神应该如何解决呢，谢谢！！！

**Comment by ShaneCan** [comment]
补充一下，训练后的权重在识别过程中正常，只是测试环节出现上述问题

**Comment by jin-s13** [comment]
你觉得哪里有异常呀？

**Comment by ShaneCan** [comment]
> 你觉得哪里有异常呀？ 训练久一点会不会有值呢？
异常点在于AR AP居然全是0，甚至还有负值，训练了300个轮次也没有值。。。不知道是什么情况。
使用test.py发现结果相同：
AP: 0.0
AP (L): -1.0
AP (M): -1.0
AP .5: 0.0
AP .75: 0.0
AR: 0.0
AR (L): -1.0
AR (M): -1.0
AR .5: 0.0
AR .75: 0.0

**Comment by ShaneCan** [comment]
> 你觉得哪里有异常呀？ 训练久一点会不会有值呢？

AP: 0.0
AP (L): -1.0
AP (M): -1.0
AP .5: 0.0
AP .75: 0.0
AR: 0.0
AR (L): -1.0
AR (M): -1.0
AR .5: 0.0
AR .75: 0.0

**Comment by ly015** [comment]
会不会是测试数据有问题，可能要 check 一下

**Comment by jin-s13** [comment]
哦  L，M两个都是-1 有点奇怪了，Large 和 Medium的物体都是不存在的？

**Comment by ShaneCan** [comment]
> 会不会是测试数据有问题，可能要 check 一下

测试数据有问题指的是？... 测试集就是从训练集中分割出来的一部分 ....

**Comment by ShaneCan** [comment]
> 哦 L，M两个都是-1 有点奇怪了，Large 和 Medium的物体都是不存在的？

应该都存在吧.... 很奇怪

**Comment by ShaneCan** [comment]
遇到困难了 还是没有思路。。。

**Comment by jin-s13** [comment]
training acc 有值么？  如果有的话，可以看看可视化效果正不正常

**Comment by ShaneCan** [comment]
> 

acc是有值的 一切正常，就是AP AR这些不显示

**Comment by ShaneCan** [comment]
> training acc 有值么？ 如果有的话，可以看看可视化效果正不正常

acc是有值的 一切正常，就是AP AR这些不显示

**Comment by jin-s13** [comment]
想起一个可能的原因，你可以检查下标注文件的格式，有没有漏写这个categories？

https://github.com/jin-s13/xtcocoapi/blob/e1052f3009702b74ece8aa58e3ef8b73d10467f2/annotations/example_coco_val.json#L49

**Comment by ShaneCan** [comment]
> 想起一个可能的原因，你可以检查下标注文件的格式，有没有漏写这个categories？
> 
> https://github.com/jin-s13/xtcocoapi/blob/e1052f3009702b74ece8aa58e3ef8b73d10467f2/annotations/example_coco_val.json#L49

感谢，确实漏写了，但是加上以后情况还是一样，可能是sigma的原因吧 我的sigma是瞎写的

**Comment by lllrj** [comment]
你好，我遇到了和你一样的问题，请问你现在有解决吗？
PS:我的数据集由于没有很多人标记来算标准差，sigma也是根据不同点标注难度自己定的的。

**Comment by ShaneCan** [comment]
> 你好，我遇到了和你一样的问题，请问你现在有解决吗？ PS:我的数据集由于没有很多人标记来算标准差，sigma也是根据不同点标注难度自己定的的。

解决不了 无解了

**Comment by lllrj** [comment]
> > 你好，我遇到了和你一样的问题，请问你现在有解决吗？ PS:我的数据集由于没有很多人标记来算标准差，sigma也是根据不同点标注难度自己定的的。
> 
> 解决不了 无解了

我已经解决了问题，分享给你。我的情况是由于数据集生成label的时候默认area=1.0，所以导致了evaluate时的错误，修改成area=bbox的H*W就可以正确test了。再此我也分享给你一篇可能对你有帮助的博客：https://zhuanlan.zhihu.com/p/558257447

**Comment by ShaneCan** [comment]
> > > 你好，我遇到了和你一样的问题，请问你现在有解决吗？ PS:我的数据集由于没有很多人标记来算标准差，sigma也是根据不同点标注难度自己定的的。
> > 
> > 
> > 解决不了 无解了
> 
> 我已经解决了问题，分享给你。我的情况是由于数据集生成label的时候默认area=1.0，所以导致了evaluate时的错误，修改成area=bbox的H*W就可以正确test了。再此我也分享给你一篇可能对你有帮助的博客：https://zhuanlan.zhihu.com/p/558257447

非常感谢您，我生成json的时候写的也是annotation['area'] = 1.0  ，  想问问您这句话您是如何修改的呢？

**Comment by Jazzy0302** [comment]
how did you solve this situation? I am facing the same problem and have no idea to solve it ? I have the "area"= w*h but the val result still shows zero AP , but the train process seams right
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] =  0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets= 20 ] =  0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets= 20 ] =  0.000
 
09/14 21:32:30 - mmengine - INFO - Epoch(train)  [34][ 50/141]  lr: 1.000000e-04  eta: 3:56:14  time: 0.567893  data_time: 0.430769  memory: 2408  loss: 0.001147  loss_kpt: 0.001147  acc_pose: 0.792578
09/14 21:32:58 - mmengine - INFO - Epoch(train)  [34][100/141]  lr: 1.000000e-04  eta: 3:56:32  time: 0.563626  data_time: 0.428105  memory: 2408  loss: 0.001114  loss_kpt: 0.001114  acc_pose: 0.728309
09/14 21:33:20 - mmengine - INFO - Exp name: my-td-hm_res50_8xb64-210e_animalpose-256x256_20240914_205642
09/14 21:33:46 - mmengine - INFO - Epoch(train)  [35][ 50/141]  lr: 1.000000e-04  eta: 3:56:42  time: 0.522573  data_time: 0.388404  memory: 2408  loss: 0.001108  loss_kpt: 0.001108  acc_pose: 0.725313
