### ISSUE TITLE
TRB Infernece

### ISSUE THREAD

**Issue by codeHorasan** [open-mmlab/mmpose#1469]
Is there a way to get inference with mpii_TRB models like bottom_up_image_demo? I don't want to train with JSON file, just get inference

**Comment by jin-s13** [comment]
You may use https://github.com/open-mmlab/mmpose/blob/master/demo/docs/2d_human_pose_demo.md#2d-human-pose-top-down-image-demo

mpii_TRB models are top-down models, you can use top down image demos for inference.

**Comment by codeHorasan** [comment]
Thank you. I was able to solve it by importing init_pose_model and inference_top_down_pose_model from mmpose.apis.

**Comment by aodiwei** [comment]
Hi, @codeHorasan , I tried @jin-s13 's way:
`python demo/top_down_img_demo.py configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii_trb/res101_mpii_trb_256x256.py https://download
.openmmlab.com/mmpose/top_down/resnet/res50_mpii_trb_256x256-896036b8_20200812.pth  --img-root tests/data/mpii/ --json-file tests/data/mpii/test_mpii_trb.json  --out-img-root vis_results --device cpu
`
but not work, with err:
`  File "demo/top_down_img_demo.py", line 130, in <module>
    main()
  File "demo/top_down_img_demo.py", line 95, in main
    person['bbox'] = ann['bbox']
KeyError: 'bbox'
`
can you show me your demo code? thx very much.
