### ISSUE TITLE
how to test the fps of a weight

### ISSUE THREAD

**Issue by hatecodes** [open-mmlab/mmpose#1470]
我想检测下训练权重的fps，即文档中的[Inference Speed](https://mmpose.readthedocs.io/en/latest/inference_speed_summary.html#)，中的GPU Inference Speed(FPS)1。但是不知道应该使用哪个工具。.dev文件夹下的speed_test.py无法使用。

**Comment by liqikai9** [comment]
你好。可以在初始化 model 的 [这行代码](https://github.com/open-mmlab/mmpose/blob/master/.dev_scripts/benchmark/speed_test.py#L115) 加上 checkpoint 的参数，参考 apis/inference.py 的 [init_pose_model](https://github.com/open-mmlab/mmpose/blob/master/mmpose/apis/inference.py#L25)

**Comment by hatecodes** [comment]
> 你好。可以在初始化 model 的 [这行代码](https://github.com/open-mmlab/mmpose/blob/master/.dev_scripts/benchmark/speed_test.py#L115) 加上 checkpoint 的参数，参考 apis/inference.py 的 [init_pose_model](https://github.com/open-mmlab/mmpose/blob/master/mmpose/apis/inference.py#L25)

您的意思是还是使用[.dev_scripts](https://github.com/open-mmlab/mmpose/tree/master/.dev_scripts)/[benchmark](https://github.com/open-mmlab/mmpose/tree/master/.dev_scripts/benchmark)/speed_test.py 这个工具，然后加上checkpoint。那么config中输入的yaml文件是否还需要权重呢？
此外在运行时会出现报错，会出现memory error或者是RuntimeError: DataLoader worker (pid(s) 4368, 4268, 2572, 14660, 4476) exited unexpectedly等等情况。。所用配置为5900X 32G RTX3090

**Comment by liqikai9** [comment]
是的，可以继续使用 [.dev_scripts/benchmark/speed_test.py](https://github.com/open-mmlab/mmpose/blob/master/.dev_scripts/benchmark/speed_test.py)。你可以从输入的 yaml 文件中像[这一行代码](https://github.com/open-mmlab/mmpose/blob/master/.dev_scripts/benchmark/speed_test.py#L97)一样读入 checkpoint 文件
```python
checkpoint = cur_model['checkpoint']
```
然后，在初始化模型的时候，把这个checkpoint 的路径传给 init_pose_model 函数即可。

注意将 yaml 文件对应的 checkpoint 的路径修改为你的权重。

**Comment by hatecodes** [comment]
> 是的，可以继续使用 [.dev_scripts/benchmark/speed_test.py](https://github.com/open-mmlab/mmpose/blob/master/.dev_scripts/benchmark/speed_test.py)。你可以从输入的 yaml 文件中像[这一行代码](https://github.com/open-mmlab/mmpose/blob/master/.dev_scripts/benchmark/speed_test.py#L97)一样读入 checkpoint 文件
> 
> ```python
> checkpoint = cur_model['checkpoint']
> ```
> 
> 然后，在初始化模型的时候，把这个checkpoint 的路径传给 init_pose_model 函数即可。
> 
> 注意将 yaml 文件对应的 checkpoint 的路径修改为你的权重。

谢谢您的耐心解答，目前可以正常读取，但是程序会报错，如出现memory error或者是RuntimeError: DataLoader worker (pid(s) 4368, 4268, 2572, 14660, 4476) exited unexpectedly等等情况，多次运行后甚至导致pycharm闪退， 无法运行得到结果。还想请教您一下这个问题

**Comment by liqikai9** [comment]
这个问题有可能是因为 Windows 上设置 DataLoader workers 个数大于零导致的问题，你可以试试把 config 的 workers_per_gpu设置为0，看看还会不会出现这样的问题

**Comment by hatecodes** [comment]
> 这个问题有可能是因为 Windows 上设置 DataLoader workers 个数大于零导致的问题，你可以试试把 config 的 workers_per_gpu设置为0，看看还会不会出现这样的问题

感谢您的解答，目前已经可以运行！结果得到的是Overall average speed: 6.24 ± 2.68 items / s  ，请问这个是FPS吗？对比文档中的15.03 ± 1.03 ， 相差比较大。（所使用的是HRNET-W48）

**Comment by liqikai9** [comment]
> 请问这个是FPS吗？

是的。

相差比较大这个，有测过其他模型吗，都比文档中的小得多吗，还是就 HRNET-W48 这一个模型差的比较多

**Comment by hatecodes** [comment]
> > 请问这个是FPS吗？
> 
> 是的。
> 
> 相差比较大这个，有测过其他模型吗，都比文档中的小得多吗，还是就 HRNET-W48 这一个模型差的比较多

W32模型也有一定差距 这个。。有点不太懂了。。

**Comment by jin-s13** [comment]
不同机器跑出来的速度不一样，应该是正常现象。
