### ISSUE TITLE
Custom dataset for bottom up approaches

### ISSUE THREAD

**Issue by ines-mez** [open-mmlab/mmpose#1473]
Hi everyone,

First of all, thank you for this amazing repo
I've been able to create my own customized dataset following [this tutorial](https://colab.research.google.com/github/open-mmlab/mmpose/blob/master/demo/MMPose_Tutorial.ipynb) and successfully trained models

Now, I would like to do the same for bottom up approaches but it seems like the meta keys are different and I have a hard time finding some doc around what to do to transform my data (not in coco style) to match what's needed for the top down approaches. (And mimic the class [BottomUpCocoDataset class](https://github.com/open-mmlab/mmpose/blob/master/mmpose/datasets/datasets/bottom_up/bottom_up_coco.py))

I can see 'dataset', 'image_file', 'mask' and 'joints' as required metadata keys, but I have no idea what they are in terms of shape/what they mean (expect image_file). Is there doc around it ? Is there a tutorial like the one for top down approaches ? Thank you !

**Comment by Ben-Louis** [comment]
According to [TUTORIAL 2: ADDING NEW DATASET](https://mmpose.readthedocs.io/en/latest/tutorials/2_new_dataset.html), there are two ways to build your dataset, where the second one, creating a custom dataset class, is described in the tutorial. 

You may try the first method, reorganizing data to COCO format, as it suits both top-down and bottom-up approaches. After that, you could build your dataset using `BottomUpCocoDataset` with [reference config](https://github.com/open-mmlab/mmpose/blob/master/configs/body/2d_kpt_sview_rgb_img/associative_embedding/coco/res50_coco_512x512.py).

**Comment by ines-mez** [comment]
That's actually much easier. Thank you !
