### ISSUE TITLE
Ｈow  to test on an image and get the whole body result (an image with whole body pose estimation)?

### ISSUE THREAD

**Issue by Wu-Jintao** [open-mmlab/mmpose#148]
Ｈow  to test on an image and get the whole body result (an image with whole body pose estimation)?

**Comment by jin-s13** [comment]
Please refer to the topdown demo.

**Comment by Wu-Jintao** [comment]
thanks!

**Comment by Wu-Jintao** [comment]
I have run the demo like this ,but  got the result that without the whole body pose estimation, what's wrong with my run code?

`python demo/top_down_img_demo.py     configs/top_down/hrnet/coco-wholebody/hrnet_w48_coco_wholebody_256x192.py     checkpoints/hrnet_w48-8ef0771d.pth     --img-root tests/data/coco/ --json-file tests/data/coco/test_coco_wholebody.json     --out-img-root vis_results
`

**Comment by Wu-Jintao** [comment]
thanks for your answer!

**Comment by Wu-Jintao** [comment]
/media/tao/702EB4282EB3E56E/WholeBody/COCOmmpose/mmpose/vis_results/vis_0.jpg

**Comment by Wu-Jintao** [comment]
![vis_0](https://user-images.githubusercontent.com/45363047/93962946-8a8e8200-fd8e-11ea-843e-649b0215144b.jpg)

**Comment by Wu-Jintao** [comment]
the result is showed above, hope for you answer,thanks very much!

**Comment by innerlee** [comment]
have you solved it?

**Comment by Wu-Jintao** [comment]
![Uploading vis_0.jpg…]()

**Comment by Wu-Jintao** [comment]
![vis_0](https://user-images.githubusercontent.com/45363047/93984894-f7b60d80-fdb6-11ea-8354-a7ce5d1a10ed.jpg)

**Comment by Wu-Jintao** [comment]
Thank you, I have solved it, the result is shown above, but there is another problem that the line of hand and face is too thick, may I ask how to adjust the thickness of the line of hand and face?

**Comment by Wu-Jintao** [comment]
hope for your reply,THX

**Comment by innerlee** [comment]
you can tweak these lines https://github.com/open-mmlab/mmpose/blob/feb920dcce4174a978216fbb725aee427ed58b67/mmpose/models/detectors/top_down.py#L320-L328

**Comment by wanghaichuan941221** [comment]
@Wu-Jintao How did you solve this? I  get the same issue
