### ISSUE TITLE
如何使用LiteHRNet训练自己的数据集

### ISSUE THREAD

**Issue by hatecodes** [open-mmlab/mmpose#1483]
训练时报错：
FileNotFoundError: TopDownAirplaneDataset: [Errno 2] No such file or directory: 'data/coco/person_detection_results/COCO_val2017_detections_AP_H_56_person.json'

根据寻找发现这个文件输入在config文件，bbox_file一行中，但是自己的数据集并没有这个文件。
使用HRNet可以将这一行直接用''代替不写，而使用LiteHRNet如果不写还是会报错
麻烦请教如何才能开启训练呢？

**Comment by ShaneCan** [comment]
> 第一个问题，如果不用bbox_file作为测试时的bbox，请设置`use_gt_bbox=True`。第二个问题，请确认相关的数据集已经正确用 Registry 注册

感谢您！

**Comment by hatecodes** [comment]
> 第一个问题，如果不用bbox_file作为测试时的bbox，请设置`use_gt_bbox=True`。第二个问题，请确认相关的数据集已经正确用 Registry 注册

感谢！现在出现了一个小问题， 就是训练这个LiteHRNet没有 loss，accpose的显示，开始训练后只会显示保存了epoch和val。如何把训练过程中的显示打开呢？

**Comment by jin-s13** [comment]
https://github.com/open-mmlab/mmpose/blob/afb37d4ce74a2df32a68c3e66a4411e515de423f/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/2xmspn50_coco_256x192.py#L22

这是因为你的数据量过少导致，可以调小 log_interval

**Comment by hatecodes** [comment]
> 

谢谢您，问题得到了解决
