### ISSUE TITLE
KeyError: Caught KeyError in DataLoader worker process 0.

### ISSUE THREAD

**Issue by zcunyi** [open-mmlab/mmpose#1488]
multi gpus training 
![179004097-1d006ee7-fc12-4f18-b17c-e07e947f0d73](https://user-images.githubusercontent.com/33832146/179004396-eeec1ff2-862c-4ff8-957b-7c9e7f022120.png)

**Comment by liqikai9** [comment]
This may be related to the data. Please double-check whether your data for training is empty or whether the datapath is correct.

**Comment by zcunyi** [comment]
> 
thanks for your reply.
command: ./tools/dist_train.sh configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/litehrnet_30_coco_256x192.py 8 

the datasets is ok, because when used './tools/dist_train.sh configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/vipnas_mbv3_coco_256x192.py 8', it`s training normally.

**Comment by liqikai9** [comment]
Did you make any modification to the related files? 

I have Googled this issue and did not find a similar solution. I suggest you change the value of `workers_per_gpu` to 0 and see if it can help.

**Comment by zcunyi** [comment]
> Did you make any modification to the related files?
> 
> I have Googled this issue and did not find a similar solution. I suggest you change the value of `workers_per_gpu` to 0 and see if it can help.
this also not work

**Comment by ly015** [comment]
Have you upgraded your mmpose version recently? This may be related to a breaking change in v0.26.0. See `Breaking Changes` in http://github.com/open-mmlab/mmpose/releases/tag/v0.26.0 for details.

**Comment by jin-s13** [comment]
Did you solve this problem by upgrading mmpose? @zcunyi

**Comment by zcunyi** [comment]
> Did you solve this problem by upgrading mmpose? @zcunyi

No, I removed the repository, and reclone it， then it works.
