### ISSUE TITLE
muti-head implementation

### ISSUE THREAD

**Issue by nicewiz** [open-mmlab/mmpose#1489]
Excited for your great work! I am a rookie for mmpose and I would like to train a top-down multi-head model for the keypoint prediction and the keypoints radiance regression, I tried to modify the `config_file` and make `keypoint_head` a list of dict but I am confused about how to:

1. modify the forward functions to support multiple heads
2. pre-processing the training data as keypoints changed after fliping or rotating while radiance not

Could you give me some advice or existed demo? Sorry for my rudimentary question. Hope for your reply! @jin-s13

**Comment by jin-s13** [comment]
The simplest way to achieve this is to build a single big head, containing multiple sub-heads. 
Modify the forward function of the single big head, to inference these sub-heads.
