### ISSUE TITLE
Available pre-trained models

### ISSUE THREAD

**Issue by bamsom** [open-mmlab/mmpose#1492]
Great works!

I am wondering how I can access a list of downloadable models in the checkpoint directories such as
https://download.openmmlab.com/mmpose/animal/ or
https://download.openmmlab.com/mmpose/animal/top-down

I am assuming there are more *.pth files available other than the demo examples.
I am especially looking for models trained in sheep/goat images.

**Comment by jin-s13** [comment]
Thanks for your interest!
You can find all these MMPose models in https://mmpose.readthedocs.io/en/latest/modelzoo.html

Especially for sheep/goat, you may check 
1) AnimalPose dataset trained models: https://mmpose.readthedocs.io/en/latest/topics/animal.html#animalpose-dataset
OR
2) AP-10K dataset trained models: https://mmpose.readthedocs.io/en/latest/topics/animal.html#ap10k-dataset

**Comment by bamsom** [comment]
Thanks!  I missed ckpt column.
