### ISSUE TITLE
pose_results可视化的问题

### ISSUE THREAD

**Issue by herochen7372** [open-mmlab/mmpose#1508]
作者你好，请问top_down_img_demo_with_mmdet.py 中的pose_results为什么我用plot可视化得到的关键点图像与mmpose中api得到的图像关于原点成中心对称，有什么解决办法吗

**Comment by herochen7372** [comment]
Hello, author, may I ask 'top_ down_ img_ demo_ with_ mmdet. 'pose' in 'py'_ Why is the key point image visualized by 'plot' and the image obtained by 'API' in 'mmpose' symmetrical about the origin? Is there any solution？

**Comment by Ben-Louis** [comment]
您好，您说的这种情况可能是模型预测关键点坐标出错或者 plot 可视化的时候坐标轴设置错误。top_down_img_demo_with_mmdet.py 得到的 pose_results 里面的关键点坐标值一般都是大于 0 的。您可以先检查一下推理得到的关键点坐标值数值范围。如果正常的话，可以再检查下 plot 的时候坐标轴的方向
