### ISSUE TITLE
How to return the DetectionNode axis after WebCam process

### ISSUE THREAD

**Issue by superobk** [open-mmlab/mmpose#1523]
Based on the tutorial (below md), may I know how to return DetectionNode axis after process function?
docs/zh_cn/tutorials/7_webcam_api.md

Thank you in advance!

**Comment by ly015** [comment]
Hi, thanks for using mmpose webcam api. Could you please further explain what "return DetectionNode axis" means?

**Comment by superobk** [comment]
> 

Thanks for the following up.
It means that, in order to get the axis or point and pass to third party program, how to config the "dict" or which API should be used?

**Comment by ly015** [comment]
I am not sure I get the meaning of "axis and point" here. Generally speaking, to export the model inference result or other intermediate data, you may need to implement a new Node class that saves the required data to files or sends it to the third-party program. The [tutorial](https://mmpose.readthedocs.io/en/latest/tutorials/7_webcam_api.html#extending-webcam-api-with-custom-nodes) gives a brief introduction to how to implement custom Node.

You can also refer to the `ObjectVisualizerNode` for how to obtain the detection and pose estimation results from the `FrameMessage`.

**Comment by superobk** [comment]
> I am not sure I get the meaning of "axis and point" here. Generally speaking, to export the model inference result or other intermediate data, you may need to implement a new Node class that saves the required data to files or sends it to the third-party program. The [tutorial](https://mmpose.readthedocs.io/en/latest/tutorials/7_webcam_api.html#extending-webcam-api-with-custom-nodes) gives a brief introduction to how to implement custom Node.
> 
> You can also refer to the `ObjectVisualizerNode` for how to obtain the detection and pose estimation results from the `FrameMessage`.

Thanks a lot for the information.
