### ISSUE TITLE
Unable to access the PoseTrack homepage for data download.

### ISSUE THREAD

**Issue by Yulv-git** [open-mmlab/mmpose#1526]
Excuse me, I can't access the PoseTrack homepage for [data download](https://github.com/open-mmlab/mmpose/blob/master/docs/zh_cn/tasks/2d_body_keypoint.md#posetrack18).
It is not sure if it is the PoseTrack website problem or my network problem.

**Comment by jin-s13** [comment]
I think it is the problem of [PoseTrack homepage](https://posetrack.net/).

**Comment by Yulv-git** [comment]
> 
Thanks. Would you mind sharing the available link to PoseTrack?

**Comment by Yulv-git** [comment]
> I think it is the problem of [PoseTrack homepage](https://posetrack.net/).

Thanks. Would you mind sharing the available link to PoseTrack?

**Comment by jin-s13** [comment]
We do not host PoseTrack dataset. Maybe you can email to the authors of PoseTrack and see if the official website can be recovered.

**Comment by Yulv-git** [comment]
> We do not host PoseTrack dataset. Maybe you can email to the authors of PoseTrack and see if the official website can be recovered.

Ok, thanks.

**Comment by APeiZou** [comment]
@Yulv-git me too ， do you download PoseTrack dataset？

**Comment by Ared521** [comment]
> @Yulv-git me too ， do you download PoseTrack dataset？

I have the same problem. How did you solve it?

**Comment by yeonhha** [comment]
Hi, Is there anyone download the posetrack dataset?

**Comment by wxhqw** [comment]
> Hi, Is there anyone download the posetrack dataset?

I also meet the problem, have you sloved it(download the posetrack dataset)?
