### ISSUE TITLE
Different AP between benchmark and log

### ISSUE THREAD

**Issue by kangwj1995** [open-mmlab/mmpose#154]
I wonder why benchmark AP and log AP are not same.

For example, pose_resnet_50 256x192 AP from benchmark table is 0.718 but log file says 0.73477 at epoch 208.

https://github.com/open-mmlab/mmpose/blob/master/configs/top_down/resnet/README.md

**Comment by jin-s13** [comment]
Hi, the benchmark AP is **always** evaluated with _detected_ bounding boxes, however, **sometimes** the log AP are evaluated with _ground-truth_ bounding boxes.

**Comment by innerlee** [comment]
how about adding a footnote explaining this difference, and provide the command line to properly do an evaluation (and get the numbers in the table).

**Comment by kangwj1995** [comment]
> Hi, the benchmark AP is _always_ evaluated with **detected** bounding boxes. However, sometimes the log AP are evaluated with **ground-truth** bounding boxes. So they may not be exactly the same.
> You may directly test the provided model and obtain its AP.

Thank you for your reply

Can you explain me more about 'sometimes'?
If log AP while training are evaluated with gt boxes,
can I change this settings to be evaluated with detected boxes while training?
I wonder whether your training code now also evaluate AP with gt boxes.

**Comment by jin-s13** [comment]
Yes, you can choose to evaluate with **gt boxes** or **detected box** during training.
Now, our default setting is to evaluate using detected boxes.

Just change the `use_gt_bbox=False` in the config file. For example, in [res50](https://github.com/open-mmlab/mmpose/blob/master/configs/top_down/resnet/coco/res50_coco_256x192.py) see line 70.

**Comment by jin-s13** [comment]
Since evaluating with detected boxes during training may spend more time, at first we simply use gt boxes...
Sorry for the confusion.
