### ISSUE TITLE
How to set positive target_weigth and zero target for hidden keypoints

### ISSUE THREAD

**Issue by GPhilo** [open-mmlab/mmpose#1542]
Hello,

I'm training a keypoints detector for a use-case in which I have 8 keypoints and for each sample I know in advance that 4 of the 8 keypoints are occluded.
I set up the trainig dataset and trained a network, however during inference the network always predicts all 8 keypoints, instead of being able to recognize between the visible ones and the occluded ones.

Tracking down the issue, I realized that in `TopDownGenerateTarget._msra_generate_target()` the `target_weight` is derived directly from the keypoint visibility, so the network receives weight updates only if a keypoint is present in the image.

What I want to enable is for the network to have negative feedback too, by setting the target_weight to 1 and having an all-zero `target` heatmap.
Is there a way to enable this behaviour? Or should I implement my own variation of `TopDownGenerateTarget._msra_generate_target()`?

**Comment by jin-s13** [comment]
_Is there a way to enable this behaviour?_ 
Currently, no. 

_Or should I implement my own variation of TopDownGenerateTarget._msra_generate_target()?_
Yes. I think so.
