### ISSUE TITLE
How train SmoothNet?

### ISSUE THREAD

**Issue by HiiHongFe** [open-mmlab/mmpose#1546]
I think smoothnet is a very good job. I really hope I can use it in my project, but I don't see any training methods for this. Do you have any related tutorials?

**Comment by ly015** [comment]
Training of SmoothNet has not been supported in MMPose yet. Please refer to the official repo https://github.com/cure-lab/SmoothNet

**Comment by HiiHongFe** [comment]
> 

thanks!!! I very very like the idea of this work!! salute!!!

**Comment by HiiHongFe** [comment]
> Training of SmoothNet has not been supported in MMPose yet. Please refer to the official repo https://github.com/cure-lab/SmoothNet

thanks!!! I very very like the idea of this work!! salute!!!

**Comment by chenxinfeng4** [comment]
> Training of SmoothNet has not been supported in MMPose yet. Please refer to the official repo https://github.com/cure-lab/SmoothNet

I have the same interest of the SmoothNet training. Even if I can train the cure-lab/SmoothNet, is it possible to share that checkpoint file with mmpose/smoothnet??
