### ISSUE TITLE
How to configure AID? Where are the details of the implementation code of AID?

### ISSUE THREAD

**Issue by APeiZou** [open-mmlab/mmpose#1547]
@ly015 Hello， How to configure AID? Where are the details of the implementation code of AID?

**Comment by jin-s13** [comment]
We do not directly support AID. But the major components (e.g. augmentations) can be found here https://mmpose.readthedocs.io/en/latest/papers/techniques.html#albumentations-information-2020

**Comment by APeiZou** [comment]
@jin-s13 thanks for your reply
