### ISSUE TITLE
Question about regression target used in RLE

### ISSUE THREAD

**Issue by Jackqu** [open-mmlab/mmpose#1553]
Hi, When I read the code about generating regression target for RLE , I noticed that the target weight is set to 0 when the joints are out of image after transformation. The code in the original RLE implementation here https://github.com/Jeff-sjtu/res-loglikelihood-regression does not do this, they will regress the joints even those joints are out of image after transformation. 
My question is , is there reason that the target weight is set to 0? Thanks

**Comment by Ben-Louis** [comment]
The purpose of non-zero target weight for invisible joints is to enhance the robustness of model on invisible joints, which might sacrifice its performance on visible joints. This balance is influenced by many factors, including the target weight, data aug, etc. Thus the suitable target weight might vary in different implementations.

We found that the best target weight for invisible joints is 0.1 for RLE in MMPose. But the accuracy improvement is marginal compared with 0, so we keep it 0 for simplicity.

**Comment by Jackqu** [comment]
I see, thank you very much.
