### ISSUE TITLE
2D Face Keypoint Demo

### ISSUE THREAD

**Issue by henbucuoshanghai** [open-mmlab/mmpose#1560]
python demo/top_down_img_demo.py     configs/face/2d_kpt_sview_rgb_img/topdown_heatmap/aflw/hrnetv2_w18_aflw_256x256.py     https://download.openmmlab.com/mmpose/face/hrnetv2/hrnetv2_w18_aflw_256x256-f2bbc62b_20210125.pth     --img-root tests/data/aflw/ --json-file tests/data/aflw/test_aflw.json     --out-img-root vis_results

has error

anaconda3/envs/lili/lib/python3.8/site-packages/xtcocotools/mask.py", line 3, in <module>
    import xtcocotools._mask as _mask
  File "xtcocotools/_mask.pyx", line 1, in init xtcocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

**Comment by Ben-Louis** [comment]
It seems like a numpy issue. You can try to upgrade your numpy. For more discussions, please refer to https://github.com/open-mmlab/mmpose/issues/534.
