### ISSUE TITLE
mmdet and mmpose use different default channel order

### ISSUE THREAD

**Issue by tongda** [open-mmlab/mmpose#1566]
According to [mmdet LoadImageFromFile](https://github.com/open-mmlab/mmdetection/blob/3b72b12fe9b14de906d1363982b9fba05e7d47c1/mmdet/datasets/pipelines/loading.py#L40), and [mmpose LoadImageFromFile](https://github.com/open-mmlab/mmpose/blob/f7b4b257d1364011966bc9eda9295fdd93684a0e/mmpose/datasets/pipelines/loading.py#L31), default `channel_order` are different. In top down inference demo, neither mmdet config or mmpose config uses a specific channel_order. So I am confused that which channel_order should be used when I feed image to the model. Should I specify a channel_order in my own config, or there is some convention that I did not find?

**Comment by ly015** [comment]
Yes, for now, mmdet and mmpose use different default channel orders, mmdet uses 'bgr' and mmpose uses 'rgb'. We are considering switching to 'bgr' in mmpose to align with mmdet in a future version.

**Comment by tongda** [comment]
Thanks.

**Comment by hfassold** [comment]
Is that still valid - so does MMPose 1.X still expect the input image in RGB ?
