### ISSUE TITLE
The question about coco whole body！

### ISSUE THREAD

**Issue by 2050airobert** [open-mmlab/mmpose#1574]
hi，
请问下，具体标注的时候，对于脚部的三个点是完全人工标注的，标注的实际操作中具体的大脚趾和小脚趾是如何找到具体的点的，尤其是coco 大部分图片都是穿鞋的情况，这个要找大脚趾更是难上加难，具体咱们如何保证标注点的准确性和高质量结果呢？ 是否有什么措施，或者具体的标注规则是？
期待您的回答

BR

**Comment by jin-s13** [comment]
replied in https://github.com/jin-s13/COCO-WholeBody/issues/31
