### ISSUE TITLE
Cross-dataset evaluation

### ISSUE THREAD

**Issue by huyphan168** [open-mmlab/mmpose#1578]
In the literature on 3D pose lifting, cross-dataset evaluation is important for generalization examination. However, I did not find any mechanism for this task in MMPose. Specifically, it is similar to training on H36M and evaluating on 3DHP at the same time while training. I found that the key points order in 3DHP is different from H36M and tried to permute the order of joints in prepare_data method but the result is unacceptable and even worse than the unpermuted order (700 mm MPJPE in the 3DHP test while training on H36M). Any specific note or modification that I should take into account for this task?

**Comment by ly015** [comment]
I am afraid there is no simple way to do this in MMPose so far. Maybe you can reorganize the 3DHP annotation into the H36M format and load it using `Body3DH36MDataset`?

**Comment by huyphan168** [comment]
What about permuting the order of joints in prepare_data method? Do you think it's plausible?

**Comment by huyphan168** [comment]
Thanks for reply, I have permuted the joints in load_annotations method as well as eliminate 3 joints in the literature for source:3DHP - target: Human3.6m cross evaluation. The results are quite consistent with other works. Please close this issue.
