### ISSUE TITLE
 Change the colour and thickness of the lines used to make skeleton. ?

### ISSUE THREAD

**Issue by YuktiADY** [open-mmlab/mmpose#1581]
I have generated the output images . How can we change the color and thickness of lines used to make skeleton ?

**Comment by ly015** [comment]
The keypoints and skeletons are drawn by this function: https://github.com/open-mmlab/mmpose/blob/master/mmpose/core/visualization/image.py#L107

**Comment by YuktiADY** [comment]
Thank for the reply but isnt the thickness and radius needs to be changed in top_down_img_demo.py ?

For the changing the colours of skeleton it has to be changed through rgb values in dataset_info  ?

**Comment by ly015** [comment]
Yes, colors can be set in the dataset_info.
In `top_down_img_demo.py` you can set visualization arguments here: https://github.com/open-mmlab/mmpose/blob/master/demo/top_down_img_demo.py#L116

**Comment by YuktiADY** [comment]
> The keypoints and skeletons are drawn by this function: https://github.com/open-mmlab/mmpose/blob/master/mmpose/core/visualization/image.py#L107

by changing the thickness of bbox to 4, change doesnt work ...

**Comment by YuktiADY** [comment]
> Yes, colors can be set in the dataset_info. In `top_down_img_demo.py` you can set visualization arguments here: https://github.com/open-mmlab/mmpose/blob/master/demo/top_down_img_demo.py#L116

How to change the thickness of bbox ? 
because i tried changing  https://github.com/open-mmlab/mmpose/blob/master/mmpose/core/visualization/image.py#L107
here but there seems to be no difference.

Is there any way to change directly in this below file ?
 https://github.com/open-mmlab/mmpose/blob/master/demo/top_down_img_demo.py#L116
