### ISSUE TITLE
3d pose benchmark table

### ISSUE THREAD

**Issue by jinfagang** [open-mmlab/mmpose#1587]
Hi, which model in mmpose on 3d pose estimation is the best one?

**Comment by jin-s13** [comment]
The modelzoo can be found at https://mmpose.readthedocs.io/en/latest/topics/body%283d%2Ckpt%2Csview%2Cimg%29.html

3d pose estimation includes different sub-tasks (image-based, video-based, multi-view based), and each subtask has different datasets. You can find the best model for each dataset from the modelzoo.

**Comment by jinfagang** [comment]
@jin-s13 thanks, I always think html is not intuitive to look, if there is a markdown table list all metric in a single table would be better. Like detectron2 and mmdetection does.
