### ISSUE TITLE
AID training is worng

### ISSUE THREAD

**Issue by lidc1004** [open-mmlab/mmpose#1595]
run hrnet _w32_coco_256x192_udp_regress 
  File "/extraStore/userdata/356430/mmpose-master/mmpose/core/evaluation/top_down_eval.py", line 586, in keypoints_from_heatmaps
    index += W * H * np.arange(0, N * K / 3)
ValueError: operands could not be broadcast together with shapes (32,17) (544,) (32,17)

**Comment by alaa-shubbak** [comment]
@lidc1004 
can you plz explain to me how did you solve such error?
