### ISSUE TITLE
How to calculate inference speed

### ISSUE THREAD

**Issue by YuktiADY** [open-mmlab/mmpose#1599]
I want to check the inference speed of GPU of HRNET model. How can i do that ?
I am using topdown_img_demo.py to output images , so do we need to write code ?

Please suggest

**Comment by ly015** [comment]
We have provided a summary of model inference speed (https://mmpose.readthedocs.io/en/latest/inference_speed_summary.html), which focused on the model forward time and ignore the pre/post-processing part. You can also add a timer in `topdown_img_demo.py` to check the entire inference time, like:

```python
from mmcv import Timer

timer = Timer()

# All inference code

t = timer.since_start()  # The time cost in second
```

**Comment by YuktiADY** [comment]
Thank you for the answer.Yes I am able to solve this now.

I have one more issue opened .Could you please tell that ?
