### ISSUE TITLE
How to show pose label in result image?

### ISSUE THREAD

**Issue by blackCmd** [open-mmlab/mmpose#16]
How to show pose label like this.
> ![image](https://user-images.githubusercontent.com/13531174/87875306-5f448b00-ca0b-11ea-9665-c4ecf181824d.png)

And If it can, Can I train pose? not object.
For example, MMdetction will show three `person` labels in the above image.
But I want to show another three labels in the above image like `sitting`, `hitting` and `standing`.

**Comment by innerlee** [comment]
> And If it can, Can I train pose? not object.

Could you elaborate a little bit? is "train" a typo?

**Comment by jin-s13** [comment]
Hi. The COCO dataset does not provide `action` label (such as standing, hitting and sitting). You may need to train an action classifier using the human poses as input, and outputs the `action` type.

You can also choose to directly use the action recognition dataset. As far as I am concerned, some datasets already provide both human poses and action labels. see http://humaninevents.org/ for example.

**Comment by blackCmd** [comment]
> Hi. The COCO dataset does not provide `action` label (such as standing, hitting and sitting). You may need to train an action classifier using the human poses as input, and outputs the `action` type.
> 
> You can also choose to directly use the action recognition dataset. As far as I am concerned, some datasets already provide both human poses and action labels. see http://humaninevents.org/ for example.

Oh, I see.
Then I think MMpose can inference human's action using trained keypoints. Is it right?
If you know where should I edit code for showing action label in a result image.

**Comment by innerlee** [comment]
AD: 
for rgb based action recognition: https://github.com/open-mmlab/mmaction2
for skeleton based action recognition: https://github.com/open-mmlab/mmskeleton

**Comment by blackCmd** [comment]
> AD:
> for rgb based action recognition: https://github.com/open-mmlab/mmaction2
> for skeleton based action recognition: https://github.com/open-mmlab/mmskeleton

Unbelievable !! 
It is what i want to do. Thank you : )
