### ISSUE TITLE
Radius of facial and body keypoints

### ISSUE THREAD

**Issue by YuktiADY** [open-mmlab/mmpose#1601]
Is it possible we can change the radius of facial and body keypoints ??
Because in the code there is option to only change the body keypoints .
How can we add parser,add argument ? Because of facial keypoints i want different radius .

The below code sets the radius for all the keypoints in the body.
 parser.add_argument(
        '--kpt-thr', type=float, default=0.3, help='Keypoint score threshold')
    #parser.add_argument(
        #'--radius',
        #type=int,
        #default=4,
        #default=10,
        #help='Keypoint radius for visualization')

I tried add argument for facial keypoints but how to specify the keypoints int the below code:

parser.add_argument(
        '--radius of face',
        type=int,
        default=6,
        help='Keypoint radius for visualization')

@jin-s13  @ly015  PLease suggest !

Awating for your reply.

**Comment by jin-s13** [comment]
You may need to understand how radius works. I suggest reading the codes of visualization and then modify the args.
