### ISSUE TITLE
想请教一下训练中的acc_pose的定义是什么呢？

### ISSUE THREAD

**Issue by ShaneCan** [open-mmlab/mmpose#1602]
想请教一下训练中的acc_pose的定义是什么呢？谢谢！

**Comment by jin-s13** [comment]
大概是 PCK, thr=0.05

**Comment by ShaneCan** [comment]
> PCK

取值时0.05嘛 这个值好小

**Comment by jin-s13** [comment]
MPII 是 PCKh，以人头框做归一化。
这里是以人体框做归一化。

**Comment by ShaneCan** [comment]
> MPII 是 PCKh，以人头框做归一化。 这里是以人体框做归一化。

感谢金哥
