### ISSUE TITLE
wholebody zoomnet missing！！！

### ISSUE THREAD

**Issue by 2050airobert** [open-mmlab/mmpose#1609]
hi，
    请问下 coco-wholebody 里面用到的zoomnet，完整识别133个关键点的模型，什么时候会发布出来呢？ 
   是否有相关资料和mmpose代码链接分享下呢，多谢~~~
BR

**Comment by jin-s13** [comment]
感谢关注Thanks♪(･ω･)ﾉ  
暂时确实还没公开这部分的代码和模型。其实是有开源计划的，但事情比较多耽搁了。
最近有时间的话，我会再整理一下代码，在mmpose里复现一下 ZoomNAS & ZoomNet。
