### ISSUE TITLE
我想把训练一个基于deeppose的mobilenetv3模型，然后训练的时候出错了，能帮我看看哪里出问题了吗？

### ISSUE THREAD

**Issue by zeckireck** [open-mmlab/mmpose#1615]
这个是报的错
![image](https://user-images.githubusercontent.com/81000191/187626778-c38c9d79-8567-49e0-b0c8-04f17ece2d15.png)

这个是配置文件的截图
![image](https://user-images.githubusercontent.com/81000191/187626510-01d4c7c5-489e-4d2b-b687-708a22dcf630.png)
![image](https://user-images.githubusercontent.com/81000191/187626621-82decdba-8c35-4621-b25f-599927db83a1.png)

**Comment by zeckireck** [comment]
嗯，能正常训练基于top-down的mobilenetv3

**Comment by Ben-Louis** [comment]
这个 bug 可能是因为 FC 层 input, weight 维度不一致导致的。
MobileNetV3  `arch='small'` 的时候，输出的 feature map 维度数是96，`keypoint_heat.in_channels` 可以改成96试一下。
或者可以尝试  `arch='big'`，对应的 backbone 输出的 feature map 维度数是 160
