### ISSUE TITLE
How to use mmpose for mouse detection & pose estimation?

### ISSUE THREAD

**Issue by tiger990111** [open-mmlab/mmpose#1630]
Dear,
  Thank you for all you jobs. I am now wondering how to get a mouse detection and a mouse pose estimation. I know there are some pretrained modals and relative configs. But I notice that they are trained on datasets like ap10K, which includes 50+ species. So what can I do if I just want "mouse/rodent" detection & pose estimation？

**Comment by tiger990111** [comment]
I mean there is no extra parameter to specify species(for here, I want "mouse").

**Comment by jin-s13** [comment]
AP100k models are trained for general 4-foot animals. It might be also useful for detecting mouse keypoints. 
You do not need to specify the species. Pls directly try the model and see if it works.

We do not provide mouse detection models. I am afraid that you may need to train your own mouse detection models, possibly using mmdetection.

**Comment by tiger990111** [comment]
Got you. Thank you very much!
