### ISSUE TITLE
COCO json annotation format: image and annotation IDs

### ISSUE THREAD

**Issue by julianzille** [open-mmlab/mmpose#1643]
Following the COCO '.json' annotation format, is it ok if an image id and annotation id have the same value? Ie.
{
   "images": [ { "id": 26, "width": ... }, ... ]
   
    "annotations": [ {"id" : 26, "image_id": 26, ...}]
}

**Comment by jin-s13** [comment]
Yes. It is ok.

**Comment by julianzille** [comment]
Thank you. Furthermore, is it possible for an image in the training data annotation file to have the same ID as an image in the validation file, provided the images are in separate folders?

**Comment by jin-s13** [comment]
Do you mean that the training json file and the validation json file have different images (but have the same image id?)
Since they are in different json files, it is okay. But I will suggest using separate ids to avoid confusion :)
