### ISSUE TITLE
Is it suitable for the outline of the animal

### ISSUE THREAD

**Issue by monkeycc** [open-mmlab/mmpose#1648]
![微信截图_20220908205708](https://user-images.githubusercontent.com/6490927/189127616-719b93d8-620e-460f-95a0-18ac66b9fe46.png)

Is it suitable for the outline of the animal

I need to know exactly the height and length of each node

Is mmpose appropriate

**Comment by monkeycc** [comment]
Maybe each node (instead of the whole animal individual) can be considered as an with 4 keypoints
Yes, you can also understand it this way


The middle abdominal section is really tricky
Because I need the outline width and height of each node

**Comment by jin-s13** [comment]
I think you may have a try. labeling its outline is similar to face annotations.

**Comment by jin-s13** [comment]
One thing needs to be confirmed in advance: "Does each mantis shrimp have the same number of keypoints?"
