### ISSUE TITLE
SimCC support?

### ISSUE THREAD

**Issue by jinfagang** [open-mmlab/mmpose#1649]
https://github.com/leeyegy/SimCC

**Comment by Tau-J** [comment]
Yes, we have already implemented it in our 1.x branch

**Comment by jinfagang** [comment]
@Tau-J when will it release along with cocofullbody pretrain model? I would like to use it since it seems it has better performance while avoid lagging postprocessing of heatmaps. (don't know if real speed can be faster or not)

**Comment by Tau-J** [comment]
According to my test, it can be faster than the heatmap-based counterpart. As for pretrained models, they are still during training and we will release asap., maybe at the end of this month.

**Comment by jinfagang** [comment]
will it possible train a wholebody model as well? I'd like to seems how does to perform on challenge task.

**Comment by Tau-J** [comment]
I'm willing to release a wholebody pretrained model for you, but behind other planned models, so I'm afraid I can't give you a promise time. I'll do it if you can wait, or maybe you can train it by yourselves when the code release.

**Comment by jinfagang** [comment]
thank u!  would love to waiting for your pretrained models.
