### ISSUE TITLE
Question: Why inference_top_down_pose_model shows low FPS compared to benchmark_inference 

### ISSUE THREAD

**Issue by malpeddinilesh** [open-mmlab/mmpose#166]
This regarding inference_top_down_pose_model shows low FPS whereas benchmark_inference shows higher FPS. 

It will be helpful if you provide info and reason why inference_top_down_pose_model shows low FPS compared to benchmark_inference?

**Comment by innerlee** [comment]
note that benchmark_inference only timing model inference, and does not count the data loading time.

**Comment by malpeddinilesh** [comment]
If I am passing image in numpy array to "inference_top_down_pose_model", should it still take data loading time? 

Basically, I am actually doing inference using "inference_top_down_pose_model" and when I do the calculation for FPS just for the execution part of "inference_top_down_pose_model", I see very low FPS compared to "benchmark_inference".

**Comment by innerlee** [comment]
this line https://github.com/open-mmlab/mmpose/blob/5a4e472fd6aa8144089e978832b40e1f438b8db3/mmpose/apis/inference.py#L328 is doing data processing

**Comment by malpeddinilesh** [comment]
Data processing such as "test_pipeline" should it take that much process to lower the FPS. 

For example on "benchmark_inference" I am getting about 10 FPS and with "inference_top_down_pose_model" I am getting around 6 FPS. 

Thank you for your quick response!

**Comment by innerlee** [comment]
yes processing takes time. in benchmark code, the preprocessing and gpu inference are overlapped in parallel, while in inference code, they are run in serial

**Comment by malpeddinilesh** [comment]
Thank you for your valuable feedback!
