### ISSUE TITLE
about output

### ISSUE THREAD

**Issue by frensher** [open-mmlab/mmpose#1665]
你好,我想问下
人体骨架关键点检测
怎么在无GT的情况下
输入关键点的x,y,conf的文本信息呢

**Comment by jin-s13** [comment]
Sorry I do not understand your question. Could you please describe your question in more details?

**Comment by Actmaiji** [comment]
请问lite-hrnet 18网络的输入是直接resize成192*256吗?还是通过其他的方式

**Comment by ly015** [comment]
> 请问lite-hrnet 18网络的输入是直接resize成192*256吗?还是通过其他的方式

是的，在 top-down 方法中，通常是通过一个 affine transform 将 bbox 区域图像 resize 成网络输入大小（如192x256）

**Comment by ly015** [comment]
We will close this issue for now. Please feel free to re-open it if there are further questions.
