### ISSUE TITLE
Is this detection result a bug or a performance issue?

### ISSUE THREAD

**Issue by VisImage** [open-mmlab/mmpose#1666]
I am not sure if the detection result below is a performance issue, or a bug in the configuration. The key points detected from the algorithm is so strange. This result is generated using the following instruction as indicated in the file "https://github.com/open-mmlab/mmpose/blob/master/docs/en/install.md":
 
Option (b). If you install mmpose with pip, open you python interpreter and copy&paste the following codes.

from mmpose.apis import (init_pose_model, inference_bottom_up_pose_model, vis_pose_result)
config_file = 'associative_embedding_hrnet_w32_coco_512x512.py'
checkpoint_file = 'hrnet_w32_coco_512x512-bcb8c247_20200816.pth'
pose_model = init_pose_model(config_file, checkpoint_file, device='cpu')  # or device='cuda:0'
image_name = 'demo/1015.jpg'
pose_results, _ = inference_bottom_up_pose_model(pose_model, image_name)
vis_pose_result(pose_model, image_name, pose_results, out_file='demo/vis_persons.jpg')

![vis_persons](https://user-images.githubusercontent.com/38402317/190562600-d300c6a0-e2fa-4d6f-b078-80f52822eb80.jpg)

original image is as below:
![1015](https://user-images.githubusercontent.com/38402317/190562891-490c0c4f-1ac4-411e-8188-cdf54b5af5ba.jpg)

**Comment by jin-s13** [comment]
It is a performance issue. The bottom-up AE model may not perform very well in crowded scenes.
You may also try top-down models. They normally perform better than bottom-up ones.
