### ISSUE TITLE
about NO GT inference

### ISSUE THREAD

**Issue by frensher** [open-mmlab/mmpose#1667]
你好
我想问下
如何在没有gt的前提下
还没有对应对json
利用demo进行关键点推理呢

**Comment by liqikai9** [comment]
你好，可以参考这个[文档](https://github.com/open-mmlab/mmpose/blob/master/demo/docs/2d_human_pose_demo.md#using-mmdet-for-human-bounding-box-detection)，使用 mmdet 检测人体，无需 gt 和对应的 json。

**Comment by frensher** [comment]
> 你好，可以参考这个[文档](https://github.com/open-mmlab/mmpose/blob/master/demo/docs/2d_human_pose_demo.md#using-mmdet-for-human-bounding-box-detection)，使用 mmdet 检测人体，无需 gt 和对应的 json。

谢谢
