### ISSUE TITLE
root_trajectory in 3d pose video demo

### ISSUE THREAD

**Issue by darcula1993** [open-mmlab/mmpose#1670]
Seems that 3d pose video demo do not consider root_trajectory output from videopose3d self-supervised model? The root node is always on the original point（0，0，0）.
The config file is:`configs/body/3d_kpt_sview_rgb_vid/video_pose_lift/h36m/videopose3d_h36m_27frames_fullconv_semi-supervised.py`

**Comment by ly015** [comment]
Sorry for the late reply. Yes, this model only predicts the relative keypoint coordinates around the root.

**Comment by darcula1993** [comment]
Maybe I can submit a PR to add root traj info? Since semi-surpervised 3d model can output root position info.

**Comment by ly015** [comment]
Wow, that would be great! Thank you very much and we are looking forward to your PR.
