### ISSUE TITLE
Why heatmap_size is 1/4 of the image_size, how to get rid of it.

### ISSUE THREAD

**Issue by chenxinfeng4** [open-mmlab/mmpose#1672]
I see there are always the shrink of heatmap_size in many top-down and bottom-up models. For example, if the image_size=512, then the heatmap_size=512/4=128 . Why we need to shrink the heatmap_size by "1/4"? And the head decoder must restore the "1/4" relationship, nothing but wasting time. Sometimes, it's a disaster for small animal or small image_size.

```
# TopDown HRnet; TopDown TopdownHeatmapSimpleHead
data_cfg = dict(
    image_size=[512, 512],
    heatmap_size=[128, 128],
    ...
)
```

Why just make they equal? If I must need it so how can I make then equal? Is there any template CONFIG file I can get started with?
```
# What I want
data_cfg = dict(
    image_size=[512, 512],
    heatmap_size=[512, 512],
    ...
)
```

**Comment by Tau-J** [comment]
1/4 is an empirical choice to balance the computation cost and performance. You can add more deconv layers by setting `num_deconv_layers ` in `TopdownHeatmapSimpleHead ` to obtain higher resolution heatmaps.

**Comment by chenxinfeng4** [comment]
Ohh, I will try it by myself. Thanks.
