### ISSUE TITLE
Using MMPose with MMDet to output labelled keypoints+bbox to a file

### ISSUE THREAD

**Issue by julianzille** [open-mmlab/mmpose#1675]
Hi everyone.

I was hoping anyone could assist me with something: I have managed to generate a labelled video incl. bbox and keypoints, using 'demo/top_down_pose_tracking_demo_with_mmdet.py'. 

I was wondering if there was a way to output the generated labels, maybe to a '.pkl' or '.csv' file (or any other format)? 

I hope someone is able to help - thanks in advance!

**Comment by Ben-Louis** [comment]
Hi, thanks for using MMPose. To save inference results, you need to modify the demo script. Take `demo/top_down_pose_tracking_demo_with_mmdet.py` for example, you can save bboxes and keypoints by the following steps:

1. Initialize an empty list before [the start of the loop](https://github.com/open-mmlab/mmpose/blob/af2cacd8492bea3b18d7eb407c5b9e52af1ad2fb/demo/top_down_pose_tracking_demo_with_mmdet.py#L175)
2. Append `pose_results` to the list after [smoothing](https://github.com/open-mmlab/mmpose/blob/af2cacd8492bea3b18d7eb407c5b9e52af1ad2fb/demo/top_down_pose_tracking_demo_with_mmdet.py#L210-L211)
3.  Save the list to disk after the loop using pickle or json_tricks
