### ISSUE TITLE
Freihand PCK and AUC question

### ISSUE THREAD

**Issue by pablovela5620** [open-mmlab/mmpose#168]
So looking at the evaluation code in the topdown Freihand dataset, I'm confused about the percentage of keypoints and area under the curve metrics

for PCK my confusion involves the naming of the threshold. When I look at the code below it seems like the threshold is actually the normalization factor? Is this correct or am I missing something? So its the percentage of keypoints within 1 pixel normalized by 1/5 the bounding box size? Why is this the choice for normalization/threshold value
```python
if 'PCK' in metrics:
        hit = 0
        exist = 0

        for pred, item in zip(preds, self.db):
            bbox = np.array(item['bbox'])
            threshold = np.max(bbox[2:]) * 0.2
            h, _, e = keypoint_pck_accuracy(
                    np.array(pred['keypoints'])[None, :, :-1],
                    np.array(item['joints_3d'])[None, :, :-1], 1,
                    np.array([[threshold, threshold]]))
            hit += len(h[h > 0])
            exist += e
        pck = hit / exist

        info_str.append(('PCK', pck))
```

In the case of AUC why is the choice now 30 for the normalization vs the bounding box method in PCK.
```python
if 'AUC' in metrics:
    info_str.append(('AUC', keypoint_auc(outputs, gts, 30)))
```

Also looking at the original Freihand dataset, there is no normalization in the distance calculations. Why the choice to add this?

Appreciate the help

**Comment by jin-s13** [comment]
To the best of our knowledge, there are only a few research works on **2d** hand pose estimation. Please also note that FreiHand is initially proposed as a **3d** hand pose estimation dataset. We surveyed the papers on 2d hand pose estimation and found that most of them reported PCK@0.2, AUC and EPE.

In our implementation, we simply report PCK@0.2 (normalized by the bounding box size) following [OneHand10K](https://www.yangangwang.com/papers/WANG-MCC-2018-10.html). We follow [Boukhayma et al.](https://arxiv.org/abs/1903.00812) and [Zimmermann et al.](https://openaccess.thecvf.com/content_ICCV_2017/papers/Zimmermann_Learning_to_Estimate_ICCV_2017_paper.pdf) to use AUC ranging from 0 to 30 px for 2d keypoint estimation.

**Comment by jin-s13** [comment]
Yes, the naming of the threshold & normalization is a little bit confusing. We will make this clear soon. 
It would be better to set `thr=0.2` and `normalize=[np.max(bbox[2:]), np.max(bbox[2:])]` @liuxin9608

**Comment by pablovela5620** [comment]
Great, thank you for clearing that up. I appreciate all the effort you guys are making in this space
