### ISSUE TITLE
h36 Annotation Format

### ISSUE THREAD

**Issue by julianzille** [open-mmlab/mmpose#1683]
Hi everyone.

I am busy training a model based on VideoPose3D's architecture on my own dataset, and was wondering if anyone could share the general format of the annotation files (`cameras.pkl`, `h36m_train.npz`, `_rel_stats.pkl` and `_stats.pkl` files) that are used (after h36 preprocessing). I am able to get my custom annotations into coco format, but it is difficult to infer from `preprocess_h36m.py` and `h36m_to_coco.py` what the suitable format is.

Thank you in advance!

**Comment by ly015** [comment]
Hi, h36m data can be downloaded from the [official site](http://vision.imar.ro/human3.6m/description.php). You may consider downloading some of the annotation files to check the format.
