### ISSUE TITLE
The heatmap of pose 2d not match to original input image

### ISSUE THREAD

**Issue by andy1213aa** [open-mmlab/mmpose#1685]
HI, 

I'm using heatmap to help with some research about pose reconstruction from occlusion.
However, I met a curious situation while visualizing the heatmap that I checked all the issues whit the keyword "heatmap" whit no help.

In my cognition, the heatmap indicates where the joint most probably is, so I set the 'return_heatmap=True' in "inference_top_down_pose_model" and successfully got the heatmap ndarray with the size (17, 64, 48). 

(P.S. The config file is "hrnet_w48_coco_256x192.py" and ckpt file is "hrnet_w48_coco_256x192-b9e0b3ab_20200708.pth", which are all download from mmpose github without any change.)

Since the output heatmap size is (64, 48) for each joint, which does not match the original input size, I resize the input detect crop image into (64, 48). Next, stack the heatmaps and the resized crop image on top of each other.
The result I got is as follows:

![圖片9](https://user-images.githubusercontent.com/59753286/192280487-e50f4b99-93bf-44a5-9383-a3f324e7ae84.png)

It seems there exists some shift or padding in the heatmap(?)
But except for the heatmap, the model outputs, including "bbox" and "2D keypoints", are all correct and perfect.
What can explain why the heatmap does not match the input image but predict the good 2D keypoints position simultaneously?
Did I misunderstand the heatmap, or am I doing something less under the mmpose framework?

I really appreciate any help you can provide.

**Comment by andy1213aa** [comment]
As a side note, the above question arises because the heatmaps will be a basis for accuracy probability in my research, so I need the points of these heatmaps to be in the correct positions; thank you!

**Comment by andy1213aa** [comment]
(Sorry for accidentally pressing the closed button)

As a side note, the above question arises because the heatmaps will be a basis for accuracy probability in my research, so I need the points of these heatmaps to be in the correct positions; thank you!

**Comment by ChenZhenGui** [comment]
hello ,could you tell me  how to slove the problem?
