### ISSUE TITLE
The 2D pose heatmaps not match to the input image.

### ISSUE THREAD

**Issue by andy1213aa** [open-mmlab/mmpose#1686]
(Sorry that I accidentally pressed the closed button)

HI, 

I'm using heatmap to help with some research about pose reconstruction from occlusion.
However, I met a curious situation while visualizing the heatmap that I checked all the issues whit the keyword "heatmap" whit no help.

In my cognition, the heatmap indicates where the joint most probably is, so I set the 'return_heatmap=True' in "inference_top_down_pose_model" and successfully got the heatmap ndarray with the size (17, 64, 48). 

(P.S. The config file is "hrnet_w48_coco_256x192.py" and ckpt file is "hrnet_w48_coco_256x192-b9e0b3ab_20200708.pth", which are all download from mmpose GitHub without any change.)

Since the output heatmap size is (64, 48) for each joint, which does not match the original input size, I resize the input detect crop image into (64, 48). Next, stack the heatmaps and the resized crop image on top of each other.
The result I got is as follows:

![圖片9](https://user-images.githubusercontent.com/59753286/192280487-e50f4b99-93bf-44a5-9383-a3f324e7ae84.png)

It seems there exists some shift or padding in the heatmap(?)
But except for the heatmap, the model outputs, including "bbox" and "2D keypoints", are all correct and perfect.
What can explain why the heatmap does not match the input image but predict the good 2D keypoints position simultaneously?
Did I misunderstand the heatmap, or am I doing something less under the mmpose framework?

The above question arises because the heatmaps will be a basis for accuracy probability in my research, so I need the points of these heatmaps to be in the correct positions; thank you!

I really appreciate any help you can provide.

**Comment by andy1213aa** [comment]
I see! Thank you for solving my doubts.

**Comment by github2016-yuan** [comment]
@andy1213aa  Hi, I also want to get the heatmap result image so I set "return_heatmap=True"
after the following cmd:
`python demo/top_down_img_demo.py configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w48_coco_256x192.py https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_coco_256x192-b9e0b3ab_20200708.pth  --img-root tests/data/coco/ --json-file tests/data/coco/test_coco.json --out-img-root vis_results`

I just get some vis image with points but no heatmap image. Do I miss something?

**Comment by Ben-Louis** [comment]
@github2016-yuan Hi, visualization of predicted heatmaps is supported in [MMPose 1.0](https://github.com/open-mmlab/mmpose/tree/1.x). Examples can be found in [human_pose_demo](https://github.com/open-mmlab/mmpose/blob/1.x/demo/docs/2d_human_pose_demo.md).

**Comment by github2016-yuan** [comment]
@Ben-Louis  Thanks! I will check it .
