### ISSUE TITLE
3D Human Pose Demo

### ISSUE THREAD

**Issue by julianzille** [open-mmlab/mmpose#1689]
Hi everyone. With reference to the image below, I am running the 3D Human Pose Two-Stage Estimation Video Demo (`demo/body3d_two_stage_video_demo.py`), and am trying to view the Prediction (0) video.  ![image](https://user-images.githubusercontent.com/112982053/192561898-60332375-828d-4760-82e0-a275540f7972.png)
The video saved after running the demo with the following flags only shows the 'Input' video.
``` --video-path cam3ph.mp4 --out-video-root cam3ph3D --radius 12 --thickness 4  ```.
Is there any way of generating this 'Prediction (0)' video using code available in MMPose? 

Thanks in advance.

**Comment by ly015** [comment]
Hi, thanks for the feedback. However, we couldn't reproduce this problem. Could you please provide more details, like the full demo command including the model information and the source video?

**Comment by julianzille** [comment]
I have trained a model using my own dataset, but have followed all the conventions of the h36 dataset and configs (`configs/body/3d_kpt_sview_rgb_vid/video_pose_lift/h36m/videopose3d_h36m_27frames_fullconv_supervised.py`). 

The demo command I used is:
```!python demo/body3d_two_stage_video_demo.py MMDet/configs/faster_rcnn_r50_fpn_2x_acino.py MMDet/epoch_4.pth configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/acino/res50_acino_256x256.py work_dirs/res50_acino_256x256_epoch150/epoch_150.pth configs/body/3d_kpt_sview_rgb_vid/video_pose_lift/h36m/videopose3d_acino_27frames_fullconv_supervised.py  work_dirs/videopose3d_acino_27frames_epoch160/latest.pth --video-path cam3ph.mp4 --out-video-root cam3ph3D```

cam3ph.mp4 is a video of a cheetah running. The output video looks something like 
![image](https://user-images.githubusercontent.com/112982053/192697394-fd389c11-66b0-406e-a724-56dd3346fa86.png)
which isn't unexpected -- I am just trying to get it in the form of 'Prediction (0)' (as above). I will continue looking and update this issue if I find anything. Thank you! @ly015

**Comment by ly015** [comment]
Thanks. Is there any error or warning information during the demo running?

**Comment by julianzille** [comment]
The only warning I get is ```/usr/local/lib/python3.9/dist-packages/mmdet/datasets/utils.py:66: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.```
I doubt this has anything to do with generating the output video(s)?

Is the code that was used to generate the videos in my initial comment's image available?

**Comment by ly015** [comment]
The command looks good and this warning should not affect the result. I am not sure about the reason why prediction visualization is missing. Maybe you will need to check the model output.
