### ISSUE TITLE
low fps(3 fps) on Nvidia Orin

### ISSUE THREAD

**Issue by venkatshivap** [open-mmlab/mmpose#1690]
Hi,

I'm trying to do real time pose estimation, but I'm getting very low 3 fps on Nvidia Orin. I want to achieve atleast 7 fps, could you please help me. Please find the details below

mmpose_pose_config="Downloads/mmpose/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w48_coco_256x192.py"
mmpose_pose_checkpoint="https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_coco_256x192-b9e0b3ab_20200708.pth"

cuda 11.4
jetpack 5.0.1
pytorch 1.12

Quick help would be really appreciated!

Thanks.

**Comment by ly015** [comment]
HRNet could be a little too heavy for real-time inference. Maybe consider models with lightweight backbones like MobileNet and ViPNAS?

And you can also raise issues at [MMDeploy](https://github.com/open-mmlab/mmdeploy) for questions about model deployment.
