### ISSUE TITLE
请教一下mmpose中有没有一些即插即用的模块可以使用

### ISSUE THREAD

**Issue by ShaneCan** [open-mmlab/mmpose#1694]
比如说一些可以插在backbone的模块等，谢谢！

**Comment by ly015** [comment]
请问具体指什么样的模块呢，可以举个例子么？

**Comment by ShaneCan** [comment]
> 请问具体指什么样的模块呢，可以举个例子么？

例如一些注意力机制等等

**Comment by ly015** [comment]
目前这方面没有太多支持，可以考虑看看 mmdetection 或者 mmclassification 里是否有你需要的模块。OpenMMLab 各 repo 之间的设计是比较一致的，应该可以轻松迁移其他 repo 里的模块到 mmpose 中。欢迎向 mmpose 提相关的 PR。
