### ISSUE TITLE
被遮挡（出镜头）的关键点问题

### ISSUE THREAD

**Issue by JACKYLUO1991** [open-mmlab/mmpose#1695]
我在测试代码的过程中发现，很多出镜头的关键点的坐标是随机的，是否有什么配置可以解决该问题？

**Comment by ly015** [comment]
是否可以对预测关键点分数设置阈值， 滤除出镜头关键点？

**Comment by JACKYLUO1991** [comment]
@ly015 确实在一般场景下是可以的，但在某些场景中即使不在图像中的关键点，其置信度也很大

**Comment by ly015** [comment]
@jin-s13 @Tau-J 请问对这个问题有什么建议么？

**Comment by Tau-J** [comment]
可以考虑以下方法：
1. 新增一个分支做2分类，预测每个点的存在性，用标注中的visible来监督，coco中0表示未标注，1和2表示有标注中有遮挡和无遮挡的情况，我们将0视为不存在，1和2视为存在进行存在性预测，新增的分支用bce来监督即可。
2. 也可以考虑用RLE等regression-based方法，修改数据增强，使target存在超出屏幕外的情况，让模型学习坐标值关系。
3. 调整现有heatmap对存在性的判定逻辑，默认的判定逻辑是heatmap的最大响应值是否大于阈值，可以修改为：对heatmap进行softmax归一化，然后统计最大值点周围RxR区域的响应值之和，也就是离散概率值之和是否大于阈值，也可以有效提升不可见点的判定

**Comment by JACKYLUO1991** [comment]
@Tau-J 多谢，我修改尝试一下

**Comment by betterhalfwzm** [comment]
> 

如果想把有遮挡和无遮挡也分类出来，应该如何做呢 @Tau-J

**Comment by Tau-J** [comment]
> > 
> 
> 如果想把有遮挡和无遮挡也分类出来，应该如何做呢 @Tau-J

可以选择用单独的二分类来区分，也可以用coco的原始标注0 1 2，做成三分类。哪一种更好需要实际验证一下。

**Comment by betterhalfwzm** [comment]
> > > 
> > 
> > 
> > 如果想把有遮挡和无遮挡也分类出来，应该如何做呢 @Tau-J
> 
> 可以选择用单独的二分类来区分，也可以用coco的原始标注0 1 2，做成三分类。哪一种更好需要实际验证一下。

有参考代码？每个点都做分类

**Comment by chenmz-lab** [comment]
> 可以考虑以下方法：
> 
> 1. 新增一个分支做2分类，预测每个点的存在性，用标注中的visible来监督，coco中0表示未标注，1和2表示有标注中有遮挡和无遮挡的情况，我们将0视为不存在，1和2视为存在进行存在性预测，新增的分支用bce来监督即可。
> 2. 也可以考虑用RLE等regression-based方法，修改数据增强，使target存在超出屏幕外的情况，让模型学习坐标值关系，这样即使点不存在也会按照结构信息进行预测，不会随机乱飘。
> 3. 还可以使用RLE预测的sigma作为存在性判定标准，类似于1中的方案，不过sigma是RLE方法已有的内容，所以不需要改模型。
> 4. 调整现有heatmap对存在性的判定逻辑，默认的判定逻辑是heatmap的最大响应值是否大于阈值，可以修改为：对heatmap进行softmax归一化，然后统计最大值点周围RxR区域的响应值之和，也就是离散概率值之和是否大于阈值，也可以有效提升不可见点的判定

您好，请问您说的012标注方法在cvat中如何实现呢？比如类似coco数据集的17个关键点已经标注了，这种情况怎么再加入1或者2的label呢？
![example](https://github.com/user-attachments/assets/851f1f26-af82-4d03-9030-5410368b55a6)
