### ISSUE TITLE
3D Body Pose Estimation Metrics

### ISSUE THREAD

**Issue by julianzille** [open-mmlab/mmpose#1696]
Hi!

Are the metrics MPJPE and P_MPJPE logged in meters or millimeters?

Thanks in advance 👍

**Comment by ly015** [comment]
The results reported in the model is in millimeters.
The raw output (e.g. the number in the log) may depend on the data annotation file. For example, in our experiments on h36m dataset, they are in meters.

**Comment by julianzille** [comment]
Thank you.
