### ISSUE TITLE
VideoPose 3D H36 2D annotations

### ISSUE THREAD

**Issue by julianzille** [open-mmlab/mmpose#1698]
Hi everyone. 

I have a question with regards to the 2D annotations used in the fully supervised learning of H36 dataset ([config](https://github.com/open-mmlab/mmpose/blob/master/configs/body/3d_kpt_sview_rgb_vid/video_pose_lift/h36m/videopose3d_h36m_27frames_fullconv_supervised.py)): what exactly happens when `joint_2d_src='pipeline'`? Does that mean that the 2D annotation will be loaded in the pipeline from an already existing 2D annotation file, or that 2D pose-estimation will be performed on an image in the pipeline using a pose-estimator to obtain the 2D annotation to be used in the pose-lift? Thanks in advance :)

**Comment by ly015** [comment]
Hi, sorry for the late reply. The setting `joint_2d_src='pipeline'` means to obtain 2d coordinates by projecting 3d keypoints to the image space with camera parameters in the pipeline (see [`CameraProjection`](https://github.com/open-mmlab/mmpose/blob/master/mmpose/datasets/pipelines/pose3d_transform.py#L234)). For now we don't have any configs using this setting.
