### ISSUE TITLE
transfer learning on pose models

### ISSUE THREAD

**Issue by adamsau** [open-mmlab/mmpose#1700]
is it possible to do transfer learning on HRNet / Lite HRNet? I am trying to do keypoint detection on objects, not human. Any guidance on that?

**Comment by jin-s13** [comment]
MMPose will load imagenet-pretrained model for transfer learning. If you have enough data (>hundreds of imgs), you can train a good enough model for objects.

**Comment by adamsau** [comment]
https://mmpose.readthedocs.io/en/latest/papers/backbones.html#topdown-heatmap-litehrnet-on-coco
can you share the link of Lite HRNet weights trained on imagenet? I can't seem to find the pretrained weights of different models.

**Comment by jin-s13** [comment]
lite-HRNet does not have imagenet pre-trained models. But HRNet has.

**Comment by adamsau** [comment]
is there a link for all models pretrained on imagenet?

**Comment by jin-s13** [comment]
Most models can be found in [MMClassification](https://github.com/open-mmlab/mmclassification) and mmcv [modelzoo](https://github.com/open-mmlab/mmcv/tree/master/mmcv/model_zoo).
