### ISSUE TITLE
多人背景下只保留单人姿态关键点（检测框最大），怎么实现啊

### ISSUE THREAD

**Issue by zzzwwb** [open-mmlab/mmpose#1701]
If you feel we have helped you, give us a STAR! :satisfied:

**Notice**

There are several common situations in the reimplementation issues as below

1. Reimplement a model in the model zoo using the provided configs.
2. Reimplement a model in the model zoo on other dataset (e.g., custom datasets).
3. Reimplement a custom model but all the components are implemented in MMPose.
4. Reimplement a custom model with new modules implemented by yourself.

There are several things to do for different cases as below.

- For case 1 & 3, please follow the steps in the following sections thus we could help to quick identify the issue.
- For case 2 & 4, please understand that we are not able to do much help here because we usually do not know the full code and the users should be responsible to the code they write.
- One suggestion for case 2 & 4 is that the users should first check whether the bug lies in the self-implemented code or the original code. For example, users can first make sure that the same model runs well on supported datasets. If you still need help, please describe what you have done and what you obtain in the issue, and follow the steps in the following sections and try as clear as possible so that we can better help you.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The issue has not been fixed in the latest version.

**Describe the issue**

A clear and concise description of what the problem you meet and what have you done.

**Reproduction**

- What command or script did you run?

```
A placeholder for the command.
```

- What config dir you run?

```
A placeholder for the config.
```

- Did you make any modifications on the code or config? Did you understand what you have modified?
- What dataset did you use?

**Environment**

1. Please run `PYTHONPATH=${PWD}:$PYTHONPATH python mmpose/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as

- How you installed PyTorch \[e.g., pip, conda, source\]
- Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Results**

If applicable, paste the related results here, e.g., what you expect and what you get.

```
A placeholder for results comparison
```

**Issue fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by jin-s13** [comment]
可以直接对 最后的生成结果做后处理啊

**Comment by jin-s13** [comment]
每个pose都会绑定到一个框上，只保留最大的框嘛。

**Comment by zzzwwb** [comment]
在代码中修改吗

**Comment by Yangninan** [comment]
> 在代码中修改吗

top-down 会对检测模型的结果进行自信度的筛选，你可以在这个筛选的基础上加一个比较面积的代码，max（w*h）筛选最大的检测框然后再做前处理传给模型。这样就只对面积最大的检测框进行关键点预测
