### ISSUE TITLE
mpii数据集测试demo报错

### ISSUE THREAD

**Issue by A-qingtongxiaoyou** [open-mmlab/mmpose#1711]
单帧视频预测configs使用COCO数据集训练得到的模型正常
`python demo/top_down_pose_tracking_demo_with_mmtracking.py \
        demo/mmtracking_cfg/tracktor_faster-rcnn_r50_fpn_4e_mot17-private.py \
        configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/res50_coco_256x192.py \
        https://download.openmmlab.com/mmpose/top_down/resnet/res50_coco_256x192-ec54d7f3_20200709.pth \
        --video-path data/Bolt_onestep.mp4 \
        --out-video-root outputs/D1/D1_3_mmtracking_single_frame`

改为mpii数据集训练得到的模型报错
(mmpose) pen@tesla-SYS-4028GR-TR:~/mmpose$ python demo/top_down_pose_tracking_demo_with_mmtracking.py \
    demo/mmtracking_cfg/deepsort_faster-rcnn_fpn_4e_mot17-private-half.py \ 
    configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/hourglass52_mpii_256x256.py \
    https://download.openmmlab.com/mmpose/top_down/hourglass/hourglass52_mpii_256x256-ae358435_20200812.pth \
    --video-path data/Bolt_downsampling.mp4 \
    --out-video-root outputs/D1/D1_3_mmtracking_single_frame

usage: top_down_pose_tracking_demo_with_mmtracking.py [-h] [--video-path VIDEO_PATH] [--show] [--out-video-root OUT_VIDEO_ROOT]
                                                      [--device DEVICE] [--bbox-thr BBOX_THR] [--kpt-thr KPT_THR] [--radius RADIUS]
                                                      [--thickness THICKNESS] [--smooth] [--smooth-filter-cfg SMOOTH_FILTER_CFG]
                          
![error](https://user-images.githubusercontent.com/80896381/194820463-385e50e1-7956-4336-98a3-e9187bf184c6.png)
                            [--use-multi-frames] [--online]
                                                      tracking_config pose_config pose_checkpoint
top_down_pose_tracking_demo_with_mmtracking.py: error: the following arguments are required: pose_checkpoint
configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/hourglass52_mpii_256x256.py: 行 1: _base_：未找到命令
configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/hourglass52_mpii_256x256.py: 行 2: ../../../../_base_/default_runtime.py,: 没有那个文件或目录
configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/hourglass52_mpii_256x256.py: 行 3: ../../../../_base_/datasets/mpii.py: 没有那个文件或目录
configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/hourglass52_mpii_256x256.py: 行 4: ]：未找到命令
configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/hourglass52_mpii_256x256.py: 行 5: 未预期的符号“(”附近有语法错误
configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/hourglass52_mpii_256x256.py: 行 5: `evaluation = dict(interval=10, metric=&apos;PCKh&apos;, save_best=&apos;PCKh&apos;)&apos;
</pre>

**Comment by Ben-Louis** [comment]
您好，出现这个问题的原因可能是运行demo脚本时命令格式不对，导致系统把你的命令当成两条命令来执行了。
可以尝试保持 使用COCO模型时的命令 格式不变，仅将 config & checkpoint 替换为MPII的 config & checkpoint

**Comment by A-qingtongxiaoyou** [comment]
谢谢您的提醒！未找到命令的问题已经解决。单帧视频预测可以用MPII的config
但是多帧视频预测依然不能改用MPII的config
命令：
(mmpose) pg@tesla-SYS-4028GR-TR:~/mmpose$ python demo/top_down_pose_tracking_demo_with_mmtracking.py     demo/mmtracking_cfg/tracktor_faster-rcnn_r50_fpn_4e_mot17-private.py     configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/hourglass52_mpii_256x256.py     https://download.openmmlab.com/mmpose/top_down/hourglass/hourglass52_mpii_256x256-ae358435_20200812.pth      --video-path data/ex-situ1.mp4     --out-video-root outputs/D1/D1_4_mmtracking_multi_frames     --smooth     --smooth-filter-cfg configs/_base_/filters/one_euro.py     --use-multi-frames     --online
报错：
Traceback (most recent call last):
  File "demo/top_down_pose_tracking_demo_with_mmtracking.py", line 226, in <module>
    main()
  File "demo/top_down_pose_tracking_demo_with_mmtracking.py", line 154, in main
    assert 'frame_indices_test' in pose_model.cfg.data.test.data_cfg
AssertionError


我注意到多帧视频预测configs
![image](https://user-images.githubusercontent.com/80896381/194996357-4e240c10-fe0c-45a8-840f-e091b80be133.png)
好像只有hrnet COCO数据集类型的

单帧视频预测configs支持的模型很多，有mpii格式的
![image](https://user-images.githubusercontent.com/80896381/194996611-53fa8494-88e9-4b2b-8523-1907587ba939.png)

**Comment by jin-s13** [comment]
mpii不是视频数据集，是单帧图片集，所以没有对应的config

**Comment by A-qingtongxiaoyou** [comment]
谢谢！
