### ISSUE TITLE
如何调用smoothNet模块

### ISSUE THREAD

**Issue by A-qingtongxiaoyou** [open-mmlab/mmpose#1713]
请问我该如何在demo中添加smooth的效果呢？我的命令行似乎没有启动smoothNet的模块。
命令：
python demo/top_down_pose_tracking_demo_with_mmdet.py \ demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py \ https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \ configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/res50_coco_256x192.py \ https://download.openmmlab.com/mmpose/top_down/resnet/res50_coco_256x192-ec54d7f3_20200709.pth \ --video-path data/ex-situ1.mp4 \ --out-video-root outputs/D1/D1_1_top_down_tracking_single_frame --smooth --smooth-filter-cfg

报错：
--smooth：未找到命令
--smooth-filter-cfg：未找到命令
![image](https://user-images.githubusercontent.com/80896381/195076280-01be07f2-f9b5-4a30-8fc0-6605cf33a9d8.png)

**Comment by ywyw1** [comment]
> 请问我该如何在demo中添加smooth的效果呢？我的命令行似乎没有启动smoothNet的模块。 命令： python demo/top_down_pose_tracking_demo_with_mmdet.py \ demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py \ https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \ configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/res50_coco_256x192.py \ https://download.openmmlab.com/mmpose/top_down/resnet/res50_coco_256x192-ec54d7f3_20200709.pth \ --video-path data/ex-situ1.mp4 \ --out-video-root outputs/D1/D1_1_top_down_tracking_single_frame --smooth --smooth-filter-cfg
> 
> 报错： --smooth：未找到命令 --smooth-filter-cfg：未找到命令 ![image](https://user-images.githubusercontent.com/80896381/195076280-01be07f2-f9b5-4a30-8fc0-6605cf33a9d8.png)

请问你解决了吗
