### ISSUE TITLE
Custom dataset keypoints

### ISSUE THREAD

**Issue by LjIA26** [open-mmlab/mmpose#1714]
Hello, 

I want to train on a custom dataset. I am a bit confused on the keypoints information on the COCO annotations are [x, y, ? ]?  What is the third coordinate? I see that they have 0, 1, and 2. 0 when x and y are also zero, but then what does 1 and 2 mean? 

Thanks in advance.

**Comment by ly015** [comment]
Hi, below is the description of the keypoint annotation from the [official site](https://cocodataset.org/#format-data):


> "Each keypoint has a 0-indexed location x,y and a visibility flag v defined as v=0: not labeled (in which case x=y=0), v=1: labeled but not visible, and v=2: labeled and visible."

**Comment by chungusmungus555** [comment]
> Hello,
> 
> I want to train on a custom dataset. I am a bit confused on the keypoints information on the COCO annotations are [x, y, ? ]? What is the third coordinate? I see that they have 0, 1, and 2. 0 when x and y are also zero, but then what does 1 and 2 mean?
> 
> Thanks in advance.

Hey, I'm trying to generate a custom dataset for coco 17 keypoints and would just like to ask what tool you used to generate your dataset?

**Comment by LjIA26** [comment]
Hello,

I used labelbox!
