### ISSUE TITLE
mmpose1.x face 2d keypoints 

### ISSUE THREAD

**Issue by PureHing** [open-mmlab/mmpose#1723]
你好，请问mmpose1.x face 2d keypoints的simcc等相关code和预训练大概多久会出来？
对于在1.x的版本里，我是否可以直接用body 2d kps改为face 2d kps？如果我想在face kps上只训练眼睛，现在支持特定部位训练吗？

**Comment by ly015** [comment]
你好，我们目前暂时没有添加 simcc face keypoint model 的计划，如果需要欢迎在 [modelzoo request](https://github.com/open-mmlab/mmpose/issues/383) 中留言提供详细的需求，我们会优先安排进行支持。

在 1.x 版本里，建议通过直接修改标注文件（`ann_file`）和数据集信息（`metainfo`）中关键点定义的方式，实现只保留特定关键点进行训练。我们后续会考虑支持通过配置文件实现该功能。

**Comment by PureHing** [comment]
Thank you
