### ISSUE TITLE
An abnormal result of testing

### ISSUE THREAD

**Issue by SicongLiu998** [open-mmlab/mmpose#1726]
Thanks for your error report and we appreciate it a lot.
If you feel we have helped you, give us a STAR! :satisfied:

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.
When I use the MMPose V1.x , I tried to train a model based on AP-10K data set. I found that the result of val is too low than usual (after 10 epoch) . But I had not done any change of config file and all of setting is in default  version. And I also download the official checkpoint file from MMPose and finished the test process on my server.  But the value of AP is also too low. 

**Reproduction**

- What command or script did you run?
bash tools/dist_train.sh   configs/animal_2d_keypoint/topdown_heatmap/ap10k/td-hm_hrnet-w32_8xb64-210e_ap10k-256x256.py   1

and 

python tools/test.py  configs/animal_2d_keypoint/topdown_heatmap/ap10k/td-hm_hrnet-w32_8xb64-210e_ap10k-256x256.py   hrnet_w32_ap10k_256x256-18aac840_20211029.pth

the output  of  the second is as below:

Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] =  0.051
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets= 20 ] =  0.064
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets= 20 ] =  0.054
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] =  0.003
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] =  0.052
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] =  0.048
 Average Recall     (AR) @[ IoU=0.50      | area=   all | maxDets= 20 ] =  0.060
 Average Recall     (AR) @[ IoU=0.75      | area=   all | maxDets= 20 ] =  0.050
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] =  0.003
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] =  0.049
10/15 21:04:52 - mmengine - INFO - Epoch(test) [83/83]  coco/AP: 0.051226  coco/AP .5: 0.064356  coco/AP .75: 0.053531  coco/AP (M): 0.003159  coco/AP (L): 0.052346  coco/AR: 0.047891  coco/AR .5: 0.059690  coco/AR .75: 0.050285  coco/AR (M): 0.003030  coco/AR (L): 0.049195

```
A placeholder for the command.
```

- What config did you run?
-the default version of the file
mmpose/configs/animal_2d_keypoint/topdown_heatmap/ap10k/td-hm_hrnet-w32_8xb64-210e_ap10k-256x256.py

```
A placeholder for the config.
```

- Did you make any modifications on the code or config? Did you understand what you have modified?
- No, I did not.
- What dataset did you use?
AP-10K
**Environment**

1. Please run `PYTHONPATH=${PWD}:$PYTHONPATH python mmpose/utils/collect_env.py` to collect necessary environment information and paste it here.
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.9.24=ha878542_0
  - cudatoolkit=11.3.1=h9edb442_10
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=hca18f0e_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h166bdaf_2
  - lame=3.100=h166bdaf_1003
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=4.0.0=h27087fc_0
  - libdeflate=1.14=h166bdaf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgomp=12.1.0=h8d9b700_16
  - libiconv=1.17=h166bdaf_0
  - libnsl=2.0.0=h7f98852_0
  - libpng=1.6.38=h753d276_0
  - libsqlite=3.39.4=h753d276_0
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libtiff=4.4.0=h55922b4_4
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.44.2=h166bdaf_0
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libzlib=1.2.13=h166bdaf_4
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h95df7f1_0
  - mkl_fft=1.3.1=py38h8666266_1
  - mkl_random=1.2.2=py38h1abd341_0
  - ncurses=6.3=h27087fc_1
  - nettle=3.6=he412f7d_0
  - numpy=1.23.1=py38h6c91a56_0
  - numpy-base=1.23.1=py38ha15fc14_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.5.0=h7d73246_1
  - openssl=3.0.5=h166bdaf_2
  - pillow=9.2.0=py38ha3b2c9c_2
  - pip=22.2.2=pyhd8ed1ab_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - python=3.8.13=ha86cf86_0_cpython
  - python_abi=3.8=2_cp38
  - pytorch=1.10.1=py3.8_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - readline=8.1.2=h0f457ee_0
  - setuptools=65.4.1=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.39.4=h4ff8645_0
  - tk=8.6.12=h27826a3_0
  - torchaudio=0.10.1=py38_cu113
  - torchvision=0.11.2=py38_cu113
  - typing_extensions=4.4.0=pyha770c72_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=h166bdaf_4
  - zstd=1.5.2=h6239696_4

2. You may add addition that may be helpful for locating the problem, such as

- How you installed PyTorch \[e.g., pip, conda, source\]
- Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)
conda install pytorch==1.10.1 torchvision==0.11.2 torchaudio==0.10.1 cudatoolkit=11.3
**Error traceback**

If applicable, paste the error traceback here.

```
A placeholder for traceback.
```

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by Ben-Louis** [comment]
Hi, thank you for using MMPose and reporting this result. There is indeed a bug in [`AP10KCocoMetric.process`](https://github.com/open-mmlab/mmpose/blob/2489991b6f3b6fa17a8f3d135ba6e92986fc461c/mmpose/evaluation/metrics/coco_metric.py#L457-L474). 

In line 474
```python
for _, pred in zip(data_batch, predictions):
```
`data_batch` and `predictions` have different lengths. So only predictions of the first two samples in each batch are saved.
You can fix this bug simply by ignoring `data_batch` as it is not used:
```python
for pred in predictions:
```

Would you like to open a PR to fix this bug?

**Comment by SicongLiu998** [comment]
Thanks a lot for your help and reply!  I am going to open a PR in a few days.
