### ISSUE TITLE
AP and AR evaluation metrics for different IoU thresholds.

### ISSUE THREAD

**Issue by julianzille** [open-mmlab/mmpose#1728]
Hi there. 

I am performing top down single view pose estimation using a custom coco-style dataset. 
I am testing and validating my model with `use_gt_bbox=True`. A sample output is:
```
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] =  0.734
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets= 20 ] =  0.980
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets= 20 ] =  0.871
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] =  0.577
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] =  0.752
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] =  0.774
 Average Recall     (AR) @[ IoU=0.50      | area=   all | maxDets= 20 ] =  0.988
 Average Recall     (AR) @[ IoU=0.75      | area=   all | maxDets= 20 ] =  0.891
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] =  0.637
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] =  0.792
```
I don't understand how the average precision and recall results are different for different IoU thresholds? If the ground truth bounding boxes are used, will the IoU not be 1 every time? A possible explanation is that a bounding box is calculated from the predicted keypoints, and compared to the ground truth bounding box to calculate the IoU. I am unsure and if anyone could clarify it would be greatly appreciated!

**Comment by liqikai9** [comment]
@julianzille Hi. These AP and AR are not calculating based on bbox IOU. Instead, they calculate the **Object Keypoint Similarity (OKS)** of the ground truth and predicted keypoints, which also locates between [0, 1]. And these are OKS thresholds are for during matching the prediction to ground truth.

You may also refer to this [link ](https://cocodataset.org/#keypoints-eval)to have more detail about the keypoint evaluation in COCO dataset.

**Comment by julianzille** [comment]
Thank you @liqikai9. 
The output is a bit misleading was a bit misleading which makes me wonder if 'Average Precision' in the output is actually mAP (since 'mAP' is the only set evaluation metric)? Can you confirm this?

**Comment by liqikai9** [comment]
I am not sure what you mean by actually **`mAP`**? Did you mean the AP of multiple classes or categories? 

It is worth mentioning that these results are the AP on the `person` category. Usually, there are **only one** category in the pose estimation dataset, like person, hand, face, etc. It is a little different from `mAP` in the object detection, which is averaged over multiple object categries.

**Comment by julianzille** [comment]
I meant mean average precision. That helps, thanks again!

**Comment by julianzille** [comment]
I have looked more into this. From what I've [found](https://cocodataset.org/#keypoints-eval), the AP in keypoint detection is calculated using a specific OKS threshold, and mAP is calculated as the average AP across a range of OKS thresholds. This may help someone with the same confusion I had. Thanks again 👍
