### ISSUE TITLE
how to use many Gpus?

### ISSUE THREAD

**Issue by graceforlife** [open-mmlab/mmpose#1731]
what should I write if I want to run with cuda 0,1,2?
(I have tried it with the code"--device cuda:'0','1','2' " but faild)
thanks!

![Inked屏幕截图 2022-10-16 213721](https://user-images.githubusercontent.com/115878494/196038834-b5117774-a3ec-45ed-9e8b-6f281b55083e.png)

**Comment by ly015** [comment]
Hi, I am afraid this demo can not run with multiple GPUs. It's designed for a single GPU or CPU.

**Comment by graceforlife** [comment]
> Hi, I am afraid this demo can not run with multiple GPUs. It's designed for a single GPU or CPU.

ok,I konw,thanks u!
