### ISSUE TITLE
Evaluation of models with mmpose

### ISSUE THREAD

**Issue by IssaIssa1** [open-mmlab/mmpose#1732]
I was able to train a model using mmpose on cooc tiny following the tutorial and run predict and inference. 

But how may I evaluate my new model and report the accuracy metrics for example coco-tiny again. Is there any function/tutorial or api for this?

**Comment by ly015** [comment]
You can use `tools/test.py` for evaluation. Please refer to the [doc](https://mmpose.readthedocs.io/en/latest/get_started.html#inference-with-pre-trained-models) for details.

**Comment by ly015** [comment]
For now, we don't have such an evaluation method. You can follow the steps below to evaluate the model:

1. Organize your test data in a supported format (e.g. COCO)
2. Set the test dataset in the model config file
3. Run `tools/test.py` for evaluation

**Comment by ly015** [comment]
Sorry for the late reply. You may need to set `use_gt_bbox=True` in `data_cfg`.
