### ISSUE TITLE
How to extend 2D body keypoints?

### ISSUE THREAD

**Issue by Hwismos** [open-mmlab/mmpose#1738]
when I've used mmpose, I've got 17 points like that `"Nose", "Eyes", "Ears", "Shoulders", "Elbows", "Wrists", "Hips", "Knees", "Ankles"`.

I want to customize something in mmpose to extends points from 17 to 24 which includes `"Neck", "Back", "Waist", "Palms", "Foots"`.  

How to implement this?

**Comment by ly015** [comment]
Maybe you can use our whole-body keypoint model which predicts 133 keypoints. Check out the demo [here](https://github.com/open-mmlab/mmpose/blob/master/demo/docs/2d_wholebody_pose_demo.md).

![image](https://user-images.githubusercontent.com/9464825/95552839-00a61080-0a40-11eb-818c-b8dad7307217.gif)
