### ISSUE TITLE
cannot import name 'init_pose_model' from 'mmpose.apis

### ISSUE THREAD

**Issue by hailong1991** [open-mmlab/mmpose#1742]
Thanks for your error report and we appreciate it a lot.
If you feel we have helped you, give us a STAR! :satisfied:

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

- What command or script did you run?

```
A placeholder for the command.
```

- What config did you run?

```
A placeholder for the config.
```

- Did you make any modifications on the code or config? Did you understand what you have modified?
- What dataset did you use?

**Environment**

1. Please run `PYTHONPATH=${PWD}:$PYTHONPATH python mmpose/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as

- How you installed PyTorch \[e.g., pip, conda, source\]
- Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**

If applicable, paste the error traceback here.

```
A placeholder for traceback.
```

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by Tau-J** [comment]
Hi there, could you please print `pip list | grep mm` to make sure `mmpose` is installed correctly?

**Comment by PureHing** [comment]
@Tau-J 

`pip list | grep mm`:
```
commonmark             0.9.1
mmcv                   2.0.0rc1
mmdet                  3.0.0rc1
mmengine               0.2.0
mmpose                 1.0.0rc0 
```

```
Traceback (most recent call last):
  File "tools/deployment/pytorch2onnx.py", line 8, in <module>
    from mmpose.apis import init_pose_model
  File "/media/lvm/home/aa/zxc/wybflow/modules/mmpose/mmpose/__init__.py", line 10, in <module>
    mmcv_version = digit_version(mmcv.__version__)
AttributeError: module 'mmcv' has no attribute '__version__'
```
