### ISSUE TITLE
mmpose 1.x pytorch2onnx

### ISSUE THREAD

**Issue by PureHing** [open-mmlab/mmpose#1744]
@Tau-J  Hi,
`pip list | grep mm` :
```
commonmark             0.9.1
mmcv                   2.0.0rc1
mmcv-full              1.6.2
mmdet                  3.0.0rc1
mmengine               0.2.0
mmpose                 1.0.0rc0
```
Run `python tools/deployment/pytorch2onnx.py configs/**  **.pth`
Some errors:

1. `AssertionError: MMCV==1.6.2 is used but incompatible. Please install mmcv>=2.0.0rc0, <=2.1.0.`
     if  `pip uninstall mmcv-full`
 [here](https://github.com/open-mmlab/mmpose/blob/2489991b6f3b6fa17a8f3d135ba6e92986fc461c/mmpose/__init__.py#L10)  raise `AttributeError: module 'mmcv' has no attribute '__version__'`
[here](https://github.com/open-mmlab/mmpose/blob/2489991b6f3b6fa17a8f3d135ba6e92986fc461c/mmpose/datasets/transforms/bottomup_transforms.py#L7) raise `ModuleNotFoundError: No module named 'mmcv.image'`
2. If skip version check，raise `KeyError: "class TopdownPoseEstimator in mmpose/models/pose_estimators/topdown.py: 'PoseDataPreprocessor is not in the model registry. Please check whether the value of PoseDataPreprocessor is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/tutorials/config.html#import-custom-python-modules'"`

**Comment by Tau-J** [comment]
Hi, thanks for trying `mmpose 1.x`. I suggest uninstalling both of `mmcv-full` and `mmcv` first, and use: 
```shell
pip install -U openmim
mim install "mmcv>=2.0.0rc1"
```
to reinstall `mmcv`

**Comment by PureHing** [comment]
@Tau-J 
the same errors:
`KeyError: "class TopdownPoseEstimator in mmpose/models/pose_estimators/topdown.py: 'PoseDataPreprocessor is not in the model registry. Please check whether the value of PoseDataPreprocessor is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/tutorials/config.html#import-custom-python-modules'"`

**Comment by Tau-J** [comment]
Sorry I don't understand what does `there's no problems when training model` mean. As for `tools/deployment`, in `mmpose 1.x`, we recommend users to use `mmdeploy` to conduct deployment.

**Comment by PureHing** [comment]
I have change to V0.29.0.
Thanks!

**Comment by Jwy-jump** [comment]
@ly015 @PureHing I meet the same questions
`Traceback (most recent call last):
  File "demo/topdown_demo_with_mmdet.py", line 293, in <module>
    main()
  File "demo/topdown_demo_with_mmdet.py", line 183, in main
    pose_estimator = init_pose_estimator(
  File "/home/user/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmpose/apis/inference.py", line 101, in init_model
    model = build_pose_estimator(config.model)
  File "/home/user/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmpose/models/builder.py", line 35, in build_pose_estimator
    return POSE_ESTIMATORS.build(cfg)
  File "/home/user/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/user/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 250, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/user/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 144, in build_from_cfg
    raise type(e)(
KeyError: "class `TopdownPoseEstimator` in mmpose/models/pose_estimators/topdown.py: 'mmcls.VisionTransformer is not in the model registry. Please check whether the value of `mmcls.VisionTransformer` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'"`

finally, how to solve it? I use mmdeploy to conduct deployment.
