### ISSUE TITLE
Smoother error in two stage 3D video demo (inconsistent track IDs error)

### ISSUE THREAD

**Issue by julianzille** [open-mmlab/mmpose#1745]
Hi everyone.

I am facing an issue with [two stage 3D video demo](https://github.com/open-mmlab/mmpose/blob/master/demo/body3d_two_stage_video_demo.py), where the smoother is outputting an inconsistent track ID error.
`pose_results_2d = smoother.smooth(pose_results_2d)`
After inspecting `pose_results_2d`, there are some empty arrays [] (probably corresponding to non-detections for that frame), which I think causes the error when the smoother tries to smooth these frames. I am using the default one euro smoother.

Is there any workaround for this, or does the smoother only work where the object is tracked in every frame of the video?

Thanks in advance.

**Comment by ly015** [comment]
Thanks for the feedback. We will look into the smoother and the demo script and try to figure out a better way to handle frames without detected objects. Please let us know if you have any suggestions.

Meanwhile, maybe you can try some simple workarounds like dropping frames without objects or reusing the object information from the last frame.
