### ISSUE TITLE
hand detection & pose estimation on coco-wholebody dataset

### ISSUE THREAD

**Issue by linjing7** [open-mmlab/mmpose#1746]
Hi, I want to train a model that can detect the hand box, crop it, and then use a model to perform pose estimation. Could you please tell me how to do it on coco-wholebody dataset?

**Comment by linjing7** [comment]
Okay, thank you very much. I notice that there is a pretrained hand-detect model provided in demo. Are there any other hand-detect model in addition to `cascade_rcnn_x101_64x4d_fpn_20e_onehand10k-dac19597_20201030.pth`?
<img width="817" alt="image" src="https://user-images.githubusercontent.com/70081899/196595499-3af09e56-ab28-488f-957a-61dd5493983a.png">

**Comment by Ben-Louis** [comment]
There is also a lightweight hand detector [ssdlite_mobilenetv2_scratch_600e_onehand](https://github.com/open-mmlab/mmpose/blob/master/demo/mmdetection_cfg/ssdlite_mobilenetv2_scratch_600e_onehand.py) whose checkpoint is available at https://download.openmmlab.com/mmpose/mmdet_pretrained/ssdlite_mobilenetv2_scratch_600e_onehand-4f9f8686_20220523.pth

**Comment by linjing7** [comment]
Okay, thank you very much.

**Comment by Msameim181** [comment]
Do we need a detection model for training MMPose for hand keypoints? Where should we define that?
