### ISSUE TITLE
FileNotFoundError: class `AP10KDataset` in mmpose/datasets/datasets/animal/ap10k_dataset.py: The metainfo config file "configs/_base_/datasets/ap10k.py" does not exist.

### ISSUE THREAD

**Issue by darkredrock** [open-mmlab/mmpose#1747]
The following error is reported when trying to train the ap-10k dataset:.
FileNotFoundError: class `AP10KDataset` in mmpose/datasets/datasets/animal/ap10k_dataset.py: The metainfo config file "configs/_base_/datasets/ap10k.py" does not exist.

**Comment by liqikai9** [comment]
Hi. Thanks for your feedback. Could you please give more information about the config you used? So that we can check the problem more quickly~ 

BTW, I think this path "configs/base/datasets/ap10k.py" should be "configs/_base_/datasets/ap10k.py"

**Comment by ly015** [comment]
Hi, this issue will be closed for now. Please feel free to reopen it if there are further questions.
