### ISSUE TITLE
Hrnet augumentation detailed！

### ISSUE THREAD

**Issue by 2050airobert** [open-mmlab/mmpose#1748]
Hi,
    请问下
     1 hrnet 训练的时候，采用了哪些数据增广呢？是否有针对不同的物体或者人 检测框box 尺寸和大小随机调整的数据增广呢？ 具体文档链接是？ 
     2  就是说假如前面输入的人检测出来的box 比人要大的多而且尺寸 宽高比也很异常，那么这种情况的数据增广是怎么处理的呢？ 具体代码体现在哪个地方呢？ 具体代码位置是？
  
BR

**Comment by jin-s13** [comment]
1.可以具体看config文件
2.训练的时候，用gt框，不用检测框

**Comment by jin-s13** [comment]
https://github.com/open-mmlab/mmpose/blob/master/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w32_coco_256x192.py#L95

这里可以看到，我们训练中用到的所有aug

**Comment by 2050airobert** [comment]
多谢，那请问下mmpose实现了 yolov5或者v4吗？ 具体的代码和文档分别在哪呢？

**Comment by jin-s13** [comment]
mmpose 没有支持 yolov5，可以去 [mmyolo](https://github.com/open-mmlab/mmyolo) 看一下

**Comment by 2050airobert** [comment]
有木有一些demo，可以同时使用yolov5 检测人，然后mmpose hrnet检测关键点？  或者类似的可参考？

**Comment by jin-s13** [comment]
https://github.com/open-mmlab/mmpose/blob/master/demo/docs/2d_human_pose_demo.md#using-mmdet-for-human-bounding-box-detection

mmdet检测+mmpose关键点

**Comment by nanhui69** [comment]
> https://github.com/open-mmlab/mmpose/blob/master/demo/docs/2d_human_pose_demo.md#using-mmdet-for-human-bounding-box-detection
> 
> mmdet检测+mmpose关键点

现在支持mmyolo 里的yolov5了么
