### ISSUE TITLE
How to save the coco-format json in top_down_img_demo_with_mmdet.py?

### ISSUE THREAD

**Issue by linjing7** [open-mmlab/mmpose#1749]
Hi, thanks for your excellent work! I want to use the wholebody model in mmpose to generate coco-format whole-body keypoint json to replace [openpose](https://github.com/CMU-Perceptual-Computing-Lab/openpose). However, the demo output the images instead of json files. Could you please tell me how to modify it?

**Comment by Ben-Louis** [comment]
Hi, thanks for using MMPose! The demo script `op_down_img_demo_with_mmdet.py` does not support coco-format output now. You may need to save and pack the predictions in coco-format by yourself. An example function is 

```python
def convert_pose_results_to_coco_format(pose_results, out_file, args):
    annotations = []
    
    for result in pose_results:
        keypoints_visible = result['keypoints'][:, 2] > args.kpt_thr
        keypoints = np.concatenate(
            (result['keypoints'][:, :2], 
             keypoints_visible[:, None]), 
            axis=1).astype(float)
        bbox = result['bbox'].astype(float)
        image_name = os.path.join(args.img_root, args.img)

        annotations.append(dict(
            image_name = image_name,
            bbox = bbox[:4].tolist(),
            score = bbox[4],
            keypoints = keypoints.tolist(),
            category_id = args.det_cat_id
        ))

    with open(out_file, 'w') as f:
        json.dump(annotations, f)
```
You could call this function after [the inference function](https://github.com/open-mmlab/mmpose/blob/4a86bdf086f58720897fc44aa016421b76591602/demo/top_down_img_demo_with_mmdet.py#L106) to save necessary information for coco-format annotaions.

**Comment by linjing7** [comment]
Okay, thank you very much.
