### ISSUE TITLE
How to test the performance of HRNet-w48+ on COCO-WholeBody dataset?

### ISSUE THREAD

**Issue by linjing7** [open-mmlab/mmpose#1756]
Hi, thanks for your excellent work! I wonder how to evaluate the performance (e.g., `Body AP`, `Hand AP`, `Foot AP`) of `HRNet-w48+` on `COCO-WholeBody` Dataset?
<img width="912" alt="image" src="https://user-images.githubusercontent.com/70081899/197167041-a39066d6-2488-4894-a6f4-df45628a75fb.png">

**Comment by liqikai9** [comment]
@linjing7  Hi. If you want to test the performance of the trained model, you can refer to [this doc](https://github.com/open-mmlab/mmpose/blob/master/docs/en/get_started.md#test-a-dataset). Then you can select your desired config file name and corresponding checkpoint file according to the guidance.

Specifically, for COCO-WholeBody dataset, the evaluation will be performed on different parts like body, foot, face, hand, etc. respectively.  Only a prt of the keypoints will be evaluated. Finally, the performance of overall keypoints will also be evaluated. The detail can be found [here](https://github.com/open-mmlab/mmpose/blob/master/mmpose/datasets/datasets/top_down/topdown_coco_wholebody_dataset.py#L189).

**Comment by linjing7** [comment]
Okay,  thank you very much.
