### ISSUE TITLE
多视角3d融合，test.py程序，out的参数设置应该是什么？

### ISSUE THREAD

**Issue by graceforlife** [open-mmlab/mmpose#1758]
![248bfe1cab659a862b1becf4da2ea6c](https://user-images.githubusercontent.com/115878494/197325277-907b0875-65bd-4ec1-886e-3d21a307d686.jpg)
![9314a82b8223f657edccaddd38e9973](https://user-images.githubusercontent.com/115878494/197325279-a5e7c879-a25d-49c0-983b-ffcec7fb0050.jpg)
我运行的命令是：
python  tools/test.py configs/body/3d_kpt_mview_rgb_img/voxelpose/campus/voxelpose_prn64x64x64_cpn80x80x20_campus_cam3.py  checkpoints/voxelpose_prn64x64x64_cpn80x80x20_campus_cam3-d8decbf7_20220323.pth --out vis_results
vis_results文件夹存在，但是他给我显示格式错误，请问这里out参数应该怎么改，out后面应该接着什么呢？谢谢

**Comment by liqikai9** [comment]
@graceforlife Hi. ` --out` should be the whole name of the output file, including the **suffix** of the filename, for example you can use like this: 
`--out vis_results.json`

**Comment by graceforlife** [comment]
> @graceforlife Hi. ` --out` should be the whole name of the output file, including the **suffix** of the filename, for example you can use like this: `--out vis_results.json`

ok,i konw ,and i also find that --out is also can with pkl,like 
--out vis_results.pkl
