### ISSUE TITLE
The AP of the given ckpt is inconsistent with that in the log

### ISSUE THREAD

**Issue by StartingPointM** [open-mmlab/mmpose#1759]
For example, the AP recorded in the table of pose_resnet_50 with input size 256x192 [in this link](https://mmpose.readthedocs.io/en/v0.29.0/topics/body%282d%2Ckpt%2Csview%2Cimg%29.html#topdown-heatmap-resnet-on-coco) is 71.8. But in its [log](https://download.openmmlab.com/mmpose/top_down/resnet/res50_coco_256x192_20200709.log.json), the AP has reached 73.7 when the epoch is 192. In addition, this kind of problem also appears in other places such as [hrnet](https://mmpose.readthedocs.io/en/v0.29.0/topics/body%282d%2Ckpt%2Csview%2Cimg%29.html#topdown-heatmap-hrnet-on-coco). That's my confusion, and i sincerely hope to get your reply.

**Comment by liqikai9** [comment]
Hi. You can refer to this [answer](https://github.com/open-mmlab/mmpose/issues/993#issuecomment-953776862) in this [issue](https://github.com/open-mmlab/mmpose/issues/993):

> In the log, the val AP is reported using ground-truth box.

**Comment by StartingPointM** [comment]
Oh, that makes sense. Thanks.
