### ISSUE TITLE
How can I make the program output the fused image results

### ISSUE THREAD

**Issue by graceforlife** [open-mmlab/mmpose#1760]
我使用的程序是tool/test.py,算法是voxelpose，我输入的campus类型的（2000*3个摄像头图片），我想得到程序推理出来的2000张融合的照片，我该怎么做？我应该用tool/test.py来推理吗？

**Comment by liqikai9** [comment]
你好。你可以参考这个 [demo](https://github.com/open-mmlab/mmpose/blob/master/demo/docs/3d_multiview_human_pose_demo.md)，关于相机参数这一块，代码处理的逻辑不一样，可能需要自己修改一下。

tools/test.py 会输出模型的预测结果，可能需要经过一定的后处理才能得到你想要的结果~

**Comment by graceforlife** [comment]
> 
谢谢你了~，但是好难啊啊，不会处理，呜呜呜

**Comment by graceforlife** [comment]
> 你好。你可以参考这个 [demo](https://github.com/open-mmlab/mmpose/blob/master/demo/docs/3d_multiview_human_pose_demo.md)，关于相机参数这一块，代码处理的逻辑不一样，可能需要自己修改一下。
> 
> tools/test.py 会输出模型的预测结果，可能需要经过一定的后处理才能得到你想要的结果~

您好，可以告诉我一下怎么处理test.py的结果吗，没有思路~
