### ISSUE TITLE
Keypoint and bounding box confidence score

### ISSUE THREAD

**Issue by julianzille** [open-mmlab/mmpose#1769]
Hi everyone.

I was hoping someone could briefly describe how confidence scores are calculated from heatmaps in coco keypoint detection? Or perhaps point me to the relevant code or paper that describes it? Thanks in advance.

**Comment by liqikai9** [comment]
@julianzille Hi. The keypoint confidence scores are actually the maximum value of the corresponding heatmaps. 

You may refer to [this code](https://github.com/open-mmlab/mmpose/blob/master/mmpose/core/evaluation/top_down_eval.py#L474) and [tis code](https://github.com/open-mmlab/mmpose/blob/master/mmpose/models/heads/topdown_heatmap_base_head.py#L75) to get more detail.

**Comment by julianzille** [comment]
Thanks @liqikai9. Are the confidence scores given in MMDet for each bounding box the IoU scores? Or are they different? (In the coco context)

**Comment by liqikai9** [comment]
I think they are different. The confidence scores given in MMDet for each bounding box are output by the specific model, they may have different meaning with the IoU scores. You can also raise an issue in [mmdetection](https://github.com/open-mmlab/mmdetection/issues/new/choose) about this question~
