### ISSUE TITLE
how can i get the heatmap with gardcam

### ISSUE THREAD

**Issue by sayoko17** [open-mmlab/mmpose#1779]
how can i get the heatmap with gardcam?
I install the grad-cam(pytorch-grad-cam) and copy some code in the inference.py 【 _inference_single_pose_model 】, but it had errors . such as dimension... so how can i use the gradcam in mmpose.

我要怎么在mmpose里使用gradcam查看呢，我是加在 inference.py 的 _inference_single_pose_model 里，然后还改了一些base_cam的输入，因为之前会报维度的错误，在想是不是没加img_metas，然后加上之后还是进入model的时候会报错，但是我的backbone没有问题，能训练也能验证。
` # forward the model
    with torch.no_grad():
        #添加
        #添加
        rgb_img = cv2.imread(img_or_path, 1)[:, :, ::-1]
        rgb_img = np.float32(rgb_img) / 255
        input_tensor = preprocess_image(rgb_img,
                                        mean=[0.485, 0.456, 0.406],
                                        std=[0.229, 0.224, 0.225])
        print(input_tensor)
        targets = None
        methods = \
            {"gradcam": GradCAM,
             "hirescam": HiResCAM,
             "scorecam": ScoreCAM,
             "gradcam++": GradCAMPlusPlus,
             "ablationcam": AblationCAM,
             "xgradcam": XGradCAM,
             "eigencam": EigenCAM,
             "eigengradcam": EigenGradCAM,
             "layercam": LayerCAM,
             "fullgrad": FullGrad,
             "gradcamelementwise": GradCAMElementWise}
        print(model)
        target_layer=[model.backbone.stem.conv1[1]]
        cam_algorithm = methods['gradcam']
        with cam_algorithm(model=model,
                           target_layers=target_layer,
                           use_cuda=True) as cam:
            # AblationCAM and ScoreCAM have batched implementations.
            # You can override the internal batch size for faster computation.
            cam.batch_size = 32
            print(batch_data['img'])
            grayscale_cam = cam(input_tensor=batch_data['img'],
                                targets=targets,img_metas=batch_data['img_metas'])

            print(grayscale_cam)

            # Here grayscale_cam has only one image in the batch
            grayscale_cam = grayscale_cam[0, :]

            cam_image = show_cam_on_image(rgb_img, grayscale_cam, use_rgb=True)

            # cam_image is RGB encoded whereas "cv2.imwrite" requires BGR encoding.
            cam_image = cv2.cvtColor(cam_image, cv2.COLOR_RGB2BGR)

            cv2.imwrite(f'{methods}_cam.jpg', cam_image)

        ###结束
        ###结束
        result = model(
            img=batch_data['img'],
            img_metas=batch_data['img_metas'],
            return_loss=False,
            return_heatmap=return_heatmap)`
我大概是这样子加的，对应的base_cam里也改了一些，但是失败了，所以感觉可能不是这样子用的，想问问有没有人有写好的py文件分享一下，谢谢thanks

**Comment by Ben-Louis** [comment]
您好，您可以参考[这个脚本](https://github.com/open-mmlab/mmpose/files/9895642/inference.py.txt)修改 `inference.py`。 里面的 `target_layers` 还需要配合您使用的模型进行调整
