### ISSUE TITLE
How to make my own human keypoint detection dataset in coco format

### ISSUE THREAD

**Issue by lpredoomy** [open-mmlab/mmpose#1782]
Do I need to frame the body when labeling data with labelme? How to convert a json file to coco format

**Comment by ly015** [comment]
There are public tools to convert LabelMe data to COCO format, like https://github.com/fcakyon/labelme2coco. You can also write your own script to do the conversion. The description of COCO json format can be found on their [website](https://cocodataset.org/#format-data).
