### ISSUE TITLE
 code for the IIA and GFD modules in the CID architecture

### ISSUE THREAD

**Issue by Ody-trek** [open-mmlab/mmpose#1802]
Maybe I'm not reading carefully, where is the implementation code for the IIA and GFD modules in the CID architecture?

**Comment by Ben-Louis** [comment]
Hi, the IIA and GFD modules are implemented in [cid_head](https://github.com/open-mmlab/mmpose/blob/master/mmpose/models/heads/cid_head.py).

**Comment by Ody-trek** [comment]
> Hi, the IIA and GFD modules are implemented in [cid_head](https://github.com/open-mmlab/mmpose/blob/master/mmpose/models/heads/cid_head.py).

Thanks a lot!
