### ISSUE TITLE
How to get PCK valus after training animalpose dataset (coco-format)

### ISSUE THREAD

**Issue by github2016-yuan** [open-mmlab/mmpose#1805]
I follow [animalpose](https://github.com/open-mmlab/mmpose/blob/master/docs/en/tasks/2d_animal_keypoint.md#animal-pose)
and get epoch_210.pth. Then I use the following cmd to get the mAP value:
`python tools/test.py  configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/animalpose/hrnet_w32_animalpose_256x256.py  work_dirs/hrnet_w32_animalpose_256x256/epoch_210.pth --eval mAP`

It works so I get mAP. Now I want to get PCKh value so I do some changes in  animal_pose_dataset.py 
 Line 212
before: allowed_metrics = ['mAP']
now: **allowed_metrics = ['mAP','PCKh']**

Then I  run  cmd below:
`python tools/test.py  configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/animalpose/hrnet_w32_animalpose_256x256.py  work_dirs/hrnet_w32_animalpose_256x256/epoch_210.pth --eval PCKh`

No error occurs but I still get the mAP result. So I want to know is there anything that I miss?  Is it possible to get PCK value in model trained with coco format dataset and script. I also know that 'PCK' is a evaluation indicator of mpii dataset. Something related to this?

**Comment by liqikai9** [comment]
@github2016-yuan Hi. Currently ,we only supporting mAP for animalpose dataset. Except modifying this line: `allowed_metrics = ['mAP','PCKh']`, you also need to add the evaluation code yourself.  And you can refer to this [code](https://github.com/open-mmlab/mmpose/blob/master/mmpose/datasets/datasets/base/kpt_2d_sview_rgb_img_top_down_dataset.py#L197).  


By the way, [mmpose 1.0](https://github.com/open-mmlab/mmpose/tree/1.x) has released and if you would like to calculate mulitple metrics on a dataset, you can easily add multiple metrics like this [example](https://github.com/open-mmlab/mmpose/blob/1.x/configs/animal_2d_keypoint/topdown_heatmap/locust/td-hm_res101_8xb64-210e_locust-160x160.py#L119-L123). You can try this~

**Comment by github2016-yuan** [comment]
OK, I will try.
