### ISSUE TITLE
No output when performing inference on a custom dataset

### ISSUE THREAD

**Issue by Viet-T07** [open-mmlab/mmpose#1808]
Hi, I am currently using the bottom-up model under configs/body/2d_kpt_sview_rgb_img/associative_embedding/coco/hrnet_w32_coco_512x512.py to perform inference on a dataset with 14 keypoints. 

The dataset is in the same format as the coco dataset. Here is an example of the annotation
` "annotations": [
        {
            "keypoints": [
                63.435739999999996,
                49.720459999999996,
                2,
                40.5833,
                59.1704,
                2,
                51.3436,
                66.0485,
                2,
                58.2302,
                105.136,
                2,
                77.7613,
                119.849,
                2,
                27.877,
                51.3624,
                2,
                37.6656,
                70.9406,
                2,
                52.3866,
                83.6523,
                2,
                18.5,
                113.5,
                2,
                44.5345,
                145.28,
                2,
                62.1126,
                201.031,
                2,
                2.93294,
                109.064,
                2,
                32.7689,
                125.72,
                2,
                16.1651,
                162.877,
                2
            ],
            "num_keypoints": 14,
            "image_id": 0,
            "category_id": 1,
            "id": 18919
        }]`
In order, the keypoints refer to the head, neck, right shoulder, right wrist, left shoulder, left elbow, left wrist, right hip, right knee, right ankle, left hip, left knee, left ankle.

I have modified the original config so that it looks as follows [config.txt](https://github.com/open-mmlab/mmpose/files/10016251/config.txt) and I am using this [checkpoint file](https://download.openmmlab.com/mmpose/bottom_up/hrnet_w32_coco_512x512-bcb8c247_20200816.pth). However, when I run the bottom-up image demo using this configuration, no keypoints appear on the test images. 

Additionally, when using running this configuration with test.py I get the following output:
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
=> num_images: 30
load checkpoint from local path: hrnet_w32_coco_512x512-bcb8c247_20200816.pth
The model and loaded state dict do not match exactly
size mismatch for keypoint_head.final_layer.weight: copying a param with shape torch.Size([34, 32, 1, 1]) from checkpoint, the shape in current model is torch.Size([28, 32, 1, 1]).
size mismatch for keypoint_head.final_layer.bias: copying a param with shape torch.Size([34]) from checkpoint, the shape in current model is torch.Size([28]).
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 30/30, 1.7 task/s, elapsed: 17s, ETA:     0sAP: 0
AP (L): 0
AP (M): 0
AP .5: 0
AP .75: 0
AR: 0
AR (L): 0
AR (M): 0
AR .5: 0
AR .75: 0 

Is there anything I am missing or something I should differently?

**Comment by ly015** [comment]
Hi, thanks for using MMPose. I am afraid you can not change the output joint number of an existing model by simply modifying the config. It will lead to mismatching between the model and the checkpoint file (e.g. the channel number of the last convolutional layer is 14 vs 17) and the model weights won't be successfully loaded.

Maybe you can try using the original model config and checkpoints to predict 17 COCO joints, and add a few post-processing codes to convert it into desired 14 joints. Or if you have some training data, maybe directly training a 14-joint model will achieve better performance.

**Comment by Viet-T07** [comment]
> Hi, thanks for using MMPose. I am afraid you can not change the output joint number of an existing model by simply modifying the config. It will lead to mismatching between the model and the checkpoint file (e.g. the channel number of the last convolutional layer is 14 vs 17) and the model weights won't be successfully loaded.
> 
> Maybe you can try using the original model config and checkpoints to predict 17 COCO joints, and add a few post-processing codes to convert it into desired 14 joints. Or if you have some training data, maybe directly training a 14-joint model will achieve better performance.

I see, thank you for the answer!
