### ISSUE TITLE
HRNET+RLE+SIMDR  not work!

### ISSUE THREAD

**Issue by 2050airobert** [open-mmlab/mmpose#1810]
Hi，
      If I want to do train different  models  with the combination of different technique or module， how could do improve the code or config of  mmpose?
     For example, there are some  trial as following:
    1   deep pose  with DLA + RLE + IPR + DSNT  
    2   deep pose  with resnet  + RLE +  SIMDR 
    3   hrnet with  resnet  + simdr + RLE
    4   hrnet with  resnet  + RLE + IPR + DSNT  
    etc.
     Is there any example to show how to complete these trial above?  Do I need to change some source code of  mmpose?
     Or all I need to do is that to change the config file for training (eg. https://github.com/open-mmlab/mmpose/tree/1.x/configs/body_2d_keypoint/topdown_heatmap/coco)?
     Looking forward to your reply ~
BR

**Comment by Tau-J** [comment]
Hi @2050airobert ，thanks for using MMPose. For IPR/DSNT+RLE, you just need to change the loss function in config, because all targets you need are generated by codec `IntegralRegressionLabel`. But for SimCC(SimDR), we do not provide a soft-argmax operation in SimCC so that you have to implement a new head to conduct such processing. In addition, you can change backbones directly in config.

**Comment by 2050airobert** [comment]
hi @Tau-J 
    1   What do you mean about "codec IntegralRegressionLabel", is it this  some OP in the config file or config python file just like "configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_hrnet-w48_8xb32-210e_coco-256x192.py"?
    2   Is it so hard that to add the oft-argmax operation in SimCC , if not so why not?  So you mean there is HRNET+simcc ，yet not  HRNET+simcc + RLE ,right ?
    3  If I want to change the backbones of the deeppose , simplebaseline  or hrnet ,  all I need to do is change the code in the config python file? 
BR

**Comment by 2050airobert** [comment]
Sound nice kit!
Is there two config file as following?
1 Could you help me to show how to change  the  simcc_vipnas-mbv3_8xb64-210e_coco-256x192.py to support hrnet + simcc/dr , or share the simcc_hrnet-xxx_coco_256x192.py file ?
2  How about  hrnet + RLE + IPR + DSNT ? Could you please  share the  hrnet_rle_ipr_dsnt_coco-256x192.py file ? 
tks

**Comment by Tau-J** [comment]
For new users, we prepare a tutorial, therefore, I suggest referring to [this tutorial](https://mmpose.readthedocs.io/en/1.x/migration.html) to learn how to use MMPose 1.0. If you find any part of the tutorial not easy to understand, please let me know, which will help us to improve.

**Comment by darcula1993** [comment]
seems that we need some code hack to do deeppose+IPR+RLE+DSNT

RLE take 3 parameters as input (pred,sigmas,target) but DSNT head do not provide sigmas for the RLE loss.
