### ISSUE TITLE
Something about use-multi-frames.

### ISSUE THREAD

**Issue by Ared521** [open-mmlab/mmpose#1811]
Hi, thank you for your great work, now, I have a question: 
  I want to predict 3d pose in my own video, and I use body3d_two_stage_video_demo.py.    However, I ran into a very tricky problem.    The posetrack18 dataset website was down and I couldn't find the author's email address.    I want to get to the final pose by multi frames, which is --use_multi_frames.  What should I do now, please?    Can JHMDB dataset be used instead?    Is there any other way?
I'm looking forward to your early reply.Thank you.

**Comment by liqikai9** [comment]
@Ared521 Hi.  To use `body3d_two_stage_video_demo.py`, you can refer to this [doc](https://github.com/open-mmlab/mmpose/blob/master/demo/docs/3d_human_pose_demo.md#3d-human-pose-two-stage-estimation-video-demo). You do not need the original posetrack18 dataset and can just input your own images.
