### ISSUE TITLE
Questions about key point matching

### ISSUE THREAD

**Issue by ChenZhenGui** [open-mmlab/mmpose#1816]
hello，I would like to ask how the order in the heat map generated after passing through the head ，heatmap:(17,64,48) matches the annotation order,such as heatmap[0] match the nose，heatmap[1] match the left eye

**Comment by Ben-Louis** [comment]
Hi, the order of output keypoints and heatmaps depends on the training dataset. You can refer to the corresponding metainfo config files for the order. For example, if you are interested in the output keypoint order of a model trained with coco, you can look into [the keypoint_info in coco metainfo](https://github.com/open-mmlab/mmpose/blob/7fcf2e85e157d36261629c2ebc6ad0ce8de5946a/configs/_base_/datasets/coco.py#L13) .
