### ISSUE TITLE
新版webcam api开发难度较大

### ISSUE THREAD

**Issue by ShaneCan** [open-mmlab/mmpose#1817]
老版本的webcam_demo.py内包含了运行的所有代码，逻辑较为清楚，容易读懂，便于修改。新版api采用nodes的形式，虽然使代码更加简洁，但是嵌套很多，修改起来无从下手，不是很方便。望能否提供一个类似于老版，代码整合到一起的py文件呢？

**Comment by ly015** [comment]
新版 Webcam API 设计的目标是提供给一个模块化的工具，让用户可以开发功能更为丰富和灵活的应用，同时无需关注线程通信等底层部分。相比旧版，新版 API 包含更多模块定义和类型封装，对于习惯直接阅读代码的同学确实不如原来直观，因此我们也提供了 [教程文档](https://mmpose.readthedocs.io/en/latest/tutorials/7_webcam_api.html) 和 [demo](https://github.com/open-mmlab/mmpose/blob/master/demo/docs/webcam_demo.md)，以及[所有接口的索引文档](https://mmpose.readthedocs.io/en/latest/api.html#mmpose-apis-webcam)，希望能有所帮助。

**Comment by ShaneCan** [comment]
> 新版 Webcam API 设计的目标是提供给一个模块化的工具，让用户可以开发功能更为丰富和灵活的应用，同时无需关注线程通信等底层部分。相比旧版，新版 API 包含更多模块定义和类型封装，对于习惯直接阅读代码的同学确实不如原来直观，因此我们也提供了 [教程文档](https://mmpose.readthedocs.io/en/latest/tutorials/7_webcam_api.html) 和 [demo](https://github.com/open-mmlab/mmpose/blob/master/demo/docs/webcam_demo.md)，以及[所有接口的索引文档](https://mmpose.readthedocs.io/en/latest/api.html#mmpose-apis-webc
