### ISSUE TITLE
TypeError: Unsupported format: data\pigBehavior\vis_results

### ISSUE THREAD

**Issue by hsp2454** [open-mmlab/mmpose#1818]
I'm running "python tools\test.py configs\pig\pig_behavior.py work_dirs\pig_behavior\best_PCK_epoch_80.pth --out data\pigBehavior\vis_results "When testing, he reported this error
![image](https://user-images.githubusercontent.com/115400289/202695276-4e42ccee-3deb-4754-b3f2-1849c6e7140d.png)

**Comment by Ben-Louis** [comment]
Hi, thanks for using MMPose. If you want to save model outputs during testing, the file path you specify using argument `--out` should have postfix `.json`, `yml`, or `pkl`.

**Comment by hsp2454** [comment]
I want to generate the image skeleton in the test set, isn't it "--out save path", every time I want to save the test results error
![image](https://user-images.githubusercontent.com/115400289/202824525-0b708165-29a3-4b6e-989b-e88e04b8b339.png)

**Comment by Ben-Louis** [comment]
You could try the command `python tools\test.py configs\pig\pig_behavior.py work_dirs\pig_behavior\best_PCK_epoch_80.pth --out data\pigBehavior\results.json` and check if the output file `data\pigBehavior\results.json` contains predicted keypoints.
