### ISSUE TITLE
Training warning make me worry!

### ISSUE THREAD

**Issue by 2050airobert** [open-mmlab/mmpose#1819]
Hi,

11/18 16:27:18 - mmengine - WARNING - Failed to search registry with scope "mmpose" in the "parameter scheduler" registry tree. As a workaround, the current "parameter scheduler" registry in "mmengine" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpose" is a correct scope, or whether the registry is initialized.

BR

**Comment by Ben-Louis** [comment]
> This warning is probably because that MMPose uses the default data samplers and optimizer wrapper constructors provided by MMEngine for now, and doesn't define these registries under the scope `mmpose`. You can safely ignore these warnings. We will optimize the warning trigger condition.

Please refer to https://github.com/open-mmlab/mmpose/issues/1699.

**Comment by ly015** [comment]
We will close this issue for now and please feel free to re-open it if there are further questions.

**Comment by ly015** [comment]
Update: the warning turned out to be triggered by some missing registries in MMPose (the default registry in MMEngine will be used instead with the warning raised). It has been fixed in #1849
