### ISSUE TITLE
Weakly and semi supervised cross domain adaptation

### ISSUE THREAD

**Issue by LjIA26** [open-mmlab/mmpose#1820]
Hello! 

Thanks for your work! 
I saw in your paper titled Cross domain adaptation for animal pose estimation, you use weakly supervised learning but in the implementation for animal pose, you are only using the MSE loss? Is this correct? or I am missing something? Do you have a config file for semi supervised learning I am missing? 

Thank you

**Comment by ly015** [comment]
Hi, for the paper you mentioned, we only support the AnimalPose dataset and basic settings using MSE loss. WS-CDA and PPLO are not supported yet.

**Comment by LjIA26** [comment]
Oh that's a shame, Thank you for your answer anyways!
