### ISSUE TITLE
RLELoss bar_mu is different from the paper

### ISSUE THREAD

**Issue by superaha** [open-mmlab/mmpose#1825]
Hi there, 

The bar_mu, which I assume is the "error" variable here:
https://github.com/open-mmlab/mmpose/blob/3fbd7b69b93e5f23fd59ccffc3c13a86da331197/mmpose/models/losses/regression_loss.py#L64

is different from the paper ( below Eq. (5) and the pseudocode in Algorithm 1 [Arxiv Paper](https://arxiv.org/pdf/2107.11291.pdf ).

It is defined as
``
bar_mu = (gt_mu - pred_mu) / hat_sigma
``

When we assume the distribution of bar_mu is symmetric around bar_mu = 0, then it is totally okay. 
Not sure if this causes any performance difference. Or is there anything I missed?

Thanks.

**Comment by ly015** [comment]
Hi, thanks for using MMPose.
Here we follow the official implementation: https://github.com/Jeff-sjtu/res-loglikelihood-regression/blob/master/rlepose/models/regression_nf.py#L134-L136.

And some of the details in MMPose are slightly different from the official RLE code, which has been discussed with the authors and should not affect the results (more information can be found in discussions in #1259 )
