### ISSUE TITLE
Warnings-`Visualizer` backend and "mmdet" is not "mmpose" !

### ISSUE THREAD

**Issue by 2050airobert** [open-mmlab/mmpose#1826]
Hi, 
Question  1: 
more quesetion added ,if I want to my training running on the gpu 2 not 1, how should I do  with the following training cmd? 

Question 2: 
Following the 1.x version of mmpose  " https://github.com/open-mmlab/mmpose/blob/1.x/demo/docs/2d_human_pose_demo.md"
 ， using the cmd below 
“”python3 demo/topdown_demo_with_mmdet.py \
    demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py \
https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \
    configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_hrnet-w32_8xb64-210e_coco-256x192.py \
    https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_coco_256x192-c78dce93_20200708.pth \
    --input /mnt/DataDisk/lvchenglin/datasets/sit_up/already_ok/50fc09bfa76d4c3681e188cc5d57967a.mp4 \
    --output-root=vis_results1121-test/demo --show --draw-heatmap   ”
There will be some warnings as following， 
/usr/local/lib/python3.8/dist-packages/mmengine/visualization/visualizer.py:170: UserWarning: `Visualizer` backend is not initialized because save_dir is None.
  warnings.warn('`Visualizer` backend is not initialized '
[                                                  ] 0/1808, elapsed: 0s, ETA:
/usr/local/lib/python3.8/dist-packages/mmdet/utils/setup_env.py:83: UserWarning: The current default scope "mmpose" is not "mmdet", `register_all_modules` will force the currentdefault scope to be "mmdet". If this is not expected, please set `init_default_scope=False`.
  warnings.warn('The current default scope '
/app_lcl/paddle_test/mmpose/mmpose/utils/setup_env.py:79: UserWarning: The current default scope "mmdet" is not "mmpose", `register_all_modules` will force the currentdefault scope to be "mmpose". If this is not expected, please set `init_default_scope=False`.
  warnings.warn('The current default scope '
/usr/local/lib/python3.8/dist-packages/mmengine/visualization/utils.py:196: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.

    Could you please check what is wrong with my result？
mmcv                          2.0.0rc1
mmdet                         2.25.1
mmengine                      0.3.0
mmpose                        1.0.0rc0              
more-itertools                4.2.0

BR

**Comment by ly015** [comment]
Hi, thanks for the questions and feedback.

1. We suggest adding `CUDA_VISIBLE_DEVICES=2` at the beginning of the command line to specify the GPU index.
2. It seems that these are some harmless warnings and you can safely ignore them as long as the result looks reasonable. We will optimize the scope checking to avoid unnecessary warning information.

**Comment by 2050airobert** [comment]
1 In fact， “setting CUDA_VISIBLE_DEVICES=2” doesn't work at all. I don't know why?
2 Looking forward your optimization version~

**Comment by ly015** [comment]
Hi, the warning has been fixed in the latest dev-1.x code. Is there any progress on the GPU selection issue?
