### ISSUE TITLE
td-hm_hrnet-w32_coco doubt?

### ISSUE THREAD

**Issue by chen-del** [open-mmlab/mmpose#1829]
Hello! I found that dev1.0 has changed a lot, but I have doubts about the pose output, what does its output mean, and its post-processing code is encapsulated. Where is the post-processing code for the actual reasoning? Please answer your doubts, thank you!
![image](https://user-images.githubusercontent.com/58769772/203249834-892d2f78-7654-4bc4-ba53-b26898ad2a18.png)

**Comment by Tau-J** [comment]
Hi @chen-del , thanks for using MMPose 1.0 ! According to your screenshot, the output feature in shape [1, 17, 86, 72], which corresponds to 17 keypoint heatmaps, each with a size of 96x72. In MMPose 1.0, the post-processing operations are defined in the codec, which is a new module to encode/decode the targets. You can refer to [this tutoral](https://mmpose.readthedocs.io/en/1.x/user_guides/codecs.html) for details.

**Comment by chen-del** [comment]
Ok, thank you, but I saw that bbox is actually used in it, but I don’t know where to call it. If you want to use it, does poseonnx still need a pedestrian detection model to use bbox to return the coordinates of people?

**Comment by Tau-J** [comment]
@chen-del  Sorry for late reply. Yes, for top-down algorithms, a pedestrain detector is needed.
