### ISSUE TITLE
run camera_demo on MCU

### ISSUE THREAD

**Issue by ChenZhenGui** [open-mmlab/mmpose#1830]
I am running the demo on a Jetson Nano and I was wondering if there is any way to speed it up and increase the frame count

**Comment by ly015** [comment]
Simple tricks include using lightweight models for detection and pose estimation and removing unnecessary nodes (e.g. unimportant models, visualization, and diagnosis).

To further speed up the inference, you may need to extend it to support model inference with TensorRT or other inference backends. Deployment of MMPose with TensorRT has been supported in MMDeploy (see the documentation for [MMPose 0.x & MMDeploy 0.x](https://mmdeploy.readthedocs.io/en/latest/04-supported-codebases/mmpose.html) and [MMPose 1.0 & MMDeploy 1.0](https://mmdeploy.readthedocs.io/en/dev-1.x/04-supported-codebases/mmpose.html)).
