### ISSUE TITLE
ImportError: cannot import name 'init_pose_model' from 'mmpose.apis'

### ISSUE THREAD

**Issue by Billccx** [open-mmlab/mmpose#1832]
Hello!

I use the code of mmpose 1.x

when I try to run `tools/deployment/pytorch2onnx.py`, it failed with the error
```
ImportError: cannot import name 'init_pose_model' from 'mmpose.apis' (/home/ccx/code/python/mmpose-1.x/mmpose/apis/__init__.py)
```

However, I did not found anything about `init_pose_model` in the code of mmpose 1.x, while `init_pose_model` exists in other version's code:  [`/mmpose/apis/inference.py` ](https://github.com/open-mmlab/mmpose/blob/master/mmpose/apis/inference.py).

Could your please tell me how to deal with this problem?
Thanks!

**Comment by ly015** [comment]
Could you please verify the installation of MMPose by running `pip show mmpose`?

Meanwhile, `pytorch2onnx.py` is deprecated, and please use MMDeploy for model export and deployment. Details can be found in the docs: https://mmdeploy.readthedocs.io/en/dev-1.x/04-supported-codebases/mmpose.html

**Comment by Billccx** [comment]
Thank you for such a quick reply! I have just found this issue and try to use MMDeploy, thanks a lot.

**Comment by Billccx** [comment]
Besides that, I have another question. I wonder if it is proper fro me to express my question in Chinese?

**Comment by Billccx** [comment]
感谢您的回答，新的issue已经提到[#1833](https://github.com/open-mmlab/mmpose/issues/1833)中了，希望能够得到贵团队的帮助和建议，谢谢！
