### ISSUE TITLE
A question about using model to inference in other projects.

### ISSUE THREAD

**Issue by Billccx** [open-mmlab/mmpose#1833]
Hello!
I have a question about mode inferencing. I want to use the model pretrained by mmpose in other projects. I wonder if it is possible for me to directly load the .pth file in pytorch. I am not very familiar with this part and I am desperate for some advice.

您好，我想在mmpose中训练模型，然后将该模型从mmpose的整体框架中剥离出来，放到我其他的项目中进行推理使用。我看到mmpose可以保存pytorch的.pth文件，但是如果想要在其他项目中使用，是否还需要给出模型的定义文件？从mmpose中将模型定义抽离出来是不是比较困难？此外我还看到mmpose支持导出onnx，我是否可以通过在其他项目中加载onnx文件来实现模型的推理呢？

对于上述问题，怎样做会比较好呢? 希望能够得到您的一些建议,感谢！

**Comment by ly015** [comment]
You can use MMPose as a 3rd-party dependency of your projects and directly use MMPose's inference API. Or you can export MMPose models to onnx and use onnx-runtime for inference (MMDeploy's doc gives an example [here](https://mmdeploy.readthedocs.io/en/dev-1.x/04-supported-codebases/mmpose.html)). You can further deploy the model to use inference backends like OpenVINO, TensorRT, et al, which are also supported in MMDeploy. Please check their documents for details.
