### ISSUE TITLE
mmpoe with mmdeploy

### ISSUE THREAD

**Issue by ChenZhenGui** [open-mmlab/mmpose#1837]
Hello ,I would like to ask how to use mmdeploy to transfomer my own backbone(mobilevit) to do inference,and what is the difference from onnxruntime、tensorrt、pplnn、ncnn

**Comment by ChenZhenGui** [comment]
by the way , my hardware is Jetson Nano

**Comment by ly015** [comment]
Hi, we will transfer this issue to MMDeploy to seek more professional answers.

**Comment by ly015** [comment]
Hi, would you like to raise an issue in MMDeploy to seek more professional suggestions?
