### ISSUE TITLE
several questions

### ISSUE THREAD

**Issue by SylvainArd** [open-mmlab/mmpose#1840]
Hello I have several questions : 
1 : what is the latest version 0 or 1 ? and is the version 2 which will arrive in January improve a lot the program ?
2 : in COCO format a point class (ex : left_eye) have one and exactly one point per object and per class, how to have multiple points per object and per class please ? have you a code to advise to me ?
3 : what are the values to put in sigmas in the file configs/_base_/datasets/coco.py please for a custom dataset ?
4 : have you a description of the differents config files and their differences please ?
5 : how to change the default model (resnet50, resnet101, etc) of a config file ?
6 : what means " type='upper'" in configs/_base_/datasets/coco.py please
7 : have I to add lines to these lines of \configs\body\2d_kpt_sview_rgb_img\cid\coco\hrnet_w48_coco_512x512.py file if I put image_size to 1024 :
extra=dict(
            stage1=dict(
                num_modules=1,
                num_branches=1,
                block='BOTTLENECK',
                num_blocks=(4, ),
                num_channels=(64, )),
            stage2=dict(
                num_modules=1,
                num_branches=2,
                block='BASIC',
                num_blocks=(4, 4),
                num_channels=(48, 96)),
            stage3=dict(
                num_modules=4,
                num_branches=3,
                block='BASIC',
                num_blocks=(4, 4, 4),
                num_channels=(48, 96, 192)),
            stage4=dict(
                num_modules=3,
                num_branches=4,
                block='BASIC',
                num_blocks=(4, 4, 4, 4),
                num_channels=(48, 96, 192, 384),
                multiscale_output=True)),
and what please ?
thank you very much
best regards

**Comment by ly015** [comment]
1. MMPose v0.x (latest version is v0.29.0) and v1.x (latest version is v1.0.0rc1) are maintained in parallel now and the next year. New features will be supported in v1.x first.
2. In a dataset, each sample (object) should have a consistent number of keypoints, and the keypoint should be well-defined. Objects with arbitrary numbers of keypoints or multiple keypoints with an identical definition are unsupported in MMPose.
3. COCO website describes how to obtain sigmas from annotations. A custom dataset of human body keypoint can also use sigmas from COCO.

4-7: MMPose documentation provides tutorials for [config](https://mmpose.readthedocs.io/en/latest/tutorials/0_config.html) and [custom dataset](https://mmpose.readthedocs.io/en/latest/tutorials/2_new_dataset.html), which should be able to cover these questions. And more detailed configurations of specific modules can be found in the [API reference](https://mmpose.readthedocs.io/en/latest/api.html). It's highly recommended to browse the documentation first before jumping into coding or experimenting, especially for users new to the OpenMMLab framework.

**Comment by SylvainArd** [comment]
sigmas are not presents if I do Ctrl+F in the page
https://cocodataset.org/#keypoints-eval
I don't find the answers of the orther questions or for example for the
question 7 what I must put is not clear for me

Sylvain Ard
0549507724
0778380991
***@***.***
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers

**Comment by SylvainArd** [comment]
if I understand in the mmpose documentation sigmas are standard deviation
of keypoints so if I want the keypoints detected to be at one pixel in mean
of the ground truth pixel I must put 1/1024=0.001 ?
Sylvain Ard
0549507724
0778380991
***@***.***
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers

**Comment by ly015** [comment]
Please refer to sections 1.2 and 1.3 of https://cocodataset.org/#keypoints-eval about the description of $\sigma$. Actually, I would suggest leaving the sigmas along and using other metrics.

To change the input image size, `image_size` and `heatmap_size` is what you need to modify in the config.

There is no mmpose 2. MMPose 0.x (latest is 0.29.0) can be found at the master branch, and its documentation can be found at https://cocodataset.org/#keypoints-eval. MMPose 1.0 can be found at the 1.x branch, and its documentation can be found at https://mmpose.readthedocs.io/en/1.x/. MMPose 1.0 introduced major refactoring and breaking changes.

**Comment by SylvainArd** [comment]
If I read  https://cocodataset.org/#keypoints-eval    I see :  σi2=E[di2/s2]
where di is the distance between the ground truth points and the predicted
points and s is the square root of the object area and E is the esperance,
as my objects are on average 80 pixels wide, and I want one pixel error
maximum, sigma = 1/80=0.01
Am I right ?
Sylvain Ard
0549507724
0778380991
***@***.***
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers

**Comment by SylvainArd** [comment]
up please
Sylvain Ard
0549507724
0778380991
***@***.***
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers

**Comment by ShaneCan** [comment]
ok

**Comment by SylvainArd** [comment]
So I’m right ?

Envoyé de mon iPhone

**Comment by ly015** [comment]
Sigmas indicate the diversity among multiple annotations (from different subjects) of the same keypoint. So you need to collect multiple annotations for each object in your dataset to calculate sigmas.

**Comment by SylvainArd** [comment]
ok thank you and for my another question of prediction performance please ?
Sylvain Ard
0549507724
0778380991
***@***.***
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers
