### ISSUE TITLE
prediction and see the results

### ISSUE THREAD

**Issue by SylvainArd** [open-mmlab/mmpose#1841]
Hi I see in the documentation that we can do prediction on the complete dataset and generate a JSON of predictions or see the ground truth keypoints of the dataset but I see nowhere how to do the prediction on a new image and to see the predictions on the image predicted. The JSON file format generated by prediction is incompatible with those of the visualization.
Furthermore I launched my training and after 140 epochs I have a loss of 2.0 and my keypoints are far of where it would be, the max score I have is 0.35.
How to improve it please ?

**Comment by ly015** [comment]
You can refer to the demo on how to visualize predictions on the image: https://github.com/open-mmlab/mmpose/tree/master/demo/docs. I am afraid that the JSON file can not be directly used for visualization.

About the model performance issue, could you please share the full config and the training log?

**Comment by SylvainArd** [comment]
I am not at home now so I will send it to you this evening in french hour

Envoyé de mon iPhone

**Comment by SylvainArd** [comment]
Hello,
here is the entire folder of mmpose with all dataset and config files.
I launched :
python tools/train.py
"C:\mmpose-master\configs\body\2d_kpt_sview_rgb_img\cid\coco\hrnet_w48_coco_512x512.py"
--work-dir "output"
thank you very much for your help !
Best regards

Sylvain Ard
0549507724
0778380991
***@***.***
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers

**Comment by SylvainArd** [comment]
up please

Sylvain Ard
0549507724
0778380991
***@***.***
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers

**Comment by SylvainArd** [comment]
Have I just to do more iterations .?
Sylvain Ard
0549507724
0778380991
***@***.***
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers

**Comment by ly015** [comment]
Hi, I have taken a look at the config and I have a few questions:

1. The training and testing dataset uses the same annotation file. Is it intended to use the same data for both training and testing?
2. The training batch size is set as 1 (assume 1 GPU is used) which may be too small.
3. There are lots of log files in the `output` folder and I am not sure which one to check.

**Comment by ly015** [comment]
BTW, I would suggest starting from a simpler model like a top-down heatmap model instead of CID. The former should be easier to tune on your own data. Maybe [HRNet](https://github.com/open-mmlab/mmpose/blob/master/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_coco.md) is what you may be interested in. Of course, you would need to train a detection model to extract object bbox for a top-down keypoint model.

**Comment by SylvainArd** [comment]
the logs are very similar
there are two warnings but I don't understand these :

2022-11-25 14:48:28,267 - mmpose - WARNING - The model and loaded
state dict do not match exactly

unexpected key in source state_dict: head.0.0.0.conv1.weight,
head.0.0.0.bn1.weight, head.0.0.0.bn1.bias,
head.0.0.0.bn1.running_mean, head.0.0.0.bn1.running_var,
head.0.0.0.conv2.weight, head.0.0.0.bn2.weight, head.0.0.0.bn2.bias,
head.0.0.0.bn2.running_mean, head.0.0.0.bn2.running_var,
head.0.0.0.conv3.weight, head.0.0.0.bn3.weight, head.0.0.0.bn3.bias,
head.0.0.0.bn3.running_mean, head.0.0.0.bn3.running_var,
head.0.0.0.downsample.0.weight, head.0.0.0.downsample.1.weight,
head.0.0.0.downsample.1.bias, head.0.0.0.downsample.1.running_mean,
head.0.0.0.downsample.1.running_var, head.0.1.0.conv1.weight,
head.0.1.0.bn1.weight, head.0.1.0.bn1.bias,
head.0.1.0.bn1.running_mean, head.0.1.0.bn1.running_var,
head.0.1.0.conv2.weight, head.0.1.0.bn2.weight, head.0.1.0.bn2.bias,
head.0.1.0.bn2.running_mean, head.0.1.0.bn2.running_var,
head.0.1.0.conv3.weight, head.0.1.0.bn3.weight, head.0.1.0.bn3.bias,
head.0.1.0.bn3.running_mean, head.0.1.0.bn3.running_var,
head.0.1.0.downsample.0.weight, head.0.1.0.downsample.1.weight,
head.0.1.0.downsample.1.bias, head.0.1.0.downsample.1.running_mean,
head.0.1.0.downsample.1.running_var, head.0.2.0.conv1.weight,
head.0.2.0.bn1.weight, head.0.2.0.bn1.bias,
head.0.2.0.bn1.running_mean, head.0.2.0.bn1.running_var,
head.0.2.0.conv2.weight, head.0.2.0.bn2.weight, head.0.2.0.bn2.bias,
head.0.2.0.bn2.running_mean, head.0.2.0.bn2.running_var,
head.0.2.0.conv3.weight, head.0.2.0.bn3.weight, head.0.2.0.bn3.bias,
head.0.2.0.bn3.running_mean, head.0.2.0.bn3.running_var,
head.0.2.0.downsample.0.weight, head.0.2.0.downsample.1.weight,
head.0.2.0.downsample.1.bias, head.0.2.0.downsample.1.running_mean,
head.0.2.0.downsample.1.running_var, head.1.0.0.conv1.weight,
head.1.0.0.bn1.weight, head.1.0.0.bn1.bias,
head.1.0.0.bn1.running_mean, head.1.0.0.bn1.running_var,
head.1.0.0.conv2.weight, head.1.0.0.bn2.weight, head.1.0.0.bn2.bias,
head.1.0.0.bn2.running_mean, head.1.0.0.bn2.running_var,
head.1.0.0.conv3.weight, head.1.0.0.bn3.weight, head.1.0.0.bn3.bias,
head.1.0.0.bn3.running_mean, head.1.0.0.bn3.running_var,
head.1.0.0.downsample.0.weight, head.1.0.0.downsample.1.weight,
head.1.0.0.downsample.1.bias, head.1.0.0.downsample.1.running_mean,
head.1.0.0.downsample.1.running_var, head.1.1.0.conv1.weight,
head.1.1.0.bn1.weight, head.1.1.0.bn1.bias,
head.1.1.0.bn1.running_mean, head.1.1.0.bn1.running_var,
head.1.1.0.conv2.weight, head.1.1.0.bn2.weight, head.1.1.0.bn2.bias,
head.1.1.0.bn2.running_mean, head.1.1.0.bn2.running_var,
head.1.1.0.conv3.weight, head.1.1.0.bn3.weight, head.1.1.0.bn3.bias,
head.1.1.0.bn3.running_mean, head.1.1.0.bn3.running_var,
head.1.1.0.downsample.0.weight, head.1.1.0.downsample.1.weight,
head.1.1.0.downsample.1.bias, head.1.1.0.downsample.1.running_mean,
head.1.1.0.downsample.1.running_var, head.2.0.0.conv1.weight,
head.2.0.0.bn1.weight, head.2.0.0.bn1.bias,
head.2.0.0.bn1.running_mean, head.2.0.0.bn1.running_var,
head.2.0.0.conv2.weight, head.2.0.0.bn2.weight, head.2.0.0.bn2.bias,
head.2.0.0.bn2.running_mean, head.2.0.0.bn2.running_var,
head.2.0.0.conv3.weight, head.2.0.0.bn3.weight, head.2.0.0.bn3.bias,
head.2.0.0.bn3.running_mean, head.2.0.0.bn3.running_var,
head.2.0.0.downsample.0.weight, head.2.0.0.downsample.1.weight,
head.2.0.0.downsample.1.bias, head.2.0.0.downsample.1.running_mean,
head.2.0.0.downsample.1.running_var, head.3.0.0.conv1.weight,
head.3.0.0.bn1.weight, head.3.0.0.bn1.bias,
head.3.0.0.bn1.running_mean, head.3.0.0.bn1.running_var,
head.3.0.0.conv2.weight, head.3.0.0.bn2.weight, head.3.0.0.bn2.bias,
head.3.0.0.bn2.running_mean, head.3.0.0.bn2.running_var,
head.3.0.0.conv3.weight, head.3.0.0.bn3.weight, head.3.0.0.bn3.bias,
head.3.0.0.bn3.running_mean, head.3.0.0.bn3.running_var,
head.3.0.0.downsample.0.weight, head.3.0.0.downsample.1.weight,
head.3.0.0.downsample.1.bias, head.3.0.0.downsample.1.running_mean,
head.3.0.0.downsample.1.running_var, fc.weight, fc.bias


The maximum bach size I can do with  1024 image size is 3
Sylvain Ard
054950772 4
0778380991
***@***.***
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers

**Comment by SylvainArd** [comment]
I don't think the model you suggest me is simpler than cid, the parameters
are the same
Sylvain Ard
0549507724
0778380991
***@***.***
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers

**Comment by SylvainArd** [comment]
when I do batch_size=3 the training does not advance
Sylvain Ard
0549507724
0778380991
***@***.***
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers

**Comment by SylvainArd** [comment]
1. The training and testing dataset uses the same annotation file. Is it
   intended to use the same data for both training and testing? >> yes
   2. The training batch size is set as 1 (assume 1 GPU is used) which may
   be too small. >> I tried 3 but I don't see the progression, and I don't
   know if it advance or not
   3. There are lots of log files in the output folder and I am not sure
   which one to check.

Sylvain Ard
0549507724
0778380991
***@***.***
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers

**Comment by SylvainArd** [comment]
I think the only part where we can do something is :

backbone=dict(
        type='HRNet',
        in_channels=3,
        extra=dict(
            stage1=dict(
                num_modules=1,
                num_branches=1,
                block='BOTTLENECK',
                num_blocks=(4, ),
                num_channels=(64, )),
            stage2=dict(
                num_modules=1,
                num_branches=2,
                block='BASIC',
                num_blocks=(4, 4),
                num_channels=(48, 96)),
            stage3=dict(
                num_modules=4,
                num_branches=3,
                block='BASIC',
                num_blocks=(4, 4, 4),
                num_channels=(48, 96, 192)),
            stage4=dict(
                num_modules=3,
                num_branches=4,
                block='BASIC',
                num_blocks=(4, 4, 4, 4),
                num_channels=(48, 96, 192, 384),
                multiscale_output=True)),
    ),

but I don't know what, an idea please ?
Sylvain Ard
0549507724
0778380991
***@***.***
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers

**Comment by SylvainArd** [comment]
and if we change the learning rate ?
Sylvain Ard
0549507724
0778380991
***@***.***
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers

**Comment by SylvainArd** [comment]
after 140 epochs with batch size =25 the results are :

2022-12-01 13:13:55,455 - mmpose - INFO - Epoch [140][50/51]    lr:
1.000e-05, eta: 0:00:00, time: 0.801, data_time: 0.208, memory: 13346,
multi_heatmap_loss: 0.4749, single_heatmap_loss: 1.9669, contrastive_loss:
0.0246, loss: 2.4665
2022-12-01 13:13:56,065 - mmpose - INFO - Saving checkpoint at 140 epochs
[                                                  ] 0/101, elapsed: 0s,
ETA:C:\Users\MASTER\.conda\envs\openmmlab\lib\site-packages\mmcv\__init__.py:20:
UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will
remove components related to the training process and add a data
transformation module. In addition, it will rename the package names mmcv
to mmcv-lite and mmcv-full to mmcv. See
https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for
more details.
  warnings.warn(
C:\Users\MASTER\.conda\envs\openmmlab\lib\site-packages\mmcv\__init__.py:20:
UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will
remove components related to the training process and add a data
transformation module. In addition, it will rename the package names mmcv
to mmcv-lite and mmcv-full to mmcv. See
https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for
more details.
  warnings.warn(
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 101/101, 2.9 task/s,
elapsed: 35s, ETA:     0sLoading and preparing results...
DONE (t=0.01s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *keypoints*
DONE (t=0.49s).
Accumulating evaluation results...
DONE (t=0.01s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] =
 0.357
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets= 20 ] =
 0.734
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets= 20 ] =
 0.315
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] =
 0.002
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] =
 0.373
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] =
 0.470
 Average Recall     (AR) @[ IoU=0.50      | area=   all | maxDets= 20 ] =
 0.792
 Average Recall     (AR) @[ IoU=0.75      | area=   all | maxDets= 20 ] =
 0.478
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] =
 0.100
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] =
 0.472
2022-12-01 13:14:35,225 - mmpose - INFO - The previous best checkpoint
C:\mmpose-master\output\best_AP_epoch_120.pth was removed
2022-12-01 13:14:37,579 - mmpose - INFO - Now best checkpoint is saved as
best_AP_epoch_140.pth.
2022-12-01 13:14:37,580 - mmpose - INFO - Best AP is 0.3571 at 140 epoch.
2022-12-01 13:14:37,582 - mmpose - INFO - Epoch(val) [140][101] AP: 0.3571,
AP .5: 0.7335, AP .75: 0.3148, AP (M): 0.0024, AP (L): 0.3734, AR: 0.4702,
AR .5: 0.7923, AR .75: 0.4777, AR (M): 0.1000, AR (L): 0.4725

I launch it on 450 epochs much
Sylvain Ard
0549507724
0778380991
***@***.***
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers

**Comment by SylvainArd** [comment]
batch size=2 perdon
Sylvain Ard
0549507724
0778380991
***@***.***
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers

**Comment by ly015** [comment]
The CID model we provided on the COCO dataset uses a total batch size of 160 (8 GPU) for training. Training with a very small batch size could be unstable or even non-convergent. Maybe consider reducing the image size or the feature channels to have a larger batch size with limited GPU memory.

The top-down heatmap is a straightforward and widely used keypoint detection method, which is usually easy to train and can achieve promising performance in most cases, based on our experience. By 'simpler' I mean the algorithm itself, not how the config or the parameters look like. It's still recommended to try a top-down heatmap model as a starter.

I am afraid the above is all suggestions I can give now.

**Comment by SylvainArd** [comment]
Ok have you an example of top down algorithm config file to give me please ?

Envoyé de mon iPhone

**Comment by ly015** [comment]
The [link](https://github.com/open-mmlab/mmpose/blob/master/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_coco.md) to a summary page of top-down heatmap models with HRNet has been given above.

And with all respect, I would have to suggest that it's better not to include too much irrelevant content (e.g. email signatures and history messages) in an issue discussion, which can be a distractor for readers and potential helpers from the community.

**Comment by SylvainArd** [comment]
OK thank you but I see :
image_size=[288, 384],
the image size is fix
if I put [1024,1024] my images which have not the same heights and widths
will be deformed isn't it ?

best regards

**Comment by SylvainArd** [comment]
huh if I put  image_size=[288, 384], sorry because 1024 is too high because
of samples_per_gpu
Sylvain Ard
0549507724
0778380991
***@***.***
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers

**Comment by SylvainArd** [comment]
sorry but I have the error :
Traceback (most recent call last):
  File
"C:\Users\MASTER\.conda\envs\openmmlab\lib\site-packages\mmcv\utils\registry.py",
line 69, in build_from_cfg
    return obj_cls(**args)
  File
"c:\mmpose-master\mmpose\datasets\datasets\top_down\topdown_coco_dataset.py",
line 75, in __init__
    super().__init__(
  File
"c:\mmpose-master\mmpose\datasets\datasets\base\kpt_2d_sview_rgb_img_top_down_dataset.py",
line 74, in __init__
    assert self.ann_info['num_joints'] == dataset_info.keypoint_num
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 201, in <module>
    main()
  File "tools/train.py", line 176, in main
    datasets = [build_dataset(cfg.data.train)]
  File "c:\mmpose-master\mmpose\datasets\builder.py", line 87, in
build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File
"C:\Users\MASTER\.conda\envs\openmmlab\lib\site-packages\mmcv\utils\registry.py",
line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
AssertionError: TopDownCocoDataset:
my config file :
https://www.dropbox.com/s/b2u89p5onx7f6it/hrnet_w32_coco_384x288.py?dl=0


my config file :
I launched :
python tools/train.py
configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w48_coco_384x288.py
--work-dir "output"
Sylvain Ard
0549507724
0778380991
***@***.***
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers

**Comment by SylvainArd** [comment]
The problem was I changed a bad config file
I had a problem with
bbox_file='data/coco/person_detection_results/'
    'COCO_val2017_detections_AP_H_56_person.json so I did use_gt_bbox=True,
as it described in https://github.com/open-mmlab/mmpose/issues/687

**Comment by SylvainArd** [comment]
here are the results after 20 epochs there are very better :

Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] =
 0.505
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets= 20 ] =
 0.845
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets= 20 ] =
 0.535
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] =
 0.010
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] =
 0.518
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] =
 0.589
 Average Recall     (AR) @[ IoU=0.50      | area=   all | maxDets= 20 ] =
 0.880
 Average Recall     (AR) @[ IoU=0.75      | area=   all | maxDets= 20 ] =
 0.642
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] =
 0.171
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] =
 0.592
Sylvain Ard
0549507724
0778380991
***@***.***
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers

**Comment by SylvainArd** [comment]
but how to interpret these results please ?

**Comment by SylvainArd** [comment]
hello my results at the end of training are :
2022-12-01 23:00:56,950 - mmpose - INFO - Best AP is 0.9750 at 210 epoch.
2022-12-01 23:00:56,951 - mmpose - INFO - Epoch(val) [210][36] AP: 0.9750,
AP .5: 1.0000, AP .75: 0.9901, AP (M): 0.8867, AP (L): 0.9764, AR: 0.9859,
AR .5: 1.0000, AR .75: 0.9991, AR (M): 0.9571, AR (L): 0.9861

I have a question : I want to see the results so I did :
python demo/top_down_img_demo.py
 configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w48_coco_384x288.py
"output/latest.pth"  --img-root dataset/photos --json-file
dataset/coco.json --out-img-root res_img

the results seems perfect but are they ground truth (in this case why give
the model at the command) or predicted (in this case why give the JSON of
ground truth) ?

I have also run this command :

python tools/test.py
configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w48_coco_384x288.py
"output/latest.pth" --out  res_img/res.json

I can't see the results on images but I opened the image with Gimp and
pointed the cursor on predicted coordinates in JSON and it seems good

Thank you very much

If the results of
python tools/test.py
configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w48_coco_384x288.py
"output/latest.pth" --out  res_img/res.json
are predictions your program is perfect !

Sylvain Ard
0549507724
0778380991
***@***.***
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers

**Comment by ly015** [comment]
You needn't worry about the ground-truth json file passed to the demo script `demo/top_down_img_demo.py`. As you may already know that a top-down keypoint model needs the input of the object bounding box to perform the keypoint detection within the bbox area. The ground-truth json file is only used to give the bbox information and the keypoints in the visualized images are predicted by the model. And that's why you would need a detection model together with the top-down keypoint model to perform bbox+keypoint prediction on raw images (where ground-truth boxes are not available).

In the config of a top-down keypoint model in MMPose, the `image_size` is actually the model input size to which the bbox area will be resized (by affine transform), and it's irrelevant to the original image size. The original image can be in arbitrary sizes.

**Comment by SylvainArd** [comment]
so for prediction we need to detect the bbox first, the program don't do it
?
Sylvain Ard
0549507724
0778380991
***@***.***
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers

**Comment by SylvainArd** [comment]
I tried to launch test on a new image but it crashed because it doesn't
find the image in the JSON, have I to create a JSON with bbox (and
obviously not keypoints) for the testing with another program ?
Sylvain Ard
0549507724
0778380991
***@***.***
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers

**Comment by SylvainArd** [comment]
well, I have maked a JSON file with bbox but with testing I have the error :
KeyError: 'keypoints'
it's cheating if we pass the points to the program it's normal that it
discovers them! this is not normal at all!
Sylvain Ard
0549507724
0778380991
***@***.***
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers

**Comment by SylvainArd** [comment]
please help me ! it is the final step

**Comment by ly015** [comment]
Yes, top-down keypoint detection needs an object detector. Please see `/demo/top_down_img_demo_with_mmdet.py` for this paradigm. In this demo, we use MMDetection for detection.

In `/demo/top_down_image_demo.py`, as I mentioned, only bbox information from the json file is used. You can check it in the code: https://github.com/open-mmlab/mmpose/blob/master/demo/top_down_img_demo.py#L91-L96

If you are using the testing tool, it requires the ground-truth keypoint coordinates to evaluate the model performance, like calculating COCO AP.

**Comment by SylvainArd** [comment]
OK so how to do a prediction with only bboxes if test needs ground-truth ?

Sylvain Ard
0549507724
0778380991
***@***.***
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers

**Comment by SylvainArd** [comment]
what is the command ?
Sylvain Ard
0549507724
0778380991
***@***.***
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers

**Comment by SylvainArd** [comment]
I mean a prediction with a JSON file ?
Sylvain Ard
0549507724
0778380991
***@***.***
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers

**Comment by ly015** [comment]
I am confused about your need.

If you want to predict keypoints from an image with a top-down keypoint model, only bounding boxes are needed, no matter if they are from the json file or an extra detector. This is shown in `demo/top_down_image_demo.py` and `demo/top_down_image_demo_with_mmdet.py`. And a brief guide is provided in `demo/docs/2d_human_pose_demo.md`.

If you want to evaluate your model, you need to compare the model prediction with the ground-truth keypoint annotations. That's what the `tools/test.sh` does.

**Comment by SylvainArd** [comment]
yes but   demo/top_down_image_demo.py  only give images, what I want is a
JSON where I can find the points coordinates
Sylvain Ard
0549507724
0778380991
***@***.***
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers

**Comment by ly015** [comment]
Maybe just add a few lines of code to dump the prediction to a JSON? The demo is just meant to show the basic use of MMPose API.

**Comment by SylvainArd** [comment]
on demo on an image of training dataset wich I give only bboxes it detects
none keypoints, whereas when I give keypoints it detects the keypoints and
display it !!
Sylvain Ard
0549507724
0778380991
***@***.***
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers

**Comment by SylvainArd** [comment]
it works ! it was errors in my JSON file

**Comment by SylvainArd** [comment]
I added the lines :

        chaine=""
        for line in pose_results:
            bbox=line["bbox"]
            kps=line["keypoints"]
            chaine=chaine+"bbox:"
            i=0
            for c in bbox:
                i=i+1
                chaine=chaine+str(c)
                if i!=4:
                    chaine=chaine+","
            chaine=chaine+"|keypoints:["
            for kp in kps:
                chaine=chaine+"["
                i=0
                for c in kp:
                    i=i+1
                    chaine=chaine+str(c)
                    if i!=3:
                        chaine=chaine+","
                chaine=chaine+"]"
            chaine=chaine+"]\n"

        with open('demo_img/kp.txt', 'w') as f:
            f.write(chaine)

to top_down_img_demo.py it works, you can close the ticket, a last question
the image size is 384x288, if the input image is more high than wide, it is
deformed isn'it and it decrease training efficiency isn'it ?

**Comment by ly015** [comment]
As explained above, 384x288 is the model input size to which the **bbox area** will be resized, and it's irrelevant to the full image size. And the size 384x288 is for human keypoint detection (that's why the height is larger than the width). You can set it according to the task.
