### ISSUE TITLE
Information about keypoints

### ISSUE THREAD

**Issue by RSKothari** [open-mmlab/mmpose#185]
Hello, it would be most helpful if you could add a document on the details of which keypoints are detected.

**Comment by innerlee** [comment]
Could you give more detail? Is the info here https://github.com/open-mmlab/mmpose/blob/master/mmpose/datasets/datasets/top_down/topdown_aic_dataset.py#L19 what you want?

It seems that the doc system has some issue, and not displaying these docstrings.

**Comment by RSKothari** [comment]
Thanks! That's close to what I'm looking for. Essentially, I'm trying to use a model which would give me best performance for profile or back-view faces. Examples of my application:

![image](https://user-images.githubusercontent.com/10388010/95682418-1ab43000-0bb3-11eb-933f-3cc3e8e1b261.png)
![image](https://user-images.githubusercontent.com/10388010/95682405-0b34e700-0bb3-11eb-9856-dbb4f50c76c5.png)

In order to do this, I need a model which provides reasonably reliable key-points. Now the coco-full body might not work for such examples, so I'm trying to figure out which model to use.

**Comment by jin-s13** [comment]
Most models focus on predicting body keypoints.
For coco models, we only have 5 face keypoints, i.e. nose, left eye, right eye, left ear, right ear.
https://github.com/open-mmlab/mmpose/blob/1a2b1d85023a4697dbec37a804c358818f1a489b/mmpose/datasets/datasets/top_down/topdown_coco_dataset.py#L25

And coco-wholebody models, will have 68 extra face keypoints. see https://github.com/jin-s13/COCO-WholeBody

**Comment by jin-s13** [comment]
I used the following settings to do the inference. 
```
$PATH_MMDET/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py
$PATH_MMDET_WEIGHTS/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
$PATH_MMPOSE/configs/top_down/darkpose/coco-wholebody/hrnet_w48_coco_wholebody_384x288_dark_plus.py
$PATH_MMPOSE_WEIGHTS/hrnet_w48_coco_wholebody_384x288_dark-f5726563_20200918.pth
--img-root $IMG_ROOT
--img demo.png
--out-img-root vis_results
--bbox-thr 0.5
--kpt-thr 0.5
```

The result imgs can be downloaded here.

https://drive.google.com/file/d/1jHPdeCeJZ5Wsu45fYL9l7vbQ0p3h1K_2/view?usp=sharing
https://drive.google.com/file/d/1SjqnMed9C_Fe6jbYAqCvBdpkSOG0FXuX/view?usp=sharing

**Comment by RSKothari** [comment]
Thanks a lot @jin-s13
