### ISSUE TITLE
How to convert hrnet topdown model to onnx

### ISSUE THREAD

**Issue by lamhust2008** [open-mmlab/mmpose#1852]
I want to convert checkpoint hrnet_w32_coco_256x192-c78dce93_20200708.pth, and config: hrnet_w32_coco_256x192.py. I try to use command in mmaction2/tools/deployment/pytorch2onnx.py, and error appeared:
File "pytorch2onnx.py", line 149, in
cfg.model, train_cfg=None, test_cfg=cfg.get('test_cfg'))
File "/home/data/lamnt/lamnt/Video_recog/mmaction2/mmaction/models/builder.py", line 87, in build_model
raise ValueError(f'{obj_type} is not registered in '
ValueError: TopDown is not registered in LOCALIZERS, RECOGNIZERS or DETECTORS

WHO CAN HELP ME,thanks

**Comment by lamhust2008** [comment]
I want to convert checkpoint hrnet_w32_coco_256x192-c78dce93_20200708.pth, and config: hrnet_w32_coco_256x192.py. I try to use command in mmaction2/tools/deployment/pytorch2onnx.py, and error appeared:
 File "pytorch2onnx.py", line 149, in <module>
    cfg.model, train_cfg=None, test_cfg=cfg.get('test_cfg'))
  File "/home/data/lamnt/lamnt/Video_recog/mmaction2/mmaction/models/builder.py", line 87, in build_model
    raise ValueError(f'{obj_type} is not registered in '
ValueError: TopDown is not registered in LOCALIZERS, RECOGNIZERS or DETECTORS

WHO CAN HELP ME,thanks

**Comment by Tau-J** [comment]
Hi, it seems that you are using scripts from MMAction2 to convert a model from MMPose, that's why the error occurs.

**Comment by lamhust2008** [comment]
> Hi, it seems that you are using scripts from MMAction2 to convert a model from MMPose, that's why the error occurs.

Thanks for your answer, but can you tell me how to inference my onnx model

**Comment by ly015** [comment]
Further discussion in #1856
