### ISSUE TITLE
mmpose是否支持SPPNet中的空间金字塔池化结构呢？

### ISSUE THREAD

**Issue by ShaneCan** [open-mmlab/mmpose#1854]
想要在网络的neck部分使用SPPlayer，不知道可否实现，感谢解答！

**Comment by ly015** [comment]
可能需要自己实现一个 neck。目前 MMPose 里只有 gap 和 fpn 等 neck：https://github.com/open-mmlab/mmpose/tree/master/mmpose/models/necks

**Comment by ShaneCan** [comment]
> 可能需要自己实现一个 neck。目前 MMPose 里只有 gap 和 fpn 等 neck：https://github.com/open-mmlab/mmpose/tree/master/mmpose/models/necks

感谢亦宁，我目前采用了swin中的fpn结构，效果尚可。
