### ISSUE TITLE
InterHands2.6m annotations unavailable

### ISSUE THREAD

**Issue by jhkim-lumanlab** [open-mmlab/mmpose#1857]
I tried to download InterHands2.6m annotations files from the link the documentation provides(https://github.com/open-mmlab/mmpose/blob/master/docs/en/tasks/3d_hand_keypoint.md), but Error 404 popped up.
It seems the link is no longer available, so I wonder where I can download the annotations.

**Comment by ly015** [comment]
Thanks for your feedback, the download link seems outdated and we will update it asap. You can download the annotations from their website: https://mks0601.github.io/InterHand2.6M/
