### ISSUE TITLE
How to test the speed when I run the test/val

### ISSUE THREAD

**Issue by ChenZhenGui** [open-mmlab/mmpose#1863]
Hello,I would like to ask how to test the speed just like the  cost time or the fps when I run the test/val
![image](https://user-images.githubusercontent.com/52156532/206102728-8e4ec4b6-c923-4dfe-a1a9-c3092752b008.png)

**Comment by jin-s13** [comment]
You may try https://github.com/open-mmlab/mmpose/blob/master/tools/analysis/benchmark_inference.py

**Comment by liqikai9** [comment]
@ChenZhenGui Thanks for using MMPose 1.x. For now, we do not have the script to test inference speed in 1.x version. 

> You may try https://github.com/open-mmlab/mmpose/blob/master/tools/analysis/benchmark_inference.py

You can try the above script which is in the `master` branch of MMPose and make minor modification to be compatible to 1.x version. We are planning to add this feature into mmpose 1.x. And if you are interested in supporting this feature in mmpose 1.x, please let us know. We are glad to help.

**Comment by ChenZhenGui** [comment]
That's my pleasure, about the speed-test feature I saw in the mmdeploy project, it specifically provides an optional parameter to test the inference speed, it feels very practical

**Comment by liqikai9** [comment]
> about the speed-test feature I saw in the mmdeploy project,

Could you please share the llink to this feature? So that we may add it in mmpose as well.

**Comment by ChenZhenGui** [comment]
the doc:
https://github.com/open-mmlab/mmdeploy/blob/master/docs/zh_cn/02-how-to-run/profile_model.md
the code:
https://github.com/open-mmlab/mmdeploy/blob/master/tools/test.py
