### ISSUE TITLE
AssertionError: MMCV==2.0.0rc3 is used but incompatible. Please install mmcv>=1.3.8, <=1.8.0.

### ISSUE THREAD

**Issue by Jeong-Bin** [open-mmlab/mmpose#1874]
I should use `--save-predictions` for get predict result, so I created new conda env and installed mmpose 1.0 followed [here](https://mmpose.readthedocs.io/en/1.x/installation.html)

Then I tried to `import mmpose` but I received this error :
   AssertionError: MMCV==2.0.0rc3 is used but incompatible. Please install mmcv>=1.3.8, <=1.8.0.

How do I solve this for use mmpose 1.0 ?

And also I have some little questions.
- Is the 'segmentation' nessesary in [COCO format](https://mmpose.readthedocs.io/en/latest/tutorials/2_new_dataset.html#customize-datasets-by-reorganizing-data-to-coco-format) ? 
   My annotation files don't have the segmentation, what should I do?
- If I modify COCO format for 3D(x,y,z), should I change the  'keypoints' like this? : 
   'keypoints' : [x,y,z,v]
- Is v nessesary in keypoints? Also my annotation files don't have the v... what should I do?

I always appreciate your support.

**Comment by Jeong-Bin** [comment]
Hello, Let me change the question.
Finally, I succeeded to import mmcv==2.0.0rc3 and mmpose==1.0.0b0.
And also I changed my annotation format to COCO format.
Thanks to your help and good documents.

So now, all I have to do is activate the demo code.
but I coundn't find the `3d_human_pose_demo.md` in MMPose 1.x and [hear](https://github.com/open-mmlab/mmpose/tree/dev-1.x/demo/docs)
Is there only `2d_human_pose_demo.md`  in MMPose1.x  so far?

What should I do to use `--save-predictions` with 3d_human_pose?

Thanks.

**Comment by ly015** [comment]
Hi, thanks for using MMPose v1.x. We are still working on refactoring the 3d part and it will be added to 1.x next month.

**Comment by Jeong-Bin** [comment]
> Hi, thanks for using MMPose v1.x. We are still working on refactoring the 3d part and it will be added to 1.x next month.

Thanks. Then... When I tried 2D human pose demo whit this code,

```
!python topdown_demo_with_mmdet.py \
    demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py \
    https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \
    configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_hrnet-w32_8xb64-210e_coco-256x192.py \
    https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_coco_256x192-c78dce93_20200708.pth \
    --input /content/drive/MyDrive/kmu_CAI_lab/01_PoseEstimation/MMPose/sample_data/vidtest2.mp4 \
    --output-root=output/test \
    --show --draw-heatmap --save-predictions 
```

I got this error
```
usage: topdown_demo_with_mmdet.py
       [-h]
       [--input INPUT]
       [--show]
       [--output-root OUTPUT_ROOT]
       [--device DEVICE]
       [--det-cat-id DET_CAT_ID]
       [--bbox-thr BBOX_THR]
       [--nms-thr NMS_THR]
       [--kpt-thr KPT_THR]
       [--draw-heatmap]
       [--radius RADIUS]
       [--thickness THICKNESS]
       det_config
       det_checkpoint
       pose_config
       pose_checkpoint
topdown_demo_with_mmdet.py: error: unrecognized arguments: --save-predictions
```

Is that way to use `--save-predictions` wrong?

**Comment by Ben-Louis** [comment]
This feature has been supported in branch `dev-1.x` instead of `1.x`. If you install mmpose from source, you could simply switch to branch `dev-1.x`. Otherwise, you may need to install mmpose again via `pip install -e .` after switching to branch `dev-1.x`.

**Comment by Jeong-Bin** [comment]
> This feature has been supported in branch `dev-1.x` instead of `1.x`. If you install mmpose from source, you could simply switch to branch `dev-1.x`. Otherwise, you may need to install mmpose again via `pip install -e .` after switching to branch `dev-1.x`.

I tried this code, but it still coundn't recognize `--save-predictions`.

```
!pip3 install openmim
!mim install mmengine
!mim install "mmcv>=2.0.0rc1"
!mim install "mmdet>=3.0.0rc0"

!git clone https://github.com/open-mmlab/mmpose.git -b dev-1.x
## mmpose -> mmpose_dev-1.0
%cd mmpose_dev-1.0

!pip install -r requirements.txt
!pip install -v -e 
```
```
!python topdown_demo_with_mmdet.py \
## "demo/topdown_demo_with_mmdet.py" didn't work because of this error: 
## ModuleNotFoundError: No module named 'mmpose'
## so I changed the directoty to "/topdown_demo_with_mmdet.py"
    demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py \
    https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \
    configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_hrnet-w32_8xb64-210e_coco-256x192.py \
    https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_coco_256x192-c78dce93_20200708.pth \
    --input /kmu_CAI_lab/01_PoseEstimation/MMPose/sample_data/vidtest2.mp4 \
    --output-root=output/test \
    --show --draw-heatmap --save-predictions
```

How to swich to branch `dev-1.x`?

**Comment by Ben-Louis** [comment]
It seems like the problem is that mmpose is not installed successfully. Maybe you could try `pip install -v -e .` instead of `pip install -v -e`

The command for switching to branch `dev-1.x` is `git checkout -b dev-1.x origin/dev-1.x` which should be executed under the directory of mmpose. But the branch of your local repo should be correct as it is specified when you clone the repo.

**Comment by Jeong-Bin** [comment]
> It seems like the problem is that mmpose is not installed successfully. Maybe you could try `pip install -v -e .` instead of `pip install -v -e`
> 
> The command for switching to branch `dev-1.x` is `git checkout -b dev-1.x origin/dev-1.x` which should be executed under the directory of mmpose. But the branch of your local repo should be correct as it is specified when you clone the repo.

Finally, It worked! Thank you vary much!!
I have last one question.
It I wanna realtime human pose demo, which should I use?Do you have any plan to add 3D webcam demo in `dev-1.x`?

**Comment by Tau-J** [comment]
@Jeong-Bin Sorry for late reply. For real-time inference, you can try some lightweight models, such as mobilenetv2, shufflenetv2, litehrnet etc. and you can use webcam_demo.py to inference with your camara.
As for 3d webcam demo, we do have a plan but we're still refactoring 3d algorithms right now.

**Comment by sxj731533730** [comment]
AssertionError: MMCV==2.0.0rc4 is used but incompatible. Please install mmcv>=1.3.17, <=1.8.0.

**Comment by sxj731533730** [comment]
AssertionError: MMCV==2.0.0rc4 is used but incompatible. Please install mmcv>=1.3.8, <=1.7.0.
ubuntu@ubuntu:~/mmpose/demo$ mim list
Package    Version    Source
---------  ---------  -----------------------------------------
mmcv       2.0.0rc4   https://github.com/open-mmlab/mmcv
mmdet      3.0.0rc6   https://github.com/open-mmlab/mmdetection
mmengine   0.6.0      https://github.com/open-mmlab/mmengine
mmpose     0.28.1     /home/ubuntu/mmpose
mmrotate   0.3.3      /home/ubuntu/mmrotate
mmcv环境安装真是难
