### ISSUE TITLE
Error with bottom_up_img_demo.py and DEKR

### ISSUE THREAD

**Issue by cechantonin** [open-mmlab/mmpose#1875]
Hi, I'm trying to run the bottom_up_img_demo.py with DEKR config and checkpoint, but I get the following error. I saw issues #1734 and #1724 but I couldn't get the fix to work. The script works fine with Associative Embedding.
![image](https://user-images.githubusercontent.com/84121269/206868614-792643ff-3029-4602-a0d7-a889ca6941da.png)

I have the latest MMPose pulled and I'm on Windows with Python 3.10 and torch 1.13.0+cu117. I'm running the script with: 
python bottom_up_img_demo.py path_to_dekr_config/hrnet_w48_coco_640x640.py path_to_dekr_checkpoint/hrnet_w48_coco_640x640-8854b2f1_20220930.pth --img-path b:/pose_est/mscoco/images/val2017 --out-img-root b:/pose_est/mmpose_results

**Comment by Ben-Louis** [comment]
I guess this might be a version problem. https://github.com/open-mmlab/mmpose/pull/1734 was fixed after the release of MMPose v0.29. So if you install MMPose as a third-party package, you might miss it. You could try to install MMPose **from source** after pulling the latest commits (see [installation guide](https://mmpose.readthedocs.io/en/latest/install.html#best-practices))

**Comment by cechantonin** [comment]
I installed it using pip and it installed version 0.29.0, which should be the one with DEKR working, according to the release notes. Nevertheless, installing from source fixed it and DEKR works for me now, thank you.
