### ISSUE TITLE
how to extract inference info  from PoseDataSample

### ISSUE THREAD

**Issue by yjdqk** [open-mmlab/mmpose#1881]
my question is that: my project inference a image,got keypoints info ,which typedata as PoseSample.How to solve PoseSample  ?

**Comment by Tau-J** [comment]
Hi @yjdqk , thanks for using MMPose! I think you should decode the results, maybe [codecs](https://github.com/open-mmlab/mmpose/tree/dev-1.x/mmpose/codecs) and [this](https://github.com/open-mmlab/mmpose/blob/b2e8c0c2610e2c7f8e2680e0041168d1d2206fb9/mmpose/models/heads/base_head.py#L99) could help.
