### ISSUE TITLE
Doubt about the use of mmpose

### ISSUE THREAD

**Issue by antonio2600** [open-mmlab/mmpose#1883]
Hello. 
I'm doing a project abaout disease detection in human behaviors. For this I need to detect the poses of people in videos of daily tasks. I want to use the mmpose library, but I don't really know how to do it. The examples that I have seen you do it with an image, how could I do it with a video?
Thanks.

**Comment by Ben-Louis** [comment]
Hi, the simplest way to extract human poses in videos with MMPose is to use the demo scripts of MMPose 1.x. The detailed steps:
1) Install MMPose 1.x (see [installation guide](https://mmpose.readthedocs.io/en/dev-1.x/installation.html#best-practices)). Note that you need to install MMPose **from source** in "Step 1" and using the branch `dev-1.x` instead of `1.x`.
2) Run demo on your videos following [this guide](https://github.com/open-mmlab/mmpose/blob/dev-1.x/demo/docs/2d_human_pose_demo.md#2d-human-pose-top-down-video-demo). Remember to add argument `--save-predictions` to save the model predictions on your disk. 

Then you can find the detected human poses of each frame in your video under the `OUTPUT_ROOT` you set in step 2, which is ready for use on your own tasks.

**Comment by antonio2600** [comment]
Ok. And another question. I have been working with mmaction2 action recognition on kinetics-400. Can I combine the action recognition model with mmpose?

**Comment by Ben-Louis** [comment]
I think it is practicable since MMAction2 supports [skeleton-based action recognition models](https://mmaction2.readthedocs.io/en/1.x/skeleton_models.html). @ly015 Could you please give some specific advice?

**Comment by ly015** [comment]
In MMActoin2 we provided a demo to use MMDetection, MMPose, and MMAction2 to perform human detection, pose estimation, and skeleton-based action recognition. The documentation can be found [here](https://mmaction2.readthedocs.io/en/1.x/user_guides/3_inference.html#inference-with-skeleton-based-action-recognition-models).

**Comment by antonio2600** [comment]
Ok, thanks!

**Comment by antonio2600** [comment]
Hello. I have been trying inference with Skeleton-based Action Recognition Models but the command fails and I don't know why, because it says that there isn't module named 'mmaction'.
![Captura desde 2022-12-19 19-15-25](https://user-images.githubusercontent.com/42941507/208493147-ded2a98e-9e85-48b4-aa94-0dfc13e05fb7.png)

**Comment by Ben-Louis** [comment]
Have you installed MMAction2? If not, you could install it following [this doc](https://mmaction2.readthedocs.io/zh_CN/1.x/get_started.html#installation) and try again.

**Comment by antonio2600** [comment]
Yes I installed it and I have used other files that also import from mmaction and they have not given me problems, but now it fails.

**Comment by antonio2600** [comment]
I have solved the error copying the mmaction folder inside demo, otherwise it doesn't detect it. Now the error that I get is this:

![image](https://user-images.githubusercontent.com/42941507/208662033-3f6948b6-8443-4f6d-bf55-f488caa4d1c7.png)

**Comment by antonio2600** [comment]
I've got the original video with the 2D skeleton. The work I'm doing is based on recognizing actions related to diseases, so I need to extract metrics from the skeleton I just got. The question I have is, how do I get information now from the video, is there any information about this? Time that the skeleton is still, time that it is sitting... @ly015  @Ben-Louis

**Comment by Billccx** [comment]
> Hi, the simplest way to extract human poses in videos with MMPose is to use the demo scripts of MMPose 1.x. The detailed steps:
> 
> 1. Install MMPose 1.x (see [installation guide](https://mmpose.readthedocs.io/en/dev-1.x/installation.html#best-practices)). Note that you need to install MMPose **from source** in "Step 1" and using the branch `dev-1.x` instead of `1.x`.
> 2. Run demo on your videos following [this guide](https://github.com/open-mmlab/mmpose/blob/dev-1.x/demo/docs/2d_human_pose_demo.md#2d-human-pose-top-down-video-demo). Remember to add argument `--save-predictions` to save the model predictions on your disk.
> 
> Then you can find the detected human poses of each frame in your video under the `OUTPUT_ROOT` you set in step 2, which is ready for use on your own tasks.

Could you please explain the difference between dev-1.x and 1.x ? The branches of mmpose is quite confusing. Sometimes I failed to run the demo code, however, I works when I change to another branch.

**Comment by Ben-Louis** [comment]
Hi @Billccx, sorry for the confusion. Branch `1.x` is the stable version of MMPose 1.0 while branch `dev-1.x` is the develop branch where new features, such as saving model predictions locally when running demos, are added. This is why you will fail to run demos in branch `1.x` with some functions only supported in `dev-1.x`. New features in `dev-1.x` will be merged into `1.x` upon the release of new versions.
