### ISSUE TITLE
Is there an example of pose model distillation ？

### ISSUE THREAD

**Issue by APeiZou** [open-mmlab/mmpose#1884]
@piercus @zhiqwang @open-mmlab Hello, Is there an example of pose model distillation ？

**Comment by jin-s13** [comment]
Currently, model distillation is not supported.

**Comment by APeiZou** [comment]
@jin-s13 Will you plan to develop the knowledge distillation of the pose model in the future?

**Comment by ly015** [comment]
We are working on supporting model distillation based on [MMPose v1.x](https://github.com/open-mmlab/mmpose/tree/1.x) and [MMRazor](https://github.com/open-mmlab/mmrazor). Please stay tuned.

By the way, may I know why those 2 GitHub users (peircus and zhiqwang) pinged in this issue?

**Comment by APeiZou** [comment]
@ly015   Thanks for your reply, I don't know why they appear
