### ISSUE TITLE
Does it make sense to have batched pose model inference tutorial?

### ISSUE THREAD

**Issue by nghorbani** [open-mmlab/mmpose#1885]
Thanks for the great work. 
This feature is asked for multiple times and I see most of the reported issues marked as closed, yet I miss to find a single point of demo on how to use pose models on batched data. could you please give us a clue?

**Comment by tctco** [comment]
looking forward to this feature

**Comment by ly015** [comment]
Batch data is supported in the [inference API](https://github.com/open-mmlab/mmpose/blob/master/mmpose/apis/inference.py#L277). When using multiple images and corresponding bboxes as the input, they will be batched to feed into the model.

**Comment by tctco** [comment]
Is this feature also available in mmpose 1.x?
