### ISSUE TITLE
训练hourglass报错

### ISSUE THREAD

**Issue by hatecodes** [open-mmlab/mmpose#1887]
### **训练至70轮次后报错：**
2022-12-20 15:57:03,755 - mmpose - INFO - load checkpoint from local path: F:\mmpose-master\tools\logs\f_airplane_hourglass52_7points_bz12_384\epoch_70.pth
Traceback (most recent call last):
  File "F:/mmpose-master/tools/train.py", line 195, in <module>
    main()
  File "F:/mmpose-master/tools/train.py", line 191, in main
    meta=meta)
  File "F:\mmpose-master\mmpose\apis\train.py", line 197, in train_model
    runner.resume(cfg.resume_from)
  File "F:\Anaconda\envs\mmpose\lib\site-packages\mmcv\runner\base_runner.py", line 356, in resume
    map_location=lambda storage, loc: storage.cuda(device_id))
  File "F:\Anaconda\envs\mmpose\lib\site-packages\mmcv\runner\base_runner.py", line 345, in load_checkpoint
    revise_keys=revise_keys)
  File "F:\Anaconda\envs\mmpose\lib\site-packages\mmcv\runner\checkpoint.py", line 542, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "F:\Anaconda\envs\mmpose\lib\site-packages\mmcv\runner\checkpoint.py", line 481, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "F:\Anaconda\envs\mmpose\lib\site-packages\mmcv\runner\checkpoint.py", line 251, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "F:\Anaconda\envs\mmpose\lib\site-packages\mmcv\runner\checkpoint.py", line 268, in load_from_local
    checkpoint = torch.load(filename, map_location=map_location)
  File "F:\Anaconda\envs\mmpose\lib\site-packages\torch\serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "F:\Anaconda\envs\mmpose\lib\site-packages\torch\serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input

### **config如下：**
_base_ = [
    '../../../../_base_/default_runtime.py',
    '../../../../_base_/datasets/fly.py'
]
evaluation = dict(interval=10, metric='mAP', save_best='AP')

optimizer = dict(
    type='Adam',
    lr=5e-4,
)
optimizer_config = dict(grad_clip=None)
# learning policy
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.001,
    step=[170, 200])
total_epochs = 210
log_config = dict(
    interval=1,
    hooks=[
        dict(type='TextLoggerHook'),
        # dict(type='TensorboardLoggerHook')
    ])
channel_cfg = dict(
    num_output_channels=7,
    dataset_joints=7,
    dataset_channel=[
        [0, 1, 2, 3,4,5,6],
    ],
    inference_channel=[
        0, 1, 2, 3,4,5,6
    ])

# model settings
model = dict(
    type='TopDown',
    pretrained=None,
    backbone=dict(
        type='HourglassNet',
        num_stacks=1,
    ),
    keypoint_head=dict(
        type='TopdownHeatmapMultiStageHead',
        in_channels=256,
        out_channels=channel_cfg['num_output_channels'],
        num_stages=1,
        num_deconv_layers=0,
        extra=dict(final_conv_kernel=1, ),
        loss_keypoint=dict(type='JointsMSELoss', use_target_weight=True)),
    train_cfg=dict(),
    test_cfg=dict(
        flip_test=True,
        post_process='default',
        shift_heatmap=True,
        modulate_kernel=11))

data_cfg = dict(
    image_size=[384, 384],
    heatmap_size=[96, 96],
    num_output_channels=channel_cfg['num_output_channels'],
    num_joints=channel_cfg['dataset_joints'],
    dataset_channel=channel_cfg['dataset_channel'],
    inference_channel=channel_cfg['inference_channel'],
    soft_nms=False,
    nms_thr=1.0,
    oks_thr=0.9,
    vis_thr=0.2,
    use_gt_bbox=True,
    det_bbox_thr=0.0,
    bbox_file='',
)

train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='TopDownRandomFlip', flip_prob=0.5),
    dict(
        type='TopDownHalfBodyTransform',
        num_joints_half_body=8,
        prob_half_body=0.3),
    dict(
        type='TopDownGetRandomScaleRotation', rot_factor=40, scale_factor=0.5),
    dict(type='TopDownAffine'),
    dict(type='ToTensor'),
    dict(
        type='NormalizeTensor',
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]),
    dict(type='TopDownGenerateTarget', sigma=3),
    dict(
        type='Collect',
        keys=['img', 'target', 'target_weight'],
        meta_keys=[
            'image_file', 'joints_3d', 'joints_3d_visible', 'center', 'scale',
            'rotation', 'bbox_score', 'flip_pairs'
        ]),
]

val_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='TopDownAffine'),
    dict(type='ToTensor'),
    dict(
        type='NormalizeTensor',
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]),
    dict(
        type='Collect',
        keys=['img'],
        meta_keys=[
            'image_file', 'center', 'scale', 'rotation', 'bbox_score',
            'flip_pairs'
        ]),
]

test_pipeline = val_pipeline

data_root = 'datacoco'
data = dict(
    samples_per_gpu=12,
    workers_per_gpu=12,
    val_dataloader=dict(samples_per_gpu=32),
    test_dataloader=dict(samples_per_gpu=32),
    train=dict(
        type='TopDownAirplaneDataset',
        ann_file=f'{data_root}/annotations/keypoints_train.json',
        img_prefix=f'{data_root}/train/',
        data_cfg=data_cfg,
        pipeline=train_pipeline,
        dataset_info={{_base_.dataset_info}}),
    val=dict(
        type='TopDownAirplaneDataset',
        ann_file=f'{data_root}/annotations/keypoints_val.json',
        img_prefix=f'{data_root}/val/',
        data_cfg=data_cfg,
        pipeline=val_pipeline,
        dataset_info={{_base_.dataset_info}}),
    test=dict(
        type='TopDownAirplaneDataset',
        ann_file=f'{data_root}/annotations/keypoints_val.json',
        img_prefix=f'{data_root}/val/',
        data_cfg=data_cfg,
        pipeline=test_pipeline,
        dataset_info={{_base_.dataset_info}}),
)

**Comment by Ben-Louis** [comment]
您好，这个报错看起来是程序保存的本地模型文件出了问题。请问在前面的轮次（例如第50、60轮）中程序的验证步骤能正常运行吗？

**Comment by hatecodes** [comment]
> 您好，这个报错看起来是程序保存的本地模型文件出了问题。请问在前面的轮次（例如第50、60轮）中程序的验证步骤能正常运行吗？

前面的轮次是可以正常保存的，不知道是怎么回事
