### ISSUE TITLE
AttributeError: 'ConfigDict' object has no attribute 'test_pipeline'

### ISSUE THREAD

**Issue by santhosh-inno** [open-mmlab/mmpose#189]
#13 

Hi, the error #13  is definitely resolved for COCO configs(mmpose) but same error still exists when testing on MPII configs(mmpose).

Here is the setting I used:

python $PATH_MMPOSE/demo/top_down_img_demo_with_mmdet.py $PATH_MMDET/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py
$PATH_MMDET_WEIGHTS/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
$PATH_MMPOSE/configs/top_down/hrnet/mpii/hrnet_w48_mpii_256x256.py
$PATH_MMPOSE_WEIGHTS/hrnet_w48_mpii_256x256-92cab7bd_20200812.pth
--img-root $IMG_ROOT
--img demo.jpg
--out-img-root vis_results

**Comment by innerlee** [comment]
the fix might be not hard, would you mind make a pull request?

**Comment by jin-s13** [comment]
#190
