### ISSUE TITLE
mmpose是否可以做热图的可视化呢？

### ISSUE THREAD

**Issue by ShaneCan** [open-mmlab/mmpose#1892]
即在图片上显示heatmap

**Comment by Ben-Louis** [comment]
您好，topdown-heatmap 方法的热图可视化功能已经在新版本 1.x 中支持了。可以参考 [文档](https://mmpose.readthedocs.io/en/1.x/user_guides/visualization.html) 或者 [demo](https://github.com/open-mmlab/mmpose/blob/1.x/demo/docs/2d_human_pose_demo.md)

**Comment by ShaneCan** [comment]
> 您好，topdown-heatmap 方法的热图可视化功能已经在新版本 1.x 中支持了。可以参考 [文档](https://mmpose.readthedocs.io/en/1.x/user_guides/visualization.html) 或者 [demo](https://github.com/open-mmlab/mmpose/blob/1.x/demo/docs/2d_human_pose_demo.md)

感谢您的回答，我之前用的是老版本，看来我需要更新至新版了！

**Comment by diu-diu-diu** [comment]
> 您好，topdown-heatmap 方法的热图可视化功能已经在新版本 1.x 中支持了。可以参考 [文档](https://mmpose.readthedocs.io/en/1.x/user_guides/visualization.html) 或者 [demo](https://github.com/open-mmlab/mmpose/blob/1.x/demo/docs/2d_human_pose_demo.md)

So, how can I do this in 0.28 version of MMPose

**Comment by ShaneCan** [comment]
> > 您好，topdown-heatmap 方法的热图可视化功能已经在新版本 1.x 中支持了。可以参考 [文档](https://mmpose.readthedocs.io/en/1.x/user_guides/visualization.html) 或者 [demo](https://github.com/open-mmlab/mmpose/blob/1.x/demo/docs/2d_human_pose_demo.md)
> 
> So, how can I do this in 0.28 version of MMPose

im currently using 0.24.0!!!

**Comment by 20LGWZQ** [comment]
> > > 您好，topdown-heatmap 方法的热图可视化功能已经在新版本 1.x 中支持了。可以参考 [文档](https://mmpose.readthedocs.io/en/1.x/user_guides/visualization.html) 或者 [demo](https://github.com/open-mmlab/mmpose/blob/1.x/demo/docs/2d_human_pose_demo.md)
> > 
> > 
> > So, how can I do this in 0.28 version of MMPose
> 
> im currently using 0.24.0!!!

请问你在0.24.0上实现热图可视化了吗
