### ISSUE TITLE
How to finetune Voxelpose?

### ISSUE THREAD

**Issue by Camila641** [open-mmlab/mmpose#1893]
Thanks for the great work! I'd like to finetune Voxelpose to get the 3d pose estimation from multiple views but I'm new to this. May I ask if there is any guide I can follow? I have read the repo but not sure which to follow.

Many thanks!

**Comment by liqikai9** [comment]
@Camila641 Hi. Thanks for using mmpose. 

You can refer to [this config ](https://github.com/open-mmlab/mmpose/blob/master/configs/body/3d_kpt_mview_rgb_img/voxelpose/panoptic/voxelpose_prn64x64x64_cpn80x80x20_panoptic_cam5.py), which train VoxelPose on Panoptic dataset. You can modify the corresponding settings according to your own dataset.

**Comment by Camila641** [comment]
> @Camila641 Hi. Thanks for using mmpose.
> 
> You can refer to [this config ](https://github.com/open-mmlab/mmpose/blob/master/configs/body/3d_kpt_mview_rgb_img/voxelpose/panoptic/voxelpose_prn64x64x64_cpn80x80x20_panoptic_cam5.py), which train VoxelPose on Panoptic dataset. You can modify the corresponding settings according to your own dataset.

Thanks for the quick response! To finetune it on my custom dataset, should the dataset in Panoptic format and are 3D keypoint coordinates needed? I'm a little bit confused about how to get the 3D keypoint coordinates.

**Comment by liqikai9** [comment]
> should the dataset in Panoptic format

Yes. The images and camera calibration data should be formatted into the Panoptic style.



> are 3D keypoint coordinates needed?

Yes, the ground truth 3D  keypoint coordinates annotations are necessary.

**Comment by Camila641** [comment]
> 

Other than [#1679](https://github.com/open-mmlab/mmpose/issues/1679), Do you have any recommended ways or tools to get the 3D keypoint coordinates annotations?

**Comment by liqikai9** [comment]
I think you may try [labelbee](https://github.com/open-mmlab/labelbee). 

Or you may read the detail about the [Panoptic dataset](http://domedb.perception.cs.cmu.edu/), and see if there are some guidances to get 3D keypoint coordinates annotations.
