### ISSUE TITLE
Use MMPose for my data

### ISSUE THREAD

**Issue by junkunyuan** [open-mmlab/mmpose#1895]
Hi, I want to use MMPose to extract the pose of my private person data.

I use the top down method by following https://github.com/open-mmlab/mmpose/blob/master/demo/docs/2d_human_pose_demo.md.

I run the following command:
```bash
python demo/top_down_img_demo_with_mmdet.py \
    demo/mmdetection_cfg/cascade_rcnn_x101_64x4d_fpn_coco.py \
    cascade_rcnn.pth \
    configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w32_coco_256x192.py\
    hrnet.pth
    --img-root my_data/ \
    --img my_img.jpg \
    --out-img-root get_pose/
```

Although I have extracted the pose of my person data, I find the keypoints were out of the bounding box. 

**My questions are:**

**1. How does it happen?**

**2. If I want to set the bbox to be the area of the whole image, what should I do? Could this cause an error? Because the keypoints may out of the whole image.**

Thanks a lot!

**Comment by Ben-Louis** [comment]
Thank you for using MMPose. During inference, the bounding boxes are expanded with a ratio of 1.25 by default. If you want to keep the keypoints inside the bounding box, you could modify the ratio in [this line](https://github.com/open-mmlab/mmpose/blob/148091e7a021c0f2f2e7060f945f76640e06263d/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w32_coco_256x192.py#L124) to 1.0.

**Comment by junkunyuan** [comment]
Thank you very much!
