### ISSUE TITLE
size mismatch for head.final_layer.weight

### ISSUE THREAD

**Issue by Jeong-Bin** [open-mmlab/mmpose#1902]
Hello!
I made the custom train code as a 2d human body model.
My custom annotations have 25 keypoints, not 17.
So I modified  `out_channels` in `td-hm_hrnet-w32_8xb64-210e_coco-256x192` :
(also, I modified other codes according to the Tutoral)
```
head=dict(
        type='HeatmapHead',
        in_channels=32,
        out_channels=25,
        deconv_out_channels=None,
        loss=dict(type='KeypointMSELoss', use_target_weight=True),
        decoder=codec),
```

but this error has occurred from demo script:
```
size mismatch for head.final_layer.weight: copying a param with shape torch.Size([17, 32, 1, 1]) from checkpoint, the shape in current model is torch.Size([25, 32, 1, 1]).
size mismatch for head.final_layer.bias: copying a param with shape torch.Size([17]) from checkpoint, the shape in current model is torch.Size([25]).
```

What additional code should I modify?

**Comment by jin-s13** [comment]
What checkpoint did you load? It seems that the checkpoint is a 17-channel model.

**Comment by Jeong-Bin** [comment]
> What checkpoint did you load? It seems that the checkpoint is a 17-channel model.

I used this script from [hear](https://github.com/open-mmlab/mmpose/blob/dev-1.x/demo/docs/2d_wholebody_pose_demo.md)
```
python demo/topdown_demo_with_mmdet.py \
    demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py \
    https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \
    configs/wholebody_2d_keypoint/topdown_heatmap/coco-wholebody/td-hm_hrnet-w48_dark-8xb32-210e_coco-wholebody-384x288.py \
    https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_coco_wholebody_384x288_dark-f5726563_20200918.pth \
    --input tests/data/coco/000000196141.jpg \
    --output-root vis_results/ --show
```

How to modify the checkpoint?

**Comment by jin-s13** [comment]
This is the problem. 
hrnet_w48_coco_wholebody_384x288_dark-f5726563_20200918.pth only have 17 keypoints, but your customed config is a 25 keypoint model. So you cannot load the pre-trained models.

**Comment by jin-s13** [comment]
You will need to retrain a 25-keypoint model.

**Comment by Jeong-Bin** [comment]
> You will need to retrain a 25-keypoint model.

Oh I see...
Than.. Is it impossible to remove the keypoints of the face and hands from wholebody model too?
(I need the body and foot keypoints)
Also, I wonder if the wholebody model can be speed up by remove some keypoints.
If there is no difference in speed, I will use the base wholebody model as it is and I will just remove the visualization.

**Comment by jin-s13** [comment]
It is possible to remove face/hand keypoints, but the speed difference is very small. 
I will suggest using the original model.

**Comment by Jeong-Bin** [comment]
> It is possible to remove face/hand keypoints, but the speed difference is very small. I will suggest using the original model.

Thanks! But I have to get foot's keypoints, so I think I can't use the original model(with 17 kpts).
Thank you for your suggestion!

**Comment by jin-s13** [comment]
Sorry, my mistake ... 
td-hm_hrnet-w32_8xb64-210e_coco-256x192   -----  17 keypoint
td-hm_hrnet-w48_dark-8xb32-210e_coco-wholebody-384x288  ---- 133 keypoint

**Comment by jin-s13** [comment]
You can use td-hm_hrnet-w48_dark-8xb32-210e_coco-wholebody-384x288, and only visualize the 25 keypoints from 133.

**Comment by Jeong-Bin** [comment]
@jin-s13  Thanks!!
