### ISSUE TITLE
pretrained in hrnet_w32_coco_256x192.py is wrong

### ISSUE THREAD

**Issue by vipcxj** [open-mmlab/mmpose#1903]
Thanks for your error report and we appreciate it a lot.
If you feel we have helped you, give us a STAR! :satisfied:

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

The pretrained value in [hrnet_w32_coco_256x192.py](https://github.com/open-mmlab/mmpose/blob/master/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w32_coco_256x192.py) is wrong. 
Current value is 'hrnet_w32-36af842e.pth'. But the link in the [doc](https://mmpose.readthedocs.io/en/latest/topics/body%282d%2Ckpt%2Csview%2Cimg%29.html#topdown-heatmap-hrnet-on-coco) is [ckpt](https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_coco_256x192-c78dce93_20200708.pth). And I try the current one. As a result, the model is broken. And then I try the link in the doc, though the ckpt does not exactly match the model, the model can work.

**Reproduction**

- What command or script did you run?

```
A placeholder for the command.
```

- What config did you run?

```
A placeholder for the config.
```

- Did you make any modifications on the code or config? Did you understand what you have modified?
- What dataset did you use?

**Environment**

1. Please run `PYTHONPATH=${PWD}:$PYTHONPATH python mmpose/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as

- How you installed PyTorch \[e.g., pip, conda, source\]
- Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**

If applicable, paste the error traceback here.

```
A placeholder for traceback.
```

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by jin-s13** [comment]
https://download.openmmlab.com/mmpose/pretrain_models/hrnet_w32-36af842e.pth is the classification model trained on imagenet, which is used for initialization. 

And https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_coco_256x192-c78dce93_20200708.pth is our pose model trained on coco.

**Comment by vipcxj** [comment]
So why the pretrained value in [hrnet_w32_coco_256x192.py](https://github.com/open-mmlab/mmpose/blob/master/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w32_coco_256x192.py) is the classification model trained on imagenet since the model name with coco

**Comment by jin-s13** [comment]
When training pose estimation models, we will load the imagenet-pretrained classification model for network initialization. That's called transfer learning.
