### ISSUE TITLE
little config error in 1.x

### ISSUE THREAD

**Issue by xinxinxinxu** [open-mmlab/mmpose#1905]
mmpose/tree/1.x/configs/hand_2d_keypoint/topdown_heatmap/coco_wholebody_hand)/td-hm_mobilenetv2_8xb32-210e_coco-wholebody-hand-256x256.py

mobilenetv2 out_channels is 1280, however "in_channles" of the head is 2048 in this config file.

**Comment by jin-s13** [comment]
Thanks for reporting this bug. Would you mind helping raising a PR to fix this bug?

**Comment by ly015** [comment]
Fixed in #1906
