### ISSUE TITLE
There is an error in install.md

### ISSUE THREAD

**Issue by hear0me** [open-mmlab/mmpose#1909]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

I got an error when I try to verify my installation. 
I use this commend to download test file:
mim download mmpose --config associative_embedding_hrnet_w32_coco_512x512  --dest .
but it tell me that I dont have mmengine package.

**Reproduction**

- What command or script did you run?
```
mim download mmpose --config associative_embedding_hrnet_w32_coco_512x512  --dest .
```

**Error traceback**

If applicable, paste the error traceback here.

```
UserWarning: Distutils was imported before Setuptools, but importing Setuptools also replaces the `distutils` module in `sys.modules`. This may lead to undesirable behaviors or errors. To avoid these issues, avoid using distutils directly, ensure that setuptools is installed in the traditional way (e.g. not an editable install), and/or make sure that setuptools is always imported before distutils.
  warnings.warn(
C:\Users\a\anaconda3\envs\openmmlab\lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "C:\Users\a\anaconda3\envs\openmmlab\lib\site-packages\mim\commands\download.py", line 105, in download
    from mmengine import Config
ModuleNotFoundError: No module named 'mmengine'
```

**Bug fix**

You can fix the problem by this command
```
mim install mmengine
```

**Comment by xin-li-67** [comment]
I believe in order to use `mim` we have to switch to the 1.x branch and the installation of `mmengine` has been covered in the `installation.md` already. Please take a look at this [link](https://github.com/open-mmlab/mmpose/blob/1.x/docs/en/installation.md#best-practices).
