### ISSUE TITLE
AssertionError: DetectorNode: MMDetection is required for DetectorNode.

### ISSUE THREAD

**Issue by pkmnjourney** [open-mmlab/mmpose#1911]
**Describe the bug**

Trying to run webcam_demo.py for first time returns MMDetection error
 
**Reproduction**

```
python demo/webcam_demo.py
```

- What config did you run?

No modifications made. Fresh install using the docs (not using mim).

**Environment**

Trying to run ```python mmpose/utils/collect_env.py``` returns:
```
C:\Users\Pkmnj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\mmcv\__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
Traceback (most recent call last):
  File "D:\Documents\GitHub\mmpose\mmpose\utils\collect_env.py", line 15, in <module>
    for name, val in collect_env().items():
  File "D:\Documents\GitHub\mmpose\mmpose\utils\collect_env.py", line 9, in collect_env
    env_info = collect_basic_env()
  File "C:\Users\Pkmnj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\mmcv\utils\env.py", line 124, in collect_env
    from mmcv.ops import get_compiler_version, get_compiling_cuda_version
  File "C:\Users\Pkmnj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\mmcv\ops\__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "C:\Users\Pkmnj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\mmcv\ops\active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "C:\Users\Pkmnj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing _ext: The specified procedure could not be found.
```

- Torch version ```1.12.1+cu113``` installed through pip.

**Error traceback**

```
C:\Users\Pkmnj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\mmcv\__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
C:\Users\Pkmnj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\mmcv\cnn\bricks\transformer.py:33: UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv-full`` if you need this module.
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
Traceback (most recent call last):
  File "C:\Users\Pkmnj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\mmcv\utils\registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "C:\Users\Pkmnj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\mmpose\apis\webcam\nodes\model_nodes\detector_node.py", line 78, in __init__
    assert has_mmdet, \
AssertionError: MMDetection is required for DetectorNode.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Documents\GitHub\mmpose\demo\webcam_demo.py", line 72, in <module>
    run()
  File "D:\Documents\GitHub\mmpose\demo\webcam_demo.py", line 67, in run
    webcam_exe = WebcamExecutor(**cfg.executor_cfg)
  File "C:\Users\Pkmnj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\mmpose\apis\webcam\webcam_executor.py", line 121, in __init__
    node = NODES.build(node_cfg)
  File "C:\Users\Pkmnj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\mmcv\utils\registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "C:\Users\Pkmnj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\mmcv\utils\registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
AssertionError: DetectorNode: MMDetection is required for DetectorNode.
```

**Comment by xin-li-67** [comment]
Yes, you need to install MMDetection as the [installation guide](https://mmpose.readthedocs.io/en/1.x/installation.html#best-practices) mentioned.

**Comment by pkmnjourney** [comment]
> Yes, you need to install MMDetection as the [installation guide](https://mmpose.readthedocs.io/en/1.x/installation.html#best-practices) mentioned.

Yes I've noticed that but is there no alternative way as whenever i try ```pip install mim``` I get the following error:
```'mim' is not recognized as an internal or external command,
operable program or batch file.```

So I can't use mim to donwload mmdet. I have done ```pip install mmdet``` but that hasn't worked.

**Comment by Ben-Louis** [comment]
Hey @pkmnjourney, try using `pip install -U openmim` to install mim. Additionally, if you are using **MMPose 1.x**, make sure to specify the version of mmdet by using `mim install "mmdet>=3.0.0rc0"`. Otherwise, you can just install mmdet with `pip install mmdet`.

**Comment by pkmnjourney** [comment]
> Hey @pkmnjourney, try using `pip install -U openmim` to install mim. Additionally, if you are using **MMPose 1.x**, make sure to specify the version of mmdet by using `mim install "mmdet>=3.0.0rc0"`. Otherwise, you can just install mmdet with `pip install mmdet`.

Thank you for the response. I have reinstalled everything in a fresh conda environment and I believe it worked but now I'm facing this error:
```ImportError: cannot import name 'Config' from 'mmcv'```

**Comment by xin-li-67** [comment]
> 

Hi, Please double check your environment with the installation guide. To use MMPose 1.x, you need to have MMEngine, MMCV("mmcv>=2.0.0rc1"), and MMDet, which are all mentioned in Step 0 in the document.

**Comment by pkmnjourney** [comment]
> mim install "mmdet>=3.0.0rc0"

It seems the issue is with mmcv as when the code tries to call any of its scripts it fails.
Current mmcv version is ```2.0.0rc1```
```python mmpose/utils/collect_env.py``` returns:
```Traceback (most recent call last):```
  ```File "mmpose/utils/collect_env.py", line 3, in <module>```
    ```from mmcv.utils import get_git_hash```
```ImportError: cannot import name 'get_git_hash' from 'mmcv.utils' (C:\Users\Pkmnj\anaconda3\envs\openmmlab\lib\site-packages\mmcv\utils\__init__.py)```

And I still get ```ImportError: cannot import name 'Config' from 'mmcv'```

**Comment by xin-li-67** [comment]
> > > 
> > 
> > 
> > Hi, Please double check your environment with the installation guide. For example, to use MMPose 1.x, you need to have MMEngine, MMCV("mmcv>=2.0.0rc1"), and MMDet, which are all mentioned in Step 0 in the document.
> 
> It seems the issue is with mmcv as when the code tries to call any of its scripts it fails. Current mmcv version is `2.0.0rc1` `python mmpose/utils/collect_env.py` returns: `Traceback (most recent call last):` `File "mmpose/utils/collect_env.py", line 3, in <module>` `from mmcv.utils import get_git_hash` `ImportError: cannot import name 'get_git_hash' from 'mmcv.utils' (C:\Users\Pkmnj\anaconda3\envs\openmmlab\lib\site-packages\mmcv\utils\__init__.py)`
> 
> And I still get `ImportError: cannot import name 'Config' from 'mmcv'`
> 
> This is all after starting a new environment and following the recommended installation steps.

Which MMPose branch are you using??

**Comment by pkmnjourney** [comment]
> > > > 
> > > 
> > > 
> > > Hi, Please double check your environment with the installation guide. For example, to use MMPose 1.x, you need to have MMEngine, MMCV("mmcv>=2.0.0rc1"), and MMDet, which are all mentioned in Step 0 in the document.
> > 
> > 
> > It seems the issue is with mmcv as when the code tries to call any of its scripts it fails. Current mmcv version is `2.0.0rc1` `python mmpose/utils/collect_env.py` returns: `Traceback (most recent call last):` `File "mmpose/utils/collect_env.py", line 3, in <module>` `from mmcv.utils import get_git_hash` `ImportError: cannot import name 'get_git_hash' from 'mmcv.utils' (C:\Users\Pkmnj\anaconda3\envs\openmmlab\lib\site-packages\mmcv\utils\__init__.py)`
> > And I still get `ImportError: cannot import name 'Config' from 'mmcv'`
> > This is all after starting a new environment and following the recommended installation steps.
> 
> Which MMPose branch are you using??

master

**Comment by xin-li-67** [comment]
> > > > > 
> > > > 
> > > > 
> > > > Hi, Please double check your environment with the installation guide. For example, to use MMPose 1.x, you need to have MMEngine, MMCV("mmcv>=2.0.0rc1"), and MMDet, which are all mentioned in Step 0 in the document.
> > > 
> > > 
> > > It seems the issue is with mmcv as when the code tries to call any of its scripts it fails. Current mmcv version is `2.0.0rc1` `python mmpose/utils/collect_env.py` returns: `Traceback (most recent call last):` `File "mmpose/utils/collect_env.py", line 3, in <module>` `from mmcv.utils import get_git_hash` `ImportError: cannot import name 'get_git_hash' from 'mmcv.utils' (C:\Users\Pkmnj\anaconda3\envs\openmmlab\lib\site-packages\mmcv\utils\__init__.py)`
> > > And I still get `ImportError: cannot import name 'Config' from 'mmcv'`
> > > This is all after starting a new environment and following the recommended installation steps.
> > 
> > 
> > Which MMPose branch are you using??
> 
> master

master branch is not MMPose 1.x, please refer to the installation guide at this [URL](https://mmpose.readthedocs.io/en/latest/install.html#installation).
To use MMPose 1.x, please checkout to 1.x branch.

**Comment by pkmnjourney** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > Hi, Please double check your environment with the installation guide. For example, to use MMPose 1.x, you need to have MMEngine, MMCV("mmcv>=2.0.0rc1"), and MMDet, which are all mentioned in Step 0 in the document.
> > > > 
> > > > 
> > > > It seems the issue is with mmcv as when the code tries to call any of its scripts it fails. Current mmcv version is `2.0.0rc1` `python mmpose/utils/collect_env.py` returns: `Traceback (most recent call last):` `File "mmpose/utils/collect_env.py", line 3, in <module>` `from mmcv.utils import get_git_hash` `ImportError: cannot import name 'get_git_hash' from 'mmcv.utils' (C:\Users\Pkmnj\anaconda3\envs\openmmlab\lib\site-packages\mmcv\utils\__init__.py)`
> > > > And I still get `ImportError: cannot import name 'Config' from 'mmcv'`
> > > > This is all after starting a new environment and following the recommended installation steps.
> > > 
> > > 
> > > Which MMPose branch are you using??
> > 
> > 
> > master
> 
> master branch is not MMPose 1.x, please refer to the installation guide at this [URL](https://mmpose.readthedocs.io/en/latest/install.html#installation). To use MMPose 1.x, please checkout to 1.x branch.

Thank you. I was able to manage but even the URL you linked was missing a few commands like ```mim install mmengine```.
I got it working thank you.
