### ISSUE TITLE
MIm command not working

### ISSUE THREAD

**Issue by SoumyajitMukherjee-droid** [open-mmlab/mmpose#1917]
when i try to run "!mim download mmpose --config associative_embedding_hrnet_w32_coco_512x512  --dest ." in a cell in Jupyter notebook, it gives the following error.

"'mim' is not recognized as an internal or external command,
operable program or batch file."

i installed openmim "pip install openmim" it got successfully installed, and i have restarted the kernel as well, then also it throws the above error

**Comment by xin-li-67** [comment]
Hi, based on my personal experience, while running a jupyeter notebook locally, I have to change the kernel for my running file manually. Have you been able to check on this??

**Comment by Tau-J** [comment]
I'll close this issue due to no response. Please feel free to reopen it if need.

**Comment by Xray420** [comment]
I too face the same issue
'mim' is not recognized as an internal or external command, operable program or batch file.

Any solution?
