### ISSUE TITLE
Is there any code for visualizing the keypoint heatmap?

### ISSUE THREAD

**Issue by gjgjgjfff** [open-mmlab/mmpose#1920]

**Comment by jin-s13** [comment]
Here is a tutorial for visualization.
https://mmpose.readthedocs.io/en/1.x/user_guides/visualization.html

**Comment by qiuzhongwei-USTB** [comment]
Is there no --show-dir in tools/test.py for the current version?

**Comment by LjIA26** [comment]
I haven't been able to use it either. Is there any fix yet?

**Comment by jin-s13** [comment]
Are you using 1.x branch?

**Comment by gaominqi** [comment]
I want to use the model trained on master-branch to visualize the heatmap on the 1. x-branch. But when I try it, the prediction effect is very poor. How to convert the model trained on master-branch so that the 1. x branch can support it.
