### ISSUE TITLE
A question about inference

### ISSUE THREAD

**Issue by jojolee123** [open-mmlab/mmpose#1923]
I have trained a model. When I take it to test the pose estimation, why do I need the additional information of “center” and "scale" …?  Normally, I should input an image and the model can directly forward output the results

**Comment by ly015** [comment]
Hi, in a typical top-down pose estimation algorithm, human or object bounding boxes are first obtained from the input or by a detector, and the image area within the bbox is fed into the pose model. In MMPose, the bbox information is provided by the dataset during training. And to test the model on images, you need to provide the bboxes via a json file, or use a detection model to obtain bboxes from the image. Please check out our demo at https://mmpose.readthedocs.io/en/latest/demo.html#d-human-pose-top-down-image-demo
