### ISSUE TITLE
Update on ZoomNet whole body implementation?

### ISSUE THREAD

**Issue by felipe-parodi** [open-mmlab/mmpose#1926]
Hello, I wanted to know if/when ZoomNet would be added to mmpose. It seems it has been requested a couple of times over the past 2 years. Thank you!

**Comment by Tau-J** [comment]
Hi @jin-s13 , Could you help to give a reply?

**Comment by jin-s13** [comment]
Thanks for your interest in ZoomNet/ZoomNAS. 
We do have plans to support them in MMPose. However we are now busy on other projects. Sorry for the delay.
