### ISSUE TITLE
question about the result

### ISSUE THREAD

**Issue by ChenZhenGui** [open-mmlab/mmpose#1927]
![image](https://user-images.githubusercontent.com/52156532/211712815-d53e7c3d-a6e1-4d4b-b6cc-145e57b20c10.png)
Hello, I have a question about the training results. I want to know what the AP in it specifically represents. Is there any relationship between AP and the accuracy of Pose?

**Comment by jin-s13** [comment]
Please refer to https://cocodataset.org/#keypoints-eval
