### ISSUE TITLE
ConcatDataset

### ISSUE THREAD

**Issue by 17862923747** [open-mmlab/mmpose#1931]
ConcatDataset类的evaluate方法没有实现，这个问题在配置多数据集训练时必现，应该不是我的问题，我自己重写了这个方法可以了

**Comment by Ben-Louis** [comment]
您好，感谢使用 MMPose！能问一下您在使用目前的 ConcatDataset 时，程序会在哪个阶段（train/val/test）报错吗？因为多数据集一般用于训练，而模型测试大多时候还是在单个测试集上进行的，所以我们还没有支持在 ConcatDataset 上进行测试

**Comment by 17862923747** [comment]
您好，我在val的时候报错，我刚回复了下邮件说错了，请忽略

**Comment by 17862923747** [comment]
主要是我看到mmdet和mmcls都有实现，唯独mmpose没有实现，感觉还是有必要的

**Comment by Ben-Louis** [comment]
mmcls 和 mmdet 里面 `ConcatDataset.evaluate` 函数主要支持了两种测试形式：
1. 模型在各个子数据集上单独进行测试 (separate_eval)
2. 将所有子数据集的样本合并并用于测试 (只支持同类型的子数据集)

请问您主要会用到哪种测试形式呢？

**Comment by 17862923747** [comment]
您好，希望是都有，选一个的话是1，谢谢

**Comment by Ben-Louis** [comment]
功能1本身可以通过配置多个 config 的方式实现，所以我们短期内暂时没有添加这个功能的计划。如果您想要这个功能快速得到支持，可以考虑将您的实现通过 PR 的形式提交，我们会帮助您一起完善对这个新功能的支持

**Comment by 17862923747** [comment]
好的

**Comment by 17862923747** [comment]
您好，我提交了PR

**Comment by 17862923747** [comment]
您好，打扰您一下，TensorboardLoggerHook只显示了训练过程中的lr和momentum变化，我想加上loss，该怎么改呢？实在是没找到地方改，期待您回复，谢谢🙏
