### ISSUE TITLE
InterHand2.6M annotation file failed to download

### ISSUE THREAD

**Issue by Billccx** [open-mmlab/mmpose#1935]
Hi!

The download link for the [InterHand2.6m annotation](https://drive.google.com/drive/folders/1pWXhdfaka-J0fSAze0MsajN0VpZ8e8tO) seems to failed, could you please fix it or give another link?

Thanks in advance and looking forward to your reply.

**Comment by ly015** [comment]
Hi, you can download the annotation files from the [official site](https://mks0601.github.io/InterHand2.6M/) or [our link](https://download.openmmlab.com/mmpose/datasets/interhand2.6m_annotations.zip). Details about InterHand2.6m data preparation can be found in the [docs](https://mmpose.readthedocs.io/en/latest/tasks/3d_hand_keypoint.html#interhand2-6m).

**Comment by Billccx** [comment]
Thank you for such a quick reply!

**Comment by Billccx** [comment]
I noticed that this link is the annotation for 3D hand keypoints dataset. But what I need is the annotation for 2D hand keypoints dataset.  I wonder if they are identical?

**Comment by jin-s13** [comment]
Could you try the download link in 
https://mmpose.readthedocs.io/en/latest/tasks/2d_hand_keypoint.html#interhand2-6m ?

https://download.openmmlab.com/mmpose/datasets/interhand2.6m_annotations.zip

**Comment by Billccx** [comment]
@jin-s13  @ly015  I can download now. Thanks a lot!
