### ISSUE TITLE
Is there 2d keypoints dataset about the paper HuMMan: Multi-Modal 4D Human Dataset for Versatile Sensing and Modeling ？

### ISSUE THREAD

**Issue by APeiZou** [open-mmlab/mmpose#1946]
@ly015 @jin-s13   Hi, all, is there 2d keypoints dataset about the paper HuMMan: Multi-Modal 4D Human Dataset for Versatile Sensing and Modeling ？

**Comment by jin-s13** [comment]
Not supported yet in mmpose.

**Comment by APeiZou** [comment]
@jin-s13  Thanks  a lot
