### ISSUE TITLE
Questions about cross validation implementation on mmpose keypoint detection

### ISSUE THREAD

**Issue by cnr0724** [open-mmlab/mmpose#1948]
1. Why is cross validation not used on mmpose keypoint detection? Is there a specific reason to use limited image sets as a validation set?
2. If it is okay to use cross validation, then how should I implement the cross validation based on current structure of mmpose keypoint detection?

**Comment by Ben-Louis** [comment]
Many popular pose estimation benchmarks do not include cross-validation in their protocols. You may need to manually split train/val set in dataset annotation files for cross-validation.
