### ISSUE TITLE
Use of multiple losses in V1.0.0

### ISSUE THREAD

**Issue by LjIA26** [open-mmlab/mmpose#1951]
Hello,

I want to use two losses as follows:

Loss_1*0.5 + Loss_2*0.2

But it seems like I can only call for one loss at once? Maybe I am doing something wrong.

Also, can the logger also output both losses? 

Thank you!

**Comment by ly015** [comment]
Hi, you can refer to the [DSNT](https://github.com/open-mmlab/mmpose/blob/dev-1.x/configs/body_2d_keypoint/integral_regression/coco/ipr_res50_dsnt-8xb64-210e_coco-256x256.py#L54-L59) implementation in MMPose, which uses a loss wrapper to combine multiple losses. Please note that this part is still experimental and may change in the future.

**Comment by LjIA26** [comment]
Thank you, I am going to try that and update later

**Comment by LjIA26** [comment]
Thanks for your answer, It works, how do I make it print each loss separately? I only get one loss as result.

**Comment by ly015** [comment]
Please refer to the MMEngine documentation on logging: https://mmengine.readthedocs.io/zh_CN/latest/advanced_tutorials/logging.html

**Comment by Tau-J** [comment]
@LjIA26 In DSNTHead, we add the losses together [here](https://github.com/open-mmlab/mmpose/blob/c6de39ce8984e90f4f92690af30cae86e080a1fb/mmpose/models/heads/regression_heads/dsnt_head.py#L145) and update the logs by specifying:
```
losses.update(loss_kpt=loss)
```
you can modify this line as follows:
```
losses.updaste(loss1=loss_list[0])
losses.updaste(loss2=loss_list[1])
```
