### ISSUE TITLE
poor performance of HHRnet on demo page

### ISSUE THREAD

**Issue by BobDLA** [open-mmlab/mmpose#1954]
I run the demo on the https://platform.openmmlab.com/web-demo/demo/poseestimation
and got poor result as below image
![image](https://user-images.githubusercontent.com/3804610/216538213-0b3e1fc5-4e4a-44ca-8661-a161483bfbfe.png)

Is this the right performance?

**Comment by Ben-Louis** [comment]
To ensure quick inference, inputs consisting of low-quality and small-sized images are employed for online demo, resulting in poor performance. The pose estimated by [demo script](https://github.com/open-mmlab/mmpose/blob/master/demo/docs/2d_human_pose_demo.md#2d-human-pose-bottom-up-image-demo) using the same algorithm and the original image is displayed below
![vis_loge-numero-chambery-massage-casse-noisette](https://user-images.githubusercontent.com/26127467/216556610-4c942bd9-51d6-4949-9eed-0e8cdde84266.jpg)

**Comment by BobDLA** [comment]
> To ensure quick inference, inputs consisting of low-quality and small-sized images are employed for online demo, resulting in poor performance. The pose estimated by [demo script](https://github.com/open-mmlab/mmpose/blob/master/demo/docs/2d_human_pose_demo.md#2d-human-pose-bottom-up-image-demo) using the same algorithm and the original image is displayed below ![vis_loge-numero-chambery-massage-casse-noisette](https://user-images.githubusercontent.com/26127467/216556610-4c942bd9-51d6-4949-9eed-0e8cdde84266.jpg)

OK, thanks for the answer.
Btw, seems HHRNET has been removed from the 1.xx version.  Will it be added back soon?

**Comment by BobDLA** [comment]
> To ensure quick inference, inputs consisting of low-quality and small-sized images are employed for online demo, resulting in poor performance. The pose estimated by [demo script](https://github.com/open-mmlab/mmpose/blob/master/demo/docs/2d_human_pose_demo.md#2d-human-pose-bottom-up-image-demo) using the same algorithm and the original image is displayed below ![vis_loge-numero-chambery-massage-casse-noisette](https://user-images.githubusercontent.com/26127467/216556610-4c942bd9-51d6-4949-9eed-0e8cdde84266.jpg)

OK, thanks for the answer.
Btw, seems HHRNET has been removed from the 1.xx version.  Will it be added back soon?

**Comment by Ben-Louis** [comment]
> OK, thanks for the answer. Btw, seems HHRNET has been removed from the 1.xx version. Will it be added back soon?

In MMPose 1.x, AssociativeEmbedding has not been fully supported yet. However, it won't take long before HHRNET is added once AssociativeEmbedding is fully supported.

**Comment by BobDLA** [comment]
> > OK, thanks for the answer. Btw, seems HHRNET has been removed from the 1.xx version. Will it be added back soon?
> 
> In MMPose 1.x, AssociativeEmbedding has not been fully supported yet. However, it won't take long before HHRNET is added once AssociativeEmbedding is fully supported.

@Ben-Louis  OK, thanks, how about the PAF or PIFPAF supporting?

**Comment by ly015** [comment]
We don't have a plan to support PAF or PIFPAF in the immediate future. Of course, contributions from the community will always be welcome.

**Comment by BobDLA** [comment]
OK, thanks all
