### ISSUE TITLE
Pretrain simplebaseline 3d

### ISSUE THREAD

**Issue by testing715** [open-mmlab/mmpose#1955]
Hi! I'd like to pretrain simplebaseline 3d on my own dataset and get 3d skeletons through single RGB image. But I'm quite new to this. May I ask if there is a guide I can follow? What style should my own dataset be? Panoptic? Thanks a lot!

**Comment by ly015** [comment]
Hi, we provide SimpleBaseline3D implementations in MMPose and its config and checkpoint can be found [here](https://github.com/open-mmlab/mmpose/blob/master/configs/body/3d_kpt_sview_rgb_img/pose_lift/h36m/simplebaseline3d_h36m.md).

About the data preparation, you can refer to the guide for the [Human3.6M dataset](https://mmpose.readthedocs.io/en/latest/tasks/3d_body_keypoint.html#human3-6m).

And the inference of single-view 3D human pose can be found in the [demo](https://github.com/open-mmlab/mmpose/blob/master/demo/docs/3d_human_pose_demo.md). Please note that SimpleBaseline3D is a 2D-to-3D lifting method, so it needs an extra 2D pose estimation model to perform the complete inference process from RGB images.

**Comment by testing715** [comment]
Thanks for the quick response! 

For data preparation, do I have to prepare both pose annotations at full framerate (50 FPS) and downsampled framerate (10 FPS)? Or pose annotations at one single framerate is fine? 

And since I cannot access Human3.6m, I am a little bit confused about the format of skeleton file like "joint3d_stats.pkl" and the training file like "h36m_train.npz". Is there any other guide I can go through? 

For " it needs an extra 2D pose estimation model ", does it mean 2D joints are required for fine-tuning simplebaseline 3d?

Many thanks!
