### ISSUE TITLE
multi-data train

### ISSUE THREAD

**Issue by whffams2** [open-mmlab/mmpose#1962]
Thank you very much for your work, I have encountered some problems when using mmpose, I would like to ask, if I want to use multiple datasets for training. (I mean I want to use both coco_train_2017 and coco_unlabeled_2017 while training). how should I do it?

**Comment by Ben-Louis** [comment]
Thanks for using MMPose. Currently, to train models with multiple datasets, you'll need to 
1. Define the dataset class for any undefined datasets.
2. Use the `CombinedDataset` wrapper in the `dev-1.x` branch to combine each individual dataset. Please check out the [doc](https://mmpose.readthedocs.io/en/dev-1.x/user_guides/prepare_datasets.html#combineddataset) or [coco_aic_config](https://github.com/open-mmlab/mmpose/blob/dev-1.x/configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_hrnet-w32_8xb64-210e_coco-aic-256x192-combine.py) example config for further information.

**Comment by whffams2** [comment]
> 

Thank you so much, I'll try it later.

**Comment by whffams2** [comment]
> Thanks for using MMPose. Currently, to train models with multiple datasets, you'll need to
> 
> 1. Define the dataset class for any undefined datasets.
> 2. Use the `CombinedDataset` wrapper in the `dev-1.x` branch to combine each individual dataset. Please check out the [doc](https://mmpose.readthedocs.io/en/dev-1.x/user_guides/prepare_datasets.html#combineddataset) or [coco_aic_config](https://github.com/open-mmlab/mmpose/blob/dev-1.x/configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_hrnet-w32_8xb64-210e_coco-aic-256x192-combine.py) example config for further information.

Excuse me again, my description last time may be a little unclear. I mean I want to do a semi-supervised task and need to use both labeled and unlabeled data, how should I read both kinds of data at the same time?
