### ISSUE TITLE
How to use smoothnet in 2D pose humanpose demo

### ISSUE THREAD

**Issue by AgileChen3** [open-mmlab/mmpose#1965]

**Comment by ly015** [comment]
For now, we only support SmoothNet for 3D pose using Human3.6M dataset. Please refer to the [project page](https://ailingzeng.site/smoothnet) for more applications.

**Comment by guker** [comment]
why? but the author say that smoothnet support 2d pose estimation

**Comment by ly015** [comment]
Yes, SmoothNet is a general smoothing method applicable to both 2D and 3D pose estimation. It's not fully integrated into MMPose so far. The models and checkpoints for 2D pose estimation can be found on the official project page and should be able to be applied in MMPose demos in a similar way as the 3D SmoothNet.
