### ISSUE TITLE
How to get the 2d human keypoints coordinates？

### ISSUE THREAD

**Issue by taro-liu** [open-mmlab/mmpose#1966]
我想利用深度相机进行人体双耳关键点的追踪与定位，需要获得双耳的二维坐标，请问相关代码和双耳id在什么地方？

**Comment by ly015** [comment]
We recommend using MMPose 1.x version. Facial landmark models can be found at: https://mmpose.readthedocs.io/en/dev-1.x/model_zoo/face_2d_keypoint.html, and the keypoint id can be found in the metainfo of the corresponding dataset at: https://github.com/open-mmlab/mmpose/tree/dev-1.x/configs/_base_/datasets
