### ISSUE TITLE
semi-supervised train 

### ISSUE THREAD

**Issue by whffams2** [open-mmlab/mmpose#1967]
Thanks a lot for your work, I would like to ask a question. I want to conduct a semi-supervised experiment, but I have a problem with the dataload part. How should I load and use unsupervised and supervised data at the same time?

**Comment by ly015** [comment]
Hi, thanks for using MMPose. You may need to implement a custom dataset for this purpose. One approach is to pack both supervised and unsupervised parts into one data sample (with different field names). Another is to load only one data sample, together with an extra label indicating it's supervised data or unsupervised data.

You can refer to the implementation of [VideoPose3D](https://github.com/open-mmlab/mmpose/blob/master/configs/body/3d_kpt_sview_rgb_vid/video_pose_lift/h36m/videopose3d_h36m_27frames_fullconv_semi-supervised.py) in MMPose which involves semi-supervised learning.

**Comment by whffams2** [comment]
> Hi, thanks for using MMPose. You may need to implement a custom dataset for this purpose. One approach is to pack both supervised and unsupervised parts into one data sample (with different field names). Another is to load only one data sample, together with an extra label indicating it's supervised data or unsupervised data.
> 
> You can refer to the implementation of [VideoPose3D](https://github.com/open-mmlab/mmpose/blob/master/configs/body/3d_kpt_sview_rgb_vid/video_pose_lift/h36m/videopose3d_h36m_27frames_fullconv_semi-supervised.py) in MMPose which involves semi-supervised learning.

Thanks for your help, I'll try it later
