### ISSUE TITLE
about pth2onnx model input shape

### ISSUE THREAD

**Issue by IniAully** [open-mmlab/mmpose#1970]
I convert model hrnet_w32_coco_512x512 to onnx, and set shape=(1, 3, 512, 512). 
But I found that the shape of data preparation is not fixed. 
Should I set dynamic shape?

**Comment by Tau-J** [comment]
This seems not an MMPose-related issue. I think it depends on your application scenarios and the algorithm you use. For instance, it doesn't matter when you use the heatmap-based method.
