### ISSUE TITLE
Image size IndexError on inference run

### ISSUE THREAD

**Issue by andpuc23** [open-mmlab/mmpose#1977]
I am trying to run inference script (demo/top_down_img_demo.py) on CID and then DEKR models with COCO dataset, to check the pipeline is actually working in prediction mode. Used the provided config (here and further for CID): configs/body/2d_kpt_sview_rgb_img/cid/coco/hrnet_w48_coco_512x512.py (didn't change anything)

`python demo/top_down_img_demo.py \
configs/body/2d_kpt_sview_rgb_img/cid/coco/hrnet_w48_coco_512x512.py \
https://download.openmmlab.com/mmpose/pretrain_models/hrnet_w48-8ef0771d.pth \
--img-root data/coco/val2017/ \
--json-file data/coco/annotations/person_keypoints_val2017.json \
--out-img-root data/coco/predictions/`

The 1-st problem I encounter is that config provides image_size as an int (512 in the case), and TopDownTransform calculates `aspect_ratio = image_size[0] / image_size[1]`

OK, I change image_size to [512, 512]  and heatmap_size to [128, 128] in config, get the next error:

Traceback (most recent call last):
  File "demo/top_down_img_demo.py", line 130, in <module>
    main()
  File "demo/top_down_img_demo.py", line 99, in main
    pose_results, returned_outputs = inference_top_down_pose_model(
  File "/home/student/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/misc.py", line 340, in new_func
    output = old_func(*args, **kwargs)
  File "/home/student/.local/share/Trash/files/mmpose/mmpose/mmpose/apis/inference.py", line 392, in inference_top_down_pose_model
    poses, heatmap = _inference_single_pose_model(
  File "/home/student/.local/share/Trash/files/mmpose/mmpose/mmpose/apis/inference.py", line 267, in _inference_single_pose_model
    result = model(
  File "/home/student/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/student/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 119, in new_func
    return old_func(*args, **kwargs)
  File "/home/student/.local/share/Trash/files/mmpose/mmpose/mmpose/models/detectors/cid.py", line 141, in forward
    return self.forward_test(
  File "/home/student/.local/share/Trash/files/mmpose/mmpose/mmpose/models/detectors/cid.py", line 228, in forward_test
    assert img.size(0) == 1
AssertionError

Printing img.shape in cid.py 's forward_test() gives `torch.Size([2, 427, 640, 3])`, which means that there is a batch of 2 images passed to processing. My next question is how to control batch size in this case, since config doesn't seem to have such an option.
OK, I fix that by throwing away 2-nd image in a batch:
`        if img.shape[0] > 1:
        	img = img[0]
        	img = img[None, :,:,:]`
(I know this can be done neater, for now I just want it to work)
and picking list containing 1-st item of img_metas instead of the original list.

Next I get such error:
Traceback (most recent call last):
  File "demo/top_down_img_demo.py", line 130, in <module>
    main()
  File "demo/top_down_img_demo.py", line 99, in main
    pose_results, returned_outputs = inference_top_down_pose_model(
  File "/home/viacheslav/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/misc.py", line 340, in new_func
    output = old_func(*args, **kwargs)
  File "/home/viacheslav/mmpose/mmpose/apis/inference.py", line 392, in inference_top_down_pose_model
    poses, heatmap = _inference_single_pose_model(
  File "/home/viacheslav/mmpose/mmpose/apis/inference.py", line 259, in _inference_single_pose_model
    data = test_pipeline(data)
  File "/home/viacheslav/mmpose/mmpose/datasets/pipelines/shared_transform.py", line 107, in __call__
    data = t(data)
  File "/home/viacheslav/mmpose/mmpose/datasets/pipelines/shared_transform.py", line 178, in __call__
    meta[key_tgt] = results[key_src]
KeyError: 'flip_index'

No idea what to do here, pls help

enironment:
/home/xxx/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
sys.platform: linux
Python: 3.8.16 (default, Jan 17 2023, 23:13:24) [GCC 11.2.0]
CUDA available: True
GPU 0: NVIDIA GeForce GTX 1080
CUDA_HOME: None
GCC: gcc (Ubuntu 5.5.0-12ubuntu1) 5.5.0 20171010
PyTorch: 1.10.2
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.11.3
OpenCV: 4.7.0
MMCV: 1.7.1
MMCV Compiler: GCC 9.3
MMCV CUDA Compiler: 11.3
MMPose: 0.29.0+4c397f2

**Comment by ly015** [comment]
Hi, thanks for using MMPose. CID and DEKR follow the bottom-up paradigm, so please use the script `demo/bottom_up_img_demo.py`. Details can be found at https://github.com/open-mmlab/mmpose/blob/master/demo/docs/2d_human_pose_demo.md#2d-human-pose-bottom-up-image-demo.

**Comment by ly015** [comment]
There is a lack of demo guides for each model indeed. We will consider adding them to the model README files in the future.

**Comment by andpuc23** [comment]
Thank you @ly015! I found an error, and now it works.
However, as you noticed, more guides would be much appreciated!
