### ISSUE TITLE
Why exchange the y and z-axis, and then reverse the direction of x and z-axis of the 3D pose coordinates?

### ISSUE THREAD

**Issue by jorislimonier** [open-mmlab/mmpose#1978]
Hello, in [line 451](https://github.com/open-mmlab/mmpose/blob/master/demo/body3d_two_stage_video_demo.py#L451) and following of the demo file (code below), you exchange the y and z-axis, and then reverse the direction of x and z-axis of the 3D pose coordinates.\
Could you explain why this happens?
```python
        # Pose processing
        pose_lift_results_vis = []
        for idx, res in enumerate(pose_lift_results):
            keypoints_3d = res['keypoints_3d']
            # exchange y,z-axis, and then reverse the direction of x,z-axis
            keypoints_3d = keypoints_3d[..., [0, 2, 1]]
            keypoints_3d[..., 0] = -keypoints_3d[..., 0]
            keypoints_3d[..., 2] = -keypoints_3d[..., 2]
            # rebase height (z-axis)
            if args.rebase_keypoint_height:
                keypoints_3d[..., 2] -= np.min(
                    keypoints_3d[..., 2], axis=-1, keepdims=True)
            res['keypoints_3d'] = keypoints_3d
```

Thanks in advance.

**Comment by ly015** [comment]
Hi, thanks for using MMPose. These codes convert the coordinates from the camera system to the world system.

**Comment by jorislimonier** [comment]
@ly015 , thank you for your response.

I am not too experienced with this field. Would you mind elaborating on what this means? Thanks!

**Comment by ly015** [comment]
In these demos, the model prediction is keypoint coordinates in the camera system, which is usually like this:
![image](https://user-images.githubusercontent.com/15977946/220029602-94761834-8273-4ada-bb04-8439c8fd11ff.png)

To visualize the predicted results in matplotlib, we would like to use a different coordinate system where the x-y parallels to the horizontal plane and the z-axis parallels to the vertical direction. And the code above will do the conversion.

**Comment by jorislimonier** [comment]
Thank you for the detailed answer. Makes sense now!
