### ISSUE TITLE
在coco-wholebody-hand上如何使用ap和AR评估？这个目前是pck auc

### ISSUE THREAD

**Issue by mywordwin** [open-mmlab/mmpose#1981]
![image](https://user-images.githubusercontent.com/39481420/219943263-d49d4eb4-3bf9-455e-a401-49f461f8211f.png)

**Comment by ly015** [comment]
For now, the COCO-Wholebody-Hand dataset only supports evaluation metrics AUC, EPE, and PCK (see [hear](https://github.com/open-mmlab/mmpose/blob/master/mmpose/datasets/datasets/hand/hand_coco_wholebody_dataset.py#L164)). To use other metrics like AP/AR, you will need to:

- Extend the `evaluate()` method of the dataset class to support the new metric. The implementation of the [COCO dataset](https://github.com/open-mmlab/mmpose/blob/master/mmpose/datasets/datasets/top_down/topdown_coco_dataset.py#L224) can be a good reference
- Modify the evaluation config to use the new metric like [here](https://github.com/open-mmlab/mmpose/blob/master/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w32_coco_256x192.py#L5)

**Comment by mywordwin** [comment]
OK, got it.
May I ask how to get the specific results of the hand like the test results on coco-wholebody, for example, if  #i want to get the specific items of the hand, AP, AP50, AP75, AP (M), AP (L), AR, AR50....
![image](https://user-images.githubusercontent.com/39481420/220553857-edf451dc-38da-4036-ac8c-7053402ee080.png)
