### ISSUE TITLE
Do you have plans to implement yolov7-pose

### ISSUE THREAD

**Issue by APeiZou** [open-mmlab/mmpose#1987]
@openmmlab-bot Hi, All，Do you have plans to implement yolov7-pose？

**Comment by Ben-Louis** [comment]
Thanks for your interest. At this moment, we have not yet made plans to implement yolov7-pose. However, we greatly appreciate any contributions that the community would like to make towards this endeavor

**Comment by APeiZou** [comment]
@Ben-Louis Thank you for your reply
