### ISSUE TITLE
MMCV==1.7.1 is used but incompatible with v0.29.0 and v1.0.0b0

### ISSUE THREAD

**Issue by sunyc11** [open-mmlab/mmpose#1989]
Thanks for your error report and we appreciate it a lot.
If you feel we have helped you, give us a STAR! :satisfied:

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
I found mmpose v0.29.0 requires mmcv<=1.7.0, and v1.0.0b0 requires mmcv>=2.0.0rc0, so I can't use mmcv==1.7.1

**Comment by ly015** [comment]
Thanks for your feedback. MMPose v0.29.0 is compatible with MMCV up to v1.7.0. You can install MMPose from the source code of the latest master branch, which is compatible with MMCV v1.7.1. Please find the [document](https://mmpose.readthedocs.io/en/latest/install.html#installation) for installing MMPose from the source code.

To access the latest features of MMPose, we recommend using [MMPose v1.0](https://github.com/open-mmlab/mmpose/tree/dev-1.x), which works with MMCV v2.0.0. See our [v1.0 documents](https://mmpose.readthedocs.io/en/dev-1.x/) for more information.

And the compatibility information of MMCV/MMEngine will be updated in #1990 and #1991.

**Comment by sunyc11** [comment]
> Thanks for your feedback. MMPose v0.29.0 is compatible with MMCV up to v1.7.0. You can install MMPose from the source code of the latest master branch, which is compatible with MMCV v1.7.1. Please find the [document](https://mmpose.readthedocs.io/en/latest/install.html#installation) for installing MMPose from the source code.
> 
> To access the latest features of MMPose, we recommend using [MMPose v1.0](https://github.com/open-mmlab/mmpose/tree/dev-1.x), which works with MMCV v2.0.0. See our [v1.0 documents](https://mmpose.readthedocs.io/en/dev-1.x/) for more information.
> 
> And the compatibility information of MMCV/MMEngine will be updated in #1990 and #1991.

OK，thanks for your reply
