### ISSUE TITLE
Processing Human3.6m

### ISSUE THREAD

**Issue by testing715** [open-mmlab/mmpose#1997]
Hi! Thanks for the great work! I'm now fine-tuning the simplebaseline 3D for 3D pose estimation and preparing my own dataset in human3.6m style. I have run preprocess_h36m.py and got multiple cdf. file now. May I ask how they go to these files required for data preparation like below?
        |   |   ├── h36m_test.npz
        |   |   ├── h36m_train.npz
        |   |   ├── joint2d_rel_stats.pkl
        |   |   ├── joint2d_stats.pkl
        |   |   ├── joint3d_rel_stats.pkl
        |   |   `── joint3d_stats.pkl

Thank you so much!

**Comment by Ben-Louis** [comment]
Hi, thanks for using MMPose. The `npz` and `pkl` files you're referring to are created by the generate_annotations function which is invoked at https://github.com/open-mmlab/mmpose/blob/cbac8809f9aaf9a06d12739b1000eb9fc7b9a69d/tools/dataset/preprocess_h36m.py#L436 
Please note that the `preprocess_h36m.py` script relies on the `'S1', 'S5', 'S6', 'S7', 'S8', 'S9', 'S11'` splits. If your dataset's file structure differs from that of H36M, the program may encounter difficulties processing your data.
