### ISSUE TITLE
left and right points

### ISSUE THREAD

**Issue by SylvainArd** [open-mmlab/mmpose#1998]
hello,
is it serious if we invert the left and right points in the masks ?
Thank you
Best regards

**Comment by Ben-Louis** [comment]
Sorry, could you please clarify what you mean by 'invert the points in the masks'?

**Comment by SylvainArd** [comment]
could the left and right points be inverted in the labelisation ?
Sylvain Ard
0549507724
0778380991
***@***.***
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers

**Comment by Ben-Louis** [comment]
Sorry, but I am having difficulty understanding your question. If you are asking whether swapping the original left point with the right point (e.g. left hand with right hand) would affect the performance of the model, I believe it would not be an issue. However, if you could provide more clarity or context regarding your doubt, I would be happy to assist you further.
