### ISSUE TITLE
Is the detection of each keypoint type independent?

### ISSUE THREAD

**Issue by SylvainArd** [open-mmlab/mmpose#1999]
hello,
does the detection of points of a certain type take into account the position of points of other types or is the detection of each type of point independent?
thank you
best regards

**Comment by Ben-Louis** [comment]
Hi, thanks for your interest. In my personal opinion, many pose estimation models are designed to detect each point type independently, and they typically lack explicit modules for enabling interaction among different types of points. Nevertheless, these models can still infer point locations by considering both the local features around each point and the overall structure of the object.

**Comment by ly015** [comment]
BTW, I modified the issue title so it can be reached easily by others who are interested in this question :)

**Comment by SylvainArd** [comment]
ok thank you
Sylvain Ard
0549507724
0778380991
***@***.***
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers
