### ISSUE TITLE
code for several points per type detection

### ISSUE THREAD

**Issue by SylvainArd** [open-mmlab/mmpose#2000]
Hello,
have you a code for example on Github for multiple points per type detection please ?
Thank you
Best regards

**Comment by Ben-Louis** [comment]
Hi, thanks for your interest. You might want to consider using bottom-up methods that first detect all the points and then group them together. These methods can detect multiple points for each type and include techniques such as [Associative Embedding](https://github.com/open-mmlab/mmpose/tree/master/configs/body/2d_kpt_sview_rgb_img/associative_embedding), [DEKR](https://github.com/open-mmlab/mmpose/tree/master/configs/body/2d_kpt_sview_rgb_img/dekr) and [CID](https://github.com/open-mmlab/mmpose/tree/master/configs/body/2d_kpt_sview_rgb_img/cid/coco).

**Comment by ly015** [comment]
Maybe top-down approaches can also be adapted for this task. In the typical top-down paradigm, the model is expected to predict a gaussian heatmap for each keypoint type, and the peak of the heatmap is the predicted location of that keypoint. Instead, you can also train the model to predict a multimodal heatmap for a keypoint type with an arbitrary number of keypoints. And during inference, the model can predict multiple locations by selecting heatmap peaks above a threshold.

**Comment by SylvainArd** [comment]
OK thank you for your answer, but in the coco labelisation format there is
only one keypoint per type, so we must change the original format too, have
you a snippet for both modifications to send to me please ?
Sylvain Ard
0549507724
0778380991
***@***.***
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers


Le jeu. 23 févr. 2023 à 04:16, Yining Li ***@***.***> a
écrit :

**Comment by SylvainArd** [comment]
thank you but I am unable to code this, perhaps it could interest other
people and that you can code it ? imagine a new annotation format and code
the program ?
Sylvain Ard
0549507724
0778380991
***@***.***
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers


Le jeu. 23 févr. 2023 à 15:46, Yining Li ***@***.***> a
écrit :

**Comment by ly015** [comment]
Sorry, this is not within our immediate plan. We can leave this to the community and if someone is interested, we would like to provide help.

**Comment by SylvainArd** [comment]
How much do you want to be paid to do it ?

**Comment by ly015** [comment]
Well, we don't have the plan to undertake outsourcing projects. Someone in the community may do, and we are always willing to help.
