### ISSUE TITLE
RuntimeError: mmpose is not installed. Please install it first.

### ISSUE THREAD

**Issue by Get-it-right** [open-mmlab/mmpose#2001]
Thanks for your error report and we appreciate it a lot.
If you feel we have helped you, give us a STAR! :satisfied:

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

I install mmpose directly in the remote server (without virtual environment), and there is no error report. when I try to test the installment using 'mim download mmpose --config associative_embedding_hrnet_w32_coco_512x512  --dest .', the error report is 'RuntimeError: mmpose is not installed. Please install it first.'

**Comment by ly015** [comment]
Could you please run `pip show mmpose` to check the installation?

**Comment by Tau-J** [comment]
l'll close this issue due to no response. Please feel free to reopen it if need.

**Comment by nanshanvv** [comment]
It seem that I have same question.When I follow the document, the following occurs.
![image](https://user-images.githubusercontent.com/77189526/231341466-3cb8261b-80d0-4fcc-8e2a-11f94496088b.png)
It shows: Requirement already satisfied
But when I run `pip show mmpose`
![image](https://user-images.githubusercontent.com/77189526/231341807-531f56ec-3d43-4919-8d3c-a0781a41ca4d.png)

**Comment by chemingmei** [comment]
我遇到了同样的问题，应该是下载过程中丢失了一些东西，把mmpose删掉重新下载一遍就好了
