### ISSUE TITLE
how to modify the fps in "demo/body3d_ two_ stage_ video_ Demo.py "

### ISSUE THREAD

**Issue by gaominqi** [open-mmlab/mmpose#2003]
When I run "demo/body3d_ two_ stage_ video_ Demo.py ", the fps in the process is 50. I want to modify this parameter. What should I do?
For example, in the following figure, a 47-second video is divided into 2357 pictures for processing, so fps=50, and I want to change fps to 10
![image](https://user-images.githubusercontent.com/28819516/220816451-420a2130-02a2-472e-832a-3be38fade466.png)

**Comment by Ben-Louis** [comment]
Hi, thanks for using MMPose. If you would like to specify the frames per second (fps) in the "demo/body3d_two_stage_video_demo.py", the easiest method is to manually set the desired value to the `fps` parameter that initializes [this VideoWriter](https://github.com/open-mmlab/mmpose/blob/master/demo/body3d_two_stage_video_demo.py#L491-L494). If you wish to conveniently adjust the fps for multiple runs, you can add a new argument called `fps` in the `argparser` and assign it to the aforementioned VideoWriter.

**Comment by ly015** [comment]
Please note that the `fps` in [body3d_two_stage_video_demo.py](https://github.com/open-mmlab/mmpose/blob/master/demo/body3d_two_stage_video_demo.py#L390) only controls the frame rate of the output videos that visualize the results, and it will not affect the sampling rate during video reading, which I assume is what you actually want. To sample from the input frames, you may need to add a few codes [here](https://github.com/open-mmlab/mmpose/blob/master/demo/body3d_two_stage_video_demo.py#L332) to skip unused frames.

**Comment by gaominqi** [comment]
Thank you for your answer, which has helped me a lot.
