### ISSUE TITLE
Demo error with update

### ISSUE THREAD

**Issue by LjIA26** [open-mmlab/mmpose#2004]
Thanks for your error report and we appreciate it a lot.
If you feel we have helped you, give us a STAR! :satisfied:

Hello, thanks for this framework. I just updated mmpose and I started getting this error. 

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

- What command or script did you run?

```
D:\toolkit\mmpose>python demo/image_demo.py  "data\results\images-test\PIC-2000.jpg"  configs/plantsv5.py train-F24/epoch_50.pth --draw-heatmap
```

- What config did you run?

```
Latest
```

- Did you make any modifications on the code or config? Did you understand what you have modified?
- What dataset did you use?

**Environment**
```
TorchVision: 0.13.1+cu113
OpenCV: 4.7.0
MMEngine: 0.5.0
MMPose: 1.0.0rc0+c6de39c
```

**Error traceback**

If applicable, paste the error traceback here.

```
02/24 23:38:02 - mmengine - WARNING - The "model" registry in mmpose did not set import location. Fallback to call `mmpose.utils.register_all_modules` instead.
02/24 23:38:04 - mmengine - WARNING - The "KEYPOINT_CODECS" registry in mmpose did not set import location. Fallback to call `mmpose.utils.register_all_modules` instead.
Loads checkpoint by local backend from path: train-F24/epoch_5.pth
02/24 23:38:05 - mmengine - WARNING - The "visualizer" registry in mmpose did not set import location. Fallback to call `mmpose.utils.register_all_modules` instead.
C:\Users\LJ\anaconda3\envs\toolkit\lib\site-packages\mmengine\visualization\visualizer.py:163: UserWarning: `Visualizer` backend is not initialized because save_dir is None.
  warnings.warn('`Visualizer` backend is not initialized '
02/24 23:38:05 - mmengine - WARNING - The "transform" registry in mmpose did not set import location. Fallback to call `mmpose.utils.register_all_modules` instead.
Traceback (most recent call last):
  File "D:\toolkit\mmpose\demo\image_demo.py", line 67, in <module>
    main(args)
  File "D:\toolkit\mmpose\demo\image_demo.py", line 49, in main
    results = inference_topdown(model, args.img)
  File "d:\tool\mmpose\mmpose\apis\inference.py", line 175, in inference_topdown
    data.append(pipeline(_data))
  File "C:\Users\LJ\anaconda3\envs\toolkit\lib\site-packages\mmengine\dataset\base_dataset.py", line 58, in __call__
    data = t(data)
  File "C:\Users\LJ\anaconda3\envs\toolkit\lib\site-packages\mmcv\transforms\base.py", line 12, in __call__
    return self.transform(results)
  File "d:\tool\mmpose\mmpose\datasets\transforms\common_transforms.py", line 947, in transform
    raise ValueError(
ValueError: GenerateTarget requires 'transformed_keypoints' or 'keypoints' in the results.
```

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by Ben-Louis** [comment]
Hi, thanks for using MMPose. Could you please provide more information regarding the `test_pipeline` in your config? Typically, during inference, `GenerateTarget` should not be included in the pipeline.

**Comment by LjIA26** [comment]
@Ben-Louis Thank you for your answer 
```
test_pipeline = [
    dict(type='LoadImage', file_client_args={{_base_.file_client_args}}),
    dict(type='GetBBoxCenterScale', padding=2),
    dict(type='TopdownAffine', input_size=codec['input_size']),
    dict(type='GenerateTarget', target_type='heatmap', encoder=codec),
    dict(type='PackPoseInputs')
]
```

**Comment by Ben-Louis** [comment]
I think you can remove the `'GenerateTarget'` component in `test_pipeline` and try again. This transform is commonly used to create learning targets for models during the training phase, and it requires ground truth labels which are not usually applicable during inference.
