### ISSUE TITLE
custom dataset 

### ISSUE THREAD

**Issue by alaa-shubbak** [open-mmlab/mmpose#2008]
Hello , 

Thanks for your effort and work. 

I only have two questions regard using my custom dataset ,which is have some similarity to coco keypoint dataset but not typical. 

my dataset is as bellow: 
either i have a json file for each image has info about image name , id , heigh,width and annotation. 
or have one json file in the following format
![Screenshot from 2023-02-27 14-32-56](https://user-images.githubusercontent.com/10245810/221586325-053a0dbd-0b68-4d78-a6d5-3a3e2c7d3b71.png)

as you may see, it has a separated image field for each image of the dataset. so i don't have a image field include all images in my dataste. 

my questions are 
first : can i use coco config dataset  [coco.py](https://github.com/open-mmlab/mmpose/blob/master/configs/_base_/datasets/coco.py) to train a model with my dataset and  find keypoint in my objects? i am working with object totally different from human. 

here another presentation for my annotation in json file: 
![Screenshot from 2023-02-27 14-33-19](https://user-images.githubusercontent.com/10245810/221588224-701d47df-027b-41c9-8ca9-154c9a19fa80.png)

sceond : I read through the repository that i can use the bottom-up approach for case which has annotation as keypoint without boundary boxes. is it true?

**Comment by ly015** [comment]
Thanks for using MMPose. Regarding your questions:
1. I think the best practice is to re-organize your annotation file in the standard COCO format, so you can reuse most of the code in MMPose without the need for modification, like the code of data pipe-processing, models, and evaluation. And please note that the [coco.py](https://github.com/open-mmlab/mmpose/blob/master/configs/_base_/datasets/coco.py) you mentioned is a metainfo description of the original COCO dataset. It's part of the dataset configuration, instead of implementation, and you would need to modify it according to your own data. The actual dataset implementation can be found at https://github.com/open-mmlab/mmpose/tree/master/mmpose/datasets/datasets. A tutorial on using custom dataset in MMPose can be found at: https://mmpose.readthedocs.io/en/latest/tutorials/2_new_dataset.html
2. Bottom-up approaches do not need an extra detection model in inference. However, to train a bottom-up model, it may still need the bounding box information in evaluation (if you use COCO AP/AR metrics). So if there is no bounding box annotation in your dataset, you can simply generate bonding boxes from keypoints (e.g. use the minimum bounding rectangle).

**Comment by alaa-shubbak** [comment]
Thank you for reply. 
I try to train a model with my new dataset. 
I use a model of bottom up approach similar to this [one](https://github.com/open-mmlab/mmpose/blob/master/configs/body/2d_kpt_sview_rgb_img/dekr/coco/hrnet_w48_coco_640x640.py)
i only changed  the data directory  and the joint info as bellow
```
channel_cfg = dict(
# change the # of keypoints 
    dataset_joints=4,
    dataset_channel=[
        [0, 1, 2, 3],
    ],
    inference_channel=[
        0, 1, 2, 3
    ])

```
as my dataset has only 4 keypoints , 3 joint lines (skeleton lines).

Unfortunately , I got this error message: 
(KeyError: "BottomUpCocoDataset: 'id'")
![error_mmpopse](https://user-images.githubusercontent.com/10245810/222213382-f63cf851-4687-4e78-a28b-ca2438c99d07.png)
I am not sure if this error is from the annotation format or from another stuff. 
I modified my dataset in a format similar to coco dataset. 
it has all the field with coco format mentioned in the [website](https://mmpose.readthedocs.io/en/latest/tutorials/2_new_dataset.html) expected the bbox and the id terms in the annotation. 

is this error because of such miss matching? as i don't have the 'id' info for each annotation part. ? 
if it is so , can i make the id = image_id ? 

another point ; you mentioned that in Bottom-up approaches i can generate bonding boxes from keypoints, can you please provide me with some code for that?

**Comment by alaa-shubbak** [comment]
i did the change in the dataset format. 
I added the id for each annotation ,and add bbox for object
unfortunately , i got another error as bellow: 

TypeError: BottomUpCocoDataset: string indices must be integers

![error2](https://user-images.githubusercontent.com/10245810/222278011-b6c59d69-ddc9-4374-aff2-66318244ab51.png)

the bbox format is (x_top_left,y_top_left,width,height) which is similar to coco format. 
what shall i do? and what does such error means?

**Comment by alaa-shubbak** [comment]
I think the problem in the format of my dataset. 
can some one check it for me. 

here is a part of test.json file
![sample_of_dataset_2](https://user-images.githubusercontent.com/10245810/222539415-071c08e0-7c8b-47f1-8e94-fef8945764be.png)


![sample_of_my_dataset](https://user-images.githubusercontent.com/10245810/222539386-df1931cf-fd4e-4752-9c33-c299983f71f4.png)

is there any program (script or code) that help to check if the format of my dataset is correct or not? 
looking forward to any suggestion ,as i try my dataset with three config 
1. res50_exc_192x192.py
2. hrnet_w32_coco_256x192.py
3. hrnet_w48_coco_ex_640x640.py

, one using coco dataset ,and other using a new dataset config after register it . unfortunately all of them give the same error message.

**Comment by alaa-shubbak** [comment]
any help on this please !
i have a look on dataset of animals/fly.

![fly_ann](https://user-images.githubusercontent.com/10245810/222977702-497819aa-bb7d-42d6-a8e8-9b723e7a1a6f.jpg)


I try it  and still got the same error.

**Comment by alaa-shubbak** [comment]
this is the full error 

```
loading annotations into memory...
Done (t=0.00s)
creating index...
Traceback (most recent call last):
  File "/home/lem/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "/home/lem/mmpose/mmpose/datasets/datasets/machines/excavator_datasetn.py", line 62, in __init__
    super().__init__(
  File "/home/lem/mmpose/mmpose/datasets/datasets/base/kpt_2d_sview_rgb_img_top_down_dataset.py", line 85, in __init__
    self.coco = COCO(ann_file)
  File "/home/lem/miniconda3/envs/openmmlab/lib/python3.8/site-packages/xtcocotools/coco.py", line 100, in __init__
    self.createIndex()
  File "/home/lem/miniconda3/envs/openmmlab/lib/python3.8/site-packages/xtcocotools/coco.py", line 126, in createIndex
    cats[cat['id']] = cat
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 201, in <module>
    main()
  File "tools/train.py", line 176, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/lem/mmpose/mmpose/datasets/builder.py", line 87, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/lem/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: ExcavatorDatan: string indices must be integers

```

<img width="448" alt="image" src="https://user-images.githubusercontent.com/10245810/222987733-ea37d3d6-a6fd-4748-8964-e252873a9808.png">

**Comment by alaa-shubbak** [comment]
is it necessary to have segmentation part in the annotation json file of the training data?

**Comment by alaa-shubbak** [comment]
I think i found already the answer
[here](https://github.com/open-mmlab/mmpose/issues/1293)

Thank you very much. you can close this issue now.
