### ISSUE TITLE
workers_per_gpu

### ISSUE THREAD

**Issue by SylvainArd** [open-mmlab/mmpose#2009]
Hello,
what is the workers_per_gpu parameter and what is its effect please ?
Thank you
Best regards

**Comment by ly015** [comment]
You can set `workers_per_gpu` as a positive integer to turn on multi-process data loading with the specified number of loader worker processes for each GPU. More information can be found in PyTorch documentation:  https://pytorch.org/docs/stable/data.html#multi-process-data-loading

**Comment by SylvainArd** [comment]
OK is it has an influence on training results precision or only on the
training speed ?
Sylvain Ard
0549507724
0778380991
***@***.***
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers


Le mar. 28 févr. 2023 à 06:38, Yining Li ***@***.***> a
écrit :

**Comment by ly015** [comment]
It will only influence the speed. Usually, enlarging the worker number only helps to speed up the training in I/O bound scenarios. If data loading is not the bottleneck in training, a large worker number will not help and may cause large CPU and memory costs.

**Comment by SylvainArd** [comment]
OK tank you
Sylvain Ard
0549507724
0778380991
***@***.***
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers


Le mar. 28 févr. 2023 à 09:31, Yining Li ***@***.***> a
écrit :
