### ISSUE TITLE
workers_per_gpu and images_per_gpu

### ISSUE THREAD

**Issue by SylvainArd** [open-mmlab/mmpose#2010]
Hello,
If we divide the workers_per_gpu by two, can we increase the images_per_gpu by two please ?
Thank you
Best regards

**Comment by ly015** [comment]
If you hope to enlarge the batch size (images per GPU), you should use a larger number of workers so they can collect data faster to build the large batch in time.

**Comment by SylvainArd** [comment]
Yes but if we increase workers per gpu we increase the GPU RAM used isn’t it ?

Envoyé de mon iPhone

**Comment by ly015** [comment]
BTW, we notice that you are maintaining a distribution of mmpose on https://www.sylvain-ard.fr/projets_d_IA.php. We would like to kindly remind you that MMPose is licensed under the [Apache 2.0 license](https://github.com/open-mmlab/mmpose/blob/master/LICENSE). Please make sure that your distribution meets all conditions in the license. Thank you.

**Comment by ly015** [comment]
Increasing worker numbers doesn't increase the GPU RAM cost. It will increase the CPU occupancy and CPU RAM cost. The GPU memory cost usually depends on the batch size and the model size.

**Comment by SylvainArd** [comment]
Ok I will do it

Envoyé de mon iPhone

**Comment by SylvainArd** [comment]
If I well understand I must put an Apache license in my installer isn’t it ?


Envoyé de mon iPhone

**Comment by SylvainArd** [comment]
Have I to precise the modifications I have made to the original mmpose in the license ?

Envoyé de mon iPhone

**Comment by ly015** [comment]
> If I well understand I must put an Apache license in my installer isn’t it?

Yes, it seems so.

> Have I to precise the modifications I have made to the original mmpose in the license?

Personally, I think a brief description of the modification should be okay. (Sorry I am not an expert on the license stuff)

**Comment by SylvainArd** [comment]
In my mmpose installer, I use conda-pack to install automatically the
python packages useful for mmpose, have I to also add licenses for all
these packages ?
Sylvain Ard
0549507724
0778380991
***@***.***
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers

**Comment by ly015** [comment]
You may need to refer to the specific licenses of these dependencies.

**Comment by SylvainArd** [comment]
I have added apache2 mmpose license to my installer
Sylvain Ard
0549507724
0778380991
***@***.***
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers
