### ISSUE TITLE
请问什么算法最轻量呢？跑手机上的2d姿态算法？

### ISSUE THREAD

**Issue by henbucuoshanghai** [open-mmlab/mmpose#2012]

**Comment by henbucuoshanghai** [comment]
which is the fastest&nbsp; can run on my phone?tks

**Comment by Ben-Louis** [comment]
@Tau-J, 你能帮忙看一下这位同学的问题吗？

**Comment by ly015** [comment]
可以关注一下我们即将发布的 RTMPose 系列算法和模型，目前可以通过 #1971 对应的代码分支试用。文档请见：https://github.com/Tau-J/mmpose/tree/tau/rtm/projects/rtmpose

**Comment by henbucuoshanghai** [comment]
RTMPose 系列算法 手机上可以60fps吗？有多快呢？精度如何？感谢

**Comment by Tau-J** [comment]
这些信息在[这份文档](https://github.com/Tau-J/mmpose/tree/tau/rtm/projects/rtmpose)里都有详细介绍，欢迎查阅
