### ISSUE TITLE
About the filepath of encoder-decoder(codec)

### ISSUE THREAD

**Issue by kdavidlp123** [open-mmlab/mmpose#2013]
Hi, May I ask about the filepath of encoder-decoder(codec).
As the code in [this](https://github.com/open-mmlab/mmpose/blob/1.x/configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_hrnet-w32_8xb64-210e_coco-256x192.py) below
**#codec settings
codec = dict(
    type='MSRAHeatmap', input_size=(192, 256), heatmap_size=(48, 64), sigma=2)**

Because I'd like to study how the coordinates transform during the workflow.

Thank you

**Comment by Ben-Louis** [comment]
Hi, thanks for using MMPose. The codecs can be found in the directory `mmpose/codecs/`. As an example, you can find the definition for MSRAHeatmap in the following link: https://github.com/open-mmlab/mmpose/blob/1.x/mmpose/codecs/msra_heatmap.py.

**Comment by kdavidlp123** [comment]
Thank you for your reply.
In addition, does the CODEC be included in the latest version? 
It seems that 1.x is a little different from the latest version.
