### ISSUE TITLE
About warning issues when verify the installation

### ISSUE THREAD

**Issue by kdavidlp123** [open-mmlab/mmpose#2016]
Hi, May I ask one question about the warning issues when verify the installation.
![image](https://user-images.githubusercontent.com/69571884/222893486-a1f7e82b-1c34-4bf7-867b-cbffb216ad8c.png)
I am not sure about what's happened, because I have followed the instructions of installation steps.
Thank you!!

**Comment by ly015** [comment]
These warnings will not affect the use of MMPose and you can safely ignore them. Or you can build MMPose using the latest dev-1.x branch, where this issue has been fixed.
