### ISSUE TITLE
How to add Attention mechanism to MMpose

### ISSUE THREAD

**Issue by 20LGWZQ** [open-mmlab/mmpose#2018]
How to add Attention mechanism to MMpose, I use animal/fly/res152 to train my model, I want to add Attention mechanism to my project, Thanks

**Comment by Ben-Louis** [comment]
Hi, thanks for using MMPose. If you want to apply attention mechanisms in MMPose, there are two ways to achieve it: modify the source code of the module or add a new module. For instance, if you want to incorporate an attention mechanism with the  `TopdownHeatmapSimpleHead` model head in [res152_fly_192x192](https://github.com/open-mmlab/mmpose/blob/master/configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/fly/res152_fly_192x192.py), you can either:

1) Modify the `TopdownHeatmapSimpleHead` definition  in [this file](https://github.com/open-mmlab/mmpose/blob/master/mmpose/models/heads/topdown_heatmap_simple_head.py);
2) Add a new head module that uses an attention mechanism and register it. For more details, please refer to [document about adding new module](https://mmpose.readthedocs.io/en/latest/tutorials/4_new_modules.html#).

**Comment by 20LGWZQ** [comment]
> Hi, thanks for using MMPose. If you want to apply attention mechanisms in MMPose, there are two ways to achieve it: modify the source code of the module or add a new module. For instance, if you want to incorporate an attention mechanism with the `TopdownHeatmapSimpleHead` model head in [res152_fly_192x192](https://github.com/open-mmlab/mmpose/blob/master/configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/fly/res152_fly_192x192.py), you can either:
> 
> 1. Modify the `TopdownHeatmapSimpleHead` definition  in [this file](https://github.com/open-mmlab/mmpose/blob/master/mmpose/models/heads/topdown_heatmap_simple_head.py);
> 2. Add a new head module that uses an attention mechanism and register it. For more details, please refer to [document about adding new module](https://mmpose.readthedocs.io/en/latest/tutorials/4_new_modules.html#).

Hello Liu Peng, I want to ask you more details, if you have some spare time, Can you give me your contact information. Thank you very much.

**Comment by Ben-Louis** [comment]
Hi @20LGWZQ, I think we can communicate about this issue on this issue page so everyone can see. Our talk might help others with the same question.

**Comment by Tau-J** [comment]
I'll close this issue due to no response. Please feel free to reopen it if need.
