### ISSUE TITLE
topdown_demo_with_mmdet.py with a bug

### ISSUE THREAD

**Issue by Dominic23331** [open-mmlab/mmpose#2022]
When i use demo/topdown_demo_with_mmdet.py, i found a bug. The code will raise  “AssertionError: `tensor_list` could not be an empty list” when the video frame have no person. It is inconvenient for user to inference a model.  Please fix it.

**Comment by Dominic23331** [comment]
I found dev-1.x fix this problem

**Comment by ly015** [comment]
Thank you very much for reporting this issue. This bug has been fixed in #2007 and merged into the `dev-1.x` branch. It will be merged into the `1.x` branch soon as part of the next release.
