### ISSUE TITLE
如何正确的固定某些参数不训练呢？

### ISSUE THREAD

**Issue by KeyKy** [open-mmlab/mmpose#2027]
mmpose/apis/train.py中的
```
optimizer = build_optimizers(model, cfg.optimizer)
```
会训练所有model的parameter，如何剔除某些参数呢？有没有规范的写法

**Comment by Ben-Louis** [comment]
您好，如果您想冻结 backbone 的参数的话，可以通过在配置文件中设置 `frozen_stages` 来实现。例如
```python
model=dict(
    ...
    backbone=dict(
        type='ResNet',
        depth=50,
        frozen_stages=2
    )
```
会实例化一个以 ResNet50 为 backbone 的姿态估计模型，这个 ResNet50 前两个阶段的网络参数是被固定的。大部分 backbone 网络都可以通过这种方式设置冻结的参数。

上述方法只能在 backbone stage 这个粒度的进行冻结参数设置。如果您需要更加精细的设置或者需要冻结 head 的参数，就要修改网络代码了

**Comment by KeyKy** [comment]
谢谢，其实我觉得还是修改一下源码 支持参数名的正则匹配 感觉比较好~
