### ISSUE TITLE
mmpose cannot use the model in mmyolo for person detection?

### ISSUE THREAD

**Issue by aixiaodewugege** [open-mmlab/mmpose#2031]
I try to use the demo/top_down_img_demo_with_mmdet.py file with detection model from mmyolo but it report error.

My input command is 
python demo/top_down_img_demo_with_mmdet.py configs/yolov8/yolov8_s_mask-refine_syncbn_fast_8xb16-500e_coco.py https://download.openmmlab.com/mmyolo/v0/yolov8/yolov8_s_mask-refine_syncbn_fast_8xb16-500e_coco/yolov8_s_mask-refine_syncbn_fast_8xb16-500e_coco_20230216_095938-ce3c1b3f.pth configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w48_coco_256x192.py https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_coco_256x192-b9e0b3ab_20200708.pth --img-root tests/data/coco/ --img 000000196141.jpg --out-img-root vis_results.

And the reported error is
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpw0lh7c1d/tmpa0bon2vh.py'

Besides I notice that mmpose and mmyolo are using different version mmcv, one is mmcv-full 1.7.1 and the other is mmcv 2.0x. So I want to confirm is mmpose able to use mmyolo model?

**Comment by Tau-J** [comment]
MMPose 1.0 is based on mmcv 2.x, please switch to `1.x` or `dev-1.x` branch.

**Comment by aixiaodewugege** [comment]
Thanks for your quick reply. I follow your step but still can not use the mmyolo detection model.

My input command is
python demo/topdown_demo_with_mmdet.py configs/yolov8/yolov8_s_mask-refine_syncbn_fast_8xb16-500e_coco.py https://download.openmmlab.com/mmyolo/v0/yolov8/yolov8_s_mask-refine_syncbn_fast_8xb16-500e_coco/yolov8_s_mask-refine_syncbn_fast_8xb16-500e_coco_20230216_095938-ce3c1b3f.pth configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w48_coco_256x192.py https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_coco_256x192-b9e0b3ab_20200708.pth --input tests/data/coco/000000196141.jpg --show

The error is
KeyError: 'YOLODetector is not in the model registry. Please check whether the value of `YOLODetector` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

What should I do to solve the problem?

**Comment by Tau-J** [comment]
Would you like to modify the demo script to make it compatible with both `mmdet` and `mmyolo`? You can propose a PR to us, it can help a lot of users.

**Comment by aixiaodewugege** [comment]
I just checked my packages and my mmdet is already 3.0.0rc6.
mmcv                     2.0.0rc4
mmdet                    3.0.0rc6
mmengine                 0.6.0
mmpose                   1.0.0rc0   /home/wushuchen/projects/mmyolo/mmpose
mmyolo                   0.5.0      /home/wushuchen/projects/mmyolo/mmyolo

**Comment by Ben-Louis** [comment]
It looks like MMYOLO doesn't have an interface for downstream tasks like MMDetection does... 
Maybe you can try using YOLO models that are supported by MMDetection, such as [YOLOX](https://github.com/open-mmlab/mmdetection/tree/dev-3.x/configs/yolox).

**Comment by aixiaodewugege** [comment]
Thanks for your reply. It is really helpful.
