### ISSUE TITLE
OS Error: Checkpoint file issue

### ISSUE THREAD

**Issue by battulaharish2** [open-mmlab/mmpose#2032]
input: python demo/top_down_img_demo.py configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w48_coco_256x192.py mmpose/top_down/hrnet/hrnet_w48_coco_256x192-b9e0b3ab_20200708.pth --img-root tests/data/coco/ --json-file tests/data/coco/test_coco.json --out-img-root vis_results

Error message:

apex is not installed
apex is not installed
apex is not installed
/home/harish/mmcv/mmcv/cnn/bricks/transformer.py:27: **UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv-full`` if you need this module.
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '**
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Use load_from_local loader
Traceback (most recent call last):
  File "demo/top_down_img_demo.py", line 129, in <module>
    main()
  File "demo/top_down_img_demo.py", line 59, in main
    pose_model = init_pose_model(
  File "/home/harish/ViTPose/mmpose/apis/inference.py", line 42, in init_pose_model
    load_checkpoint(model, checkpoint, map_location='cpu')
  File "/home/harish/mmcv/mmcv/runner/checkpoint.py", line 513, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "/home/harish/mmcv/mmcv/runner/checkpoint.py", line 451, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/home/harish/mmcv/mmcv/runner/checkpoint.py", line 244, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "/home/harish/mmcv/mmcv/runner/checkpoint.py", line 260, in load_from_local
    raise IOError(f'{filename} is not a checkpoint file')
**OSError: mmpose/top_down/hrnet/hrnet_w48_coco_256x192-b9e0b3ab_20200708.pth is not a checkpoint file**

My issues, is how to give checkpoint files in the input. help will be highly appreciated.

**Comment by Ben-Louis** [comment]
Hi, thanks for using MMPose. Have you downloaded the checkpoint file to `mmpose/top_down/hrnet/hrnet_w48_coco_256x192-b9e0b3ab_20200708.pth`? If not, you can simply use the checkpoint URL as input:
```bash
python demo/top_down_img_demo.py \
    configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w48_coco_256x192.py \
    https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_coco_256x192-b9e0b3ab_20200708.pth \
    --img-root tests/data/coco/ --json-file tests/data/coco/test_coco.json \
    --out-img-root vis_results
```

**Comment by battulaharish2** [comment]
@Ben-Louis thanks for the quick reply. Yeah, the file was missing in my directory, now I downloaded using the checkpoint URL, and it's working now. Thank you.
