### ISSUE TITLE
cite

### ISSUE THREAD

**Issue by liangzc2016** [open-mmlab/mmpose#2033]
请问怎样在论文里面引用这个开源代码呢，我们并没有使用latex格式。

**Comment by ly015** [comment]
可能需要看一下你们投稿刊物的具体格式要求，下面的例子供参考：
![image](https://user-images.githubusercontent.com/15977946/224010040-cde4c888-eda1-4410-aadc-108078a386c6.png)

**Comment by LjIA26** [comment]
Hello, 
I am planning to cite MMPose and MMLab in my paper as I used it for training. Is this the only citation available?
