### ISSUE TITLE
How to handle parallel data stream in mmpose webcam_demo.py?

### ISSUE THREAD

**Issue by aixiaodewugege** [open-mmlab/mmpose#2043]
I found that both in master and 1.X branch the webcam_demo can only handle serial data stream. Is there any way that two nodes can use the same input buffer?

**Comment by Ben-Louis** [comment]
Sure, it is indeed possible to specify the argument `input_buffer` for each individual node within your webcam configs utilizing the identical buffer name. For more details, please refer [this doc](https://mmpose.readthedocs.io/en/latest/tutorials/7_webcam_api.html).

**Comment by aixiaodewugege** [comment]
However, with the same input_buffer name two nodes will consume the same buffer and will lead to frame leak. In other word, one frame can't be processed by two nodes.

**Comment by ly015** [comment]
Perhaps you can implement a new `SpliteFrameNode` that splits the input frames into multiple identical frames for different downstream nodes?

**Comment by aixiaodewugege** [comment]
Thanks for your reply. I have tried it and it worked. 

But are the different output buffers must have same content

**Comment by ly015** [comment]
I think it depends on your need. The content doesn't have to be exactly the same. Also please pay attention to the shallow/deep copy issue. Sharing memory across frames may lead to expected results.
