### ISSUE TITLE
object detection before keypoints detection

### ISSUE THREAD

**Issue by SylvainArd** [open-mmlab/mmpose#2048]
Hello,
I want to do object detection before keypoints detection. What program do you advise me ? I saw yolov8 but it is under GPL license and I don't want to provide my program source code.
Thank you 
Best regards

**Comment by Tau-J** [comment]
I suggest trying [RTMDet](https://github.com/open-mmlab/mmdetection/tree/dev-3.x/configs/rtmdet). BTW, we release a real-time and high-performance model named [RTMPose](https://github.com/open-mmlab/mmpose/tree/dev-1.x/projects/rtmpose), would you like to have a try?

**Comment by SylvainArd** [comment]
Thank you very much !
Sylvain Ard
0549507724
0778380991
***@***.***
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers
