### ISSUE TITLE
labels on demo

### ISSUE THREAD

**Issue by SylvainArd** [open-mmlab/mmpose#2049]
Hello,
I want to print keypoints class labels on images generated by demo.py.
How to do this please ?
Thank you
Best regards

**Comment by Tau-J** [comment]
Here's an example of visualizing keypoint indexes https://github.com/open-mmlab/mmpose/pull/2051, FYI

**Comment by SylvainArd** [comment]
OK thank you and it is not possible to see the labels names instead of labels numbers ?

**Comment by Tau-J** [comment]
In most circumstances, the label name is a meaningless symbol, so I tend to vis the index. If necessary, I think you can modify the code slightly to show the label name.

**Comment by SylvainArd** [comment]
ok thank you
