### ISSUE TITLE
mmpose中HRNet的改进

### ISSUE THREAD

**Issue by mgcyung** [open-mmlab/mmpose#2050]
请问mmpose中HRNet的实现相比于原始HRNet有什么区别和改进的地方吗？比如，
对于 hrnetv2_w18_300w_256x256.py 的配置，在网络结构、loss、学习率、
augmentation 这些方面有什么修改吗？

**Comment by ly015** [comment]
你好，可以参考具体模型的 config 和原论文或官方实现对比一下哈。通常网络结构是与论文一致的，在训练超参和数据增强上可能会存在一点差异。

**Comment by mgcyung** [comment]
感谢提示
