### ISSUE TITLE
Memory leakage issue in body3d_multiview_detect_and_regress_img_demo?

### ISSUE THREAD

**Issue by BatFaceWayne** [open-mmlab/mmpose#2052]
Thanks for the wonderful work! There might be a memory leakage issue that hinders long video inference with voxelpose.

https://github.com/open-mmlab/mmpose/blob/cbac8809f9aaf9a06d12739b1000eb9fc7b9a69d/demo/body3d_multiview_detect_and_regress_img_demo.py#L152
Add a .copy() at the end resolves the issue on my side. Cheers!

**Comment by ly015** [comment]
Thank you very much for your feedback! Would you mind submitting a pull request to fix the memory leaking issue? We have prepared a [guide on contributing to MMPose](https://github.com/open-mmlab/mmpose/blob/master/.github/CONTRIBUTING.md). Of course, if it's not convenient for you, we will fix it asap.
