### ISSUE TITLE
associative_embedding/ hrnet_48_mydataset_512x512  loss is very low?

### ISSUE THREAD

**Issue by lkvanny** [open-mmlab/mmpose#2059]
When I used  "associative_embedding/ hrnet_48_mydataset_512x512" to train my own dataset,  heatmap_loss, push_loss, pull_loss, loss are very low. Is this normal？

<img width="813" alt="图片 1" src="https://user-images.githubusercontent.com/53886782/224982532-8b46c90b-b5c4-4407-87bd-3c29a9ed7143.png">

**Comment by lkvanny** [comment]
The above is the result of my running with 0. X version. Is this reasonable?

**Comment by ly015** [comment]
You can check if the validation AP is increasing properly along with the training process.

**Comment by jin-s13** [comment]
I think that's normal. Don't worry.
