### ISSUE TITLE
some questions about 1.x

### ISSUE THREAD

**Issue by lkvanny** [open-mmlab/mmpose#2060]
（1）1. x version has almost no bottom-up integration method at present,why?  Will it be supported in the future, such as open pose

（2）Compared with 0. x, 1. x has a great improvement in the overall framework, but the supported data sets, algorithms and use documents are not perfect. Which version do you recommend for beginners？

（3）In addition, the top-down method needs to be dectected first. If on my own dataset, do I need to install mmdection to train a detection model?

（4）When testing the efficiency of the algorithm, does the detection time in the top-down method count?

**Comment by lkvanny** [comment]
Thank you very much for your reply, and look forward to a more complete 1. x version, the sooner the better!

**Comment by lkvanny** [comment]
In addition, will part affinity field  or Spatio-Temporal Affinity Fields models （such as OpenPose）be integrated in the future？

**Comment by ly015** [comment]
For now, we don't have the plan to integrate PAF in immediate future. Community contributions will be always welcome and we will help our contributors as a high-priority task.
