### ISSUE TITLE
Please don't arbitrarily overwrite the render platform.

### ISSUE THREAD

**Issue by tzaman** [open-mmlab/mmpose#2062]
https://github.com/open-mmlab/mmpose/blob/52fd3f35499e1450ff18179f603796c57dd72424/mmpose/core/visualization/image.py#L20

This line breaks PyRender entirely if it's being used in other contexts (with egl, for example). There's no need to manually force the platform to a specific setting and stomp over the user environment.

**Comment by ly015** [comment]
Thanks for your feedback. Maybe the overwriting of the render platform can be moved into the `imshow_3d_mesh` and use a lazy import to avoid inference on other parts. Would you be willing to submit a pull request to help fix this issue?
