### ISSUE TITLE
how to train model on mutiple datasets in one config file for mmpose 1.x?

### ISSUE THREAD

**Issue by darcula1993** [open-mmlab/mmpose#2066]
I found another issue here but seems only work for mmpose 0.x: https://github.com/open-mmlab/mmpose/issues/1256
any idea how to do this in mmpose 1.x?

**Comment by Tau-J** [comment]
I suggest using [CombinedDataset](https://github.com/open-mmlab/mmpose/blob/dev-1.x/docs/en/advanced_guides/mixed_datasets.md)

**Comment by darcula1993** [comment]
great it works！
