### ISSUE TITLE
the precision of the printing information

### ISSUE THREAD

**Issue by HuangJunJie2017** [open-mmlab/mmpose#207]
![image](https://user-images.githubusercontent.com/31001081/96687285-4359d800-13b2-11eb-8277-1e035606b3a6.png)
how to modify the precision of the printing information(loss)?  e.g. Print the loss in precision of '%.07f'

**Comment by innerlee** [comment]
you can change this line of mmcv https://github.com/open-mmlab/mmcv/blob/4ec73abbcc30314604d7afa6f59c1d6be5e8426c/mmcv/runner/hooks/logger/text.py#L118

**Comment by innerlee** [comment]
you may also request a feature in mmcv repo to support customizing float precision in logging
