### ISSUE TITLE
rtmpose评估问题

### ISSUE THREAD

**Issue by xiaochenwise** [open-mmlab/mmpose#2078]
If I use my own data to train rtmpose, how should I evaluate it on the coco data set? I didn't find a module for evaluation, but there was this module in the previous version of mmpose.

**Comment by Tau-J** [comment]
Thanks for using MMPose. You just need to set the `dataset` and `val_dataloader` to be coco data. Take [this config](https://github.com/open-mmlab/mmpose/blob/1.x/projects/rtmpose/rtmpose/body_2d_keypoint/rtmpose-m_8xb256-420e_coco-256x192.py) as an example, the training and validation are all on COCO, you can modify the training part into your own datasets, and keep the val part as it was.

**Comment by xiaochenwise** [comment]
> Thanks for using MMPose. You just need to set the `dataset` and `val_dataloader` to be coco data. Take [this config](https://github.com/open-mmlab/mmpose/blob/1.x/projects/rtmpose/rtmpose/body_2d_keypoint/rtmpose-m_8xb256-420e_coco-256x192.py) as an example, the training and validation are all on COCO, you can modify the training part into your own datasets, and keep the val part as it was.

Hello, now that the model training is finished, I want to test the accuracy of COCO val2017 with detector having human AP of 56.4, but the command evaluated by the previous version will give an error

**Comment by Tau-J** [comment]
Hi @xiaochenwise , MMPose 1.x is incompatible with previous version, so you need to follow [new docs](https://mmpose.readthedocs.io/en/1.x/user_guides/train_and_test.html) to test. If you meed any error, you can print it in this issue.
