### ISSUE TITLE
how to evaluate AP metrics for each joint or for each category?

### ISSUE THREAD

**Issue by HyoKong** [open-mmlab/mmpose#2081]
I train a hrnet on my own dataset and the performance is not good. Then I check the annotations of the training and the testing dataset with your visualization tools. The annotations seem perfect. The visualization results on the testing dataset are good too. I don't know why the AP is under 0.5. So I want to analyze AP for each category (there are many categories on my dataset) and each joint. May I ask if is there any function to achieve this or what script should I revise to analyze the performance?

**Comment by Ben-Louis** [comment]
Hi, thanks for using MMPose. If you want to calculate the AP for each keypoint, you can refer to the [KeypointPartitionMetric](https://github.com/open-mmlab/mmpose/pull/1944) However, it should be noted that category-specific AP is not yet supported. One workaround is to add category filters to [this function](https://github.com/open-mmlab/mmpose/blob/0076817a3c85ac0006d8f2c0a83ba14be9c75609/mmpose/datasets/datasets/base/base_coco_style_dataset.py#L431) and manually set the category using `filter_cfg` in config.

**Comment by HyoKong** [comment]
Thank you so much for your help! The KeypointPartitionMetric works well. 

One more thing, may I ask how to evaluate more metrics during training and testing? The val and test evaluators seem only support one metric.

```
test_evaluator = dict(
    type='KeypointPartitionMetric',
    metric=dict(
        type='PCKAccuracy',
    ),
    partitions=dict(
        face=range(7),
        arm=range(7, 13),
        torso=range(13, 14),
        leg=range(14, 20),
        tail=range(20, 23),
        all=range(23)
    )
)```

For example, how can I evaluate two types (KeypointPartitionMetric & CoCoMetric), and calculate two metrics (PCKAccuracy and AP) for each type at the same time?

Thank you so much! @Ben-Louis
