### ISSUE TITLE
Can rtmpose be used in master branch?

### ISSUE THREAD

**Issue by aixiaodewugege** [open-mmlab/mmpose#2083]
I notice that there are some difference in config file between master and 1.x branch. So can I  use rtmpose model in old version?

**Comment by Ben-Louis** [comment]
Some modules utilized by RTMPose are exclusively defined in the 1.x branch. Therefore, if you intend to use RTMPose in the old version, you will have to transfer all the modules to the older version, which can be a cumbersome process. We suggest utilizing the 1.x version of MMPose, as the forthcoming development will primarily focus on this version.
