### ISSUE TITLE
The drawing visualization is weird

### ISSUE THREAD

**Issue by NikolayTV** [open-mmlab/mmpose#209]
python demo/bottom_up_video_demo.py \
    configs/bottom_up/mobilenet/coco/mobilenetv2_coco_512x512.py \
    models/mobilenetv2_coco_512x512-4d96e309_20200816_2.pth \
    --video-path data/classroom.mp4 \
    --out-video-root vis_results \
    --show \
    --device cuda:0

Why is this so?
![image](https://user-images.githubusercontent.com/32233366/96818295-c8e19480-1453-11eb-9915-5654bb9ca1b7.png)

**Comment by innerlee** [comment]
could you try the same img with a larger backbone?

**Comment by NikolayTV** [comment]
higher_hrnet32_coco_512x512-8ae85183_20200713.pth 

![image](https://user-images.githubusercontent.com/32233366/96819768-fda31b00-1456-11eb-9e86-238296b2740b.png)

**Comment by NikolayTV** [comment]
hrnet_w32_coco_512x512-bcb8c247_20200816.pth
![image](https://user-images.githubusercontent.com/32233366/96819912-5672b380-1457-11eb-8dd2-951a6b963b6e.png)

**Comment by NikolayTV** [comment]
res50_coco_512x512-5521bead_20200816.pth
![image](https://user-images.githubusercontent.com/32233366/96819982-85892500-1457-11eb-960a-dfd9d2cd2ca6.png)

**Comment by NikolayTV** [comment]
So, you see. That HigherHrNet and HRNet are making good lines, while mobilenet and resnet are something weird. Even so the keypoints are on the place, lines are crazy

**Comment by jin-s13** [comment]
The bottom up methods have two parts: the keypoint detection part and the keypoint grouping part. As shown in the fig, the detection is correct but the grouping is wrong. The grouping method we support now is Associative Embedding, which seems to be hard to learn for lightweight backbones.

**Comment by NikolayTV** [comment]
Thank you for reply. Now I know this is not a bug in code
