### ISSUE TITLE
Feature Map Visualization

### ISSUE THREAD

**Issue by HyoKong** [open-mmlab/mmpose#2090]
Hi, may I ask if is there any tool to visualize the output feature maps for each model? For instance, How to visualize the output feature map for hrnet stage 4? How to obtain the intermediate feature maps from the model?

Thank you so much!

**Comment by Ben-Louis** [comment]
Sorry, there is no off-the-shelf tools available for visualizing the intermediate feature maps. To achieve this, you might have to make modifications to the model's forward process so that it returns the desired feature map, and then plot it.
