### ISSUE TITLE
Why is the result of image_demo.py running different from that of test.py?

### ISSUE THREAD

**Issue by hh123445** [open-mmlab/mmpose#2091]
Thanks for your error report and we appreciate it a lot.
If you feel we have helped you, give us a STAR! :satisfied:

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

I use my own dataset for training, and the trained mAP can reach 0.98. So I used test.py to test it and set -- show='show_ dir 'to display the test results. "There are multiple objects in my image, and I have found that the key point detection results for different objects in the same image cannot be displayed on the same image, but instead are displayed separately in multiple identical images.".

To display the results on the same image, I used image_demo.py, but I found that the detection results did not show any key points. I observed the results and found that the keypoint scores was very low, only around 0.07, so it was completely filtered out.

Why is the result of image_demo.py running different from that of test.py?
Is the preprocessing method of image_demo.py different from test.py? If so, how should I modify it?
The configuration used in image_demo.py is as follows:
````
def parse_args():
    parser = ArgumentParser()
    parser.add_argument('--img', help='Image file', default='/my_path/coco/train/0008.jpg')
    parser.add_argument('--config', help='Config file', default='my_path/my_td-hm_resnetv1d50_8xb64-210e_coco-384x288.py')
    parser.add_argument('--checkpoint', help='Checkpoint file', default='run/best_coco/AP_epoch_35.pth')
    parser.add_argument('--out-file', default='show_dir/0008.jpg', help='Path to output file')
    parser.add_argument(
        '--device', default='cuda:0', help='Device used for inference')
    parser.add_argument(
        '--draw-heatmap',
        action='store_true',
        help='Visualize the predicted heatmap')
    parser.add_argument(
        '--show-kpt-idx',
        action='store_true',
        default=True,
        help='Whether to show the index of keypoints')
    parser.add_argument(
        '--show',
        action='store_true',
        default=True,
        help='whether to show img')
````

**Comment by Ben-Louis** [comment]
Hi, thanks for using MMPose. Based on the information you provided, it appears that you are currently using a top-down model that detects keypoints within the range of an instance bounding box. However, in the `image_demo.py` script, the entire image is used as input for the model, which deviates from the training process. This may result in a decrease in the accuracy of the pose estimation. To ensure that all predictions are displayed on one image, we recommend using `demo/topdown_demo_with_mmdet.py` instead. Please note that it is important to choose an appropriate object detector that can accurately detect the objects you wish to estimate the pose on.

**Comment by hh123445** [comment]
Thank you very much! Do you mean that top-down key point detection uses only the range of the box, not the whole picture, for training and testing?
By the way, in fact, the size of my input pictures is very large and the number of pictures is small, but my box range is very small. During the training process, I found that only about 10 Epoch, mAP achieves very good results. I was curious whether this is also because the smaller box range makes the background interference less, so the learning of key-point features is very fast.

**Comment by Ben-Louis** [comment]
Indeed, you are correct. The diagram below portrays the top-down pose estimation pipeline:
![A-classical-pipeline-of-top-down-framework-for-human-pose-estimation-a-Original-image-in](https://user-images.githubusercontent.com/26127467/226156177-a7b9ea28-761b-436e-b532-5705929063b5.png)
In addition to discarding superfluous background as you mentioned, the top-down approach also confers another benefit: it standardizes the size of all instances, simplifying the model's learning process.
