### ISSUE TITLE
Why no VitPose?

### ISSUE THREAD

**Issue by Lanrzip** [open-mmlab/mmpose#2095]
I saw the "mmpose" in the https://github.com/ViTAE-Transformer/ViTPose repository. What's the relationship between the mmpose and VitPose? Thanks!

**Comment by ly015** [comment]
Hi, the official ViTPose implementation is based on MMPose, as you can see at https://github.com/ViTAE-Transformer/ViTPose. And we have integrated ViTPose into the latest MMPose v1.0.0rc1, so you can use it in MMPoes now. Please checkout https://github.com/open-mmlab/mmpose/blob/1.x/configs/body_2d_keypoint/topdown_heatmap/coco/vitpose_coco.md

**Comment by Lanrzip** [comment]
thanks!!!

**Comment by Lanrzip** [comment]
I also want to ask, can the vitpose model be used for the version in the master branch of mmpose?
