### ISSUE TITLE
Can not run image demo example on MPII 

### ISSUE THREAD

**Issue by duckduck-sys** [open-mmlab/mmpose#210]
When i run the image examples given [here](https://github.com/open-mmlab/mmpose/blob/master/docs/getting_started.md) it works fine on COCO, but if i modify the examples to run a model trained for MPII like so:

python demo/top_down_img_demo.py configs/top_down/hourglass/mpii/hourglass52_mpii_256x256.py checkpoints/hourglass52_mpii_256x256-ae358435_20200812.pth --img-root tests/data/mpii/ --json-file tests/data/mpii/test_mpii.json --out-img-root vis_results

I get this error:

```
Traceback (most recent call last):
  File "demo/top_down_img_demo.py", line 94, in <module>
    main()
  File "demo/top_down_img_demo.py", line 44, in main
    coco = COCO(args.json_file)
  File "/home/user/anaconda3/envs/pytorch-gpu/lib/python3.6/site-packages/xtcocotools/coco.py", line 90, in __init__
    assert type(dataset)==dict, 'annotation file format {} not supported'.format(type(dataset))
AssertionError: annotation file format <class 'list'> not supported
```

Any ideas? If i replace --json-file tests/data/mpii/test_mpii.json with --json-file tests/data/mpii/test_mpii_trb.json the demo also fails

**Comment by jin-s13** [comment]
Currently, the`top_down_img_demo.py` only works for coco-format json file.  The annotation file format of mpii is not supported yet.

For now, you can try `top_down_img_demo_with_mmdet.py`, this will work fine for mpii models.

**Comment by duckduck-sys** [comment]
Ok i tried with the top_down_img_demo_with_mmdet.py demo instead. If i run using the a model trained on COCO using the command:

python demo/top_down_img_demo_with_mmdet.py ../mmdetection/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py ../mmdetection/checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth configs/top_down/hrnet/coco/hrnet_w48_coco_256x192.py checkpoints/hrnet_w48_coco_256x192-b9e0b3ab_20200708.pth --img-root tests/data/coco/ --img 000000196141.jpg --out-img-root vis_results

It works fine. But if i switch to a model trained on MPII:

python demo/top_down_img_demo_with_mmdet.py ../mmdetection/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py ../mmdetection/checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth configs/top_down/hrnet/mpii/hrnet_w32_mpii_256x256.py checkpoints/hrnet_w32_mpii_256x256-6c4f923f_20200812.pth --img-root tests/data/coco/ --img 000000196141.jpg --out-img-root vis_results

I get the following error:

```
Traceback (most recent call last):
  File "demo/top_down_img_demo_with_mmdet.py", line 93, in <module>
    main()
  File "demo/top_down_img_demo_with_mmdet.py", line 73, in main
    dataset=dataset)
  File "/home/user/PycharmProjects/mmpose/mmpose/apis/inference.py", line 277, in inference_top_down_pose_model
    model, img_or_path, bbox, dataset)
  File "/home/user/PycharmProjects/mmpose/mmpose/apis/inference.py", line 189, in _inference_single_pose_model
    raise NotImplementedError()
NotImplementedError
```

Seems like the demo's always fail when running MPII models?

**Comment by jin-s13** [comment]
We have just added the demo code support for MPII models. Thanks for pointing out this issue.

**Comment by duckduck-sys** [comment]
Alright, thanks a lot!
