### ISSUE TITLE
您好，我想通过voxelpose输出多角度融合出来的人体关键点，我该运行哪个程序，该怎么做，谢谢

### ISSUE THREAD

**Issue by graceforlife** [open-mmlab/mmpose#2100]

**Comment by ly015** [comment]
你好，可以参考 voxelpose demo：https://github.com/open-mmlab/mmpose/blob/master/demo/docs/3d_multiview_human_pose_demo.md

**Comment by graceforlife** [comment]
> 你好，可以参考 voxelpose demo：https://github.com/open-mmlab/mmpose/blob/master/demo/docs/3d_multiview_human_pose_demo.md
好的，谢谢
