### ISSUE TITLE
Multiclass pose estimation with RTMPose

### ISSUE THREAD

**Issue by NicolasPetermann134** [open-mmlab/mmpose#2101]
Hey community!
I just came across your great work. Many thanks! - I wonder if it is possible to train a RTMPose as a multiclass model that detects kpts for instance from animal 1 and animal 2?

If possible: What should i pay attention to?
If not yet possbile: Which parts of the source code should I adjust?

Would appreciate any comment/hint!

Kind Regards,
Nico

**Comment by Tau-J** [comment]
Thanks for using MMPose and RTMPose! Yes, RTMPose can detect kpts from different animals. In fact, we release a RTMPose-m trained on AP-10K dataset, which contains images from 23 animal families and 54 species.

**Comment by NicolasPetermann134** [comment]
That's amazing! When will it come out? 
So does that mean, if I have a dataset containing 2 classes with different numbers of kpts in coco format it will work if I follow this instruction?: https://mmpose.readthedocs.io/en/1.x/user_guides/train_and_test.html

**Comment by sherry521sherry** [comment]
@NicolasPetermann134  Hello, do you have a public available dataset （Multiple species of different points on an image），I would appreciate it if you could provide.

**Comment by NicolasPetermann134** [comment]
@sherry521sherry 
I can not share my dataset, unfortunately. But why are you no using the ap10k dataset? https://github.com/AlexTheBad/AP-10K
Regards
