### ISSUE TITLE
no DETR-based pose estimation

### ISSUE THREAD

**Issue by amazing-cc** [open-mmlab/mmpose#2102]
No pose estimation algorithms using detr-like structures were found in the mmpose repository, and it is hoped that some such algorithms will be added in future work. 
Since I want to build detr-based algorithms with mpose 1.x, do you have any suggestions for this?
Or do you have any additional concerns about this?
So far I've only seen poseur build such algorithms based on mmpose 0.x. edpose is also detr-based network, but does not use mmpose.

**Comment by ly015** [comment]
Hi, thanks for your interest in MMPose. We have a plan to support [PETR (CVPR'22)](https://openaccess.thecvf.com/content/CVPR2022/papers/Shi_End-to-End_Multi-Person_Pose_Estimation_With_Transformers_CVPR_2022_paper.pdf) in MMPose 1.x. Please stay tuned.

**Comment by amazing-cc** [comment]
Thank you for your prompt reply, I would like to know the exact timing of the PETR support. Very much looking forward to it

**Comment by ly015** [comment]
@Ben-Louis Could you please give an ETA of PETR?

**Comment by Ben-Louis** [comment]
Hi @amazing-cc, PETR will be supported in approximately 2 weeks
