### ISSUE TITLE
How to change Object Detection model?

### ISSUE THREAD

**Issue by Per-Ardua-Ad-Astra** [open-mmlab/mmpose#2107]
Hello
I'm testing HRNet_w48_coco_256x192 and want to change object detection model from yolov3 to yolov7.
I encountered this error `FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp_ey1b908/tmp_92_uze_.py'`

What more modifications should I make to code work?

Below is the command I put into action.
`python demo/top_down_img_demo_with_mmdet.py demo/mmdetection_cfg/yolov7_syncbn_8x16b-100e_coco_custom.py data/yolov7_custom_epoch_best.pt configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w48_coco_256x192.py data/hrnet_w48_coco_256x192-b9e0b3ab_20200708.pth --img-root test_data/day/ --img day_1.png --out-img-root data/results/yolov7_hrnetw48`

I want to know what I'm gonna do. Thank you so much!

**Comment by Ben-Louis** [comment]
Hi, thanks for using MMPose. The issue you mentioned is usually triggered by errors in the config. We suggest verifying your config and running the following code to confirm if the issue has been resolved:
```python
from mmcv import Config
config = Config.fromfile(config_path)
```
If the config can be loaded without any issues, it indicates that the problem has been resolved. You could refer to [this document](https://mmcv.readthedocs.io/en/master/understand_mmcv/config.html) for details about config file.
