### ISSUE TITLE
when deploy mmpose rtmpose, for example, pt to onnx. It can not detect the pose since it locks the detection model.

### ISSUE THREAD

**Issue by lelechen63** [open-mmlab/mmpose#2109]
I follow the instruction. And use the following command to deploy the model. It can output onnx model. However, there are no pose detection results on images since you did not have the port for the detection model. I would suggest you include a new deploy function that incorporates the detection model in the pytorch2onnx.
python tools/deploy.py \
    configs/mmpose/pose-detection_simcc_onnxruntime_dynamic.py  \
    ../codebase/models/rtmpose/rtmpose/body_2d_keypoint/rtmpose-t_8xb256-420e_coco-256x192.py\
    ../codebase/models/rtmpose/rtmpose/body_2d_keypoint/rtmpose-tiny_simcc-aic-coco_pt-aic-coco_420e-256x192-cfc8f33d_20230126.pth \
    ./25742375907_cam3.png \
    --work-dir ./rtm_onnx \
    --device cpu \
    --show

**Comment by Tau-J** [comment]
Thanks for using MMPose. As a script for exporting the model, we think it is not necessary to add the detection method in `deploy.py`. We provide a human-pose.jpg under `mmdeploy/demo/resources/` for verifying whether the model is converted successfully, and you can also quickly get a validation image through screenshots and cropping.

**Comment by lelechen63** [comment]
> Thanks for using MMPose. As a script for exporting the model, we think it is not necessary to add the detection method in `deploy.py`. We provide a human-pose.jpg under `mmdeploy/demo/resources/` for verifying whether the model is converted successfully, and you can also quickly get a validation image through screenshots and cropping.

Oh yea, that make sense. Thanks. One more question, the rtmdetection model contains hard sigmoid which is not supported by on onnx2dlc. Will you change the hard sigmoid to sigmoid function for snpe?

**Comment by Tau-J** [comment]
You can discuss issues related to RTMDet with the MMDetection repo team, but MMPose does not involve the development of RTMDet.

**Comment by Tau-J** [comment]
Hi @Serdnad , for top-down algorithms like RTMPose, it is assumed that the user already has an independent detector to predict bounding boxes. Therefore, the exported mmpose model does not include the step of generating bounding boxes. In the [RTMPose documentation](https://github.com/open-mmlab/mmpose/tree/1.x/projects/rtmpose#%EF%B8%8F-step2-convert-model), we provide scipts for exporting detection models (such as RTMDet) and offer `det_pose` and `pose_tracker` for joint inference.
