### ISSUE TITLE
COCO Metrics

### ISSUE THREAD

**Issue by HyoKong** [open-mmlab/mmpose#2112]
Hi, I noticed that the joint annotation would be -1 if the joint is not visible or occluded on some datasets. However, when we analyze COCO metrics, the oks scores for all joints will be computed. May I ask how the COCOmetrics API in mmpose deals with the issue?

Thank you so much!

**Comment by Ben-Louis** [comment]
Based on the definition of the OKS score, only visible keypoints are taken into account. 
![image](https://user-images.githubusercontent.com/26127467/227154604-9a2b0787-969d-40ec-a4a0-b14492ab2abd.png)

MMPose follows this definition. For more details, please refer to the [COCO keypoints evaluation page](https://cocodataset.org/#keypoints-eval)
