### ISSUE TITLE
RTMPose model document show flops or Macs？

### ISSUE THREAD

**Issue by darcula1993** [open-mmlab/mmpose#2119]
The status page of RTMPose showed that RTM-tiny model is 0.3G flops.
Just want to make sure it is flops or macs？I am using torchinfo to count and it showed that RTMPose-tiny model is 0.3G Macs(mult-adds) which is actually 0.6G flops.

**Comment by Tau-J** [comment]
We count FLOPs via [fvcore](https://github.com/facebookresearch/fvcore/tree/main) and `mmengine`, the results are the same.

**Comment by darcula1993** [comment]
@Tau-J That's the problem. fvcore actually count macs not flops: https://github.com/facebookresearch/fvcore/issues/69
"We count one fused multiply-add as one flop."
Flops should count one fused multiply-add as two flops.

**Comment by Tau-J** [comment]
Thanks for your kind reminder. We will add a note in docs later.
