### ISSUE TITLE
双卡训练报错，单卡训练正常

### ISSUE THREAD

**Issue by sayoko17** [open-mmlab/mmpose#2123]
一开始报错：
`RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).`
然后我根据网上的资料去找哪些参数没有返回梯度，在loss那里打印了
        for name, p in self.head.named_parameters():
            #  print(name)
            if p.grad is None:
                print(name)
结果出来是
final_layer.weight
final_layer.bias
然后我就用了has_final_layer=False，但是显而易见是不可以的，会产生维度报错。
想知道为什么单卡训练没有问题，但是双卡的时候就会出现这个问题呢，有没有其他办法能够解决，万分感谢！

**Comment by sayoko17** [comment]
在mmpose1.0版本下。

**Comment by sayoko17** [comment]
是我自己根据litehrnet的改进，litehrnet的部分是没有问题的，既可以单卡也可以双卡。

**Comment by Ben-Louis** [comment]
您好，您可以试下在 config 文件里加一行 
```python
find_unused_parameters = True
```
再进行训练

**Comment by sayoko17** [comment]
谢谢，神速解决2333333，我自己折腾了一早上，万分感谢~~~
