### ISSUE TITLE
Could you support python3.7?

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmpose#213]
I tried to install the mmpose, mmdetection, mmclassification and mmsegmentation in the one environment(python=3.7,conda). But I found that except for mmpose, the other three succeeded.And the error told me the version of python should >=3.6& <3.7. As follow:

![2020-10-24 22-19-47 的屏幕截图](https://user-images.githubusercontent.com/48090608/97084157-9dbf9680-1647-11eb-98dd-7f89bb26201d.png)

I sincerely hope mmpose can support python3.7.
Thank you!

**Comment by innerlee** [comment]
finally, time to blame dataclass.

**Comment by innerlee** [comment]
Hi @zhongqiu1245 , how to reproduce this error? I tried python 3.8 and it installed successfully

**Comment by zhongqiu1245** [comment]
My conda environment(main):pytorch1.6.0,torchvision0.7.0,python3.7.8
But I installed it successfully in the python3.6 environment.
Strange......

**Comment by innerlee** [comment]
are you installing from source or from pypi, and which installation command is used?

**Comment by zhongqiu1245** [comment]
pytorch,torchvision,cudatoolkit:conda install
others:pip install

**Comment by zhongqiu1245** [comment]
And I found the environment with (pytorch1.5.0 torchvision0.6.0 python3.7) could work,but failed in pytorch1.6.0

**Comment by zhongqiu1245** [comment]
main(most of requirements):conda install xxx
others(when the "conda install didn't work",a few):pip install xxx (source of pypi:aliyun)
(sorry for previous comment)

**Comment by innerlee** [comment]
from the screenshot in the first post, this is caused by the dataclasses package, which is the dependency of the smplx package.

on the failed environment, could you try `pip install git+https://github.com/vchoutas/smplx` ?

**Comment by zhongqiu1245** [comment]
Thank you for your advice! I will try later.

**Comment by zhongqiu1245** [comment]
Didn't work
The smplx was fine, but the dataclasses still failed.
![2020-10-26 16-26-44 的屏幕截图](https://user-images.githubusercontent.com/48090608/97149834-4127bd00-17a8-11eb-8571-057de8fa0e2b.png)

**Comment by innerlee** [comment]
dataclasses is a builtin package in python3.7, so you cannot and don't need to pip install it.
dataclasses is in the requirements of smplx, so if you can install it successfully, then pip is smart enough to bypass this package.
Now the question is, why mmpose would fail with it?

**Comment by innerlee** [comment]
Could you try `pip install git+git:https://github.com/open-mmlab/mmpose.git@34db60a5110edaf73621cf3c0c763097fcd1a34c`? In this commit, dataclasses is removed. Let's see if everything is okay

**Comment by zhongqiu1245** [comment]
Thank you, it worked!!!
![2020-10-26 18-39-08 的屏幕截图](https://user-images.githubusercontent.com/48090608/97162996-f499ad00-17ba-11eb-9c8b-fd1bc2ce323c.png)

**Comment by innerlee** [comment]
nice
