### ISSUE TITLE
ViTPose Support

### ISSUE THREAD

**Issue by HyoKong** [open-mmlab/mmpose#2131]
Hi, may I ask where is the ViTPose model file? I can find the config file [https://github.com/open-mmlab/mmpose/blob/1.x/configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_ViTPose-base_8xb64-210e_coco-256x192.py](url) but cannot find the model file. Besides, VisionTransformer cannot be imported from mmcls although I've already installed mmcls. https://github.com/open-mmlab/mmpose/blob/cd710204e2c52b9635ad30f43e121a158e1faa08/configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_ViTPose-base_8xb64-210e_coco-256x192.py#L62

Thank you so much for your help!

**Comment by Ben-Louis** [comment]
Hi, thanks for using MMPose. To utilize ViTPose, you'll need to have [MMClassification](https://github.com/open-mmlab/mmclassification). To install the required version, run the following command:

```
mim install 'mmcls>=1.0.0rc5'
```

**Comment by HyoKong** [comment]
Thank you so much for your quick reply. But I cannot find a version meets the requirement mmcls>=1.0.0rc5. The highest version is 1.0.0rc3.

**Comment by HyoKong** [comment]
Is there any way to install mmcls 1.0.0rc5 from the source code?

**Comment by HyoKong** [comment]
I've alr installed mmcls1.0.0rc3 from the source code. But I still cannot import VisionTransformer from mmcls.

![image](https://user-images.githubusercontent.com/32049327/228432808-bfba3a30-5540-4746-8643-e13bce107113.png)

**Comment by LareinaM** [comment]
Hi, if you wish to import it in Python shell, use `from mmcls.models.backbones import VisionTransformer`.

**Comment by LareinaM** [comment]
Model files are updated in [this PR](https://github.com/open-mmlab/mmpose/pull/2133).

**Comment by ly015** [comment]
BTW, MMClassification v1.0.0rc5 has been released for a while. More information can be found at https://github.com/open-mmlab/mmclassification/releases

**Comment by vv111y** [comment]
> Model files are updated in [this PR](https://github.com/open-mmlab/mmpose/pull/2133).

Hi, I tried to use this by checking out both the PR and the dev1.x branch. 
Either case there is a MMCV incompatibility

```
Traceback (most recent call last):
  File "/home/will/Work/prosfit_gait_analysis/proj-prosfit-pose-estimation/make_coco_dataset_videoset.py", line 8, in <module>
    from mmpose.apis import inference_top_down_pose_model, init_pose_model, vis_pose_result
  File "/home/will/Work/prosfit_gait_analysis/mmpose/mmpose/apis/__init__.py", line 3, in <module>
    from .inferencers import MMPoseInferencer, Pose2DInferencer
  File "/home/will/Work/prosfit_gait_analysis/mmpose/mmpose/apis/inferencers/__init__.py", line 2, in <module>
    from .mmpose_inferencer import MMPoseInferencer
  File "/home/will/Work/prosfit_gait_analysis/mmpose/mmpose/apis/inferencers/mmpose_inferencer.py", line 14, in <module>
    from .pose2d_inferencer import Pose2DInferencer
  File "/home/will/Work/prosfit_gait_analysis/mmpose/mmpose/apis/inferencers/pose2d_inferencer.py", line 20, in <module>
    from mmdet.apis.det_inferencer import DetInferencer
  File "/home/will/anaconda3/envs/vaex/lib/python3.10/site-packages/mmdet/__init__.py", line 25, in <module>
    and mmcv_version <= digit_version(mmcv_maximum_version)), \
AssertionError: MMCV==2.0.0rc4 is used but incompatible. Please install mmcv>=1.3.17, <=1.8.0.
``` 
and if I attempt to correct the version, I get
```
Traceback (most recent call last):
  File "/home/will/Work/prosfit_gait_analysis/proj-prosfit-pose-estimation/make_coco_dataset_videoset.py", line 8, in <module>
    from mmpose.apis import inference_top_down_pose_model, init_pose_model, vis_pose_result
  File "/home/will/Work/prosfit_gait_analysis/mmpose/mmpose/__init__.py", line 17, in <module>
    and mmcv_version <= digit_version(mmcv_maximum_version)), \
AssertionError: MMCV==1.7.1 is used but incompatible. Please install mmcv>=2.0.0rc4, <=2.1.0.
```

**Comment by Ben-Louis** [comment]
Hello  @vv111y , it appears that the issue might be related to the version of mmdet you have installed. For MMPose 1.x, it's compatible with mmdet 3.x and mmcv 2.x. If you've installed mmdet 2.x, you might encounter this mmcv version conflict. To resolve this, please refer to the [documentation](https://mmpose.readthedocs.io/en/dev-1.x/installation.html#prerequisites) and install mmdet 3.x, which should be compatible with your setup.

**Comment by tomik125** [comment]
Hi, Are you planning to support ViTPose+ models also?

**Comment by Tau-J** [comment]
> Hi, Are you planning to support ViTPose+ models also?

We don't have a plan fot that at the moment. If anyone from the community can help, we will appreciate a lot.
