### ISSUE TITLE
config layer_decay_rate

### ISSUE THREAD

**Issue by HyoKong** [open-mmlab/mmpose#2142]
Hi, may I ask what's the meaning of layer_decay_rate in the ViTPose config?
https://github.com/open-mmlab/mmpose/blob/cd710204e2c52b9635ad30f43e121a158e1faa08/configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_ViTPose-base_8xb64-210e_coco-256x192.py#L16

**Comment by LareinaM** [comment]
Hi, thank you for using MMPose. As from the [original paper](https://arxiv.org/abs/2204.12484), 

> We sweep the layer-wise learning rate decay [[46](https://papers.nips.cc/paper_files/paper/2019/hash/dc6a7e655d7e5840e66733e9ee67cc69-Abstract.html)] and stochastic drop path ratio for each model, and the optimal settings are provided in Table 1.

You can refer to these two pieces of research for detailed information.

**Comment by HyoKong** [comment]
okok, thank you!
