### ISSUE TITLE
After convert rtmdet model to openvino format, the inference time is slower its pytorch format.

### ISSUE THREAD

**Issue by aixiaodewugege** [open-mmlab/mmpose#2144]
Hi, I tried to convert the RTMdet model to openvino format to increase its speed, however I found the time for every inference became longer.

I think I have convert the model successfully, for the openvino output looks same as pytorch.

Have you test it with the openvino sdk? Can it be fixed or did I mise taking anything?

here is my deploy config:

{
    "version": "1.0.0rc3",
    "codebase": {
        "task": "ObjectDetection",
        "codebase": "mmdet",
        "version": "3.0.0rc6",
        "pth": "https://download.openmmlab.com/mmdetection/v3.0/rtmdet/rtmdet_tiny_8xb32-300e_coco/rtmdet_tiny_8xb32-300e_coco_20220902_112414-78e30dcc.pth",
        "config": "../mmdetection/configs/rtmdet/rtmdet_tiny_8xb32-300e_coco.py"
    },
    "codebase_config": {
        "type": "mmdet",
        "task": "ObjectDetection",
        "model_type": "end2end",
        "post_processing": {
            "score_threshold": 0.05,
            "confidence_threshold": 0.005,
            "iou_threshold": 0.5,
            "max_output_boxes_per_class": 200,
            "pre_top_k": 5000,
            "keep_top_k": 100,
            "background_label_id": -1
        }
    },
    "onnx_config": {
        "type": "onnx",
        "export_params": true,
        "keep_initializers_as_inputs": false,
        "opset_version": 11,
        "save_file": "end2end.onnx",
        "input_names": [
            "input"
        ],
        "output_names": [
            "dets",
            "labels"
        ],
        "input_shape": null,
        "optimize": true
    },
    "backend_config": {
        "type": "openvino",
        "model_inputs": [
            {
                "opt_shapes": {
                    "input": [
                        1,
                        3,
                        640,
                        640
                    ]
                }
            }
        ]
    },
    "calib_config": {}
}

**Comment by Tau-J** [comment]
Thanks for your response. We haven't test it with openvine. Maybe you can create an issue to mmdet.
