### ISSUE TITLE
higherHRNet performance question

### ISSUE THREAD

**Issue by HoBeom** [open-mmlab/mmpose#215]
Hi, I'm testing higherHRNet (Bottom Up) video demo.
During it, I have a question about single, multi person performance.
Other bottom up methods provide constant performance regardless of the number of people. 
But in this code, higherHRNet has low performance in multi-person inference.
If you have a reason or a clue for this, please let me know.
Thanks.

**Comment by jin-s13** [comment]
More information is needed to reproduce the results. 
Can you share us some example video frames that HigherHRNet does not perform well? And what config file & command do you use?

**Comment by HoBeom** [comment]
My ENV is 
RTX 3080, CUDA 11, Pytorch 1.8.0
I'm selected 2 video, single person and multi person as
Single : [50 TOPROCKS & VARIATIONS Under 5 Minutes](https://www.youtube.com/watch?v=zMhTaatkbLc) 00:00:20 ~ 8010 frames
Multi :  [Down at the Twist & Shout](https://www.youtube.com/watch?v=lv-h4WNnw0g) 4006 frames

**Comment by jin-s13** [comment]
So the `performance` here means speed not accuracy, right?

**Comment by HoBeom** [comment]
Yes, How can I improve speed ?

**Comment by jin-s13** [comment]
The speed difference is caused by the post-processing (or grouping) procedure. You may improve the inference speed by editing the config file:

set flip_test=False (line 80 in bottomup-res50)
set refine=False (line 79 in bottomup-res50)
use smaller input image size (line 39 in bottomup-res50)

**Comment by HoBeom** [comment]
Thanks. Im trying again soon and let you know.

**Comment by HoBeom** [comment]
I got similar speeds in both single and multi as is well known.
In higherHRNet_512x512, previously mentioned single person video 87.52 ms, multi person video 97.63 ms per frame.
In mobilenetV2 as fastest model(?) in bottom up, single 32.89 ms, multi 46.93 ms. 

However, i got some issue at tool/test.py bottom-up eval.
During test higherHRNet_coco_512x512 and mobilenetV2, process was killed with out error. 
I'm using original config, ENV is RTX 3080, CUDA 11.0, pytorch 1.7.0 official docker. and top-down eval works well.
```
python tools/test.py configs/bottom_up/mobilenet/coco/mobilenetv2_coco_512x512.py models/pytorch/bottomUp/mobilenetv2/mobilenetv2_coco_512x512-4d96e309_20200816.pth
loading annotations into memory...
Done (t=0.16s)
creating index...
index created!
=> num_images: 5000
[>>>>>>>>>>>>>>>>>>>>                              ] 2025/5000, 1.8 task/s, elapsed: 1099s, ETA:  1615s[1]    23853 killed     python tools/test.py
```

**Comment by jin-s13** [comment]
Hi, we have also noticed this problem. This is caused by insufficient memory.
This problem will be fixed by #229

**Comment by HoBeom** [comment]
Thanks a lot. @jin-s13

**Comment by alaa-shubbak** [comment]
hello , 
i used the same model of hrnet_w32
i got this error : 

`loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
=> num_images: 396
=> load 396 samples
Killed
`
i used in the first worker_per_gpu=2 ,then i changed it to 1  but still get the same error. the job all time is killed. 
any idea to solve it?
