### ISSUE TITLE
Are there some  xxx.py  missing in the demo folder?

### ISSUE THREAD

**Issue by graceforlife** [open-mmlab/mmpose#2154]
I saw these two .py (the first and second picture) from the guide on the official website, but I didn't find it in the demo folder of github, nor did I find it in the one I downloaded locally. why is that?
![屏幕截图 2023-04-05 162619](https://user-images.githubusercontent.com/115878494/230026606-fea94b61-2100-4db1-8fe9-09d6e26249fb.png)
![屏幕截图 2023-04-05 163142](https://user-images.githubusercontent.com/115878494/230026627-3445c07e-3536-45c4-ae11-d3692bcfa77c.png)
![屏幕截图 2023-04-05 162709](https://user-images.githubusercontent.com/115878494/230026644-d3c3dee4-8742-4f92-b677-f5632d052856.png)

**Comment by graceforlife** [comment]
> Hi, thanks for using MMPose. It appears that you are using version 0.x of the code while referring to documentation for the new version 1.x. We recommend switching to branch `1.x` and using of the latest MMPose version for a seamless experience. Under branch `1.x`, you will find the file `demo/inferencer_demo.py`.
Then I want to go from 0.x to 1.x, do I need to delete 0.x and then reinstall 1.x? Or will 0.x be overwritten after installing 1.x?

**Comment by graceforlife** [comment]
Then I want to go from 0.x to 1.x, do I need to delete 0.x and then reinstall 1.x? Or will 0.x be overwritten after installing 1.x?

**Comment by Ben-Louis** [comment]
Yeah, the 0.x will be overwritten if you reinstall MMPose 1.x. But the dependency package of MMPose 0.x may conflict with MMPose 1.x, so we suggest following this [installation guide](https://mmpose.readthedocs.io/en/1.x/installation.html) to reinstall MMPose 1.x to prevent potential package conflict.

**Comment by graceforlife** [comment]
> Yeah, the 0.x will be overwritten if you reinstall MMPose 1.x. But the dependency package of MMPose 0.x may conflict with MMPose 1.x, so we suggest following this [installation guide](https://mmpose.readthedocs.io/en/1.x/installation.html) to reinstall MMPose 1.x to prevent potential package conflict.

ok,3Q~
