### ISSUE TITLE
Does version 1. x not support the voxelpose algorithm?

### ISSUE THREAD

**Issue by graceforlife** [open-mmlab/mmpose#2155]
I didn't find voxelpose in 1.x, is the current version not supported yet?

**Comment by Ben-Louis** [comment]
Unfortunately, the current version does not support voxelpose. However, there are plans to support it in future releases.

**Comment by graceforlife** [comment]
> Unfortunately, the current version does not support voxelpose. However, there are plans to support it in future releases.

ok,3Q~
