### ISSUE TITLE
the mmpose.apis docs has changed? i can't find the functions I need

### ISSUE THREAD

**Issue by StephStates** [open-mmlab/mmpose#2162]
I notice that the docs on the website has changed a little. But now I can't find the "inference_bottom_up_pose_model" from the mmpose.apis, which still work yesterday.

**Comment by Tau-J** [comment]
Thanks for using MMPose. Yes, we switch to MMPose 1.0 today. If you are still using 0.x version, please refer to [here](https://mmpose.readthedocs.io/en/0.x/) for the previous docs.

**Comment by StephStates** [comment]
> Thanks for using MMPose. Yes, we switch to MMPose 1.0 today. If you are still using 0.x version, please refer to [here](https://mmpose.readthedocs.io/en/0.x/) for the previous docs.

tks a lot
