### ISSUE TITLE
Checkpoint link is not available

### ISSUE THREAD

**Issue by HyoKong** [open-mmlab/mmpose#2174]
Hi, it seems that the download link of vitpose-b w/ simple decoder is not available. 
https://github.com/open-mmlab/mmpose/blob/main/configs/body_2d_keypoint/topdown_heatmap/coco/vitpose_coco.md
Could you please help to update the download link?

Thank you so much!

**Comment by Tau-J** [comment]
Hi @HyoKong , tks for your feedback. We'll fix it in https://github.com/open-mmlab/mmpose/pull/2180 , the link in this PR can be used.
