### ISSUE TITLE
Why was 3d pose estimation removed from v1.0.0?

### ISSUE THREAD

**Issue by noeykan** [open-mmlab/mmpose#2181]
I'm using videopose3d for 3d pose estimation, but in new release v1.0.0, I couldn't find it anymore.

Why was it removed? Any plan to add these 3d pose things to v1.0.0?

**Comment by Tau-J** [comment]
Thanks for using MMPose. Currently, a part of the algorithms have been migrated to v1.0.0, and the remaining algorithms will be completed in subsequent versions. We will show the migration progress [here](https://github.com/open-mmlab/mmpose#0x--1x-migration)

**Comment by noeykan** [comment]
@Tau-J Thank you for your quick and kind reply. If you don't mind, could you give me a rough schedule for videopose3d algorithm?

**Comment by Tau-J** [comment]
The algorithm related to 3D pose will be migrated this quarter. We will first conduct the migration of SimpleBaseline3D. VideoPose3D will be scheduled after the completion of SimpleBaseline3D.

**Comment by noeykan** [comment]
@Tau-J thank you!
