### ISSUE TITLE
multi-head design

### ISSUE THREAD

**Issue by syusukee** [open-mmlab/mmpose#219]
hi，if I would like to use multi-head for the keypoint prediction, there is only one key word("keypoint_head") in the model config, how can I realize it? Could you give me some advice?  Hope for your reply! @jin-s13

**Comment by jin-s13** [comment]
Three steps to achieve this.

1) In the config, simply modify this
https://github.com/open-mmlab/mmpose/blob/3028b9f4e4a0bdccf322979436291eccefb86ac1/configs/top_down/resnet/coco/res50_coco_256x192.py#L44
to make `keypoint_head` a list of dict, for example:
`
keypoint_head = [dict(...), dict(...), ...]
`

2) You may also modify this line, and use a for-loop to build multiple heads.
https://github.com/open-mmlab/mmpose/blob/3028b9f4e4a0bdccf322979436291eccefb86ac1/mmpose/models/detectors/top_down.py#L44

3) And modify the forward functions to support multiple heads.

https://github.com/open-mmlab/mmpose/blob/master/mmpose/models/detectors/top_down.py

================================================================================

By the way, what are these heads for? Maybe we can give an example of using `multi_head` models later.

**Comment by syusukee** [comment]
Thanks a lot!! I've read some paper that they combine classification or some other tasks with keypoints, so maybe you could add an example for the multi-head usage, it's a useful one!!
