### ISSUE TITLE
MultiTask with MMDetection

### ISSUE THREAD

**Issue by austinmw** [open-mmlab/mmpose#2190]
Hi, I saw that there's a MultiTask class implemented. I'm trying to determine the easiest way in openmmlab to perform multi-task learning combining detection and superresolution. Would it make sense to use this class for this or is there a better way to go about it?

**Comment by Ben-Louis** [comment]
Hi @austinmw, the `MultiTask` class in MMPose is designed to support multiple heads for various pose estimation tasks. However, it is not suitable for handling detection and superresolution tasks. For more relevant information and guidance, we recommend raising issues in the [MMDetection](https://github.com/open-mmlab/mmdetection) or [MMEditing](https://github.com/open-mmlab/mmediting) repositories.
