### ISSUE TITLE
LiteHRNet inference speed

### ISSUE THREAD

**Issue by moonsh** [open-mmlab/mmpose#2194]
After deploying, I tested the ONNX model on CPU. 
The FPS reached around 45 and the latency was around 21ms.  I think latency is correct which is almost the same as in the paper.

However, HRNet is also able to reach this FPS speed. so I wonder if this LiteHRNet speed is correct. I thought LiteHRNet should be two or three times faster than HRNet

I used these two models.

LiteHRNet ( [LiteHRNet-18](https://github.com/open-mmlab/mmpose/tree/main/configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_litehrnet-18_8xb64-210e_coco-256x192.py) )

HRNet ( [pose_hrnet_w32_fp16](https://github.com/open-mmlab/mmpose/tree/main/configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_hrnet-w32_fp16-8xb64-210e_coco-256x192.py) )

**Comment by Tau-J** [comment]
I think your result is correct. LiteHRNet is not that fast on our device.

**Comment by moonsh** [comment]
Thank you @Tau-J  . Do you know any reason for this?

**Comment by Tau-J** [comment]
Sorry for late reply. Based on my experience, LiteHRNet doesn't have a significant advantage in terms of speed, but I can't provide any specific reason for that.

**Comment by moonsh** [comment]
I see. Thank you for the reply.
