### ISSUE TITLE
RTMPose Quantization using NCNN

### ISSUE THREAD

**Issue by moonsh** [open-mmlab/mmpose#2203]
I wanted to reduce the size of rtmpose-tiny model through NCNN quantization.

Converting to NCNN without quantization is fine but when the quantization function is on I got an error like below. 
Quantization for RTMPose is not supported yet?

#### Error

loading annotations into memory...
Done (t=0.23s)
creating index...
index created!
2023-04-11:14:10:34 - root - ERROR - 0
Traceback (most recent call last):
  File "/mmdeploy/mmdeploy/utils/utils.py", line 41, in target_wrapper
    result = target(*args, **kwargs)
  File "/mmdeploy/tools/onnx2ncnn_quant_table.py", line 47, in get_table
    input_tensor = input_data[0]
KeyError: 0
04/11 14:10:34 - mmengine - ERROR - tools/deploy.py - create_process - 82 - ncnn quant table failed.

#### And I used this command for deployment.

python tools/deploy.py configs/mmpose/pose-detection_simcc_ncnn-fp16_static-256x192.py ../mmpose/projects/rtmpose/rtmpose/body_2d_keypoint/rtmpose-t_8xb256-420e_coco-256x192.py ../mmpose/rtmpose-tiny_simcc-coco_pt-aic-coco_420e-256x192.pth demo/resources/human-pose.jpg --work-dir test3 --device cpu --quant

**Comment by Tau-J** [comment]
Yes, the current quantized performance of RTMPose and RTMDet is not very good. We plan to optimize this issue in subsequent versions.

**Comment by Tau-J** [comment]
The quantization is not supported.

**Comment by irexyc** [comment]
@moonsh 

Please modify ncnn code like this https://github.com/Tencent/ncnn/pull/4658 and try your command again

For custom quant image, I am fixing the dataloader and will update code soon
