### ISSUE TITLE
RuntimeError: mmpose is not installed. Please install it first.

### ISSUE THREAD

**Issue by nanshanvv** [open-mmlab/mmpose#2204]
Here is the whole process：

1. I created the virtual environment in anaconda and downloaded all the required files according to the mmpose documentation
2. Because of some bugs I decided to use the command `conda remove -n openmmlab --all` to remove this virtual environment and wanted to do a re-download of mmpose
3. When I created the corresponding virtual environment (with a different name than the one in step 1) according to the documentation again, and performed the operation of downloading the relevant dependency files, the following prompt appeared:
![image](https://user-images.githubusercontent.com/77189526/231345289-aee24370-bef5-45d5-9648-1e6491804bc0.png)
it says **Requirement already satisfied**
4.When I run `mim download mmpose --config td-hm_hrnet-w48_8xb32-210e_coco-256x192 --dest .` to download the configuration file and the model weights file, the following prompt appears：
![image](https://user-images.githubusercontent.com/77189526/231345727-c8306af5-d777-49e0-8fc8-819c829583fe.png)
5.Finally, I ran `pip show mmpose`
![image](https://user-images.githubusercontent.com/77189526/231345896-f65593b3-3041-4f69-b4f6-a3e1a4920fdb.png)

**Comment by nanshanvv** [comment]
Additional content：
When I run `mim install "mmcv>=2.0.0"`，the following situations occur：
![image](https://user-images.githubusercontent.com/77189526/231351842-d91a0a80-04a2-45ab-8328-307974de46d3.png)

**Comment by Tau-J** [comment]
Thanks for using MMPose. It seems that the pytorch you installed is imcompatible with your runtime CUDA version.
You can use `nvidia-smi` to check the runtime version, and make sure that torch version is matched. For example, if CUDA runtime is 11.1, you need to install `torch==xxx+cu111`.
`mmcv` requires strictly consistency between torch and CUDA. For more details you can refer to [install docs](https://mmcv.readthedocs.io/en/latest/get_started/installation.html)

**Comment by nanshanvv** [comment]
> Thanks for using MMPose. It seems that the pytorch you installed is imcompatible with your runtime CUDA version. You can use `nvidia-smi` to check the runtime version, and make sure that torch version is matched. For example, if CUDA runtime is 11.1, you need to install `torch==xxx+cu111`. `mmcv` requires strict consistency between torch and CUDA. For more details you can refer to [install docs](https://mmcv.readthedocs.io/en/latest/get_started/installation.html)

It worked, thanks!
