### ISSUE TITLE
Error running `mim install "mmdet>=3.0.0"`

### ISSUE THREAD

**Issue by nanshanvv** [open-mmlab/mmpose#2206]
When I run` mim install "mmdet>=3.0.0"`, I get the following error
![image](https://user-images.githubusercontent.com/77189526/231377357-c4f1a960-252a-4197-b1f3-522d5951c00e.png)
What should I do?

**Comment by Tau-J** [comment]
This is an issue of pycocotools on windows. You can try installing ` pycocotools-window` or google about how to install `pycocotools` on windows.

**Comment by nanshanvv** [comment]
> 

This problem was solved by downloading the corresponding Microsoft C++ Build Tools, thank you for your prompt answer.

**Comment by colt18** [comment]
A better solution without downloading C++ Build Tools. Install pycocotools from conda-forge.

` conda install -c conda-forge pycocotools`

Then continue with:

`mim install "mmdet>=3.0.0"`.

pycocotools wil be satisfied and won't be compiled. Enjoy.
