### ISSUE TITLE
register new head in mmpose model

### ISSUE THREAD

**Issue by alaa-shubbak** [open-mmlab/mmpose#2211]
Hello ,
 I would like to thank you for your effort in develop such a library. 
i am wondering how to add my new head within the config of mmpose , especially the model. 

i build my own head , try to register it . but it did not work, it gives me the following error : 
`ModuleNotFoundError: No module named 'mmpose.models.heads.xxxxx'`

If there is any instructions that helps me to understand how to build and add my own head ,
or if there is any ideas or hints that help me to be sure that my head is combatable with my model, please share it with me. 

 i would be so thankful to have it.  

thanks.

**Comment by Tau-J** [comment]
Hi @alaa-shubbak , all new modules need to be registered using Registry and imported in __init__.py in the corresponding directory before we can create their instances from configs. [The Config Docs](https://mmpose.readthedocs.io/en/1.x/user_guides/configs.html) may help.
