### ISSUE TITLE
[BUG] ImportError: dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by ThomaswellY** [open-mmlab/mmpose#2215]
TAG:v1.0.0

Describe the BUG:

        when i run the tools/train.py, the BUG reports as follow:

 File "/home/yhao/project/mmpose_1.X/tools/train.py", line 6, in <module>
    from mmengine.runner import Runner
  File "/home/yhao/miniconda3/envs/mmpose_1.X/lib/python3.8/site-packages/mmengine/runner/__init__.py", line 2, in <module>
    from .amp import autocast
  File "/home/yhao/miniconda3/envs/mmpose_1.X/lib/python3.8/site-packages/mmengine/runner/amp.py", line 11, in <module>
    from mmengine.utils.dl_utils import TORCH_VERSION
  File "/home/yhao/miniconda3/envs/mmpose_1.X/lib/python3.8/site-packages/mmengine/utils/dl_utils/__init__.py", line 3, in <module>
    from .collect_env import collect_env
  File "/home/yhao/miniconda3/envs/mmpose_1.X/lib/python3.8/site-packages/mmengine/utils/dl_utils/collect_env.py", line 8, in <module>
    import cv2
  File "/home/yhao/miniconda3/envs/mmpose_1.X/lib/python3.8/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/yhao/miniconda3/envs/mmpose_1.X/lib/python3.8/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/home/yhao/miniconda3/envs/mmpose_1.X/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: dlopen: cannot load any more object with static TLS

        I found the error happens in "from mmengine.runner import Runner"
        and I retried another script, which only contains one command "from mmengine.runner import Runner"
        the same error happens again. So maybe it's because of my dependence packages?
        the details of enviroment is shown as follows:
Environment:
absl-py                 1.4.0
addict                  2.4.0
attrs                   22.2.0
cachetools              5.3.0
certifi                 2022.12.7
charset-normalizer      3.1.0
chumpy                  0.70
click                   8.1.3
colorama                0.4.6
contourpy               1.0.7
coverage                7.2.2
cycler                  0.11.0
Cython                  0.29.34
exceptiongroup          1.1.1
flake8                  6.0.0
flit_core               3.8.0
fonttools               4.39.3
future                  0.18.3
google-auth             2.17.3
google-auth-oauthlib    0.4.6
grpcio                  1.53.0
idna                    3.4
importlib-metadata      6.1.0
importlib-resources     5.12.0
iniconfig               2.0.0
interrogate             1.5.0
isort                   4.3.21
json-tricks             3.16.1
kiwisolver              1.4.4
Markdown                3.4.3
markdown-it-py          2.2.0
MarkupSafe              2.1.2
matplotlib              3.7.1
mccabe                  0.7.0
mdurl                   0.1.2
minio                   7.1.14
mkl-fft                 1.3.1
mkl-random              1.2.2
mkl-service             2.4.0
mmcv                    2.0.0rc4
mmdet                   3.0.0rc6
mmengine                0.7.0
mmpose                  1.0.0     /home/yhao/project/mmpose_1.X
model-index             0.1.11
munkres                 1.1.4
numpy                   1.23.5
oauthlib                3.2.2
opencv-python           4.7.0.72
openmim                 0.3.7
ordered-set             4.1.0
packaging               23.0
pandas                  1.5.3
parameterized           0.9.0
Pillow                  9.4.0
pip                     23.0.1
pluggy                  1.0.0
protobuf                3.19.0
py                      1.11.0
pyasn1                  0.4.8
pyasn1-modules          0.2.8
pycocotools             2.0.6
pycodestyle             2.10.0
pyflakes                3.0.1
Pygments                2.14.0
pyparsing               3.0.9
pytest                  7.2.2
pytest-runner           6.0.0
python-dateutil         2.8.2
pytz                    2023.3
PyYAML                  6.0
requests                2.28.2
requests-oauthlib       1.3.1
rich                    13.3.3
rsa                     4.9
scipy                   1.10.1
setuptools              59.5.0
six                     1.16.0
tabulate                0.9.0
tensorboard             2.12.0
tensorboard-data-server 0.7.0
tensorboard-plugin-wit  1.8.1
termcolor               2.2.0
terminaltables          3.1.10
toml                    0.10.2
tomli                   2.0.1
torch                   1.10.1
torchvision             0.11.2
typing_extensions       4.4.0
urllib3                 1.26.15
Werkzeug                2.2.3
wheel                   0.38.4
xdoctest                1.1.1
xtcocotools             1.13
yapf                    0.32.0
zipp                    3.15.0

**Comment by ly015** [comment]
The error seems to happen in OpenCV codes. Could you please try ```import cv2``` and check if it can be properly imported?

**Comment by ThomaswellY** [comment]
> 

It's ok to just import cv2, But "from mmengine.runner import Runner" still reports error even if cv2 is imported already

**Comment by HAOCHENYE** [comment]
Hi @ThomaswellY! This seems to be a systemic issue, and it has been thoroughly discussed in this [issue](https://github.com/tensorflow/models/issues/523). If you cannot upgrade the system, you can only adjust the import order.

**Comment by ThomaswellY** [comment]
I update mmengine==0.7.2, and other corresponding packages, only then import cv2 before import mmengine can fix the problem. perhaps, this solution can be applied by otherone
