### ISSUE TITLE
about head

### ISSUE THREAD

**Issue by sayoko17** [open-mmlab/mmpose#2217]
您好，想请问一下mmpose0.x版本中的TopdownHeatmapSimpleHead和1.0中的版本HeatmapHead，MSRAHeatmap，是同一个吗？请问一下在这些提供的heatmap检测中，TopdownHeatmapSimpleHead是计算最简单的（参数量较小）吗，是否有文档说明不同head的不同结果值？谢谢！

**Comment by Ben-Louis** [comment]
您好，TopdownHeatmapSimpleHead 和 HeatmapHead 功能是一样的，都是实现 [SimpleBaseline 算法](https://arxiv.org/abs/1804.06208) 的 Head。这个 Head 需要基于较高分辨率的 2D Heatmap 做关键点检测，所以要么需要 backbone 能输出高分辨率 Heatmap (例如 HRNet), 要么需要一些反卷积层增加 Heatmap 分辨率，因此计算量都比较可观。不同 head 的效果请参考这个文档： https://mmpose.readthedocs.io/en/dev-1.x/model_zoo/body_2d_keypoint.html
