### ISSUE TITLE
Error with mmDeploy

### ISSUE THREAD

**Issue by CourbotA** [open-mmlab/mmpose#2223]
Thanks for your work.
I am having this issue when trying to use rtm pose, I followed the installation instructions provided in https://github.com/open-mmlab/mmpose/tree/1.x/projects/rtmpose (I am using windows). when i check the instalation using pip list i can see mmdeploy in the list : 
![image](https://user-images.githubusercontent.com/72599332/231787594-ef521beb-8c88-46a6-a9e3-835a98b89958.png)

But when i try to run the example code it isn't detected and this error message occurs : 
![image](https://user-images.githubusercontent.com/72599332/231788570-62d531f8-139b-43a0-8be8-ee541658ae78.png)

I have tried to use a 3.8.16 and a 3.8.13 environments but the same issue occured in both cases ?

**Comment by Tau-J** [comment]
Thanks for using MMPose. We just update the guides for mmdeploy 1.0.0, you can refer to [here](https://github.com/open-mmlab/mmpose/tree/dev-1.x/projects/rtmpose#windows).
