### ISSUE TITLE
how to increase fps on cpu

### ISSUE THREAD

**Issue by sidh1603** [open-mmlab/mmpose#2229]
Hi , I m using v0.28.0 version , today when i was testing on cpu on  intel real sense camera , i was getting 30 fps (when no person was detected) and when 1 person was detected the fps reduced to 4 and when 2 person was detected the fps reduced to 2.

please , how could i increase number of fps on cpu so that i can have accurate predictions.

Thanks

**Comment by Ben-Louis** [comment]
Thanks for using MMPose. We suggest using the latest version and trying the [RTMPose](https://github.com/open-mmlab/mmpose/tree/main/projects/rtmpose).

**Comment by sidh1603** [comment]
Hi,thanks for your reply , i have clone the latest version , but dont know how to use rtmpose on my project.kind regardssiddharthSent from my iPhoneOn Apr 14, 2023, at 1:31 AM, Peng Lu ***@***.***> wrote:﻿
Thanks for using MMPose. We suggest using the latest version and trying the RTMPose.

**Comment by sidh1603** [comment]
Hi,

Actually after cloning mmpose , we used python demo/webcam_api_demo.py --cpu
to check and its working , but for rtmpose , its working on images , but
how to test on live webcam or any example.

please any help would be appreciated

**Comment by Tau-J** [comment]
For webcam inference, we suggest using [PoseTracker](https://github.com/open-mmlab/mmpose/tree/main/projects/rtmpose#python-inference) to get the maximum speed. You can specify the video path as `0` to use your local camera as inputs.

**Comment by sidh1603** [comment]
Hi,

i tried to use this command

*python pose_tracker.py cpu
C:\Users\ivc21247adm\mmpose\detection_model\rtmdet_m_8xb32-100e_coco-obj365-person-235e8209.pth
C:\Users\ivc21247adm\mmpose\pose_model\rtmpose-l_simcc-aic-coco_pt-aic-coco_420e-256x192-f016ffe0_20230126.pth
cpu*

*and also i have made changed in pose_tracker.py file , i have changed
to  video = cv2.VideoCapture(0)* ,

 but after running in terminal i am getting error



*loading mmdeploy_ort_net.dll ...[2023-04-17 23:16:10.595] [mmdeploy]
[error] [model.cpp:40] Failed to load model:
"C:/Users/ivc21247adm/mmpose/pose_model/rtmpose-l_simcc-coco-wholebody_pt-aic-coco_270e-256x192-6f206314_20230124.pth",
implementations tried: [("DirectoryModel", 0)][2023-04-17 23:16:10.595]
[mmdeploy] [error] [model.cpp:16] Failed to load model
"C:/Users/ivc21247adm/mmpose/pose_model/rtmpose-l_simcc-coco-wholebody_pt-aic-coco_270e-256x192-6f206314_20230124.pth"*







*Traceback (most recent call last):  File "pose_tracker.py", line 98, in
<module>    main()  File "pose_tracker.py", line 70, in main    tracker =
PoseTracker(RuntimeError: unknown (6)*


*please kindly provide me some solution so that i can run pose on cpu.*


*Kind Regards*
*Siddharth*

**Comment by Tau-J** [comment]
When using `pose_tracker`, please pass the folder of the deployed model, instead of the model file.

**Comment by sidh1603** [comment]
Hi Tau,thanks for your replyi have installed mmdeploy by python inference as sdk as per your documentation.Sent from my iPhoneOn Apr 17, 2023, at 11:45 PM, Tau ***@***.***> wrote:﻿
When using pose_tracker, please pass the folder of the deployed model, instead of the model file.

**Comment by sidh1603** [comment]
Hi,please can you provide me some example.Sent from my iPhoneOn Apr 18, 2023, at 12:40 AM, Siddharth Rana ***@***.***> wrote:﻿Hi Tau,thanks for your replyi have installed mmdeploy by python inference as sdk as per your documentation.Sent from my iPhoneOn Apr 17, 2023, at 11:45 PM, Tau ***@***.***> wrote:﻿
When using pose_tracker, please pass the folder of the deployed model, instead of the model file.

**Comment by sidh1603** [comment]
Hi Tau,

I have some doubts regarding installation, the way i have installed are

1) i have git clone mmpose and inside projects / rtmpose  , i have run
command
wget
https://github.com/open-mmlab/mmdeploy/releases/download/v1.0.0rc3/mmdeploy-1.0.0rc3-linux-x86_64-onnxruntime1.8.1.tar.gz
tar -xzvf mmdeploy-1.0.0rc3-linux-x86_64-onnxruntime1.8.1.tar.gz
cd mmdeploy-1.0.0rc3-linux-x86_64-onnxruntime1.8.1/sdk
source env.sh
bash opencv.sh
bash build.sh
./bin/det_pose {det work-dir} {pose work-dir} {your_img.jpg} --device cpu
./bin/pose_tracker {det work-dir} {pose work-dir} {your_video.mp4} --device
cpu

and after that i have clone  mmdeploy in mmpose directory
then cd mmdeploy and i used the command

mim download mmpose --config td-hm_hrnet-w32_8xb64-210e_coco-256x192
--dest .# convert mmdet model to onnxruntime model with static shape
python tools/deploy.py \
configs/mmpose/pose-detection_onnxruntime_static.py \
td-hm_hrnet-w32_8xb64-210e_coco-256x192.py \
hrnet_w32_coco_256x192-c78dce93_20200708.pth \
demo/resources/human-pose.jpg \    --work-dir
mmdeploy_models/mmpose/ort \    --device cpu \    --show

i am getting error -

*mmengine - INFO - Successfully loaded onnxruntime custom ops from
/home/dell-cv1/Music/mmpose/mmdeploy/mmdeploy/lib/libmmdeploy_onnxruntime_ops.so*


* corrupted size vs. prev_size 04/18 15:14:23 - mmengine - ERROR -
tools/deploy.py - create_process - 82 - visualize onnxruntime model failed.*


*please can you tell the proper way of installation .*

*Kind Regards*

*Siddharth*

**Comment by sidh1603** [comment]
Hi,

as per your pose_tracker.py  , i have used command
*python pose_tracker.py cpu
/home/dell-cv1/pictures/open_lab/mmdeploy/mmdeploy_models/mmpose/ort/end2end.onxx
/home/dell-cv1/pictures/open_lab/mmdeploy/mmdeploy_models/mmpose/ort/end2end.onxx
/home/dell-cv1/pictures/mmdeploy/video_1.mp <http://video_1.mp>*

*but it still giving me error : *






*Traceback (most recent call last):  File "pose_tracker.py", line 98, in
<module>    main()  File "pose_tracker.py", line 70, in main    tracker =
PoseTracker(RuntimeError: unknown (6) @
/home/dell-cv1/pictures/open_lab/mmdeploy/mmdeploy_models/mmpose/ort/:654558208*

**Comment by Tau-J** [comment]
> When using `pose_tracker`, please pass the folder of the deployed model, instead of the model file. BTW, `pose_tracker` requires model be converted by mmdeploy, which means that the model should be `.onnx`, not the `.pth`.
> 
> If you just want to try cpu inference with `.pth`, you can use the `demo/topdown_demo_with_mmdet.py` in `dev-1.x` branch. It is updated in #2244

@sidh1603 
1. As I mentioned, you should pass **the folder of model, not the model file** to `pose_tracker.py`.
2. We update the docs and make it easier to deploy in `dev-1.x`, you can refer to [here](https://github.com/open-mmlab/mmpose/tree/dev-1.x/projects/rtmpose)
