### ISSUE TITLE
LiteHRNet Quantization Error

### ISSUE THREAD

**Issue by moonsh** [open-mmlab/mmpose#2230]
The below command I tried for generating INT8 litehrnet model.

python tools/deploy.py configs/mmpose/pose-detection_ncnn-int8_static-256x192.py ../mmpose/configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_litehrnet-18_8xb64-210e_coco-256x192.py ../mmpose/litehrnet18_coco_256x192.pth  demo/resources/human-pose.jpg --work-dir litehrnet_ncnn --device cpu --dump-info --quant --quant-image-dir imagenet-sample-images/

However, it keeps failing when it's generating a quant table. 
and error message is below

AttributeError: 'ConfigDict' object has no attribute '_env_variables'
 mmengine - ERROR - tools/deploy.py - create_process - 82 - ncnn quant table failed.

**Comment by Tau-J** [comment]
Hi @moonsh , I suggest raising an issue to mmdeploy, maybe they can give you some help.

**Comment by moonsh** [comment]
Yes. Thank you.
https://github.com/open-mmlab/mmdeploy/issues/1991
