### ISSUE TITLE
About whether RTMpose is able to applied on smartphone

### ISSUE THREAD

**Issue by kdavidlp123** [open-mmlab/mmpose#2232]
Hi, thank you for your latest release of RTMpose. It is a great work.
And I would like to ask is it possible to run the model on the smartphone and get the real-time detection of keypoints using the camera of smartphone .
Because I am little confused of [this](https://github.com/open-mmlab/mmpose/tree/main/projects/rtmpose#%EF%B8%8F-how-to-deploy-). Is it  the protocol of converting the model to compatible mode for mobile device?

**Comment by Tau-J** [comment]
Yes, RTMPose can conduct real-time detection after deploying on smartphone.
