### ISSUE TITLE
rtmpose wholebody consider a s vesion model?

### ISSUE THREAD

**Issue by luohao123** [open-mmlab/mmpose#2233]
hi, currently the smallest model is m, it's still slow on some lower compute devices, would be great if can provide a s version of whole body model.

thank u!

**Comment by Tau-J** [comment]
Thanks for using MMPose. We think model smaller than m may not meet the accuracy requirement. Maybe you can train it by yourself.

**Comment by luohao123** [comment]
@Tau-J  the accuracy dependes on how many kpts you training on, it was awkard that rtmpose-m-whobody is slow but the rtmpose-s 17 kpts version can not meet my requirements on keypoints num, maybe have a 22 kpts version could more useful?
