### ISSUE TITLE
Simple way to get prediction output from pretrained model ?

### ISSUE THREAD

**Issue by moonsh** [open-mmlab/mmpose#2234]
I wanted to pass input to a model and get prediction results directly like below without using the visualizer tool in mmengine.
Is there a simple way to do this?

x = torch.randn(1, 1, 256, 192, requires_grad=True)
torch_out = model(x)

**Comment by Ben-Louis** [comment]
Thank you for using MMPose. To directly pass input to a model and obtain prediction results without using the visualizer tool in mmengine, you can make use of the Inferencer. The Inferencer provides a unified inference interface to achieve this.

You can refer to the documentation on [Inferencer](https://mmpose.readthedocs.io/en/latest/user_guides/inference.html#inferencer-a-unified-inference-interface) for more information and guidance on how to use it.

**Comment by colt18** [comment]
@Ben-Louis Can we access to the output image as a matrix instead of pop-up.

**Comment by Ben-Louis** [comment]
> @Ben-Louis Can we access to the output image as a matrix instead of pop-up.

Hi @colt18, as introduced in the document on [Inferencer](https://mmpose.readthedocs.io/en/latest/user_guides/inference.html#inferencer-a-unified-inference-interface),  if the `return_vis` argument is set to `True`, the image array (including pose visualization) can be found within the poped result.
