### ISSUE TITLE
version 

### ISSUE THREAD

**Issue by hsp2454** [open-mmlab/mmpose#2238]
If I use the version of mmpose0.x, I want to use the newly added functions of mmpose1.x, can I only re-git the new version. Also, the faster rcnn I trained in mmdetection2.25.2 can be used in mmpose0.x, so can it be used in mmpose1.x? Do I need to update the version of mmdetection to the latest?

**Comment by Tau-J** [comment]
Thanks for using MMPose. 

1. MMPose v1.0.0 is a major update, including many API and config file changes, and most of the code in MMPose 1.0 will not be compatible with 0.x version.
2. Here are the version correspondences between `mmdet` and `mmpose`:
  - MMDetection 2.x <=> MMPose 0.x <=> MMCV 1.x
  - MMDetection 3.x <=> MMPose 1.x <=> MMCV 2.x

**Comment by hsp2454** [comment]
Thank you!

**Comment by hsp2454** [comment]
My mmpose is 0.x, when I train HrNet,
The following evaluation is set,
`evaluation = dict(interval=20, metric='PCK', save_best='PCK'),` then how do I evaluate the accuracy of this model? I can only output one PCK value with tools\test.py. Is there any way Do you output other evaluation indicators, such as OKS, mAP, etc.
