### ISSUE TITLE
image_demo.py: error: unrecognized arguments: /--out-file vis_results.jpg /--draw-heatmap

### ISSUE THREAD

**Issue by Ezreal0211** [open-mmlab/mmpose#2242]
when I installed the mmpose，I want to verify if my installation was successful.So I followed the Verification steps.The first step is ok,(mim download mmpose --config td-hm_hrnet-w48_8xb32-210e_coco-256x192 --dest .)
but the second step gave me this error.
The command code is as follows：
python demo/image_demo.py \
       tests/data/coco/000000000785.jpg \
       td-hm_hrnet-w48_8xb32-210e_coco-256x192.py \
       hrnet_w48_coco_256x192-b9e0b3ab_20200708.pth \
       --out-file vis_results.jpg \
       --draw-heatmap 
I don't know why.Please help me and thanks for everyone!(I used the newest installation of mmpose)

**Comment by Tau-J** [comment]
Could you print the result of 'pip list | grep mm' on your env? BTW, which branch are you using?

**Comment by Ezreal0211** [comment]
Yes，I can print the result of pip list.What mean of you said 'branch'?
`(openmmlab) D:\anaconda\envs\openmmlab\mmpose>pip list
Package             Version   Editable project location
------------------- --------- ---------------------------------
addict              2.4.0
attrs               22.2.0
brotlipy            0.7.0
certifi             2022.12.7
cffi                1.15.1
charset-normalizer  2.0.4
chumpy              0.70
click               8.1.3
colorama            0.4.6
contourpy           1.0.7
coverage            7.2.3
cryptography        39.0.1
cycler              0.11.0
Cython              0.29.34
exceptiongroup      1.1.1
filelock            3.9.0
flake8              6.0.0
flit_core           3.8.0
fonttools           4.39.3
idna                3.4
importlib-metadata  6.2.0
importlib-resources 5.12.0
iniconfig           2.0.0
interrogate         1.5.0
isort               4.3.21
Jinja2              3.1.2
json-tricks         3.16.1
kiwisolver          1.4.4
Markdown            3.4.3
markdown-it-py      2.2.0
MarkupSafe          2.1.1
matplotlib          3.7.1
mccabe              0.7.0
mdurl               0.1.2
mkl-fft             1.3.1
mkl-random          1.2.2
mkl-service         2.4.0
mmcv                2.0.0
mmdet               3.0.0
mmengine            0.7.2
mmgen               0.7.2
mmpose              1.0.0     d:\anaconda\envs\openmmlab\mmpose
model-index         0.1.11
mpmath              1.2.1
munkres             1.1.4
networkx            2.8.4
numpy               1.23.5
opencv-python       4.7.0.72
openmim             0.3.7
ordered-set         4.1.0
packaging           23.0
pandas              2.0.0
parameterized       0.9.0
Pillow              9.4.0
pip                 23.0.1
pluggy              1.0.0
py                  1.11.0
pycocotools         2.0.6
pycodestyle         2.10.0
pycparser           2.21
pyflakes            3.0.1
Pygments            2.14.0
pyOpenSSL           23.0.0
pyparsing           3.0.9
PySocks             1.7.1
pytest              7.3.1
pytest-runner       6.0.0
python-dateutil     2.8.2
pytz                2023.3
PyYAML              6.0
regex               2023.3.23
requests            2.28.1
rich                13.3.3
scipy               1.10.1
setuptools          57.5.0
shapely             2.0.1
six                 1.16.0
sympy               1.11.1
tabulate            0.9.0
termcolor           2.2.0
terminaltables      3.1.10
toml                0.10.2
tomli               2.0.1
torch               2.0.0
torchvision         0.15.0
typing_extensions   4.4.0
tzdata              2023.3
urllib3             1.26.15
wheel               0.38.4
win-inet-pton       1.1.0
wincertstore        0.2
xdoctest            1.1.1
xtcocotools         1.13
yapf                0.32.0
zipp                3.15.0`

**Comment by Ezreal0211** [comment]
sorry, I think I'm using MMPose v1.0.0 .(the new version)

**Comment by Tau-J** [comment]
Sorry, I cannot reproduce your error. Could you try reinstalling mmpose again? or you can clone the 0.x branch and install via `pip install -e .`

**Comment by Ezreal0211** [comment]
Thanks! but the current error is the result of reinstalling mmpose.

**Comment by Tau-J** [comment]
Could you share the entire command you use? or a screenshot of that.

**Comment by Ezreal0211** [comment]
Perhaps I didn't express myself clearly, here are the commands I entered.
![image](https://user-images.githubusercontent.com/125781444/232425057-c6e0393c-9964-454a-b896-bdcc80b93308.png)

**Comment by Ezreal0211** [comment]
Sorry，should I delete all the `/`？

**Comment by Tau-J** [comment]
Please show the screenshot

**Comment by Tau-J** [comment]
I mean, use `--out-file` and `--draw-heatmap`, instead of `/--out-file` and `/--draw-heatmap`

**Comment by Ezreal0211** [comment]
![image](https://user-images.githubusercontent.com/125781444/232427575-71e47025-f5ef-405e-a5f3-93a16c9b55f1.png)
![image](https://user-images.githubusercontent.com/125781444/232427655-858ca7c1-7f4c-420c-8492-245921a3dc9b.png)
The error report and my file placement are shown in the screenshot.

**Comment by Tau-J** [comment]
I think you miss the `td-` in filename

**Comment by Tau-J** [comment]
Thanks for your response. Would you like to create a PR to fix this?

**Comment by Ezreal0211** [comment]
Yes! I want to solve the problem. But I don't know how to create a PR.Could you help me to create a PR?Thank you !

**Comment by Tau-J** [comment]
[Here](https://mmpose.readthedocs.io/en/1.x/contribution_guide.html) is the contribution guide, you can fix this link in `mmpose/docs/en/installation.md` and `mmpose/docs/zh_cn/installation.md`
