### ISSUE TITLE
Aboout the elements of 3d kepoints array

### ISSUE THREAD

**Issue by Kazusaisjustice** [open-mmlab/mmpose#2245]
Hello, I ran the 'body3d_two_stage_video_demo.py' to get the coordinates of 3d keypoints. I confused on why the 3d coordinates are too much smaller than 2d coordinates as follow,
![AUSL_IYKIHRBAGWMMHNE786](https://user-images.githubusercontent.com/108652440/232466203-e44a4b23-af2c-4d45-9d53-7c455f31e8a0.png)

So how can I understand these? And what should I do if I want to adjust these?

**Comment by Tau-J** [comment]
@ly015 Could you give some suggestions?

**Comment by LareinaM** [comment]
Hi, thanks for using MMPose. The 3d training label we used is obtained from the original human3.6m dataset, divided by 1000, as you can check that the coordinates are between -1 and 1.
