### ISSUE TITLE
How to obtain the data in file 【test_interhand2.6m_joint_3d.json】 of Project InterHand3d hand keypoints?

### ISSUE THREAD

**Issue by Han-WG** [open-mmlab/mmpose#2249]
There is a key keypoints_3d_gt parameter that is used to convert the gt joint from world space to camera space,
But I noticed that the parameter was loaded from a json file, not calculated.
So how do I get this data when I examine different images?

**Comment by LareinaM** [comment]
Hi, this json file is obtained from the InterHand2.6M dataset. If you wish to use the complete dataset, please download [here](https://mmpose.readthedocs.io/en/dev-1.x/dataset_zoo/3d_hand_keypoint.html#interhand2-6m ).

**Comment by Han-WG** [comment]
> Hi, this json file is obtained from the InterHand2.6M dataset. If you wish to use the complete dataset, please download [here](https://mmpose.readthedocs.io/en/dev-1.x/dataset_zoo/3d_hand_keypoint.html#interhand2-6m).

thanks,I found it.
Does this mean I can't get a absolute depth value through the interhand3d？

**Comment by LareinaM** [comment]
> > Hi, this json file is obtained from the InterHand2.6M dataset. If you wish to use the complete dataset, please download [here](https://mmpose.readthedocs.io/en/dev-1.x/dataset_zoo/3d_hand_keypoint.html#interhand2-6m).
> 
> thanks,I found it. Does this mean I can't get a absolute depth value through the interhand3d？

For issues related to the dataset and their data, please raise through the [original repo](https://github.com/facebookresearch/InterHand2.6M).
