### ISSUE TITLE
About human 3d keypoint coordinates 

### ISSUE THREAD

**Issue by Kazusaisjustice** [open-mmlab/mmpose#2252]
Hello, I got human 3d keypoint coordinates by 'body3d_two_stage_video_demo'. It seems to be local coordinates while the origin is human's pelvis. So can I convert it to global coordinates like 2d keypoints? Thanks!

**Comment by LareinaM** [comment]
Hi, could you please clarify your question, e.g. what keypoint coordinate you are referring to? Also, you can refer to [this code](https://github.com/open-mmlab/mmpose/blob/main/tools/dataset_converters/h36m_to_coco.py) for some ideas on converting keypoints to world coordinate.

**Comment by Kazusaisjustice** [comment]
Thanks for your replying! The 3d coordinates I got are as following,
![image](https://user-images.githubusercontent.com/108652440/232801440-74f076ae-cce4-4010-9b0a-ef7783869b70.png)
and the 2d coordinates are these,
![image](https://user-images.githubusercontent.com/108652440/232801578-8d773060-5053-451e-ab8d-a5e00fe57891.png)
It seems that the origin of 2d and 3d coordinates are different. Maybe the origin of 3d coordinates is human's pelvis? However, in our project we expect the coordinates of 3d keypoints are similar to 2d's. So what can I do for this?

**Comment by LareinaM** [comment]
Could you provide the parameters you are using?

**Comment by Kazusaisjustice** [comment]
The parameters here are?

**Comment by LareinaM** [comment]
> The parameters here are?

The arguments you passed into the python script.

**Comment by Kazusaisjustice** [comment]
If you ask for the command, there is,

python demo/body3d_two_stage_video_demo.py demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w48_coco_256x192.py https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_coco_256x192-b9e0b3ab_20200708.pth configs/body/3d_kpt_sview_rgb_vid/video_pose_lift/h36m/videopose3d_h36m_243frames_fullconv_supervised_cpn_ft.py https://download.openmmlab.com/mmpose/body3d/videopose/videopose_h36m_243frames_fullconv_supervised_cpn_ft-88f5abbb_20210527.pth --video-path video_guidedog/cid_0/GL010078.MP4 --out-video-root vis_3d_results --rebase-keypoint-height

In addition, I downloaded the 3d coordinates of human3.6m, which is quite different from yours,
![image](https://user-images.githubusercontent.com/108652440/232971053-be16f7e2-dcd8-41dc-91a1-84e04e604b09.png)
so why are the values of your 3d coordinates too much small as I mentioned before?

**Comment by Ben-Louis** [comment]
The 2D joint coordinates undergo normalization prior to being input into the pose_lifter. For more information, please refer to the transform `ImageCoordinateNormalization` for details.

 https://github.com/open-mmlab/mmpose/blob/3b8173463c4ecdcd3d82d566254bb2ae2eb0cc07/mmpose/datasets/pipelines/pose3d_transform.py#L126-L183

**Comment by Kazusaisjustice** [comment]
Thanks a lot! I got it. By the way, what should I do if I don't want to normalize 2d coordinates? Is there any  effect on the generated 3d coordinates?

**Comment by Ben-Louis** [comment]
The checkpoints we've supplied are trained using normalized inputs. You might need to retrain a model that can adapt to unnormalized 2D pose data. In fact, you could attempt to obtain the unnormalized 3D coordinates by reversing the normalization process.

**Comment by Kazusaisjustice** [comment]
So this means I can directly reverse 2d's normalization way as you mentioned above in 'ImageCoordinateNormalization' to obtain the unnormalized 3D coordinates?

**Comment by Ben-Louis** [comment]
> directly reverse 2d's normalization way as you mentioned above in 'ImageCoordinateNormalization' to obtain the unnormalized 3D coo

Sorry for misleading. The point definition and reference frame of the predicted 3D pose are different from the 2D pose, so the unnormalized 3D coordinates cannot be obtained simply by reversing the normalization process
