### ISSUE TITLE
video output after using inferencer

### ISSUE THREAD

**Issue by colt18** [open-mmlab/mmpose#2253]
Is it possible to have an output video after using `inferencer` as below:

```
inferencer = MMPoseInferencer('td-hm_hrnet-w48_dark-8xb32-210e_coco-wholebody-384x288', device='cuda:0')
result_generator = inferencer(video_path, out_dir='output', radius=1, return_vis=True, show=True)
```
currently I get only the initial image of the video. There is no video output and only 3 frames for keypoints for a 15 seconds video.

**Comment by filippuo2000** [comment]
Same here, only the initial frame of the 3 second clip as an output of inference.

**Comment by Ben-Louis** [comment]
Hi @colt18, could you please provide the command you utilized for generating predictions with `result_generator`? Additionally, were there any errors encountered during the process?

**Comment by colt18** [comment]
Hi @Ben-Louis , here is the code for inferencing:

```
from mmpose.apis import inference_topdown, init_model
video_path="myvideo.mp4"
inferencer = MMPoseInferencer('td-hm_hrnet-w32_8xb64-210e_coco-256x192')
result_generator = inferencer(video_path, out_dir='output')
result = next(result_generator)
```
Only yields 3 images.

I also ran `topdown_demo_with_mmdet.py` with the config shown in the tutorials with my video file which is 1920x1080 res and have 7 people. I get like 1 frame per like 6 seconds, and very very low GPU utilization like this:
![resim](https://user-images.githubusercontent.com/26602153/233209607-727d05f7-5dc9-4b8a-b433-c9175d3917e7.png)
Same behavior under linux and windows. Am I doing something wrong, or this is the max speed that can be achieved. Can we do batch inference? I need some directions if possible.

`python demo/topdown_demo_with_mmdet.py demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth configs/wholebody_2d_keypoint/topdown_heatmap/coco-wholebody/td-hm_hrnet-w48_dark-8xb32-210e_coco-wholebody-384x288.py https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_coco_wholebody_384x288_dark-f5726563_20200918.pth --input video.mp4 --output-root vis_results/ --show --save-predictions`

**Comment by Ben-Louis** [comment]
Thanks for your feedback @colt18.

1. The `result_generator` is an iterator, and you might need to use the following code to iterate through all the video frames:
    ```python
    results = [r for r in result_generator]
    ```

2. The `topdown_demo_with_mmdet.py` script was slow because of a visualization issue. However, this has been resolved in https://github.com/open-mmlab/mmpose/pull/2244 this week. You can try the updated demo script available in the `dev-1.x` branch.

**Comment by colt18** [comment]
Thanks @Ben-Louis ,

I have used the dev-1.x branch and now it works as expected. However, if I write a custom read from camera and process as below, I do get very low frame rates compared to webcam_demo.

```
from mmpose.apis import MMPoseInferencer

inferencer = MMPoseInferencer(
    pose2d=r"configs\wholebody_2d_keypoint\rtmpose\coco-wholebody\rtmpose-m_8xb64-270e_coco-wholebody-256x192.py",
    pose2d_weights=r"configs/rtmpose-m_simcc-coco-wholebody_pt-aic-coco_270e-256x192-cd5e845c_20230123.pth",
    det_model=r"projects/rtmpose/rtmdet/person/rtmdet_nano_320-8xb32_coco-person.py",
    det_weights=r"configs/rtmdet_nano_8xb32-100e_coco-obj365-person-05d8511e.pth",
    det_cat_ids=[0],  # the category id of 'human' class
    device='cuda:0'
)

cap = cv2.VideoCapture(0)
while cap.isOpened():
    ret, frame = cap.read()
    result_generator = inferencer(frame, return_vis=True)
    result = next(result_generator)
    out = result['visualization'][0]
    cv2.imshow('OpenCV Feed', out)
    if cv2.waitKey(10) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()
```
As you can see, I take a frame, run an inference, get the visualization result and send it to OpenCV feed. I copied this same config to webcam_demo (wholebody especially since webcam_demo default config is not wholebody) and got good results. So is it still related to visualization bug as you described, or I lack something architectural like frame buffer? Could `MMPoseInferencer` be using main branch, since I installed it with both `mim install` and `git clone`. If this is the case, I'll purge my environment and will do git clone dev-1.x. Thanks for the support btw.
