### ISSUE TITLE
RTMPose-m achieves 75.8% AP on COCO with 90+ FPS on an Intel i7-11700 CPU

### ISSUE THREAD

**Issue by sidh1603** [open-mmlab/mmpose#2254]
Hi,

As per your documentation , RTMPose-m achieves 75.8% AP on COCO with 90+ FPS on an Intel i7-11700 CPU .
Could you please explain me how to achieve that fps on cpu using live webcam stream.

because i have used mmpose , it was giving 30 fps , but when it started detecting people in the area , it reduced to 2 fps.
please help me to achieve maximum fps on cpu.

Thanks

**Comment by Tau-J** [comment]
To achieve maximum speed, you need to deploy the model by using MMDeploy, and inference with onnxruntime. For details, you can refer to our [deployment guide](https://github.com/open-mmlab/mmpose/tree/main/projects/rtmpose#%EF%B8%8F-how-to-deploy-)

**Comment by sidh1603** [comment]
Hi Tau-j,

I have done the same , but in your document nothing is mentioned for the web cam even , 

after deploying , i got mmdeploy model that is end2end.onxx

python pose_tracker.py cpu C:/Users/ivc21247adm/mmpose/detection_model/end2end.onxx C:/Users/ivc21247adm/mmpose/pose_model/end2end.onxx  / home/video,mp4

but i was getting error .

my question is how to use rtmpose for live webcam

**Comment by Tau-J** [comment]
If you want to use PoseTracker with webcam, just set `0`  as `input`.

![image](https://user-images.githubusercontent.com/13503330/232965340-8579e471-cf45-4967-b896-e735fb813ead.png)

And for the arguments, I answered in https://github.com/open-mmlab/mmpose/issues/2229

**Comment by sidh1603** [comment]
Hi,

 aftyer converting hrnet model to onnx model that can be inferred by ONNX Runtime.
i got mmdeplot model that have end2end.onxx 

pose_tracker requires model be converted by mmdeploy that is .onxx, so do i need to pass that same end2end onxx model for det_model and pose_model??

for example like  
****
python pose_tracker.py cpu C:/Users/ivc21247adm/mmpose/detection_model/end2end.onxx C:/Users/ivc21247adm/mmpose/pose_model/end2end.onxx  0

**Comment by sidh1603** [comment]
python pose_tracker.py cpu home/dell-cv1/pictures/open_lab/mmdeploy/mmdeploy_models/mmpose/ort/end2end.onxx
/home/dell-cv1/pictures/open_lab/mmdeploy/mmdeploy_models/mmpose/ort/end2end.onxx 0

*but i got this  error : *

*Traceback (most recent call last):  File "pose_tracker.py", line 98, in
<module>    main()  File "pose_tracker.py", line 70, in main    tracker =
PoseTracker(RuntimeError: unknown (6) @
/home/dell-cv1/pictures/open_lab/mmdeploy/mmdeploy_models/mmpose/ort/:654558208

**Comment by Tau-J** [comment]
![image](https://user-images.githubusercontent.com/13503330/232967330-13b2662b-d1f1-4693-9fbd-fe42d8fefb88.png)

I have answered this in https://github.com/open-mmlab/mmpose/issues/2229 , PLEASE read it.

**Comment by sidh1603** [comment]
pass the folder of the model , that make me confused because after converting the model to onxx , i got mmdeploy model folder , so how to use that folder for det_model and pose_model because pose tracker.py we have to pass  det_model=args.det_model,
 pose_model=args.pose_model,
   device_name=args.device_name

so for det_model  and pose_model do i need to pass the end2end.onxx folder??


please any example would be of great help for me.

**Comment by Tau-J** [comment]
```
python pose_tracker.py cpu home/dell-cv1/pictures/open_lab/mmdeploy/mmdeploy_models/mmpose/ort/
/home/dell-cv1/pictures/open_lab/mmdeploy/mmdeploy_models/mmpose/ort/ 0
```

**Comment by sidh1603** [comment]
in mmdeploy directory , i did the same but i got error 

main() File "pose_tracker.py", line 70, in main tracker =
PoseTracker(RuntimeError: unknown (6) @
/home/dell-cv1/pictures/open_lab/mmdeploy/mmdeploy_models/mmpose/ort/:654558208

**Comment by Tau-J** [comment]
You need to convert det model and pose model separately, so don't set the same folder as target. Here's an example:
```
python pose_tracker.py cpu mmdeploy_models/mmpose/rtmdet-sdk/ mmdeploy_models/mmpose/rtmpose-sdk/ 0
```

**Comment by sidh1603** [comment]
like this


# run the command to convert RTMDet
python tools/deploy.py \
    configs/mmdet/detection/detection_onnxruntime_static.py \
    {RTMPOSE_PROJECT}/rtmdet/person/rtmdet_nano_320-8xb32_coco-person.py \
    ../rtmdet_nano/rtmdet_nano.pth \
    demo/resources/human-pose.jpg \
    --work-dir mmdeploy_models/mmdet/ort \
    --device cpu \
    --show

# run the command to convert RTMPose
python tools/deploy.py \
    configs/mmpose/pose-detection_simcc_onnxruntime_dynamic.py \
    {RTMPOSE_PROJECT}/rtmpose/body_2d_keypoint/rtmpose-m_8xb256-420e_coco-256x192.py \
    ../rtmpose_m/rtmpose_m.pth \
    demo/resources/human-pose.jpg \
    --work-dir mmdeploy_models/mmpose/ort \
    --device cpu \
    --show

**Comment by Tau-J** [comment]
to inference with sdk, you need add `--dump-info`

**Comment by sidh1603** [comment]
python tools/deploy.py \
    configs/mmdet/detection/detection_onnxruntime_dynamic.py \
    {RTMPOSE_PROJECT}/rtmdet/person/rtmdet_nano_320-8xb32_coco-person.py \
    ../rtmdet_nano/rtmdet_nano.pth \
    demo/resources/human-pose.jpg \
    --work-dir mmdeploy_models/mmdet/sdk \
    --device cpu \
    --show \
    --dump-info  # dump sdk info

# RTMPose
python tools/deploy.py \
    configs/mmpose/pose-detection_simcc_onnxruntime_dynamic.py \
    {RTMPOSE_PROJECT}/rtmpose/body_2d_keypoint/rtmpose-m_8xb256-420e_coco-256x192.py \
    ../rtmpose_m/rtmpose_m.pth \
    demo/resources/human-pose.jpg \
    --work-dir mmdeploy_models/mmpose/sdk \
    --device cpu \
    --show \
    --dump-info  # dump sdk info

**Comment by sidh1603** [comment]
is it going to give 90 fps on cpu??

**Comment by Tau-J** [comment]
Yes

**Comment by sidh1603** [comment]
Thank you so much tau , i will try to run in the same way 

do i run the command python pose_tracker.py cpu mmdeploy_models/mmpose/rtmdet-sdk/ mmdeploy_models/mmpose/rtmpose-sdk/ 0    in mmdeploy/build/bin  ??

but mmdeply repository dont have build directory

**Comment by sidh1603** [comment]
my parent directory look live this  mmdeploy , mmpose , rtmdet_nano , rtmpose_nano 

i have run this command 

**python tools/deploy.py configs/mmdet/detection/detection_onnxruntime_static.py /home/dell-cv1/Documents/open_lab/mmpose/projects/rtmpose/rtmdet/person/rtmdet_nano_320-8xb32_coco-person.py ../rtmdet_nano/rtmdet_nano.pth demo/resources/human-pose.jpg --work-dir mmdeploy_models/mmdet/ort --device cpu --show**

**error**
tools/deploy.py – create_process -82 – visualize onnxruntime model failed

**Comment by sidh1603** [comment]
my parent directory look live this mmdeploy , mmpose , rtmdet_nano , rtmpose_nano

i have run this command

python tools/deploy.py configs/mmdet/detection/detection_onnxruntime_static.py /home/dell-cv1/Documents/open_lab/mmpose/projects/rtmpose/rtmdet/person/rtmdet_nano_320-8xb32_coco-person.py ../rtmdet_nano/rtmdet_nano.pth demo/resources/human-pose.jpg --work-dir mmdeploy_models/mmdet/ort --device cpu --show

error
tools/deploy.py – create_process -82 – visualize onnxruntime model failed

**Comment by sidh1603** [comment]
my parent directory look live this mmdeploy , mmpose , rtmdet_nano ,
rtmpose_nano

i have run this command

python tools/deploy.py
configs/mmdet/detection/detection_onnxruntime_static.py
/home/dell-cv1/Documents/open_lab/mmpose/projects/rtmpose/rtmdet/person/rtmdet_nano_320-8xb32_coco-person.py
../rtmdet_nano/rtmdet_nano.pth demo/resources/human-pose.jpg --work-dir
mmdeploy_models/mmdet/ort --device cpu --show

error
tools/deploy.py – create_process -82 – visualize onnxruntime model failed
