### ISSUE TITLE
Error - tools/deploy.py – create_process -82 – visualize onnxruntime model failed

### ISSUE THREAD

**Issue by sidh1603** [open-mmlab/mmpose#2259]
my parent directory look live this mmdeploy , mmpose , rtmdet_nano , rtmpose_nano

i have run this command

python tools/deploy.py configs/mmdet/detection/detection_onnxruntime_static.py /home/dell-cv1/Documents/open_lab/mmpose/projects/rtmpose/rtmdet/person/rtmdet_nano_320-8xb32_coco-person.py ../rtmdet_nano/rtmdet_nano.pth demo/resources/human-pose.jpg --work-dir mmdeploy_models/mmdet/ort --device cpu --show

error
tools/deploy.py – create_process -82 – visualize onnxruntime model failed

**Comment by Tau-J** [comment]
I would like close this issue, because you have already created a same one in https://github.com/open-mmlab/mmpose/issues/2261

**Comment by sidh1603** [comment]
Hi Tau-j only you are reply me dont close this issue

**Comment by Tau-J** [comment]
We can talk in https://github.com/open-mmlab/mmpose/issues/2261
