### ISSUE TITLE
Inference with SDK

### ISSUE THREAD

**Issue by sidh1603** [open-mmlab/mmpose#2260]
# RTMDet
python tools/deploy.py \
    configs/mmdet/detection/detection_onnxruntime_dynamic.py \
    {RTMPOSE_PROJECT}/rtmdet/person/rtmdet_nano_320-8xb32_coco-person.py \
    ../rtmdet_nano/rtmdet_nano.pth \
    demo/resources/human-pose.jpg \
    --work-dir mmdeploy_models/mmdet/sdk \
    --device cpu \
    --show \
    --dump-info  # dump sdk info

# RTMPose
python tools/deploy.py \
    configs/mmpose/pose-detection_simcc_onnxruntime_dynamic.py \
    {RTMPOSE_PROJECT}/rtmpose/body_2d_keypoint/rtmpose-m_8xb256-420e_coco-256x192.py \
    ../rtmpose_m/rtmpose_m.pth \
    demo/resources/human-pose.jpg \
    --work-dir mmdeploy_models/mmpose/sdk \
    --device cpu \
    --show \
    --dump-info  # dump sdk info

The above mentioned step for rtmdet and rtm pose need to be run in mmdeploy-1.0.0rc3-linux-x86_64 or mmdeploy??

if its need to be run in mmdeploy then mmdeploy github repository dont have any directory sdk.
so where should i run the above command??

**Comment by Tau-J** [comment]
You need to run the command under root dir of mmdeploy. For exacmple:

```shell
git clone https://github.com/open-mmlab/mmdeploy.git

cd mmdeploy

# install it follow installation guides

# then
python tools/deploy.py .......
```

**Comment by sidh1603** [comment]
i have done the same as you have mentioned.

**Comment by sidh1603** [comment]
i have done the same as you have mentioned. but i got this error 

munmap_chunk(): invalid pointer
04/19 17:57:14 - mmengine - ERROR - tools/deploy.py - create_process - 82 - visualize onnxruntime model failed.

**Comment by Tau-J** [comment]
I would like to close this issue to avoid repeating. We can communicate in https://github.com/open-mmlab/mmpose/issues/2261.

**Comment by sidh1603** [comment]
![Screenshot (32)](https://user-images.githubusercontent.com/51013394/233267246-874e00c5-fde0-4815-9c90-f983749bf67a.png)
i have followed this steps
