### ISSUE TITLE
RuntimeError: unable to mmap 136 bytes from file <filename not specified>: Cannot allocate memory (12)

### ISSUE THREAD

**Issue by darcula1993** [open-mmlab/mmpose#2264]
I am trying to reproduce rtmpose result using lmdb backend but got error like:
RuntimeError: unable to mmap 136 bytes from file <filename not specified>: Cannot allocate memory (12)

the config file is here:
[test_rtm.zip](https://github.com/open-mmlab/mmpose/files/11283789/test_rtm.zip)

Any idea why this happen? Looks like it related to multi-processing.

**Comment by LareinaM** [comment]
@Tau-J Could you help on this issue relating to RTMPose?

**Comment by Tau-J** [comment]
`file_client_args` has been deprecated, could you pull the newest code and try again?

**Comment by darcula1993** [comment]
```
backend_args = dict(backend = 'lmdb',
                         db_path = "/lixinwei/mmpose/data/lmdb_pose/",
                         )
```
define this line like new config file,but got same error. Is there any tutorial or sample code show how to use lmdb in mmpose?

**Comment by Tau-J** [comment]
Sorry, we just directly integrate this api from mmengine.
