### ISSUE TITLE
https://github.com/open-mmlab/mmpose/tree/dev-1.x/projects/rtmpose

### ISSUE THREAD

**Issue by sidh1603** [open-mmlab/mmpose#2268]
HI,

I have followed this url steps to use rtmpose on cpu

after installing everything , i am getting this error :
![Screenshot from 2023-04-20 11-01-21](https://user-images.githubusercontent.com/51013394/233427550-354da0f7-08a0-4d25-a36a-7b103d38be05.png)
![Screenshot from 2023-04-20 11-00-00](https://user-images.githubusercontent.com/51013394/233427552-e41ea9c0-8b6b-4e7b-8a8b-d73e45b8865f.png)

**Comment by LareinaM** [comment]
Closed due to duplication, please discuss in [#2267](https://github.com/open-mmlab/mmpose/issues/2267).
