### ISSUE TITLE
Halpe26 official model support

### ISSUE THREAD

**Issue by lucasjinreal** [open-mmlab/mmpose#2271]
Hi, will consider support halpe26 kpts on rtmpose model? rtmpose is a great model, but currently only coco17 and wholebody support on official demo. It would be great if a more useful halpe26 kpts model support.

**Comment by Ben-Louis** [comment]
Thanks for using MMPose. Halpe26 dataset has been supported in MMPose 1.0. We warmly welcome and appreciate contributions from the community.

**Comment by lucasjinreal** [comment]
Would like to, but lacking of GPU resources.
