### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by sidh1603** [open-mmlab/mmpose#2276]
HI , 

I have clone mmpose using branch dev-1.x and after that i have followed all the steps which are mentioned on rtmpose documentation page ,
but when i am running command 
![Screenshot from 2023-04-20 11-58-49](https://user-images.githubusercontent.com/51013394/233679933-080d6b6a-d253-433b-b315-994bca83f70d.png)
![Screenshot from 2023-04-20 11-01-21](https://user-images.githubusercontent.com/51013394/233679935-9aca33ef-b897-4054-8c97-3484dfde0fb2.png)
![Screenshot from 2023-04-20 11-00-00](https://user-images.githubusercontent.com/51013394/233679937-e96125ef-074b-4cf9-852c-964a8c30d9a7.png)
![Screenshot from 2023-04-20 10-34-28](https://user-images.githubusercontent.com/51013394/233679939-16020d16-c85c-487e-8980-29e43e308cc1.png)

python tools/deploy.py \
    configs/mmdet/detection/detection_onnxruntime_dynamic.py \
    ../mmpose/projects/rtmpose/rtmdet/person/rtmdet_nano_320-8xb32_coco-person.py \
    https://download.openmmlab.com/mmpose/v1/projects/rtmpose/rtmdet_nano_8xb32-100e_coco-obj365-person-05d8511e.pth \
    demo/resources/human-pose.jpg \
    --work-dir rtmpose-ort/rtmdet-nano \
    --device cpu \
    --show \
    --dump-info  # dump sdk info

**Comment by Tau-J** [comment]
Sorry, we cannot reproduce your error.
