### ISSUE TITLE
/opt/rh/devtoolset-9/root/usr/include/c++/9/bits/stl_vector.h:1042: std::vector

### ISSUE THREAD

**Issue by sidh1603** [open-mmlab/mmpose#2277]
HI, 
**Note : i have clone dev-1.x version**

**i have also attached the scrrenshot my parent directory**
when i am trying to run python pose_tracker.py cpu rtmpose-ort/rtmdet-nano/ rtmpose-ort/rtmpose-m/ 0 inside **mmdeploy/example/python directory**

i am getting error  /opt/rh/devtoolset-9/root/usr/include/c++/9/bits/stl_vector.h:1042: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = int; _Alloc = std::allocator<int>; std::vector<_Tp, _Alloc>::reference = int&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
Aborted (core dumped)

![Screenshot from 2023-04-21 11-19-23](https://user-images.githubusercontent.com/51013394/233686161-209bf0b0-771d-4a62-bc5c-4e6f8c43e671.png)
![image1](https://user-images.githubusercontent.com/51013394/233686163-21d4a8bb-9819-427d-b66f-9d08a6881951.png)
![Screenshot from 2023-04-21 11-19-23](https://user-images.githubusercontent.com/51013394/233686209-81316eea-e9ab-4470-977b-e744b1c7d9b9.png)
![image1](https://user-images.githubusercontent.com/51013394/233686212-a242404e-0244-4352-a233-e74af4ae17ff.png)
for the same i have attached screenshsot

**Comment by Tau-J** [comment]
Answered in https://github.com/open-mmlab/mmpose/issues/2278.
