### ISSUE TITLE
./bin/det_pose rtmpose-ort/rtmdet-nano/ rtmpose-ort/rtmpose-m/ your_img.jpg --device cpu

### ISSUE THREAD

**Issue by sidh1603** [open-mmlab/mmpose#2278]
HI,

Running this command ./bin/det_pose rtmpose-ort/rtmdet-nano/ rtmpose-ort/rtmpose-m/ your_img.jpg --device cpu

![image_2](https://user-images.githubusercontent.com/51013394/233694760-58aa0ff5-f777-4116-8458-d5651e56b4a9.png)

**Comment by Tau-J** [comment]
Hi, I suggest raising an issue to [mmdeploy](https://github.com/open-mmlab/mmdeploy), we cannot reproduce this error on our device.

**Comment by liuzong616** [comment]
我也遇到了这个问题，请问您解决了吗
