### ISSUE TITLE
UDP for mmpose

### ISSUE THREAD

**Issue by HuangJunJie2017** [open-mmlab/mmpose#228]
I am the author of UDP, and i am planing a new pull-request about UDP for mmpose
the main problem is that, to acquire the precision improvement, all the trained models in mmpose need to be retrained~ 
Some results list in our project for both bottom-up and top-down paradigm:  https://github.com/HuangJunJie2017/UDP-Pose

**Comment by innerlee** [comment]
Thanks! Looks fantastic! I have a few questions

> ...all the trained models in mmpose need to be retrained

Will hand/mesh tasks benefit from this? What is needed for the retrain, do we need to change config files, and any docs for instructions? The retrain happens after the pull request, and carried out by us, am I understanding correct?

**Comment by jin-s13** [comment]
Excited to hear that! PR is welcome. 
I have read about UDP-Pose and I really like this work :+1: It is general and can boost the performance of both top-down and bottom-up methods.
Once the code is ready, we can help with training these models : )

**Comment by HuangJunJie2017** [comment]
-Will hand/mesh tasks benefit from this?  
UDP modifies the data processing pipeline which is used for all tasks. Theoretically speaking, hand/mesh tasks will benefit from this.  
-What is needed for the retrain, do we need to change config files, and any docs for instructions? 
For training, we just need to replace some code in 'mmpose/datasets/pipelines/bottom_up_transform.py' and 'mmpose/datasets/pipelines/top_down_transform.py' for bottom-up and top-down paradigm respectively.  
For testing, we need to change some extra code about the post processing. Some configs may need to be modified, for example PROJECT2IMAG is no longer need for bottom-up paradigm as it is consumptive and doesn't provide any precision improvement.
I have not reviewed all this project and there may be something else need to be changed~
-The retrain happens after the pull request, and carried out by us, am I understanding correct?
Yes, this is consumptive

**Comment by HuangJunJie2017** [comment]
@jin-s13 ok, i still need some time to review, prepare and test the code,  i will pr in next week if it is ready
