### ISSUE TITLE
An error occurred when I verified if the installation of mmpose-1.0.0 was successful

### ISSUE THREAD

**Issue by Ezreal0211** [open-mmlab/mmpose#2282]
![image](https://user-images.githubusercontent.com/125781444/233770511-cd222321-374c-4d93-9f37-72a8ecb59193.png)

I downloaded the required. py and. pth files according to the verification command provided on the official website, and then reported the following error.
![image](https://user-images.githubusercontent.com/125781444/233770529-df2c5f2e-06b8-4c47-b655-14fa80b51e40.png)
![image](https://user-images.githubusercontent.com/125781444/233770543-a0adf33e-a3bc-4191-8785-7461ef803872.png)
Thanks for  everyone's help！！！

**Comment by Ben-Louis** [comment]
Thanks for using MMPose. Could you kindly specify the location within the documentation where you found the command? AE algorithm has not yet been fully integrated into MMPose version 1.0.0.

**Comment by Ezreal0211** [comment]
![image](https://user-images.githubusercontent.com/125781444/233773681-5ab470ee-2fc6-47c4-9b46-8eaa3eb7e5ca.png)
Thanks!

**Comment by Ezreal0211** [comment]
Sorry, there was a problem with the screenshot of my first chapter. I made an error in the first step of verifying the command. Below is the correct screenshot of the command.
![image](https://user-images.githubusercontent.com/125781444/233773745-76280faf-4893-4078-9d03-07281c3a7bfe.png)

**Comment by Ben-Louis** [comment]
It seems you're using MMPose 1.0.0 while referencing the documentation for MMPose 0.29, which are incompatible. We recommend referring to the documentation specific to MMPose 1.0.0 instead: https://mmpose.readthedocs.io/en/latest/installation.html

**Comment by Ezreal0211** [comment]
Sorry，but my installation steps are completely based on 0.29.0, I don't know which part is incompatible.

**Comment by Ben-Louis** [comment]
Sorry, the document for 0.29 has not been updated. You may need to switch to branch '0.x' before installing mmpose:
```shell
git clone https://github.com/open-mmlab/mmpose.git
cd mmpose

# switch to branch 0.x
git fetch origin
git checkout -b 0.x origin/0.x

pip install -r requirements.txt
pip install -v -e .
# "-v" means verbose, or more output
# "-e" means installing a project in editable mode,
# thus any local modifications made to the code will take effect without reinstallation.
```

**Comment by Ezreal0211** [comment]
I don't know if there is a problem with my operation, but when I enter the installation page from the installation tutorial on the official website, I will jump to v0.29.
![image](https://user-images.githubusercontent.com/125781444/233776723-c4837ec2-4a34-4624-ad82-0631c0e9b26a.png)

**Comment by Ben-Louis** [comment]
Hi @Ezreal0211, it appears you've navigated to the readme page for [MMPose 0.x](https://github.com/open-mmlab/mmpose/tree/0.x). The installation guide link on this page directs you to the installation tutorial for MMPose 0.29. Instead, you may want to visit https://github.com/open-mmlab/mmpose, which is the homepage for the most recent version, MMPose 1.0.0.

**Comment by Ezreal0211** [comment]
I know what you mean, but some algorithms in the new version of MMPOSE have not been fully updated, so I specifically installed the old version of MMPOSE.
