### ISSUE TITLE
error on ubuntu 20.04

### ISSUE THREAD

**Issue by sidh1603** [open-mmlab/mmpose#2296]
### What's wrong?

Hi, after installing rtmpose , i run it on windows by using command 

python pose_tracker.py cpu rtmpose-ort/rtmdet-nano/ rtmpose-ort/rtmpose-m/ 0 

it work well and the speed is also good on cpu .

but when i run the same command on ubuntu20.04 , i got the error 

![9c88ffbe507edebeb539f0b0dca3fa0b20093194b640d0ba66cebc6f9948879a](https://user-images.githubusercontent.com/51013394/233869021-a01e08f5-c093-4800-a49e-13d176d3ff1a.png)

**Comment by Tau-J** [comment]
Sorry, we cannot reproduce this error. BTW, please follow the bug report template to provide necessary information to help us reproduce.

**Comment by sidh1603** [comment]
Hi,any idea why this error occured so that i fan work on it.Sent from my iPhoneOn Apr 23, 2023, at 10:56 PM, Tau ***@***.***> wrote:﻿
Sorry, we cannot reproduce this error. BTW, please follow the bug report template to provide necessary information to help us reproduce.

**Comment by Tau-J** [comment]
I have no idea about that. The script works fine on my Linux device.

**Comment by sidh1603** [comment]
for me its worked well on windows , but when i tried to run it on ubuntu 20.04 its give me that error.Sent from my iPhoneOn Apr 23, 2023, at 11:24 PM, Tau ***@***.***> wrote:﻿
I have no idea about that. The script works fine on my Linux device.

**Comment by sidh1603** [comment]
We are using the RTM Pose on windows. We would like to extract the key
points (coordinates of hands and head ). Please let me know how to find and
extract the same.
