### ISSUE TITLE
[Docs] How to train on Halpe-26 model?

### ISSUE THREAD

**Issue by luohao123** [open-mmlab/mmpose#2305]
### 📚 The doc issue

Like alpha-pose, how to train only on halpe-26 model which consist of 26 body keypoints model only? (less then whole body but more than ococ 17??)

**Comment by Tau-J** [comment]
I suggest using `KeypointConverter` to select 26 kpts from ther original 136-kpt annotations. Details can be found in [our docs](https://mmpose.readthedocs.io/en/dev-1.x/user_guides/mixed_datasets.html)

**Comment by luohao123** [comment]
@Tau-J thank u!  BTW, I didn't see any existed configs to train halpe all body, does there any config files I can reference and selecet kpts I need? thank u very much!
