### ISSUE TITLE
3D body demo not found in the main branch

### ISSUE THREAD

**Issue by CourbotA** [open-mmlab/mmpose#2317]
### 📚 The doc issue

I am following the documentation from your website : https://mmpose.readthedocs.io/en/v0.29.0/demo.html#id10 
I want to do the inference using : demo/body3d_two_stage_video_demo.py  as described in the documentation. 
However this file is not present on the repository , i have been able to find it on https://github.com/ritaank/pose-estimation-ui/blob/main/demo/body3d_two_stage_video_demo.py , when i try to do the inference i have the following error : 
![image](https://user-images.githubusercontent.com/72599332/234895000-a99d4ce7-e3ae-4d9d-b658-de0522a63118.png)
I have the latest versions of mmpose and mmdet ( i ran pip install mmpose -U and pip install mmdet -U ) 
Can you help me doing two stage video 2d to 3D uplifting ?

**Comment by Ben-Louis** [comment]
Hi @CourbotA, sorry for the confusion. The original 'master' branch, containing the lifting algorithms, has been renamed to the '0.x' branch. To proceed, please switch to the '0.x' branch and install mmpose by running `pip install -e .` within the mmpose directory. Once completed, you should be able to run `demo/body3d_two_stage_video_demo.py`.
