### ISSUE TITLE
keypoints and bbox value are pixel values or something else??

### ISSUE THREAD

**Issue by sidh1603** [open-mmlab/mmpose#2319]
### 📚 The doc issue

bboxes [[177.51779 175.4541  727.9131  960.0001 ]]
Keypoints [[[670 316]
  [665 306]
  [674 291]
  [590 257]
  [640 266]
  [448 313]
  [678 343]
  [232 365]
  [667 533]
  [383 476]
  [558 528]
  [433 647]
  [590 666]
  [393 901]
  [551 902]
  [382 937]
  [600 927]]]
bboxes [[177.3735  175.89624 733.39417 960.00037]]

i got these keypoint and boundarybox values. Are these pixel values or something else? 
Please let me know.

**Comment by Ben-Louis** [comment]
Yes, they are pixel values

**Comment by colt18** [comment]
@Ben-Louis I'm getting keypoint pixel values outside of webcam resolutions for wholebody. Is this normal? Lets say webcam is 640x480, I'm getting [61,709] and [676,476]. There are no visible legs in these images. Does it guesses the coordinations of unseen body parts?

**Comment by Ben-Louis** [comment]
Hi @colt18, sorry for the late reply. If you’re using regression models such as Deeppose or DEKR, it’s normal for the model to predict keypoint coordinates outside the image. These models do have the ability to estimate the location of unseen keypoints.

**Comment by Lehieubkhn** [comment]
> Yes, they are pixel values

Hi Ben,
I want to ask you a question. How can I extract hand keypoint from the output of "Topdown Heatmap + Hrnet on Coco-Wholebody" which are shape of (133, 3). I can't find anything that points out the mapping of them
