### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Yesinaly** [open-mmlab/mmpose#2325]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

run python -c "from mmpose.utils import collect_env; print(collect_env())"
report:
 warnings.warn(
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/wuyueru/mmpose_tu/mmpose/mmpose/__init__.py", line 16, in <module>
    assert (mmcv_version >= digit_version(mmcv_minimum_version)
AssertionError: MMCV==1.7.1 is used but incompatible. Please install mmcv>=2.0.0rc4, <=2.1.0.

run pip list | grep mm
report:
command-not-found            0.3
mmcls                        0.25.0
mmcv-full                    1.7.1
mmdet                        2.28.2
mmengine                     0.7.3
mmpose                       1.0.0                 .../mmpose
mmtrack                      0.14.0               .../mmtracking
ubuntu-drivers-common        0.0.0

### Reproduces the problem - code sample

AssertionError: MMCV==2.0.0rc4 is used but incompatible. Please install mmcv>=1.3.17, <=1.8.0.
AssertionError: MMCV==1.7.1 is used but incompatible. Please install mmcv>=2.0.0rc4, <=2.1.0.

### Reproduces the problem - command or script

AssertionError: MMCV==2.0.0rc4 is used but incompatible. Please install mmcv>=1.3.17, <=1.8.0.
AssertionError: MMCV==1.7.1 is used but incompatible. Please install mmcv>=2.0.0rc4, <=2.1.0.

### Reproduces the problem - error message

I run code to Verify the mmpose installation
> python3 demo/image_demo.py \
>         demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py \
>     https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \
>         configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w48_coco_256x192.py \
>         https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_coco_256x192-b9e0b3ab_20200708.pth \
>         --img data/Dancer.png \
>         --out-img-root outputs/A
it reports:
**AssertionError: MMCV==2.0.0rc4 is used but incompatible. Please install mmcv>=1.3.17, <=1.8.0.**

**so I uninstall MMCV2.0.0rc4 , and install mmcv1.7.1**
and run the code again:
it reports
**AssertionError: MMCV==1.7.1 is used but incompatible. Please install mmcv>=2.0.0rc4, <=2.1.0.**

How to solve this problem?Thank you very much!

**Comment by Ben-Louis** [comment]
Hi @Yesinaly, it appears that you are encountering issues related to version incompatibility. To resolve this, please refer to the [installation FAQ](https://mmpose.readthedocs.io/en/latest/faq.html#installation) for information on the compatible versions of mmpose and mmcv.
