### ISSUE TITLE
modify a backbone of mmpose and use pretrained model

### ISSUE THREAD

**Issue by alaa-shubbak** [open-mmlab/mmpose#2337]
### What is the feature?

I would like to ask about the possibility to change the initialization of a backbone in mmpose model. 
for example in model based on HRNet as bellow : 
![HRNet for mmpose](https://user-images.githubusercontent.com/10245810/236466318-f8258798-b727-4c89-8ef3-402e62c76cb0.jpg)

can i modify the backbone and load a pretrain model of .pth from another training stage ? 
is there certain points shall i take care of ? 

can i do the same in the model based on ResNet-50 backbone ,like this one : 
![resnet_50 for mmpose](https://user-images.githubusercontent.com/10245810/236466621-6d7e95f2-fd35-4715-b694-42080b71a49b.jpg)

### Any other context?

i need to try to train the backbone first on huge amount of dataset ,without any annotation or with just basic annotation. then do the pose estimation part on less amount of data. 

so i was thinking to modify the backbone initialization by the results of .pth of well trained model. 

looking forward to hear from your side. 

thanks

**Comment by Ben-Louis** [comment]
Certainly, you can change the value of `checkpoint` to reference any other checkpoint file you'd like.

**Comment by alaa-shubbak** [comment]
Thanks for your reply. 

I try it, but unfortunately  i got this error :

`TypeError: TopDown: ResNet: __init__() got an unexpected keyword argument 'init_cfg'`

here is my update in the  [Resnet_50_animalpose](https://github.com/open-mmlab/mmpose/blob/main/configs/animal_2d_keypoint/topdown_heatmap/animalpose/td-hm_res50_8xb64-210e_animalpose-256x256.py) config:

<img width="551" alt="image" src="https://user-images.githubusercontent.com/10245810/236621021-4e1931b9-0a1a-4236-9b76-85ad67662ce3.png">

please note that i used the old version of mmpose. as it worked before with me in my application.

**Comment by Ben-Louis** [comment]
Hi @alaa-shubbak, the old version (v0.x) of mmpose is not compatible with the current config you are using. You could use the configs from the old version and modify the `pretrained` value in config, such as https://github.com/open-mmlab/mmpose/blob/3b8173463c4ecdcd3d82d566254bb2ae2eb0cc07/configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/ap10k/hrnet_w48_ap10k_256x256.py#L40-L41.

**Comment by alaa-shubbak** [comment]
Thank you very much. the training is running now.
