### ISSUE TITLE
[Bug] try to get_flops and --show-arch-info of litehrnet

### ISSUE THREAD

**Issue by amazing-cc** [open-mmlab/mmpose#2338]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

OrderedDict([('sys.platform', 'win32'), ('Python', '3.8.16 (default, Mar  2 2023, 03:18:16) [MSC v.1916 64 bit (AMD64)]'), ('CUDA available', True), ('numpy_random_seed', 2147483648), ('GPU 0', 'NVIDIA GeForce RTX 3060'), ('CUDA_HOME', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.3'), ('NVCC', 'C
uda compilation tools, release 11.3, V11.3.109'), ('MSVC', '用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.29.30148 版'), ('GCC', 'n/a'), ('PyTorch', '1.10.1'), ('PyTorch compiling details', 'PyTorch built with:\n  - C++ Version: 199711\n  - MSVC 192829337\n  - Intel(R) Math Kernel Library Version 2020.0.2 Produ
ct Build 20200624 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)\n  - OpenMP 2019\n  - LAPACK is enabled (usually provided by MKL)\n  - CPU capability usage: AVX2\n  - CUDA Runtime 11.3\n  - NVCC architecture flags: -gencode;arch=comput
e_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37\n  
- CuDNN 8.2\n  - Magma 2.5.4\n  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/cb/pytorch_100000000000
0/work/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_
GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, \n'), ('TorchVision', '0.11.2'), ('OpenCV', '4.7.0'), ('MMEngine', '0.7.2'), ('MMPose', '1.0.0+212c4ea')])

### Reproduces the problem - code sample

On the dev1.x branch, using the get_flops.py script, the detailed structure of litehrnet is not available.

### Reproduces the problem - command or script

configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_litehrnet-18_8xb64-210e_coco-256x192.py --show-arch-info

### Reproduces the problem - error message

`Traceback (most recent call last):
  File "C:/Users/cc/PycharmProjects/2dpose_3/mmpose/tools/analysis_tools/get_flops.py", line 149, in <module>
    main()
  File "C:/Users/cc/PycharmProjects/2dpose_3/mmpose/tools/analysis_tools/get_flops.py", line 130, in main
    outputs = inference(args, input_shape, logger)
  File "C:/Users/cc/PycharmProjects/2dpose_3/mmpose/tools/analysis_tools/get_flops.py", line 103, in inference
    outputs = get_model_complexity_info(
  File "C:\Users\cc\anaconda3\envs\mmpose1x\lib\site-packages\mmengine\analysis\print_helper.py", line 724, in get_model_complexity_info
    complexity_arch = complexity_stats_str(
  File "C:\Users\cc\anaconda3\envs\mmpose1x\lib\site-packages\mmengine\analysis\print_helper.py", line 546, in complexity_stats_str
    model_string += _model_stats_str(model, stats)  # type: ignore
  File "C:\Users\cc\anaconda3\envs\mmpose1x\lib\site-packages\mmengine\analysis\print_helper.py", line 279, in _model_stats_str
    return repr_with_statistics(model, '')
  File "C:\Users\cc\anaconda3\envs\mmpose1x\lib\site-packages\mmengine\analysis\print_helper.py", line 263, in repr_with_statistics
    submod_str = repr_with_statistics(submod, submod_name)
  File "C:\Users\cc\anaconda3\envs\mmpose1x\lib\site-packages\mmengine\analysis\print_helper.py", line 263, in repr_with_statistics
    submod_str = repr_with_statistics(submod, submod_name)
  File "C:\Users\cc\anaconda3\envs\mmpose1x\lib\site-packages\mmengine\analysis\print_helper.py", line 263, in repr_with_statistics
    submod_str = repr_with_statistics(submod, submod_name)
  [Previous line repeated 3 more times]
  File "C:\Users\cc\anaconda3\envs\mmpose1x\lib\site-packages\mmengine\analysis\print_helper.py", line 251, in repr_with_statistics
    extra_repr = module.extra_repr()
AttributeError: 'NoneType' object has no attribute 'extra_repr'

进程已结束,退出代码1
`

### Additional information

I tried the network with resnet as backbone and this script works fine.

**Comment by Ben-Louis** [comment]
Hi, there is a bug in the `get_model_complexity_info` function in mmengine. We suggest raising an issue with mmengine to address this problem.
