### ISSUE TITLE
Output  Keypoints and 2D Bounding Box

### ISSUE THREAD

**Issue by Yaozh66** [open-mmlab/mmpose#2341]
### What is the feature?

Hello, thanks for this great project! I want to ask is there any model that can simultaneously output keypoints and 2D bounding box of an object which is not only a person and may be some classes that I define?

**Comment by Tau-J** [comment]
Hi @Yaozh66 , if all classes of objects have the same number of keypoints, it is possible to train a single model to predict. Otherwise it's better to use a group of separate models
