### ISSUE TITLE
Previous version

### ISSUE THREAD

**Issue by eelsjpl** [open-mmlab/mmpose#2348]
### What is the feature?

The previous version of the code was very user friendly and could be modified according to personal needs of the projects very easily. The concept of plug and play was so much better in the previous versions. This new version is difficult to manage and is not friendly for customized implementations. The way the code is written in the latest version is also not pleasing. This new version lacks the ease of finding the useful modules. A person who would use this regularly would always expect the repo to improve over time. The new version is disappointment. Please maintain the most important part of customized plug and play as available in the previous versions.

**Comment by Tau-J** [comment]
Thanks for your feedback.
