### ISSUE TITLE
[Docs] Fastest keypoint detection and object detection Model in MMPose

### ISSUE THREAD

**Issue by Yaozh66** [open-mmlab/mmpose#2371]
### 📚 The doc issue

Hello! Thanks for opensourcing this great project. I want to ask which model that can play multi-task keypoint detection and object detection  is fastest or lightest in MMpose. I want to deploy it on Jetson Nano which is resource-restricted. Or do you have any suggestions? Thanks very much.

**Comment by Tau-J** [comment]
If your application scenario is fewer than 6 people, you can refer to [RTMPose](https://github.com/open-mmlab/mmpose/tree/main/projects/rtmpose), if more than 6, I suggest [YOLOX-Pose](https://github.com/open-mmlab/mmpose/tree/main/projects/yolox-pose)

**Comment by Yaozh66** [comment]
How do you think about yolov8-pose which is provided by [ultralytics](https://github.com/ultralytics/ultralytics) compared to yolox-pose?

**Comment by Tau-J** [comment]
You can compare the reported performance
