### ISSUE TITLE
[Bug] inferencer_demo.py using webcam

### ISSUE THREAD

**Issue by tet28** [open-mmlab/mmpose#2376]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

OrderedDict([('sys.platform', 'linux'), ('Python', '3.8.10 (default, Mar 13 2023, 10:26:41) [GCC 9.4.0]'), ('CUDA available', True), ('numpy_random_seed', 2147483648), ('GPU 0', 'Orin'), ('CUDA_HOME', '/usr/local/cuda-11.4'), ('NVCC', 'Cuda compilation tools, release 11.4, V11.4.315'), ('GCC', 'aarch64-linux-gnu-gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0'), ('PyTorch', '1.11.0'), ('PyTorch compiling details', 'PyTorch built with:\n  - GCC 9.4\n  - C++ Version: 201402\n  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n  - LAPACK is enabled (usually provided by MKL)\n  - NNPACK is enabled\n  - CPU capability usage: NO AVX\n  - CUDA Runtime 11.4\n  - NVCC architecture flags: -gencode;arch=compute_72,code=sm_72;-gencode;arch=compute_87,code=sm_87\n  - CuDNN 8.6\n    - Built with CuDNN 8.3.2\n  - Build settings: BLAS_INFO=open, BUILD_TYPE=Release, CUDA_VERSION=11.4, CUDNN_VERSION=8.3.2, CXX_COMPILER=/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, FORCE_FALLBACK_CUDA_MPI=1, LAPACK_INFO=open, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EIGEN_FOR_BLAS=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=OFF, USE_MKLDNN=OFF, USE_MPI=ON, USE_NCCL=0, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, \n'), ('TorchVision', '0.12.0a0+53ba0a4'), ('OpenCV', '4.7.0'), ('MMEngine', '0.7.3'), ('MMPose', '1.0.0+53ba0a4')])

mmcv                    2.0.0                /home/user/work/test/testdetection/mmcv
mmcv-lite               2.0.0
mmdet                   3.0.0
mmengine                0.7.3
mmpose                  1.0.0
mmyolo                  0.5.0

### Reproduces the problem - code sample

inferencer_demo.py

# Copyright (c) OpenMMLab. All rights reserved.
from argparse import ArgumentParser
from typing import Dict

from mmpose.apis.inferencers import MMPoseInferencer, get_model_aliases

def parse_args():
    parser = ArgumentParser()
    parser.add_argument(
        'inputs',
        type=str,
        nargs='?',
        help='Input image/video path or folder path.')
    parser.add_argument(
        '--pose2d',
        type=str,
        default=None,
        help='Pretrained 2D pose estimation algorithm. It\'s the path to the '
        'config file or the model name defined in metafile.')
    parser.add_argument(
        '--pose2d-weights',
        type=str,
        default=None,
        help='Path to the custom checkpoint file of the selected pose model. '
        'If it is not specified and "pose2d" is a model name of metafile, '
        'the weights will be loaded from metafile.')
    parser.add_argument(
        '--det-model',
        type=str,
        default=None,
        help='Config path or alias of detection model.')
    parser.add_argument(
        '--det-weights',
        type=str,
        default=None,
        help='Path to the checkpoints of detection model.')
    parser.add_argument(
        '--det-cat-ids',
        type=int,
        nargs='+',
        default=0,
        help='Category id for detection model.')
    parser.add_argument(
        '--scope',
        type=str,
        default='mmpose',
        help='Scope where modules are defined.')
    parser.add_argument(
        '--device',
        type=str,
        default=None,
        help='Device used for inference. '
        'If not specified, the available device will be automatically used.')
    parser.add_argument(
        '--show',
        action='store_true',
        help='Display the image/video in a popup window.')
    parser.add_argument(
        '--draw-bbox',
        action='store_true',
        help='Whether to draw the bounding boxes.')
    parser.add_argument(
        '--bbox-thr',
        type=float,
        default=0.3,
        help='Bounding box score threshold')
    parser.add_argument(
        '--nms-thr',
        type=float,
        default=0.3,
        help='IoU threshold for bounding box NMS')
    parser.add_argument(
        '--kpt-thr', type=float, default=0.3, help='Keypoint score threshold')
    parser.add_argument(
        '--radius',
        type=int,
        default=3,
        help='Keypoint radius for visualization.')
    parser.add_argument(
        '--thickness',
        type=int,
        default=1,
        help='Link thickness for visualization.')
    parser.add_argument(
        '--vis-out-dir',
        type=str,
        default='',
        help='Directory for saving visualized results.')
    parser.add_argument(
        '--pred-out-dir',
        type=str,
        default='',
        help='Directory for saving inference results.')
    parser.add_argument(
        '--show-alias',
        action='store_true',
        help='Display all the available model aliases.')

    call_args = vars(parser.parse_args())

    init_kws = [
        'pose2d', 'pose2d_weights', 'scope', 'device', 'det_model',
        'det_weights', 'det_cat_ids'
    ]
    init_args = {}
    for init_kw in init_kws:
        init_args[init_kw] = call_args.pop(init_kw)

    diaplay_alias = call_args.pop('show_alias')

    return init_args, call_args, diaplay_alias

def display_model_aliases(model_aliases: Dict[str, str]) -> None:
    """Display the available model aliases and their corresponding model
    names."""
    aliases = list(model_aliases.keys())
    max_alias_length = max(map(len, aliases))
    print(f'{"ALIAS".ljust(max_alias_length+2)}MODEL_NAME')
    for alias in sorted(aliases):
        print(f'{alias.ljust(max_alias_length+2)}{model_aliases[alias]}')

def main():
    init_args, call_args, diaplay_alias = parse_args()
    if diaplay_alias:
        model_alises = get_model_aliases(init_args['scope'])
        display_model_aliases(model_alises)
    else:
        inferencer = MMPoseInferencer(**init_args)
        for _ in inferencer(**call_args):
            pass

if __name__ == '__main__':
    main()

### Reproduces the problem - command or script

python3 ./demo/inferencer_demo.py webcam:0 --pose2d ./projects/yolox-pose/configs/yolox-pose_l_4xb64-300e_coco.py --pose2d-weights ./projects/yolox-pose/models/yolox-pose_l_4xb64-300e_coco-122e4cf8_20230321.pth --device cuda:0 --vis-out-dir ./vis_results --scope mmyolo --draw-bbox --bbox-thr 0.3 --kpt-thr 0.3 --pred-out-dir ./pred_results

### Reproduces the problem - error message

Loads checkpoint by local backend from path: ./projects/yolox-pose/models/yolox-pose_l_4xb64-300e_coco-122e4cf8_20230321.pth
05/18 15:31:59 - mmengine - WARNING - Failed to search registry with scope "mmyolo" in the "function" registry tree. As a workaround, the current "function" registry in "mmengine" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmyolo" is a correct scope, or whether the registry is initialized.
05/18 15:31:59 - mmengine - WARNING - `Visualizer` backend is not initialized because save_dir is None.
-----------------------------------webcam:0--------------------------------
True
True
/home/user/work/test/testdetection/mmpose-main/mmpose/apis/inferencers/mmpose_inferencer.py:176: UserWarning: The display mode is closed when using webcam input. It will be turned on automatically.
  warnings.warn('The display mode is closed when using webcam '
<generator object BaseMMPoseInferencer._get_webcam_inputs.<locals>._webcam_reader at 0xfffed2027f90>
Inference ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   05/18 15:32:00 - mmengine - WARNING - "FileClient" will be deprecated in future. Please use io functions in https://mmengine.readthedocs.io/en/latest/api/fileio.html#file-io
05/18 15:32:00 - mmengine - WARNING - "HardDiskBackend" is the alias of "LocalBackend" and the former will be deprecated in future.
Inference ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   
Traceback (most recent call last):
  File "./demo/inferencer_demo.py", line 138, in <module>
    main()
  File "./demo/inferencer_demo.py", line 133, in main
    for _ in inferencer(**call_args):
  File "/home/user/work/test/testdetection/mmpose-main/mmpose/apis/inferencers/mmpose_inferencer.py", line 193, in __call__
    for proc_inputs, ori_inputs in inputs:
  File "/home/user/work/test/testdetection/test-env/lib/python3.8/site-packages/rich/progress.py", line 168, in track
    yield from progress.track(
  File "/home/user/work/test/testdetection/test-env/lib/python3.8/site-packages/rich/progress.py", line 1210, in track
    for value in sequence:
  File "/home/user/work/test/testdetection/mmpose-main/mmpose/apis/inferencers/mmpose_inferencer.py", line 104, in preprocess
    data_infos = self.pose2d_inferencer.preprocess_single(
  File "/home/user/work/test/testdetection/mmpose-main/mmpose/apis/inferencers/pose2d_inferencer.py", line 189, in preprocess_single
    data_infos = [self.pipeline(data_info)]
  File "/home/user/work/test/testdetection/test-env/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 59, in __call__
    data = t(data)
  File "/home/user/work/test/testdetection/mmcv/mmcv/transforms/base.py", line 12, in __call__
    return self.transform(results)
  File "/home/user/work/test/testdetection/mmcv/mmcv/transforms/loading.py", line 107, in transform
    raise e
  File "/home/user/work/test/testdetection/mmcv/mmcv/transforms/loading.py", line 97, in transform
    img_bytes = file_client.get(filename)
  File "/home/user/work/test/testdetection/test-env/lib/python3.8/site-packages/mmengine/fileio/file_client.py", line 301, in get
    return self.client.get(filepath)
  File "/home/user/work/test/testdetection/test-env/lib/python3.8/site-packages/mmengine/fileio/backends/local_backend.py", line 33, in get
    with open(filepath, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '000000.jpg'

### Additional information

expected: run the demo with webcam input
If you have another way to run yolox-pose with webcam input (I think topdown_demo_with_mmdet.py can be used), that will be fine too.

**Comment by Ben-Louis** [comment]
Hi @tet28, thank you very much for your feedback.It appears the issue has originated from an incompatibility between the transform `LoadImageFromFile` and image array input. You can modify the config of YOLOX-Pose as in https://github.com/open-mmlab/mmpose/pull/2378 to resolve this issue
