### ISSUE TITLE
use evaluation indicators (ap, ar) instead of auc, pck

### ISSUE THREAD

**Issue by mywordwin** [open-mmlab/mmpose#2380]
Hello, I have used mmpose1.0 at present, and I have replaced val_evaluator. I want to change the evaluation index auc to ap, etc. The hand has 21 key points, and cocoeval defaults to the body with 17 key points. May I ask? Need to modify the cocoeval.py function to make the key points correspond? Or how to do it?
Thank you for your reply, I wish you a happy life!
![image](https://github.com/open-mmlab/mmpose/assets/39481420/3e8595c2-fcdc-4a14-8f61-1307c8328ef8)

**Comment by Tau-J** [comment]
Thanks for using MMPose. CocoMetric doesn't support COCO-wholebody-hand, because the number of keypoints in annotations (133 kpts) is different from the number of hand keypoints (21 kpts).

**Comment by mywordwin** [comment]
> 感谢您使用 MMPose。CocoMetric 不支持 COCO-wholebody-hand，因为注释中的关键点数 (133 kpts) 与手部关键点数 (21 kpts) 不同。

Thank you for your timely reply. I use cocowholebodymetric and just want to use lefthand and righthand to evaluate the model trained by coco-wholebody-hand. Is this possible or do you have any suggestions? I am eager to use these algorithms on coco-wholebody-hand The ap, ar evaluation index instead of auc...

**Comment by Tau-J** [comment]
Currently, for 21-kpt model, you have to prepare the 21-kpt annotation file, so that you can evaluate it with Cocometric. If you have the ability to do some developments, I suggest adding a mapping function to convert the 133-kpt array into 21-kpt ones.

**Comment by mywordwin** [comment]
> 目前，对于 21-kpt 模型，您必须准备 21-kpt 注释文件，以便您可以使用 Cocometric 对其进行评估。如果你有能力做一些开发，我建议添加一个映射函数，将 133-kpt 数组转换为 21-kpt 数组。

OK, thank you for your timely reply, I got it, I wish you a happy life!
