### ISSUE TITLE
After converting the official pth model with mmpose to the onnx model, the accuracy of the keypoints of the feet decreases a lot

### ISSUE THREAD

**Issue by LMR2018** [open-mmlab/mmpose#2388]
### 📚 The doc issue

After converting the official pth model with mmpose to the onnx model, the accuracy of the keypoints of the feet decreases a lot
'--deploy-cfg', default='configs/mmpose/pose-detection_onnxruntime_static.py'
'--model-cfg', default='configs/wholebody_2d_keypoint/topdown_heatmap/coco-wholebody/td-hm_hrnet-w48_dark-8xb32-210e_coco-wholebody-384x288.py'
'--checkpoint', default='https://download.openmmlab.com/mmpose/pretrain_models/hrnet_w48-8ef0771d.pth',

![Snipaste_2023-05-22_16-23-45](https://github.com/open-mmlab/mmpose/assets/37955893/f2ff5af2-6ce7-4071-b721-8c1a4ab729a2)
![output3](https://github.com/open-mmlab/mmpose/assets/37955893/e48dc47a-db50-409c-9968-90a3c202dfd8)
https://platform.openmmlab.com/deploee/add-task-convert

**Comment by Tau-J** [comment]
The python inference script will conduct flip-testing by default, which can improve the performance.

**Comment by LMR2018** [comment]
那么转成onnx模型后，跑一个图片不就要进行两次推理了？一次正常的，一次flip(-1)翻转的，那速度不是很慢了？

**Comment by Tau-J** [comment]
是的，flip-test是一种测试时牺牲速度来增强模型精度的技术，是否使用需要进行权衡，在速度需求高的场景是不适合用的。MMPose作为一个开源项目只能使用开源数据集，是无法保证业务场景能表现好的，而且wholebody本身数据量就很小，表现不好是在情理之中的。我建议你使用自己公司的业务数据来微调，或者可以等待后续RTMPose的wholebody模型。
