### ISSUE TITLE
[Bug] train Associative Embedding

### ISSUE THREAD

**Issue by VEGETALOADING** [open-mmlab/mmpose#2389]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

when i want to train Associative Embedding on mmpose, i find that default train_pipeline is null, is that right?

### Reproduces the problem - code sample

# pipelines
train_pipeline = []

### Reproduces the problem - command or script

how to reright?

### Reproduces the problem - error message

should i update the default train_pipeline?

**Comment by Tau-J** [comment]
Thanks for using MMPose. Associative Embedding is still under refactory in MMPose 1.0. You can use the previous version i.e. 0.x

**Comment by VEGETALOADING** [comment]
how to install the previous version i.e. 0.x?

**Comment by Tau-J** [comment]
```python
git clone https://github.com/open-mmlab/mmpose.git -b 0.x
pip install -e .
```
