### ISSUE TITLE
[Docs] demo/image_demo.py issue

### ISSUE THREAD

**Issue by comaraDOTcom** [open-mmlab/mmpose#2392]
### 📚 The doc issue

I've followed the install guide in the [docs](https://mmpose.readthedocs.io/en/latest/installation.html#install-as-a-python-package) and am running into an issue running the inference demo. Running `mim download mmpose --config td-hm_hrnet-w48_8xb32-210e_coco-256x192  --dest .` saves a `td-hm_hrnet-w48_8xb32-210e_coco-256x192.py` and a `td-hm_hrnet-w48_8xb32-210e_coco-256x192-0e67c616_20220913.pth` in my directory. Note the second file is different to the naming suggested in the demo (`hrnet_w48_coco_256x192-b9e0b3ab_20200708.pth`).

Run the following command next.
```python
python demo/image_demo.py \
    tests/data/coco/000000000785.jpg \
    td-hm_hrnet-w48_8xb32-210e_coco-256x192.py \
    td-hm_hrnet-w48_8xb32-210e_coco-256x192-0e67c616_20220913.pth \
    --out-file vis_results.jpg \
    --draw-heatmap --device cpu
```

And get the following error.
```
Loads checkpoint by local backend from path: td-hm_hrnet-w48_8xb32-210e_coco-256x192-0e67c616_20220913.pth
The model and loaded state dict do not match exactly

unexpected key in source state_dict: data_preprocessor.mean, data_preprocessor.std

05/23 09:10:06 - mmengine - WARNING - `Visualizer` backend is not initialized because save_dir is None.
```

I'm wondering is there a different config I should use for this example demo?

### Suggest a potential alternative/fix
Is there a version I should specify. Or a different config that should be used?

**Comment by Ezreal0211** [comment]
I have the same problem as you. I reported an error while verifying whether the mmpose download was successful. The weight file name I downloaded is different from the weight file name prompted in the tutorial, resulting in an error during operation. Have you solved it yet?
`FileNotFoundError: hrnet_w48_coco_256x192-b9e0b3ab_20200708.pth can not be found.`
The commands given in the installation tutorial：
![image](https://github.com/open-mmlab/mmpose/assets/125781444/8b0f296c-1bc5-4330-88c3-746c82438f70)
The weight file name obtained by downloading the command（mim download mmpose --config td-hm_hrnet-w48_8xb32-210e_coco-256x192  --dest .）: 
![image](https://github.com/open-mmlab/mmpose/assets/125781444/7ef27171-6525-434f-91de-d06472b3ed4f)

 
笔记

**Comment by comaraDOTcom** [comment]
Well I renamed the weights file in the command to match the filename I downloaded.

**Comment by Ezreal0211** [comment]
I have tried this before, but I still reported an error.
![image](https://github.com/open-mmlab/mmpose/assets/125781444/62482dee-f3b6-4fd1-88db-44699723c679)
![image](https://github.com/open-mmlab/mmpose/assets/125781444/32317319-7120-4fd2-8095-6f41172c9726)

**Comment by comaraDOTcom** [comment]
I think you're missing the file extension `.pth` when you call it.
