### ISSUE TITLE
[Docs] mmpose/projects yolox-pose rtmpose licensing

### ISSUE THREAD

**Issue by BDJohnston** [open-mmlab/mmpose#2393]
### 📚 The doc issue

Can you please confirm whether the yolox-pose and rtmpose implementations in mmpose/projects are covered by a GNU General Public License v3.0 or a Apache License 2.0 license?

**Comment by Tau-J** [comment]
Thanks for using MMPose. Both of YOLOX-Pose and RTMPose are covered by Apache License 2.0. All of MMPose projects are licensed with permission for commercial use.
