### ISSUE TITLE
[Feature] Why alway keep aspect_ratio?

### ISSUE THREAD

**Issue by 610265158** [open-mmlab/mmpose#2395]
### What is the feature?

I found that it is always keep aspect_ratio in TopdownAffine. Is it the best way? I think we may need a parameter to control it. How do you think?

**Comment by Ben-Louis** [comment]
Interesting idea! But we have not conducted related experiments to verify the effectiveness of fixed aspect ratio. Our current use is simply to maintain the original shape of the instance. How do you think the aspect ratio should be appropriately assigned?

**Comment by Ben-Louis** [comment]
Thank you kindly for your thoughtful suggestion. Might you be interested in lending your support to this feature in MMPose?

**Comment by 610265158** [comment]
yes, would like to.  And i will do some experiments with that feature, firstly.

**Comment by 610265158** [comment]
After some experiments, mainly work on face keypoints task. It seems that there is not significant improvement with random aspect ratio.
