### ISSUE TITLE
Modify the backbone HRNET

### ISSUE THREAD

**Issue by mywordwin** [open-mmlab/mmpose#2398]
Modified the convolution method in the BasicBlock of Backbone-hrnet (using Ghost convolution instead of regular convolution), and then reported this error, is there something I missed in the middle? Please answer, thank you
![image](https://github.com/open-mmlab/mmpose/assets/39481420/9cf44c61-ede4-4e25-8e37-e8f625f4631c)

**Comment by Tau-J** [comment]
Thanks for using MMPose. [Configs](https://mmpose.readthedocs.io/en/dev-1.x/user_guides/configs.html) may help you to understand the system. Specifically, you need to modify the backbone in `mmpose/models/backbones/hrnet.py`, add the custom args, then you can use them in config.

**Comment by mywordwin** [comment]
> Thanks for using MMPose. [Configs](https://mmpose.readthedocs.io/en/dev-1.x/user_guides/configs.html) may help you to understand the system. Specifically, you need to modify the backbone in `mmpose/models/backbones/hrnet.py`, add the custom args, then you can use them in config.

Define the basic block for replacing convolution in resnet

![image](https://github.com/open-mmlab/mmpose/assets/39481420/02a3d500-8d05-4e19-adcd-bb3435c08432)

Import the defined in HRNET
![image](https://github.com/open-mmlab/mmpose/assets/39481420/7e86aff6-bef0-4ba8-82e1-1c3483efeac6)

Finally modify the config file, I'm so confused, what's the problem?

**Comment by Tau-J** [comment]
Sorry, I cannot understand your issue. If need, just feel free to describe in Chinese.

**Comment by mywordwin** [comment]
> Sorry, I cannot understand your issue. If need, just feel free to describe in Chinese.

你好，我的意思是我对hrnet的basicblock做了修改，仿照basicblock的写法写了一个G_BasicBlock，并打算在hrnet中引入他，    blocks_dict = {'BASIC': BasicBlock, 'BOTTLENECK': Bottleneck, 'GBASIC':G_BasicBlock  }，但是遇到了这个问题TypeError: TopDown: HRNet: expansion is not specified for G_BasicBlock，请问这是什么问题？望指教，祝生活愉快！

![image](https://github.com/open-mmlab/mmpose/assets/39481420/d34757c8-3ce6-4446-856c-67af346a42e3)

**Comment by Tau-J** [comment]
你好，通过以下 debug 过程可以定位你的问题：
- 在 backbones/hrnet.py 中搜索 `expansion` 可以找到 `get_expansion()`
- 经过跳转来到 backbones/resnet.py 下可以看到 `get_expansion()` 只支持特定的Block类型，或者block拥有`.expansion` 成员，所以无法处理你自定义的block

所以，如果你只是希望让模型顺利运行起来，你可以修改`get_expansion()`，增加对你的自定义模块的支持，返回特定的`expansion`值。

当然，我认为在hrnet中使用resnet.py下的`get_expansion()`并不是一个好的写法，更合理的实现应该是在hrnet.py下实现一个新的`get_expansion()`。请问你是否愿意提一个PR来完成这个功能？感谢你的提问帮助我发现了这个问题，如果不愿意我也会尽快修复这个问题。
