### ISSUE TITLE
What is the purpose of "COCO_val2017_detections_AP_H_56_person.json" while testing model?

### ISSUE THREAD

**Issue by hellosungha** [open-mmlab/mmpose#2400]
### What is the feature?

I'm doing test with trained model of 3xrsn50 model of 2D body keypoint detection with halpe dataset. I found it is gonna different when erase 'bbox_file' of dataset of val_dataloader in config file. The difference is about number of Epoch when doing test. 
What is purpose of this json when doing test with coco base dataset? What's gonna happen when I erase this?
(I tried to erase this to try test with my own validation dataset. There are also bbox information in validation annotation file(I used halpe_val_v1.json), so I thought human detection annotation is not necessary .)

val_dataloader = dict(
    batch_size=32,
    num_workers=4,
    persistent_workers=True,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False, round_up=False),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        data_mode=data_mode,
        ann_file='mmpose/data/halpe/annotations/halpe_val_v1.json',
        bbox_file='mmpose/data/halpe/person_detection_results/COCO_val2017_detections_AP_H_56_person.json',
        data_prefix=dict(img='mmpose/data/halpe/val2017/'),
        test_mode=True,
        pipeline=val_pipeline,
    ))
test_dataloader = val_dataloader

**Comment by LareinaM** [comment]
This file is the person detection result of COCO val2017 provided by [HRNet-Human-Pose-Estimation](https://github.com/HRNet/HRNet-Human-Pose-Estimation) to reproduce our multi-person pose estimation results.

**Comment by jin-s13** [comment]
bbox_file (str, optional): Detection result file path. If ``bbox_file`` is set, detected bboxes loaded from this file will be used instead of ground-truth bboxes. 

If you would like to use ground-truth bboxes, you can remove this.

**Comment by hellosungha** [comment]
I found that there are many overlapping bbox&score for one image.
Is there any advantage to use this person detection?

**Comment by Tau-J** [comment]
This simulates the input that a pose model would receive in a real-world scenario. As you know, real detectors are bound to have false positives (many overlapping bbox&score as you say). Evaluating with these bboxes gives metrics that are closer to the actual performance of the algorithm.

**Comment by hellosungha** [comment]
Thanks for your information!
