### ISSUE TITLE
[Docs] About dataflow document

### ISSUE THREAD

**Issue by kdavidlp123** [open-mmlab/mmpose#2402]
### 📚 The doc issue

![螢幕擷取畫面 2023-05-26 133650](https://github.com/open-mmlab/mmpose/assets/69571884/82c7b029-85a3-4dd1-8703-f67587c7028e)

Sorry, I would like to ask about the marked red area, where can I find the document.
Thank you!!!!

**Comment by Tau-J** [comment]
For the image and annotation part, you can refer to coresponding dataset definition in `mmpose/datasets/`. As for the prediction part, it is in `mmpose/models/pose_estimators`, specifically, in `predict()`

**Comment by kdavidlp123** [comment]
Thank, is inference also followed with this flowchart?

**Comment by Tau-J** [comment]
Sure

**Comment by kdavidlp123** [comment]
Thank you so much!!
