### ISSUE TITLE
[Feature] whether support Batch Augmentation

### ISSUE THREAD

**Issue by JH95-ai** [open-mmlab/mmpose#2403]
### What is the feature?

I want use batch augmention to deal with keypoints result jitter.
Details is :
if batch size =8,
after every sample image through train pipeline, repeat  or some move images to save ten images for train model
I don't know whether support in mmpose
Hope your reply THX

**Comment by Tau-J** [comment]
Thanks for using MMPose. Currently, we don't support batch augmentation. If you can create a PR to support, we will appreaciate so much.

**Comment by JH95-ai** [comment]
> Thanks for using MMPose. Currently, we don't support batch augmentation. If you can create a PR to support, we will appreaciate so much.

thanks your reply
