### ISSUE TITLE
How to train multiple label types

### ISSUE THREAD

**Issue by GXYao7** [open-mmlab/mmpose#2404]
### What is the feature?

I want to know whether in the top-down algorithm, the framework can train the pose of multiple labels at the same time, for example: there are pigs and sheep in my image, how should I operate and be able to get the evaluation indicators corresponding to the two labels; And how to make me show the label in my rectangular box when predicting the outcome

**Comment by Tau-J** [comment]
It depends on the number of keypoints you defined. If the number is the same, you can use a single pose model to predict, just like models trained on ap10k ([details](https://mmpose.readthedocs.io/en/dev-1.x/dataset_zoo/2d_animal_keypoint.html#ap-10k)). If not, I suggest training two models to predict kpts specifically.

**Comment by GXYao7** [comment]
Ok, my key points are the same, I'll look into the relevant content, thank you for your reply.
