### ISSUE TITLE
关于预训练模型推理图片输出关键点的问题

### ISSUE THREAD

**Issue by ainndejj11** [open-mmlab/mmpose#2407]
### What is the feature?

请问下，mmpose中coco数据集的人体骨骼关键点，使用下载的预训练模型推理图片，输入只有上半身的图片，也会输出17个点，膝盖和脚那就完全错误了。  这种情况怎么办，模型是一定输出17个点么？

如果自己标注一些数据集，这种半身的，可不可以只标注可见的部位的点？

**Comment by Tau-J** [comment]
谢谢使用 MMPose。 输出的关键点个数是固定的，一定会预测全部的点，对于画面中不存在点，可以通过每个点的置信度进行过滤（在我们的demo脚本中一般阈值设为0.3）。自己标注数据集时，每个点会有一个`visible`属性，详细细节可以查看 COCO 官方文档。
