### ISSUE TITLE
the input of hrnet must be 32x but i have a dataset with 260x346 what can i do

### ISSUE THREAD

**Issue by sunbaby01** [open-mmlab/mmpose#2409]
### What is the feature?

the input of hrnet must be 32x but i have a dataset with 260x346 what can i do.

**Comment by Tau-J** [comment]
In our pipeline, we will resize the image to the required size.

**Comment by sunbaby01** [comment]
but my annotation is in 260x346 and when i set input_size=260x346., it report feature dismatch. 256x352 will be work, but  my annotation is in 260x346

**Comment by Tau-J** [comment]
It doesn't matter, both of the image and annotation will be resized of course. I think the dismatch error is caused by other reason.

**Comment by sunbaby01** [comment]
thank for you answer. you mean the pipeline knows the original size of my picture and annotation such as 360x346. When i set a different input_size, such as 256x352, the pipeline will change picture and annotation into 256x352? 

i try it again, i set 360x346 in input_size, it reports that.
![image](https://github.com/open-mmlab/mmpose/assets/45324085/bcc46379-f94f-47bf-9ef1-6e9f0b753cf4)

**Comment by Tau-J** [comment]
No, the pipeline (train/val) will resize the image and annotations into the model required size, e.g. 256x192. But if you conduct inference yourself, you must resize the image manually into 256x192.
