### ISSUE TITLE
关于人体骨骼关键点标注数据的问题

### ISSUE THREAD

**Issue by ainndejj11** [open-mmlab/mmpose#2410]
### What is the feature?

请问  mmpose/configs/body/topdown_heatmap/coco    下的都是单人关键点检测。   标注这个coco的格式的数据集，除了17个关键点，还需要检测框的信息么，需要画框么？

 一般用什么工具进行标注呢

**Comment by Tau-J** [comment]
一般来说，如果已经有了关键点标注，就可以通过求一组关键点的外接框的方式得到bbox标注了，因此不需要手动再标一次。
