### ISSUE TITLE
failed to load library mmdeploy_trt_net.dll

### ISSUE THREAD

**Issue by mozhijing** [open-mmlab/mmpose#2411]
### 📚 The doc issue

https://github.com/open-mmlab/mmpose/tree/main/projects/rtmpose#python-inference-1
In the window environment, there is a problem with using python pose_tracker.py

**Comment by Tau-J** [comment]
Thanks for using MMPose. It seems that you need to set trt lib path properly. For more help, I suggest creating an issue in mmdeploy.
