### ISSUE TITLE
关于mmpose在mmploy C++demo中的问题

### ISSUE THREAD

**Issue by ainndejj11** [open-mmlab/mmpose#2412]
### What is the feature?

请问下，mmpose中coco数据集的人体骨骼关键点，使用下载的预训练模型推理图片，像是输入这种半身的图片，也会输出17个点，腿和脚那就完全错误了。 这种情况怎么办，关键点阈值的源码在什么位置呢？

**Comment by Tau-J** [comment]
我们在 codec 中定义每种算法的解码过程，用于从模型的输出结果里得到坐标和置信度，你可以从 [这里](https://github.com/open-mmlab/mmpose/tree/main/mmpose/codecs) 找到你使用的算法对应的解码过程。mmdeploy具体的源码位置请前往 mmdeploy 询问。
