### ISSUE TITLE
How to change directory of visualizer while doing inference?

### ISSUE THREAD

**Issue by hellosungha** [open-mmlab/mmpose#2423]
### What is the feature?

I've noticed that visualizer.py code in site-packages is used while doing inference with "topdown_demo_with_mmdet.py" .

/opt/conda/lib/python3.7/site-packages/mmengine/visualization/visualizer.py:666: UserWarning: Warning: The circle is out of bounds, the drawn circle may not be in the image
  ' the drawn circle may not be in the image', UserWarning)

But it is bit difficult fix and customizing the code in site-packages, so I wanted to make it set to use mmengine/visualization/visualizer.py code in my work directory.
What should I do?

**Comment by hellosungha** [comment]
I already installed mmengine before using mmpose. So, imported visualizer from mmpose.registry in "topdown_demo_with_mmdet.py" is refer to visualizer module in site-packages.
What I want to know is how to make it change visualizer module to refer to local mmengine code in my work directory.

**Comment by Ben-Louis** [comment]
You can install mmengine \***from source**\* following [this doc](https://mmengine.readthedocs.io/en/latest/get_started/installation.html#build-from-source) and modify the code in the cloned repo.

**Comment by hellosungha** [comment]
Thank you, I made it!
