### ISSUE TITLE
[Feature] Does OpenMMPose provide any existed file to test models‘s AP on COCO val2017?

### ISSUE THREAD

**Issue by StephStates** [open-mmlab/mmpose#2426]
### What is the feature?

The website gives hrnet model mAP result on COCO val2017,  I wanna test all the APs  of 17 different human body keypoints on COCO val2017.  Does MMPose provide command-line command to do this or I need to write my own script to do it. If so, how to do that?   I would be so grateful if you could help me out!

**Comment by Ben-Louis** [comment]
Hi, thanks for using MMPose. The feature you're seeking could potentially be accommodated by the [KeypointPartitionMetric](https://mmpose.readthedocs.io/en/latest/_modules/mmpose/evaluation/metrics/keypoint_partition_metric.html?highlight=partition%20metric). You can configure the `KeypointPartitionMetric` like:
```python
val_evaluator = dict(
        type='KeypointPartitionMetric',
        metric=dict(
            type='CocoMetric',
        ),
        partitions=dict(
            kpt0=range(0,1),
            kpt1=range(1,2),
            ...
            kpt16=range(16, 17),
            all=range(17)
        )
)
```

**Comment by StephStates** [comment]
I've got the config file of the model I would like to test and the val 2017 of COCO, what command-line command should I execute to get the result?

**Comment by StephStates** [comment]
> Hi, thanks for using MMPose. The feature you're seeking could potentially be accommodated by the [KeypointPartitionMetric](https://mmpose.readthedocs.io/en/latest/_modules/mmpose/evaluation/metrics/keypoint_partition_metric.html?highlight=partition%20metric). You can configure the `KeypointPartitionMetric` like:
> 
> ```python
> val_evaluator = dict(
>         type='KeypointPartitionMetric',
>         metric=dict(
>             type='CocoMetric',
>         ),
>         partitions=dict(
>             kpt0=range(0,1),
>             kpt1=range(1,2),
>             ...
>             kpt16=range(16, 17),
>             all=range(17)
>         )
> )
> ```

I've got the config file of the model I would like to test and the val 2017 of COCO, what command-line command should I execute to get the result?

**Comment by Tau-J** [comment]
Modify the evaluator part of the config, and then use `tools/test.py` to test following our [docs](https://mmpose.readthedocs.io/en/dev-1.x/user_guides/train_and_test.html).

**Comment by StephStates** [comment]
> Modify the evaluator part of the config, and then use `tools/test.py` to test following our [docs](https://mmpose.readthedocs.io/en/dev-1.x/user_guides/train_and_test.html).

thanks! that's really helpful!

**Comment by StephStates** [comment]
> Modify the evaluator part of the config, and then use `tools/test.py` to test following our [docs](https://mmpose.readthedocs.io/en/dev-1.x/user_guides/train_and_test.html).

Sorry for my ignorance! But there's so many alike files all talking about the evaluation. If all I need to do is typing the code"python tools/test.py {configfile} {checkpointfile}", where exactly should I add the code @Ben-Louis suggest me to configure so I can get the results I need after running it.  Sincerely sorry again for taking your time, but I do need it!

**Comment by StephStates** [comment]
> Modify the evaluator part of the config, and then use `tools/test.py` to test following our [docs](https://mmpose.readthedocs.io/en/dev-1.x/user_guides/train_and_test.html).

Sorry for my ignorance! But there's so many alike files all talking about the evaluation. If all I need to do is typing the code"python tools/test.py {configfile} {checkpointfile}", where exactly should I add the code @Ben-Louis suggest me to configure so I can get the results I need after running it. Sincerely sorry again for taking your time, but I do need it!

**Comment by Tau-J** [comment]
Hi @StephStates , we provide many pre-made configs and their corresponding [ckpt files](https://mmpose.readthedocs.io/en/dev-1.x/model_zoo/body_2d_keypoint.html). You can see the differences based on the file names, for more detailed information please refer to the [documentation](https://mmpose.readthedocs.io/en/dev-1.x/user_guides/configs.html). When you have customized needs (such as KeypointPartitionMetric), you only need to modify the corresponding parts of the same config.

**Comment by StephStates** [comment]
> Hi @StephStates , we provide many pre-made configs and their corresponding [ckpt files](https://mmpose.readthedocs.io/en/dev-1.x/model_zoo/body_2d_keypoint.html). You can see the differences based on the file names, for more detailed information please refer to the [documentation](https://mmpose.readthedocs.io/en/dev-1.x/user_guides/configs.html). When you have customized needs (such as KeypointPartitionMetric), you only need to modify the corresponding parts of the same config.

thank you so much! I've figured it out yesterday, and certainly your advice helped a lot!
