### ISSUE TITLE
[Bug]    assert (mmcv_version >= digit_version(mmcv_minimum_version)

### ISSUE THREAD

**Issue by alaa-shubbak** [open-mmlab/mmpose#2429]
n### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

my environment is as bellow : 

`
{'sys.platform': 'linux', 'Python': '3.9.10 (main, Mar  4 2022, 13:58:45) [GCC 8.4.0]', 'CUDA available': True, 'GPU 0': 'Tesla V100-SXM2-32GB', 'CUDA_HOME': '/usr/local/cuda', 'NVCC': 'Build cuda_12.1.r12.1/compiler.32688072_0', 'GCC': 'gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)', 'PyTorch': '1.10.0+cu111', 'PyTorch compiling details': 'PyTorch built with:\n  - GCC 7.3\n  - C++ Version: 201402\n  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)\n  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n  - LAPACK is enabled (usually provided by MKL)\n  - NNPACK is enabled\n  - CPU capability usage: AVX512\n  - CUDA Runtime 11.1\n  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86\n  - CuDNN 8.0.5\n  - Magma 2.5.2\n  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, \n', 'TorchVision': '0.11.0+cu111', 'OpenCV': '4.6.0', 'MMCV': '1.4.6', 'MMCV Compiler': 'n/a', 'MMCV CUDA Compiler': 'n/a', 'MMPose': '0.29.0+8e6169b'}

`

### Reproduces the problem - code sample

as i am working on some previous version of mmpose (mmpose version 0.29.0)
i am trying to test my model using this command : 

`python demo/top_down_img_demo.py configs/excavator/resnet50normal/res50_animalpose_256x256_new_pose_6p.py /work/shubbak/mmpose_train/resnet_50_original/new_poe_data_6p_Normal/best_AP_epoch_320.pth --img-root /work/shubbak/datasets/new_pose/images/ --json-file /work/shubbak/datasets/new_pose/annotations/annotation_test_new.json --out-img-root vis_results_6p_resnet50_normal --kpt-thr 0.3`

### Reproduces the problem - command or script

i am running to test the model that i already have and i want to see the results as images. 
please notice that i am using old mmpose version as my config is written according to 0.29.0 version of mmpose. 
so that i expected that i need old  version from mmcv . but now i am so confused . i don't know which version will work correctly. 

i try to use mmcv -versions of : 1.7.0 , 1.7.1, 1.6.0, 
1.3.8, 2.0.0rc4
 all of  them did not work

### Reproduces the problem - error message

`
Traceback (most recent call last):
  File "/home/shubbak/mmpose_old/demo/top_down_img_demo.py", line 9, in <module>
    from mmpose.apis import (inference_top_down_pose_model, init_pose_model,
  File "/home/shubbak/env_pose/lib/python3.9/site-packages/mmpose/__init__.py", line 16, in <module>
    assert (mmcv_version >= digit_version(mmcv_minimum_version)
AssertionError: MMCV==1.4.6 is used but incompatible. Please install mmcv>=2.0.0rc4, <=2.1.0.

`

**Comment by alaa-shubbak** [comment]
look here please : 
![image](https://github.com/open-mmlab/mmpose/assets/10245810/6ac25d19-aca6-4792-aca4-d10556c62756)

as i am use mmpose 0.29.0 , it needs to  install mmcv>=1.3.8, <=1.8.0.

but also the system gives me this error : 
![image](https://github.com/open-mmlab/mmpose/assets/10245810/677b1441-7e8d-47aa-a18b-6ce1c8a64ea5)


so what shall i do?

**Comment by Ben-Louis** [comment]
Hi, thanks for using MMPose. The demo script you're utilizing relies on mmdet, which could potentially be the root of the version conflict you're experiencing. If your are using mmpose 0.x, please ensure you are using mmdet 2.x and mmcv 1.x at the same time.
