### ISSUE TITLE
[Feature] MMPoseInferencer support for 3D models.

### ISSUE THREAD

**Issue by zh-plus** [open-mmlab/mmpose#2432]
### What is the feature?

Now MMPoseInferencer supports vitpose and rtmpose, both of which are 2D pose estimation methods. Will you consider adding 3D models in the future, such as videopose3D and simplebaseline?

**Comment by Ben-Louis** [comment]
Certainly! This feature is under development. We appreciate your patience as we work to make it available. Additionally, if you're interested in contributing to the development of this feature, please don't hesitate to reach out. We'd be delighted to discuss potential collaboration

**Comment by zh-plus** [comment]
Thanks!
