### ISSUE TITLE
[Docs] How to configure multi-person pose estimation

### ISSUE THREAD

**Issue by MarioMatuschek** [open-mmlab/mmpose#2434]
### 📚 The doc issue

It is stated that RTMPose is able to run multi-person pose estimation on images as well as videos. However, when I run the model on some sample images I always just receive a single pose for one selected person among many in the image. After some research, I did not find any concrete information on the potential cause of error. My current assumption is that I need to adjust the default config-file - is this a valid assumption? If yes, how should this be done or if not in this way, how can I ensure my model to work in the multi-person case?

**Comment by MarioMatuschek** [comment]
Thank you very much for the comment - but the suggested demo script requires a lot of dependencies that cause multiple conflicts. Is there a comprehensive requirements, docker or other environment file that supports all dependencies ranging (mmengine, mmdet, mmpose, mmcv, etc.)?

Following the instructions of the provided README do not solve the issue. I created a separate docker with a respective shell script to set it all up. 

#!/bin/bash
set -eu

# clean up
rm -rf mmcv/ mmdeploy/ mmdetection/ mmpose/ onnxruntime-linux-x64-gpu-1.14.1*

# install necessary python dependencies
python3 -m pip install openmim onnxruntime-gpu==1.14.1 numpy==1.23.5 numba==0.56.4 scipy==1.10.1

# get onnxruntime
wget https://github.com/microsoft/onnxruntime/releases/download/v1.14.1/onnxruntime-linux-x64-gpu-1.14.1.tgz
tar -zxvf onnxruntime-linux-x64-gpu-1.14.1.tgz

export ONNXRUNTIME_DIR=$(pwd)/onnxruntime-linux-x64-gpu-1.14.1

# get open-mmlab mmcv
git clone https://github.com/open-mmlab/mmcv.git
cd mmcv
git checkout v2.0.0rc4
git submodule update --init
python3 -m pip install -r requirements/optional.txt
MMCV_WITH_OPS=1 pip install -e .
python3 .dev_scripts/check_installation.py
cd ..

# get open-mmlab mmdetection
git clone https://github.com/open-mmlab/mmdetection.git
cd mmdetection
git checkout v3.0.0rc6
python3 -m pip install -e .
cd ..

# get open-mmlab mmpose
git clone https://github.com/open-mmlab/mmpose.git
cd mmpose
git checkout v1.0.0rc1
python3 -m pip install -e .
cd ..

# get open-mmlab mmdeploy
git clone https://github.com/open-mmlab/mmdeploy.git
# export MMDEPLOY_DIR=$(pwd)/mmdeploy
cd mmdeploy
git checkout v1.0.0rc3
mkdir -p build
cd build
cmake -DMMDEPLOY_TARGET_BACKENDS=ort -DONNXRUNTIME_DIR=$ONNXRUNTIME_DIR ..
make -j32
make install
cd ..
python3 -m mim install -e .
cd ..

The docker container I create previously is called with the following command: 

docker run -it --gpus all -v $PWD:/work nvcr.io/nvidia/pytorch:22.12-py3

The environment itself is set up with a further shell script, that contains the following code: 

#!/bin/bash
set -e

export ONNXRUNTIME_DIR=$(pwd)/onnxruntime-linux-x64-gpu-1.14.1
export LD_LIBRARY_PATH=$ONNXRUNTIME_DIR/lib:$LD_LIBRARY_PATH
export MMDEPLOY_DIR=$(pwd)/mmdeploy

This seems to solve all  my dependency issues but still cannot run multi-person pose estimation / detection. The pose estimation model does only return poses for one model.

**Comment by Tau-J** [comment]
You can refer to the ]installation guide](https://mmpose.readthedocs.io/en/dev-1.x/installation.html) to install mmpose easily.
