### ISSUE TITLE
Please check whether the value of `CSPNeXt` is correct or it was registered as expected.

### ISSUE THREAD

**Issue by Rx2633** [open-mmlab/mmpose#2438]
### 📚 The doc issue

I try  Custom Pose Estimation Models

from mmpose.apis import MMPoseInferencer

img_path = r'E:/mmpose-main/tests/data/coco/000000000785.jpg'

inferencer = MMPoseInferencer(
     pose2d='human',
    det_model='configs/body_2d_keypoint/topdown_regression/coco/td-reg_res101_rle-8xb64-210e_coco-256x192.py',
    det_weights=r'E:/mmpose-main/deeppose_res101_coco_256x192_rle-16c3d461_20220615.pth',
    det_cat_ids=[0]
)
result_generator = inferencer(img_path, show=True)
result = next(result_generator)

BUT：
KeyError: "class `TopdownPoseEstimator` in mmpose/models/pose_estimators/topdown.py: 'CSPNeXt is not in the model registry. Please check whether the value of `CSPNeXt` is correct or it was registered as expected. More details can be found at

**Comment by Tau-J** [comment]
Thanks for using MMPose. To use RTMPose, you need to install mmdet via `mim install mmdet` first.
