### ISSUE TITLE
[Bug] demo during installation DLL load failed 

### ISSUE THREAD

**Issue by LjIA26** [open-mmlab/mmpose#2441]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

Hello! 

I was trying the latest version of mmpose, as I have been running the older version for a while now. And I don't get a successful instalation

### Reproduces the problem - code sample

```
  File "D:\demo\mmpose\demo\image_demo.py", line 105, in <module>
    main()
  File "D:\demo\mmpose\demo\image_demo.py", line 69, in main
    model = init_model(
  File "d:\demo\mmpose\mmpose\apis\inference.py", line 102, in init_model
    model = revert_sync_batchnorm(model)
  File "C:\Users\LJ\anaconda3\envs\inference\lib\site-packages\mmengine\model\utils.py", line 174, in revert_sync_batchnorm
    from mmcv.ops import SyncBatchNorm
  File "C:\Users\LJ\anaconda3\envs\inference\lib\site-packages\mmcv\ops\__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "C:\Users\LJ\anaconda3\envs\inference\lib\site-packages\mmcv\ops\active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "C:\Users\LJ\anaconda3\envs\inference\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "C:\Users\LJ\anaconda3\envs\inference\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)


```

### Reproduces the problem - command or script

```
python demo/image_demo.py  tests/data/coco/000000000785.jpg td-hm_hrnet-w48_8xb32-210e_coco-256x192.py hrnet_w48_coco_256x192-b9e0b3ab_20200708.pth --out-file vis_results.jpg --draw-heatmap

```

### Reproduces the problem - error message

```
ImportError: DLL load failed while importing _ext: The specified procedure could not be found.

```

**Comment by Tau-J** [comment]
Hi @LjIA26 , this error message infers that your pytorch version is not compatible with your cuda. I suggest checking your cuda version via `nvidia-smi` and `pip list | grep torch` to make sure that `torch+cu1xx` is the same. If not, you need to install correct `pytorch`. After that, you need to reinstall `mmcv`, because mmcv is compiled accroding to your pytorch.

**Comment by LjIA26** [comment]
I solved it thank you

**Comment by justsonghua** [comment]
> Hi @LjIA26 , this error message infers that your pytorch version is not compatible with your cuda. I suggest checking your cuda version via `nvidia-smi` and `pip list | grep torch` to make sure that `torch+cu1xx` is the same. If not, you need to install correct `pytorch`. After that, you need to reinstall `mmcv`, because mmcv is compiled accroding to your pytorch.

![Snipaste_2024-04-11_13-08-18](https://github.com/open-mmlab/mmpose/assets/41994375/757208cb-a56a-4b27-87a1-947bee3a5df5)

Hi. `PyTorch`的文档说 `torch 2.2+`已经支持到`CUDA 12.4`了。但是在按照教程先安装`PyTorch`，再安装的`mmcv`后。我还是遇到了

```ImportError: DLL load failed while importing _arpack: The specified module could not be found.```

的问题。

这依旧还是`CUDA`和`PyTorch`版本产生的问题吗？

**Comment by justsonghua** [comment]
> > Hi @LjIA26 , this error message infers that your pytorch version is not compatible with your cuda. I suggest checking your cuda version via `nvidia-smi` and `pip list | grep torch` to make sure that `torch+cu1xx` is the same. If not, you need to install correct `pytorch`. After that, you need to reinstall `mmcv`, because mmcv is compiled accroding to your pytorch.
> 
> ![Snipaste_2024-04-11_13-08-18](https://private-user-images.githubusercontent.com/41994375/321607307-757208cb-a56a-4b27-87a1-947bee3a5df5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NDY1MDUsIm5iZiI6MTcxMjg0NjIwNSwicGF0aCI6Ii80MTk5NDM3NS8zMjE2MDczMDctNzU3MjA4Y2ItYTU2YS00YjI3LTg3YTEtOTQ3YmVlM2E1ZGY1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDE0MzY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwYzVmYTY3NDQ1ODhhY2YxNzk3ODA0MWU0MzFlMTUwODBlYTU0ODk5ZGIzMDA0YzY2M2MyYzE4MGIwZmFmZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-7PHM0_Izl55pzkiXtP82Eg9WN-7bbDLiCgIuaMX-b8)
> 
> Hi. `PyTorch`的文档说 `torch 2.2+`已经支持到`CUDA 12.4`了。但是在按照教程先安装`PyTorch`，再安装的`mmcv`后。我还是遇到了
> 
> `ImportError: DLL load failed while importing _arpack: The specified module could not be found.`
> 
> 的问题。
> 
> 这依旧还是`CUDA`和`PyTorch`版本产生的问题吗？

不知道是什么原因，我`conda`环境下的`scipy`被指向了另一个环境。

使用`pip install --force-reinstall scipy`指令后，demo可以成功运行。
