### ISSUE TITLE
mAP and recall of each key point

### ISSUE THREAD

**Issue by hsp2454** [open-mmlab/mmpose#2457]
### What is the feature?

Hello, I would like to ask how to calculate the evaluation indicators such as mAP and recall of each key point separately in mmpose0.x

**Comment by LareinaM** [comment]
Hi, thanks for using MMPose. Please refer to our [doc](https://mmpose.readthedocs.io/en/0.x/api.html#module-mmpose.core.evaluation).

**Comment by hsp2454** [comment]
Unfortunately, this does not solve the problem. Is there a more detailed solution?
