### ISSUE TITLE
[Bug] Is it a bug in KeypointMSELoss's _get_mask function?

### ISSUE THREAD

**Issue by treasureqqm** [open-mmlab/mmpose#2464]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

skip

### Reproduces the problem - code sample

skip

### Reproduces the problem - command or script

skip

### Reproduces the problem - error message

skip

### Additional information

The function is _get_mask of class KeypointMSELoss in the file mmpose/models/losses/heatmap_loss.py. I think the code "_mask = (target != 0).flatten(2).any()" should be "_mask = (target != 0).flatten(2).any(dim=2)", is it?

**Comment by Ben-Louis** [comment]
Thank you for your feedback. You are right. Would you be interested in submitting a Pull Request to resolve this issue?

**Comment by treasureqqm** [comment]
> Thank you for your feedback. You are right. Would you be interested in submitting a Pull Request to resolve this issue?

Sorry for late reply, my github connection is bad these days (and I also don't know the procedure to create and test a PR). And I see you have already created a PR and tested it. Great job!
