### ISSUE TITLE
[Feature] deepfashion pretrained model

### ISSUE THREAD

**Issue by Cathy0908** [open-mmlab/mmpose#2465]
### What is the feature?

Are there pretrained deepfashion models ?

**Comment by Ben-Louis** [comment]
You can find several pretrained DeepFashion2 models at this link: https://github.com/open-mmlab/mmpose/blob/main/configs/fashion_2d_keypoint/topdown_heatmap/deepfashion2/res50_deepfashion2.md. 

However, please note that the new version does not yet support the DeepFashion dataset. You may refer to the [model zoo of MMPose 0.x](https://mmpose.readthedocs.io/en/0.x/papers/datasets.html#deepfashion-cvpr-2016) for relevant models.

**Comment by Cathy0908** [comment]
thanks very much
