### ISSUE TITLE
[Bug] AttributeError: 'ConfigDict' object has no attribute 'model'

### ISSUE THREAD

**Issue by eqwwadfw** [open-mmlab/mmpose#2470]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

OrderedDict([('sys.platform', 'linux'), ('Python', '3.10.10 (main, Mar 21 2023, 18:45:11) [GCC 11.2.0]'), ('CUDA available', True), ('numpy_random_seed', 2147483648), ('GPU 0,1', 'TITAN RTX'), ('CUDA_HOME', '/usr/local/cuda'), ('NVCC', 'Cuda compilation tools, release 11.2, V11.2.67'), ('GCC', 'gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)'), ('PyTorch', '2.0.1+cu117'), ('PyTorch compiling details', 'PyTorch built with:\n  - GCC 9.3\n  - C++ Version: 201703\n  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)\n  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n  - LAPACK is enabled (usually provided by MKL)\n  - NNPACK is enabled\n  - CPU capability usage: AVX2\n  - CUDA Runtime 11.7\n  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86\n  - CuDNN 8.5\n  - Magma 2.6.1\n  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, \n'), ('TorchVision', '0.15.2+cu117'), ('OpenCV', '4.7.0'), ('MMEngine', '0.7.4'), ('MMPose', '1.0.0+59eff49')])

mmcv                     2.0.0
mmdet                    3.0.0        /home/jiao_yang/mmdetection
mmengine                 0.7.4
mmpose                   1.0.0        /home/jiao_yang/mmpose
mmpycocotools            12.0.3

### Reproduces the problem - code sample

python demo/topdown_demo_with_mmdet.py \
>         demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py \
>         https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \
>         configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_hrnet-w32_8xb64-210e_coco-256x192.py \
>         https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_coco_256x192-c78dce93_20200708.pth \
>         --input data/test/multi-person.jpeg \
>         --output-root outputs/B1_HRNet_1 \
>         --device cuda:0 \
>         --bbox-thr 0.5 \
>         --kpt-thr 0.2 \
>         --nms-thr 0.3 \
>         --radius 8 \
>         --thickness 4 \
>         --draw-bbox \
>         --draw-heatmap \
>         --show-kpt-idx

### Reproduces the problem - command or script

python demo/topdown_demo_with_mmdet.py \
>         demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py \
>         https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \
>         configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_hrnet-w32_8xb64-210e_coco-256x192.py \
>         https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_coco_256x192-c78dce93_20200708.pth \
>         --input data/test/multi-person.jpeg \
>         --output-root outputs/B1_HRNet_1 \
>         --device cuda:0 \
>         --bbox-thr 0.5 \
>         --kpt-thr 0.2 \
>         --nms-thr 0.3 \
>         --radius 8 \
>         --thickness 4 \
>         --draw-bbox \
>         --draw-heatmap \
>         --show-kpt-idx

### Reproduces the problem - error message

Traceback (most recent call last):
  File "/home/jiao_yang/miniconda3/lib/python3.10/site-packages/mmengine/config/config.py", line 52, in __getattr__
    value = super().__getattr__(name)
  File "/home/jiao_yang/miniconda3/lib/python3.10/site-packages/addict/addict.py", line 67, in __getattr__
    return self.__getitem__(item)
  File "/home/jiao_yang/miniconda3/lib/python3.10/site-packages/mmengine/config/config.py", line 48, in __missing__
    raise KeyError(name)
KeyError: 'model'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jiao_yang/mmpose/demo/topdown_demo_with_mmdet.py", line 292, in <module>
    main()
  File "/home/jiao_yang/mmpose/demo/topdown_demo_with_mmdet.py", line 178, in main
    detector = init_detector(
  File "/home/jiao_yang/mmdetection/mmdet/apis/inference.py", line 57, in init_detector
    elif 'init_cfg' in config.model.backbone:
  File "/home/jiao_yang/miniconda3/lib/python3.10/site-packages/mmengine/config/config.py", line 903, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/jiao_yang/miniconda3/lib/python3.10/site-packages/mmengine/config/config.py", line 54, in __getattr__
    raise AttributeError(f"'{self.__class__.__name__}' object has no "
AttributeError: 'ConfigDict' object has no attribute 'model'

### Additional information

When I run train.py, there will be a 'model' related error. I can't find a solution to the related problem on the Internet. The configuration environment and code are normal. I hope you can help me point out my problem.

**Comment by LareinaM** [comment]
Hi, thanks for using MMPose. This error means that MMEngine could not find a key called 'model' from your detector configuration file. Please make sure that your detector configuration file is not modified and that MMPose is installed properly.

**Comment by eqwwadfw** [comment]
> 您好，感谢您使用 MMPose。此错误意味着 MMEngine 无法从您的检测器配置文件中找到名为“模型”的密钥。请确保您的检测器配置文件未被修改并且 MMPose 已正确安装。

**Comment by eqwwadfw** [comment]
> 您好，感谢您使用 MMPose。此错误意味着 MMEngine 无法从您的检测器配置文件中找到名为“模型”的密钥。请确保您的检测器配置文件未被修改并且 MMPose 已正确安装。

Thank you for your reply. I have checked it before and downloaded mmpose three times, but this problem has always occurred. In addition, I have not modified my detector configuration file, so neither I nor my classmates know what to do when encountering this problem. How to solve.

**Comment by eqwwadfw** [comment]
> 您好，感谢您使用MMPose。此错误意味着MMEngine无法从您的检测器配置文件中找到名为“模型”的密匙。请确保您的检测器配置文件未被修改和MMPose 已正确安装。

For the installation part, I refer to https://github.com/TommyZihao/MMPose_Tutorials/blob/main/2023/0524/%E3%80%90A1%E3%80%91%E5%AE%89%E8%A3 %85MMPose.ipynb, and see mmpose installed successfully in linux, the version is 1.0.0

**Comment by eqwwadfw** [comment]
> Hi, thanks for using MMPose. This error means that MMEngine could not find a key called 'model' from your detector configuration file. Please make sure that your detector configuration file is not modified and that MMPose is installed properly.

For the installation part, I refer to https://github.com/TommyZihao/MMPose_Tutorials/blob/main/2023/0524/%E3%80%90A1%E3%80%91%E5%AE%89%E8%A3%85MMPose.ipynb，and see mmpose installed successfully in linux, the version is 1.0.0

**Comment by LareinaM** [comment]
I am sorry but we could not reproduce your problem. I suggest you try [re-install MMEngine](https://mmengine.readthedocs.io/en/latest/get_started/installation.html) and raise the problem on their side.
