### ISSUE TITLE
The difference about YoloPose 

### ISSUE THREAD

**Issue by TengfeiHou** [open-mmlab/mmpose#2480]
### 📚 The doc issue

Thanks for ur great work!
I find something strange in YOLOPOSE project, where performance is difference in readme and training log. For instance, the medium model AP is 0.685 in coco at 640*640, but in log the best is about 0.6592 at 300 epochs. And the small model AP is 0.632 in coco at 640*640, but in log the best is about 0.591 at 299/300 epochs.  Is there any more details that I miss?

**Comment by Ben-Louis** [comment]
There was a bug in CocoMetric that made it unable to correctly evaluate the YOLO-Pose models. After fixing this problem, the correct results are reported in the readme

**Comment by TengfeiHou** [comment]
> There was a bug in CocoMetric that made it unable to correctly evaluate the YOLO-Pose models. After fixing this problem, the correct results are reported in the readme

so how to make it right?  

what about "--dump the pickle file"  and transform it to coco evaluation form by my own  and test it by xcocotools? can this  work?

and could you explain it about the  detail why CocoMetric unable to correctly evaluate the YOLO-Pose models? 

Thanks a lot

**Comment by Ben-Louis** [comment]
The old CocoMetric did not employ the bbox scores predicted by YOLO-Pose to sort the predictions. This bug has been fixed.
