### ISSUE TITLE
python .\demo\webcam_api_demo.py --cpu    [Bug] 程序按q退出程序一直没关闭，ctrl c也关不了

### ISSUE THREAD

**Issue by lonngxiang** [open-mmlab/mmpose#2484]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

windows11

[('sys.platform', 'win32'), ('Python', '3.10.0 | packaged by conda-forge | (default, Nov 10 2021, 13:20:59) [MSC v.1916 64 bit (AMD64)]'), ('CUDA available', False), ('numpy_random_seed', 2147483648), ('MSVC', '用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.36.32534 版'), ('GCC', 'n/a'), ('PyTorch', '2.0.1+cpu'), ('PyTorch compiling details', 'PyTorch built with:\n  - C++ Version: 199711\n  - MSVC 193431937\n  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)\n  - OpenMP 2019\n  - LAPACK is enabled (usually provided by MKL)\n  - CPU capability usage: AVX2\n  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj /FS -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=OFF, TORCH_VERSION=2.0.1, USE_CUDA=0, USE_CUDNN=OFF, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF, \n'), ('TorchVision', '0.15.2+cpu'), ('OpenCV', '4.7.0'), ('MMEngine', '0.7.3'), ('MMPose', '1.0.0+')])

### Reproduces the problem - code sample

python .\demo\webcam_api_demo.py --cpu 

### Reproduces the problem - command or script

python .\demo\webcam_api_demo.py --cpu 

### Reproduces the problem - error message

程序按q退出程序一直没关闭，ctrl c也关不了

**Comment by lonngxiang** [comment]
问题有点多呀，测试其他案例也有新报错

**Comment by Ben-Louis** [comment]
感谢您的反馈！
1. webcam_api_demo.py 在后续版本中将不再维护，请使用其他推理脚本（例如 demo/topdown_demo_with_mmdet.py, demo/inferencer_demo.py）进行摄像头推理。
2. TypeError 这个问题，请确定一下 demo 脚本的版本和安装的 mmpose 版本一致。如果您安装了 dev-1.x 分支最新版本的 mmpose, 但是使用了旧版本的 demo 脚本，就会出现这个问题

**Comment by lonngxiang** [comment]
> 感谢您的反馈！
> 
> 1. webcam_api_demo.py 卡住的原因可能是使用 CPU 跑模型。请尝试用 GPU 进行模型推理。另外，这个 demo 脚本在后续版本中将不再维护，请使用其他推理脚本（例如 demo/topdown_demo_with_mmdet.py, demo/inferencer_demo.py）进行摄像头推理。
> 2. TypeError 这个问题，请确定一下 demo 脚本的版本和安装的 mmpose 版本一致。如果您安装了 dev-1.x 分支最新版本的 mmpose, 但是使用了旧版本的 demo 脚本，就会出现这个问题

安装的是main分支，各版本情况
mmcv                   2.0.0
mmdet                  3.0.0
mmengine               0.7.3
mmpose                 1.0.0

**Comment by Ben-Louis** [comment]
main 分支中 `MMPoseInferencer.__init__` 方法是有 `output_heatmaps` 这个参数的，照理说不会报 `got an unexpected keyword argument` 这个 TypeError. 
https://github.com/open-mmlab/mmpose/blob/2c4a60e357c7f68f3388f0fc4ddcb404674b81ae/mmpose/apis/inferencers/mmpose_inferencer.py#L72-L80

您可以看一下本地代码文件中这个片段是不是和上述一致吗

**Comment by lonngxiang** [comment]
> 

确实安装包里没有，显示的版本1.0.0  __version__ = '1.0.0'
![image](https://github.com/open-mmlab/mmpose/assets/40717349/1d63b826-c871-48ab-866b-b8c233adeb54)
