### ISSUE TITLE
[Bug] the training demo in MMPose_Tutorial.ipynb gets stuck (using CPU)

### ISSUE THREAD

**Issue by just-maxime** [open-mmlab/mmpose#2488]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

python-3.9
opencv-4.7.0.72
pytorch-cpu-1.7.1，torchvision-cpu-0.8.2
mmengine – 0.7.4，mmcv – 2.0.0，mmdet – 3.0.0，mmpose – 1.0.0

### Reproduces the problem - code sample

[config.txt](https://github.com/open-mmlab/mmpose/files/11876818/config.txt)
[train.txt](https://github.com/open-mmlab/mmpose/files/11876819/train.txt)

I use the code in demo to set the config file and train the model, but gets stuck when only using CPU to train. 

### Reproduces the problem - command or script

use spyder to run the train.py

### Reproduces the problem - error message

06/27 09:30:19 - mmengine - WARNING - "FileClient" will be deprecated in future. Please use io functions in https://mmengine.readthedocs.io/en/latest/api/fileio.html#file-io
06/27 09:30:19 - mmengine - WARNING - "HardDiskBackend" is the alias of "LocalBackend" and the former will be deprecated in future.
06/27 09:30:19 - mmengine - INFO - Checkpoints will be saved to C:\New_folder\5_mmpose\RGBdataset_for_test\work_dirs\hrnet_w32_coco_tiny_256x192.

**Comment by Ben-Louis** [comment]
Hi, thanks for using MMPose. Training pose estimation networks using a CPU may be too slow. We recommend using a GPU for training.

**Comment by just-maxime** [comment]
> 

Thank you for replying to me. But the CUP usage is very low (about 1%) when training, I wonder if the code is running

**Comment by Ben-Louis** [comment]
What about memory usage? The program may get stuck when the memory usage reaches its maximum capacity

**Comment by just-maxime** [comment]
> 

The memory usage is about 43% (1000MB), meanwhile the CPU usage is about 1%.

**Comment by Ben-Louis** [comment]
I suggest considering training models on a device equipped with a GPU and a larger amount of RAM, preferably exceeding 20GB.

**Comment by just-maxime** [comment]
> I suggest considering training models on a device equipped with a GPU and a larger amount of RAM, preferably exceeding 20GB.

Hi, I solved this problem after rewrite the config file. I test it on both win 11 with GPU and win 10 without GPU, they work. Thank you for answer my question.
