### ISSUE TITLE
[Feature] Rtmpose Visualization Demo

### ISSUE THREAD

**Issue by wukurua** [open-mmlab/mmpose#2490]
### What is the feature?

Could provide the code for implementing visualization demo in readme files of rtmpose project？That is a simcc-based visualization demo.

**Comment by Tau-J** [comment]
Thanks for using MMPose. The visualization of RTMPose is following Simcc's. You can refer to [this file](https://github.com/open-mmlab/mmpose/blob/main/mmpose/visualization/simcc_vis.py) for details.
