### ISSUE TITLE
How to disable some of the nodes(key points)?

### ISSUE THREAD

**Issue by HandsomeFYM** [open-mmlab/mmpose#2491]
### 📚 The doc issue

In your code, if I want to disable some nodes or add a new node in the pose estimation using a webcam, which script should I focus on? And how do I modify the script?

Thank you very much.

**Comment by LareinaM** [comment]
Hi, thanks for using MMPose. If you mean changing the keypoints used for pose estimation, you may modify the dataset. Please read through our [doc](https://mmpose.readthedocs.io/en/latest/advanced_guides/customize_datasets.html) for more information.

**Comment by HandsomeFYM** [comment]
Thanks for your reply.

It's not such complicated, I just want to disable some of the keypoints. 
For example, I only want to view the keypoints on the head, so how to make the keypoints on the body disappear(unviewable) in my webcam?
I don't think I need to re-train a model for the above request, right?

**Comment by LareinaM** [comment]
> Thanks for your reply.
> 
> It's not such complicated, I just want to disable some of the keypoints. For example, I only want to view the keypoints on the head, so how to make the keypoints on the body disappear(unviewable) in my webcam? I don't think I need to re-train a model for the above request, right?

Could you provide which script you are running? If you are trying one of our demos, visualization is controlled by our [visualizers](https://mmpose.readthedocs.io/en/latest/api.html#module-mmpose.visualization).

**Comment by HandsomeFYM** [comment]
Never mind, I found I can achieve my goal in the script [https://github.com/open-mmlab/mmpose/blob/main/mmpose/apis/webcam/nodes/visualizer_nodes/object_visualizer_node.py](url)

I will close this issue and thanks for your reply very much.

BTW, in that script, I notice there is a line of "kpt_thr (float): The threshold of keypoint score. Default: 0.3".
What is this threshold mean? I  didn't find the implementation of this threshold.
