### ISSUE TITLE
[Bug] Pretrained model 

### ISSUE THREAD

**Issue by LjIA26** [open-mmlab/mmpose#2521]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

Hello,

I would like to use my own pretrained weights, pretrained previously in the same model in mmpose. It has all of the same information, same architecture and all. 

But It doesn't seem to work. The accuracy starts off from zero, again. I don't think that's normal. 

### Reproduces the problem - code sample

```
        init_cfg=dict(
            type='Pretrained',
            checkpoint='./train-J0506/best_coco_AP_epoch_65.pth'
 
        )),
```

### Reproduces the problem - command or script

```
backbone.stage4.2.branches.3.1.conv2.weight - torch.Size([256, 256, 3, 3]): 
The value is the same before and after calling `init_weights` of TopdownPoseEstimator  

backbone.stage4.2.branches.3.1.bn2.weight - torch.Size([256]): 
The value is the same before and after calling `init_weights` of TopdownPoseEstimator  

backbone.stage4.2.branches.3.1.bn2.bias - torch.Size([256]): 
The value is the same before and after calling `init_weights` of TopdownPoseEstimator  

backbone.stage4.2.branches.3.2.conv1.weight - torch.Size([256, 256, 3, 3]): 
The value is the same before and after calling `init_weights` of TopdownPoseEstimator  

backbone.stage4.2.branches.3.2.bn1.weight - torch.Size([256]): 
The value is the same before and after calling `init_weights` of TopdownPoseEstimator  

```

### Reproduces the problem - error message

No error message, just a message.

**Comment by Ben-Louis** [comment]
You can use load_from=checkpoint_path at the top level of config instead of setting init_cfg. If it still does not work, you can attach the complete config and thus we can help find the problem

**Comment by LjIA26** [comment]
it worked!
