### ISSUE TITLE
[Docs] How can I deploy mmpose on Torchserve

### ISSUE THREAD

**Issue by SunWeimiao** [open-mmlab/mmpose#2523]
### 📚 The doc issue

mmaction                0.5.0
mmcv                    2.0.0
mmdeploy                1.2.0
mmdeploy-runtime        1.2.0
mmdet                   3.0.0
mmengine                0.8.1
mmpose                  1.0.0
mmpretrain              1.0.0
smmap                   5.0.0
torch                   2.0.1
torch-model-archiver    0.8.1
torchaudio              2.0.2
torchserve              0.8.1
torchvision             0.15.2

### Suggest a potential alternative/fix

I noticed `tools/torchserve/mmpose2torchserve.py` in mmpose but it seems unusable.
Can anyone tell me how to deploy mmpose on torchserve?

**Comment by Tau-J** [comment]
Thanks for your feedback. We will have a test on it.
