### ISSUE TITLE
Training failure due to changing the number of keypoints.

### ISSUE THREAD

**Issue by blackCmd** [open-mmlab/mmpose#2527]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

I have created a custom pose dataset related to cars in COCO format, but I am failing to train the dataset. (The dataset was successful in YOLOv5, v7, and v8 pose training.)

The number of keypoints in my dataset is 22, but I couldn't find any document explaining how to train the dataset by changing the number of keypoints.

**Comment by Tau-J** [comment]
Thanks for using MMPose. You can custmize the dataset by following [this doc](https://mmpose.readthedocs.io/en/dev-1.x/advanced_guides/customize_datasets.html#create-a-custom-dataset-class), then change the num of kpt in config.

Takeing topdown-heatmap method on COCO as example ([this config](https://github.com/open-mmlab/mmpose/blob/main/configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_hrnet-w32_8xb64-210e_coco-256x192.py)). The model is defined as follows:
![image](https://github.com/open-mmlab/mmpose/assets/13503330/a784a5ca-57e2-4d51-8ff4-b5a3a170f159)

You can specify the num of kpt by modifying `out_channels` to `20`.

**Comment by blackCmd** [comment]
@Tau-J Oh, I really appreciate it! 
I'll try it!
