### ISSUE TITLE
About training my own data from your pretrained model

### ISSUE THREAD

**Issue by Kazusaisjustice** [open-mmlab/mmpose#2533]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

Hello, I want to train my own data from your pretrained model(configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/animalpose/res152_animalpose_256x256.py). I modified the path of data in this config file and use the command as following,
python tools/train.py configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/animalpose/res152_animalpose_dog_256x256.py --load-from https://download.openmmlab.com/mmpose/animal/resnet/res152_animalpose_256x256-a0a7506c_20210426.pth
But I found load-from is an unrecognized argument, I hope to know the reason.

In addition, I changed load-from to resume-from and received this error,
![image](https://github.com/open-mmlab/mmpose/assets/108652440/21c05323-5e2e-4a81-b915-c1c4af95c170)

And my version is 0.29.0. Waiting for your reply, thanks!

### Reproduces the problem - code sample

None

### Reproduces the problem - command or script

configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/animalpose/res152_animalpose_dog_256x256.py --load-from https://download.openmmlab.com/mmpose/animal/resnet/res152_animalpose_256x256-a0a7506c_20210426.pth

configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/animalpose/res152_animalpose_dog_256x256.py --resume-from https://download.openmmlab.com/mmpose/animal/resnet/res152_animalpose_256x256-a0a7506c_20210426.pth

### Reproduces the problem - error message

![image](https://github.com/open-mmlab/mmpose/assets/108652440/058e401e-b32c-482c-a06a-860ceb2783a6)

![image](https://github.com/open-mmlab/mmpose/assets/108652440/72a7c810-a0a4-4bc0-9c34-ecc6debcf8a3)

**Comment by Tau-J** [comment]
Thanks for using MMPose. Please refer to [the doc](https://mmpose.readthedocs.io/en/0.x/tutorials/1_finetune.html) to fine-tune your model. In addition, I suggest trying mmpose v1.1.0 as the 0.x is deprecated.

**Comment by Kazusaisjustice** [comment]
Well, I got it, thank you!
