### ISSUE TITLE
Is it available to deploy a custom model using mmdeploy

### ISSUE THREAD

**Issue by kdavidlp123** [open-mmlab/mmpose#2536]
### 📚 The doc issue

Hi, 
Recently I have already trained a custom model(with custom dataset) and I want to increase the fps by using webcam for my real-time project. I have read the previous issues about increasing fps and noticed that you recommended user to deploy the model and use pose_tracker. 
So I got some questions to ask, 
1. Which document should I modify?
2. When should the modification be done, before deploy or after?

Thank you

### Suggest a potential alternative/fix

None

**Comment by Tau-J** [comment]
I suggest raising an issue to mmdeploy.
