### ISSUE TITLE
[Question] How to preprocess images when using RTMPose Face models?

### ISSUE THREAD

**Issue by deep-practice** [open-mmlab/mmpose#2538]
### 📚 The doc issue

How to preprocess images when using RTMPose Face models?When I simply crop the face region as the input,the result is not so good.

**Comment by Tau-J** [comment]
Thanks for using MMPose. We will multiply the length and width of the face bbox by 1.25 for expansion, and use the expanded bbox for cropping as the input to the model.

**Comment by deep-practice** [comment]
Got it
