### ISSUE TITLE
How to set visualizer to use opencv instead of matplotlib?

### ISSUE THREAD

**Issue by hellosungha** [open-mmlab/mmpose#2540]
### 📚 The doc issue

I'm using topdown_demo_with_mmdet.py and want to use Opencv as visualizer instead of matplotlib.
But it seems code passes mmpose/visualization/opencv_backend_visualizer.py so only mmengine/visualizer.py works.
I want to use some kind of "draw_circles" and "draw_lines" working with opencv in opencv_backend_visualizer.py. 
What should I fix to do this?

**Comment by Ben-Louis** [comment]
Hi, thanks for using MMPose. In the latest version, the visualizer will use opencv as backend by default. You can update mmpose to the latest version to use this feature

**Comment by hellosungha** [comment]
I found the problem, Thanks for your support
