### ISSUE TITLE
rtmpose improvement ideas

### ISSUE THREAD

**Issue by songjiahao-wq** [open-mmlab/mmpose#2547]
### What is the feature?

CSPNext backbone network is used in rtmpose. Can we learn from ELAN's idea of gradient flow transmission to improve it, just like YOLOv7 and YOLOv8, to achieve higher speed and accuracy

**Comment by Tau-J** [comment]
Hi @songjiahao-wq , thanks for your suggestion. RTMPose can easily build with any backbone you want, and I believe there can always be stronger backbones we can use. If you find more powerful & efficient network, please feel free to give us a PR. We will train it on large datasets.

**Comment by songjiahao-wq** [comment]
> Hi @songjiahao-wq , thanks for your suggestion. RTMPose can easily build with any backbone you want, and I believe there can always be stronger backbones we can use. If you find more powerful & efficient network, please feel free to give us a PR. We will train it on large datasets.

I just started learning MMCV and am not very familiar with it, but I will try to modify it
