### ISSUE TITLE
Get all available detection model 

### ISSUE THREAD

**Issue by steward1212** [open-mmlab/mmpose#2551]
### 📚 The doc issue

Hi, is there any chance to list all available detection model? It is very clear in MMPose document that which pose model is used in https://mmpose.readthedocs.io/en/latest/model_zoo/hand_2d_keypoint.html but it doesn't show which detection model we can use. Thanks

**Comment by Ben-Louis** [comment]
Hello there, thank you for choosing MMPose. We have a page available at https://github.com/open-mmlab/mmpose/blob/main/demo/docs/en/mmdet_modelzoo.md that lists detection models for different specific tasks. If your task involves objects in the COCO dataset, you can use any detection models from the [MMDetection Model Zoo](https://mmdetection.readthedocs.io/en/latest/model_zoo.html) directly.
