### ISSUE TITLE
how to use ViTPose+ in MMPose？

### ISSUE THREAD

**Issue by wanghlsara** [open-mmlab/mmpose#2552]
### What is the feature?

It seems that MMPose doesn't support ViTPose+ now.
So, for mmdeploy users, It difficult to convert a pretained pth wholebody model to onnx/tensorrt, and then infer with mmdeploy SDK .Who can give me some advice on the usage of ViTPose+ in MMPose or MMdeploy?

**Comment by LareinaM** [comment]
Hi, thanks for using MMPose. The official implementation of ViTPose+ is based on MMPose 0.x. If you wish to use it on MMPose 1.x, you may need to migrate detectors and models. For more details on migration, you can refer to our [doc](https://mmpose.readthedocs.io/en/latest/migration.html).

**Comment by BiomechatronicsRookie** [comment]
HI I have tried to use the ViTPose-s network on MMPose 1.0.0, however I get the following error:

KeyError: "class `TopdownPoseEstimator` in mmpose/models/pose_estimators/topdown.py: 'mmcls.VisionTransformer is not in the model registry. Please check whether the value of `mmcls.VisionTransformer` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'"

Trying to solve this I arrived to this issue, however I am not sure what to do with the information provided in the migration document. Can someone give me a hint? 

**Any extrea information**
I am simply using the _inferer_ class provided with the argument  _'vitpose-s'_ supposedly the correct alias for the network.

Thank you in advance!

**Comment by Nour-Aldein2** [comment]
> Hi, thanks for using MMPose. The official implementation of ViTPose+ is based on MMPose 0.x. If you wish to use it on MMPose 1.x, you may need to migrate detectors and models. For more details on migration, you can refer to our [doc](https://mmpose.readthedocs.io/en/latest/migration.html).

The issue is still there until today.
