### ISSUE TITLE
[Feature] How to directly obtain key point coordinates.

### ISSUE THREAD

**Issue by Rx2633** [open-mmlab/mmpose#2556]
### What is the feature?

How to directly obtain key point coordinates.
Not to use "pred out_dir” to get a JSON file.

Thank you very much for your help.

**Comment by Tau-J** [comment]
Thanks for using MMPose. You can refer to our [inferencer doc](https://mmpose.readthedocs.io/en/dev-1.x/user_guides/inference.html).
