### ISSUE TITLE
[Feature] pose 2D to 3D more than 17 keypoints (24?)

### ISSUE THREAD

**Issue by srn-source** [open-mmlab/mmpose#2560]
### What is the feature?

Your work is great!! but i am new in Pose estimation 3D... many people trend to use 2D to 3D pose with human3.6 dataset there is on ly 17 keypoints but if i want more than 17 such as 24 skeleton in SMLP dataset not mash only keypoint SMPL what should i have to do? can i use data keypoint from smpl 24 points and finetuning? or mmpose already support 24 keypoint? i try to find in readme but i see nothing related to more than 17 keypoints

**Comment by Ben-Louis** [comment]
Hi, thanks for using MMPose. Currently, we don't have a 3D pose estimator that can predict 24 keypoints. However, you can train your own model to achieve this. To begin, you'll need to create a new dataset class that can load your SMPL dataset by following the instructions in [this document](https://mmpose.readthedocs.io/en/latest/user_guides/prepare_datasets.html). After that, you can customize a pose lifting model in the configuration settings. Take a look at the existing configurations on [this page](https://github.com/open-mmlab/mmpose/tree/main/configs/body_3d_keypoint/pose_lift/h36m) and adjust the number of keypoints as needed.
