### ISSUE TITLE
May I have an example about how to deploy the model on mobile phone?

### ISSUE THREAD

**Issue by kdavidlp123** [open-mmlab/mmpose#2569]
### 📚 The doc issue

As you mentioned in [here](https://github.com/Tau-J/mmpose/tree/tau/rtm/projects/rtmpose), the inference of rtmpose can be tested by Snapdragon 865 chip. And I would to ask that does the model run like an app on mobile phone's chip for the inference? Because I have converted the model to ncnn and I am eager to test it on smart phone. May I have an quick example ?

### Suggest a potential alternative/fix

None

**Comment by Tau-J** [comment]
Thanks for using MMPose. Principally, we only provide documentation on converting models to the ncnn format, as deploying and using ncnn models on mobile devices falls outside the scope of the mmpose repository. We assume that users are knowledgeable about these processes. I suggest referring to the documentation of mmdeploy or ncnn to learn how to perform speed testing on your smart phone.

**Comment by kdavidlp123** [comment]
OK, thank you!!!
