### ISSUE TITLE
version 0.x  topdown_heatmap hrnet model result is different version 1.x !!!!!!!!

### ISSUE THREAD

**Issue by Dian-Yi** [open-mmlab/mmpose#2587]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

mmpose 0.x
mmpose 1.x

### Reproduces the problem - code sample

problems: I test the same weights using different version, but get results is different. if test video, the error of result of v0.x and v1.x may be >10.pixel.  

Test mode: **HRNet-w48+Dark+**
In version 0.x:
[hrnet_w48_coco_wholebody_384x288_dark_plus.py](https://github.com/open-mmlab/mmpose/blob/0.x/configs/wholebody/2d_kpt_sview_rgb_img/topdown_heatmap/coco-wholebody/hrnet_w48_coco_wholebody_384x288_dark_plus.py)
using reference test script: [top_down_img_demo.py](https://github.com/open-mmlab/mmpose/blob/0.x/demo/top_down_img_demo.py) .i change it can be able to inference one image. The key function is `inference_top_down_pose_model `and `init_pose_model `for mode predicting image.

In version 1.x:
[td-hm_hrnet-w48_dark-8xb32-210e_coco-wholebody-384x288.py](https://github.com/open-mmlab/mmpose/blob/1.x/configs/wholebody_2d_keypoint/topdown_heatmap/coco-wholebody/td-hm_hrnet-w48_dark-8xb32-210e_coco-wholebody-384x288.py)
using script: [image_demo.py](https://github.com/open-mmlab/mmpose/blob/1.x/demo/image_demo.py). The key function is `inference_topdown`and `init_model`for mode predicting image.

they using same weight: [hrnet_w48_coco_wholebody_384x288_dark-f5726563_20200918.pth](https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_coco_wholebody_384x288_dark-f5726563_20200918.pth)

test image: [human-pose.jpg](https://github.com/open-mmlab/mmdeploy/blob/main/demo/resources/human-pose.jpg)
the error in first 23 kpts, max error is greater than 0.001 :

```
[[-0.00050616 -0.00053427], 
[-0.00046116 -0.00088068], 
[-0.00088266 -0.00050416],
 [-0.00013053  0.00064203],
 [-0.0001184  -0.00096056], 
[ 0.0003685   0.00056959], 
[ 0.00026796 -0.00123682],
 [-0.00330903 -0.0051923 ], 
[-0.00049023 -0.00146822],
 [ 0.00657733  0.00569618],
 [ 0.00035305 -0.0008228 ],
 [ 0.00073896 -0.00136121], 
[ 0.00088561 -0.00161781],
 [ 0.0006241   0.00029776],
 [-0.00102663  0.0011887 ],
 [-0.00323097 -0.00249183],
 [-0.0001573  -0.00091338], 
[-0.00226096 -0.00092038], 
[-0.00145191 -0.00143007],
 [-0.00347451 -0.0035733 ],
 [-0.00061263  0.00220291], 
[ 0.00016074  0.00195758],
 [ 0.00177862  0.00059239]]
```

### Reproduces the problem - command or script

None

### Reproduces the problem - error message

None

**Comment by Tau-J** [comment]
Thanks for using MMPose. In `mmpose 1.x`, you need to use [topdown_demo_with_mmdet.py](https://github.com/open-mmlab/mmpose/blob/main/demo/topdown_demo_with_mmdet.py) instead of `image_demo.py`. In addition, according to our test , the prediction results of these two versions are not perfectly the same, but there exists slight differences (less than 0.1 AP).

**Comment by Dian-Yi** [comment]
thanks for your response, i guess `mmpose 1.x` change some preprocess or postprocess function lead to this problems.
