### ISSUE TITLE
one question:Using heat maps for human pose estimation, why are some poses recognized outside the picture?

### ISSUE THREAD

**Issue by balala8** [open-mmlab/mmpose#2604]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

none

### Reproduces the problem - code sample

none

### Reproduces the problem - command or script

none

### Reproduces the problem - error message

none

### Additional information

There is only one person in the picture, the upper body on bbox by the label, the lower body is not in the callout frame, and it is occluded, why can it also be recognized? Doesn't a heatmap identify only the part of the bbox?
![image](https://github.com/open-mmlab/mmpose/assets/37032100/8b77d201-15b8-4a6a-9ad4-10692c4472d1)

**Comment by Ben-Louis** [comment]
By default, the bounding boxes will be expanded with a ratio of 1.25 before cropping. As a result, some of the detected keypoints may be located outside of the bounding boxes.
