### ISSUE TITLE
About evaluation or testing during training

### ISSUE THREAD

**Issue by kdavidlp123** [open-mmlab/mmpose#2607]
### 📚 The doc issue

Hi, may I ask about how to modify the testing or evaluation type during topdown heatmap training.
If I want the testing loss like the training loss below.(Instead of coco_metrics, I want to get loss_kpt)
```08/09 14:37:15 - mmengine - [4m[97mINFO[0m - Epoch(train)   [1][100/138]  lr: 9.959920e-05  eta: 3:43:24  time: 0.621880  data_time: 0.450119  memory: 5867  loss: 0.001288  loss_kpt: 0.001288  acc_pose: 0.944323```
Is it possible to do this? If so, could you please point me which doc should I modify.

### Suggest a potential alternative/fix

None

**Comment by Ben-Louis** [comment]
Losses can be found in https://github.com/open-mmlab/mmpose/tree/main/mmpose/models/losses. It may be necessary to refer to your configuration file to confirm which loss is being utilized.

**Comment by kdavidlp123** [comment]
Okay, I will study on it. Thank you for your quick reply!!!
