### ISSUE TITLE
SimCC applied to YOLOX-Pose

### ISSUE THREAD

**Issue by Egrt** [open-mmlab/mmpose#2610]
### What is the feature?

The latest key point detection model adopts SimCC's loss function. How to modify YOLOX-Pose detection header and decoding to adapt to better performance SimCC loss？

**Comment by Ben-Louis** [comment]
We are currently working on combining SimCC and YOLOX-Pose, and plan to release the new model in the next version. Your patience and attention will be appreciated.

**Comment by Egrt** [comment]
> We are currently working on combining SimCC and YOLOX-Pose, and plan to release the new model in the next version. Your patience and attention will be appreciated.

great！！！
Looking forward to your update, and can YOLOv8 Pose also be applied?

**Comment by Ben-Louis** [comment]
Due to license issue, we will not include YOLOv8 in MMPose
