### ISSUE TITLE
OOM while change train_pipeline_stage

### ISSUE THREAD

**Issue by TengfeiHou** [open-mmlab/mmpose#2613]
### What is the feature?

Thanks for your great work

I find the memory increasing while training,   and it seems to caused by changing the train_pipeline_stage at sencond training schedule. Is there any solution to solve it?  for example , how to clean the memory of the first stage?

**Comment by Ben-Louis** [comment]
May I know the model you are currently using?

**Comment by TengfeiHou** [comment]
> May I know the model you are currently using?

YOLOX-pose

**Comment by Ben-Louis** [comment]
When training data goes through transformations, it doesn't actually use up GPU memory. However, during the second stage, the model will optimize an additional bbox loss, which adds to the memory consumption compared to the first stage. To prevent running out of memory (OOM), you might want to consider using relatively smaller batch sizes.

**Comment by TengfeiHou** [comment]
> When training data goes through transformations, it doesn't actually use up GPU memory. However, during the second stage, the model will optimize an additional bbox loss, which adds to the memory consumption compared to the first stage. To prevent running out of memory (OOM), you might want to consider using relatively smaller batch sizes.

The CUDA memory is fine, I mean the memory which occupied by dataloader
