### ISSUE TITLE
About log_processor window_size

### ISSUE THREAD

**Issue by kdavidlp123** [open-mmlab/mmpose#2618]
### 📚 The doc issue

Hi!!
May I ask about the window_size of the log_processor?
Because I want it to print just one time after all the batches are done. 
And I knew that the default_hooks and log_processor of the default_runtime.py can handle the window_size but it has to be given a fixed integer and cannot change under different length of data. 
I would like to ask which doc can handle this problem.

### Suggest a potential alternative/fix

None

**Comment by Ben-Louis** [comment]
You could try to set `window_size='epoch'`
