### ISSUE TITLE
Keypoints overlap 

### ISSUE THREAD

**Issue by LjIA26** [open-mmlab/mmpose#2621]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

I have noticed that a few of the keypoints overlap when that part of the skeleton is out of the picture during inference. Say keypoints 5 to 7 are out of the picture. They all get exactly the same coordinates as keypoints 4. Down to the 4 decimals. This issue only happens when the keypoint is outside of the image and when the keypoint coinfidence is super high. 

What is causing this bug?

### Reproduces the problem - code sample

When using the inferencer 

### Reproduces the problem - command or script

Not an error

### Reproduces the problem - error message

Not an error

**Comment by Ben-Louis** [comment]
Perhaps you can provide more information about the model and input you are using when you encounter this problem.

**Comment by LjIA26** [comment]
Certainly

'''
model = dict(
    type='TopdownPoseEstimator',
    data_preprocessor=dict(
        type='PoseDataPreprocessor',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        bgr_to_rgb=True),
    backbone=dict(
        type='HRNet',
        in_channels=3,
        extra=dict(
            stage1=dict(
                num_modules=2,
                num_branches=1,
                block='BOTTLENECK',
                num_blocks=(4, ),
                num_channels=(64, )),
            stage2=dict(
                num_modules=2,
                num_branches=2,
                block='BASIC',
                num_blocks=(4, 4),
                num_channels=(32, 64)),
            stage3=dict(
                num_modules=5,
                num_branches=3,
                block='BASIC',
                num_blocks=(4, 4, 4),
                num_channels=(32, 64, 128)),
            stage4=dict(
                num_modules=3,
                num_branches=4,
                block='BASIC',
                num_blocks=(4, 4, 4, 4),
                num_channels=(32, 64, 128, 256))),
        init_cfg=dict(
            type='Pretrained',
            checkpoint=
            'https://download.openmmlab.com/mmpose/pretrain_models/hrnet_w32-36af842e.pth'
        )),
    head=dict(
        type='HeatmapHead',
        in_channels=32,
        out_channels=49,
        deconv_out_channels=None,
        loss=dict(type='AdaptiveWingLoss', use_target_weight=True),
        decoder=dict(
            type='MSRAHeatmap',
            input_size=(256, 256),
            heatmap_size=(64, 64),
            sigma=3)),
    test_cfg=dict(
        flip_test=False,
        shift_heatmap=False,
        use_gt_bbox=True,
        output_heatmaps=True))
''''

**Comment by LjIA26** [comment]
Yes, I have verified that the annotations are correct.

**Comment by LjIA26** [comment]
Considering that the predictions have exactly the same coordinates, I think this is an issue in the code.
