### ISSUE TITLE
How should I test the coco test-dev task

### ISSUE THREAD

**Issue by da13132** [open-mmlab/mmpose#2628]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

mmcv                2.0.0
mmdet               3.0.0        /home/keli/下载/pose/mmdetection-3.0.0
mmengine            0.8.2
mmpose              1.0.0        /home/keli/下载/pose
mmpretrain          1.0.0rc8     /home/keli/下载/pose/mmpretrain
mmyolo              0.6.0        /home/keli/下载/pose/mmyolo
timm                0.4.9

### Reproduces the problem - code sample

_base_ = ['../../../_base_/default_runtime.py']

# runtime
train_cfg = dict(max_epochs=210, val_interval=10)

# optimizer
optim_wrapper = dict(optimizer=dict(
    type='Adam',
    lr=5e-4,
))

# learning policy
param_scheduler = [
    dict(
        type='LinearLR', begin=0, end=500, start_factor=0.001,
        by_epoch=False),  # warm-up
    dict(
        type='MultiStepLR',
        begin=0,
        end=210,
        milestones=[170, 200],
        gamma=0.1,
        by_epoch=True)
]

# automatically scaling LR based on the actual training batch size
auto_scale_lr = dict(base_batch_size=512)

# hooks
default_hooks = dict(checkpoint=dict(save_best='coco/AP', rule='greater'))

# codec settings
codec = dict(
    type='MSRAHeatmap', input_size=(192, 256), heatmap_size=(48, 64), sigma=2)

# model settings
model = dict(
    type='TopdownPoseEstimator',
    data_preprocessor=dict(
        type='PoseDataPreprocessor',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        bgr_to_rgb=True),
    backbone=dict(
        type='HRNet',
        in_channels=3,
        extra=dict(
            stage1=dict(
                num_modules=1,
                num_branches=1,
                block='BOTTLENECK',
                num_blocks=(4, ),
                num_channels=(64, )),
            stage2=dict(
                num_modules=1,
                num_branches=2,
                block='BASIC',
                num_blocks=(4, 4),
                num_channels=(32, 64)),
            stage3=dict(
                num_modules=4,
                num_branches=3,
                block='BASIC',
                num_blocks=(4, 4, 4),
                num_channels=(32, 64, 128)),
            stage4=dict(
                num_modules=3,
                num_branches=4,
                block='BASIC',
                num_blocks=(4, 4, 4, 4),
                num_channels=(32, 64, 128, 256))),
        init_cfg=dict(
            type='Pretrained',
            checkpoint='https://download.openmmlab.com/mmpose/'
            'pretrain_models/hrnet_w32-36af842e.pth'),
    ),
    head=dict(
        type='HeatmapHead',
        in_channels=32,
        out_channels=17,
        deconv_out_channels=None,
        loss=dict(type='KeypointMSELoss', use_target_weight=True),
        decoder=codec),
    test_cfg=dict(
        flip_test=True,
        flip_mode='heatmap',
        shift_heatmap=True,
    ))

# base dataset settings
dataset_type = 'CocoDataset'
data_mode = 'topdown'
data_root = 'data/coco/'

# pipelines
train_pipeline = [
    dict(type='LoadImage'),
    dict(type='GetBBoxCenterScale'),
    dict(type='RandomFlip', direction='horizontal'),
    dict(type='RandomHalfBody'),
    dict(type='RandomBBoxTransform'),
    dict(type='TopdownAffine', input_size=codec['input_size']),
    dict(type='GenerateTarget', encoder=codec),
    dict(type='PackPoseInputs')
]
val_pipeline = [
    dict(type='LoadImage'),
    dict(type='GetBBoxCenterScale'),
    dict(type='TopdownAffine', input_size=codec['input_size']),
    dict(type='PackPoseInputs')
]

# data loaders
train_dataloader = dict(
    batch_size=64,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        data_mode=data_mode,
        ann_file='annotations/person_keypoints_train2017.json',
        data_prefix=dict(img='train2017/'),
        pipeline=train_pipeline,
    ))
val_dataloader = dict(
    batch_size=1,
    num_workers=2,
    persistent_workers=True,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False, round_up=False),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        data_mode=data_mode,
        ann_file='annotations/person_keypoints_val2017.json',
        bbox_file='data/coco/person_detection_results/'
        'COCO_val2017_detections_AP_H_56_person.json',
        data_prefix=dict(img='val2017/'),
        test_mode=True,
        pipeline=val_pipeline,
    ))
test_dataloader = dict(
    batch_size=256,
    num_workers=8,
    persistent_workers=True,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False, round_up=False),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        data_mode=data_mode,
        ann_file='annotations/person_keypoints_test-dev-2017.json',
        bbox_file='data/coco/person_detection_results/'
        'COCO_test-dev2017_detections_AP_H_609_person.json',
        data_prefix=dict(img='test2017/'),
        test_mode=True,
        pipeline=val_pipeline,
    ))
# evaluators
val_evaluator = dict(
    type='CocoMetric',
    ann_file=data_root + 'annotations/person_keypoints_val2017.json')
test_evaluator = dict(
    type='CocoMetric',
    ann_file=data_root + 'annotations/person_keypoints_test-dev-2017.json')

### Reproduces the problem - command or script

python tools/test.py configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_hrnet-w48_8xb32-210e_coco-256x192.py pthfile/hrnet-heatmap/td-hm_hrnet-w48_8xb32-210e_coco-256x192-0e67c616_20220913.pth

### Reproduces the problem - error message

Traceback (most recent call last):
  File "/home/keli/anaconda3/envs/mmpose/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 122, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/keli/下载/pose/mmpose/evaluation/metrics/coco_metric.py", line 136, in __init__
    assert 'annotations' in load(ann_file), \
AssertionError: Ground truth annotations are required for evaluation when `format_only` is False.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/keli/下载/pose/tools/test.py", line 129, in <module>
    main()
  File "/home/keli/下载/pose/tools/test.py", line 125, in main
    runner.test()
  File "/home/keli/anaconda3/envs/mmpose/lib/python3.9/site-packages/mmengine/runner/runner.py", line 1774, in test
    self._test_loop = self.build_test_loop(self._test_loop)  # type: ignore
  File "/home/keli/anaconda3/envs/mmpose/lib/python3.9/site-packages/mmengine/runner/runner.py", line 1584, in build_test_loop
    loop = TestLoop(
  File "/home/keli/anaconda3/envs/mmpose/lib/python3.9/site-packages/mmengine/runner/loops.py", line 413, in __init__
    self.evaluator = runner.build_evaluator(evaluator)  # type: ignore
  File "/home/keli/anaconda3/envs/mmpose/lib/python3.9/site-packages/mmengine/runner/runner.py", line 1299, in build_evaluator
    return Evaluator(evaluator)  # type: ignore
  File "/home/keli/anaconda3/envs/mmpose/lib/python3.9/site-packages/mmengine/evaluator/evaluator.py", line 25, in __init__
    self.metrics.append(METRICS.build(metric))
  File "/home/keli/anaconda3/envs/mmpose/lib/python3.9/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/keli/anaconda3/envs/mmpose/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 144, in build_from_cfg
    raise type(e)(
AssertionError: class `CocoMetric` in mmpose/evaluation/metrics/coco_metric.py: Ground truth annotations are required for evaluation when `format_only` is False.

### Additional information

When I tried to perform the AP test of `coco test-dev 2017` in mmpose, I found that the official `tools/test.p`y was running on `coco val2017`. When I tried to modify the corresponding config file, the error was reported as follows: `class `CocoMetric` in mmpose/ evaluation/metrics/coco_metric.py: Ground truth annotations are required for evaluation when `format_only` is False`. How should I test coco `test-dev 2017`? thanks for your help!

**Comment by LareinaM** [comment]
Hi, thanks for using MMPose. File `person_keypoints_test-dev-2017.json` does not contain annotation results and is for testing purposes only. To obtain testing results, please set 
```python
test_evaluator = dict(
    type='CocoMetric',
    ann_file=data_root + 'annotations/person_keypoints_test-dev-2017.json',
    format_only=True,
    outfile_prefix='' # set your path here which includes the file path and the prefix of filename
)
```

**Comment by da13132** [comment]
Thank you for your reply. I hope to get the AP score in test-dev-2017. After following your tips, I got a json file with test data annotations. How can I get the AP score of the COCO test task?

**Comment by da13132** [comment]
> Hi, thanks for using MMPose. File `person_keypoints_test-dev-2017.json` does not contain annotation results and is for testing purposes only. To obtain testing results, please set
> 
> ```python
> test_evaluator = dict(
>     type='CocoMetric',
>     ann_file=data_root + 'annotations/person_keypoints_test-dev-2017.json',
>     format_only=True,
>     outfile_prefix='' # set your path here which includes the file path and the prefix of filename
> )
> ```

Thank you for your reply. I hope to get the AP score in test-dev-2017. After following your tips, I got a json file with test data annotations. How can I get the AP score of the COCO test task?

**Comment by LareinaM** [comment]
> > Hi, thanks for using MMPose. File `person_keypoints_test-dev-2017.json` does not contain annotation results and is for testing purposes only. To obtain testing results, please set
> > ```python
> > test_evaluator = dict(
> >     type='CocoMetric',
> >     ann_file=data_root + 'annotations/person_keypoints_test-dev-2017.json',
> >     format_only=True,
> >     outfile_prefix='' # set your path here which includes the file path and the prefix of filename
> > )
> > ```
> 
> Thank you for your reply. I hope to get the AP score in test-dev-2017. After following your tips, I got a json file with test data annotations. How can I get the AP score of the COCO test task?

To get the AP score you will need the ground truth data, which is not available in test-dev. The evaluation must be performed using the [COCO evaluation server](https://cocodataset.org/#upload).
