### ISSUE TITLE
About modify the POSETRACKER.apply function

### ISSUE THREAD

**Issue by kdavidlp123** [open-mmlab/mmpose#2633]
### 📚 The doc issue

Hi,
May I ask about how to modify the java file of POSETRACKER?
It seems that if I use POSETRACKER.apply, it will return the bbox and keypoints simultaneously. And I cannot find more detail about the apply function.
Because I want to analyze the execution time of object detection model and keypoints detection model respectively.
Is it possible to reach that? If so, could you please tell me which doc I should modify.
Thank you!!!!!!!!!!

### Suggest a potential alternative/fix

None

**Comment by Tau-J** [comment]
Hi @kdavidlp123 , I suggest asking MMDeploy for help. PoseTracker is developed by them.
