### ISSUE TITLE
Can you explain the learning policy?

### ISSUE THREAD

**Issue by felipe-parodi** [open-mmlab/mmpose#2645]
### 📚 The doc issue

I see this learning policy used frequently: 

```
# learning policy
param_scheduler = [
    dict(
        type='LinearLR', begin=0, end=500, start_factor=0.001,
        by_epoch=False),  # warm-up
    dict(
        type='MultiStepLR',
        begin=0,
        end=210,
        milestones=[170, 200],
        gamma=0.1,
        by_epoch=True)
]
```

Can you please explain why LinearLR is used from [0,500] yet the MultiStepLR kicks in at 170? Thanks.

**Comment by Tau-J** [comment]
@felipe-parodi , thanks for using MMPose. [Here](https://mmengine.readthedocs.io/en/latest/tutorials/param_scheduler.html) is the details of LR Scheduler.

**Comment by felipe-parodi** [comment]
Thank you!

**Comment by felipe-parodi** [comment]
Ahh okay now i understand. thank you!
