### ISSUE TITLE
[Docs] The config dev-1.x note linking not found

### ISSUE THREAD

**Issue by chaodyna** [open-mmlab/mmpose#2649]
### 📚 The doc issue

Here is a tiny,  minor bug found.
In the docs in $MMPose/docs/en(zh-CN)/user-guides/config, the linking to MMEngine at the end of docs note is blank
https://github.com/open-mmlab/mmpose/blob/dev-1.x/docs/zh_cn/user_guides/configs.md?plain=1#L501  :-)

**Comment by Tau-J** [comment]
Fixed in https://github.com/open-mmlab/mmpose/pull/2655
