### ISSUE TITLE
Inference with custom dataset and trained model

### ISSUE THREAD

**Issue by PallottaEnrico** [open-mmlab/mmpose#2650]
### 📚 The doc issue

Hi, I've trained a top-down pose model, namely `td-hm_hrnet-w48_8xb32-210e_coco-384x288.py`, for object detection and keypoint detection of a custom object with 4 keypoints. 
Training and testing went smoothly, I got great results according to metrics and the result image saved after launching the script `tools/test.py`.

However, after training, I've only one .pth file saved (for each validation epoch and best epoch) so i don't know how to run inference as, according to the [doc](https://mmpose.readthedocs.io/en/latest/user_guides/inference.html), you must provide both the pose model and the detection model.

If i don't specify the detection model then it downloads a default one trained for human detection, which is not able to detect my object.

How is it possible that the `test script` is able to perform inference while the `inference` one requires this additional model? If the model stored at the end of training is only a keypoint detector, where is the object detector stored?

**Comment by Tau-J** [comment]
Hi @PallottaEnrico , thanks for using MMPose. In fact, there is no detection model trained, because the targets of pose model are generated by groundtruth. When using topdwon algorithm, ou need to train an object detection model by yourself, which is out of the scope of MMPose.

**Comment by grpinto** [comment]
Hey, how did you train your model with a custom dataset, I don't think that the tutorial is very explicit and therefore I am founding quite difficult to set up mine. I want to use COCO dataset, its training, vals and testing. Would you mind explaining me step by step how you did it ?

**Comment by LareinaM** [comment]
> Hey, how did you train your model with a custom dataset, I don't think that the tutorial is very explicit and therefore I am founding quite difficult to set up mine. I want to use COCO dataset, its training, vals and testing. Would you mind explaining me step by step how you did it ?

Hi, MMPose has implemented COCO dataset for you to use, so you do not need to implement it yourself. You can refer to [this config](https://github.com/open-mmlab/mmpose/blob/main/configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_hrnet-w32_8xb64-210e_coco-256x192.py#L119C1) on using the COCO dataset.

**Comment by Renat2001** [comment]
Hi, @PallottaEnrico. How did you train your model on a custom object? Did you use pretrained weights of human pose model as an initial point? It would be nice to see your implementation of the training.

**Comment by PallottaEnrico** [comment]
Sorry @Renat2001 but I barely remember why I was even using this repo 2 years ago 😅
