### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by arymax** [open-mmlab/mmpose#2652]
### 📚 The doc issue

I have searching for this problem two days plz give me some help !

I want using my own dataset to finetune a pretrain model and I have change it to COCO dataset
following is my config
Config:
auto_scale_lr = dict(base_batch_size=64, enable=True)
backend_args = dict(backend='local')
codec = dict(
heatmap_size=(
48,
64,
),
input_size=(
192,
256,
),
sigma=2,
type='UDPHeatmap')
custom_hooks = [
dict(type='SyncBuffersHook'),
]
custom_imports = dict(
allow_failed_imports=False,
imports=[
'mmpose.engine.optim_wrappers.layer_decay_optim_wrapper',
])
data_mode = 'topdown'
data_root = 'data/coco/'
dataset_info = dict(
data_root='/data1/data/vscode-ml/pose detect/確認使用',
dataset_name='pelvictiltDataset',
joint_weights=[
1.5,
1.2,
1.0,
1.0,
1.2,
1.5,
1.3,
],
keypoint_info=dict({
0:
dict(color=[
255,
128,
0,
], id=0, name='head', swap='', type='upper'),
1:
dict(color=[
255,
128,
0,
], id=1, name='ear', swap='', type='upper'),
2:
dict(
color=[
255,
128,
0,
],
id=2,
name='shoulder',
swap='',
type='upper'),
3:
dict(
color=[
0,
255,
0,
], id=3, name='psis', swap='psis', type='lower'),
4:
dict(
color=[
0,
255,
0,
], id=4, name='asis', swap='asis', type='lower'),
5:
dict(color=[
0,
255,
0,
], id=5, name='knee', swap='', type='lower'),
6:
dict(
color=[
0,
0,
255,
],
id=6,
name='midpoint_psis_asis',
swap='',
type='lower')
}),
paper_info=dict(author='max'),
sigmas=[
0.089,
0.087,
0.107,
0.107,
0.087,
0.089,
0.095,
],
skeleton_info=dict({
0:
dict(color=[
255,
128,
0,
], id=0, link=(
'head',
'ear',
)),
1:
dict(color=[
255,
128,
0,
], id=1, link=(
'head',
'shoulder',
)),
2:
dict(color=[
0,
255,
0,
], id=2, link=(
'shoulder',
'psis',
)),
3:
dict(color=[
0,
255,
0,
], id=3, link=(
'psis',
'asis',
)),
4:
dict(color=[
0,
255,
0,
], id=4, link=(
'asis',
'knee',
)),
5:
dict(color=[
0,
0,
255,
], id=5, link=(
'psis',
'midpoint_psis_asis',
)),
6:
dict(color=[
0,
0,
255,
], id=6, link=(
'asis',
'midpoint_psis_asis',
))
}))
dataset_type = 'CocoDataset'
default_hooks = dict(
checkpoint=dict(
interval=10,
max_keep_ckpts=1,
rule='greater',
save_best='coco/AP',
type='CheckpointHook'),
logger=dict(interval=50, type='LoggerHook'),
param_scheduler=dict(type='ParamSchedulerHook'),
sampler_seed=dict(type='DistSamplerSeedHook'),
timer=dict(type='IterTimerHook'),
visualization=dict(enable=False, type='PoseVisualizationHook'))
default_scope = 'mmpose'
env_cfg = dict(
cudnn_benchmark=False,
dist_cfg=dict(backend='nccl'),
mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0))
load_from = None
log_level = 'INFO'
log_processor = dict(
by_epoch=True, num_digits=6, type='LogProcessor', window_size=50)
model = dict(
backbone=dict(
arch='huge',
drop_path_rate=0.55,
frozen_stages=2,
img_size=(
256,
192,
),
init_cfg=dict(
checkpoint=
'https://download.openmmlab.com/mmpose/v1/pretrained_models/mae_pretrain_vit_huge.pth',
prefix='backbone',
type='Pretrained'),
out_type='featmap',
patch_cfg=dict(padding=2),
patch_size=16,
qkv_bias=True,
type='mmpretrain.VisionTransformer',
with_cls_token=False),
data_preprocessor=dict(
bgr_to_rgb=True,
mean=[
123.675,
116.28,
103.53,
],
std=[
58.395,
57.12,
57.375,
],
type='PoseDataPreprocessor'),
head=dict(
decoder=dict(
heatmap_size=(
48,
64,
),
input_size=(
192,
256,
),
sigma=2,
type='UDPHeatmap'),
deconv_kernel_sizes=(
4,
4,
),
deconv_out_channels=(
256,
256,
),
in_channels=1280,
loss=dict(type='KeypointMSELoss', use_target_weight=True),
out_channels=7,
type='HeatmapHead'),
test_cfg=dict(flip_mode='heatmap', flip_test=True, shift_heatmap=False),
type='TopdownPoseEstimator')
optim_wrapper = dict(
clip_grad=dict(max_norm=1.0, norm_type=2),
constructor='LayerDecayOptimWrapperConstructor',
optimizer=dict(
betas=(
0.9,
0.999,
), lr=0.0005, type='AdamW', weight_decay=0.1),
paramwise_cfg=dict(
custom_keys=dict(
bias=dict(decay_multi=0.0),
norm=dict(decay_mult=0.0),
pos_embed=dict(decay_mult=0.0),
relative_position_bias_table=dict(decay_mult=0.0)),
layer_decay_rate=0.85,
num_layers=32))
param_scheduler = [
dict(
begin=0, by_epoch=False, end=500, start_factor=0.001, type='LinearLR'),
dict(
begin=0,
by_epoch=True,
end=210,
gamma=0.1,
milestones=[
170,
200,
],
type='MultiStepLR'),
]
resume = False
test_cfg = dict()
test_dataloader = dict(
batch_size=8,
dataset=dict(
ann_file='/data1/data/vscode-ml/pose detect/test_output.json',
bbox_file='/data1/data/vscode-ml/pose detect/bbox_output.json',
data_mode='topdown',
data_prefix=dict(
img='/data1/data/vscode-ml/pose detect/確認使用/test_images'),
data_root='/data1/data/vscode-ml/pose detect/確認使用',
metainfo=dict(
from_file=
'/data1/data/vscode-ml/pose detect/mmpose/configs/base/datasets/pelvictilt-custom.py'
),
pipeline=[
dict(type='LoadImage'),
dict(type='GetBBoxCenterScale'),
dict(input_size=(
192,
256,
), type='TopdownAffine', use_udp=True),
dict(type='PackPoseInputs'),
],
test_mode=True,
type='CocoDataset'),
drop_last=False,
num_workers=4,
persistent_workers=True,
sampler=dict(round_up=False, shuffle=False, type='DefaultSampler'))
test_evaluator = dict(
ann_file='/data1/data/vscode-ml/pose detect/test_output.json',
type='CocoMetric')
train_cfg = dict(by_epoch=True, max_epochs=210, val_interval=10)
train_dataloader = dict(
batch_size=16,
dataset=dict(
ann_file='/data1/data/vscode-ml/pose detect/train_output.json',
data_mode='topdown',
data_prefix=dict(
img='/data1/data/vscode-ml/pose detect/確認使用/train_images'),
data_root='/data1/data/vscode-ml/pose detect/確認使用/',
metainfo=dict(
from_file=
'/data1/data/vscode-ml/pose detect/mmpose/configs/base/datasets/pelvictilt-custom.py'
),
pipeline=[
dict(type='LoadImage'),
dict(type='GetBBoxCenterScale'),
dict(direction='horizontal', type='RandomFlip'),
dict(type='RandomHalfBody'),
dict(type='RandomBBoxTransform'),
dict(input_size=(
192,
256,
), type='TopdownAffine', use_udp=True),
dict(
encoder=dict(
heatmap_size=(
48,
64,
),
input_size=(
192,
256,
),
sigma=2,
type='UDPHeatmap'),
type='GenerateTarget'),
dict(type='PackPoseInputs'),
],
type='CocoDataset'),
num_workers=4,
persistent_workers=True,
sampler=dict(shuffle=True, type='DefaultSampler'))
train_pipeline = [
dict(type='LoadImage'),
dict(type='GetBBoxCenterScale'),
dict(direction='horizontal', type='RandomFlip'),
dict(type='RandomHalfBody'),
dict(type='RandomBBoxTransform'),
dict(input_size=(
192,
256,
), type='TopdownAffine', use_udp=True),
dict(
encoder=dict(
heatmap_size=(
48,
64,
),
input_size=(
192,
256,
),
sigma=2,
type='UDPHeatmap'),
type='GenerateTarget'),
dict(type='PackPoseInputs'),
]
val_cfg = dict()
val_dataloader = dict(
batch_size=8,
dataset=dict(
ann_file='/data1/data/vscode-ml/pose detect/val_output.json',
bbox_file='/data1/data/vscode-ml/pose detect/bbox_output.json',
data_mode='topdown',
data_prefix=dict(
img='/data1/data/vscode-ml/pose detect/確認使用/val_images'),
data_root='/data1/data/vscode-ml/pose detect/確認使用',
metainfo=dict(
from_file=
'/data1/data/vscode-ml/pose detect/mmpose/configs/base/datasets/pelvictilt-custom.py'
),
pipeline=[
dict(type='LoadImage'),
dict(type='GetBBoxCenterScale'),
dict(input_size=(
192,
256,
), type='TopdownAffine', use_udp=True),
dict(type='PackPoseInputs'),
],
test_mode=True,
type='CocoDataset'),
drop_last=False,
num_workers=4,
persistent_workers=True,
sampler=dict(round_up=False, shuffle=False, type='DefaultSampler'))
val_evaluator = dict(
ann_file='/data1/data/vscode-ml/pose detect/val_output.json',
type='CocoMetric')
val_pipeline = [
dict(type='LoadImage'),
dict(type='GetBBoxCenterScale'),
dict(input_size=(
192,
256,
), type='TopdownAffine', use_udp=True),
dict(type='PackPoseInputs'),
]
vis_backends = [
dict(type='LocalVisBackend'),
]
visualizer = dict(
name='visualizer',
type='PoseLocalVisualizer',
vis_backends=[
dict(type='LocalVisBackend'),
])
am I do anything wrong on this config?

**Comment by Tau-J** [comment]
Hi @arymax , thanks for using MMPose. Please follow the issue template to provide as much information as possible.

**Comment by arymax** [comment]
Sorry!
Following is my metafile:
dataset_info = dict(
    dataset_name='pelvictiltDataset',
    data_root='/data1/data/vscode-ml/pose detect/確認使用',
    paper_info=dict(
        author='max'
    ),
     keypoint_info={
        0: dict(name='head', id=0, color=[255, 128, 0], type='upper', swap=''),
        1: dict(name='ear', id=1, color=[255, 128, 0], type='upper', swap=''),
        2: dict(name='shoulder', id=2, color=[255, 128, 0], type='upper', swap=''),
        3: dict(name='psis', id=3, color=[0, 255, 0], type='lower', swap='psis'),
        4: dict(name='asis', id=4, color=[0, 255, 0], type='lower', swap='asis'),
        5: dict(name='knee', id=5, color=[0, 255, 0], type='lower', swap=''),
        6: dict(name='midpoint_psis_asis', id=6, color=[0, 0, 255], type='lower', swap=''),
    },
    skeleton_info={
        0: dict(link=('head', 'ear'), id=0, color=[255, 128, 0]),
        1: dict(link=('head', 'shoulder'), id=1, color=[255, 128, 0]),
        2: dict(link=('shoulder', 'psis'), id=2, color=[0, 255, 0]),
        3: dict(link=('psis', 'asis'), id=3, color=[0, 255, 0]),
        4: dict(link=('asis', 'knee'), id=4, color=[0, 255, 0]),
        5: dict(link=('psis', 'midpoint_psis_asis'), id=5, color=[0, 0, 255]),
        6: dict(link=('asis', 'midpoint_psis_asis'), id=6, color=[0, 0, 255]),
    },
    joint_weights=[1.5, 1.2, 1.0, 1.0, 1.2, 1.5, 1.3],
    sigmas=[0.089, 0.087, 0.107, 0.107, 0.087, 0.089, 0.095]
)
I think I have use coco dataset.So I dont need to  registe myself dataset right?

**Comment by Tau-J** [comment]
This value error infers that the training img path you set is wrong. The entire path in dataset config is combined as `{data_root}/{data_prefix['img']}`, but you set 

```python
data_prefix=dict(
img='/data1/data/vscode-ml/pose detect/確認使用/train_images'),

data_root='/data1/data/vscode-ml/pose detect/確認使用/',
```

I thnk you can modify as follow:
```python
data_prefix=dict(
img='train_images'),

data_root='/data1/data/vscode-ml/pose detect/確認使用/',
```

**Comment by arymax** [comment]
Very Thanks for your help !
but it seems not work on me
I take your advice and change my config data but it get the same result.
Have any other reason to cause this issue? 
I change following setting:
auto_scale_lr = dict(base_batch_size=64, enable=True)
backend_args = dict(backend='local')
codec = dict(
    heatmap_size=(
        48,
        64,
    ),
    input_size=(
        192,
        256,
    ),
    sigma=2,
    type='UDPHeatmap')
custom_hooks = [
    dict(type='SyncBuffersHook'),
]
custom_imports = dict(
    allow_failed_imports=False,
    imports=[
        'mmpose.engine.optim_wrappers.layer_decay_optim_wrapper',
    ])
data_mode = 'topdown'
data_root = 'data/coco/'
dataset_info = dict(
    data_root='/data1/data/vscode-ml/pose detect/確認使用',
    dataset_name='CocoDataset',
    joint_weights=[
        1.5,
        1.2,
        1.0,
        1.0,
        1.2,
        1.5,
        1.3,
    ],
    keypoint_info=dict({
        0:
        dict(color=[
            255,
            128,
            0,
        ], id=0, name='head', swap='', type='upper'),
        1:
        dict(color=[
            255,
            128,
            0,
        ], id=1, name='ear', swap='', type='upper'),
        2:
        dict(
            color=[
                255,
                128,
                0,
            ],
            id=2,
            name='shoulder',
            swap='',
            type='upper'),
        3:
        dict(
            color=[
                0,
                255,
                0,
            ], id=3, name='psis', swap='psis', type='lower'),
        4:
        dict(
            color=[
                0,
                255,
                0,
            ], id=4, name='asis', swap='asis', type='lower'),
        5:
        dict(color=[
            0,
            255,
            0,
        ], id=5, name='knee', swap='', type='lower'),
        6:
        dict(
            color=[
                0,
                0,
                255,
            ],
            id=6,
            name='midpoint_psis_asis',
            swap='',
            type='lower')
    }),
    paper_info=dict(author='max'),
    sigmas=[
        0.089,
        0.087,
        0.107,
        0.107,
        0.087,
        0.089,
        0.095,
    ],
    skeleton_info=dict({
        0:
        dict(color=[
            255,
            128,
            0,
        ], id=0, link=(
            'head',
            'ear',
        )),
        1:
        dict(color=[
            255,
            128,
            0,
        ], id=1, link=(
            'head',
            'shoulder',
        )),
        2:
        dict(color=[
            0,
            255,
            0,
        ], id=2, link=(
            'shoulder',
            'psis',
        )),
        3:
        dict(color=[
            0,
            255,
            0,
        ], id=3, link=(
            'psis',
            'asis',
        )),
        4:
        dict(color=[
            0,
            255,
            0,
        ], id=4, link=(
            'asis',
            'knee',
        )),
        5:
        dict(color=[
            0,
            0,
            255,
        ], id=5, link=(
            'psis',
            'midpoint_psis_asis',
        )),
        6:
        dict(color=[
            0,
            0,
            255,
        ], id=6, link=(
            'asis',
            'midpoint_psis_asis',
        ))
    }))
dataset_type = 'CocoDataset'
default_hooks = dict(
    checkpoint=dict(
        interval=10,
        max_keep_ckpts=1,
        rule='greater',
        save_best='coco/AP',
        type='CheckpointHook'),
    logger=dict(interval=50, type='LoggerHook'),
    param_scheduler=dict(type='ParamSchedulerHook'),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    timer=dict(type='IterTimerHook'),
    visualization=dict(enable=False, type='PoseVisualizationHook'))
default_scope = 'mmpose'
env_cfg = dict(
    cudnn_benchmark=False,
    dist_cfg=dict(backend='nccl'),
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0))
launcher = 'none'
load_from = None
log_level = 'INFO'
log_processor = dict(
    by_epoch=True, num_digits=6, type='LogProcessor', window_size=50)
model = dict(
    backbone=dict(
        arch='huge',
        drop_path_rate=0.55,
        frozen_stages=2,
        img_size=(
            256,
            192,
        ),
        init_cfg=dict(
            checkpoint=
            'https://download.openmmlab.com/mmpose/v1/pretrained_models/mae_pretrain_vit_huge.pth',
            prefix='backbone',
            type='Pretrained'),
        out_type='featmap',
        patch_cfg=dict(padding=2),
        patch_size=16,
        qkv_bias=True,
        type='mmpretrain.VisionTransformer',
        with_cls_token=False),
    data_preprocessor=dict(
        bgr_to_rgb=True,
        mean=[
            123.675,
            116.28,
            103.53,
        ],
        std=[
            58.395,
            57.12,
            57.375,
        ],
        type='PoseDataPreprocessor'),
    head=dict(
        decoder=dict(
            heatmap_size=(
                48,
                64,
            ),
            input_size=(
                192,
                256,
            ),
            sigma=2,
            type='UDPHeatmap'),
        deconv_kernel_sizes=(
            4,
            4,
        ),
        deconv_out_channels=(
            256,
            256,
        ),
        in_channels=1280,
        loss=dict(type='KeypointMSELoss', use_target_weight=True),
        out_channels=7,
        type='HeatmapHead'),
    test_cfg=dict(flip_mode='heatmap', flip_test=True, shift_heatmap=False),
    type='TopdownPoseEstimator')
optim_wrapper = dict(
    clip_grad=dict(max_norm=1.0, norm_type=2),
    constructor='LayerDecayOptimWrapperConstructor',
    optimizer=dict(
        betas=(
            0.9,
            0.999,
        ), lr=0.0005, type='AdamW', weight_decay=0.1),
    paramwise_cfg=dict(
        custom_keys=dict(
            bias=dict(decay_multi=0.0),
            norm=dict(decay_mult=0.0),
            pos_embed=dict(decay_mult=0.0),
            relative_position_bias_table=dict(decay_mult=0.0)),
        layer_decay_rate=0.85,
        num_layers=32))
param_scheduler = [
    dict(
        begin=0, by_epoch=False, end=500, start_factor=0.001, type='LinearLR'),
    dict(
        begin=0,
        by_epoch=True,
        end=210,
        gamma=0.1,
        milestones=[
            170,
            200,
        ],
        type='MultiStepLR'),
]
resume = False
test_cfg = dict()
test_dataloader = dict(
    batch_size=8,
    dataset=dict(
        ann_file='/data1/data/vscode-ml/pose detect/test_output.json',
        bbox_file='/data1/data/vscode-ml/pose detect/bbox_output.json',
        data_mode='topdown',
        data_prefix=dict(img='test_images/'),
        data_root='/data1/data/vscode-ml/pose detect/確認使用/',
        metainfo=dict(
            from_file=
            '/data1/data/vscode-ml/pose detect/mmpose/configs/_base_/datasets/pelvictilt-custom.py'
        ),
        pipeline=[
            dict(type='LoadImage'),
            dict(type='GetBBoxCenterScale'),
            dict(input_size=(
                192,
                256,
            ), type='TopdownAffine', use_udp=True),
            dict(type='PackPoseInputs'),
        ],
        test_mode=True,
        type='CocoDataset'),
    drop_last=False,
    num_workers=4,
    persistent_workers=True,
    sampler=dict(round_up=False, shuffle=False, type='DefaultSampler'))
test_evaluator = dict(
    ann_file='/data1/data/vscode-ml/pose detect/test_output.json',
    type='CocoMetric')
train_cfg = dict(by_epoch=True, max_epochs=210, val_interval=10)
train_dataloader = dict(
    batch_size=16,
    dataset=dict(
        ann_file='/data1/data/vscode-ml/pose detect/train_output.json',
        data_mode='topdown',
        data_prefix=dict(img='train_images/'),
        data_root='/data1/data/vscode-ml/pose detect/確認使用/',
        metainfo=dict(
            from_file=
            '/data1/data/vscode-ml/pose detect/mmpose/configs/_base_/datasets/pelvictilt-custom.py'
        ),
        pipeline=[
            dict(type='LoadImage'),
            dict(type='GetBBoxCenterScale'),
            dict(direction='horizontal', type='RandomFlip'),
            dict(type='RandomHalfBody'),
            dict(type='RandomBBoxTransform'),
            dict(input_size=(
                192,
                256,
            ), type='TopdownAffine', use_udp=True),
            dict(
                encoder=dict(
                    heatmap_size=(
                        48,
                        64,
                    ),
                    input_size=(
                        192,
                        256,
                    ),
                    sigma=2,
                    type='UDPHeatmap'),
                type='GenerateTarget'),
            dict(type='PackPoseInputs'),
        ],
        type='CocoDataset'),
    num_workers=4,
    persistent_workers=True,
    sampler=dict(shuffle=True, type='DefaultSampler'))
train_pipeline = [
    dict(type='LoadImage'),
    dict(type='GetBBoxCenterScale'),
    dict(direction='horizontal', type='RandomFlip'),
    dict(type='RandomHalfBody'),
    dict(type='RandomBBoxTransform'),
    dict(input_size=(
        192,
        256,
    ), type='TopdownAffine', use_udp=True),
    dict(
        encoder=dict(
            heatmap_size=(
                48,
                64,
            ),
            input_size=(
                192,
                256,
            ),
            sigma=2,
            type='UDPHeatmap'),
        type='GenerateTarget'),
    dict(type='PackPoseInputs'),
]
val_cfg = dict()
val_dataloader = dict(
    batch_size=8,
    dataset=dict(
        ann_file='/data1/data/vscode-ml/pose detect/val_output.json',
        bbox_file='/data1/data/vscode-ml/pose detect/bbox_output.json',
        data_mode='topdown',
        data_prefix=dict(img='val_images/'),
        data_root='/data1/data/vscode-ml/pose detect/確認使用/',
        metainfo=dict(
            from_file=
            '/data1/data/vscode-ml/pose detect/mmpose/configs/_base_/datasets/pelvictilt-custom.py'
        ),
        pipeline=[
            dict(type='LoadImage'),
            dict(type='GetBBoxCenterScale'),
            dict(input_size=(
                192,
                256,
            ), type='TopdownAffine', use_udp=True),
            dict(type='PackPoseInputs'),
        ],
        test_mode=True,
        type='CocoDataset'),
    drop_last=False,
    num_workers=4,
    persistent_workers=True,
    sampler=dict(round_up=False, shuffle=False, type='DefaultSampler'))
val_evaluator = dict(
    ann_file='/data1/data/vscode-ml/pose detect/val_output.json',
    type='CocoMetric')
val_pipeline = [
    dict(type='LoadImage'),
    dict(type='GetBBoxCenterScale'),
    dict(input_size=(
        192,
        256,
    ), type='TopdownAffine', use_udp=True),
    dict(type='PackPoseInputs'),
]
vis_backends = [
    dict(type='LocalVisBackend'),
]
visualizer = dict(
    name='visualizer',
    type='PoseLocalVisualizer',
    vis_backends=[
        dict(type='LocalVisBackend'),
    ])
work_dir = '../checkpoint'

**Comment by arymax** [comment]
I have found what reason cause this issue.This issue happened at my bbox file. "category_id", should be "1" when you build your bboxfile or you will get a empty list and get this issue.

**Comment by XH-B** [comment]
I have found what reason cause this issue. Maybe your 'image_id' is error，this leads to can not find right image path

**Comment by kirillmeisser** [comment]
In my case the following method caused the error:

```python
@staticmethod
    def _is_valid_instance(data_info: Dict) -> bool:
        """Check a data info is an instance with valid bbox and keypoint
        annotations."""
        # crowd annotation
        if 'iscrowd' in data_info and data_info['iscrowd']:
            return False
        # invalid keypoints
        if 'num_keypoints' in data_info and data_info['num_keypoints'] == 0:
            return False
        # invalid bbox
        if 'bbox' in data_info:
            bbox = data_info['bbox'][0]
            w, h = bbox[2:4] - bbox[:2]
            if w <= 0 or h <= 0:
                return False
        # invalid keypoints
        if 'keypoints' in data_info:
            if np.max(data_info['keypoints']) <= 0:
                return False
        return True
```

This method belongs to the ```BaseCocoStyleDataset``` class and it filtered out all the entries in ```data_list``` because my ```iscrowd``` field was a string "0" and resolved to ```True```. Given that my ```data_list``` is an empty list at this point, the concatenation in the ```_serialize_data```method in the ```BaseDataset``` class fails and the error is you see is produced.
