### ISSUE TITLE
[Bug] Colab error: [Errno 2] No such file or directory: '/usr/local/lib/python3.10/dist-packages/setuptools-67.7.2.dist-info/METADATA'

### ISSUE THREAD

**Issue by cjn0116** [open-mmlab/mmpose#2664]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

Package    Version    Source
---------  ---------  -----------------------------------------
mmcv       2.0.1      https://github.com/open-mmlab/mmcv
mmdet      3.1.0      https://github.com/open-mmlab/mmdetection
mmengine   0.8.4      https://github.com/open-mmlab/mmengine
mmpose     1.1.0      https://github.com/open-mmlab/mmpose

### Reproduces the problem - code sample

# import settings of MMPose
from mmpose.apis import inference_topdown
from mmpose.apis import init_model as init_pose_estimator
from mmpose.evaluation.functional import nms
from mmpose.registry import VISUALIZERS
from mmpose.structures import merge_data_samples

### Reproduces the problem - command or script

non

### Reproduces the problem - error message

AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
AttributeError: _pkg_info

During handling of the above exception, another exception occurred:

FileNotFoundError                         Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py](https://localhost:8080/#) in _get(self, path)
   1724             return fspath[len(self.egg_root) + 1:].split(os.sep)
   1725         raise AssertionError(
-> 1726             "%s is not a subpath of %s" % (fspath, self.egg_root)
   1727         )
   1728 

FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.10/dist-packages/setuptools-67.7.2.dist-info/METADATA'

### Additional information

This code is the demo of mmpose on colab
The code is unable to run only recently
Is it the version issue due to the update of mmengine

**Comment by Ben-Louis** [comment]
In my personal experience, using setuptools version higher than 60 may cause a similar bug. I suggest trying to install a lower version, like 59.5.

**Comment by cjn0116** [comment]
> 

Thanks a lot! I will try it

**Comment by dapaolufuduizhang** [comment]
> In my personal experience, using setuptools version higher than 60 may cause a similar bug. I suggest trying to install a lower version, like 59.5.
Hello, I encountered this error after reducing the version.
"ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cvxpy 1.3.2 requires setuptools>65.5.1, but you have setuptools 59.8.0 which is incompatible.
setuptools-rust 1.7.0 requires setuptools>=62.4, but you have setuptools 59.8.0 which is incompatible."
I would like to ask which version of cvxpy and setuptools rust need to be downgraded to.

**Comment by dapaolufuduizhang** [comment]
> > 
> 
> Thanks a lot! I will try it

Hello,Have you solved this problem yet？

**Comment by cjn0116** [comment]
> > > 
> > 
> > 
> > Thanks a lot! I will try it
> 
> Hello,Have you solved this problem yet？

not yet
