### ISSUE TITLE
Reduce the dataset

### ISSUE THREAD

**Issue by grpinto** [open-mmlab/mmpose#2665]
### 📚 The doc issue

 Is it possible to reduce the coco dataset size along with its annotations and still make it work, or I must train my model on the whole coco dataset, which currently takes 104 days ?

**Comment by Ben-Louis** [comment]
Hi, you might want to consider lowering the number of training epochs in your config file. You can find guidance on how to do this here: https://mmpose.readthedocs.io/en/latest/user_guides/configs.html#training

**Comment by grpinto** [comment]
I have already tried that but in my computer, which has no gpu, it will still take like 5 days to run one of the configs, I tried reducing the size of the data as well as the annotations, but the program kept searching for annotations as well as data that do not exist anymore after I removed them. I used this code :

import os
import json

annotations_folder = "/Users/kingsize/Documents/binedgeml/mmpose/data/coco/annotations"
train2017_folder = "/Users/kingsize/Documents/binedgeml/mmpose/data/coco/train2017"

# Load the annotations
with open(os.path.join(annotations_folder, "coco_wholebody_train_v1.0.json"), "r") as f:
    annotations = json.load(f)

# Get the list of image filenames in train2017
image_filenames = [filename for filename in os.listdir(train2017_folder) if filename.lower().endswith(".jpg")]

# Create a dictionary to store filtered annotations with the same structure
filtered_annotations = {
    "info": annotations["info"],
    "licenses": annotations["licenses"],
    "images": [],
    "annotations": [],
    "categories": annotations["categories"]
}

# Filter images and annotations to keep only those with matching filenames
for img in annotations["images"]:
    file = img['file_name']  # Format image ID with leading zeros
    if file in image_filenames:
        filtered_annotations["images"].append(img)


for ann in annotations["annotations"]:
    for filtered_image in filtered_annotations["images"]:
        if ann["image_id"] == filtered_image["id"]:
            filtered_annotations["annotations"].append(ann)

# Save the updated annotations
output_file = os.path.join(annotations_folder, "coco_wholebody_train_filtered.json")
with open(output_file, "w") as f:
    json.dump(filtered_annotations, f)

print("Filtered annotations saved to", output_file)
