### ISSUE TITLE
[Docs] 

### ISSUE THREAD

**Issue by lwttttt** [open-mmlab/mmpose#2666]
### 📚 The doc issue

在安装文档中，由于版本的更新，可能出现以下错误：
![image](https://github.com/open-mmlab/mmpose/assets/85999869/a735ba64-c80e-4c66-80e8-07f27055fcd1)
这条命令中所下载的模型已经发生了变化，具体名字为：
![image](https://github.com/open-mmlab/mmpose/assets/85999869/109aaefa-d34f-4302-bfea-9a1b53c2405a)

### Suggest a potential alternative/fix

应该对上述命令和下面验证的python代码进行修改，修改文件名即可

**Comment by lwttttt** [comment]
忘记说了 这是mmpose 1.1.0源码安装部分的安装文档

**Comment by Tau-J** [comment]
Hi @lwttttt ，谢谢你的反馈。请问你是否愿意提一个 PR 来帮助我们修复这个文档 bug？

**Comment by lwttttt** [comment]
> Hi @lwttttt ，谢谢你的反馈。请问你是否愿意提一个 PR 来帮助我们修复这个文档 bug？
好的我会提交·一个pr 让我尝试一下

**Comment by Tau-J** [comment]
@lwttttt , 提交 PR 的相关流程可以跟随[这个文档](https://mmpose.readthedocs.io/zh_CN/dev-1.x/contribution_guide.html)
