### ISSUE TITLE
[Docs] 安装文档补充

### ISSUE THREAD

**Issue by lwttttt** [open-mmlab/mmpose#2667]
### 📚 The doc issue

![image](https://github.com/open-mmlab/mmpose/assets/85999869/7111317b-dbc5-4ee6-b9bd-907784ef04ea)
在此场景中由于xtcocotools本身源文件书写路径出现问题，直接运行python setup.py install在linux下会报找不到maskapi.c编译错误，并不能安装成功

### Suggest a potential alternative/fix

安装时应该对xcocotools内部代码做出以下调整：
![image](https://github.com/open-mmlab/mmpose/assets/85999869/0740f57e-35c9-44d8-8414-4280539b9d7c)
![image](https://github.com/open-mmlab/mmpose/assets/85999869/54de4ae4-d888-4b5f-bc41-6d82243de2e5)
虽然我知道应该在xcocotools下提出此issue，但是原作者并没有及进行修改，因此使用此api还是会报错，对于我们文档安装的时候还是出现问题，所以在此作出补充

**Comment by lwttttt** [comment]
忘记说了 这是mmpose 1.1.0源码安装部分的安装文档

**Comment by jin-s13** [comment]
这个问题是否和cython版本 或其他库的版本 有关？

**Comment by lwttttt** [comment]
>没有遇到Cython的问题 是gcc编译会找不到这个文件 是xcocotools新版本代码中路径写的有问题
