### ISSUE TITLE
[Feature] display the dataset 

### ISSUE THREAD

**Issue by alaa-shubbak** [open-mmlab/mmpose#2672]
### What is the feature?

Thanks for your effort in introduce all poes estimation models in one directory . 

i would like to ask for a way to show my custom annotated dataset. 

I have my own dataset in a coco format, and want to show/display the images with the annotation of 4 keypoints. 

I noticed that there was such command in mmdet , which is 
 ` python tools/misc/browse_dataset.py`

i am searching for such a function in mmpose , but i could not find. 

i used the functions in directiry /demo/ such as this one : 
`python demo/top_down_img_demo.py`
which gives a results , but not so accurate . it did not display the ground truth of my annotation very well. 

and this one : 
`python demo/top_down_img_demo_with_mmdet.py`
which gave me this error: 

```
Traceback (most recent call last):
  File "demo/top_down_img_demo_with_mmdet.py", line 138, in <module>
    main()
  File "demo/top_down_img_demo_with_mmdet.py", line 70, in main
    assert args.img != ''
AssertionError
```

any help please .

**Comment by Ben-Louis** [comment]
The new version supports the dataset browser. For more information, refer to [this doc](https://mmpose.readthedocs.io/en/latest/user_guides/prepare_datasets.html#browse-dataset).
