### ISSUE TITLE
[Bug] Kpt Scores for hand model for every keypoint is 1

### ISSUE THREAD

**Issue by chiragdeep01** [open-mmlab/mmpose#2679]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

OUTPUT FROM python -c "from mmpose.utils import collect_env; print(collect_env())" : 
OrderedDict([('sys.platform', 'win32'), ('Python', '3.8.0 (default, Nov  6 2019, 16:00:02) [MSC v.1916 64 bit (AMD64)]'), ('CUDA available', True), ('numpy_random_seed', 2147483648), ('GPU 0', 'NVIDIA GeForce GTX 1650 SUPER'), ('CUDA_HOME', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.8'), ('NVCC', 'Cuda compilation tools, release 11.8, V11.8.89'), ('MSVC', 'Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30151 for x64'), ('GCC', 'n/a'), ('PyTorch', '2.0.0'), ('PyTorch compiling details', 'PyTorch built with:\n  - C++ Version: 199711\n  - MSVC 193431937\n  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)\n  - OpenMP 2019\n  - LAPACK is enabled (usually provided by MKL)\n  - CPU capability usage: NO AVX\n  - CUDA Runtime 11.8\n  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90;-gencode;arch=compute_37,code=compute_37\n  - CuDNN 8.7\n  - Magma 2.5.4\n  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj /FS -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=OFF, TORCH_VERSION=2.0.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF, \n'), ('TorchVision', '0.15.0'), ('OpenCV', '4.8.0'), ('MMEngine', '0.8.4'), ('MMPose', '1.1.0+')])
ENVIROMENT DETAILS : 
Package                       Version
----------------------------- ---------
addict                        2.4.0
aliyun-python-sdk-core        2.13.36
aliyun-python-sdk-kms         2.16.1
asttokens                     2.2.1
backcall                      0.2.0
backports.functools-lru-cache 1.6.5
brotlipy                      0.7.0
certifi                       2023.7.22
cffi                          1.15.1
charset-normalizer            2.0.4
chumpy                        0.70
click                         8.1.7
colorama                      0.4.6
comm                          0.1.4
contourpy                     1.1.0
crcmod                        1.7
cryptography                  41.0.2
cycler                        0.11.0
Cython                        3.0.2
debugpy                       1.6.7
decorator                     4.4.2
executing                     1.2.0
filelock                      3.9.0
fonttools                     4.42.1
idna                          3.4
imageio                       2.31.2
imageio-ffmpeg                0.4.8
importlib-metadata            6.8.0
importlib-resources           6.0.1
ipykernel                     6.25.1
ipython                       8.12.0
jedi                          0.19.0
Jinja2                        3.1.2
jmespath                      0.10.0
json-tricks                   3.17.3
jupyter_client                8.3.0
jupyter_core                  5.3.1
kiwisolver                    1.4.5
Markdown                      3.4.4
markdown-it-py                3.0.0
MarkupSafe                    2.1.1
matplotlib                    3.7.2
matplotlib-inline             0.1.6
mdurl                         0.1.2
mkl-fft                       1.3.6
mkl-random                    1.2.2
mkl-service                   2.4.0
mmcv                          2.0.1
mmdet                         3.1.0
mmengine                      0.8.4
mmpose                        1.1.0
model-index                   0.1.11
moviepy                       1.0.3
mpmath                        1.3.0
munkres                       1.1.4
nest-asyncio                  1.5.6
networkx                      3.1
numpy                         1.24.3
opencv-python                 4.8.0.76
opendatalab                   0.0.10
openmim                       0.3.9
openxlab                      0.0.21
ordered-set                   4.1.0
oss2                          2.17.0
packaging                     23.1
pandas                        2.0.3
parso                         0.8.3
pickleshare                   0.7.5
Pillow                        9.4.0
pip                           23.2.1
platformdirs                  3.10.0
proglog                       0.1.10
prompt-toolkit                3.0.39
psutil                        5.9.0
pure-eval                     0.2.2
pycocotools                   2.0.7
pycparser                     2.21
pycryptodome                  3.18.0
Pygments                      2.16.1
pyOpenSSL                     23.2.0
pyparsing                     3.0.9
PySocks                       1.7.1
python-dateutil               2.8.2
pytz                          2023.3
pywin32                       305.1
PyYAML                        6.0.1
pyzmq                         23.2.1
regex                         2023.8.8
requests                      2.28.2
rich                          13.4.2
scipy                         1.10.1
setuptools                    60.2.0
shapely                       2.0.1
six                           1.16.0
stack-data                    0.6.2
sympy                         1.11.1
tabulate                      0.9.0
termcolor                     2.3.0
terminaltables                3.1.10
tomli                         2.0.1
torch                         2.0.0
torchaudio                    2.0.0
torchvision                   0.15.0
tornado                       6.2
tqdm                          4.65.2
traitlets                     5.9.0
typing_extensions             4.7.1
tzdata                        2023.3
urllib3                       1.26.16
wcwidth                       0.2.6
wheel                         0.38.4
win-inet-pton                 1.1.0
xtcocotools                   1.13
yapf                          0.40.1
zipp                          3.16.2

### Reproduces the problem - code sample

from mmpose.apis import MMPoseInferencer
from mmpose.utils import register_all_modules
register_all_modules()
import cv2
import time
model = MMPoseInferencer('td-reg_res50_8xb64-210e_onehand10k-256x256', device = "cuda:0")
video_path = 'vid.mp4'
cap = cv2.VideoCapture(video_path)
while cap.isOpened():
   ret, frame = cap.read()
    if not ret:
        break
    result_generator = model(frame,device="cuda:0", return_vis = False, draw_bbox = False, thickness = 3, kpt_thr = 1)
    result = next(result_generator)
    print(result)
    cv2.imshow("Video Playback", frame)
    if cv2.waitKey(25) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

### Reproduces the problem - command or script

.

### Reproduces the problem - error message

The kpt threshold was not affecting the visualization frame so i printed the returned results and all the keypoint scores are 1 as you can see below. I tried doing the same thing with the default model by mmpose by passing "hand" to the MMPoseInferencer and i got correct kpt scores.

defaultdict(<class 'list'>, {'visualization': None, 'predictions': [[{'keypoints': [[191.08105088886805, 178.7283274800866], [172.24347139991005, 144.21521476644557], [189.4724801381817, 164.94325896102237], [212.33086724540044, 209.07202931164647], [233.64268450907548, 245.3558083679527], [272.61243143552565, 130.41640996892238], [285.89331097967806, 216.30436757436837], [283.09497584804194, 253.286520044785], [285.57681361288996, 307.7019239512156], [291.60306158993626, 187.40410090546357], [300.1678188631777, 263.1433882327401], [294.4207626223506, 306.7436121092178], [286.3306575722527, 342.1338950418285], [291.6819138332212, 226.8084922057751], [295.99251564306905, 278.3986138550681], [288.5176157200185, 324.0170198021806], [275.43801393918693, 333.24622263235506], [278.6416443469934, 249.89028149202932], [280.02563069795724, 273.4054391044192], [276.29266566887964, 294.06209968798794], [264.3932954418706, 307.5068387724459]], 'keypoint_scores': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0], 'bbox': ([12.785720825195312, 1.72137451171875, 516.5158081054688, 479.5793151855469],), 'bbox_score': 0.9619084}]]}

**Comment by Ben-Louis** [comment]
The deeppose algorithm used by config 'td-reg_res50_8xb64-210e_onehand10k-256x256' will not generate scores for each keypoint prediction.

**Comment by chiragdeep01** [comment]
okay thanks
