### ISSUE TITLE
[Docs] Interval flag on training

### ISSUE THREAD

**Issue by grpinto** [open-mmlab/mmpose#2681]
### 📚 The doc issue

Can somebody clarify to me how to use the interval flag on the python tools/train.py command, or how should I use it ?

**Comment by Ben-Louis** [comment]
This parameter controls how often the validation results are displayed. For example, if you choose `--interval=50`, the model will show the predictions for only one validation image after every 50 images. It's important to note that this parameter only functions when `--show` or `--show-dir` is enabled.
