### ISSUE TITLE
[Bug] 09/13 10:14:19 - mmengine - INFO - Exp name: cspnext-m_udp_8xb64-210e_coco-wholebody-256x192_20230913_074951 09/13 10:14:19 - mmengine - INFO - Switch pipeline now!

### ISSUE THREAD

**Issue by grpinto** [open-mmlab/mmpose#2689]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

I have had this error message on epoch 4 of my training. I edited the config file to have 5 epochs, 4 for training and 1 for validation and right before the validation error starts I get this problem :

09/13 10:14:19 - mmengine - INFO - Exp name: cspnext-m_udp_8xb64-210e_coco-wholebody-256x192_20230913_074951
09/13 10:14:19 - mmengine - INFO - Switch pipeline now!

Does anybody has any idea on how to solve this ?

PS: Also I don't seem to be able to export the checkpoints of the model, I am running the model on colab

### Reproduces the problem - code sample

.

### Reproduces the problem - command or script

!python tools/train.py configs/wholebody_2d_keypoint/topdown_heatmap/coco-wholebody/cspnext-m_udp_8xb64-210e_coco-wholebody-256x192.py --resume

### Reproduces the problem - error message

.

**Comment by Tau-J** [comment]
Hi @grpinto , thanks for using MMPose. `09/13 10:14:19 - mmengine - INFO - Switch pipeline now!` is not a bug, but a normal log.  This config adapts a 2-stage augmentation strategy, thus, there is a log when strategy changed.
