### ISSUE TITLE
使用c++推理rtmpose的tensorRT模型效果变差

### ISSUE THREAD

**Issue by Haroldhy** [open-mmlab/mmpose#2690]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

我使用了mmdeploy/tools/depoly.py导出了rtmpose的.engine模型，并使用mmpose\projects\rtmpose\examples\RTMPose-Deploy\Windows\TensorRT\src\RTMPoseTensorRT文件夹下的c++代码进行推理。很奇怪的是，在部分情况下，我推理得到的结果比直接使用mmpose/demo/topdown_demo_with_mmdet.py推理pytorch模型的效果差。请问这是为什么呢？
此外，我修改了后处理的两行代码，才能够显示正确的keypoints，不然keypoint的横坐标和纵坐标会反过来，修改代码如下：
        //temp_point.x = (pose_x - offset[0]) * img_w / (input_w - 2 * offset[0]);
        //temp_point.y = (pose_y - offset[1]) * img_h / (input_h - 2 * offset[1]);

	temp_point.x = pose_x * img_w / input_w;
	temp_point.y = pose_y * img_h / input_h;

### Reproduces the problem - code sample

std::vector<PosePoint> TrtRTMPose::postprocess(std::vector<float> simcc_x_result, std::vector<float> simcc_y_result, int img_w, int img_h)
{
    std::vector<PosePoint> pose_result;
    for (int i = 0; i < num_points; ++i)
    {
        // find the maximum and maximum indexes in the value of each Extend_width length
        auto x_biggest_iter = std::max_element(simcc_x_result.begin() + i * extend_width, simcc_x_result.begin() + i * extend_width + extend_width);
        int max_x_pos = std::distance(simcc_x_result.begin() + i * extend_width, x_biggest_iter);
        int pose_x = max_x_pos / 2;
        float score_x = *x_biggest_iter;

        // find the maximum and maximum indexes in the value of each exten_height length
        auto y_biggest_iter = std::max_element(simcc_y_result.begin() + i * extend_height, simcc_y_result.begin() + i * extend_height + extend_height);
        int max_y_pos = std::distance(simcc_y_result.begin() + i * extend_height, y_biggest_iter);
        int pose_y = max_y_pos / 2;
        float score_y = *y_biggest_iter;

        // get point confidence
        float score = MAX(score_x, score_y);

        PosePoint temp_point;
        //temp_point.x = (pose_x - offset[0]) * img_w / (input_w - 2 * offset[0]);
        //temp_point.y = (pose_y - offset[1]) * img_h / (input_h - 2 * offset[1]);

	temp_point.x = pose_x * img_w / input_w;
	temp_point.y = pose_y * img_h / input_h;

        temp_point.score = score;
        pose_result.emplace_back(temp_point);
    }

    return pose_result;
}

### Reproduces the problem - command or script

E:\hy\algorithm\workspace\mmpose\projects\rtmpose\examples\RTMPose-Deploy\Windows\TensorRT\src\RTMPoseTensorRT/main.cpp

### Reproduces the problem - error message

tensorRT的运行结果与原来的结果有差距，就是原先pytorch模型可以预测准确的内容现在预测不准了，这一点让我感到非常奇怪。但在简单情况下，姿态的预测仍然准确，而在一些复杂任务中的表现会下降。

**Comment by Tau-J** [comment]
@Haroldhy 你好，pytorch 推理脚本默认开启了flip_test，这会为模型精度带来1 AP左右的提升，c++版本单次推理应该不带tta，因此效果会略有差异。

**Comment by Haroldhy** [comment]
感谢回答，我关闭了flip_test，但是还是和我c++推理的结果很不一样。当在复杂情况下（也不是特别复杂的情况，仅仅是人侧身或者躺下之类的情况），c++代码推理的结果就比原来的结果差非常多，部分姿态点会乱跳。

**Comment by Tau-J** [comment]
我无法定位你的问题，但是这份代码据我了解是跟pytorch版本结果可以对齐的。我想请问你的输入图片是否有使用det模型进行检测和裁剪，因为RTMPose 是一个topdown算法，如果单独将未检测的图片送入Pose模型，会导致性能大幅度下降，这是我想到的一种常见的误用。

**Comment by Haroldhy** [comment]
我是用rtmdet检测然后裁剪了图片，然后再用rtmpose推理的。这是我导出onnx和engine的代码，请问有什么明显的问题吗？python .\tools\deploy.py .\configs\mmpose\pose-detection_simcc_tensorrt_dynamic-256x192.py ..\mmpose\projects\rtmpose\rtmpose\body_2d_keypoint\rtmpose-m_8xb256-420e_coco-256x192.py .\weights\rtmpose-m_simcc-aic-coco_pt-aic-coco_420e-256x192-63eb25f7_20230126.pth .\demo\resources\human-pose.jpg --work-dir rtmpose-trt/rtmpose-m --device cuda:0 --show --dump-info

**Comment by Haroldhy** [comment]
另外，我没有看懂RTMpose页面下的用python的API调用tensorRT的推理，我不知道要如何进行推理。我将这个其放到mmploy文件夹下，并运行 python .\test_tensorRT.py cuda:0 .\rtmpose-trt\rtmpose-m\end2end.engine .\demo\resources\human-pose.jpg，结果报错：

loading mmdeploy_trt_net.dll ...
loading mmdeploy_ort_net.dll ...
[2023-09-14 19:00:04.958] [mmdeploy] [info] [zip_model_impl.cpp:38] Failed to open zip file .\rtmpose-trt\rtmpose-m\end2end.engine, ret 19
[2023-09-14 19:00:04.958] [mmdeploy] [error] [model.cpp:40] Failed to load model: ".\rtmpose-trt\rtmpose-m\end2end.engine", implementations tried: [("DirectoryModel", 0), ("ZipModel", 0)]
[2023-09-14 19:00:04.959] [mmdeploy] [error] [model.cpp:16] Failed to load model ".\rtmpose-trt\rtmpose-m\end2end.engine"
[2023-09-14 19:00:04.960] [mmdeploy] [error] [model.cpp:21] failed to create model: not supported (2)
Traceback (most recent call last):
  File ".\test_tensorRT.py", line 51, in <module>
    main()
  File ".\test_tensorRT.py", line 30, in main
    detector = PoseDetector(
RuntimeError: failed to create pose_detector

您可以帮我看一下是什么问题吗？或者您有什么其他建议的推理RTMPose的tensorRT模型的python代码吗？这样我就可以根据python代码检查我的c++代码了

**Comment by Tau-J** [comment]
请仔细阅读文档和示例中的注释，输入是文件夹，不是`.engine`文件

**Comment by liangzhenghao2000** [comment]
解决问题了吗，我这边测试wholebody的trt模型效果也变差了很多

**Comment by Haroldhy** [comment]
我的问题是因为库中提供的c++推理代码的前处理使得输入图像变形了，前处理的时候不要让它变形就好了。如果是自己写的代码应该不会有这个问题。

**Comment by liangzhenghao2000** [comment]
> 我的问题是因为库中提供的c++推理代码的前处理使得输入图像变形了，前处理的时候不要让它变形就好了。如果是自己写的代码应该不会有这个问题。

库中的代码是mmpose这边提供的那个吗？我这边看好像还挺正常的。

**Comment by Haroldhy** [comment]
https://github.com/open-mmlab/mmpose/tree/main/projects/rtmpose/examples/RTMPose-Deploy/Windows/TensorRT
我记得当时看的是这里的代码

**Comment by liangzhenghao2000** [comment]
> https://github.com/open-mmlab/mmpose/tree/main/projects/rtmpose/examples/RTMPose-Deploy/Windows/TensorRT 我记得当时看的是这里的代码

嗯，代码我看了，前处理那部分让输入图像变形了吗？我看到只是缩放了然后置中放进输入里了

**Comment by Haroldhy** [comment]
我觉得问题就在于直接缩放，导致了人被拉长或者压扁了。我测试出来是对效果有影响的，将前处理改为填充黑边再缩放，测试效果就正常了。

**Comment by liangzhenghao2000** [comment]
> 我觉得问题就在于直接缩放，导致了人被拉长或者压扁了。我测试出来是对效果有影响的，将前处理改为填充黑边再缩放，测试效果就正常了。

你那个问题可能是一路引用修改到原图了，这个问题我之前解决了，那看来我们遇到的不是一个问题

**Comment by FunnyWii** [comment]
请问这个RTMPose是只能用C++ TensorRT在Windows下面部署吗
