### ISSUE TITLE
[Feature] The AIDI and VIDI products have a positioning function similar to key point detection, which can set the size and direction of key points

### ISSUE THREAD

**Issue by youzeng** [open-mmlab/mmpose#2694]
### What is the feature?

The AIDI and VIDI products  have a positioning function similar to key point detection, which can set the size and direction of key points. They belong to the manufacturing industry and are used for target positioning of equipment or production lines, with all key points combined to represent the entire product position. Is it possible to consider similar functions for mmpose, or are there any relevant papers or materials recommended for me to study

**Comment by Ben-Louis** [comment]
Thank you for your interest. At this time, MMPose does not have any plans to support this particular function. However, it is possible to use MMPose for detecting keypoints and predicting their direction. If you happen to come across any projects related to this, please kindly consider adding them into [mmpose projects](https://github.com/open-mmlab/mmpose/tree/main/projects).
