### ISSUE TITLE
[Bug] 运行pip install -r requirements.txt，报错，卡在安装教程中

### ISSUE THREAD

**Issue by qq1342753906** [open-mmlab/mmpose#2695]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

PS D:\python\mmpose\mmpose> pip install -r requirements.txt
Requirement already satisfied: numpy in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from -r requirements/build.txt (line 2)) (1.25.2)
Requirement already satisfied: torch>=1.8 in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from -r requirements/build.txt (line 3)) (2.0.1+cu117)
Collecting chumpy (from -r requirements/runtime.txt (line 1))
  Using cached chumpy-0.70-py3-none-any.whl
Collecting json_tricks (from -r requirements/runtime.txt (line 2))
  Obtaining dependency information for json_tricks from https://files.pythonhosted.org/packages/ae/fd/e3edcf827e7f9c17c5ea1a192841dcfb1dd575a7518c25c5cadd921625b1/json_tricks-3.17.3-py2.py3-none-any.whl.metadata
  Using cached json_tricks-3.17.3-py2.py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: matplotlib in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from -r requirements/runtime.txt (line 3)) (3.7.2)
Collecting munkres (from -r requirements/runtime.txt (line 4))
  Using cached munkres-1.1.4-py2.py3-none-any.whl (7.0 kB)
Requirement already satisfied: opencv-python in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from -r requirements/runtime.txt (line 6)) (4.8.0.76)
Requirement already satisfied: pillow in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from -r requirements/runtime.txt (line 7)) (10.0.0)
Requirement already satisfied: scipy in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from -r requirements/runtime.txt (line 8)) (1.11.2)
Requirement already satisfied: torchvision in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from -r requirements/runtime.txt (line 9)) (0.15.2+cu117)
Collecting xtcocotools>=1.12 (from -r requirements/runtime.txt (line 10))
  Using cached xtcocotools-1.13.tar.gz (28 kB)
  Preparing metadata (setup.py) ... done
Collecting coverage (from -r requirements/tests.txt (line 1))
  Obtaining dependency information for coverage from https://files.pythonhosted.org/packages/09/c2/bdcdff246f7bcfcc63a84679412837e44ec8460d152caeff07e3668e5733/coverage-7.3.1-cp311-cp311-win_amd64.whl.metadata
  Using cached coverage-7.3.1-cp311-cp311-win_amd64.whl.metadata (8.3 kB)
Collecting flake8 (from -r requirements/tests.txt (line 2))
  Obtaining dependency information for flake8 from https://files.pythonhosted.org/packages/b0/24/bbf7175ffc47cb3d3e1eb523ddb23272968359dfcf2e1294707a2bf12fc4/flake8-6.1.0-py2.py3-none-any.whl.metadata
  Using cached flake8-6.1.0-py2.py3-none-any.whl.metadata (3.8 kB)
Collecting interrogate (from -r requirements/tests.txt (line 3))
  Using cached interrogate-1.5.0-py3-none-any.whl (45 kB)
Collecting isort==4.3.21 (from -r requirements/tests.txt (line 4))
  Using cached isort-4.3.21-py2.py3-none-any.whl (42 kB)
Collecting parameterized (from -r requirements/tests.txt (line 5))
  Using cached parameterized-0.9.0-py2.py3-none-any.whl (20 kB)
Collecting pytest (from -r requirements/tests.txt (line 6))
  Obtaining dependency information for pytest from https://files.pythonhosted.org/packages/df/d0/e192c4275aecabf74faa1aacd75ef700091913236ec78b1a98f62a2412ee/pytest-7.4.2-py3-none-any.whl.metadata
  Using cached pytest-7.4.2-py3-none-any.whl.metadata (7.9 kB)
Collecting pytest-runner (from -r requirements/tests.txt (line 7))
  Using cached pytest_runner-6.0.0-py3-none-any.whl (7.2 kB)
Collecting xdoctest>=0.10.0 (from -r requirements/tests.txt (line 8))
  Using cached xdoctest-1.1.1-py3-none-any.whl (137 kB)
Requirement already satisfied: yapf in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from -r requirements/tests.txt (line 9)) (0.40.1)
Requirement already satisfied: requests in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from -r requirements/optional.txt (line 1)) (2.28.2)
Requirement already satisfied: filelock in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from torch>=1.8->-r requirements/build.txt (line 3)) (3.9.0)
Requirement already satisfied: typing-extensions in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from torch>=1.8->-r requirements/build.txt (line 3)) (4.4.0)
Requirement already satisfied: sympy in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from torch>=1.8->-r requirements/build.txt (line 3)) (1.11.1)
Requirement already satisfied: networkx in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from torch>=1.8->-r requirements/build.txt (line 3)) (3.0)
Requirement already satisfied: jinja2 in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from torch>=1.8->-r requirements/build.txt (line 3)) (3.1.2)
Requirement already satisfied: six>=1.11.0 in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from chumpy->-r requirements/runtime.txt (line 1)) (1.16.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from matplotlib->-r requirements/runtime.txt (line 3)) (1.1.0)
Requirement already satisfied: cycler>=0.10 in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from matplotlib->-r requirements/runtime.txt (line 3)) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from matplotlib->-r requirements/runtime.txt (line 3)) (4.42.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from matplotlib->-r requirements/runtime.txt (line 3)) (1.4.5)
Requirement already satisfied: packaging>=20.0 in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from matplotlib->-r requirements/runtime.txt (line 3)) (23.1)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from matplotlib->-r requirements/runtime.txt (line 3)) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from matplotlib->-r requirements/runtime.txt (line 3)) (2.8.2)
Requirement already satisfied: setuptools>=18.0 in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from xtcocotools>=1.12->-r requirements/runtime.txt (line 10)) (68.2.2)
Requirement already satisfied: cython>=0.27.3 in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from xtcocotools>=1.12->-r requirements/runtime.txt (line 10)) (3.0.2)
Collecting mccabe<0.8.0,>=0.7.0 (from flake8->-r requirements/tests.txt (line 2))
  Using cached mccabe-0.7.0-py2.py3-none-any.whl (7.3 kB)
Collecting pycodestyle<2.12.0,>=2.11.0 (from flake8->-r requirements/tests.txt (line 2))
  Obtaining dependency information for pycodestyle<2.12.0,>=2.11.0 from https://files.pythonhosted.org/packages/31/c2/e1508ed4395793f69e40fd8c6b5a690e1d568e649aae9492076a7b6befb4/pycodestyle-2.11.0-py2.py3-none-any.whl.metadata
  Using cached pycodestyle-2.11.0-py2.py3-none-any.whl.metadata (4.5 kB)
Collecting pyflakes<3.2.0,>=3.1.0 (from flake8->-r requirements/tests.txt (line 2))
  Obtaining dependency information for pyflakes<3.2.0,>=3.1.0 from https://files.pythonhosted.org/packages/00/e9/1e1fd7fae559bfd07704991e9a59dd1349b72423c904256c073ce88a9940/pyflakes-3.1.0-py2.py3-none-any.whl.metadata
  Using cached pyflakes-3.1.0-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting attrs (from interrogate->-r requirements/tests.txt (line 3))
  Using cached attrs-23.1.0-py3-none-any.whl (61 kB)
Requirement already satisfied: click>=7.1 in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from interrogate->-r requirements/tests.txt (line 3)) (8.1.7)
Requirement already satisfied: colorama in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from interrogate->-r requirements/tests.txt (line 3)) (0.4.6)
Collecting py (from interrogate->-r requirements/tests.txt (line 3))
  Using cached py-1.11.0-py2.py3-none-any.whl (98 kB)
Requirement already satisfied: tabulate in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from interrogate->-r requirements/tests.txt (line 3)) (0.9.0)
Collecting toml (from interrogate->-r requirements/tests.txt (line 3))
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting iniconfig (from pytest->-r requirements/tests.txt (line 6))
  Using cached iniconfig-2.0.0-py3-none-any.whl (5.9 kB)
Collecting pluggy<2.0,>=0.12 (from pytest->-r requirements/tests.txt (line 6))
  Obtaining dependency information for pluggy<2.0,>=0.12 from https://files.pythonhosted.org/packages/05/b8/42ed91898d4784546c5f06c60506400548db3f7a4b3fb441cba4e5c17952/pluggy-1.3.0-py3-none-any.whl.metadata
  Using cached pluggy-1.3.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: importlib-metadata>=6.6.0 in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from yapf->-r requirements/tests.txt (line 9)) (6.8.0)
Requirement already satisfied: platformdirs>=3.5.1 in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from yapf->-r requirements/tests.txt (line 9)) (3.10.0)
Requirement already satisfied: tomli>=2.0.1 in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from yapf->-r requirements/tests.txt (line 9)) (2.0.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from requests->-r requirements/optional.txt (line 1)) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from requests->-r requirements/optional.txt (line 1)) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from requests->-r requirements/optional.txt (line 1)) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from requests->-r requirements/optional.txt (line 1)) (2023.7.22)
Requirement already satisfied: zipp>=0.5 in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from importlib-metadata>=6.6.0->yapf->-r requirements/tests.txt (line 9)) (3.16.2)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from jinja2->torch>=1.8->-r requirements/build.txt (line 3)) (2.1.2)
Requirement already satisfied: mpmath>=0.19 in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from sympy->torch>=1.8->-r requirements/build.txt (line 3)) (1.2.1)
Using cached json_tricks-3.17.3-py2.py3-none-any.whl (27 kB)
Using cached coverage-7.3.1-cp311-cp311-win_amd64.whl (204 kB)
Using cached flake8-6.1.0-py2.py3-none-any.whl (58 kB)
Using cached pytest-7.4.2-py3-none-any.whl (324 kB)
Using cached pluggy-1.3.0-py3-none-any.whl (18 kB)
Using cached pycodestyle-2.11.0-py2.py3-none-any.whl (31 kB)
Using cached pyflakes-3.1.0-py2.py3-none-any.whl (62 kB)
Building wheels for collected packages: xtcocotools
  Building wheel for xtcocotools (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [36 lines of output]
      C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!

              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************

      !!
        dist.fetch_build_eggs(dist.setup_requires)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\xtcocotools
      copying xtcocotools\coco.py -> build\lib.win-amd64-cpython-311\xtcocotools
      copying xtcocotools\cocoeval.py -> build\lib.win-amd64-cpython-311\xtcocotools
      copying xtcocotools\mask.py -> build\lib.win-amd64-cpython-311\xtcocotools
      copying xtcocotools\version.py -> build\lib.win-amd64-cpython-311\xtcocotools
      copying xtcocotools\__init__.py -> build\lib.win-amd64-cpython-311\xtcocotools
      running build_ext
      Compiling xtcocotools/_mask.pyx because it changed.
      [1/1] Cythonizing xtcocotools/_mask.pyx
      C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\Cython\Compiler\Main.py:384: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: C:\Users\Administrator\AppData\Local\Temp\pip-install-va7d2hot\xtcocotools_ef4ea13bb1604b2e92f5d0bd597d6bca\xtcocotools\_mask.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      building 'xtcocotools._mask' extension
      creating build\temp.win-amd64-cpython-311
      creating build\temp.win-amd64-cpython-311\common
      creating build\temp.win-amd64-cpython-311\Release
      creating build\temp.win-amd64-cpython-311\Release\common
      creating build\temp.win-amd64-cpython-311\Release\xtcocotools
      "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\core\include -I./common -IC:\Users\Administrator\AppData\Local\Programs\Python\Python311\include -IC:\Users\Administrator\AppData\Local\Programs\Python\Python311\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /Tc../common/maskApi.c /Fobuild\temp.win-amd64-cpython-311\Release\../common/maskApi.obj
      maskApi.c
      c1: fatal error C1083: 无法打开源文件: “../common/maskApi.c”: No such file or directory
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for xtcocotools
  Running setup.py clean for xtcocotools
Failed to build xtcocotools
ERROR: Could not build wheels for xtcocotools, which is required to install pyproject.toml-based projects

### Reproduces the problem - code sample

不知道

### Reproduces the problem - command or script

不知道

### Reproduces the problem - error message

不知道

### Additional information

不知道

**Comment by Ben-Louis** [comment]
可以尝试这么几个方案：
1. 安装最新版 xtcocotools `pip install xtcocotools==1.14`
2. 从源码安装 xtcocotools: https://github.com/jin-s13/xtcocoapi
3. 按照报错信息中的提示，运行 `pip install --use-pep517 xtcocotools`

如果以上方案都不行，建议在 linux 环境下尝试安装和运行 mmpose
