### ISSUE TITLE
[Docs] How to use SmoothNet

### ISSUE THREAD

**Issue by spicer-c** [open-mmlab/mmpose#2697]
### 📚 The doc issue

I see this was supported at some point, I am looking to smooth my 2d pose results frames, how can I do this? Thanks

**Comment by Tau-J** [comment]
@spicer-c thanks for using MMPose. SmoothNet is supported in the `0.x` branch for now, you can refer to [here](https://github.com/open-mmlab/mmpose/blob/0.x/mmpose/core/post_processing/temporal_filters/smoothnet_filter.py). We do not migrate it into `mmpose 1.x` yet, we will appreciate a lot if you can help.
