### ISSUE TITLE
[Bug] Importing visualize from mmpose.apis crashes code

### ISSUE THREAD

**Issue by anorakthegreat** [open-mmlab/mmpose#2700]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

Although documentation linked [here ](https://mmpose.readthedocs.io/en/latest/user_guides/inference.html) imports visualize to show results, using it in my code crashes it. 

What am i doing wrong?

### Reproduces the problem - code sample

from mmpose.apis import visualize

### Reproduces the problem - command or script

from mmpose.apis import visualize

### Reproduces the problem - error message

ImportError: cannot import name 'visualize' from 'mmpose.apis' (C:\Users\sanja\anaconda3\envs\openmmlab\lib\site-packages\mmpose\apis\__init__.py)

**Comment by Ben-Louis** [comment]
Thank you for using MMPose. The new function is included in branch ‘dev-1.x’ and is not available in the pypi package. To install the required version of mmpose for this function, please run the command: pip install git+https://github.com/open-mmlab/mmpose.git@dev-1.x
