### ISSUE TITLE
COCO与AIC数据结合的训练的问题？

### ISSUE THREAD

**Issue by TDIT-haha** [open-mmlab/mmpose#2704]
### 📚 The doc issue

你好，我查看COCO与AIC数据结合训练的demo。但是我有个疑惑COCO数据集是17个关键点，AIC与COCO的关键点数是不一样的，尽管在AIC中提取了与COCO相同的关键点，而AIC并没有脸部的关键点，因此在AIC中把脸部关键点的可见性变为0。在模型训练中读取AIC的图像时对象脸部的关键点实际是可见的，但又告诉模型这是不可见，这不是对比读COCO数据集时有明显的差别，这样训练出来的结果会好么？但是rtmpose论文中告诉我是能提点的，我有点疑惑，这样的训练对脸部关键点的检测不会有影响么？为什么指标会有提升？那如果我添加一个只有上半身的关键点的数据集（下半身的关键点没有标注但可见），也可以这样添加么？是会对上半身的关键点检测有提升么？

**Comment by Tau-J** [comment]
@TDIT-haha 你好，谢谢关注 MMPose。混合数据集训练时，没有标注信息的点的权重会被设置成0，在计算loss时，这个点不会有loss产生，因此不会对模型训练产生正向或者负面的影响。这一类的技术问题可以加 MMPose 的社区群讨论，issue中主要是解答 MMPose 开源库使用上的问题，谢谢。
