### ISSUE TITLE
[Bug] topdown_demo_with_mmdet.py script visualization takes too long

### ISSUE THREAD

**Issue by da13132** [open-mmlab/mmpose#2715]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

mmcv                2.0.0
mmdet               3.0.0        /home/keli/pose/mmdetection-3.0.0
mmengine            0.8.2
mmpose              1.0.0        /home/keli/pose
mmpretrain          1.0.0rc8     /home/keli/下pose/mmpretrain
mmyolo              0.6.0        /home/keli/pose/mmyolo
timm                0.4.9

### Reproduces the problem - code sample

# Copyright (c) OpenMMLab. All rights reserved.
import mimetypes
import os
import tempfile
from argparse import ArgumentParser

import json_tricks as json
import mmcv
import mmengine
import numpy as np

from mmpose.apis import inference_topdown
from mmpose.apis import init_model as init_pose_estimator
from mmpose.evaluation.functional import nms
from mmpose.registry import VISUALIZERS
from mmpose.structures import merge_data_samples, split_instances
from mmpose.utils import adapt_mmdet_pipeline

try:
    from mmdet.apis import inference_detector, init_detector
    has_mmdet = True
except (ImportError, ModuleNotFoundError):
    has_mmdet = False

def process_one_image(args, img_path, detector, pose_estimator, visualizer,
                      show_interval):
    """Visualize predicted keypoints (and heatmaps) of one image."""

    # predict bbox
    det_result = inference_detector(detector, img_path)
    pred_instance = det_result.pred_instances.cpu().numpy()
    bboxes = np.concatenate(
        (pred_instance.bboxes, pred_instance.scores[:, None]), axis=1)
    bboxes = bboxes[np.logical_and(pred_instance.labels == args.det_cat_id,
                                   pred_instance.scores > args.bbox_thr)]
    bboxes = bboxes[nms(bboxes, args.nms_thr), :4]

    # predict keypoints
    pose_results = inference_topdown(pose_estimator, img_path, bboxes)
    data_samples = merge_data_samples(pose_results)

    # show the results
    img = mmcv.imread(img_path, channel_order='rgb')

    out_file = None
    if args.output_root:
        out_file = f'{args.output_root}/{os.path.basename(img_path)}'

    visualizer.add_datasample(
        'result',
        img,
        data_sample=data_samples,
        draw_gt=False,
        draw_heatmap=args.draw_heatmap,
        draw_bbox=args.draw_bbox,
        show_kpt_idx=args.show_kpt_idx,
        skeleton_style=args.skeleton_style,
        show=args.show,
        wait_time=show_interval,
        out_file=out_file,
        kpt_thr=args.kpt_thr)

    # if there is no instance detected, return None
    return data_samples.get('pred_instances', None)

def main():
    """Visualize the demo images.

    Using mmdet to detect the human.
    """
    parser = ArgumentParser()
    parser.add_argument('det_config', help='Config file for detection')
    parser.add_argument('det_checkpoint', help='Checkpoint file for detection')
    parser.add_argument('pose_config', help='Config file for pose')
    parser.add_argument('pose_checkpoint', help='Checkpoint file for pose')
    parser.add_argument(
        '--input', type=str, default='', help='Image/Video file')
    parser.add_argument(
        '--show',
        action='store_true',
        default=False,
        help='whether to show img')
    parser.add_argument(
        '--output-root',
        type=str,
        default='',
        help='root of the output img file. '
        'Default not saving the visualization images.')
    parser.add_argument(
        '--save-predictions',
        action='store_true',
        default=False,
        help='whether to save predicted results')
    parser.add_argument(
        '--device', default='cuda:0', help='Device used for inference')
    parser.add_argument(
        '--det-cat-id',
        type=int,
        default=0,
        help='Category id for bounding box detection model')
    parser.add_argument(
        '--bbox-thr',
        type=float,
        default=0.3,
        help='Bounding box score threshold')
    parser.add_argument(
        '--nms-thr',
        type=float,
        default=0.3,
        help='IoU threshold for bounding box NMS')
    parser.add_argument(
        '--kpt-thr',
        type=float,
        default=0.3,
        help='Visualizing keypoint thresholds')
    parser.add_argument(
        '--draw-heatmap',
        action='store_true',
        default=False,
        help='Draw heatmap predicted by the model')
    parser.add_argument(
        '--show-kpt-idx',
        action='store_true',
        default=False,
        help='Whether to show the index of keypoints')
    parser.add_argument(
        '--skeleton-style',
        default='mmpose',
        type=str,
        choices=['mmpose', 'openpose'],
        help='Skeleton style selection')
    parser.add_argument(
        '--radius',
        type=int,
        default=3,
        help='Keypoint radius for visualization')
    parser.add_argument(
        '--thickness',
        type=int,
        default=1,
        help='Link thickness for visualization')
    parser.add_argument(
        '--alpha', type=float, default=0.8, help='The transparency of bboxes')
    parser.add_argument(
        '--draw-bbox', action='store_true', help='Draw bboxes of instances')

    assert has_mmdet, 'Please install mmdet to run the demo.'

    args = parser.parse_args()

    assert args.show or (args.output_root != '')
    assert args.input != ''
    assert args.det_config is not None
    assert args.det_checkpoint is not None
    if args.output_root:
        mmengine.mkdir_or_exist(args.output_root)
    if args.save_predictions:
        assert args.output_root != ''
        args.pred_save_path = f'{args.output_root}/results_' \
            f'{os.path.splitext(os.path.basename(args.input))[0]}.json'

    # build detector
    detector = init_detector(
        args.det_config, args.det_checkpoint, device=args.device)
    detector.cfg = adapt_mmdet_pipeline(detector.cfg)

    # build pose estimator
    pose_estimator = init_pose_estimator(
        args.pose_config,
        args.pose_checkpoint,
        device=args.device,
        cfg_options=dict(
            model=dict(test_cfg=dict(output_heatmaps=args.draw_heatmap))))

    # init visualizer
    pose_estimator.cfg.visualizer.radius = args.radius
    pose_estimator.cfg.visualizer.alpha = args.alpha
    pose_estimator.cfg.visualizer.line_width = args.thickness

    visualizer = VISUALIZERS.build(pose_estimator.cfg.visualizer)
    # the dataset_meta is loaded from the checkpoint and
    # then pass to the model in init_pose_estimator
    visualizer.set_dataset_meta(
        pose_estimator.dataset_meta, skeleton_style=args.skeleton_style)

    input_type = mimetypes.guess_type(args.input)[0].split('/')[0]
    if input_type == 'image':
        pred_instances = process_one_image(
            args,
            args.input,
            detector,
            pose_estimator,
            visualizer,
            show_interval=0)
        pred_instances_list = split_instances(pred_instances)

    elif input_type == 'video':
        tmp_folder = tempfile.TemporaryDirectory()
        video = mmcv.VideoReader(args.input)
        progressbar = mmengine.ProgressBar(len(video))
        video.cvt2frames(tmp_folder.name, show_progress=False)
        output_root = args.output_root
        args.output_root = tmp_folder.name
        pred_instances_list = []

        for frame_id, img_fname in enumerate(os.listdir(tmp_folder.name)):
            pred_instances = process_one_image(
                args,
                f'{tmp_folder.name}/{img_fname}',
                detector,
                pose_estimator,
                visualizer,
                show_interval=1)

            progressbar.update()
            pred_instances_list.append(
                dict(
                    frame_id=frame_id,
                    instances=split_instances(pred_instances)))

        if output_root:
            mmcv.frames2video(
                tmp_folder.name,
                f'{output_root}/{os.path.basename(args.input)}',
                fps=video.fps,
                fourcc='mp4v',
                show_progress=False)
        tmp_folder.cleanup()

    else:
        args.save_predictions = False
        raise ValueError(
            f'file {os.path.basename(args.input)} has invalid format.')

    if args.save_predictions:
        with open(args.pred_save_path, 'w') as f:
            json.dump(
                dict(
                    meta_info=pose_estimator.dataset_meta,
                    instance_info=pred_instances_list),
                f,
                indent='\t')
        print(f'predictions have been saved at {args.pred_save_path}')

if __name__ == '__main__':
    main()

### Reproduces the problem - command or script

python demo/topdown_demo_with_mmdet.py  mmdetection-3.0.0/configs/yolox/yolox_l_8xb8-300e_coco.py pthfile/yolox_det/yolox_l_8x8_300e_coco_20211126_140236-d3bd2b23.pth configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_hrnet-w32_8xb64-210e_coco-256x192.py pthfile/hrnet-heatmap/td-hm_hrnet-w32_8xb64-210e_coco-256x192-81c58e40_20220909.pth  --input tests/data/coco/000000197388.jpg --show --draw-heatmap --output-root vis_results

### Reproduces the problem - error message

When I enter the visual command, the program does not respond for a long time. This is the feedback after I manually stop the program. I suspect that there is a long delay time.

```
Loads checkpoint by local backend from path: pthfile/yolox_det/yolox_l_8x8_300e_coco_20211126_140236-d3bd2b23.pth
Loads checkpoint by local backend from path: pthfile/hrnet-heatmap/td-hm_hrnet-w32_8xb64-210e_coco-256x192-81c58e40_20220909.pth
The model and loaded state dict do not match exactly

unexpected key in source state_dict: data_preprocessor.mean, data_preprocessor.std

09/22 14:27:05 - mmengine - WARNING - `Visualizer` backend is not initialized because save_dir is None.
/home/keli/anaconda3/envs/mmpose/lib/python3.9/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3190.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/home/keli/anaconda3/envs/mmpose/lib/python3.9/site-packages/mmengine/visualization/visualizer.py:680: UserWarning: Warning: The circle is out of bounds, the drawn circle may not be in the image
  warnings.warn(
^CTraceback (most recent call last):
  File "/home/keli/pose/demo/topdown_demo_with_mmdet.py", line 249, in <module>
    main()
  File "/home/keli/pose/demo/topdown_demo_with_mmdet.py", line 190, in main
    pred_instances = process_one_image(
  File "/home/keli/pose/demo/topdown_demo_with_mmdet.py", line 50, in process_one_image
    visualizer.add_datasample(
  File "/home/keli/anaconda3/envs/mmpose/lib/python3.9/site-packages/mmengine/dist/utils.py", line 400, in wrapper
    return func(*args, **kwargs)
  File "/home/keli/pose/mmpose/visualization/local_visualizer.py", line 566, in add_datasample
    self.show(drawn_img, win_name=name, wait_time=wait_time)
  File "/home/keli/anaconda3/envs/mmpose/lib/python3.9/site-packages/mmengine/dist/utils.py", line 400, in wrapper
    return func(*args, **kwargs)
  File "/home/keli/anaconda3/envs/mmpose/lib/python3.9/site-packages/mmengine/visualization/visualizer.py", line 265, in show
    wait_continue(fig, timeout=wait_time, continue_key=continue_key)
  File "/home/keli/anaconda3/envs/mmpose/lib/python3.9/site-packages/mmengine/visualization/utils.py", line 219, in wait_continue
    figure.canvas.start_event_loop(timeout)  # type: ignore
  File "/home/keli/anaconda3/envs/mmpose/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2553, in start_event_loop
    time.sleep(timestep)
KeyboardInterrupt

```

### Additional information

The script `topdown_demo_with_mmdet.py` has no results after running for a long time, but `image_demo.py` and `inferencer_demo.py` work fine. I hope to use the heatmap visualization tool, but in the mmpose1.0 version `inferencer_demo.py` does not include heatmap visualization. , and in mmpose1.1 version, `inferencer_demo.py` cannot run properly. Hope to get your help!

**Comment by Ben-Louis** [comment]
You could try to remove `--show` argument in the command if you have no GUI

**Comment by da13132** [comment]
> You could try to remove `--show` argument in the command if you have no GUI

Thank you very much
