### ISSUE TITLE
[Bug] Visualisation of topdown_demo_with_mmdet

### ISSUE THREAD

**Issue by evabasa** [open-mmlab/mmpose#2718]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

As shown in the documentation, I'm trying to run the animal detection demo (topdown_demo_with_mmdet.py). The code is as follows:

  

### Reproduces the problem - code sample

`python demo/topdown_demo_with_mmdet.py \
    demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py \
    https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \
    configs/animal_2d_keypoint/topdown_heatmap/animalpose/td-hm_hrnet-w32_8xb64-210e_animalpose-256x256.py \
    https://download.openmmlab.com/mmpose/animal/hrnet/hrnet_w32_animalpose_256x256-1aa7f075_20210426.pth \
    --input path/of/video.mp4 \
    --output-root vis_result --draw-heatmap --det-cat-id=16`

### Reproduces the problem - command or script

`python demo/topdown_demo_with_mmdet.py \
    demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py \
    https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \
    configs/animal_2d_keypoint/topdown_heatmap/animalpose/td-hm_hrnet-w32_8xb64-210e_animalpose-256x256.py \
    https://download.openmmlab.com/mmpose/animal/hrnet/hrnet_w32_animalpose_256x256-1aa7f075_20210426.pth \
    --input path/of/video.mp4 \
    --output-root vis_result --draw-heatmap --det-cat-id=16`

### Reproduces the problem - error message

"Loads checkpoint by http backend from path: https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
Loads checkpoint by http backend from path: https://download.openmmlab.com/mmpose/animal/hrnet/hrnet_w32_animalpose_256x256-1aa7f075_20210426.pth
/usr/local/lib/python3.10/dist-packages/mmengine/visualization/visualizer.py:196: UserWarning: Failed to add <class 'mmengine.visualization.vis_backend.LocalVisBackend'>, please provide the `save_dir` argument.
  warnings.warn(f'Failed to add {vis_backend.__class__}, '

### Additional information

 I tried to put in the code a save_dir argument (--save_dir your/path) but then I had an error like this: "topdown_demo_with_mmdet.py: error: unrecognized arguments: --save_dir your/path"

**Comment by Ben-Louis** [comment]
This is a bug in mmengine version 0.8.3. To fix the error, upgrade to version 0.8.4.

**Comment by evabasa** [comment]
I worked the code to the Google Colab. I upgraded mmengine to version 0.8.4, but still I saw the same error about the visualization.

**Comment by Ben-Louis** [comment]
please use a specific image or video path instead of `path/of/video.mp4` as input.
