### ISSUE TITLE
[Bug] Demo doesn't work.

### ISSUE THREAD

**Issue by JANGRAEJO** [open-mmlab/mmpose#2722]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

**python -c "from mmpose.utils import collect_env; print(collect_env())"** 
OrderedDict([('sys.platform', 'linux'), ('Python', '3.8.18 (default, Sep 11 2023, 13:40:15) [GCC 11.2.0]'), ('CUDA available', True), ('numpy_random_seed', 2147483648), ('GPU 0,1', 'Quadro RTX 5000'), ('CUDA_HOME', '/usr/local/cuda'), ('NVCC', 'Cuda compilation tools, release 11.6, V11.6.112'), ('GCC', 'gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0'), ('PyTorch', '2.0.1'), ('PyTorch compiling details', 'PyTorch built with:\n  - GCC 9.3\n  - C++ Version: 201703\n  - Intel(R) oneAPI Math Kernel Library Version 2023.1-Product Build 20230303 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)\n  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n  - LAPACK is enabled (usually provided by MKL)\n  - NNPACK is enabled\n  - CPU capability usage: AVX2\n  - CUDA Runtime 11.8\n  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90;-gencode;arch=compute_37,code=compute_37\n  - CuDNN 8.7\n  - Magma 2.6.1\n  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, \n'), ('TorchVision', '0.15.2'), ('OpenCV', '4.8.0'), ('MMEngine', '0.8.5'), ('MMPose', '1.1.0+537bd8e')])

**pip list | grep mm**
comm                     0.1.2
mmcv                     2.0.1
mmdet                    3.1.0
mmengine                 0.8.5
mmpose                   1.1.0        /lana-local/mmpose

I installed everything and check my env, status. 
However, It doesn't work. could you solve this problem? I wanna use demo first and I am trying to use this tool for my research.
Thanks.
My bugs is as below:

python demo/image_demo.py tests/data/coco/000000000785.jpg td-hm_hrnet-w48_8xb32-210e_coco-256x192.py td-hm_hrnet-w48_8xb32-210e_coco-256x192-0e67c616_20220913.pth --out-file vis_results.jpg --draw-heatmap

Loads checkpoint by local backend from path: td-hm_hrnet-w48_8xb32-210e_coco-256x192-0e67c616_20220913.pth
The model and loaded state dict do not match exactly

unexpected key in source state_dict: data_preprocessor.mean, data_preprocessor.std

/lana-local/anaconda3/envs/jjo/lib/python3.8/site-packages/mmengine/visualization/visualizer.py:196: UserWarning: Failed to add <class 'mmengine.visualization.vis_backend.LocalVisBackend'>, please provide the `save_dir` argument.
  warnings.warn(f'Failed to add {vis_backend.__class__}, '

### Reproduces the problem - code sample

python demo/image_demo.py tests/data/coco/000000000785.jpg td-hm_hrnet-w48_8xb32-210e_coco-256x192.py td-hm_hrnet-w48_8xb32-210e_coco-256x192-0e67c616_20220913.pth --out-file vis_results.jpg --draw-heatmap

### Reproduces the problem - command or script

Loads checkpoint by local backend from path: td-hm_hrnet-w48_8xb32-210e_coco-256x192-0e67c616_20220913.pth
The model and loaded state dict do not match exactly

unexpected key in source state_dict: data_preprocessor.mean, data_preprocessor.std

/lana-local/anaconda3/envs/jjo/lib/python3.8/site-packages/mmengine/visualization/visualizer.py:196: UserWarning: Failed to add <class 'mmengine.visualization.vis_backend.LocalVisBackend'>, please provide the `save_dir` argument.
  warnings.warn(f'Failed to add {vis_backend.__class__}, '

### Reproduces the problem - error message

Loads checkpoint by local backend from path: td-hm_hrnet-w48_8xb32-210e_coco-256x192-0e67c616_20220913.pth
The model and loaded state dict do not match exactly

unexpected key in source state_dict: data_preprocessor.mean, data_preprocessor.std

/lana-local/anaconda3/envs/jjo/lib/python3.8/site-packages/mmengine/visualization/visualizer.py:196: UserWarning: Failed to add <class 'mmengine.visualization.vis_backend.LocalVisBackend'>, please provide the `save_dir` argument.
  warnings.warn(f'Failed to add {vis_backend.__class__}, '

**Comment by Ben-Louis** [comment]
Did the `vis_results.jpg` output file generate as expected?

**Comment by 505115220** [comment]
same problem，I check the video in bilibili and read the installation，it doesn't work

**Comment by Ben-Louis** [comment]
Hi @JANGRAEJO, I cannot reproduce this issue on my machine with the same environment. Does the program get stuck when displaying this warning or does it just exit?

**Comment by imlegend19** [comment]
@Ben-Louis I also faced this issue when trying to run the following demo script:

```python
from mmpose.apis import inference_topdown, init_model
from mmpose.utils import register_all_modules

register_all_modules()

config_file = "td-hm_hrnet-w48_8xb32-210e_coco-256x192.py"
checkpoint_file = "td-hm_hrnet-w48_8xb32-210e_coco-256x192-0e67c616_20220913.pth"
model = init_model(config_file, checkpoint_file, device="cpu")

# please prepare an image with person
results = inference_topdown(model, "demo.png")
```

Output:

```text
Loads checkpoint by local backend from path: td-hm_hrnet-w48_8xb32-210e_coco-256x192-0e67c616_20220913.pth
The model and loaded state dict do not match exactly

unexpected key in source state_dict: data_preprocessor.mean, data_preprocessor.std


Process finished with exit code 0
```

**Comment by Ben-Louis** [comment]
If you want to run inference on CPU, you can try using lightweight models like RTMPose-tiny.

**Comment by Hyanaki** [comment]
I am facing the same issue.
I also tried with td-hm_hrnet-w48_8xb32-210e_coco-384x288 and the same error occurs.
Any update concerning the situation?

**Comment by Ben-Louis** [comment]
Hello @Hyanaki, could you kindly provide more details about the error you encountered?

**Comment by Matthew1204** [comment]
/home/student/anaconda3/envs/mmpose/lib/python3.10/site-packages/mmengine/visualization/visualizer.py:196: UserWarning: Failed to add <class 'mmengine.visualization.vis_backend.TensorboardVisBackend'>, please provide the `save_dir` argument.
  warnings.warn(f'Failed to add {vis_backend.__class__}, '
  
  same problem

**Comment by Ben-Louis** [comment]
> /home/student/anaconda3/envs/mmpose/lib/python3.10/site-packages/mmengine/visualization/visualizer.py:196: UserWarning: Failed to add <class 'mmengine.visualization.vis_backend.TensorboardVisBackend'>, please provide the `save_dir` argument. warnings.warn(f'Failed to add {vis_backend.**class**}, '
> 
> same problem

Hi @Matthew1204, thank you for your feedback. This is a warning and should not affect the program's output. Can you please check if any output images were saved locally?

**Comment by Hyanaki** [comment]
> Hello @Hyanaki, could you kindly provide more details about the error you encountered?

Hello @Ben-Louis!
After confirmation, the program outputs the expecting result. 
However the displayed message in the console is a bit disturbing :

-------------------------------------------------------------------------------------------------------------------------------------
Loads checkpoint by local backend from path: checkpoints/rtmdet_x_8xb32-300e_coco_20220715_230555-cc79b9ae.pth
Loads checkpoint by local backend from path: checkpoints/td-hm_hrnet-w48_udp-8xb32-210e_coco-384x288-70d7ab01_20220913.pth
The model and loaded state dict do not match exactly

unexpected key in source state_dict: data_preprocessor.mean, data_preprocessor.std
-------------------------------------------------------------------------------------------------------------------------------------

From this "error・warning", I assume the preprocessing of the image doesn't occur. 
Any information about it ?

**Comment by Tau-J** [comment]
> > Hello @Hyanaki, could you kindly provide more details about the error you encountered?
> 
> Hello @Ben-Louis! After confirmation, the program outputs the expecting result. However the displayed message in the console is a bit disturbing :
> 
> Loads checkpoint by local backend from path: checkpoints/rtmdet_x_8xb32-300e_coco_20220715_230555-cc79b9ae.pth Loads checkpoint by local backend from path: checkpoints/td-hm_hrnet-w48_udp-8xb32-210e_coco-384x288-70d7ab01_20220913.pth The model and loaded state dict do not match exactly unexpected key in source state_dict: data_preprocessor.mean, data_preprocessor.std
> 
> From this error・warning, I assume the preprocessing of the image doesn't occur. Any information about it ?

This warning is caused by the compatibility process and is safe, so feel free to ignore it.
