### ISSUE TITLE
[Docs] Is there a pathway for hand 3d keypoints?

### ISSUE THREAD

**Issue by anorakthegreat** [open-mmlab/mmpose#2725]
### 📚 The doc issue

Hi! Looking through the docs, I see that there is something called MMPoseInferencer. While there are certain aliases, built in there is a custom version, to be built with custom config and pth files. I looked through the GitHub for hand 3d and found a link to some other page. Is there a tutorial / guide I can follow to turn that hand 3d link into something I can use with MMPoseInferencer?

Thanks!

**Comment by Tau-J** [comment]
Hi @anorakthegreat , thanks for using MMPose. `MMPoseInferencer` is a new feature of MMPose 1.x, yet hand 3d is not supported. We have migrated a 3d hand baseline, namely, InterNet, into MMPose 1.x, And We will support it in Inferencer soon.
