### ISSUE TITLE
[Docs] cannot find the `hand3d_internet_demo.py` file

### ISSUE THREAD

**Issue by Rickfdalton** [open-mmlab/mmpose#2730]
### 📚 cannot find the `hand3d_internet_demo.py` file

I cannot find the `hand3d_internet_demo.py` file from demos, I need to run a demo to check the 3d hand point estimation of the mmpose. Any help how can I proceed ?

**Comment by Tau-J** [comment]
Hi @Rickfdalton , you can find hand3d demo [here](https://github.com/open-mmlab/mmpose/blob/dev-1.x/demo/hand3d_internet_demo.py), which is in the `dev-1.x` branch. We will merge `dev-1.x` into `main` branch next week.

**Comment by Rickfdalton** [comment]
thanks. I got it
