### ISSUE TITLE
[Bug] Building a package that includes customised MMPose.

### ISSUE THREAD

**Issue by korneliaWatson** [open-mmlab/mmpose#2732]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

OrderedDict([('sys.platform', 'linux'), ('Python', '3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]'), ('CUDA available', False), ('numpy_random_seed', 2147483648), ('GCC', 'x86_64-linux-gnu-gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0'), ('PyTorch', '2.0.1+cu117'), ('PyTorch compiling details', 'PyTorch built with:\n  - GCC 9.3\n  - C++ Version: 201703\n  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)\n  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n  - LAPACK is enabled (usually provided by MKL)\n  - NNPACK is enabled\n  - CPU capability usage: AVX2\n  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, \n'), ('TorchVision', '0.15.2+cu117'), ('OpenCV', '4.8.0'), ('MMEngine', '0.8.4'), ('MMPose', '1.1.0+9e816a6')])

mmcv                     2.0.0
mmdeploy                 1.2.0
mmdeploy-runtime         1.2.0
mmdet                    3.1.0
mmengine                 0.8.4
mmpose                   1.1.0        /home/project/mmpose

### Reproduces the problem - code sample

hatchling build

### Reproduces the problem - command or script

```
hatchling build
```

### Reproduces the problem - error message

```
[wheel]
Traceback (most recent call last):
  File "/home/project/venv/bin/hatchling", line 8, in <module>
    sys.exit(hatchling())
  File "/home/project/venv/lib/python3.10/site-packages/hatchling/cli/__init__.py", line 26, in hatchling
    command(**kwargs)
  File "/home/project/venv/lib/python3.10/site-packages/hatchling/cli/build/__init__.py", line 75, in build_impl
    for artifact in builder.build(
  File "/home/project/venv/lib/python3.10/site-packages/hatchling/builders/plugin/interface.py", line 158, in build
    artifact = version_api[version](directory, **build_data)
  File "/home/project/venv/lib/python3.10/site-packages/hatchling/builders/wheel.py", line 371, in build_standard
    record = archive.add_file(included_file)
  File "/home/project/venv/lib/python3.10/site-packages/hatchling/builders/wheel.py", line 86, in add_file
    file_stat = os.stat(included_file.path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/project/src/mmpose/projects/yolox_pose/demo'
```

### Additional information

Hi, I trained MMPose on a custom keypoint detection task. The inference works fine. Now I want to package the code into a python library so that I can share it easily for inferencing with. I use hatchling to build the package. The build fails with `FileNotFoundError: [Errno 2] No such file or directory: '/home/project/src/mmpose/projects/yolox_pose/demo'` but the file exists. Any ideas how I should approach this issue/task?

**Comment by Ben-Louis** [comment]
`mmpose/projects/yolox_pose/demo` is a symbolic link to `mmpose/demo`. You can safely delete this link if it's not being used in your project.

**Comment by korneliaWatson** [comment]
Deleting whole `yolox_pose` worked. Thank you. :-)
