### ISSUE TITLE
[Bug] Webcam not opening when running inferencer

### ISSUE THREAD

**Issue by Rickfdalton** [open-mmlab/mmpose#2733]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

OrderedDict([('sys.platform', 'linux'), ('Python', '3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]'), ('CUDA available', False), ('numpy_random_seed', 2147483648), ('GCC', 'x86_64-linux-gnu-gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0'), ('PyTorch', '2.0.1+cu118'), ('PyTorch compiling details', 'PyTorch built with:\n  - GCC 9.3\n  - C++ Version: 201703\n  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)\n  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n  - LAPACK is enabled (usually provided by MKL)\n  - NNPACK is enabled\n  - CPU capability usage: AVX2\n  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, \n'), ('TorchVision', '0.15.2+cu118'), ('OpenCV', '4.8.0'), ('MMEngine', '0.8.5'), ('MMPose', '1.1.0+a7f7939')])

### Reproduces the problem - code sample

```
!python demo/inferencer_demo.py \
    webcam \
    --pose2d hand --vis-out-dir vis_results/testing \
    --bbox-thr 0.5 --kpt-thr 0.05
```

### Reproduces the problem - command or script

`!python demo/inferencer_demo.py \
    webcam \
    --pose2d hand --vis-out-dir vis_results/testing \
    --bbox-thr 0.5 --kpt-thr 0.05`

### Reproduces the problem - error message

```
Loads checkpoint by http backend from path: https://download.openmmlab.com/mmpose/v1/projects/rtmposev1/rtmpose-m_simcc-hand5_pt-aic-coco_210e-256x256-74fb594_20230320.pth
09/30 13:30:04 - mmengine - WARNING - Failed to search registry with scope "mmpose" in the "function" registry tree. As a workaround, the current "function" registry in "mmengine" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpose" is a correct scope, or whether the registry is initialized.
/usr/local/lib/python3.10/dist-packages/mmengine/visualization/visualizer.py:196: UserWarning: Failed to add <class 'mmengine.visualization.vis_backend.LocalVisBackend'>, please provide the `save_dir` argument.
  warnings.warn(f'Failed to add {vis_backend.__class__}, '
Loads checkpoint by http backend from path: https://download.openmmlab.com/mmpose/v1/projects/rtmposev1/rtmdet_nano_8xb32-300e_hand-267f9c8f.pth
/usr/local/lib/python3.10/dist-packages/mmdet/apis/det_inferencer.py:153: UserWarning: palette does not exist, random is used by default. You can also set the palette to customize.
  warnings.warn(
09/30 13:30:05 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "function" registry tree. As a workaround, the current "function" registry in "mmengine" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
/usr/local/lib/python3.10/dist-packages/mmengine/visualization/visualizer.py:196: UserWarning: Failed to add <class 'mmengine.visualization.vis_backend.LocalVisBackend'>, please provide the `save_dir` argument.
  warnings.warn(f'Failed to add {vis_backend.__class__}, '
[ WARN:0@8.686] global cap_v4l.cpp:982 open VIDEOIO(V4L2:/dev/video0): can't open camera by index
[ERROR:0@8.687] global obsensor_uvc_stream_channel.cpp:156 getStreamChannelGroup Camera index out of range
09/30 13:30:05 - mmengine - WARNING - Cannot open camera (ID=0)
/content/mmpose/mmpose/apis/inferencers/mmpose_inferencer.py:187: UserWarning: The display mode is closed when using webcam input. It will be turned on automatically.
  warnings.warn('The display mode is closed when using webcam '
```

**Comment by Ben-Louis** [comment]
I suggest determining the appropriate configuration for `cv2.VideoCapture` on your device first. It may be helpful to reference [this issue](https://github.com/opencv/opencv/issues/23425).

**Comment by Rickfdalton** [comment]
Do I need to explicitly open webcam using libraries like opencv? I though having the input parameter as webcam automatically opens the cam.

**Comment by Rickfdalton** [comment]
Even if I open the camera using libraries how can I pass the webcam data for a real-time processing of hand-pose estimation using mmpose

**Comment by Ben-Louis** [comment]
You could use `'webcam:{CAMERA_ID}'` as input for inferencer. This will involve `cv2.VideoCapture(CAMERA_ID)`

**Comment by Rickfdalton** [comment]
can you provide me an implementation example

**Comment by Rickfdalton** [comment]
I got it working locally. It was not working in colab. Any way the real-time processing was slow

**Comment by Ben-Louis** [comment]
The code runs on a server without accessing your camera when using Colab. To improve inference speed, consider using a GPU.
