### ISSUE TITLE
[Bug] Bad demo results of RTMW

### ISSUE THREAD

**Issue by lelexx** [open-mmlab/mmpose#2741]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

python -c "from mmpose.utils import collect_env; print(collect_env())"
OrderedDict([('sys.platform', 'linux'), ('Python', '3.9.0 (default, Nov 15 2020, 14:28:56) [GCC 7.3.0]'), ('CUDA available', True), ('numpy_random_seed', 2147483648), ('GPU 0,1,2,3', 'NVIDIA GeForce RTX 4090'), ('CUDA_HOME', '/usr/local/cuda'), ('NVCC', 'Cuda compilation tools, release 11.7, V11.7.99'), ('GCC', 'gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0'), ('PyTorch', '1.9.1+cu111'), ('PyTorch compiling details', 'PyTorch built with:\n  - GCC 7.3\n  - C++ Version: 201402\n  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)\n  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n  - NNPACK is enabled\n  - CPU capability usage: AVX2\n  - CUDA Runtime 11.1\n  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86\n  - CuDNN 8.0.5\n  - Magma 2.5.2\n  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, \n'), ('TorchVision', '0.10.1+cu111'), ('OpenCV', '4.8.0'), ('MMEngine', '0.8.4'), ('MMPose', '1.1.0+')])

pip list | grep mm
mmcv                    2.0.1
mmdet                   3.1.0
mmengine                0.8.4
mmpose                  1.1.0                
smmap                   5.0.1

### Reproduces the problem - code sample

![image](https://github.com/open-mmlab/mmpose/assets/48544069/3dc1d553-2e1d-4783-ac81-5e8d8469429b)

### Reproduces the problem - command or script

#!/bin/bash

cd demo
img=/amax/3D/test_model/0029.png
cfg=/amax/3D/mmpose/projects/rtmpose/rtmpose/wholebody_2d_keypoint/rtmw-x_8xb320-270e_cocktail13-384x288.py
checkpoint=/amax/3D/pretrained_models/rtmw-x_simcc-cocktail13_pt-ucoco_270e-384x288-0949e3a9_20230925.pth

outdir=/3D/mmpose/output/1.jpg
python image_demo.py   $img  $cfg  $checkpoint --out-file $outdir

### Reproduces the problem - error message

<img width="486" alt="3078524ade4d61d42355e3d224ac4f7" src="https://github.com/open-mmlab/mmpose/assets/48544069/de5d9dd5-2bf9-4a70-bc76-e376d54cf2f9">

The left is the result of DWPose, the right is the result of RTMW,

**Comment by Tau-J** [comment]
Hi @lelexx , thanks for using MMPose. Could you please share the test image to let me have a check?

**Comment by lelexx** [comment]
![0029](https://github.com/open-mmlab/mmpose/assets/48544069/c754886b-4ce4-4f0a-9062-58d83ec960a8)

**Comment by lelexx** [comment]
![0029](https://github.com/open-mmlab/mmpose/assets/48544069/d40457d6-08e2-4a13-8695-746728d4e3d3)
What I gave you is the original picture. The input to the model is actually the cropped image. Even if the input to the model is the original uncropped picture, the hand pose will be inaccurate, but the results of the body joints will not be so bad.

**Comment by lelexx** [comment]
<img width="888" alt="1696856028572" src="https://github.com/open-mmlab/mmpose/assets/48544069/014d5d54-fde6-49dc-ad57-7650364e321d">
![test](https://github.com/open-mmlab/mmpose/assets/48544069/5f58f7a7-e70a-4c0c-85e0-b97638677055)

This is the result of topdown_demo_with_mmdet.py.

**Comment by Tau-J** [comment]
Sorry for late reply. You can modify [this line](https://github.com/open-mmlab/mmpose/blob/6d10b2ec81da7e252016b3154c7fdb46c403ecd8/projects/rtmpose/rtmpose/wholebody_2d_keypoint/rtmw-x_8xb320-270e_cocktail13-384x288.py#L131), namely, replace `act_fn=SiLU` with `act_fn='SiLU'` in `gau_cfg` to fix it.
For details you can refer to https://github.com/open-mmlab/mmpose/pull/2754

Thanks for your feedback.
