### ISSUE TITLE
[Docs] https://mmpose.readthedocs.io/zh_CN/dev-1.x/installation.html#id7

### ISSUE THREAD

**Issue by zzmbhm** [open-mmlab/mmpose#2745]
### 📚 The doc issue

按照步骤执行：
pip install -U openmim
mim install mmengine
mim install "mmcv>=2.0.1"
mim install "mmdet>=3.1.0"
git clone https://github.com/open-mmlab/mmpose.git
cd mmpose
pip install -r requirements.txt
pip install -v -e .
mim download mmpose --config td-hm_hrnet-w48_8xb32-210e_coco-256x192  --dest .

如果执行python demo/image_demo.py，会报错：
UserWarning: Failed to add <class 'mmengine.visualization.vis_backend.LocalVisBackend'>, please provide the `save_dir` argument.

如果执行from mmpose.apis import inference_topdown, init_model
from mmpose.utils import register_all_modules
register_all_modules()
config_file = 'td-hm_hrnet-w48_8xb32-210e_coco-256x192.py'
checkpoint_file = 'td-hm_hrnet-w48_8xb32-210e_coco-256x192-0e67c616_20220913.pth'
model = init_model(config_file, checkpoint_file, device='cpu')  # or device='cuda:0'
results = inference_topdown(model, 'demo.jpg')
会报错：
Loads checkpoint by local backend from path: td-hm_hrnet-w48_8xb32-210e_coco-256x192-0e67c616_20220913.pth
The model and loaded state dict do not match exactly

我的email:zzmbhm@163.com

**Comment by Ben-Louis** [comment]
Hi @zzmbhm, thanks for the feedback. These warnings are harmless and won't affect program outputs. You can safely ignore them. We're working on fixing them for the next version.

**Comment by mask-code** [comment]
可是这样就没法运行demo了
