### ISSUE TITLE
[Feature] How yolox plots heat maps of test results

### ISSUE THREAD

**Issue by WinnerMeat** [open-mmlab/mmpose#2749]
### What is the feature?

Currently it is possible to use MMPoseInferencer to plot the key point information of the detection results, but when I want to plot the corresponding heat map, I fail to do so, the main reason is that the pred_fields field is missing from the predicted results. I would like to know how to implement heat mapping on YOLOx model, thanks.

**Comment by Ben-Louis** [comment]
YOLOX-Pose is a regression-based algorithm, so it does not generate heatmaps during inference.

**Comment by WinnerMeat** [comment]
@Ben-Louis Is there a way to generate a corresponding pre_fields based on pre_keypoints in mmpose?
