### ISSUE TITLE
The keypoint scores predicted by rtmpose are bigger than 1

### ISSUE THREAD

**Issue by kdavidlp123** [open-mmlab/mmpose#2755]
### 📚 The doc issue

I referred to the issue #884 but I did not know whether it is possible to restrict the confidence scores between [0,1] in "SimCCLabel type"

**Comment by Ben-Louis** [comment]
You may need to apply softmax on `simcc_x` and `simcc_y` before [this line](https://github.com/open-mmlab/mmpose/blob/6d10b2ec81da7e252016b3154c7fdb46c403ecd8/mmpose/codecs/simcc_label.py#L162C47-L162C54)
