### ISSUE TITLE
[Bug] RTMW's predicted results for the foot are unsatisfactory

### ISSUE THREAD

**Issue by lelexx** [open-mmlab/mmpose#2759]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

none

### Reproduces the problem - code sample

none

### Reproduces the problem - command or script

none

### Reproduces the problem - error message

The following are the results of [model online](https://openxlab.org.cn/apps/detail/mmpose/RTMPose). The first video displays the results from RTMW, while the second video shows the results from DWPose. Why is the foot pose predicted by RTMW performing so poorly?

https://github.com/open-mmlab/mmpose/assets/48544069/0f4ffa94-f9c2-412c-b14f-3b730f019d33

https://github.com/open-mmlab/mmpose/assets/48544069/471c83e7-d5cd-4cd8-9589-7f792078d2fb

**Comment by Tau-J** [comment]
Hi @lelexx , this error may be caused by a bug in data mixing, we will fix it soon. Thanks for your feedback.
