### ISSUE TITLE
AssertionError: `pose_lift_dataset` should be `h36m`, but got coco. 

### ISSUE THREAD

**Issue by faisalshahbaz** [open-mmlab/mmpose#2765]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

AssertionError: `pose_lift_dataset` should be `h36m`, but got coco. 

### Reproduces the problem - code sample

AssertionError: `pose_lift_dataset` should be `h36m`, but got coco. 

### Reproduces the problem - command or script

AssertionError: `pose_lift_dataset` should be `h36m`, but got coco. 

### Reproduces the problem - error message

AssertionError: `pose_lift_dataset` should be `h36m`, but got coco.

**Comment by Ben-Louis** [comment]
Hi, please provide the information prompted in the issue template. This will help developers understand your question

**Comment by XuanAo1016** [comment]
Hey~ I think I got the same error.
And error message as follows
(pose) mmpose>python demo/inferencer_demo.py webcam --pose3d human --show --black-background
Loads checkpoint by http backend from path: https://download.openmmlab.com/mmpose/v1/projects/rtmposev1/rtmpose-m_simcc-body7_pt-body7_420e-256x192-e48f03d0_20230504.pth
11/24 15:36:29 - mmengine - WARNING - Failed to search registry with scope "mmpose" in the "function" registry tree. As a workaround, the current "function" registry in "mmengine" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpose" is a correct scope, or whether the registry is initialized.
Loads checkpoint by http backend from path: https://download.openmmlab.com/mmpose/v1/projects/rtmposev1/rtmpose-m_simcc-body7_pt-body7_420e-256x192-e48f03d0_20230504.pth
Loads checkpoint by http backend from path: https://download.openmmlab.com/mmdetection/v3.0/rtmdet/rtmdet_m_8xb32-300e_coco/rtmdet_m_8xb32-300e_coco_20220719_112220-229f527c.pth
The model and loaded state dict do not match exactly

unexpected key in source state_dict: data_preprocessor.mean, data_preprocessor.std

11/24 15:36:30 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "function" registry tree. As a workaround, the current "function" registry in "mmengine" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
C:\Users\sunma\miniconda3\envs\pose\Lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release,
it will be required to pass the indexing argument. (Triggered internally at
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\TensorShape.cpp:3527.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Inference ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Traceback (most recent call last):
  File "C:\Users\sunma\Desktop\pose\mmpose\demo\inferencer_demo.py", line 193, in <module>
    main()
  File "C:\Users\sunma\Desktop\pose\mmpose\demo\inferencer_demo.py", line 188, in main
    for _ in inferencer(**call_args):
  File "C:\Users\sunma\miniconda3\envs\pose\Lib\site-packages\mmpose\apis\inferencers\mmpose_inferencer.py", line 205, in __call__
    for proc_inputs, ori_inputs in inputs:
  File "C:\Users\sunma\miniconda3\envs\pose\Lib\site-packages\mmpose\apis\inferencers\mmpose_inferencer.py", line 114, in preprocess
    data_infos = self.inferencer.preprocess_single(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunma\miniconda3\envs\pose\Lib\site-packages\mmpose\apis\inferencers\pose3d_inferencer.py", line 217, in preprocess_single
    ds.pred_instances.keypoints = self._keypoint_converter(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunma\miniconda3\envs\pose\Lib\site-packages\mmpose\apis\inference_3d.py", line 25, in convert_keypoint_definition
    assert pose_lift_dataset in [
           ^^^^^^^^^^^^^^^^^^^^^^
AssertionError: `pose_lift_dataset` should be `h36m`, but got coco.

**Comment by SpisakJ** [comment]
I had this assertion error when i changed the MMPoseInferencer from human3d to human without changing the parameter name from pose3d to pose2d.
