### ISSUE TITLE
[Bug] KeyError: 'mmcls.VisionTransformer is not in the mmpose::model registry. while trying to run ViTPose pretrained on Human-Art

### ISSUE THREAD

**Issue by julkaztwittera** [open-mmlab/mmpose#2768]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

OrderedDict([('sys.platform', 'linux'), ('Python', '3.9.16 (main, May 29 2023, 00:00:00) [GCC 11.3.1 20221121 (Red Hat 11.3.1-4)]'), ('CUDA available', False), ('numpy_random_seed', 2147483648), ('GCC', 'gcc (GCC) 10.3.0'), ('PyTorch', '1.12.1+cu113'), ('PyTorch compiling details', 'PyTorch built with:\n  - GCC 9.3\n  - C++ Version: 201402\n  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)\n  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n  - LAPACK is enabled (usually provided by MKL)\n  - NNPACK is enabled\n  - CPU capability usage: AVX2\n  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, \n'), ('TorchVision', '0.13.1+cu113'), ('OpenCV', '4.8.1'), ('MMEngine', '0.9.0'), ('MMPose', '1.2.0+6d10b2e')])

mmcv                    2.0.1
mmdet                   3.1.0
mmengine                0.9.0
mmpose                  1.1.0
mmpretrain              1.1.0

### Reproduces the problem - code sample

```
from mmpose.apis import init_model as init_pose_estimator

pose_config = "mmpose/configs/body_2d_keypoint/topdown_heatmap/humanart/td-hm_ViTPose-huge_8xb64-210e_humanart-256x192.py"
pose_checkpoint = "mmpose/checkpoints/td-hm_ViTPose-huge_8xb64-210e_humanart-256x192-603bb573_20230612.pth"

cfg_options = dict(model=dict(test_cfg=dict(output_heatmaps=True)))
pose_estimator = init_pose_estimator(
    pose_config, pose_checkpoint, device=device, cfg_options=cfg_options
)
```

### Reproduces the problem - command or script

`python init_model.py`

### Reproduces the problem - error message

```
mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'mmcls.VisionTransformer is not in the mmpose::model registry. Please check whether the value of `mmcls.VisionTransformer` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'
```

### Additional information

I tried to initialize ViTPose model pretrained on Human-Art dataset, but I got this error.

**Comment by aleeyang** [comment]
try
`pip install -U openmim && mim install "mmpretrain>=1.0.0rc8" `

**Comment by tamaskaracsony** [comment]
In your config file 

`pose_config = "mmpose/configs/body_2d_keypoint/topdown_heatmap/humanart/td-hm_ViTPose-huge_8xb64-210e_humanart-256x192.py`

it should be on line 61-63

```
    backbone=dict(
        type='mmpretrain.VisionTransformer',
        arch='huge',
```

instead of 

```
 backbone=dict(
        type='mmcls.VisionTransformer',
        arch='huge',
```

**Comment by julkaztwittera** [comment]
Thank you, @tamaskaracsony, it helped!

**Comment by Kebii** [comment]
I meet an error TypeError when trying to run ViTPose with Human-Art:

```
Traceback (most recent call last):
  File "demo/humanart_demo.py", line 7, in <module>
    inferencer = MMPoseInferencer('td-hm_ViTPose-huge_8xb64-210e_humanart-256x192')
  File "/data/midjourney/zhangjiaxu/code/mmpose/mmpose/apis/inferencers/mmpose_inferencer.py", line 100, in __init__
    self.inferencer = Pose2DInferencer(pose2d, pose2d_weights, device,
  File "/data/midjourney/zhangjiaxu/code/mmpose/mmpose/apis/inferencers/pose2d_inferencer.py", line 86, in __init__
    super().__init__(
  File "/data/midjourney/zhangjiaxu/code/mmpose/mmpose/apis/inferencers/base_mmpose_inferencer.py", line 64, in __init__
    super().__init__(
  File "/root/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/infer/infer.py", line 180, in __init__
    self.model = self._init_model(cfg, weights, device)  # type: ignore
  File "/root/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/infer/infer.py", line 483, in _init_model
    model = MODELS.build(cfg.model)
  File "/root/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/root/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/root/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/data/midjourney/zhangjiaxu/code/mmpose/mmpose/models/pose_estimators/topdown.py", line 47, in __init__
    super().__init__(
  File "/data/midjourney/zhangjiaxu/code/mmpose/mmpose/models/pose_estimators/base.py", line 53, in __init__
    self.backbone = MODELS.build(backbone)
  File "/root/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/root/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/root/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
TypeError: __init__() got an unexpected keyword argument 'output_cls_token'
```

 if anyone can help me?

**Comment by ajoseph28** [comment]
> TypeError: __init__() got an unexpected keyword argument 'output_cls_token'

Were you ever able to fix this?

**Comment by wubowen416** [comment]
> > TypeError: **init**() got an unexpected keyword argument 'output_cls_token'
> 
> Were you ever able to fix this?

I changed the config as follows:
```python
    backbone=dict(
        type='mmpretrain.VisionTransformer',
        ...
        out_type='featmap',
        # output_cls_token=False,
        ...
```
