### ISSUE TITLE
[Docs] how to do silent infer with MMPoseInferencer

### ISSUE THREAD

**Issue by jonbakerfish** [open-mmlab/mmpose#2775]
### 📚 The doc issue

Is there an option to disable the terminal output (the text and color bar) of MMPoseInferencer during inferencing?

**Comment by Ben-Louis** [comment]
At the moment, we don't offer the ability to hide the color bar. However, we plan to include this feature in the next version. BTW, could you please elaborate on why you'd like to hide the text output?

**Comment by jonbakerfish** [comment]
> At the moment, we don't offer the ability to hide the color bar. However, we plan to include this feature in the next version. BTW, could you please elaborate on why you'd like to hide the text output?

Thanks for the reply @Ben-Louis. When using mmpose as a component, the text output will interfere with other system logs. Could you show me the code where the outputs are generated so that I can temporarily fix it?

**Comment by jeremiasbaur** [comment]
I would also like to know where I can turn off the inference bar in the code.

**Comment by Ben-Louis** [comment]
The `dev-1.x` branch now supports turning off the inferencer bar, which is off by default.
