### ISSUE TITLE
[Bug] Wrong Heatmap and keypoints output

### ISSUE THREAD

**Issue by aleeyang** [open-mmlab/mmpose#2780]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

mmcv                   2.0.1
mmdet                  3.2.0
mmengine               0.9.0
mmpose                 1.2.0      
mmpretrain             1.1.0

### Reproduces the problem - code sample

`python demo/topdown_demo_with_mmdet.py \
    demo/mmdetection_cfg/rtmdet_m_640-8xb32_coco-person.py \
    https://download.openmmlab.com/mmpose/v1/projects/rtmpose/rtmdet_m_8xb32-100e_coco-obj365-person-235e8209.pth \
    configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_ViTPose-huge-simple_8xb64-210e_coco-256x192.py \
    https://download.openmmlab.com/mmpose/v1/pretrained_models/mae_pretrain_vit_huge_20230913.pth \
    --input tests/data/coco/000000000785.jpg  --draw-heatmap \
    --output-root vis_results/`

### Reproduces the problem - command or script

`python demo/topdown_demo_with_mmdet.py \
    demo/mmdetection_cfg/rtmdet_m_640-8xb32_coco-person.py \
    https://download.openmmlab.com/mmpose/v1/projects/rtmpose/rtmdet_m_8xb32-100e_coco-obj365-person-235e8209.pth \
    configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_ViTPose-huge-simple_8xb64-210e_coco-256x192.py \
    https://download.openmmlab.com/mmpose/v1/pretrained_models/mae_pretrain_vit_huge_20230913.pth \
    --input tests/data/coco/000000000785.jpg  --draw-heatmap \
    --output-root vis_results/`

### Reproduces the problem - error message

The output heatmap look bad and keypoints are not correct
![000000000785](https://github.com/open-mmlab/mmpose/assets/54769687/a3bae9a5-45a8-4899-9b36-72d938bc5f04)

**Comment by Ben-Louis** [comment]
Hi, thank you for using MMPose. For accurate pose estimation, make sure to download the checkpoint from the 'ckpt' link provided in our [modelzoo](https://mmpose.readthedocs.io/en/latest/model_zoo/body_2d_keypoint.html#topdown-heatmap-vitpose-on-coco). The checkpoint you're currently using, named 'mae_pretrain_vit_huge_20230913.pth,' is only pretrained on ImageNet and is not optimized for pose estimation.

**Comment by aleeyang** [comment]
Thank you so much! The problem has been solved!
