### ISSUE TITLE
[question] calculate rotation of the head?

### ISSUE THREAD

**Issue by klvnptr** [open-mmlab/mmpose#2783]
### What is the feature?

Hello. Is there any way to calculate the rotation of the head from the keypoints? Thank you. Peter

**Comment by Ben-Louis** [comment]
Maybe you can refer to [3DDFA](https://github.com/cleardusk/3DDFA_V2)

**Comment by klvnptr** [comment]
thank you @Ben-Louis i thought there were already similar functionality in mmpose. is there any way to solve this problem without 3DDFA ? thank you.
