### ISSUE TITLE
During the data visualization process, key point information cannot be found based on bbox.

### ISSUE THREAD

**Issue by SicongLiu998** [open-mmlab/mmpose#2784]
@Ben-Louis  Thanks a lot for your guidance and help！ 
We have finished the visualization part. We actually find a problem.  
When choosing not to use detection files, the visualization results are normal. But there was a problem when choosing to use the detection file, and only the bbox was visible in the visualization results without key point information. 

<img width="784" alt="图片" src="https://github.com/open-mmlab/mmpose/assets/65213342/59933985-beef-4c77-b179-94d202db7622">

<img width="824" alt="图片" src="https://github.com/open-mmlab/mmpose/assets/65213342/4ddb1b73-af32-4285-9dae-ee692f734145">
We speculate that perhaps the key point information did not match the bbox information. It should be this mismatch that caused the final test results to be abnormal. 

The normal display of bbox information in the image indicates that our bbox matches the image. The problem may be that the framework cannot effectively match key point information with bbox information.

_Originally posted by @SicongLiu998 in https://github.com/open-mmlab/mmpose/issues/2769#issuecomment-1782418103_

**Comment by Ben-Louis** [comment]
Generally, `bbox_file` does not include information about keypoints

**Comment by SicongLiu998** [comment]
Thanks for your reply and help. The bbox_file actually does not include key points information. The visualization part is normal. When it comes to issue  #2769（ https://github.com/open-mmlab/mmpose/issues/2769 ）, the bbox_file is correct and there may be some errors or bugs in metric computation. @Tau-J @Ben-Louis
