### ISSUE TITLE
[Bug] rtmpose全身关键点模型在tensorrt环境下效果明显变差

### ISSUE THREAD

**Issue by liangzhenghao2000** [open-mmlab/mmpose#2789]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

我是先用mmdeploy将pth模型转onnx，然后用trtexec把onnx转trt的，这样我发现检测结果精度损失很大，尤其在手指上，经常伸不直。

platform: win11
CUDA: 11.7
tensorrt: 8.6.1.6
mmcv: 2.1.0
mmdet: 3.2.0
mmpose: 1.2.0
model: rtmpose-l_simcc-ucoco_dw-ucoco_270e-384x288

### Reproduces the problem - code sample

。

### Reproduces the problem - command or script

pth运行脚本：
python demo/topdown_demo_with_mmdet.py  ../mmdetection/configs/rtmdet/rtmdet_tiny_8xb32-300e_coco.py  ../mmdetection/checkpoints/rtmdet_tiny_8xb32-300e_coco_20220902_112414-78e30dcc.pth  configs/wholebody_2d_keypoint/rtmpose/ubody/rtmpose-l_8xb32-270e_coco-ubody-wholebody-384x288.py  checkpoints/rtpython demo/topdown_demo_with_mmdet.py  ../mmdetection/configs/rtmdet/rtmdet_tiny_8xb32-300e_coco.py  ../mmdetection/checkpoints/rtmdet_tiny_8xb32-300e_coco_20220902_112414-78e30dcc.pth  configs/wholebody_2d_keypoint/rtmpose/ubody/rtmpose-l_8xb32-270e_coco-ubody-wholebody-384x288.py  checkpoints/rtmpose-l_simcc-ucoco_dw-ucpython demo/topdown_demo_with_mmdet.py  ../mmdetection/configs/rtmdet/rtmdet_tiny_8xb32-300e_coco.py  ../mmdetection/checkpoints/rtmdet_tiny_8xb32-300e_coco_20220902_112414-78e30dcc.pth  configs/wholebody_2d_keypoint/rtmpose/ubody/rtmpose-l_8xb32-270e_coco-ubody-wholebody-384x288.py  checkpoints/rtmpose-l_simcc-ucoco_dw-ucpython demo/topdown_demo_with_mmdet.py  ../mmdetection/configs/rtmdet/rtmdet_tiny_8xb32-300e_coco.py  ../mmdetection/checkpoints/rtmdet_tiny_8xb32-300e_coco_20220902_112414-78e30dcc.pth  configs/wholebody_2d_keypoint/rtmpose/ubody/rtmpose-l_8xb32-270e_coco-ubody-wholebody-384x288.py  checkpoints/rtmpose-l_simcc-ucoco_dw-ucoco_270e-384x288-2438fd99_20230728.pth   --input webcam     --device cuda:0       --bbox-thr 0.6        --kpt-thr 0.5         --nms-thr 0.3        --radius 2        --thickness 1        --draw-bbox   --show

tensorrt运行方式：官方c++运行代码

### Reproduces the problem - error message

。

**Comment by Tau-J** [comment]
@liangzhenghao2000 你好，导出trt并不会导致模型精度损失，可能导致结果跟pytorch推理不同的原因有：
1. pytorch 脚本推理默认开启了 flip-test TTA 增强，这会给模型带来接近 1 AP 的精度提升
2. pose 模型的输入应该是 bbox 框外扩 1.25 倍后裁剪出来的人体，导出trt后这部分预处理需要用户自己手动实现

**Comment by liangzhenghao2000** [comment]
> @liangzhenghao2000 你好，导出trt并不会导致模型精度损失，可能导致结果跟pytorch推理不同的原因有：
> 
> 1. pytorch 脚本推理默认开启了 flip-test TTA 增强，这会给模型带来接近 1 AP 的精度提升
> 2. pose 模型的输入应该是 bbox 框外扩 1.25 倍后裁剪出来的人体，导出trt后这部分预处理需要用户自己手动实现

这两个问题我都检查了，并不是这两个的原因。我想问下用mmdeploy转trt和用trtexec转区别大吗？会不会是因为mmpose自己实现了一些算子？

**Comment by Tau-J** [comment]
> > @liangzhenghao2000 你好，导出trt并不会导致模型精度损失，可能导致结果跟pytorch推理不同的原因有：
> > 
> > 1. pytorch 脚本推理默认开启了 flip-test TTA 增强，这会给模型带来接近 1 AP 的精度提升
> > 2. pose 模型的输入应该是 bbox 框外扩 1.25 倍后裁剪出来的人体，导出trt后这部分预处理需要用户自己手动实现
> 
> 这两个问题我都检查了，并不是这两个的原因。我想问下用mmdeploy转trt和用trtexec转区别大吗？会不会是因为mmpose自己实现了一些算子？

在 RTMPose 的导出里 mmdeploy 和 trtexec 应该是没有区别的，也不存在自己实现的算子。社区用户两种导出途径都有尝试过并且都能得到正确结果。或许你可以尝试一下mmdeploy导出，如果能定位到具体的原因是算法库本身的问题，欢迎反馈给我们。
