### ISSUE TITLE
[Bug] Cannot load pre-trained model with mmengine_hub.get_model()

### ISSUE THREAD

**Issue by liming-ai** [open-mmlab/mmpose#2790]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

OrderedDict([('sys.platform', 'linux'), ('Python', '3.10.0 (default, Mar  3 2022, 09:58:08) [GCC 7.5.0]'), ('CUDA available', True), ('numpy_random_seed', 2147483648), ('GPU 0,1,2,3', 'NVIDIA RTX A5000'), ('CUDA_HOME', '/usr'), ('NVCC', 'Cuda compilation tools, release 11.1, V11.1.105'), ('GCC', 'gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0'), ('PyTorch', '2.0.1'), ('PyTorch compiling details', 'PyTorch built with:\n  - GCC 9.3\n  - C++ Version: 201703\n  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)\n  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n  - LAPACK is enabled (usually provided by MKL)\n  - NNPACK is enabled\n  - CPU capability usage: AVX2\n  - CUDA Runtime 11.8\n  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90;-gencode;arch=compute_37,code=compute_37\n  - CuDNN 8.7\n  - Magma 2.6.1\n  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, \n'), ('TorchVision', '0.15.2'), ('OpenCV', '4.8.1'), ('MMEngine', '0.8.4'), ('MMPose', '1.2.0+515e53e')])

### Reproduces the problem - code sample
Hi @Tau-J 

Adding `pretrained=True` leads to error

```python
from mmengine.hub import get_model

model = get_model('mmpose::body_2d_keypoint/topdown_heatmap/humanart/td-hm_hrnet-w48_8xb32-210e_humanart-256x192.py', pretrained=True)
```

### Reproduces the problem - command or script

Just run the python commands in Linux

### Reproduces the problem - error message

```
Traceback (most recent call last):
  File "/home/chenchen/anaconda3/envs/reward_control/lib/python3.10/site-packages/mmengine/config/config.py", line 106, in __getattr__
    value = super().__getattr__(name)
  File "/home/chenchen/anaconda3/envs/reward_control/lib/python3.10/site-packages/addict/addict.py", line 67, in __getattr__
    return self.__getitem__(item)
  File "/home/chenchen/anaconda3/envs/reward_control/lib/python3.10/site-packages/mmengine/config/config.py", line 135, in __getitem__
    return self.build_lazy(super().__getitem__(key))
  File "/home/chenchen/anaconda3/envs/reward_control/lib/python3.10/site-packages/mmengine/config/config.py", line 102, in __missing__
    raise KeyError(name)
KeyError: 'model_path'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chenchen/anaconda3/envs/reward_control/lib/python3.10/site-packages/mmengine/hub/hub.py", line 84, in get_model
    load_checkpoint(model, cfg.model_path)
  File "/home/chenchen/anaconda3/envs/reward_control/lib/python3.10/site-packages/mmengine/config/config.py", line 1489, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/chenchen/anaconda3/envs/reward_control/lib/python3.10/site-packages/mmengine/config/config.py", line 110, in __getattr__
    raise AttributeError(f"'{self.__class__.__name__}' object has no "
AttributeError: 'ConfigDict' object has no attribute 'model_path'
```

**Comment by Ben-Louis** [comment]
Please add `configs/body_2d_keypoint/topdown_heatmap/humanart/hrnet_humanart.yml` in `model-index.yml`. We will fix this problem in the next version

**Comment by liming-ai** [comment]
> Please add `configs/body_2d_keypoint/topdown_heatmap/humanart/hrnet_humanart.yml` in `model-index.yml`. We will fix this problem in the next version

Thanks for your quick reply. Could you be more specific?

**Comment by Ben-Louis** [comment]
If you install mmpose via pip, you can obtain model through
```python
from mmpose.apis import init_pose_model
config = 'xxx'
checkpoint = 'xxx'
model = init_pose_model(config, checkpoint)
```

**Comment by liming-ai** [comment]
> If you install mmpose via pip, you can obtain model through
> 
> ```python
> from mmpose.apis import init_model
> config = 'xxx'
> checkpoint = 'xxx'
> model = init_model(config, checkpoint)
> ```

Thanks for your help!
