### ISSUE TITLE
3Dhuman pose 运行不了

### ISSUE THREAD

**Issue by LZhen624** [open-mmlab/mmpose#2792]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

按照同济子豪兄的mmpose教程配置的

### Reproduces the problem - code sample

!python  demo/body3d_pose_lifter_demo.py  \
demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py \
https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth  \
configs/body_2d_keypoint/topdown_heatmap/posetrack18/td-hm_hrnet-w48_8xb64-20e_posetrack18-384x288.py \
https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_posetrack18_384x288-5fd6d3ff_20211130.pth  \
configs/body_3d_keypoint/video_pose_lift/h36m/video-pose-lift_tcn-243frm-supv-cpn-ft_8xb128-200e_h36m.py \
https://download.openmmlab.com/mmpose/body3d/videopose/videopose_h36m_243frames_fullconv_supervised_cpn_ft-88f5abbb_20210527.pth  \
--input data/two_dancers.mp4 \
--output-root  outputs  \
 # --rebase-keypoint
    # --use-multi-frames --online

### Reproduces the problem - command or script

!python  demo/body3d_pose_lifter_demo.py  \
demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py \
https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth  \
configs/body_2d_keypoint/topdown_heatmap/posetrack18/td-hm_hrnet-w48_8xb64-20e_posetrack18-384x288.py \
https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_posetrack18_384x288-5fd6d3ff_20211130.pth  \
configs/body_3d_keypoint/video_pose_lift/h36m/video-pose-lift_tcn-243frm-supv-cpn-ft_8xb128-200e_h36m.py \
https://download.openmmlab.com/mmpose/body3d/videopose/videopose_h36m_243frames_fullconv_supervised_cpn_ft-88f5abbb_20210527.pth  \
--input data/two_dancers.mp4 \
--output-root  outputs  \
 # --rebase-keypoint
    # --use-multi-frames --online

### Reproduces the problem - error message

我想用mmpose 的3Dhuman pose来推理一下视频中的人物关键点，可是一直都不行

### Additional information

想要对视频进行3Dhuman pose

**Comment by Ben-Louis** [comment]
您好，请问可以提供一下您使用的 mmpose 版本以及具体的报错信息吗？

**Comment by LZhen624** [comment]
在现在最新版的mmpose包中的main，是不是对mmpose的版本有要求，我要用它做3D的人体姿态估计，就是做不了

**Comment by LZhen624** [comment]
我是根据了子豪兄去年的那个视频“MMpose代码实战 ”里面的代码，但是应该他的版本比较久了吧，我也是在云服务器上做的，我的mmpose版本应该是1.多的

**Comment by LZhen624** [comment]
mmcv是2.1.0版本的，mmpose是1.2.0版本的

**Comment by LZhen624** [comment]
!python demo/body3d_pose_lifter_demo.py \
demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py \
https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \
configs/body_2d_keypoint/topdown_heatmap/posetrack18/td-hm_hrnet-w48_8xb64-20e_posetrack18-384x288.py \
https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_posetrack18_384x288-5fd6d3ff_20211130.pth \
configs/body_3d_keypoint/video_pose_lift/h36m/video-pose-lift_tcn-243frm-supv-cpn-ft_8xb128-200e_h36m.py \
https://download.openmmlab.com/mmpose/body3d/videopose/videopose_h36m_243frames_fullconv_supervised_cpn_ft-88f5abbb_20210527.pth \
--input data/two_dancers.mp4 \
--output-root outputs \
这是我的代码，运行完后的视频，打不开，显示“文件无效”
请大神帮帮忙，mmpose 的3Dhuman pose我已经搞了好几天了，还是没有实现

**Comment by LZhen624** [comment]
我有在mmpose那边回复您，就是我问问题的地方



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Peng ***@***.***&gt;; 
发送时间: 2023年11月3日(星期五) 下午4:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [open-mmlab/mmpose] 3Dhuman pose 运行不了 (Issue #2792)





 
您好，请问可以提供一下您使用的 mmpose 版本以及具体的报错信息吗？

**Comment by LZhen624** [comment]
!python demo/body3d_pose_lifter_demo.py
demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py
https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
configs/body_2d_keypoint/topdown_heatmap/posetrack18/td-hm_hrnet-w48_8xb64-20e_posetrack18-384x288.py
https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_posetrack18_384x288-5fd6d3ff_20211130.pth
configs/body_3d_keypoint/video_pose_lift/h36m/video-pose-lift_tcn-243frm-supv-cpn-ft_8xb128-200e_h36m.py
https://download.openmmlab.com/mmpose/body3d/videopose/videopose_h36m_243frames_fullconv_supervised_cpn_ft-88f5abbb_20210527.pth
--input data/two_dancers.mp4
--output-root outputs
这是我的代码，运行完后的视频，打不开，显示“文件无效”
mmcv是2.1.0版本的，mmpose是1.2.0版本的
请大神帮帮忙，mmpose 的3Dhuman pose我已经搞了好几天了，还是没有实现




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmpose"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月3日(星期五) 下午4:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmpose] 3Dhuman pose 运行不了 (Issue #2792)





 
您好，请问可以提供一下您使用的 mmpose 版本以及具体的报错信息吗？

**Comment by LZhen624** [comment]
> 您好，请问可以提供一下您使用的 mmpose 版本以及具体的报错信息吗？

信息都发了，大佬，能否帮帮忙呢

**Comment by Ben-Louis** [comment]
文件无效估计是保存的视频有问题或者打开视频的方式有问题。可以尝试用opencv解析一下视频。如果能成功解析，那就换个软件查看视频。如果解析失败，那应该是保存的时候出问题了

**Comment by LZhen624** [comment]
> 文件无效估计是保存的视频有问题或者打开视频的方式有问题。可以尝试用opencv解析一下视频。如果能成功解析，那就换个软件查看视频。如果解析失败，那应该是保存的时候出问题了

那我的那个运行代码有错误吗

**Comment by LZhen624** [comment]
这种问题要怎么解决呢

**Comment by Ben-Louis** [comment]
> 这种问题要怎么解决呢

可以尝试用opencv解析一下视频。如果能成功解析，那就换个软件查看视频。如果解析失败，那应该是保存的时候出问题了

**Comment by LZhen624** [comment]
> > 这种问题要怎么解决呢
> 
> 可以尝试用opencv解析一下视频。如果能成功解析，那就换个软件查看视频。如果解析失败，那应该是保存的时候出问题了

我刚刚换了一个软件，可以运行了，但是视频中有两个人，只估计出了一个人的姿势呢

**Comment by LZhen624** [comment]
!python demo/body3d_pose_lifter_demo.py \
demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py \
https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \
configs/body_2d_keypoint/topdown_heatmap/posetrack18/td-hm_hrnet-w48_8xb64-20e_posetrack18-384x288.py \
https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_posetrack18_384x288-5fd6d3ff_20211130.pth \
configs/body_3d_keypoint/video_pose_lift/h36m/video-pose-lift_tcn-243frm-supv-cpn-ft_8xb128-200e_h36m.py \
https://download.openmmlab.com/mmpose/body3d/videopose/videopose_h36m_243frames_fullconv_supervised_cpn_ft-88f5abbb_20210527.pth \
--input data/two_dancers.mp4 \
--output-root outputs \
--save-predictions
代码是这样的

**Comment by LZhen624** [comment]
大佬能帮我纠纠错吗

**Comment by LZhen624** [comment]
> !python demo/body3d_pose_lifter_demo.py demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth configs/body_2d_keypoint/topdown_heatmap/posetrack18/td-hm_hrnet-w48_8xb64-20e_posetrack18-384x288.py https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_posetrack18_384x288-5fd6d3ff_20211130.pth configs/body_3d_keypoint/video_pose_lift/h36m/video-pose-lift_tcn-243frm-supv-cpn-ft_8xb128-200e_h36m.py https://download.openmmlab.com/mmpose/body3d/videopose/videopose_h36m_243frames_fullconv_supervised_cpn_ft-88f5abbb_20210527.pth --input data/two_dancers.mp4 --output-root outputs --save-predictions 代码是这样的

最后一行该怎么用呢

**Comment by Ben-Louis** [comment]
可以先试下加上 `--num-instances 2`。参数的含义可以用 `python demo/body3d_pose_lifter_demo.py -h` 查看

**Comment by LZhen624** [comment]
> --num-instances 2

好嘞，我先试试，能否加大佬的联系方式呢

**Comment by LZhen624** [comment]
也方便后续跟您请教

**Comment by LZhen624** [comment]
> 可以先试下加上 `--num-instances 2`。参数的含义可以用 `python demo/body3d_pose_lifter_demo.py -h` 查看

最后一行换成了这个，用什么软件都打不开了，都显示文件无效

**Comment by LZhen624** [comment]
加上去可以了，谢谢大佬

**Comment by LZhen624** [comment]
> 可以先试下加上 `--num-instances 2`。参数的含义可以用 `python demo/body3d_pose_lifter_demo.py -h` 查看

大佬，我演示出来的3Dhuman pose 的视频，怎么人体的关键点没有标出来了，我看了子豪兄的，是有标出每个关键点的，我的只有线段连成的火柴人。

**Comment by LZhen624** [comment]
有没有那种脚上也有关键点的3Dhuman pose 模型呢，这个正常只到脚踝就没有
