### ISSUE TITLE
求助！RTM-pose 中的halpe 26模型怎么使用

### ISSUE THREAD

**Issue by LZhen624** [open-mmlab/mmpose#2795]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

mmpose 2.1.0
mmcv 1.2.0

### Reproduces the problem - code sample

# RTMPose
!python demo/topdown_demo_with_mmdet.py \
        demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py \
        https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \
        projects/rtmpose/rtmpose/body_2d_keypoint/rtmpose-s_8xb256-420e_coco-256x192.py \
        https://download.openmmlab.com/mmpose/v1/projects/rtmpose/rtmpose-s_simcc-aic-coco_pt-aic-coco_420e-256x192-fcb2599b_20230126.pth \
        --input data/test/mother_wx.mp4 \
        --output-root outputs/B1_RTM_2 \
        --device cuda:0 \
        --bbox-thr 0.5 \
        --kpt-thr 0.5 \
        --nms-thr 0.3 \
        --radius 5 \
        --thickness 2 \
        --draw-bbox \
        --draw-heatmap \
        --show-kpt-idx
 这个是RTM-pose的运行代码

### Reproduces the problem - command or script

那RTM-pose halpe6的运行代码是啥

### Reproduces the problem - error message

想学习一下怎么对视频进行RTM-pose halpe6的人体关键点检测

**Comment by Ben-Louis** [comment]
推荐阅读 [20分钟上手 MMPose](https://mmpose.readthedocs.io/zh-cn/dev-1.x/guide_to_framework.html) 和 [demos](https://mmpose.readthedocs.io/zh-cn/dev-1.x/demos.html)

**Comment by LZhen624** [comment]
好的，谢谢，我看看

> 推荐阅读 [20分钟上手 MMPose](https://mmpose.readthedocs.io/zh-cn/dev-1.x/guide_to_framework.html) 和 [demos](https://mmpose.readthedocs.io/zh-cn/dev-1.x/demos.html)
