### ISSUE TITLE
[Bug] result of vis_accuracy in vis_head.py larger than 1.0 

### ISSUE THREAD

**Issue by yao5401** [open-mmlab/mmpose#2799]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

mmpose 1.1.0
mmcv 2.0.1
mmengine 0.9.0
torch 1.10.2
python 3.8.0

### Reproduces the problem - code sample

use vis_head as model head;
method like configs\body_2d_keypoint\topdown_heatmap\coco\td-hm-vis_res50_8xb64-210e_coco-aic-256x192-merge.py

### Reproduces the problem - command or script

run train

### Reproduces the problem - error message

here is my train_log:
11/08 15:21:36 - mmengine - INFO - Epoch(train) [231][ 50/249]  base_lr: 5.000000e-06 lr: 1.187863e-07  eta: 1:09:30  time: 1.908585  data_time: 0.380705  memory: 12226  grad_norm: 0.002086  loss: 0.000790  loss_vis: 0.000072  acc_vis: 1.048827  loss_kpt: 0.000719  acc_pose: 0.942872
11/08 15:23:05 - mmengine - INFO - Epoch(train) [231][100/249]  base_lr: 5.000000e-06 lr: 1.187863e-07  eta: 1:08:04  time: 1.774205  data_time: 0.175464  memory: 12226  grad_norm: 0.002042  loss: 0.000787  loss_vis: 0.000073  acc_vis: 1.023634  loss_kpt: 0.000715  acc_pose: 0.943494
11/08 15:24:32 - mmengine - INFO - Epoch(train) [231][150/249]  base_lr: 5.000000e-06 lr: 1.187863e-07  eta: 1:06:39  time: 1.742338  data_time: 0.180159  memory: 12226  grad_norm: 0.002115  loss: 0.000780  loss_vis: 0.000069  acc_vis: 1.022862  loss_kpt: 0.000711  acc_pose: 0.924943
11/08 15:26:00 - mmengine - INFO - Epoch(train) [231][200/249]  base_lr: 5.000000e-06 lr: 1.187863e-07  eta: 1:05:14  time: 1.749474  data_time: 0.193498  memory: 12226  grad_norm: 0.002019  loss: 0.000776  loss_vis: 0.000072  acc_vis: 1.021810  loss_kpt: 0.000704  acc_pose: 0.937651

### Additional information

vis_head.py,
as the shape of vis_weights is [N,K] like vis_label,  when compute vis_accuracy，if weights keepdims while label doesn't, this mismatch will lead wrong result:
https://github.com/open-mmlab/mmpose/blob/6d10b2ec81da7e252016b3154c7fdb46c403ecd8/mmpose/models/heads/hybrid_heads/vis_head.py#L186C9-L189C14

**Comment by Ben-Louis** [comment]
Thank you very much for pointing out this problem. Would you like to submit a Pull Request to help resolve this issue?

**Comment by yao5401** [comment]
> Thank you very much for pointing out this problem. Would you like to submit a Pull Request to help resolve this issue?
ok, I will pull request later.

**Comment by Ben-Louis** [comment]
Thanks in advance for your contribution. You may find the [contribution guide](https://mmpose.readthedocs.io/en/latest/contribution_guide.html) helpful. Please don't hesitate to reach out if you have any questions.
