### ISSUE TITLE
[Bug] KeyError: 'bbox' after running inference script over a trained model 

### ISSUE THREAD

**Issue by alaa-shubbak** [open-mmlab/mmpose#2803]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

the environment information is : 

`{'sys.platform': 'linux', 'Python': '3.9.10 (main, Mar  4 2022, 13:58:45) [GCC 8.4.0]', 'CUDA available': True, 'GPU 0': 'Tesla V100-SXM2-32GB', 'CUDA_HOME': '/usr/local/cuda', 'NVCC': 'Build cuda_12.2.r12.2/compiler.32965470_0', 'GCC': 'gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)', 'PyTorch': '1.10.0+cu111', 'PyTorch compiling details': 'PyTorch built with:\n  - GCC 7.3\n  - C++ Version: 201402\n  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)\n  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n  - LAPACK is enabled (usually provided by MKL)\n  - NNPACK is enabled\n  - CPU capability usage: AVX512\n  - CUDA Runtime 11.1\n  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86\n  - CuDNN 8.0.5\n  - Magma 2.5.2\n  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, \n', 'TorchVision': '0.11.0+cu111', 'OpenCV': '4.6.0', 'MMCV': '1.3.18', 'MMCV Compiler': 'n/a', 'MMCV CUDA Compiler': 'n/a', 'MMPose': '0.29.0+8e6169b'}
`

after running this command pip list | grep mm 
i get this : 

```
commonmark               0.9.1
mmcls                    1.0.0rc6
mmcv                     1.3.18
mmcv-full                1.7.0
mmdet                    3.0.0
mmengine                 0.7.2
mmpose                   1.0.0          /home/shubbak/env_pose/lib/python3.9/site-packages
mmsegmentation           1.0.0

```

### Reproduces the problem - code sample

the script is only try to inference a model and its trained weight on new image , 

i used code from this [site](https://mmpose.readthedocs.io/en/0.x/install.html#installation)

### Reproduces the problem - command or script

command to run 
`python inference_new.py`

this script contains the following: 

<img width="428" alt="image" src="https://github.com/open-mmlab/mmpose/assets/10245810/a7d663e5-7159-4c66-ac2e-03392b30a50a">

### Reproduces the problem - error message

```
Traceback (most recent call last):
  File "/home/shubbak/mmpose_old/inference_new.py", line 19, in <module>
    pose_results, _ = inference_bottom_up_pose_model(pose_model, image_name)
  File "/home/shubbak/mmpose_old/mmpose/apis/inference.py", line 505, in inference_bottom_up_pose_model
    data = test_pipeline(data)
  File "/home/shubbak/mmpose_old/mmpose/datasets/pipelines/shared_transform.py", line 107, in __call__
    data = t(data)
  File "/home/shubbak/mmpose_old/mmpose/datasets/pipelines/top_down_transform.py", line 44, in __call__
    bbox = results['bbox']
KeyError: 'bbox'
```
<img width="341" alt="image" src="https://github.com/open-mmlab/mmpose/assets/10245810/200c39c0-3560-4e6c-b496-b757293be272">

### Additional information

i was expected to get an image represent the result of pose estimation after using  my model and its weights. 

I had train a model on my custom dataset , and produce a .pth weight files . 
then i try to inference my trained model and its weight over new some images 
i want to try/inference this over only images without any annotation files (.json)

**Comment by Ben-Louis** [comment]
Please install mmdet 2.x since you are using an old version of mmpose.

**Comment by Ben-Louis** [comment]
Please ensure package versions are compatible, with versions in one of two groups:
- mmpose 1.x, mmdet 3.x, mmcv 2.x, mmegine 0.x
- mmpose 0.x, mmdet 2.x, mmcv/mmcv-full 1.x
