### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by yulin011** [open-mmlab/mmpose#2805]
### Prerequisite

- [x] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

1. necessary environment information:
`OrderedDict([('sys.platform', 'linux'), ('Python', '3.8.18 (default, Sep 11 2023, 13:40:15) [GCC 11.2.0]'), ('CUDA available', True), ('numpy_random_seed', 2147483648), ('GPU 0,1', 'NVIDIA GeForce RTX 4090'), ('CUDA_HOME', '/usr/local/cuda'), ('NVCC', 'Cuda compilation tools, release 11.8, V11.8.89'), ('GCC', 'gcc (Ubuntu 7.5.0-6ubuntu2) 7.5.0'), ('PyTorch', '1.13.0'), ('PyTorch compiling details', 'PyTorch built with:\n  - GCC 9.3\n  - C++ Version: 201402\n  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)\n  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n  - LAPACK is enabled (usually provided by MKL)\n  - NNPACK is enabled\n  - CPU capability usage: AVX2\n  - CUDA Runtime 11.7\n  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37\n  - CuDNN 8.5\n  - Magma 2.6.1\n  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, \n'), ('TorchVision', '0.14.0'), ('OpenCV', '4.8.1'), ('MMEngine', '0.9.1'), ('MMPose', '1.1.0+')])`

2.run` pip list | grep mm` get as follows:
```
mmcv                   2.0.1
mmdet                  3.1.0
mmengine               0.9.1
mmpose                 1.1.0
```

### Reproduces the problem - code sample

i used code from this [image_demo.py](https://github.com/open-mmlab/mmpose/blob/main/demo/image_demo.py)

### Reproduces the problem - command or script

```
python demo/image_demo.py \
    tests/data/coco/000000000785.jpg \
    td-hm_hrnet-w48_8xb32-210e_coco-256x192.py \
    td-hm_hrnet-w48_8xb32-210e_coco-256x192-0e67c616_20220913.pth \
    --out-file vis_results.jpg \
    --draw-heatmap
```

### Reproduces the problem - error message

```
File "demo/image_demo.py", line 105, in <module>
    main()
  File "demo/image_demo.py", line 69, in main
    model = init_model(
  File "/home/username/repo/PoseEstimate/mmpose-1.1.0/mmpose/apis/inference.py", line 88, in init_model
    config = Config.fromfile(config)
  File "/home/username/env/miniconda3/envs/mmpose/lib/python3.8/site-packages/mmengine/config/config.py", line 457, in fromfile
    cfg_dict, cfg_text, env_variables = Config._file2dict(
  File "/home/username/env/miniconda3/envs/mmpose/lib/python3.8/site-packages/mmengine/config/config.py", line 941, in _file2dict
    raise e
  File "/home/username/env/miniconda3/envs/mmpose/lib/python3.8/site-packages/mmengine/config/config.py", line 883, in _file2dict
    _cfg_dict, _cfg_text, _env_variables = Config._file2dict(
  File "/home/username/env/miniconda3/envs/mmpose/lib/python3.8/site-packages/mmengine/config/config.py", line 839, in _file2dict
    if lazy_import is None and Config._is_lazy_import(filename):
  File "/home/username/env/miniconda3/envs/mmpose/lib/python3.8/site-packages/mmengine/config/config.py", line 1655, in _is_lazy_import
    with open(filename, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/username/repo/PoseEstimate/mmpose-1.1.0/../../../_base_/default_runtime.py'
```

**Comment by Ben-Louis** [comment]
Please note that if you copy the `td-hm_hrnet-w48_8xb32-210e_coco-256x192.py` file directly from the `configs/` folder, its dependency on another configuration file will be broken. To avoid this issue, it is recommended to either obtain this configuration file through the command `mim download mmpose --config td-hm_hrnet-w48_8xb32-210e_coco-256x192 --dest .` or use the original path of the `td-hm_hrnet-w48_8xb32-210e_coco-256x192.py` file located under the `configs` directory.
