### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by imedsj** [open-mmlab/mmpose#2807]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

[https://github.com/imedsj/mmpose-files/blob/main/cspnext-l_udp_8xb256-210e_aic-coco-256x192/%E7%8E%AF%E5%A2%83.txt](url)

### Reproduces the problem - code sample

[https://github.com/imedsj/mmpose-files/blob/main/cspnext-l_udp_8xb256-210e_aic-coco-256x192/20231114_181448/vis_data/config.py](url)

### Reproduces the problem - command or script

bash ./...../mmpose-main/configs/body_2d_keypoint/topdown_heatmap/coco/cspnext-l_udp_8xb256-210e_aic_coco-256x196.py 1

### Reproduces the problem - error message

[https://github.com/imedsj/mmpose-files/blob/main/20231114_181448.log](url)

### Additional information

I encountered this problem when training the coco model with mmpose: no matter which configuration file I modified, the code could not run normally, and there seemed to be no error code in the logs, this is the first time I used mmpose, I followed the tutorial in the official documentation (https://mmpose.readthedocs.io/zh-cn/latest/dataset_zoo.html), I don't know how I can fix this

**Comment by Ben-Louis** [comment]
It is difficult to identify the problem without an error message. You could try interrupting the process to see if there is an error message that indicates where the program is stuck.
