### ISSUE TITLE
How to train and inference with MPII-TRB?

### ISSUE THREAD

**Issue by X-ray0214** [open-mmlab/mmpose#2812]
### 📚 The doc issue

I couldn't find any python files support MPII-TRB.

**Comment by Tau-J** [comment]
Please refer to `0.x` branch and see the docs of it.

**Comment by kxyk99** [comment]
the 0.x validator config can't be used in the latest code where is not the key 'type', how to deal with it?
![Uploading image.png…]()

**Comment by kxyk99** [comment]
it seems that the MPII-trb dataset can't use the MpiiAccuracy validator directly because of no head_size? how to config the validator for the MPII-trb dataset
