### ISSUE TITLE
This file cannot be found: “generate_bbox_file.py”

### ISSUE THREAD

**Issue by slidingfriction** [open-mmlab/mmpose#2819]
### 📚 The doc issue

![mmexport1700898180381](https://github.com/open-mmlab/mmpose/assets/151989730/30b8b623-3d1d-4d46-a4d4-b530762686d1)
File “generate_bbox_file.py” can not be found in mmpose/tools/misc
Where can I get it?

**Comment by Tau-J** [comment]
Please see `dev-1.x` branch
