### ISSUE TITLE
Keypoint detection based on video

### ISSUE THREAD

**Issue by zbl929** [open-mmlab/mmpose#2820]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

Does the currently supported algorithm have video-based keypoint detection ?

### Reproduces the problem - code sample

1

### Reproduces the problem - command or script

1

### Reproduces the problem - error message

1

**Comment by Ben-Louis** [comment]
In the previous version of mmpose, the posewarper algorithm was supported for video inputs (https://github.com/open-mmlab/mmpose/tree/0.x/configs/body/2d_kpt_sview_rgb_vid). However, this feature has not been transferred to the latest version. Using an image-based algorithm is still possible if you only need to apply pose estimation on videos.
