### ISSUE TITLE
[Question] The pipeline of pose estimation with det

### ISSUE THREAD

**Issue by aleeyang** [open-mmlab/mmpose#2823]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

The Code works. I am just confused about the pipeline.

### Reproduces the problem - code sample

I am using the [https://github.com/open-mmlab/mmpose/blob/main/demo/topdown_demo_with_mmdet.py](The pose demo with det). 

### Reproduces the problem - command or script

[https://github.com/open-mmlab/mmpose/blob/6d10b2ec81da7e252016b3154c7fdb46c403ecd8/demo/topdown_demo_with_mmdet.py#L47C5-L47C17](These are output keypoint)

### Reproduces the problem - error message

In the inference process, it first uses TopDownAffine to resize the image within the bounding box. After inference, the keypoints are rescaled to the input size (from 64x48 to 256x192), which corresponds to keypoints in the cropped image defined by the bounding box. These are not the original keypoints. I couldn't find any operation similar to TopDownAffine after the model's inference that would recover the absolute location using the detection box.

### Additional information

1. Is there some code I  have missed that applies the similar affine operation to recover the absolute location of the keypoints in heatmap?

**Comment by Tau-J** [comment]
Yes. For topdown method, please refer to [here](https://github.com/open-mmlab/mmpose/blob/1b56d56c5a2e5809021889e1aa963df7d395dbd1/mmpose/models/pose_estimators/topdown.py#L154)
