### ISSUE TITLE
[Docs] WFLW dataset json 'scale'

### ISSUE THREAD

**Issue by a-drop-in-the-ocean456** [open-mmlab/mmpose#2825]
### 📚 The doc issue

[Bug] We download json of WFLW from https://openxlab.org.cn/datasets/OpenDataLab/WFLW ,  I want to know 'scale' in this json mean. WFLW download from original website of its paper do not have this , how does it calulate . And in json of COFW, there are no 'scale' .

**Comment by Ben-Louis** [comment]
'scale' represents the width and height of the bounding box in WFLW. In COFW, the bounding box is represented in the xyxy format, so there is no 'scale'

**Comment by a-drop-in-the-ocean456** [comment]
> 'scale' represents the width and height of the bounding box in WFLW. In COFW, the bounding box is represented in the xyxy format, so there is no 'scale'

cofw is also xywh, and I can not calculate scale true from json width/height .

**Comment by Ben-Louis** [comment]
Yes, COFW annotations use xywh format for bounding boxes. WFLW uses 'scale' to represent equal width and height for square bounding boxes. It is not a ratio.

**Comment by a-drop-in-the-ocean456** [comment]
> Yes, COFW annotations use xywh format for bounding boxes. WFLW uses 'scale' to represent equal width and height for square bounding boxes. It is not a ratio.

            "bbox": [
                11.738692799999999,
                56.1495464,
                89.33841840000001,
                90.89704320000001
            ],
            "iscrowd": 0,
            "area": 8120.598076724476,
            "category_id": 1,
            "center": [
                56.5,
                101.5
            ],
            "scale": 0.385
        },   Thank you for your reply, but in wflw json, as shown above, bbox is not square.

**Comment by Ben-Louis** [comment]
Please refer to this snippet for the processing of WFLW annotations: https://github.com/open-mmlab/mmpose/blob/1b56d56c5a2e5809021889e1aa963df7d395dbd1/mmpose/datasets/datasets/face/wflw_dataset.py#L82-L89

"bbox" in json file is not used.

**Comment by a-drop-in-the-ocean456** [comment]
> Please refer to this snippet for the processing of WFLW annotations:
> 
> https://github.com/open-mmlab/mmpose/blob/1b56d56c5a2e5809021889e1aa963df7d395dbd1/mmpose/datasets/datasets/face/wflw_dataset.py#L82-L89
> 
> "bbox" in json file is not used.

Thank you, I know that now.
