### ISSUE TITLE
[Docs] VitPose inference

### ISSUE THREAD

**Issue by gokcergun** [open-mmlab/mmpose#2828]
### 📚 The doc issue

Hi, 
I am wondering if it is possible to infer using Vitpose human model. I could not find a demo for vitPose and the other demo examples did not work with it. 

Thank you. 

### Suggest a potential alternative/fix

-- add a demo for Vitpose

**Comment by Ben-Louis** [comment]
Would you mind sharing your command to use ViTPose?

**Comment by gokcergun** [comment]
Hi sure, 

I have tried this command: 
`inferencer = MMPoseInferencer(
        pose2d=".configs/td-hm_ViTPose-large_8xb64-210e_coco-256x192.py",
pose2d_weights="https://download.openmmlab.com/mmpose/v1/body_2d_keypoint/topdown_heatmap/coco/td-hm_ViTPose-base_8xb64-210e_coco-256x192-216eae50_20230314.pth",
        det_model=config["detection_config"],  #I tried with yolox-l and faster-rcnn-r50
        det_weights=config["detection_checkpoint"],
        det_cat_ids=[0], # the category id of 'human' class
        device=config['device']
    )
   result_generator = inferencer(camera_folder,
                                  pred_out_dir=config["prediction_folders"][camera_name],
                                  show=False,
                                   vis_out_dir=config["image_folders"][camera_name])
            results = [r for r in result_generator]
        else:
            result_generator = inferencer(camera_folder,
                                          pred_out_dir=config["prediction_folders"][camera_name],
                                          show=False)
            results = [r for r in result_generator]`

But I am getting `TypeError: __init__() got an unexpected keyword argument 'output_cls_token'`
I tried also running through 
`init_model()...
inference_topdown()` I'm getting the same error. 
Thanks for help.

**Comment by Ben-Louis** [comment]
Can you please run 'pip list' to show the installed packages?  As indicated in https://github.com/open-mmlab/mmpose/blob/main/configs/body_2d_keypoint/topdown_heatmap/coco/vitpose_coco.md, 'mmpretrained>=1.0.0' is required to use ViTPose

**Comment by Ben-Louis** [comment]
I see. The argument 'output_cls_token' used in the old version of mmpose has been deprecated. Please try using the latest version of mmpose along with the config file.

**Comment by gokcergun** [comment]
@Ben-Louis Great, it worked after I reinstall mmpose `mim install "mmpose>=1.1.0"`

**Comment by dqj5182** [comment]
`mim install "mmpose>=1.1.0"` does not solve the issue for me
