### ISSUE TITLE
FocalHeatmaps[Feature] 

### ISSUE THREAD

**Issue by ChenZhenGui** [open-mmlab/mmpose#2829]
### What is the feature?

Hello，I want to use FocalHeatmapsLoss to calculate the loss, but I found that part of the output in the output will be less than 0, which will cause the loss to become negative infinity when taking the logarithm. How can I solve this problem?
![image](https://github.com/open-mmlab/mmpose/assets/52156532/4e9e01f6-a450-4906-8e12-6adf17382681)
![image](https://github.com/open-mmlab/mmpose/assets/52156532/d78e9746-d5ab-4c06-9cc3-12ab35f209f2)

**Comment by ChenZhenGui** [comment]
![image](https://github.com/open-mmlab/mmpose/assets/52156532/37daf8c2-3328-4cff-a8d9-7665b8ae1e3b)

**Comment by Ben-Louis** [comment]
Please apply sigmoid on heatmaps before using focal loss

**Comment by ChenZhenGui** [comment]
已收到，谢谢
