### ISSUE TITLE
how to detect four points of an image, such as document images, tables

### ISSUE THREAD

**Issue by cqray1990** [open-mmlab/mmpose#2830]
### What is the feature?

how to detect four points of an image, such as document images, tables
![PMC515302_003_00](https://github.com/open-mmlab/mmpose/assets/32585434/acb14aee-952f-4b68-880c-496276642430)

**Comment by YrralH** [comment]
You can write scripts with traditional line detection methods (probably can be found in OpenCV) and some rules for certain styles of tables. (e.g. to find the three lines)
For the general table detection task, you may search for some business OCR software or some open source OCR tools (maybe TSRFormer <https://github.com/microsoft/table-transformer> ?)
I suggest you close this issue and you may ask the question in another OCR repo.
