### ISSUE TITLE
[Feature] how to evaluate the impact of smoothnet on mpjpe

### ISSUE THREAD

**Issue by gaominqi** [open-mmlab/mmpose#2840]
### What is the feature?

Can you answer how to modify the config file of videopose3d to evaluate the impact of Gaussian filter and smoothnet on the three-dimensional pose estimation index mpjpe.
/home/gmq/mmpose-master/configs/body/3d_kpt_sview_rgb_vid/video_pose_lift/h36m/videopose3d_h36m_27frames_fullconv_supervised.py

**Comment by Ben-Louis** [comment]
Simply modifying the config cannot apply smoothing to predictions. You may need to manually smooth the predictions on the test set and calculate the metrics.

**Comment by gaominqi** [comment]
I saw that only the demo use the smoothnet. How to add smoothnet to the model for training? Or  I can only train my model and smoothnet separately and then process them offline?
