### ISSUE TITLE
[Time dependent estimation] 

### ISSUE THREAD

**Issue by mpillet** [open-mmlab/mmpose#2844]
### What is the feature?

Does the model estimate the 2D pose only based on the current frame OR it also uses time information (the information of the previous frames) ? If no, is there a way to introduce this ?

Thank you !

**Comment by Ben-Louis** [comment]
Among the 2D pose estimators in MMPose, only RTMPose uses a pipeline inference that utilizes the pose in the previous frame to form a new bounding box. Other 2D pose estimators use only one frame as input.

**Comment by mpillet** [comment]
Thank you for the reply. 
I dont know if you already faced the issue but maybe you can help me.
I'm using 2 cameras to reconstruct the 3D kinematics of a human, with the 133 body model keypoints. I'm using my own triangulation to reconstruct the 3D, based on the 2D of the 2 cams. However, I'm facing an issue, depending if the person is facing or facing away the cameras. The body is more forward-oriented in a case rather than in another one, causing a kind of shift in my data, such my body angles. I think that the problem is probably due to the 2D marking, which is probably different depending if the cameras see the front of the body or the back. Do you think that this small difference in the 2D pose estimation is enough to modify the 3D pose ?

**Comment by Ben-Louis** [comment]
Hi @mpillet, I suggest starting a new discussion at https://github.com/open-mmlab/mmpose/discussions with a descriptive title to get help from other experienced users.
