### ISSUE TITLE
[Docs] 单张图像和文件夹图像的检测问题

### ISSUE THREAD

**Issue by caochengchen** [open-mmlab/mmpose#2846]
### 📚 The doc issue

thank you

**Comment by caochengchen** [comment]
Hello, when I run an image for hand key point detection, both hands can detect and output corresponding coordinates, but when detecting all images in a folder, many images can only detect the key point of one hand and output only one hand key point. When I run one image after another, this problem disappears again. The following is the code for me to detect the coordinates of key points of all image hands under the folder path. May I ask where the error occurred? How should it be modified? Another question I have is how to detect the key points of hand, body and face on the same image at the same time and save them, and how to modify the code? I didn't find a solution in the documentation

from mmpose.apis import MMPoseInferencer
folder_path = r'E:\image'
inferencer = MMPoseInferencer('hand')
result_generator = inferencer(folder_path, out_dir='output')
result = next(result_generator)
results = [result for result in result_generator]

**Comment by Ben-Louis** [comment]
Can you please share the images you used for per-image detection, along with the command you executed?
