### ISSUE TITLE
[Docs] mmpose

### ISSUE THREAD

**Issue by caochengchen** [open-mmlab/mmpose#2851]
### 📚 The doc issue

thank you！

**Comment by Ben-Louis** [comment]
Please replace the demo command's config and checkpoint with RTMW's, which can be found at https://mmpose.readthedocs.io/en/latest/model_zoo_papers/datasets.html#rtmpose-rtmw-on-cocktail13. 

If you're still having trouble, you can try our online demo page at https://openxlab.org.cn/apps/detail/mmpose/RTMPose.

**Comment by caochengchen** [comment]
![image](https://github.com/open-mmlab/mmpose/assets/102595565/f2220aaa-d936-4efc-8bb6-6297dc240157)
![image](https://github.com/open-mmlab/mmpose/assets/102595565/a803d99f-5ebc-4cef-8e7e-454a3d2d72c0)

**Comment by caochengchen** [comment]
Please help me, I want to use the RTMW model to detect the hand, but this code reported an error, I do not know how to modify.
I also tried to use the DWPOSE model to detect the hand and changed the model configuration and weight file, but the effect of detecting the hand was not good.
I just want this RTMW model to look like I want it to.

**Comment by caochengchen** [comment]
> 请将 demo 命令的配置和检查点替换为 RTMW 的配置和检查点，可在 https://mmpose.readthedocs.io/en/latest/model_zoo_papers/datasets.html#rtmpose-rtmw-on-cocktail13 中找到。
> 
> 如果您仍然遇到问题，可以尝试我们的在线演示页面，网址为 https://openxlab.org.cn/apps/detail/mmpose/RTMPose。

Please help me, I want to use the RTMW model to detect the hand, but this code reported an error, I do not know how to modify.
I also tried to use the DWPOSE model to detect the hand and changed the model configuration and weight file, but the effect of detecting the hand was not good.
I just want this RTMW model to look like I want it to.The specific problems I encountered and the code can be seen in the comments above.
