### ISSUE TITLE
[Bug] Problem occurs when detecting hand bbox

### ISSUE THREAD

**Issue by zxk19981227** [open-mmlab/mmpose#2853]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

OrderedDict([('sys.platform', 'linux'), ('Python', '3.9.18 (main, Sep 11 2023, 13:41:44) [GCC 11.2.0]'), ('CUDA available', True), ('numpy_random_seed', 2147483648), ('GPU 0,1,2,3', 'NVIDIA RTX A6000'), ('CUDA_HOME', '/data2/zhouxukun/cuda-11.6'), ('NVCC', 'Cuda compilation tools, release 11.6, V11.6.55'), ('GCC', 'gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0'), ('PyTorch', '1.13.1+cu116'), ('PyTorch compiling details', 'PyTorch built with:\n  - GCC 9.3\n  - C++ Version: 201402\n  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)\n  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n  - LAPACK is enabled (usually provided by MKL)\n  - NNPACK is enabled\n  - CPU capability usage: AVX2\n  - CUDA Runtime 11.6\n  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86\n  - CuDNN 8.6  (built against CUDA 11.8)\n    - Built with CuDNN 8.3.2\n  - Magma 2.6.1\n  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, \n'), ('TorchVision', '0.14.1+cu116'), ('OpenCV', '4.8.1'), ('MMEngine', '0.10.1'), ('MMPose', '1.2.0+6d10b2e')])

### Reproduces the problem - code sample

    hand_detector=init_detector(
        'mmpose/demo/mmdetection_cfg/cascade_rcnn_x101_64x4d_fpn_1class.py',
        'cascade_rcnn_x101_64x4d_fpn_20e_onehand10k-dac19597_20201030.pth',
        device='cuda',
    )
   hand_det_result=inference_detector(hand_detector,image)

### Reproduces the problem - command or script

directly run the code

### Reproduces the problem - error message

![image](https://github.com/open-mmlab/mmpose/assets/40291547/69b88e15-68e0-4def-9322-fa22c34b1e24)

### Additional information

the hand is not detected

**Comment by zxk19981227** [comment]
![image](https://github.com/open-mmlab/mmpose/assets/40291547/bfa1f42d-6ba3-46e9-81d5-1779bc03d61c)
the hand area is wrong

**Comment by Ben-Louis** [comment]
Hi, would you please share the image again since its link has been broken? BTW, the off-the-shelf hand detector `cascade_rcnn_x101_64x4d_fpn_1class` is based on an old model and was trained using a single dataset OneHand10K, so its performance might not be satisfactory, especially in difficult scenarios. If you need an accurate hand detector, we suggest that you train it using a new model and a larger hand dataset.
