### ISSUE TITLE
[Docs] Image size

### ISSUE THREAD

**Issue by caochengchen** [open-mmlab/mmpose#2858]
### 📚 The doc issue

Is there a requirement for the size of the input picture when I'm reasoning directly with different pre-trained models? Do different pretrained models automatically adjust the image input size to suit their own different model configurations?

**Comment by Ben-Louis** [comment]
This [guidance](https://mmpose.readthedocs.io/en/latest/guide_to_framework.html) could be useful for getting familiar with pipelines in MMPose.

**Comment by caochengchen** [comment]
Thanks for your answer, but most of the documentation you recommended to me was about training, and I just wanted to go straight to reasoning using the pre-trained model.
When using the pre-trained model, do I need to modify the size of the input image in advance?
May I ask the key point coordinate value of the output, and how to judge the corresponding position of each line coordinate value? For example, I use the wholebody model to check the key points of the wholebody. There are more than 100 key points. How do I determine where each key point belongs?

**Comment by YrralH** [comment]
For question
>  Do I need to modify the size of the input image in advance?

I am pretty sure the resize operation will affect the results after some testing and I am still searching for the answer.

For question ```the order of the keypoints``` <https://github.com/jin-s13/COCO-WholeBody>

**Comment by caochengchen** [comment]
Thank you for your answers, but I'm curious, is this a difficult question? The author does not respond

> 对于问题
> 
> > 我需要提前修改输入图像的大小吗？
> 
> 我很确定调整大小操作会影响经过一些测试的结果，我仍在寻找答案。（我还没有阅读详细的代码或论文）
> 
> 问题 https://github.com/jin-s13/COCO-WholeBody`the order of the keypoints`

**Comment by caochengchen** [comment]
> 本[指南](https://mmpose.readthedocs.io/en/latest/guide_to_framework.html)对于熟悉 MMPose 中的管道非常有用。

Thank you for your answers, but I'm curious, is this a difficult question? The author does not respond

**Comment by Ben-Louis** [comment]
> Thank you for your answers, but I'm curious, is this a difficult question? The author does not respond

Nope, this is a simple question and it is already clarified in the document.

![截屏2023-12-12 10 10 47](https://github.com/open-mmlab/mmpose/assets/26127467/687e15d2-5775-4299-b0e3-0c2432783091)

**Comment by Ben-Louis** [comment]
> Thanks for your answer, but most of the documentation you recommended to me was about training, and I just wanted to go straight to reasoning using the pre-trained model. When using the pre-trained model, do I need to modify the size of the input image in advance? May I ask the key point coordinate value of the output, and how to judge the corresponding position of each line coordinate value? For example, I use the wholebody model to check the key points of the wholebody. There are more than 100 key points. How do I determine where each key point belongs?

As described in the documentation, the dataset meta file includes the definition of each keypoint

![截屏2023-12-12 10 17 33](https://github.com/open-mmlab/mmpose/assets/26127467/dcc9deb7-9a15-4b4d-8c91-160d1f719552)

**Comment by caochengchen** [comment]
> > 感谢您的回答，但您向我推荐的大多数文档都是关于训练的，我只想直接使用预训练模型进行推理。使用预训练模型时，是否需要提前修改输入图像的大小？请问输出的关键点坐标值，如何判断各线坐标值的对应位置？例如，我使用全身模型来检查全身的关键点。有 100 多个关键点。如何确定每个关键点的归属位置？
> 
> 如文档中所述，数据集元文件包含每个关键点的定义
> 
> ![截屏2023-12-12 10 17 33](https://private-user-images.githubusercontent.com/26127467/289724623-dcc9deb7-9a15-4b4d-8c91-160d1f719552.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNjgzMjEsIm5iZiI6MTcwMjM2ODAyMSwicGF0aCI6Ii8yNjEyNzQ2Ny8yODk3MjQ2MjMtZGNjOWRlYjctOWExNS00YjRkLThjOTEtMTYwZDFmNzE5NTUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDA4MDAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhOGNhOGY1MWFiYjA3NjQ0NTA0NGRlMjhkNDYxZTE5YTRkY2FiZDkxMmRiYjUwM2FjNDhiYTNhNzZmMDg5NmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mI5qbxx-nsR1v2Hq3IsBRA18ZEPAwvxXvjz79bWIROY)

Thanks for your reply
