### ISSUE TITLE
finished

### ISSUE THREAD

**Issue by caochengchen** [open-mmlab/mmpose#2872]
thank you！

**Comment by Tau-J** [comment]
We provide two appoaches to conduct visualization, via opencv and matplotlib. You can refer to [here](https://github.com/open-mmlab/mmpose/blob/main/mmpose/visualization/local_visualizer.py#L46) to see details of `draw_circles()` and `draw_lines()`. We also provide a simplified api [here](https://github.com/open-mmlab/mmpose/blob/main/mmpose/apis/visualization.py)

**Comment by caochengchen** [comment]
Thank you. I think I should have addressed the problem in more detail. There are a total of 133 key points in the whole body. If I only want to draw a few of them, say 50, how should I define the code for linking and visualizing the key points?

**Comment by caochengchen** [comment]
> 我们提供了两个应用程序来进行可视化，分别是通过 opencv 和 matplotlib。您可以参考[此处](https://github.com/open-mmlab/mmpose/blob/main/mmpose/visualization/local_visualizer.py#L46)查看 和 的详细信息。[我们还在此处](https://github.com/open-mmlab/mmpose/blob/main/mmpose/apis/visualization.py)提供了一个简化的 API`draw_circles()``draw_lines()`

Thank you. I think I should have addressed the problem in more detail. There are a total of 133 key points in the whole body. If I only want to draw a few of them, say 50, how should I define the code for linking and visualizing the key points?
