### ISSUE TITLE
[Docs] About the output order

### ISSUE THREAD

**Issue by xz-123-new** [open-mmlab/mmpose#2875]
### 📚 The doc issue

About output order

### Suggest a potential alternative/fix

How can i determine the output orders of keypoints relating to each joint name? I can't find the corresponding joint name list in config files.

**Comment by Ben-Louis** [comment]
Check the [meta information file](https://github.com/open-mmlab/mmpose/tree/main/configs/_base_/datasets) for the dataset used to train the model you are using. They key `keypoint_info` includes the definition of each keypoint.
