### ISSUE TITLE
[Docs] How is keypoint_scores calculated?

### ISSUE THREAD

**Issue by Echo-san** [open-mmlab/mmpose#2883]
### 📚 The doc issue

I ran the demo [on this page](https://colab.research.google.com/github/open-mmlab/mmpose/blob/main/demo/MMPose_Tutorial.ipynb#scrollTo=ogj5h9x-HiMA),

- visualizer.get_image()._pred_instances.keypoint_scores

I would like to know how keypoint_scores in that demo are calculated.
What algorithm was used to calculate ?
Or could you please let me know which page I can refer to to find out?

My apologies if I've missed some elementary information.

**Comment by Ben-Louis** [comment]
Hi @Echo-san, the calculation of `keypoint_scores` is included in the model codec `decode` method. For example, in the tutorial, you are using the model `td-hm_hrnet-w32_8xb64-210e_coco-256x192`, whose codec is `MSRAHeatmap`. The score calculation is conducted at 
https://github.com/open-mmlab/mmpose/blob/efe09cd5268d4d6b21100334fbf2947ef36fc7db/mmpose/codecs/msra_heatmap.py#L137
