### ISSUE TITLE
[Docs] Include Pose Detection Example in C++ SDK API Documentation of RTMPose

### ISSUE THREAD

**Issue by willyfh** [open-mmlab/mmpose#2885]
### 📚 The doc issue

The current documentation for the RTMPose SDK C++ API ([C++ API Documentation](https://github.com/open-mmlab/mmpose/tree/main/projects/rtmpose#c-api)) provides an example for detecting bounding boxes given an image. However, there is a discrepancy compared to the Python API example ([Python API Documentation](https://github.com/open-mmlab/mmpose/tree/main/projects/rtmpose#python-api)), which demonstrates how to use the SDK API for pose detection.

### Suggest a potential alternative/fix

I propose including a pose detection example in the C++ API documentation to align it with the Python API example. This addition would provide users with a consistent and comprehensive understanding of how to use the RTMPose SDK for pose detection. The existing Python example showcases how to detect poses given an image and optional bounding boxes, offering valuable guidance for users interested in pose detection.

**Comment by Ben-Louis** [comment]
Thank you for your suggestion and contribution! Please feel free to raise any issues or PR if you have questions or ideas for improving the user experience
