### ISSUE TITLE
Hello, does the model support conversion to ONNX?Are there examples of deployments to C++?

### ISSUE THREAD

**Issue by huangzhenjie** [open-mmlab/mmpose#289]

**Comment by jin-s13** [comment]
Maybe just try [pytorch2onnx](https://github.com/open-mmlab/mmdetection/blob/master/tools/pytorch2onnx.py) from mmdet?

**Comment by huangzhenjie** [comment]
thanks

**Comment by innerlee** [comment]
Hi @huangzhenjie, could you pls try this pull request, https://github.com/open-mmlab/mmpose/pull/305, and report if it works for you?
