### ISSUE TITLE
[Bug] When using UDP Heatmap with heatmap_type='combined', an error is reported.

### ISSUE THREAD

**Issue by SCsleepy** [open-mmlab/mmpose#2890]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

OrderedDict([('sys.platform', 'linux'), ('Python', '3.8.18 (default, Sep 11 2023, 13:40:15) [GCC 11.2.0]'), ('CUDA available', True), ('numpy_random_seed', 2147483648), ('GPU 0,1,2', 'NVIDIA A100-SXM4-80GB'), ('GPU 3', 'NVIDIA A100 80GB PCIe'), ('CUDA_HOME', '/usr/local/cuda-11.7'), ('NVCC', 'Cuda compilation tools, release 11.7, V11.7.99'), ('GCC', 'gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0'), ('PyTorch', '1.11.0+cu113'), ('PyTorch compiling details', 'PyTorch built with:\n  - GCC 7.3\n  - C++ Version: 201402\n  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v2.5.2 (Git Hash a9302535553c73243c632ad3c4c80beec3d19a1e)\n  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n  - LAPACK is enabled (usually provided by MKL)\n  - NNPACK is enabled\n  - CPU capability usage: AVX2\n  - CUDA Runtime 11.3\n  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86\n  - CuDNN 8.2\n  - Magma 2.5.2\n  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, \n'), ('TorchVision', '0.12.0+cu113'), ('OpenCV', '4.8.1'), ('MMEngine', '0.10.1'), ('MMPose', '1.2.0+')])

mmcv                   2.1.0
mmdet                  3.2.0
mmengine               0.10.1
mmpose                 1.2.0        /data/lsc/mmpose-main-1.2.0
timm                   0.9.12

### Reproduces the problem - code sample

codec = dict(
    type='UDPHeatmap', input_size=(288, 384), heatmap_size=(72, 96), sigma=3,heatmap_type='combined') 

When I add heatmap_type='combined', an AssertionError: target_weights and target have mismatched shapes torch.Size([64, 16]) v.s. torch.Size([64, 48, 96, 72]) will be reported.When it is not added, it will run normally.

### Reproduces the problem - command or script

CUDA_VISIBLE_DEVICES=1   python tools/train.py /data/lsc/mmpose_demo/demo4-hy3096/item-3096-ablation-experiment2/td-hm_hrnet_udp_simam_offset/td-hm_hrnet-w48_udp_simam-384x288/td-hm_hrnet-w48_udp_simam-8xb32-210e_coco-384x288.py

### Reproduces the problem - error message

![1703513277655](https://github.com/open-mmlab/mmpose/assets/117082999/8cafe68e-a234-41c2-87b7-1a04502857b3)

### Additional information

1.How to run properly when using UDP Heatmap with heatmap_type='combined'?

**Comment by SCsleepy** [comment]
_base_ = ['/data/lsc/mmpose_demo/demo4-hy3096/_base_/default_runtime.py']

# # runtime
# train_cfg = dict(max_epochs=210, val_interval=10)
#
# # optimizer
# optim_wrapper = dict(optimizer=dict(
#     type='Adam',
#     lr=5e-4,
# ))
#
# # learning policy
# param_scheduler = [
#     dict(
#         type='LinearLR', begin=0, end=500, start_factor=0.001,
#         by_epoch=False),  # warm-up
#     dict(
#         type='MultiStepLR',
#         begin=0,
#         end=210,
#         milestones=[170, 200],
#         gamma=0.1,
#         by_epoch=True)
# ]
# runtime
train_cfg = dict(max_epochs=350, val_interval=10)

# optimizer
optim_wrapper = dict(optimizer=dict(
    type='Adam',
    lr=1e-3,
))
# learning policy
param_scheduler = [
    dict(
        type='LinearLR', start_factor=1.0e-5, by_epoch=False, begin=0,
        end=1000),
    dict(
        type='CosineAnnealingLR',
        eta_min=5e-05,
        begin=110,
        end=350,
        T_max=240,
        by_epoch=True,
        convert_to_iter_based=True)
]

# automatically scaling LR based on the actual training batch size
auto_scale_lr = dict(base_batch_size=512)

# hooks
default_hooks = dict(checkpoint=dict(save_best='coco/AP', rule='greater'))

# codec settings
# codec = dict(
#     type='UDPHeatmap', input_size=(288, 384), heatmap_size=(72, 96), sigma=3)
codec = dict(
    type='UDPHeatmap', input_size=(288, 384), heatmap_size=(72, 96), sigma=3,heatmap_type='combined')


# model settings
model = dict(
    type='TopdownPoseEstimator',
    data_preprocessor=dict(
        type='PoseDataPreprocessor',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        bgr_to_rgb=True),
    backbone=dict(
        type='HRNet_simam1',
        in_channels=3,
        extra=dict(
            stage1=dict(
                num_modules=1,
                num_branches=1,
                block='BOTTLENECK',
                num_blocks=(4, ),
                num_channels=(64, )),
            stage2=dict(
                num_modules=1,
                num_branches=2,
                block='BASIC',
                num_blocks=(4, 4),
                num_channels=(48, 96)),
            stage3=dict(
                num_modules=4,
                num_branches=3,
                block='BASIC',
                num_blocks=(4, 4, 4),
                num_channels=(48, 96, 192)),
            stage4=dict(
                num_modules=3,
                num_branches=4,
                block='BASIC',
                num_blocks=(4, 4, 4, 4),
                num_channels=(48, 96, 192, 384))),
        init_cfg=dict(
            type='Pretrained',
            checkpoint='https://download.openmmlab.com/mmpose/'
            'pretrain_models/hrnet_w48-8ef0771d.pth'),
    ),
    head=dict(
        type='HeatmapHead',
        in_channels=48,
        out_channels=16,
        deconv_out_channels=None,
        loss=dict(type='KeypointMSELoss', use_target_weight=True),
        # loss=dict(type='KeypointMSELoss', use_target_weight=True),
        # loss=dict(type='KeypointMSELoss'),
        decoder=codec),
    test_cfg=dict(
        flip_test=True,
        flip_mode='heatmap',
        shift_heatmap=False,
    ))

# base dataset settings
dataset_type = 'CocoDataset'
data_mode = 'topdown'
data_root = 'data/coco/'

# pipelines
train_pipeline = [
    dict(type='LoadImage'),
    dict(type='GetBBoxCenterScale'),
    dict(type='RandomFlip', direction='horizontal'),
    dict(type='RandomHalfBody'),
    dict(type='RandomBBoxTransform'),
    dict(type='TopdownAffine', input_size=codec['input_size'], use_udp=True),
    dict(type='GenerateTarget', encoder=codec),
    dict(type='PackPoseInputs')
]
val_pipeline = [
    dict(type='LoadImage'),
    dict(type='GetBBoxCenterScale'),
    dict(type='TopdownAffine', input_size=codec['input_size'], use_udp=True),
    dict(type='PackPoseInputs')
]

# data loaders
train_dataloader = dict(
    batch_size=64,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    dataset=dict(
        metainfo=dict(from_file='/data/lsc/mmpose-main/configs/_base_/datasets/dlc-coco-dekr2-hy3096.py'),
        type=dataset_type,
        data_root=data_root,
        data_mode=data_mode,
        ann_file='/data/lsc/mmpose_demo/demo4-hy3096/data/2-3096/2category/train.json',
        data_prefix=dict(img='/data/lsc/mmpose-main/data/hy-bt-3096/'),
        pipeline=train_pipeline,
    ))
val_dataloader = dict(
    batch_size=32,
    num_workers=2,
    persistent_workers=True,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False, round_up=False),
    dataset=dict(
        metainfo=dict(from_file='/data/lsc/mmpose-main/configs/_base_/datasets/dlc-coco-dekr2-hy3096.py'),
        type=dataset_type,
        data_root=data_root,
        data_mode=data_mode,
        ann_file='/data/lsc/mmpose_demo/demo4-hy3096/data/2-3096/2category/test.json',
        # bbox_file='data/coco/person_detection_results/'
        # 'COCO_val2017_detections_AP_H_56_person.json',
        data_prefix=dict(img='/data/lsc/mmpose-main/data/hy-bt-3096/'),
        test_mode=True,
        pipeline=val_pipeline,
    ))
test_dataloader = val_dataloader

# evaluators
val_evaluator = dict(
    type='CocoMetric',
    ann_file='/data/lsc/mmpose_demo/demo4-hy3096/data/2-3096/2category/test.json')
test_evaluator = val_evaluator
work_dir = '/data/lsc/mmpose_demo/demo4-hy3096/item-3096-ablation-experiment2/td-hm_hrnet_udp_simam_offset/td-hm_hrnet-w48_udp_simam-384x288/work-dir'

**Comment by Ben-Louis** [comment]
The model's codec, head, and loss must be compatible. For 'combined' mode with UDP, refer to https://github.com/open-mmlab/mmpose/blob/main/configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_hrnet-w32_udp-regress-8xb64-210e_coco-256x192.py.

**Comment by SCsleepy** [comment]
> The model's codec, head, and loss must be compatible. For 'combined' mode with UDP, refer to https://github.com/open-mmlab/mmpose/blob/main/configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_hrnet-w32_udp-regress-8xb64-210e_coco-256x192.py.

Thank you, I have successfully solved the problem
