### ISSUE TITLE
demo/body3d_two_stage_img_demo.py文件没有了，3dHPE的文档的示例里还用这个demo/body3d_two_stage_img_demo.py，应该需要修改？[Docs] 

### ISSUE THREAD

**Issue by wuzeyuuu** [open-mmlab/mmpose#2893]
### 📚 The doc issue

demo/body3d_two_stage_img_demo.py文件没有了，3dHPE的文档的示例里还用这个demo/body3d_two_stage_img_demo.py，应该需要修改？

### Suggest a potential alternative/fix

demo/body3d_two_stage_img_demo.py文件没有了，3dHPE的文档的示例里还用这个demo/body3d_two_stage_img_demo.py，应该需要修改？

**Comment by Ben-Louis** [comment]
您好，请问下您说的“3dHPE的文档”具体指哪个页面呢？
