### ISSUE TITLE
[Bug] HybridEncoder is not in the mmpose::model registry

### ISSUE THREAD

**Issue by HoangNTAsilla** [open-mmlab/mmpose#2894]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

mmcv 2.0.1

mmdet 3.1.0

mmpose 1.1.0

### Reproduces the problem - code sample

.

### Reproduces the problem - command or script

**Train** : CUDA_VISIBLE_DEVICES=3 python3 tools/train.py configs/body_2d_keypoint/rtmo/coco/rtmo-s_8xb32-600e_coco-640x640.py --work-dir rtmo/test --amp
**test** : CUDA_VISIBLE_DEVICES=3 python3 tools/test.py configs/body_2d_keypoint/rtmo/coco/rtmo-s_8xb32-600e_coco-640x640.py rtmo-s_8xb32-600e_coco-640x640-8db55a59_20231211.pth
**demo** : python demo/inferencer_demo.py DS_Prob_01/Blinking/Input/g4/4142.jpg --pose2d configs/body_2d_keypoint/rtmo/coco/rtmo-s_8xb32-600e_coco-640x640.py --vis-out-dir vis_results

### Reproduces the problem - error message

Traceback (most recent call last):
File "/home/asilla/hoangnt/RTMO/mmpose/demo/inferencer_demo.py", line 201, in <module>
main()
File "/home/asilla/hoangnt/RTMO/mmpose/demo/inferencer_demo.py", line 195, in main
inferencer = MMPoseInferencer(**init_args)
File "/home/asilla/anaconda3/envs/hoangnt_pe/lib/python3.10/site-packages/mmpose/apis/inferencers/mmpose_inferencer.py", line 93, in init
self.inferencer = Pose2DInferencer(pose2d, pose2d_weights, device,
………..
File "/home/asilla/anaconda3/envs/hoangnt_pe/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
raise KeyError(
KeyError: 'HybridEncoder is not in the mmpose::model registry. Please check whether the value of HybridEncoder is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

### Additional information

I checked Spelling and Case in Registry in Configuration File but not thing happen

**Comment by Ben-Louis** [comment]
`pip install git+https://github.com/open-mmlab/mmpose.git@dev-1.x#egg=mmpose`

**Comment by HoangNTAsilla** [comment]
Thank you, Mr. @Ben-Louis , I tried your command but not thing update : 

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting mmpose
  Cloning https://github.com/open-mmlab/mmpose.git (to revision dev-1.x) to /tmp/pip-install-1jucubce/mmpose_d6ba0d2a41024535b857b441f7f23540
  Running command git clone --filter=blob:none --quiet https://github.com/open-mmlab/mmpose.git /tmp/pip-install-1jucubce/mmpose_d6ba0d2a41024535b857b441f7f23540
  Running command git checkout -b dev-1.x --track origin/dev-1.x
  Switched to a new branch 'dev-1.x'
  Branch 'dev-1.x' set up to track remote branch 'dev-1.x' from 'origin'.
  Resolved https://github.com/open-mmlab/mmpose.git to commit 46ba2da4141b2e9b3be35c86122fd83fcb26d4ca
  Preparing metadata (setup.py) ... done
Requirement already satisfied: chumpy in /home/asilla/anaconda3/envs/hoangnt_pe/lib/python3.10/site-packages (from mmpose) (0.70)
Requirement already satisfied: json_tricks in /home/asilla/anaconda3/envs/hoangnt_pe/lib/python3.10/site-packages (from mmpose) (3.17.3)
.......

And i still have this Error : "HybridEncoder is not in the mmpose::model registry......"

**Comment by Ben-Louis** [comment]
Hi @HoangNTAsilla, what is the mmpose version after reinstalling? If you successfully install the `dev-1.x` branch of mmpose, the version should be 1.2.0

**Comment by HoangNTAsilla** [comment]
@Ben-Louis, for sure, mmpose version is 1.2.0: 

Name: mmpose
Version: 1.2.0
Summary: OpenMMLab Pose Estimation Toolbox and Benchmark.
Home-page: https://github.com/open-mmlab/mmpose
Author: MMPose Contributors
Author-email: openmmlab@gmail.com
License: Apache License 2.0
Location: /home/asilla/anaconda3/envs/hoangnt_pe/lib/python3.10/site-packages
Requires: chumpy, json-tricks, matplotlib, munkres, numpy, opencv-python, pillow, scipy, torchvision, xtcocotools
Required-by: 

But i still have this bug.

**Comment by Ben-Louis** [comment]
Sorry I cannot reproduce the issue on my computer. Perhaps you could check your Python environment, as other users have successfully run RTMO. One hypotheses is that your python and pip do not correspond
