### ISSUE TITLE
[Bug] mmpose depends on the broken package chumpy.

### ISSUE THREAD

**Issue by yurivict** [open-mmlab/mmpose#2898]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

chumpy is broken, see [here](https://github.com/mattloper/chumpy/issues/55).

### Reproduces the problem - code sample

see above

### Reproduces the problem - command or script

see above

### Reproduces the problem - error message

x

### Additional information

x

**Comment by Ben-Louis** [comment]
Hi @yurivict, there might be an issue with the numpy version you are using that is causing trouble in https://github.com/mattloper/chumpy/issues/55.
