### ISSUE TITLE
cannot download pretrained models

### ISSUE THREAD

**Issue by yccnankai** [open-mmlab/mmpose#290]
I can not open the download page: https://mmpose.readthedocs.io/en/latest/pretrained.html, which shows "SORRY This page does      not exist yet."

**Comment by innerlee** [comment]
Pretrained models has been replaced by direct http links in configs. e.g. https://github.com/open-mmlab/mmpose/blob/master/configs/top_down/hrnet/coco-wholebody/hrnet_w32_coco_wholebody_256x192.py#L40-L41

**Comment by yccnankai** [comment]
> Pretrained models has been replaced by direct http links in configs. e.g. https://github.com/open-mmlab/mmpose/blob/master/configs/top_down/hrnet/coco-wholebody/hrnet_w32_coco_wholebody_256x192.py#L40-L41

thanks
