### ISSUE TITLE
模型微调问题咨询

### ISSUE THREAD

**Issue by Syorst** [open-mmlab/mmpose#2901]
### What is the feature?

你好，最近在使用rtmpose识别人体关键点，但是在自定义数据场景下，碰见以下问题
1、关键点识别效果不是很好，如何在保留官方模型的识别效果上进行微调呢？需要把coco数据集整体下载混合自定义数据微调么？还是只需要修改某些配置参数？
2、两人拥抱的场景存在人体重叠与遮挡，这类场景应该如何优化识别效果呢？能否给出一些建议

**Comment by Tau-J** [comment]
Hi @Syorst ，issue 板块主要用于反馈代码bug或文档等问题，关于模型微调的技术交流欢迎加入 MMPose 的社区群，可以在 rtmpose 的 project 页面扫描二维码
