### ISSUE TITLE
[Docs] how to export pose lifting model to onnx? 

### ISSUE THREAD

**Issue by fungtion** [open-mmlab/mmpose#2909]
### 📚 The doc issue

I tried to convert the pose lifting model image-pose-lift_tcn_8xb64-200e_h36m to onnx following the [instruction](https://github.com/open-mmlab/mmpose/blob/dev-1.x/projects/rtmpose/examples/onnxruntime/README.md), but it prompted "AttributeError: 'ConfigDict' object has no attribute 'test_cfg'". Could you help me?

**Comment by Ben-Louis** [comment]
This instruction is specific to RTMPose. For lifting models, you can export it simply using `torch.onnx.export`.

**Comment by fungtion** [comment]
Thanks.
