### ISSUE TITLE
How to evaluate the common keypoints between two keypoint definitions?

### ISSUE THREAD

**Issue by MingHanLee** [open-mmlab/mmpose#2911]
Hello, 

The pre-trained HPE models follow the COCO keypoints definition. Using my custom dataset, I trained a HPE model following the H36M keypoints definition. Is it possible to evaluate the 12 common key points between these two models, as shown below?

Thank you very much!

![image](https://github.com/open-mmlab/mmpose/assets/28431811/84982297-6ff1-42c4-b016-896f7c2d924f)

_Originally posted by @MingHanLee in https://github.com/open-mmlab/mmpose/discussions/2905_

**Comment by Ben-Louis** [comment]
You can refer to the section [Evaluating Across Multiple Datasets](https://mmpose.readthedocs.io/en/latest/user_guides/train_and_test.html#evaluating-across-multiple-datasets) in the document.
