### ISSUE TITLE
[Feature] 有没有适应mmpose新版本的"top_down_pose_tracking_demo_with_mmdet"代码？

### ISSUE THREAD

**Issue by zbl929** [open-mmlab/mmpose#2917]
### What is the feature?

1

**Comment by Tau-J** [comment]
你好 @zbl929 ，新版本暂时没有迁移该功能，我们会将这个需求进行记录。如果你愿意尝试进行迁移并贡献给我们，我们很乐意提供相关的帮助

**Comment by zbl929** [comment]
我想，但是作为一个初学者，特别是mmpose的初学者，发现mmpose从0.x升级到1.x版本改动挺大，实现起来对于我可能有难度。希望你们能够尽快实现它，又或者是帮助我实现它。万分感谢！
