### ISSUE TITLE
[Feature] Report Multi-Person 3D Pose Results in a Common Reference Frame

### ISSUE THREAD

**Issue by garrettTuer** [open-mmlab/mmpose#2919]
### What is the feature?

I am using the MMPoseInferencer to determine 3D keypoint locations of multiple people in a single image. Currently, the reported keypoints for each person are reported in independent reference frames with the corresponding root keypoint set as the origin. I need the results to be in a common reference frame so I can relate the positions/orientations of each person to each other (for example, how close are they, are they facing toward/away from each other, etc.).

Here is a brief code snippet demonstrating how I am using the inferencer:
```
from mmpose.apis.inferencers import MMPoseInferencer

inferencer = MMPoseInferencer(pose3d='human3d')
result_generator = inferencer(my_image_file.jpg)
result = next(result_generator)
# handle results as needed
```

As far as I can tell, the functionality I need is not available in MMPose, but please correct me if I am wrong. I have seen [this issue](https://github.com/open-mmlab/mmpose/issues/2252) with a similar question, though it seems to have been closed without a definitive/working solution. The [linked code](https://github.com/open-mmlab/mmpose/blob/main/tools/dataset_converters/h36m_to_coco.py) in that issue seems to be reliant on having more information than just image files, such as camera parameters, that are not known to me for the images I am using.

Please let me know if what I need is possible and if you have any suggestions for how it could be accomplished. Thank you.

**Comment by Ben-Louis** [comment]
Hi @garrettTuer, do you want to convert the 3D coordinates from the camera coordinate system to the world coordinate system? Unfortunately, this function is not currently supported.

**Comment by garrettTuer** [comment]
@Ben-Louis Yes, I need the 3D coordinates in a world coordinate system so I can determine where each person is in the given scene/image. I figured the functionality wasn't currently supported, but I wanted to double-check that I wasn't overlooking something. Thank you for the confirmation.
