### ISSUE TITLE
resolved

### ISSUE THREAD

**Issue by caochengchen** [open-mmlab/mmpose#2928]
resolved

**Comment by caochengchen** [comment]
Here are your parameters for cocktail13：
loss=dict(
       type='KLDiscretLoss',
       use_target_weight=True,
       beta=10.,
       label_softmax=True),

Here are your parameters for cocktail14：
loss=dict(
       type='KLDiscretLoss',
       use_target_weight=True,
       beta=1.,
       label_softmax=True,
       label_beta=10.,
       mask=list(range(23, 91)),
       mask_weight=0.5,
   ),

I think the error may appear here, is there any parameter configuration file you have not uploaded？

**Comment by Tau-J** [comment]
Hi @caochengchen , `KLDiscretLoss` has been updated for RTMW, please refer to [here](https://github.com/open-mmlab/mmpose/blob/5a3be9451bdfdad2053a90dc1199e3ff1ea1a409/mmpose/models/losses/classification_loss.py#L159)

**Comment by caochengchen** [comment]
thank you very much！
