### ISSUE TITLE
[Docs] How do I addcoordinates to key points?

### ISSUE THREAD

**Issue by surtrmare** [open-mmlab/mmpose#2932]
### 📚 The doc issue

I want to lnow to coordinate the key points of this graph,please!
This is my code for the key points:
python demo/topdown_demo_with_mmdet.py \
    projects/rtmpose/rtmdet/person/rtmdet_nano_320-8xb32_coco-person.py \
    https://download.openmmlab.com/mmpose/v1/projects/rtmpose/rtmdet_nano_8xb32-100e_coco-obj365-person-05d8511e.pth \
    projects/rtmpose/rtmpose/body_2d_keypoint/rtmpose-m_8xb256-420e_coco-256x192.py \
    https://download.openmmlab.com/mmpose/v1/projects/rtmposev1/rtmpose-m_simcc-aic-coco_pt-aic-coco_420e-256x192-63eb25f7_20230126.pth \
    --input demo/R-C.jpg \
    --output-root R-C_text_res\
    --show-kpt-idx
Here are my results
![image](https://github.com/open-mmlab/mmpose/assets/105724924/ffca3f3d-4f4f-4b6d-8d89-ee683070bbfa)

**Comment by Ben-Louis** [comment]
Sorry, we couldn't understand your question. Could you please try rephrasing it or providing more context?

**Comment by surtrmare** [comment]
I am very sorry that my expression is not comprehensive enough, I am a beginner, please be tolerant, thank you! Please take a look at the diagram below, it not only carries out the calibration of key points, but also has corresponding coordinates next to each key point. I would like to know how to improve or add on the code I just sent to achieve this
![qq_pic_merged_1705646049159](https://github.com/open-mmlab/mmpose/assets/105724924/c6c6f749-a51f-4735-a73f-7d8295960c9f)
![qq_pic_merged_1705646040405](https://github.com/open-mmlab/mmpose/assets/105724924/708735a0-e0d9-4d20-bc3c-771d351516c5)

**Comment by Ben-Louis** [comment]
You can add code for drawing coordinates on the image at line 55 in this script https://github.com/open-mmlab/mmpose/blob/5a3be9451bdfdad2053a90dc1199e3ff1ea1a409/demo/topdown_demo_with_mmdet.py#L50-L56

**Comment by Jaizxzx** [comment]
@surtrmare Hey can you share the script for displaying the corresponding coordinates
