### ISSUE TITLE
How to use the function?

### ISSUE THREAD

**Issue by caochengchen** [open-mmlab/mmpose#2936]
### 📚 The doc issue

Taking whole-body 2D key points as an example, how should the following three functions be used?
convert_keypoint_definition
extract_pose_sequence
collate_pose_sequence

**Comment by Ben-Louis** [comment]
Hi, to learn the inference process of pose lifting model, please refer to https://github.com/open-mmlab/mmpose/blob/5a3be9451bdfdad2053a90dc1199e3ff1ea1a409/demo/body3d_pose_lifter_demo.py#L135-L179
