### ISSUE TITLE
Which code generates vis_data?

### ISSUE THREAD

**Issue by seon-creator** [open-mmlab/mmpose#2942]
### 📚 The doc issue

After train model with mmpose, I can find vis_data/scalars.json from the work-dir.
![Screenshot from 2024-01-23 16-26-07](https://github.com/open-mmlab/mmpose/assets/118324988/556cff80-8e49-4b12-a94f-1293f0ba3db6)

When I check the result, I want to know how these values are calculated.
But I can't to find where the code make this scalars.json.
Which code is calculate "acc_pose"?

And I have another question. My custom coco datasets has 5 keypoints of one object from each image.
But why the mAP value isn't used for validation? I can see just AP values.
![Screenshot from 2024-01-23 16-32-35](https://github.com/open-mmlab/mmpose/assets/118324988/d0ef5acf-1d00-4ea0-aee5-229a5d18a204)

**Comment by Ben-Louis** [comment]
1) `acc_pose` is calculated in the `loss` function of the model head you use.
2) "coco/AP" is exactly the "mAP"
