### ISSUE TITLE
[Docs] How to modify RTMO for new dataset

### ISSUE THREAD

**Issue by zgjja** [open-mmlab/mmpose#2943]
### 📚 The doc issue

I want to tranin a RTMO model based on `Halpe26 + COCO-Wholebody` with 26kpts converter, what i have finished:
1. add dataset and converter by refering RTMPose-body8;
2. change num_keypoints of head of RTMO model;
Here are my questions:
  * how to customize the evaluator? these are what i tried:
      * use `CocoWholeBodyMetric`:
        ```language=python3
          val_evaluator = dict(
            type='CocoWholeBodyMetric',
            ann_file=data_root + 'annotations/coco_wholebody_val_v1.0.json',
            nms_mode='none',
            score_mode='bbox',
            gt_converter=dict(
                num_keypoints=26,
                mapping=coco_halpe26
            )
        )
        ```
      this not work during evaluation because the program run `transform_ann()` of `CocoMetric` and did not recognize 26kpts but still 17kpts, causing a index error, does this mean i should pack all kpts (eg. 17body + 6feet) together first? or did i wrongly use the config?;
*  seems there are still other metrics such as mAP as mentioned in #2892  that can be applied to this situation, how can i do this?

**Comment by zgjja** [comment]
seems that i choose wrong metafile, for 26kpts, coco-wholebody meta file should be used rather than the coco one.

**Comment by dugushiyu** [comment]
val_evaluator = dict(
    type='CocoMetric',
    ann_file=data_root + 'annotations/coco_wholebody_val_v1.0.json',
    nms_mode='none',
    score_mode='bbox',
    gt_converter=dict(
        num_keypoints=26,
        mapping=coco_halpe26
    )
)
可行？
