### ISSUE TITLE
[Docs] 关于手机端速度

### ISSUE THREAD

**Issue by fire717** [open-mmlab/mmpose#2944]
### 📚 The doc issue

你好，我想评测一下RTMPose的手机端实际速度，但是翻遍了文档貌似没有看到有现成的android demo可以下载测试。

于是我随便找了一个ncnn推理的demo，替换了模型测试速度，没有改前后处理因为不考虑精度。

测试结果rtm-s在小米14pro(高通骁龙8gen3)上70ms，小米11（骁龙888）上80ms。
而官方宣称的是rtm-s在865上70fps=14ms，rtm-m 30fps=33ms。
差异很大，所以想问下问题出在哪。

1. 我是下载的模型库里的ncnn模型，看detail.json写的是FP32，是否是因为这个原因？如果FP16会正常吗？
2. 为什么官方没有直接提供FP16模型而是FP32，是因为FP16掉点吗？
3. 作为一个主打轻量级移动端的模型，强烈建议直接提供一个Android Demo，比如yolov5、naodet都有。

**Comment by Tau-J** [comment]
hi @fire717 ，感谢对 RTMPose 的关注：
1. 汇报的测速是在ncnn fp16 上小米10实机进行的，fp16相比于fp32有速度提升，不会有精度掉点
2. 模型库上线时间较晚，且由mmdeploy维护，有相关的问题欢迎给mmdeploy提issue
3. 在 rtmpose/examples 目录下提供了一个来自于社区的开源 android demo代码，我们也欢迎你贡献你的代码，我们会乐意加入到example中

**Comment by fire717** [comment]
> hi @fire717 ，感谢对 RTMPose 的关注：
> 
> 1. 汇报的测速是在ncnn fp16 上小米10实机进行的，fp16相比于fp32有速度提升，不会有精度掉点
> 2. 模型库上线时间较晚，且由mmdeploy维护，有相关的问题欢迎给mmdeploy提issue
> 3. 在 rtmpose/examples 目录下提供了一个来自于社区的开源 android demo代码，我们也欢迎你贡献你的代码，我们会乐意加入到example中

收到，感谢回复，OK我如果最近有空做android demo的话会放出来。

**Comment by kc-fantasy** [comment]
> > 你好[@fire717](https://github.com/fire717)，感谢 RTMPose 的关注：
> > 
> > 1. 报告的测速是在ncnn fp16上小米10实机进行的，fp16相比于fp32有提升，不会有精度掉点
> > 2. 模型库上线时间较晚，且由mmdeploy维护，有相关的问题欢迎给mmdeploy提issue
> > 3. 在 rtmpose/examples 目录下提供了一个来自于社区的开源 android 演示代码，我们也欢迎你贡献你的代码，我们会乐意加入到 example 中
> 
> 收到，感谢回复，好的我如果最近有空做android demo的话会放出来。

还有demo推出计划么~新手想学习一下
