### ISSUE TITLE
[Docs] Finding keypoint-body part correspondences

### ISSUE THREAD

**Issue by biotom** [open-mmlab/mmpose#2955]
### 📚 The doc issue

I have a set of keypoints generated with MMPoseInferencer(‘human’). I can’t work out where to find out which keypoint corresponds to which body part. I have so far been unable to find out which model 'human' uses behind the scenes. Could somebody point to where I should look?

### Suggest a potential alternative/fix

Make it clearer which model is being used when an argument like 'human' is passed, or have a page in the documentation that makes that clear (perhaps in the 20-minute tour page?).

**Comment by Tau-J** [comment]
Hi @biotom , thanks for using MMPose. You can refer to [Model Alias](https://mmpose.readthedocs.io/en/dev-1.x/user_guides/inference.html#model-alias) to find the corresponding model of 'human' is `rtmpose-m`. As a 17-keypoint pose estimator, the result follows COCO-format, you can refer to [COCO dataset](https://mmpose.readthedocs.io/en/dev-1.x/dataset_zoo/2d_body_keypoint.html#coco) to get the detailed index definition.

**Comment by biotom** [comment]
Hi @Tau-J - thank you very much for this!
