### ISSUE TITLE
使用MMPoseInferencer进行推理的时候，det模型每次都要从网上下载的问题[Docs] 

### ISSUE THREAD

**Issue by tangdong1994** [open-mmlab/mmpose#2974]
### 📚 The doc issue

我使用MMPoseInferencer进行推理的时候，他所依赖的det模型每一次都要从网上进行下载，就算我传了det model的本地路径也无法生效，还是会从网上下载。
![image](https://github.com/open-mmlab/mmpose/assets/37134249/0149ae61-8679-4e8f-b62f-bcafa1ac8d23)
![image](https://github.com/open-mmlab/mmpose/assets/37134249/59d8f522-c11e-481d-ba57-82151cb518a1)
![image](https://github.com/open-mmlab/mmpose/assets/37134249/31935f42-8878-4d72-8ec2-94539ded4860)
是我使用的方法有问题吗？希望能得到解答，

**Comment by Ben-Louis** [comment]
det_model 要指定对应的 det config

**Comment by tangdong1994** [comment]
> det_model 要指定对应的 det config

![image](https://github.com/open-mmlab/mmpose/assets/37134249/3fbc049e-2e3c-4fdf-8d07-baaf9c3e25e8)
fei非常不好意思，当我使用的det模型是这个的时候，MMPoseInferencer的det_model应该传啥，我试了好多种，行不通，能不能具体说一下我这种情况应该怎么改

**Comment by Ben-Louis** [comment]
1. 这个checkpoint对应的config是 https://github.com/open-mmlab/mmpose/blob/main/demo/mmdetection_cfg/rtmdet_m_640-8xb32_coco-person.py
2. 从URL下载的checkpoint会保存在一个缓存文件夹里，一般情况不会重复下载

**Comment by tangdong1994** [comment]
> 1. 这个checkpoint对应的config是 https://github.com/open-mmlab/mmpose/blob/main/demo/mmdetection_cfg/rtmdet_m_640-8xb32_coco-person.py
> 2. 从URL下载的checkpoint会保存在一个缓存文件夹里，一般情况不会重复下载

🙏
