### ISSUE TITLE
[Bug]  KeyError: 'GroupFisherAlgorithm is not in the mmpose::model registry.

### ISSUE THREAD

**Issue by Priyanshu88** [open-mmlab/mmpose#2981]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

i am running the rtmo config for body 2d keypoint and my config is following, i am directly training this with tools/train.py but not able get it running.

### Reproduces the problem - code sample

_base_ = 'rtmo.py'  # noqa
pretrained_path = 'https://download.openmmlab.com/mmpose/v1/projects/rtmo/rtmo-s_8xb32-600e_coco-640x640-8db55a59_20231211.pth'  # noqa

interval = 10
normalization_type = 'act'
lr_ratio = 0.1

target_flop_ratio = 0.51
input_shape = (1, 3, 256, 192)
##############################################################################

architecture = _base_.model

if hasattr(_base_, 'data_preprocessor'):
    architecture.update({{'data_preprocessor': _base_.data_preprocessor}})
    data_preprocessor = {{}}

architecture.init_cfg = dict(type='Pretrained', checkpoint=pretrained_path)
architecture['_scope_'] = _base_.default_scope

model = dict(
    _delete_=True,
    _scope_='mmrazor',
    type='GroupFisherAlgorithm',
    architecture=architecture,
    interval=interval,
    mutator=dict(
        type='GroupFisherChannelMutator',
        parse_cfg=dict(type='ChannelAnalyzer', tracer_type='FxTracer'),
        channel_unit_cfg=dict(
            type='GroupFisherChannelUnit',
            default_args=dict(normalization_type=normalization_type, ),
        ),
    ),
)

model_wrapper_cfg = dict(
    type='mmrazor.GroupFisherDDP',
    broadcast_buffers=False,
)

optim_wrapper = dict(
    optimizer=dict(lr=_base_.optim_wrapper.optimizer.lr * lr_ratio))

custom_hooks = getattr(_base_, 'custom_hooks', []) + [
    dict(type='mmrazor.PruningStructureHook'),
    dict(
        type='mmrazor.ResourceInfoHook',
        interval=interval,
        demo_input=dict(
            type='mmrazor.DefaultDemoInput',
            input_shape=input_shape,
        ),
        save_ckpt_thr=[target_flop_ratio],
    ),
]

### Reproduces the problem - command or script

run the file with python train.py config.py

### Reproduces the problem - error message

 File "/opt/conda/lib/python3.9/site-packages/mmengine/runner/runner.py", line 462, in from_cfg
    runner = cls(
  File "/opt/conda/lib/python3.9/site-packages/mmengine/runner/runner.py", line 429, in __init__
    self.model = self.build_model(model)
  File "/opt/conda/lib/python3.9/site-packages/mmengine/runner/runner.py", line 836, in build_model
    model = MODELS.build(model)
  File "/opt/conda/lib/python3.9/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/opt/conda/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/opt/conda/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/mmrazor/mmrazor/implementations/pruning/group_fisher/algorithm.py", line 42, in __init__
    super().__init__(architecture, data_preprocessor, init_cfg)
  File "/mmrazor/mmrazor/models/algorithms/base.py", line 67, in __init__
    architecture = MODELS.build(architecture)
  File "/opt/conda/lib/python3.9/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/mmrazor/mmrazor/registry/registry.py", line 49, in build_razor_model_from_cfg
    razor_model = build_from_cfg(cfg, registry, default_args)
  File "/opt/conda/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'GroupFisherAlgorithm is not in the mmpose::model registry. Please check whether the value of `GroupFisherAlgorithm` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

**Comment by Tau-J** [comment]
Hi @Priyanshu88 , RTMO is not supported to conduct pruning.
