### ISSUE TITLE
yolox not found in github

### ISSUE THREAD

**Issue by Beetashoke721** [open-mmlab/mmpose#2988]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

python -c "from mmpose.utils import collect_env; print(collect_env())"
pip list | grep mm

### Reproduces the problem - code sample

 pose2d='human',
    det_model=f'{PATH_TO_MMDET}/configs/yolox/yolox_l_8x8_300e_coco.py',
    det_weights='https://download.openmmlab.com/mmdetection/v2.0/' \
                'yolox/yolox_l_8x8_300e_coco/' \
                'yolox_l_8x8_300e_coco_20211126_140236-d3bd2b23.pth',

### Reproduces the problem - command or script

from mmpose.apis import MMPoseInferencer

# Specify the path to the video file and other necessary parameters
folder_path = "/Users/beetashoke/Downloads/new.mp4"
pose2d_config_path = "Downloads/mmpose/configs/body_2d_keypoint/rtmpose/body8/rtmpose-m_8xb256-420e_body8-256x192.py"
pose2d_weights_path = "Downloads/mmpose/rtmpose-m_simcc-coco_pt-aic-coco_420e-256x192-d8dd5ca4_20230127.pth"
#det_model_name='whole_image'
det_cat_ids=[0]
device="cpu"
det_model='Downloads/mmpose/projects/yolox_pose/configs/yolox-pose_s_8xb32-300e_coco.py'
det_weights="Downloads/mmpose/yoloxpose_s_8xb32-300e_coco-640-56c79c1f_20230829.pth"

# Instantiate the MMPoseInferencer with the specified configuration and weights
inferencer = MMPoseInferencer(pose2d=pose2d_config_path, pose2d_weights=pose2d_weights_path, device=device, det_model=det_model, det_cat_ids=det_cat_ids, det_weights=det_weights)

# Call the inferencer with the folder_path and show=True to display the results
result_generator = inferencer(folder_path, show=True)
results = [result for result in result_generator]

### Reproduces the problem - error message

i did not find the files

### Additional information

this file is missing ,can you tell me where to get this fine,det model file and model weight file?[zksunday](https://github.com/zksunday)

**Comment by Ben-Louis** [comment]
Hi, you can find the detection model and checkpoint from either [this page](https://github.com/open-mmlab/mmpose/blob/main/demo/docs/en/mmdet_modelzoo.md) or [MMDetetion Modelzoo](https://mmdetection.readthedocs.io/en/latest/model_zoo.html).

**Comment by Beetashoke721** [comment]
Thanks a lot for your clarification...🙂
