### ISSUE TITLE
wrong cfg? 

### ISSUE THREAD

**Issue by dmitrysarov** [open-mmlab/mmpose#30]
tried to run demo
![image](https://user-images.githubusercontent.com/19648595/88318020-ccfdf900-cd22-11ea-9ef5-ed5cd7b13df1.png)
image size in config file is single integer but  in _box2cs() expecting sequantial
![image](https://user-images.githubusercontent.com/19648595/88318335-3e3dac00-cd23-11ea-9cfd-8a445d1675ac.png)
I use higher_hrnet32_coco_512x512.py config
![image](https://user-images.githubusercontent.com/19648595/88318503-79d87600-cd23-11ea-9463-91d011b4d1d3.png)

**Comment by innerlee** [comment]
which cfg are used here?

**Comment by innerlee** [comment]
Okay it was higher hrnet, see https://github.com/open-mmlab/mmpose/issues/29
