### ISSUE TITLE
Error in MPII test

### ISSUE THREAD

**Issue by SAIL-LAB155** [open-mmlab/mmpose#300]
Hello! I trained mobilenetv2 with mpii successfully. But when I was testing, error occurs: 

_**[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 7247/7247, 55.7 task/s, elapsed: 130s, ETA:     0sTraceback (most recent call last):
  File "tools/test.py", line 119, in <module>
    main()
  File "tools/test.py", line 115, in main
    print(dataset.evaluate(outputs, args.work_dir, **eval_config))
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmpose-0.8.0-py3.7.egg/mmpose/datasets/datasets/top_down/topdown_mpii_dataset.py", line 211, in evaluate
    uv_error = pos_pred_src - pos_gt_src
ValueError: operands could not be broadcast together with shapes (16,2,7247) (16,2,2958)**_ 

I wonder how to solve it? Thank you.

**Comment by innerlee** [comment]
Could you share the config file? You may remove sensitive info beforehand.

**Comment by SAIL-LAB155** [comment]
All right. The config is shown below. Actually, I haven't modified anything. This is the config in configs/top_down/mobilenet_v2/mpii/mobilenetv2_mpii_256x256.py

**_log_level = 'INFO'
load_from = None
resume_from = None
dist_params = dict(backend='nccl')
workflow = [('train', 1)]
checkpoint_config = dict(interval=10)
evaluation = dict(interval=10, metric='PCKh', key_indicator='PCKh')

optimizer = dict(
    type='Adam',
    lr=5e-4,
)
optimizer_config = dict(grad_clip=None)
# learning policy
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.001,
    step=[170, 200])
total_epochs = 210
log_config = dict(
    interval=50, hooks=[
        dict(type='TextLoggerHook'),
    ])

channel_cfg = dict(
    num_output_channels=16,
    dataset_joints=16,
    dataset_channel=list(range(16)),
    inference_channel=list(range(16)))

# model settings
model = dict(
    type='TopDown',
    pretrained='mmcls://mobilenet_v2',
    backbone=dict(type='MobileNetV2', widen_factor=1., out_indices=(7, )),
    keypoint_head=dict(
        type='TopDownSimpleHead',
        in_channels=1280,
        out_channels=channel_cfg['num_output_channels'],
    ),
    train_cfg=dict(),
    test_cfg=dict(
        flip_test=True,
        post_process=True,
        shift_heatmap=True,
        unbiased_decoding=False,
        modulate_kernel=11),
    loss_pose=dict(type='JointsMSELoss', use_target_weight=True))

data_cfg = dict(
    image_size=[256, 256],
    heatmap_size=[64, 64],
    num_output_channels=channel_cfg['num_output_channels'],
    num_joints=channel_cfg['dataset_joints'],
    dataset_channel=channel_cfg['dataset_channel'],
    inference_channel=channel_cfg['inference_channel'],
    use_gt_bbox=True,
    bbox_file=None,
)

train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='TopDownRandomFlip', flip_prob=0.5),
    dict(
        type='TopDownGetRandomScaleRotation', rot_factor=40, scale_factor=0.5),
    dict(type='TopDownAffine'),
    dict(type='ToTensor'),
    dict(
        type='NormalizeTensor',
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]),
    dict(type='TopDownGenerateTarget', sigma=2),
    dict(
        type='Collect',
        keys=['img', 'target', 'target_weight'],
        meta_keys=[
            'image_file', 'joints_3d', 'joints_3d_visible', 'center', 'scale',
            'rotation', 'flip_pairs'
        ]),
]

val_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='TopDownAffine'),
    dict(type='ToTensor'),
    dict(
        type='NormalizeTensor',
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]),
    dict(
        type='Collect',
        keys=['img'],
        meta_keys=['image_file', 'center', 'scale', 'rotation', 'flip_pairs']),
]

test_pipeline = val_pipeline

data_root = 'data/mpii'
data = dict(
    samples_per_gpu=64,
    workers_per_gpu=2,
    train=dict(
        type='TopDownMpiiDataset',
        ann_file=f'{data_root}/annotations/mpii_train.json',
        img_prefix=f'{data_root}/images/',
        data_cfg=data_cfg,
        pipeline=train_pipeline),
    val=dict(
        type='TopDownMpiiDataset',
        ann_file=f'{data_root}/annotations/mpii_val.json',
        img_prefix=f'{data_root}/images/',
        data_cfg=data_cfg,
        pipeline=val_pipeline),
    test=dict(
        type='TopDownMpiiDataset',
        ann_file=f'{data_root}/annotations/mpii_test.json',
        img_prefix=f'{data_root}/images/',
        data_cfg=data_cfg,
        pipeline=val_pipeline),
)_**

**Comment by jin-s13** [comment]
To evaluate the mpii test dataset, we have to upload the result file to the online server (maintained by MPII team).
We cannot evaluate the performance on mpii_test.json. We only support evaluating on mpii_val.json. So please change this line
https://github.com/open-mmlab/mmpose/blob/a82dd486853a8a471522ac06b8b9356db61f8547/configs/top_down/mobilenet_v2/mpii/mobilenetv2_mpii_256x256.py#L118
to 
ann_file=f'{data_root}/annotations/mpii_val.json',

**Comment by SAIL-LAB155** [comment]
Thany you! Problem solved when I modified it, 
I also wonder that whether testing dataset is still unsupported? Or I should modify somewhere to make it supported?

**Comment by jin-s13** [comment]
Since we do not have the ground-truth for test dataset, we cannot evalute it 'locally'.
If you would like to evaluate the performance on test set, you have to upload the `pred.mat` (which is generated during testing) to the official server via email, according to [the MPII guideline]( http://human-pose.mpi-inf.mpg.de/#evaluation).

**Comment by SAIL-LAB155** [comment]
Oh, I see. After I test the validation data, I failed to find the _pred.mat_. Will the file be generated automatically, or I should assign the path to the keyword "--out"?

**Comment by jin-s13** [comment]
The file will be generated automatically. 
`$MMPOSE/work_dirs/mobilenetv2_mpii_256x256/pred.mat`

**Comment by SAIL-LAB155** [comment]
Thank you , I found it. 
So, if I test the _validation_ data, the script can run successfully and generate a pred.mat  for the validation set. 
While if I test the _test_ data, the error above will also occur, but I can still obtain a pred.mat corresponding to test data.
Is it right?

**Comment by jin-s13** [comment]
Yes.

**Comment by SAIL-LAB155** [comment]
Thank you for your reply~

**Comment by SAIL-LAB155** [comment]
Sorry, there is another problem occurs. When I was testing with testset(5709) images and valset(2729 images), I found that both of them generated a "pred.mat" with completely same size(378.8KB). 
I wonder whether it is normal? In my opinion. since test set has more images, it should generate a bigger .mat file because it contains more data.

**Comment by jin-s13** [comment]
It is strange. I will check this issue soon.

**Comment by jin-s13** [comment]
I tried to reproduce, but it works fine for me.
Please rename the config file, for example to something like `mobilenetv2_mpii_256x256_test.py`. And test again.
`GPUS=8 CPUS_PER_TASK=2 ./tools/slurm_test.sh pat_earth test configs/top_down/mobilenetv2/mpii/mobilenetv2_mpii_256x256_test.py  work_dirs/mobilenetv2_mpii_256x256/latest.pth --eval PCK`
You will find the `pred.mat` in `work_dirs/mobilenetv2_mpii_256x256_test`. The size is about 900K.

**Comment by SAIL-LAB155** [comment]
It works! Thank you!
