### ISSUE TITLE
Confusions about COCO_val2017_detections_AP_H_56_person.json

### ISSUE THREAD

**Issue by KyoukaMinaduki** [open-mmlab/mmpose#301]
HI.

When I am going to train top-down method with COCO dataset, I found that a strange file "COCO_val2017_detections_AP_H_56_person.json" is needed.

Actually, when I was training pose before, I haven't used such a file with box information. Instead, the "person_keypoints_train2017.json" and "person_keypoints_val2017.json" have the box information.

I wonder why a box json in needed in additional? Whether I can use the boxes inside the keypoints json instead of the box json? If the box json is compulsorily needed, are there any scripts in mmdetection or other projects to automatically generate this file?

Thanks a lot.

**Comment by innerlee** [comment]
Good topic for docs? @jin-s13

**Comment by jin-s13** [comment]
"COCO_val2017_detections_AP_H_56_person.json" is not for training. It is only used for evaluation. The boxes (det boxes) are generated by a detector.
person_keypoints_val2017.json also contains bboxes, but boxes (gt boxes) are manually labeled. 
During inference, one can choose to evaluate by gt or det boxes, by setting use_gt=True or False.

**Comment by jin-s13** [comment]
@innerlee I suggest adding a README to introduce the config files.

**Comment by innerlee** [comment]
let's do it

**Comment by KyoukaMinaduki** [comment]
> "COCO_val2017_detections_AP_H_56_person.json" is not for training. It is only used for evaluation. The boxes (det boxes) are generated by a detector.
> person_keypoints_val2017.json also contains bboxes, but boxes (gt boxes) are manually labeled.
> During inference, one can choose to evaluate by gt or det boxes, by setting use_gt=True or False.

Thanks a lot. I think I understand the reason.
And I wonder if I don't want to use gt, what should I set the "bbox_file=''？ Actually I tried to set bbox_file=" " or even comment it,  but there are always some errors showing that "File not find"

**Comment by jin-s13** [comment]
Just set `use_gt_bbox=True` and `bbox_file=''`.

**Comment by KyoukaMinaduki** [comment]
Problem solved! Thanks for your reply.
