### ISSUE TITLE
use specified SEblock for resnet

### ISSUE THREAD

**Issue by syusukee** [open-mmlab/mmpose#302]
hi, I've found that if I want to use SEblock in resnet, it will replace all the original bottleneck with the sebottleneck. How can I only replace part of them and is there a hyperparameter to control it? Hope you can help me, thanks a lot!! @jin-s13

**Comment by jin-s13** [comment]
Hi, currently we do not have such hyper-parameters.
To achieve this, we need to edit this part
https://github.com/open-mmlab/mmpose/blob/a82dd486853a8a471522ac06b8b9356db61f8547/mmpose/models/backbones/resnet.py#L537-L553

Replace `self.block` in line #541 to `SEBottleneck` or `Bottleneck` as you like.

**Comment by syusukee** [comment]
Thanks to your reply!! More specifically, I can add "if-else" here to assign which block to replace? Is this a correct way?

**Comment by jin-s13** [comment]
Yes. That's correct.
