### ISSUE TITLE
COCO dataset question about area.

### ISSUE THREAD

**Issue by dingyf0523** [open-mmlab/mmpose#306]
I'm using my custom dataset. If I did't have segmentation data, Can I set the area as bbox's area?

**Comment by jin-s13** [comment]
That‘s fine.

**Comment by dingyf0523** [comment]
> That‘s fine.

Does this result in reduced accuracy?

**Comment by jin-s13** [comment]
No,  this will not affect training but evaluation. By the way, it is exactly what we do when we use aic dataset. During evaluation, please set use_area=False.
https://github.com/open-mmlab/mmpose/blob/a82dd486853a8a471522ac06b8b9356db61f8547/mmpose/datasets/datasets/top_down/topdown_aic_dataset.py#L113

**Comment by dingyf0523** [comment]
> No, this will not affect training but evaluation. By the way, it is exactly what we do when we use aic dataset. During evaluation, please set use_area=False.
> https://github.com/open-mmlab/mmpose/blob/a82dd486853a8a471522ac06b8b9356db61f8547/mmpose/datasets/datasets/top_down/topdown_aic_dataset.py#L113

I see. Thank you very much.
