### ISSUE TITLE
CUDA RuntimeError too often

### ISSUE THREAD

**Issue by CheungBH** [open-mmlab/mmpose#307]
Hi. I have downloaded MPII dataset and try training top-down model. However, I tried all the model, and my computer can only train mobilenet and shufflenet. When training with resnet/ seresnet50/ hrnet/ hourglass..., Error about running out of CUDA's memory always occur.

Actually, my computer has 2080 and its memory is 8GB. I have also trained seresnet101 before, and the batch size can be set to 8. I wonder whether I should adjust something to avoid it?

**Comment by jin-s13** [comment]
Emmm. Have you tried smaller batchsize?
https://github.com/open-mmlab/mmpose/blob/a82dd486853a8a471522ac06b8b9356db61f8547/configs/top_down/resnet/mpii/res50_mpii_256x256.py#L102

**Comment by CheungBH** [comment]
oh thank you... I haven't paid attention on it .
