### ISSUE TITLE
Inference script for bottom_up model 

### ISSUE THREAD

**Issue by gachiemchiep** [open-mmlab/mmpose#31]
Hello guys.
Thank you for your great contribution. 

I tried some top-down method ([model zoo](https://mmpose.readthedocs.io/en/latest/model_zoo.html) by using the scripts inside **mmpose/demo**, and it works well.

Unfortunately, I can't run the bottom-up model yet. 
Do you guys have any clue how to do this?

Thank you.

**Comment by jin-s13** [comment]
The demo codes for bottom-up models are not available for the time being. We will add it soon.
See #29

**Comment by gachiemchiep** [comment]
@jin-s13 Thank you for your information.

**Comment by xuxixia** [comment]
> Hello guys.
> Thank you for your great contribution.
> 
> I tried some top-down method ([model zoo](https://mmpose.readthedocs.io/en/latest/model_zoo.html) by using the scripts inside **mmpose/demo**, and it works well.
> 
> Unfortunately, I can't run the bottom-up model yet.
> Do you guys have any clue how to do this?
> 
> Thank you.

Hello, I want to know the test model that  you used for mmpose/demo is the model downloaded from the model_zoo ? I download the model from the https://mmpose.readthedocs.io/en/latest/model_zoo.html , but some errors occur and I don't know why. @jin-s13  I will feel very grateful if you can help me.
`python demo/img_demo.py \
    configs/top_down/hrnet/coco/hrnet_w32_coco_256x192.py \
    hrnet_w32_coco_256x192/hrnet_w32_coco_256x192-c78dce93_20200708.pth \
    --img-root tests/data/ --json-file tests/data/test_coco.json \
    --out-img-root demo/results`
![图片1](https://user-images.githubusercontent.com/44183528/88399147-fdb06200-cdf8-11ea-91a2-a905e1bb0fa9.png)

**Comment by gachiemchiep** [comment]
@xuxixia 
I used the video_demo_with_mmdet.py. Here're the commands. 
I didn't meet any error similar to yours.

```bash
# pose_scnet_50
python demo/video_demo_with_mmdet.py     ../mmdetection/configs/ssd/ssd300_coco.py     ../checkpoints/mmdetection/ssd/ssd300_coco_20200307-a92d2092.pth     configs/top_down/scnet/coco/scnet50_coco_256x192.py     ../checkpoints/mmpose/top-down/scnet50_coco_256x192-6920f829_20200709.pth     --video-path ../../examples/girl_dancing_30secs.mp4  --show --out-video-root ./

# pose_hrnet_w32 256x192: .. 
python demo/video_demo_with_mmdet.py     ../mmdetection/configs/ssd/ssd300_coco.py     ../checkpoints/mmdetection/ssd/ssd300_coco_20200307-a92d2092.pth configs/top_down/hrnet/coco/hrnet_w32_coco_256x192.py     ../checkpoints/mmpose/top-down/hrnet_w32_coco_256x192-c78dce93_20200708.pth     --video-path ../../examples/girl_dancing_30secs.mp4  --show --out-video-root ./

# pose_resnet_50 256x192
python demo/video_demo_with_mmdet.py     ../mmdetection/configs/ssd/ssd300_coco.py     ../checkpoints/mmdetection/ssd/ssd300_coco_20200307-a92d2092.pth configs/top_down/resnet/coco/res50_coco_256x192.py     ../checkpoints/mmpose/top-down/res50_coco_256x192-ec54d7f3_20200709.pth      --video-path ../../examples/girl_dancing_30secs.mp4  --show --out-video-root ./
```

**Comment by xuxixia** [comment]
> @xuxixia
> I used the video_demo_with_mmdet.py. Here're the commands.
> I didn't meet any error similar to yours.
> 
> ```shell
> # pose_scnet_50
> python demo/video_demo_with_mmdet.py     ../mmdetection/configs/ssd/ssd300_coco.py     ../checkpoints/mmdetection/ssd/ssd300_coco_20200307-a92d2092.pth     configs/top_down/scnet/coco/scnet50_coco_256x192.py     ../checkpoints/mmpose/top-down/scnet50_coco_256x192-6920f829_20200709.pth     --video-path ../../examples/girl_dancing_30secs.mp4  --show --out-video-root ./
> 
> # pose_hrnet_w32 256x192: .. 
> python demo/video_demo_with_mmdet.py     ../mmdetection/configs/ssd/ssd300_coco.py     ../checkpoints/mmdetection/ssd/ssd300_coco_20200307-a92d2092.pth configs/top_down/hrnet/coco/hrnet_w32_coco_256x192.py     ../checkpoints/mmpose/top-down/hrnet_w32_coco_256x192-c78dce93_20200708.pth     --video-path ../../examples/girl_dancing_30secs.mp4  --show --out-video-root ./
> 
> # pose_resnet_50 256x192
> python demo/video_demo_with_mmdet.py     ../mmdetection/configs/ssd/ssd300_coco.py     ../checkpoints/mmdetection/ssd/ssd300_coco_20200307-a92d2092.pth configs/top_down/resnet/coco/res50_coco_256x192.py     ../checkpoints/mmpose/top-down/res50_coco_256x192-ec54d7f3_20200709.pth      --video-path ../../examples/girl_dancing_30secs.mp4  --show --out-video-root ./
> ```

Okay. Thanks for your reply. And I will check my code again and go to further find whether some details  go wrong.
