### ISSUE TITLE
A demo for calculate the flops of the models

### ISSUE THREAD

**Issue by HuangJunJie2017** [open-mmlab/mmpose#316]
flops is a popular matrix for network study
it is nice to plan a demo for testing the flops of the network according to a specific config~

**Comment by innerlee** [comment]
@jin-s13 is working on it.

**Comment by innerlee** [comment]
Extra note: need to use master branch of mmcv, since one dependent pull request https://github.com/open-mmlab/mmcv/pull/715 was merged just now.
