### ISSUE TITLE
questions about interhand 3d

### ISSUE THREAD

**Issue by yanglilian** [open-mmlab/mmpose#317]
This is a good project. I want to know that whether the accuracy of  the mmpose reproduce the result of interhand 3D in paper. Thanks.

**Comment by jin-s13** [comment]
Currently, we only support 2d hand keypoint estimation on the interhand3.6m dataset. The 3d hand pose&mesh parts are still under development.

**Comment by jin-s13** [comment]
You may also vote here #9 to help us prioritize it.

**Comment by jin-s13** [comment]
This feature request has been added to the TODO list. Will close this issue for now.
