### ISSUE TITLE
is zoomNet in WholeBody model?

### ISSUE THREAD

**Issue by yulong314** [open-mmlab/mmpose#327]
As I look through config files and  inference code, I do not see any "zoomNet" thing.  Just "simple_head" with 133 keypoints .  
    Is wholebody implented with zoomNet as descripted in paper "Whole-Body Human Pose Estimation in the Wild"?

**Comment by jin-s13** [comment]
Not yet. ZoomNet has not been released in MMPose.
We plan to re-implement & release this model in MMPose in a few weeks (possibly in MMPose v0.11).
Will add ZoomNet to our TODO list.

**Comment by yulong314** [comment]
I see, thanks

**Comment by yulong314** [comment]
when will zoomnet version of  mmpose release? I am earger to use it in our project

**Comment by wanghaichuan941221** [comment]
@yulong314 Did you manage to get zoomnet model?

**Comment by yulong314** [comment]
> @yulong314 Did you manage to get zoomnet model?

No, I got none.
