### ISSUE TITLE
hand landmark  data prepare

### ISSUE THREAD

**Issue by aa12356jm** [open-mmlab/mmpose#336]
hi ,i process my handlandmark data as the cropped image ,  the annotation  is only have the landmarks of cropped image ,but the mmpose need the bbox  to crop the hand. i try to  change the code ,but i can not train it , can you give me a little guidance? thanks

for example the code in onehand10k_dataset.py :

`
       
       def _get_db(self):
            """Load dataset."""
            gt_db = []
            num_joints = self.ann_info['num_joints']
            for img_id in self.img_ids:
            ann_ids = self.coco.getAnnIds(imgIds=img_id, iscrowd=False)
            objs = self.coco.loadAnns(ann_ids)
            rec = []
            for obj in objs:
                if max(obj['keypoints']) == 0:
                    continue
                joints_3d = np.zeros((num_joints, 3), dtype=np.float32)
                joints_3d_visible = np.zeros((num_joints, 3), dtype=np.float32)

                keypoints = np.array(obj['keypoints']).reshape(-1, 3)
                joints_3d[:, :2] = keypoints[:, :2]
                joints_3d_visible[:, :2] = np.minimum(1, keypoints[:, 2:3])

                # use 1.25bbox as input
                center, scale = self._xywh2cs(*obj['bbox'][:4], 1.25)   #i do not need this step ,i already cropped the hand from image

                image_file = os.path.join(self.img_prefix,
                                          self.id2name[img_id])

                rec.append({
                    'image_file': image_file,
                    'center': center,
                    'scale': scale,
                    'rotation': 0,
                    'joints_3d': joints_3d,
                    'joints_3d_visible': joints_3d_visible,
                    'bbox': obj['bbox'],
                    'bbox_score': 1
                })
            gt_db.extend(rec)
        return gt_db
`

#use 1.25bbox as input
center, scale = self._xywh2cs(*obj['bbox'][:4], 1.25)  
**i do not need this step ,i have already cropped the hand from image,i do not have the bbox,how can i to change the code  to train ? thanks**

**Comment by jin-s13** [comment]
Please refer to this example of Freihand dataset, where the image are also cropped and resized to 224x224.

https://github.com/open-mmlab/mmpose/blob/9c047f68dc222b37263c98565c06702deaa04a98/mmpose/datasets/datasets/hand/freihand_dataset.py#L98

**Comment by aa12356jm** [comment]
i got it ,thanks
