### ISSUE TITLE
Regarding multi-gpu training

### ISSUE THREAD

**Issue by YibinXie** [open-mmlab/mmpose#339]
Q1: I use normal dataparallel training with this command but got the error.
```
cd ..
python tools/train.py configs/top_down/hrnet/coco/hrnet_w32_coco_256x192.py --gpus 4
```
![image](https://user-images.githubusercontent.com/18461749/101436723-af37d600-3949-11eb-83f5-26521566d3fc.png)

Q2: I use distributed training with this command but got the error.
```
cd ..
bash tools/dist_train.sh configs/top_down/hrnet/coco/hrnet_w32_coco_256x192.py 4
```
![image](https://user-images.githubusercontent.com/18461749/101436802-d4c4df80-3949-11eb-8630-32e9a5b32f80.png)

**Comment by innerlee** [comment]
Can single gpu be trained succefully?

**Comment by YibinXie** [comment]
> Can single gpu be trained succefully?

Yes, single gpu works fine.

**Comment by innerlee** [comment]
For multiple GPUs, the distributed version is recommended.

As for the error, you can set num_workers to 0 in the config and try again

**Comment by YibinXie** [comment]
> For multiple GPUs, the distributed version is recommended.
> 
> As for the error, you can set num_workers to 0 in the config and try again

I set worker to 0 and It's stuck here. 
I never used distributed training before. I think your code is right. Yesterday, I tried to learn how to use pytorch distributed training, and I managed to distributed training a classification task on a very small dataset. But when I use the same way to train COCO dataset for pose estimation. It failed. I think maybe something goes wrong with my machine. 
![image](https://user-images.githubusercontent.com/18461749/101439093-bf9e7f80-394e-11eb-9e1c-2a2fda6a51db.png)
![image](https://user-images.githubusercontent.com/18461749/101439112-c927e780-394e-11eb-9d94-659853b6f427.png)

**Comment by innerlee** [comment]
What's the version of pytorch? Could you try an older version, say 1.3?

**Comment by YibinXie** [comment]
> What's the version of pytorch? Could you try an older version, say 1.3?

My version is 1.6.0, cause I want to use auto mixed precision training.
Ok, I will try an older version later.
Many thanks for your instant reply.

**Comment by YibinXie** [comment]
> What's the version of pytorch? Could you try an older version, say 1.3?

I've tried to reduce my PyTorch to an older version 1.3.0 and 1.4.0, unfortunately, these two versions don't make it in my cluster. My assumption something goes wrong with this cluster (4 M40 24GB). But I didn't figure out the reasons.

My M40 cluster info:
24  Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz
120G memory
4*Tesla M40 24GB
I list the info above, maybe you could give some comments.

Then I clone the codes to another machine with 2 TITAN RTX 24GB with PyTorch 1.6.0. And it works fine with distributed training.

**Comment by innerlee** [comment]
It is nearly impossible to diagnose cluster issues without access to it. Maybe you can find IT to help?

**Comment by YibinXie** [comment]
> It is nearly impossible to diagnose cluster issues without access to it. Maybe you can find IT to help?

Sure, it works anyway. Thanks for your reply.
By the way, have you thought to add the PyTorch amp feature to the project?

**Comment by innerlee** [comment]
We have some fp16 support in progress https://github.com/open-mmlab/mmpose/pull/200. PyTorch amp is one way to do it, and it might be included in near future.

**Comment by innerlee** [comment]
You may post a request here https://github.com/open-mmlab/mmpose/issues/9 to help us prioritize

**Comment by YibinXie** [comment]
> You may post a request here #9 to help us prioritize

Ok, thanks.

**Comment by MrRaptorious** [comment]
Hey, do you know if i can run multiple GPUs on one system, without using the distributed approach? 
I do not have access to network stuff and therefore cant run the train_dist script. 

Does MMPose even support that? I checked the runner.py in MMEngine and it seems like there is no multi GPU training without opening ports or something like that.
