### ISSUE TITLE
UDP checkpoints

### ISSUE THREAD

**Issue by innerlee** [open-mmlab/mmpose#342]

**Comment by HuangJunJie2017** [comment]
![image](https://user-images.githubusercontent.com/31001081/103055480-50bf5880-45d5-11eb-83c7-870a1710090a.png)
emmm,  the performance of configuration HigherHRNet-W32-512x512 with multiscale [2,1,0.5] test in crowdpose is unexpected poor.  [2,1] with 66.1 AP is reasonable. I wounder if there is any implementation difference between mmpose and the orgin HigherHRNet repo?
