### ISSUE TITLE
Speed up training

### ISSUE THREAD

**Issue by innerlee** [open-mmlab/mmpose#344]

**Comment by yaochaorui** [comment]
Using cProfile to figure out the bottleneck, we fully utilize a single GPU by a large batch size. By watching nvidia-smi, we figured out the GPU-Util is not always 100%, which means it waits for the data feeding.

According to the results, generate_target would be the bottleneck.

Config used: 
mmpose/configs/top_down/hrnet/coco-wholebody/hrnet_w48_coco_wholebody_384x288.py
/mmpose/configs/top_down/udp/coco/hrnet_w32_coco_256x192_udp.py

![Screenshot from 2020-12-31 17-00-07](https://user-images.githubusercontent.com/34575412/103403010-a8d3fd00-4b89-11eb-98e6-efd65599aef9.png)

**Comment by yaochaorui** [comment]
_msra_generate_target:
else:
target_weight[joint_id] = joints_3d_visible[joint_id, 0]
0:00:00.000045

feat_stride = image_size / [W, H]
0:00:00.000065

mu_x = int(joints_3d[joint_id][0] / feat_stride[0] + 0.5)
0:00:00.000057

mu_y = int(joints_3d[joint_id][1] / feat_stride[1] + 0.5)
0:00:00.000035

ul = [int(mu_x - tmp_size), int(mu_y - tmp_size)]
0:00:00.000008

br = [int(mu_x + tmp_size + 1), int(mu_y + tmp_size + 1)]
0:00:00.000007

if ul[0] >= W or ul[1] >= H or br[0] < 0 or br[1] < 0:
                        target_weight[joint_id] = 0
0:00:00.000014

The following won't be executed during every iteration.

size = 2 * tmp_size + 1
0:00:00.000007

x = np.arange(0, size, 1, np.float32)
0:00:00.000025

y = x[:, None]
0:00:00.000010

x0 = y0 = size // 2
0:00:00.000006

g = np.exp(-((x - x0)**2 + (y - y0)**2) / (2 * sigma**2))
0:00:00.000153

g_x = max(0, -ul[0]), min(br[0], W) - ul[0]
g_y = max(0, -ul[1]), min(br[1], H) - ul[1]
img_x = max(0, ul[0]), min(br[0], W)
img_y = max(0, ul[1]), min(br[1], H)
target[joint_id][img_y[0]:img_y[1], img_x[0]:img_x[1]] = \
          g[g_y[0]:g_y[1], g_x[0]:g_x[1]]
0:00:00.000045

**Comment by innerlee** [comment]
Use `ms` as unit would be easier to read

**Comment by innerlee** [comment]
Any progress?

**Comment by yaochaorui** [comment]
> Any progress?
This one is  for /mmpose/configs/top_down/udp/coco/hrnet_w32_coco_256x192_udp.py with ms as unit.
```
            with record_time():
                target = np.zeros((num_joints, heatmap_size[1], heatmap_size[0]),
                                dtype=np.float32)

0.2880000000011762

            with record_time():
                tmp_size = factor * 3

0.030999999999892225

            for joint_id in range(num_joints):
                with record_time():
                    feat_stride = (image_size - 1.0) / (heatmap_size - 1.0)

0.07700000000099294

                with record_time():
                    mu_x = int(joints_3d[joint_id][0] / feat_stride[0] + 0.5)

0.07100000000193063

                with record_time():
                    mu_y = int(joints_3d[joint_id][1] / feat_stride[1] + 0.5)

0.07000000000090267

                # Check that any part of the gaussian is in-bounds
                with record_time():
                    ul = [int(mu_x - tmp_size), int(mu_y - tmp_size)]

0.019999999999242846
                with record_time():
                    br = [int(mu_x + tmp_size + 1), int(mu_y + tmp_size + 1)]

0.023999999999801958

                with record_time():
                    if ul[0] >= heatmap_size[0] or ul[1] >= heatmap_size[1] \
                            or br[0] < 0 or br[1] < 0:
                        # If not, just return the image as is
                        target_weight[joint_id] = 0
                        continue

0.04699999999857596

                # # Generate gaussian

                with record_time():
                    size = 2 * tmp_size + 1

0.01899999999821489

                with record_time():
                    x = np.arange(0, size, 1, np.float32)

0.03600000000147929

                with record_time():
                    y = x[:, None]

0.02200000000129876

                with record_time():
                    mu_x_ac = joints_3d[joint_id][0] / feat_stride[0]

0.05099999999913507

                with record_time():
                    mu_y_ac = joints_3d[joint_id][1] / feat_stride[1]

0.06199999999978445

                with record_time():
                    x0 = y0 = size // 2

0.018000000000739647

                with record_time():
                    x0 += mu_x_ac - mu_x

0.027000000002885827

                with record_time():
                    y0 += mu_y_ac - mu_y

0.023000000002326715

                with record_time():
                    g = np.exp(-((x - x0)**2 + (y - y0)**2) / (2 * factor**2))

0.1619999999995514

                with record_time():
                # Usable gaussian range
                    g_x = max(0, -ul[0]), min(br[0], heatmap_size[0]) - ul[0]

0.030999999999892225

                with record_time():
                    g_y = max(0, -ul[1]), min(br[1], heatmap_size[1]) - ul[1]

0.025000000000829914

                with record_time():
                # Image range
                    img_x = max(0, ul[0]), min(br[0], heatmap_size[0])

0.023999999999801958

                with record_time():
                    img_y = max(0, ul[1]), min(br[1], heatmap_size[1]

0.023999999999801958

                with record_time():
                    v = target_weight[joint_id

0.019000000001767603
                if v > 0.5:
                    target[joint_id][img_y[0]:img_y[1], img_x[0]:img_x[1]] = \
                        g[g_y[0]:g_y[1], g_x[0]:g_x[1]]
```

**Comment by yaochaorui** [comment]
> in `ms`
> omitted insignificant operations and bp.zero()
> 
> udp combined target:
> 
> 0.09733205661177635
> np.meshgrid
> 
> 0.011076917871832848
> flatten
> 
> 0.01958012580871582
> dis = x_offset**2 + y_offset**2
> 
> 0.011411961168050766
> np.where

Speed up with tile and repeat
( modified vs original, avgd over 10000 runs)
0.532136919000186
0.5423627550946548

0.5250326895155013
0.5523091702954843

0.5749118802137673
0.5989908247021958

0.5640343049075455
0.5914553523063659

0.5676268137991428
0.5787726647919044

0.5401173901045695
0.5830983532126993

0.5941055492963642
0.6054613754851743

0.5816673572873696
0.5963009350001812

**Comment by innerlee** [comment]
can tile and repeat be avoided, too?

**Comment by yaochaorui** [comment]
> can tile and repeat be avoided, too?

Trying
