### ISSUE TITLE
can't run more than one progress

### ISSUE THREAD

**Issue by syusukee** [open-mmlab/mmpose#348]
when I try to run two progress, it raised the following error:
![微信截图_20201211174240](https://user-images.githubusercontent.com/28001951/101888091-ad377680-3bd8-11eb-92c1-d800eadba923.png)

how can I assign a tcp address for the new progress? Hope you can help me!
@jin-s13

**Comment by innerlee** [comment]
Edit the bash script directly

**Comment by syusukee** [comment]
Could you describe it more specifically? Do you mean I should change the command
`./tools/dist_train.sh configs/top_down/resnet/coco/res50_coco_256x192.py 8 `
to add more things?

**Comment by syusukee** [comment]
I've solved it! Thanks to your help!
