### ISSUE TITLE
CPU only mode

### ISSUE THREAD

**Issue by ioctl-user** [open-mmlab/mmpose#349]
Please add possibility to run mmpose without CUDA using CPU only.

**Comment by jin-s13** [comment]
Inference with cpu only is supported. For example, you can run mmpose demo with `--device=cpu`.

**Comment by ioctl-user** [comment]
Thanks!

May I suggest adding this useful parameter description to the getting_started.md and install.md?

**Comment by ioctl-user** [comment]
With --device=cpu mmpose work fine with most models, but uses only 4 CPU kernels. Is it possible to force CPU number of use autodetect?

**Comment by innerlee** [comment]
We didn't put any restriction on cpu usage.

ffmpeg sometimes uses 4 cores, and opencv might called ffmpeg.

**Comment by ioctl-user** [comment]
If ffmpeg was a bottleneck, 4-cores limitation should appear only part of the running time. But there was no more then 4-cores usage at all.

I use docker build with docker/Dockerfile , but there is no cpu limitation.

**Comment by innerlee** [comment]
You may run this script https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_gui/py_video_display/py_video_display.html#capture-video-from-camera and observe how many cores are used

**Comment by ioctl-user** [comment]
It seems, opencv itself doesn't consume more than 4 cores. Don't you know, is it strong limit?

Anyway, is opencv used for all mmpose operations?

**Comment by innerlee** [comment]
OpenCV is used for loading frames from webcam.

**Comment by ioctl-user** [comment]
> OpenCV is used for loading frames from webcam.

So, cpu consumption should be 4-cores when video is loaded, and more cores when video is processed, right?

**Comment by innerlee** [comment]
How many cores are used during processing depends on numpy cv2 and pytorch.
pytorch uses MKL, and should be able to use all cores.

**Comment by ioctl-user** [comment]
> pytorch uses MKL, and should be able to use all cores.

It's definitely not working as expected.
Can I check, that problem is not in mmpose itself?

**Comment by innerlee** [comment]
> We didn't put any restriction on cpu usage.

**Comment by ioctl-user** [comment]
OMP_NUM_THREADS=  shell variable set cpu limit for torch, but in my case it doesn't allow setting more that 4 CPU. May be it's because, I have only 4 "real" cpu with multithreading.

**Comment by innerlee** [comment]
That makes sense, since paralleling more than the number of physical cores does not offer any help
