### ISSUE TITLE
some configs about  lightweight model of 2d handlandmark? 

### ISSUE THREAD

**Issue by aa12356jm** [open-mmlab/mmpose#352]
hi ,can you provide some configs about  lightweight model of 2d handlandmark?  thanks

**Comment by innerlee** [comment]
Do you want configs or checkpoints?

**Comment by jin-s13** [comment]
Will add some more example configs for mobilenet soon.

**Comment by aa12356jm** [comment]
> Do you want configs or checkpoints?

yes ,i have already get the mobilenetv2 configs by "mmpose/configs/top_down/mobilenet_v2/coco/mobilenetv2_coco_256x192.py", in training, but i want to compare my results with yours,thanks

**Comment by jin-s13** [comment]
Which dataset did you use to train mobilenet? @aa12356jm

**Comment by aa12356jm** [comment]
> Which dataset did you use to train mobilenet? @aa12356jm

oneHand10K

**Comment by innerlee** [comment]
Help us promote 😄

**Comment by aa12356jm** [comment]
ok, if i find  better method ,i will commit a PR,  thanks for mmpose

**Comment by innerlee** [comment]
Actually "promotion" means giving star ⭐ (pull requests are also great though)
