### ISSUE TITLE
Hello, Now the hand model only supports ResNet model? How do I use other models?

### ISSUE THREAD

**Issue by huangzhenjie** [open-mmlab/mmpose#364]

**Comment by jin-s13** [comment]
An example to use mobilenet is `https://github.com/open-mmlab/mmpose/blob/master/configs/top_down/mobilenet_v2/coco/mobilenetv2_coco_256x192.py`.
Please modify the dataset part and make it support the desired hand datasets.

**Comment by innerlee** [comment]
Backbones can be changed in configs.

**Comment by huangzhenjie** [comment]
thanks
