### ISSUE TITLE
what is the Highest resolution pretrain model?

### ISSUE THREAD

**Issue by yulong314** [open-mmlab/mmpose#365]
since I want to recognize keypoints on both fingers and body,  I believe I need a very high resolution hrnet,  such as 720P as well as my Nvidia 3080's 10GB GPU memory can hold to train.  But as I can see that most high resolution available is 384x288.  Is there such a pretrain model  of this hight resolution?

**Comment by innerlee** [comment]
All available pre-trained models has been listed in the modelzoo.

BTW have you tried the current models, and verified that the resolutions are not big enough?

**Comment by jin-s13** [comment]
Yes. The highest resolution we support now is 384x288 for top-down approaches. Larger input size is not very common.

**Comment by yulong314** [comment]
I will retry, and make this question clear  later
