### ISSUE TITLE
The generated video is very slow, and the final mp4 cannot be played

### ISSUE THREAD

**Issue by Deep-learning999** [open-mmlab/mmpose#375]
python demo/bottom_up_video_demo.py \    configs/bottom_up/hrnet/coco/hrnet_w32_coco_512x512.py \  https://download.openmmlab.com/mmpose/bottom_up/hrnet_w32_coco_512x512-bcb8c247_20200816.pth \
    --video-path demo/demo_video.mp4 \
    --out-video-root vis_results
The generated video is very slow, and the final mp4 cannot be played

**Comment by innerlee** [comment]
Could you try to use opencv to encode a video, and see if cv2 is working properly? e.g. https://stackoverflow.com/questions/30509573/writing-an-mp4-video-using-python-opencv

**Comment by Deep-learning999** [comment]
If I want to infer in real time that the frame rate of OpenCV surveillance video is greater than 30, can I recommend a model that can meet the real-time requirements

**Comment by innerlee** [comment]
General guideline:

* use small input size 
* use small backbone
* use 1 clip
* use as less frames as possible

You may also survey deeper about the "real-time" requirement. Typically there is no need to infer every frame. So distinguish between "playback-realtime" and "inference-realtime"

**Comment by Deep-learning999** [comment]
I am performing video inference on cloud GPU, vis_pose_result cannot display the inference result, it should be a problem with opencv, how should I modify it to run on cloud GPU

**Comment by Deep-learning999** [comment]
There is also whether the real-time inference of cloud gpu video can provide a Demo
