### ISSUE TITLE
ImportError: cannot import name `compute_similarity_transform`

### ISSUE THREAD

**Issue by jin-s13** [open-mmlab/mmpose#385]
`ImportError: cannot import name "compute_similarity_transform" from "mmpose.core.evaluation"`

**Reproduction**

```
python tools/pytorch2onnx.py configs/hand/resnet/freihand/res50_freihand_224x224.py ./work_dirs/res50_freihand_224x224/epoch_87.pth --shape [1, 3, 224, 224]
```

**Comment by jin-s13** [comment]
This problem can be resolved by 
replace 
`from mmpose.core.evaluation import compute_similarity_transform`
with
`from mmpose.core.evaluation.mesh_eval import compute_similarity_transform`

**Comment by innerlee** [comment]
Has this been fixed?

**Comment by jin-s13** [comment]
Yes, solved already.
