### ISSUE TITLE
why not do box detection and  keypoint estimation together?

### ISSUE THREAD

**Issue by deep-practice** [open-mmlab/mmpose#388]

**Comment by jin-s13** [comment]
Could you please explain the question in more details?

**Comment by deep-practice** [comment]
In top-down method,we need to get the bboxs first and then get the keypoints for them.They are two seperate tasks which may be suboptimal.

**Comment by jin-s13** [comment]
So you are looking for [Mask-RCNN](https://arxiv.org/pdf/1703.06870.pdf).

**Comment by deep-practice** [comment]
Thx.
