### ISSUE TITLE
Trainng stucks when using multi-gpus

### ISSUE THREAD

**Issue by deep-practice** [open-mmlab/mmpose#389]
Trainng stucks when using multi-gpus
I already set works_per_gpu=0
Btw,it works fine when using single gpu
![QQ截图20201229201957](https://user-images.githubusercontent.com/54052915/103286767-eb77c700-4a1b-11eb-9e21-8886d6458c7b.png)
![error](https://user-images.githubusercontent.com/54052915/103286777-f29ed500-4a1b-11eb-8a5a-c2303c1e0138.png)

**Comment by jin-s13** [comment]
Sorry for the late reply... Have you solved this problem?
Training HRNet_w48 for coco-wholebody dataset may consume large amount of memory.
Have you tried to train some other networks? For example, `configs/top_down/resnet/coco/res50_coco_256x192.py`

**Comment by deep-practice** [comment]
Yes,you'r right.When I use smaller model,it runs smoothly.

**Comment by ioctl-user** [comment]
What is required GPU memory to train HRNet_w48/coco-wholebody?
