### ISSUE TITLE
Wrong path to pretrained model in config files of MSPN

### ISSUE THREAD

**Issue by AndersonZhangyq** [open-mmlab/mmpose#395]
In config files of MSPN, the pretrained model is pointed to `models/pytorch/imagenet/resnet50-renamed.pth`, which is not included in this repo. Those config files should be fixed.

**Comment by AndersonZhangyq** [comment]
And the link to ckpt file of mspn_50 is not working. Please fixed that, too.

**Comment by jin-s13** [comment]
Thanks for reporting the bugs. We will fix the link to the mspn_50 checkpoint via #396.
The config files will be updated soon.

**Comment by wusize** [comment]
I put up a proposal #397 to fix this.
