### ISSUE TITLE
inference speed is low

### ISSUE THREAD

**Issue by ioir123ju** [open-mmlab/mmpose#40]
I simply tested the speed.
GPU: T4
There are two people in the test video.

mmpose:
res50_coco_256x192: 27 FPS
mobilenetv2_coco_256x192: 31 FPS

alphapose:
fast_res50_256x192: 50 FPS

Why is there such a big gap in keypoint_head.

**Comment by innerlee** [comment]
could you share the configs and starting commands of both testing? a random guess is that mmpose is using single-video testing, and maybe alphapose is using batch

**Comment by ioir123ju** [comment]
**mmpose**
` python demo/top_down_video_demo_with_mmdet.py ../mmdetection/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py ../mmdetection/checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth configs/top_down/mobilenet_v2/coco/mobilenetv2_coco_256x192.py checkpoints/mobilenetv2_coco_256x192-d1e58e7b_20200727.pth --video-path /home/juzheng/dataset/action/video/test/fall_down_test_2.avi --show`

in top_down_video_demo_with_mmdet.py
` t1 = time.time()
  pose_results = inference_pose_model(
            pose_model,
            img,
            person_bboxes,
            bbox_thr=args.bbox_thr,
            format='xyxy')
 t2 = time.time()
 print(t2-t1, 1/(t2-t1))`

**alphapose**
I use my own test code.I can make sure the batch size is 1.

**Comment by innerlee** [comment]
Could you also share how to compute fps from this delta time?

**Comment by innerlee** [comment]
Also are the two frameworks using the same set of bboxes?

**Comment by ioir123ju** [comment]
@innerlee 
Yes, I use yolov4 model for both.

**Comment by innerlee** [comment]
> could you share the configs 

> Could you also share how to compute fps from this delta time?

**Comment by jin-s13** [comment]
In MMPose, flip testing is used by default. 
Could you please check if you use flip testing in AlphaPose?

**Comment by ioir123ju** [comment]
@innerlee @jin-s13 
Hi, I tested it with  ‘flip_test=False’ .
res50_coco_256x192: 45 FPS
mobilenetv2_coco_256x192: 50 FPS

This result is close to alphapose, but I think it can still be optimized.
I feel that the FPS of the ‘res50_coco_256x192’ can reach 50.

I will close this question.
Thanks for your answers.

**Comment by innerlee** [comment]
Thanks for your report. Very true that 45fps is not ideal. Speed & Accuracy are top-priorities. We will diagnose & optimize the inference speed soon.

btw how about the training speed? is it normal, slow or fast?

**Comment by ioir123ju** [comment]
I didn’t train, I used your trained model

**Comment by innerlee** [comment]
thanks!
