### ISSUE TITLE
No instructions on how to run inference for videos, like the previous getting started doc

### ISSUE THREAD

**Issue by KulkarniKaustubh** [open-mmlab/mmpose#401]
There used to be clear instructions on how to run inference for a video file and now it is missing. Please bring it back as it helped quite a bit.

Cheers!

**Comment by innerlee** [comment]
Does this help? https://mmpose.readthedocs.io/en/latest/demo.html#d-human-pose-top-down-video-demo

**Comment by KulkarniKaustubh** [comment]
Yes! Thank you. Will close the issue now :)
