### ISSUE TITLE
test set result

### ISSUE THREAD

**Issue by syusukee** [open-mmlab/mmpose#410]
Hi, I want to get the predict result on COCO test set, but now I can only find the evaluation on val set. I've tried to change the config files, but it don't have the according anno files, so I failed. Could you show me how can I get the test set result? Thanks a lot!!
![QQ截图20210108111256](https://user-images.githubusercontent.com/28001951/103970128-7be3a380-51a2-11eb-9cbc-6ea4ec733314.png)
@jin-s13

**Comment by innerlee** [comment]
The error says that one img file is missing. Does that file actually exist?

**Comment by jin-s13** [comment]
To obtain results on the COCO test set, for which ground-truth annotations are hidden, generated results must be uploaded to the evaluation server. 

To generate the results, you have to first prepare the human bounding boxes (detection results). And run with `use_gt_bbox=False`. The results will be saved in the work_dirs. Upload the results to the server, you will get the AP.

**Comment by syusukee** [comment]
I have prepared the detectction results. If I don't use the argument ‘-out’ , I won't get any output results when I run ./tools/dist_test.py. But when I use the argument ‘-out’ to get ‘result.json’, I found that the format is not correct for uploading to COCO server.

**Comment by innerlee** [comment]
what format does coco test server accept?

**Comment by syusukee** [comment]
![微信截图_20210116162811](https://user-images.githubusercontent.com/28001951/104807183-dbcbf100-5817-11eb-91b0-cbc379ee974d.png)
The evalution in training process by default can produce the correct format. But use ./tools/dist_test.py -out result.json can't produce the correct format.

**Comment by syusukee** [comment]
Here has another question
![微信截图_20210116174132](https://user-images.githubusercontent.com/28001951/104808561-20f52080-5822-11eb-95ff-124269806a00.png)
COCO test set don't have the annotations, how to set the 'ann_file' here? Hope you can help me !!

**Comment by jin-s13** [comment]
We need `images` info in the `ann_file`. 
```
 "images": [
        {
            "file_name": "000000000785.jpg",
            "height": 425,
            "width": 640,
            "id": 785
        },
...
]
```


The 'annotations' info can be set as empty.

**Comment by syusukee** [comment]
How can I produce the ann_file? Should I produce it by myself?

**Comment by syusukee** [comment]
Or can I use 'image_info_test-dev2017.json' directly?

**Comment by jin-s13** [comment]
I have added the 'anno' file for test-dev2017. Please download it [here](https://download.openmmlab.com/mmpose/datasets/person_keypoints_test-dev-2017.json)

**Comment by PkuRainBow** [comment]
@jin-s13 Sorry to bother you here, we also meet a strange error when generating the test set prediction:

Here is the test script:

![image](https://user-images.githubusercontent.com/4639578/117560486-d5ac9980-b0c0-11eb-9940-6c81f52935df.png)

We always meet the errors informs us on 

```
"
File "/home/code/mmpose/datasets/datasets/top_down/topdown_coco_dataset.py", line 278, in _load_coco_person_detection_results
    self.id2name[det_res['image_id']])
KeyError: 532481
    self.id2name[det_res['image_id']])
KeyError: 532481
=> Total boxes: 104125
"
```
