### ISSUE TITLE
FreiHAND Dataset annotation

### ISSUE THREAD

**Issue by wawaa** [open-mmlab/mmpose#431]
Hi~It seems I can't download the FreiHAND annotation file(freihand_train.json, freihand_vak.json, freihand_test.json) from the link in 2d_hand_keypoint.md. From the link I can only get a file named 'frei_annotations' Where can I obtain these annotation file? Thanks a lot!

**Comment by jin-s13** [comment]
From the provided link, you can download `frei_annotations.tar`. Right?
This is a compressed package. All you need to do is to untar it.

`tar -xvf frei_annotations.tar`

**Comment by wawaa** [comment]
Sorry. I unzip this .tar file in Windows before and I only got one file, after that I unzip in Ubuntu and I got the three annotation files I needed.

**Comment by jin-s13** [comment]
Good to know that.
