### ISSUE TITLE
Does there any bottomup model benchmark?

### ISSUE THREAD

**Issue by jinfagang** [open-mmlab/mmpose#432]
I saw there all topdown model which needs a standalone detector. Any benchmark compare the bottomup model and topdown model? Since bottomup model have a more faster speed without doubt and topdown *should* have a more reasonable accuracy.
Just want to know if bottomup model can catch up same performance as topdown models.

**Comment by jin-s13** [comment]
We find that in COCO dataset, arkPose with HRNet-w48 backbone (one of the best-performing top-down approaches) can achieve over 77+mAP. 
But HigherHRNet-w48 (one of the SOTA bottom-up approaches) achieves about 71mAP with multi-scale testing.

There are still some gaps between these two types of methods.

By the way, the benchmark can be found in the config directories (eg. [higherhrnet](https://github.com/open-mmlab/mmpose/tree/master/configs/bottom_up/higherhrnet))

**Comment by jinfagang** [comment]
@jin-s13 thank u for your insights. May I ask HigherHRet-w48 can realtime? How's the time of this model.?

In my opinion, to achieve a realtime (e2e what ever model use but need include detector time) pose estimation model, topdown model suffering on preprocess and postprocess in **many boxes** when person are crowded. What do u think?

**Comment by innerlee** [comment]
det can be very fast, like 4ms/frame, so sometimes it is not an issue

**Comment by jinfagang** [comment]
@innerlee when it comes to e2e, compare with postprocess time, model forward time actually not a considerable part. For instance, yolov5s forward time 8ms (1080ti), while most people tested preprocess && postprocess could cost about 10ms. 
The point is, pose estimation should consider that time, and the boxes preprocessing to feed to pose model time. 
Another dimension should be concerned is that, when 2 models runing at one GPU, both of them maybe slower than only 1 model runs on GPU.
