### ISSUE TITLE
what's the speed bottleneck on topdown models

### ISSUE THREAD

**Issue by jinfagang** [open-mmlab/mmpose#439]
Hi, I recently replaced detector with yolov5s and combined with a shufflenetv2 (minimal input size) to test speed.
Here is the result:

![image](https://user-images.githubusercontent.com/21303438/105668976-58965380-5f19-11eb-8f31-2cca6b134dce.png)

Here is what I found:

the speed is very slow when even only 2 person detected. 7fps. And when I try decompose the time I found that detector time dramatically slower than normaly (with only detector).

 what's the biggest speed bottleneck in topdown models? Why the speed much more slower than it should be (let's say we have a detector takes only 8ms, and a pose model takes only 10ms, why it needs 100ms to run a frame)?

**Comment by innerlee** [comment]
Could you analyze the structure of the 100ms? You may use profiling tools.

**Comment by jinfagang** [comment]
@innerlee First of all, 6fps means it needs 166ms per frame, as you can see in the screenshot. I measures whole time from detector to get pose result (vis pose not included), I am not precisely test every stage time, but relatively detector needs about 80ms here, But normally ,v5s should be very fast.

Overall, on topdown models, does there any possibal way to make it realtime ? cause 6 fps far from it

**Comment by jinfagang** [comment]
@innerlee @jin-s13 Hi. 
I just solved the issue of stuck detector when run pose in e2e. Interesting thing is that:

I found the most consuming time is not about detector, not about pose model, but the post-process, for instance, their time could be:

detector: 20ms, pose model: 10 ms , post-process: 100ms

Specifically, I carefully tested every single line of the code, and the conclusion is about this step:

```
# post-processing
    for p in range(coords.shape[0]):
        hm = hms[p]
        px = int(round(float(coords[p][0])))
        py = int(round(float(coords[p][1])))
        if 1 < px < hm_w - 1 and 1 < py < hm_h - 1:
            diff = np.array((hm[py][px + 1] - hm[py][px - 1],
                             hm[py + 1][px] - hm[py - 1][px]))
            coords[p] += np.sign(diff) * .25

    preds = np.zeros_like(coords)
    # transform bbox to scale
    xmin, ymin, xmax, ymax = bbox
    w = xmax - xmin
    h = ymax - ymin
    center = np.array([xmin + w * 0.5, ymin + h * 0.5])
    scale = np.array([w, h])
    trans = get_affine_transform(center, scale, 0, [hm_w, hm_h], inv=1)
```

More specifically, its the `get_affine_trasformation` very time-consuming, casue it calls for every single box, it needs about 3ms to run, for a single box, if we have 10box, then it should be 30ms.

I want ask 2 questions:

1) what's the ffirst part doing in my snippet? seems try to fix some diff?
2) Is affinne-transform necessary both on training and testing. can we disable it? How many AP will effected if not using it?

**Comment by innerlee** [comment]
Cool result. Now we can improve speed by optimizing affine-trans.

You could visualize what it does, and see if there are something could be done

**Comment by jinfagang** [comment]
@innerlee Can u explain what's it does? I uncomment it seems doest effect final result

**Comment by jin-s13** [comment]
1. The first part is to achieve higher performance. Adding a small shift (0.25) to avoid sub-pixel localisation problem (the heatmap is downsampled 4x relative to the input).
2. It is possible that we replace `get_affine_transform` with a lightweight operation.This part is to remap the keypoint coordinates (in the heatmap) to those of the original image.

**Comment by jinfagang** [comment]
@jin-s13 what's possible more cheaper operation can replace affine-trans?

**Comment by jinfagang** [comment]
@jin-s13 I can try replace it and do some experiments first.

**Comment by jin-s13** [comment]
`coords` is the coordinates in the heatmap. We want to get the coordinates in the original image. 
First, we have to scale the `coords` to image-coordinate-system (multiply by 4, if heatmap size is 1/4 of the input size). 
Then we need to use `scale` of the bounding boxes to re-scale the `coords`. 
Finally, use `center` to add a shift to the `coords`.

**Comment by jin-s13** [comment]
Some coordinate transformation steps.

**Comment by jinfagang** [comment]
@jin-s13 When will u guys experiment on this ? I think for mmpose to goes further on deployment, this is really important to replace this operation. If you guys update one, I will try export some topdown model to TensorRT, aiming to get a accurate and fast, realtime pose model

**Comment by jin-s13** [comment]
Of course, we will do that. 
I did not think that `get_affine_transform` was slow. Thanks for pointing it out.

**Comment by jinfagang** [comment]
@jin-s13 case by case, you can test the time, it's 2ms, but every single box will call once. takes most time of post-processing, of couse not only that is time-consuming.

**Comment by jinfagang** [comment]
![image](https://user-images.githubusercontent.com/21303438/105835698-151a1300-6007-11eb-9e28-741d7b05103d.png)
compare with get coordinates from heatmap, it's 10x slower.
