### ISSUE TITLE
Sigma and Joint settting

### ISSUE THREAD

**Issue by carolchenyx** [open-mmlab/mmpose#440]
Dear all, thanks for your great job. I have few questions about the code. I realized there are different joint_weights and sigmas for each trained dataset. For example, as for topdown_aic_dataset.py and topdown_coco_dataset.py, the sigma and joint weights are different. I would like to know there are any method or standard to set these parameters? Waiting for your reply. Super thanks.

**Comment by innerlee** [comment]
They come from the original dataset. @jin-s13 we can add comments giving links to the source.

**Comment by carolchenyx** [comment]
Super thanks for giving the link to the source.

lizz <notifications@github.com> 于2021年1月25日周一 下午4:07写道：

**Comment by innerlee** [comment]
btw have you starred the repo?

**Comment by carolchenyx** [comment]
Sure Starred and Fok!! By the way, do u have any idea to change the sigma
or weight?

lizz <notifications@github.com> 于2021年1月25日周一 下午4:17写道：

**Comment by jin-s13** [comment]
sigma is the normalized factor of the human skeletal keypoint, which is calculated by the standard deviation of human annotation result. It is used to measure the annotation quality, and will be used for evaluation (mAP). sigma should NOT be changed.

`joint_weights` are used for training. It assigns different weights for different joint types. But in our default setting, we do not use `joint_weights`. We simply use the same loss weight for all joint types.

**Comment by jin-s13** [comment]
We copy the sigma from the official dataset evaluation codes.
For example, 
https://github.com/cocodataset/cocoapi/blob/8c9bcc3cf640524c4c20a9c40e89cb6a2f2fa0e9/PythonAPI/pycocotools/cocoeval.py#L523

**Comment by carolchenyx** [comment]
Got it. Thanks lizz n Jas.

Jas <notifications@github.com> 于2021年1月25日周一 下午4:27写道：

**Comment by innerlee** [comment]
Related info has been added to source code in https://github.com/open-mmlab/mmpose/pull/441
