### ISSUE TITLE
Aic Dataset Result  Abnormal

### ISSUE THREAD

**Issue by chaowentao** [open-mmlab/mmpose#452]
The current aic result is about 30 mAP both top-down and bottom-up methods. I think the evaluation may exist some bugs.

**Comment by innerlee** [comment]
Could you please give more details on the suspected bug?

**Comment by jin-s13** [comment]
I checked the original AIChallenger [paper](https://arxiv.org/abs/1711.06475).
The results of the baseline models are reported. OpenPose, the winner of MSCOCO 2016 keypoint competition, scores only 0.296 mAP-12 on the dataset. And the top-down baseline model scores a 0.228 mAP-12 value and a 0.234 mAP-14 value. Our reported 30mAP is reasonable (the evaluation metrics are too strict). 

There might be some differences between our evaluation codes and the [official ones](https://github.com/AIChallenger/AI_Challenger_2017/blob/52014e0defbbdd85bf94ab05d308300d5764022f/Evaluation/keypoint_eval/keypoint_eval.py).  

In fact, I am a little bit hesitant to use their evaluation codes directly. 
e.g. If I understand correctly, in the official AIC evaluation [codes](https://github.com/AIChallenger/AI_Challenger_2017/blob/52014e0defbbdd85bf94ab05d308300d5764022f/Evaluation/keypoint_eval/keypoint_eval.py#L151), it is possible that one predicted human pose matches multiple ground truth poses (please correct me, if I am wrong). However, in standard evaluation metrics, this should not happen.

**Comment by chaowentao** [comment]
@jin-s13 Thank you for your hard work. I also check the evaluation codes between mmpose and aic. Thanks again.
