### ISSUE TITLE
human detection result of CrowdPose

### ISSUE THREAD

**Issue by holyYodu** [open-mmlab/mmpose#454]
When I was preparing the CrowdPose data, I didn't find the mentioned `det_for_crowd_test_0.1_0.5.json` file, can you provide this file? or if I need to get it by myself,  what's the meaning of `0.1` and `0.5`, are they config parameters of yolo3?

**Comment by jin-s13** [comment]
data preparation guide can be found [here](https://github.com/open-mmlab/mmpose/blob/master/docs/tasks/2d_body_keypoint.md#crowdpose).

You can download the detection result from [crowdpose_annotations](https://download.openmmlab.com/mmpose/datasets/crowdpose_annotations.tar).

**Comment by holyYodu** [comment]
thanks for you quick reply, I have got the file and I'll read the documentation more carefully next time, lol

**Comment by innerlee** [comment]
Star the repo if it helps you 😃
