### ISSUE TITLE
when i run python demo/top_down_img_demo.py  , how can i get the json file?

### ISSUE THREAD

**Issue by xinzi2018** [open-mmlab/mmpose#47]

**Comment by jin-s13** [comment]
You can simply save the pose_results into a json file.
line71-72 `pose_results = inference_pose_model(pose_model, image_name, person_bboxes, format='xywh')`

**Comment by innerlee** [comment]
Maybe the question was to ask how to generate the input json file for arbitrary image?

**Comment by xinzi2018** [comment]
yes😄,i want to ask how to generate the input json file for arbitrary image




| |
戴玲娜
邮箱：dln2014@126.com
|

签名由 网易邮箱大师 定制

On 08/04/2020 09:33, lizz wrote:

Maybe the question was to ask how to generate the input json file for arbitrary image?

**Comment by jin-s13** [comment]
The json file follows the COCO format.
Please check [COCO webset](https://cocodataset.org/#format-data) for more details about the data format.

---------------------------------------
Kindly note that `demo/top_down_img_demo.py` requires the ground-truth human bounding box annotations as input.
If you do not have such annotations, please use `demo/top_down_img_demo_with_mmdet.py`.

**Comment by xinzi2018** [comment]
谢谢，我后来换成了 "demo/top_down_img_demo_with_mmdet.py"来运行，但发现是先调用mmdector检测出来框 然后再使用mmpose做姿态检测，这个时候我发现有时候mmdetector会多检测出来框，从而也就导致了姿态检测结果有好些重叠的部分

**Comment by innerlee** [comment]
thanks for the info.
you may need to do some post-processing to suppress superfluous bboxes.
