### ISSUE TITLE
Use pretrained model

### ISSUE THREAD

**Issue by lweingart** [open-mmlab/mmpose#472]
Hello Team,

I need to draw human pose detection, hand pose detection and face detection on some videos, very much like what can be seen on your github page with the 133-keypoint whole-body pose estimation demo.
I therefore installed mmpose and everything but I'm a bit overwhelmed, as this is not really my area of expertise.
I'm doing this to help on an artistic project where the artist wants to use a camera that looks at people, and the video would be displayed on screen with the drawings of the whole-body pose estimation.

When I look at your many datasets and networks architectures that are supported, I have to admit that I feel a bit lost, not really knowing what to use.

I don't need to train any neural network at this point, nor do I want to create a new dataset, I just would like to use an already trained model and apply it on a camera footage.

Could you please give me some advice on how to use your amazing tools collection to achieve that goal please ?
I must say that between top-down, or bottom-up, or any of the other many possibilities and many possible configs available, I'm having difficulties to choose.

I would really appreciate the help if someone could help me in this endeavour.
Thank you very much in advance guys.

**Comment by jin-s13** [comment]
Hi @lweingart ,
Thanks for your interest in our work. 
Here is the command to generate the wholebody pose demo video in the github page, which is similar to the top-down [demo](https://mmpose.readthedocs.io/en/latest/demo.html#d-human-pose-top-down-video-demo). 

```shell
python demo/top_down_video_demo_with_mmdet.py \
demo/mmdetection_cfg/faster_rcnn_r50_fpn_1x_coco.py \ http://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \
configs/top_down/darkpose/coco-wholebody/hrnet_w48_coco_wholebody_384x288_dark_plus.py \
https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_coco_wholebody_384x288_dark-f5726563_20200918.pth \
--video-path demo/demo.mp4 \
--out-video-root vis_results
```

Note:
1. `video-path` is the input video, and `out-video-root` is the path to save results.
2. It takes time to run the demo. Please be patient : )

**Comment by lweingart** [comment]
Hi @jin-s13,

Thank you so much for your help, it worked indeed :-)

I have 2 questions now that come to my mind.
The first is that when I look at your documentation, it usually says to use something along the lines of
`python somthing.py ${MMPOSE_CONFIG_FILE} ${MMPOSE_CHECKPOINT_FILE}... etc`
but in the command you gave me it looks like you used two config files and two checkpoints file. What does that mean ?

And my second question, as you mentioned it takes quite some time to run on a video.
Would you have knowledge of an algorithm that could maybe do a simplified version (meaning with less points, like maybe without that facial landmarks and finger positions), that could run much faster, to do it on a real time video feed ?

Thanks again for your help and your availability, it's awesome.

**Comment by jin-s13** [comment]
1) For multi-human pose estimation, top-down approaches are very popular. Top-down approaches require both the human bounding box detection model and the 133-keypoint pose estimation model, so there are two config files and checkpoint files. 

```
python demo/top_down_video_demo_with_mmdet.py \
    ${MMDET_CONFIG_FILE} ${MMDET_CHECKPOINT_FILE} \
    ${MMPOSE_CONFIG_FILE} ${MMPOSE_CHECKPOINT_FILE} \
    --video-path ${VIDEO_FILE} \
    --output-video-root ${OUTPUT_VIDEO_ROOT} \
    [--show --device ${GPU_ID or CPU}] \
    [--bbox-thr ${BBOX_SCORE_THR} --kpt-thr ${KPT_SCORE_THR}]
```

2-a) Whole-body (133-keypoint) pose estimation is challenging, so it usually requires a large model which will take some time to run. Please follow the guideline [here](https://mmpose.readthedocs.io/en/latest/demo.html#id1) to speed up.

Modify the config file as following:
```
flip_test=False
post_process='default'
```

2-b) Only human pose
If you only need 17-keypoint human pose estimation, there are also smaller models to try. For example, [mobilenet-based models](https://mmpose.readthedocs.io/en/latest/top_down_models.html#mobilenetv2-inverted-residuals-and-linear-bottlenecks). Similarly, you can run the demo

```
python demo/top_down_video_demo_with_mmdet.py \
demo/mmdetection_cfg/faster_rcnn_r50_fpn_1x_coco.py \ 
http://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \
configs/top_down/mobilenet_v2/coco/mobilenetv2_coco_256x192.py \
https://download.openmmlab.com/mmpose/top_down/mobilenetv2/mobilenetv2_coco_256x192-d1e58e7b_20200727.pth \
--video-path demo/demo.mp4 \
--out-video-root vis_results
```

3-b) Faster human bounding box detector
You may also choose a faster human bounding box detection model. They can be found in [MMDetection](https://mmdetection.readthedocs.io/en/latest/model_zoo.html).

**Comment by lweingart** [comment]
Thank you so much for your help @jin-s13, I really appreciate.
I will try your advice for speeding things up.
Thanks again

Cheers
