### ISSUE TITLE
About the bottom up method

### ISSUE THREAD

**Issue by CheungBH** [open-mmlab/mmpose#473]
Hello. Are there any papers about the bottom-up method?  Like the model structure, image preprocesses, and loss function.

**Comment by innerlee** [comment]
See the cites in docs here https://mmpose.readthedocs.io/en/latest/bottom_up_models.html#associative-embedding-ae-hrnet

**Comment by jin-s13** [comment]
Currently, MMPose supports

```
@inproceedings{newell2017associative,
  title={Associative embedding: End-to-end learning for joint detection and grouping},
  author={Newell, Alejandro and Huang, Zhiao and Deng, Jia},
  booktitle={Advances in neural information processing systems},
  pages={2277--2287},
  year={2017}
}
```
and
```
@inproceedings{cheng2020higherhrnet,
  title={HigherHRNet: Scale-Aware Representation Learning for Bottom-Up Human Pose Estimation},
  author={Cheng, Bowen and Xiao, Bin and Wang, Jingdong and Shi, Honghui and Huang, Thomas S and Zhang, Lei},
  booktitle={Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition},
  pages={5386--5395},
  year={2020}
}
```

Other popular bottom-up papers include:

1. [Realtime Multi-person 2D Pose Estimation Using Part Affinity Fields ](https://arxiv.org/pdf/1611.08050.pdf)- Cao, Z., Simon, T., Wei, S., & Sheikh, Y. (CVPR 2017)
2. [PifPaf: Composite Fields for Human Pose Estimation](https://arxiv.org/abs/1903.06593) - Sven Kreiss, Lorenzo Bertoni, Alexandre Alahi (CVPR 2019)
3. [MultiPoseNet: Fast Multi-Person Pose Estimation using Pose Residual Network](https://arxiv.org/pdf/1807.04067.pdf) - Muhammed Kocabas, Salih Karagoz, Emre Akbas (ECCV 2018)
4. [Mixture Dense Regression for Object Detection and Human Pose Estimation](https://arxiv.org/abs/1912.00821) - Ali Varamesh, Tinne Tuytelaars (CVPR 2020)

**Comment by CheungBH** [comment]
Thank you for your reply.
By the way, I wonder are there any references mentioning how to determine the kernel size of gaussian distribution? I found them most of them are fixed values.

**Comment by jin-s13** [comment]
Please check this.
Rethinking the Heatmap Regression for Bottom-up Human Pose Estimation. Luo et al. ArXiv 2021
In this paper, the authors propose a scale-adaptive heatmap regression (SAHR) method, which adaptively adjusts the Gaussian kernel.

**Comment by CheungBH** [comment]
Thanks for your help!
