### ISSUE TITLE
possibly incorrect affine transformation generation

### ISSUE THREAD

**Issue by khanhha** [open-mmlab/mmpose#474]
Hello

I would like to ask about a possible problem regarding the function 
```python
def get_affine_transform(center,
                         scale,
                         rot,
                         output_size,
                         shift=(0., 0.),
                         inv=False):
```

in this function, the src_dir is supposed to a displacement vector from the center point to the mid-point of the top line of the bounding box, but in this code, src_dir uses src_w instead.  This causes the problem of shrunk height sometimes. I think that src_dir should be equal to [0, src_h*-0.5] instead and then the third src point should take into account src_w.

![image](https://user-images.githubusercontent.com/2276264/107927582-7a628380-6f77-11eb-9622-36c845eb992c.png)

However, this function get_affine_transform is the same across many top-down pose estimation repositories. So I wonder if there is anything missing in my understanding or there is actually a bug here?

**Comment by liuxin9608** [comment]
Hi,

Before applying this function, we make sure that `src_w / src_h = dst_w / dst_h`. 

Therefore,
```
src_dir = rotate_point([0., src_w * -0.5], rot_rad)
dst_dir = np.array([0., dst_w * -0.5])
```
or
```
src_dir = rotate_point([0., src_h * -0.5], rot_rad)
dst_dir = np.array([0., dst_h * -0.5])
```
do not make any differences.

**Comment by liuxin9608** [comment]
Since `src_h` will be easier to understand. Maybe we should use `src_h` instead. @jin-s13 @innerlee

**Comment by innerlee** [comment]
> This causes the problem of shrunk height sometimes

@khanhha Did you met this problem in experiments?

**Comment by khanhha** [comment]
@innerlee: thanks for your clarification. I met the shrunk height problem in some experiments. But now I am thinking that it could be due to some problems with my code base, not this function.  I am still not sure about the exact reason, but I think the issue can be closed here.
Thanks all of you for your support.
Best
