### ISSUE TITLE
Is there  a way to checkpoint submodule of network (such as backbone)

### ISSUE THREAD

**Issue by pablovela5620** [open-mmlab/mmpose#475]
So I've been looking at the checkpoint callback, and can't figure out or know a way to checkpoint only part of the network. 

The use case for this is as follows (similar to the Zoomnet paper):

 I want to pre-train a network backbone (such as resnet50) on 2d hand data from something like 0nehand10k or Panoptic dataset, then after pretraining, I want to save JUST the resnet50 backbone in order to be used for 3d pose/mesh estimation with something like the Freihand/Interhand dataset with a completely different network head. Is this use case possible with mmpose?

**Comment by jin-s13** [comment]
By setting `pretrained='torchvision://resnet50`, only the backbone weights of resnet50 will be loaded and the head will be ignored. So if I understand correctly, nothing has to be changed in your use case.

BTW, `save_checkpoint` function is in mmcv/runner/epoch_based_runner.py
https://github.com/open-mmlab/mmcv/blob/1c2e665ad69638c0e0ff27a9adfa481b9a8b0712/mmcv/runner/epoch_based_runner.py#L130

In case, you want to modify the `load_checkpoint` function. https://github.com/open-mmlab/mmpose/blob/fd8442f499f1e2a35b36f9c3065f7b489dc283ea/mmpose/models/backbones/utils/utils.py#L6

**Comment by pablovela5620** [comment]
Gotcha, just to make sure I understand. If I set the `pretrained=` path to the path of whatever trained network I have (let assume I want to use the topdown hand network on onehand10k annotations rather than the torchvision pretrained resnet on imagenet) this would ignore the keypoint head of that trained network and just load the backbone.

So using the pretrained ckpt you guys provide for pose_resnet50 I would set in my backbone `pretrained=https://download.openmmlab.com/mmpose/hand/resnet/res50_onehand10k_256x256-e67998f6_20200813.pth`
and use that resnet to train a hand 3d pose/mesh model?

On top of this, I wanted to ask if it would be possible to save individual modules of a network for a use case such as for [Monocular Real-time Hand Shape and Motion Capture using Multi-modal Data](https://github.com/CalciferZh/minimal-hand)

![image](https://user-images.githubusercontent.com/25287427/108391150-67ea8300-71df-11eb-895b-19832060a636.png)


In this case, there are multiple submodules that can be trained independently or end-to-end. For example their inverse kinematics network. It takes as an input the 2.5d root-relative predictions from the 3d network and returns rotations/joint angles and is dependent on the noisy predictions from the network. One could just run the network once to create a prediction dataset, but I believe that it is this wouldn't work as well since it would adequately model the noise the network is generating (which the IK network is attempting to solve) 


It would be ideal for me to be able to save the inverse kinematics network separately from the 2d/3d keypoint predictions. This is so I could train it once and use it with different networks to see if it will generalize to different keypoint outputs. 

 I was looking at the [checkpoint hook](https://github.com/open-mmlab/mmcv/blob/9ecd6b0d5ff9d2172c49a182eaa669e9f27bb8e7/mmcv/runner/hooks/checkpoint.py#L9) but it looks like that uses `runner.save_checkpoint()` meaning that the way it looks I would have to modify mmcv rather than just using a checkpoint. I'm not sure if thats the case or not

**Comment by jin-s13** [comment]
1. Yes, you can directly load the pose_resnet50 pre-trained on onehand10k.
2. You can try to add a customized checkpoint hook to do so. Some tutorials about adding hooks can be found [here](https://github.com/open-mmlab/mmpose/blob/master/docs/tutorials/6_customize_runtime.md#customize-hooks).
