### ISSUE TITLE
Question about mmcv

### ISSUE THREAD

**Issue by August0424** [open-mmlab/mmpose#500]
It seems that mmcv is not auto-installed and included in requirements.txt. However, it is required when running demo code in mmpose. I mannully installed mmcv and then such error vanished.

**Comment by innerlee** [comment]
Yes this is the case.

We will make this more explict in the installation guide https://github.com/open-mmlab/mmpose/blob/master/docs/install.md

**Comment by August0424** [comment]
> 
> 
> Yes this is the case.
> 
> We will make this more explict in the installation guide https://github.com/open-mmlab/mmpose/blob/master/docs/install.md

OK, thank you.
