### ISSUE TITLE
draw human pose detection on my videos

### ISSUE THREAD

**Issue by clytze0216** [open-mmlab/mmpose#511]
Hello ,mmpose team!
  your work is so great !
 now I try to draw human pose detection on my videos. I tried using the following command:
```
python demo/top_down_video_demo_with_mmdet.py \
demo/mmdetection_cfg/faster_rcnn_r50_fpn_1x_coco.py \ 
http://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \
configs/top_down/darkpose/coco-wholebody/hrnet_w48_coco_wholebody_384x288_dark_plus.py \
https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_coco_wholebody_384x288_dark-f5726563_20200918.pth \
--video-path demo/demo.mp4 \
--out-video-root vis_results
```
But my server can't directly connect to the Internet to download these.pth files.So I downloaded them offline and uploaded them to the server, but then I didn't know how to import these files, I met a lot of problems, could you please help me, this will be very important for me!Thank you very much!!!!
  Looking forward to your reply~

**Comment by innerlee** [comment]
You can download the ckpts manually and upload to the server, and then use the full local path in the command

**Comment by clytze0216** [comment]
> You can download the ckpts manually and upload to the server, and then use the full local path in the command

thanks for your quick reply~
but I met some errors,as below:
```
(open-mmlab) lixiang@star-SYS-4028GR-TR:~/zcl/mmpose-master$ python demo/bottom_up_video_demo.py \
>     --video-path demo/demo_video.mp4 \
>     --out-video-root vis_results \
>      configs/bottom_up/hrnet/coco/hrnet_w32_coco_512x512.py \
>     check/hrnet_w32_coco_512x512-bcb8c247_20200816.pth

Use load_from_local loader
(open-mmlab) lixiang@star-SYS
```
ecause I am  new in this field, sorry for any interruption

**Comment by innerlee** [comment]
Please post the full error message

**Comment by clytze0216** [comment]
I'm sorry, I didn't express myself before.When I make scrips, it doesn't produce errors. Instead, it produces the following sentence: Use load_from_local loader.

But there is no output..... sorry again

**Comment by innerlee** [comment]
The `Use load_from_local loader` is an info message saying that the checkpoint is loaded from local files.

You can change the input video to a different, easier video, or try to run the image demo

**Comment by innerlee** [comment]
@jin-s13 the demo.mp4 in the repo is the one used in pose-tracking btw. I guess it is the reason why there are no output
