### ISSUE TITLE
about the speed of bottom-up

### ISSUE THREAD

**Issue by ZhangLei999** [open-mmlab/mmpose#512]
I tested the speed by this
"python demo/bottom_up_video_demo.py \
    configs/bottom_up/mobilenet/coco/mobilenetv2_coco_512x512.py \
    models/mobilenetv2_coco_512x512-4d96e309_20200816.pth \
    --video-path demo/demo_video.mp4 \
    --out-video-root vis_results"

My GPU is 2080ti.
The speed is 25 FPS.

The config file I edited to speed up.

**Comment by ZhangLei999** [comment]
Is this speed normal?

**Comment by innerlee** [comment]
Yes

**Comment by innerlee** [comment]
The current inference speed is not optimized. It will be part of the work in [March](https://github.com/open-mmlab/mmpose/issues/513)

**Comment by ZhangLei999** [comment]
> The current inference speed is not optimized. It will be part of the work in [March](https://github.com/open-mmlab/mmpose/issues/513)

所以在mmpose里，top-down比bottom-up要快。。。。

**Comment by innerlee** [comment]
I guess most time is spent on drawing.

**Comment by jin-s13** [comment]
It is normal that in some cases (especially when the number of people < 3, and with a light-weight human detector), top-down methods are more faster.
Bottom-up approaches have to process the whole image (input resolution = 512x512)... But top-down pose estimator only processes the regions of human bounding boxes (input resolution = 256x192).

**Comment by ZhangLei999** [comment]
I understand
