### ISSUE TITLE
Memory imbalance problem when training hrnet!

### ISSUE THREAD

**Issue by YongtaoGe** [open-mmlab/mmpose#526]
![屏幕快照 2021-03-20 22 12 43](https://user-images.githubusercontent.com/22744013/111873084-97043800-89c9-11eb-8857-b8b1ab728c2e.png)

**Comment by YongtaoGe** [comment]
I just set "multiscale_output=True"

**Comment by innerlee** [comment]
What full command line is used? Is `dist_train.sh` or `train.py` used?

And please post the full screenshot of nvidia-smi.

**Comment by YongtaoGe** [comment]
@innerlee dist_train.sh is used. I replace the mmpose's implementation of hrnet with mmdetection's implementation and the memory imbalance problem just disappear.

**Comment by innerlee** [comment]
@ly015 could you try and see if this can be reproduced?

**Comment by liqikai9** [comment]
@YongtaoGe Thanks for your error report and we appreciate it a lot. But we still need more information about the command your run to locate the problem. So could you please offer us detail about the following questions?

- What command or script did you run?

- What config did you run?

- Did you make any modifications on the code or config?
- What dataset did you use?

**About the environment**

1. Please run `PYTHONPATH=${PWD}:$PYTHONPATH python mmpose/utils/collect_env.py` to collect necessary environment information and paste it here.

2. Please post the full screenshot of `nvidia-smi`.
