### ISSUE TITLE
Confusing about API usage

### ISSUE THREAD

**Issue by namirinz** [open-mmlab/mmpose#528]
First of all I'm using api for build up model and training.

1. Do I have to get the bounding box of all human object and then give the bbox to the model to get the keypoints?
2. I'm very confuse with **img_metas** argument in model.forward_test. The description told that it's the Information about data augmentation. Do you have any example on how to define it?
3. Can you make some python or jupyter notebook (colab) code about using of mmpose api?

**Comment by namirinz** [comment]
I saw in the demo file there are 2 method to run inference model
1. use gt (Ground Truth) bounding box as pose_result.
2. use mmdet for extract bounding box as pose_result.

The question is why TopDown model need to have CNN backbone to extracting feature if we can extract the feature of human using mmdet model.

Let say you use this method (mmdet for getting the bounding box of human and then use the TopDown model to get the keypoints pose output) how will these model (mmdet + TopDown) can be faster than using only Keypoint R-CNN (Faster R-CNN architecture) in Torchvision that archive (5-8 fps). 

Btw. I'm doing pose estimation.

**Comment by jin-s13** [comment]
The CNN features from mmdet model focuses on detecting human bounding boxes. And they are not suitable for detecting keypoints.

How to make the inference more faster:
1） Use smaller human detector
2）Use smaller keypoint detector
3）We do not have to run human detection at each frame. We can roughly estimate the human detection boxes with predicted keypoints (the tightest bounding box that covers all the keypoints) at previous time step.

Faster R-CNN with a keypoint head does not always produce accurate keypoint detection results.

**Comment by namirinz** [comment]
So does the TopDown model take all cropped image by bounding box then do feature extracting using TopDown backbone and output the keypoint is it?

**Comment by jin-s13** [comment]
yes. TopDown model extracts features from cropped images.

**Comment by namirinz** [comment]
Oh, it's clear now.

Thank you for your answering and this awesome open-source.
