### ISSUE TITLE
get mAP results

### ISSUE THREAD

**Issue by MIMOS-Chien** [open-mmlab/mmpose#531]
Hi, may I know which program can produce mAP if I want to test my own datasets? Thank you

**Comment by innerlee** [comment]
Generally speaking, if the dataset format is similar to one of the supported datasets, then you can use the tools/test.py to get evaluation results. 

Give more details to get more specific help :)

**Comment by MIMOS-Chien** [comment]
You guys are very kind indeed. I appreciate.  So far, I just wish to use the off-line video that capturing people come to work at the office to compare them to Hrnet results for my work. For your information, I tested few recorded videos for the case demo/bottom_up_video_demo.py in Window 10, it seems very slow. Therefore, I suspect whether it doesn;t use GPU but rather than cpu (the PC is not with me, I run remotely). My pc has two GPUs, how do I know whether it runs on GPU? I have installed cudnn 7.6.5, but has no NCCL that seems as for linux system. Do I need NCCL? TQ

**Comment by MIMOS-Chien** [comment]
Hi, just aware that in the bottom_up_video_demo.py there is a statement "parser.add_argument(
        '--device', default='cuda:0', help='Device used for inference')". Is this the one ensure GPU is using? Just put 
python demo/bottom_up_video_demo.py ... --device cuda:0  ?

**Comment by jin-s13** [comment]
1) You may run `nvidia-smi` to check the status of GPU.
2) Yes, setting `--device cuda:0` will use gpu0 for inference. 

BTW. If there are only a small number of people (<3) in the scene, the top-down approach may be more efficient.
We also find that the visualization part takes a lot of time. You may also disable visualization for faster inference.

**Comment by MIMOS-Chien** [comment]
I try mmpose botom_up case either using off-line video or on line camera , it is too slow (almost like no movement). I am very new to this pose estimation. Less than one month for setting up  this stuff in Window and yet to have time to read any related papers. Is there any suggestions for speed improvement? There is another question which is how long need to take for formiliar with this pose estimation area for a freshman to prepare for further development? TQ

**Comment by innerlee** [comment]
For speed concerns, pls open a new issue :)

**Comment by MIMOS-Chien** [comment]
Hi Lee, Sorry for inconvenience caused. I am not aware this. I will raise this issue as a new issue. May I know this software is developed by you only or a group of persons. TQ

**Comment by MIMOS-Chien** [comment]
I am not familiar with linux that is why I work on Window.  I found a problem to execute tools/test.py when I see *.sh file. I then try to *.bat file, however. I cannot complete this translation. Anyone can help

#!/usr/bin/env bash

CONFIG=$1
CHECKPOINT=$2
GPUS=$3
PORT=${PORT:-29500}

PYTHONPATH="$(dirname $0)/..":$PYTHONPATH \
python -m torch.distributed.launch --nproc_per_node=$GPUS --master_port=$PORT \
    $(dirname "$0")/test.py $CONFIG $CHECKPOINT --launcher pytorch ${@:4}

I am trying to translate it to *.bat file below but I am not able to translate certain parts. I think "@echo off" in this case is not necessary, isn;t it?

@echo off

CONFIG=%1%
CHECKPOINT=%2%
GPUS=%3%
PORT=%PORT:-29500%  , ======>is this correct compared to PORT=${PORT:-29500} ?

python -m torch.distributed.launch --nproc_per_node=%GPUS% --master_port=%PORT%  c:/mmpose/test.py %CONFIG% %CHECKPOINT%  --launcher pytorch %@:4%

======> What is this actually? %@:4%

In order to avoid wasting time in. sh, I feel that we do not need to execute the file in this way. I can run the test.py as below

**./tools/dist_test.sh configs/top_down/resnet/coco/res50_coco_256x192.py \
    checkpoints/SOME_CHECKPOINT.pth 1 \
    --eval mAP**


python -m torch.distributed.launch --nproc_per_node=1 --master_port=-29500 C:/MMPOSE/configs/bottom_up/hrnet/coco/hrnet_w32_coco_512x512.py  C:/MMPOSE/path/hrnet_w32_coco_512x512-bcb8c247_20200816.pth --img-root  C:/MMPOSE/A10/data/coco/  --json-file C:/MMPOSE/tests/data/coco/test_coco.json  --eval C:/MMPOSE/mAP

The result will finally be writen in this folder C:/MMPOSE/mAP, am I right?

I put my own dataset (10K++ files) in C:/MMPOSE/A10/data/coco/ and use the original .json file to test it, but it has nothing in the mAP folder.

Hope to get few suggestions soon. TQVM

**Comment by innerlee** [comment]
Hi @MIMOS-Chien , contributors of mmpose are here :) https://github.com/open-mmlab/mmpose/graphs/contributors 

> PORT=${PORT:-29500}

If ENV PORT exists, then use it; otherwise use value 29500

> %@:4%

Expand all remaining arguments from the 4-th

If you have only one gpu card, then there is no need to use this script. Directly run `python toos/train.py ...` is good
