### ISSUE TITLE
Error while trying to export to ONNX pose model

### ISSUE THREAD

**Issue by ccdsad** [open-mmlab/mmpose#533]
**torch 1.6.0
mmpose 0.12.0
mmcv 1.2.7
onnx 1.8.1**
`_python3 tools/pytorch2onnx.py /mmpose/configs/top_down/hrnet/coco/hrnet_w48_coco_256x192.py /mmpose/data/hrnet_w48_coco_256x192-b9e0b3ab_20200708.pth --output-file /mmpose/data/hrnet_w48_coco_256x192-b9e0b3ab_20200708.onnx --show --verify_`

`Use load_from_http loader
2021-03-26 15:30:08,692 - mmpose - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: head.0.0.0.conv1.weight, head.0.0.0.bn1.weight, head.0.0.0.bn1.bias, head.0.0.0.bn1.running_mean, head.0.0.0.bn1.running_var, head.0.0.0.conv2.weight, head.0.0.0.bn2.weight, head.0.0.0.bn2.bias, head.0.0.0.bn2.running_mean, head.0.0.0.bn2.running_var, head.0.0.0.conv3.weight, head.0.0.0.bn3.weight, head.0.0.0.bn3.bias, head.0.0.0.bn3.running_mean, head.0.0.0.bn3.running_var, head.0.0.0.downsample.0.weight, head.0.0.0.downsample.1.weight, head.0.0.0.downsample.1.bias, head.0.0.0.downsample.1.running_mean, head.0.0.0.downsample.1.running_var, head.0.1.0.conv1.weight, head.0.1.0.bn1.weight, head.0.1.0.bn1.bias, head.0.1.0.bn1.running_mean, head.0.1.0.bn1.running_var, head.0.1.0.conv2.weight, head.0.1.0.bn2.weight, head.0.1.0.bn2.bias, head.0.1.0.bn2.running_mean, head.0.1.0.bn2.running_var, head.0.1.0.conv3.weight, head.0.1.0.bn3.weight, head.0.1.0.bn3.bias, head.0.1.0.bn3.running_mean, head.0.1.0.bn3.running_var, head.0.1.0.downsample.0.weight, head.0.1.0.downsample.1.weight, head.0.1.0.downsample.1.bias, head.0.1.0.downsample.1.running_mean, head.0.1.0.downsample.1.running_var, head.0.2.0.conv1.weight, head.0.2.0.bn1.weight, head.0.2.0.bn1.bias, head.0.2.0.bn1.running_mean, head.0.2.0.bn1.running_var, head.0.2.0.conv2.weight, head.0.2.0.bn2.weight, head.0.2.0.bn2.bias, head.0.2.0.bn2.running_mean, head.0.2.0.bn2.running_var, head.0.2.0.conv3.weight, head.0.2.0.bn3.weight, head.0.2.0.bn3.bias, head.0.2.0.bn3.running_mean, head.0.2.0.bn3.running_var, head.0.2.0.downsample.0.weight, head.0.2.0.downsample.1.weight, head.0.2.0.downsample.1.bias, head.0.2.0.downsample.1.running_mean, head.0.2.0.downsample.1.running_var, head.1.0.0.conv1.weight, head.1.0.0.bn1.weight, head.1.0.0.bn1.bias, head.1.0.0.bn1.running_mean, head.1.0.0.bn1.running_var, head.1.0.0.conv2.weight, head.1.0.0.bn2.weight, head.1.0.0.bn2.bias, head.1.0.0.bn2.running_mean, head.1.0.0.bn2.running_var, head.1.0.0.conv3.weight, head.1.0.0.bn3.weight, head.1.0.0.bn3.bias, head.1.0.0.bn3.running_mean, head.1.0.0.bn3.running_var, head.1.0.0.downsample.0.weight, head.1.0.0.downsample.1.weight, head.1.0.0.downsample.1.bias, head.1.0.0.downsample.1.running_mean, head.1.0.0.downsample.1.running_var, head.1.1.0.conv1.weight, head.1.1.0.bn1.weight, head.1.1.0.bn1.bias, head.1.1.0.bn1.running_mean, head.1.1.0.bn1.running_var, head.1.1.0.conv2.weight, head.1.1.0.bn2.weight, head.1.1.0.bn2.bias, head.1.1.0.bn2.running_mean, head.1.1.0.bn2.running_var, head.1.1.0.conv3.weight, head.1.1.0.bn3.weight, head.1.1.0.bn3.bias, head.1.1.0.bn3.running_mean, head.1.1.0.bn3.running_var, head.1.1.0.downsample.0.weight, head.1.1.0.downsample.1.weight, head.1.1.0.downsample.1.bias, head.1.1.0.downsample.1.running_mean, head.1.1.0.downsample.1.running_var, head.2.0.0.conv1.weight, head.2.0.0.bn1.weight, head.2.0.0.bn1.bias, head.2.0.0.bn1.running_mean, head.2.0.0.bn1.running_var, head.2.0.0.conv2.weight, head.2.0.0.bn2.weight, head.2.0.0.bn2.bias, head.2.0.0.bn2.running_mean, head.2.0.0.bn2.running_var, head.2.0.0.conv3.weight, head.2.0.0.bn3.weight, head.2.0.0.bn3.bias, head.2.0.0.bn3.running_mean, head.2.0.0.bn3.running_var, head.2.0.0.downsample.0.weight, head.2.0.0.downsample.1.weight, head.2.0.0.downsample.1.bias, head.2.0.0.downsample.1.running_mean, head.2.0.0.downsample.1.running_var, head.3.0.0.conv1.weight, head.3.0.0.bn1.weight, head.3.0.0.bn1.bias, head.3.0.0.bn1.running_mean, head.3.0.0.bn1.running_var, head.3.0.0.conv2.weight, head.3.0.0.bn2.weight, head.3.0.0.bn2.bias, head.3.0.0.bn2.running_mean, head.3.0.0.bn2.running_var, head.3.0.0.conv3.weight, head.3.0.0.bn3.weight, head.3.0.0.bn3.bias, head.3.0.0.bn3.running_mean, head.3.0.0.bn3.running_var, head.3.0.0.downsample.0.weight, head.3.0.0.downsample.1.weight, head.3.0.0.downsample.1.bias, head.3.0.0.downsample.1.running_mean, head.3.0.0.downsample.1.running_var, fc.weight, fc.bias, stage4.2.fuse_layers.1.0.0.0.weight, stage4.2.fuse_layers.1.0.0.1.weight, stage4.2.fuse_layers.1.0.0.1.bias, stage4.2.fuse_layers.1.0.0.1.running_mean, stage4.2.fuse_layers.1.0.0.1.running_var, stage4.2.fuse_layers.1.2.0.weight, stage4.2.fuse_layers.1.2.1.weight, stage4.2.fuse_layers.1.2.1.bias, stage4.2.fuse_layers.1.2.1.running_mean, stage4.2.fuse_layers.1.2.1.running_var, stage4.2.fuse_layers.1.3.0.weight, stage4.2.fuse_layers.1.3.1.weight, stage4.2.fuse_layers.1.3.1.bias, stage4.2.fuse_layers.1.3.1.running_mean, stage4.2.fuse_layers.1.3.1.running_var, stage4.2.fuse_layers.2.0.0.0.weight, stage4.2.fuse_layers.2.0.0.1.weight, stage4.2.fuse_layers.2.0.0.1.bias, stage4.2.fuse_layers.2.0.0.1.running_mean, stage4.2.fuse_layers.2.0.0.1.running_var, stage4.2.fuse_layers.2.0.1.0.weight, stage4.2.fuse_layers.2.0.1.1.weight, stage4.2.fuse_layers.2.0.1.1.bias, stage4.2.fuse_layers.2.0.1.1.running_mean, stage4.2.fuse_layers.2.0.1.1.running_var, stage4.2.fuse_layers.2.1.0.0.weight, stage4.2.fuse_layers.2.1.0.1.weight, stage4.2.fuse_layers.2.1.0.1.bias, stage4.2.fuse_layers.2.1.0.1.running_mean, stage4.2.fuse_layers.2.1.0.1.running_var, stage4.2.fuse_layers.2.3.0.weight, stage4.2.fuse_layers.2.3.1.weight, stage4.2.fuse_layers.2.3.1.bias, stage4.2.fuse_layers.2.3.1.running_mean, stage4.2.fuse_layers.2.3.1.running_var, stage4.2.fuse_layers.3.0.0.0.weight, stage4.2.fuse_layers.3.0.0.1.weight, stage4.2.fuse_layers.3.0.0.1.bias, stage4.2.fuse_layers.3.0.0.1.running_mean, stage4.2.fuse_layers.3.0.0.1.running_var, stage4.2.fuse_layers.3.0.1.0.weight, stage4.2.fuse_layers.3.0.1.1.weight, stage4.2.fuse_layers.3.0.1.1.bias, stage4.2.fuse_layers.3.0.1.1.running_mean, stage4.2.fuse_layers.3.0.1.1.running_var, stage4.2.fuse_layers.3.0.2.0.weight, stage4.2.fuse_layers.3.0.2.1.weight, stage4.2.fuse_layers.3.0.2.1.bias, stage4.2.fuse_layers.3.0.2.1.running_mean, stage4.2.fuse_layers.3.0.2.1.running_var, stage4.2.fuse_layers.3.1.0.0.weight, stage4.2.fuse_layers.3.1.0.1.weight, stage4.2.fuse_layers.3.1.0.1.bias, stage4.2.fuse_layers.3.1.0.1.running_mean, stage4.2.fuse_layers.3.1.0.1.running_var, stage4.2.fuse_layers.3.1.1.0.weight, stage4.2.fuse_layers.3.1.1.1.weight, stage4.2.fuse_layers.3.1.1.1.bias, stage4.2.fuse_layers.3.1.1.1.running_mean, stage4.2.fuse_layers.3.1.1.1.running_var, stage4.2.fuse_layers.3.2.0.0.weight, stage4.2.fuse_layers.3.2.0.1.weight, stage4.2.fuse_layers.3.2.0.1.bias, stage4.2.fuse_layers.3.2.0.1.running_mean, stage4.2.fuse_layers.3.2.0.1.running_var

Use load_from_local loader
(tensor([[[[ 1.1089,  1.2976, -0.7773,  ...,  0.1393, -0.9787, -1.6021],
          [-0.8798, -0.4811, -0.2573,  ...,  2.4992,  0.7031,  1.1780],
          [ 0.7244, -0.5616, -0.3523,  ...,  0.0705, -1.6258, -0.2869],
          ...,
          [-2.3166, -2.3540, -0.1844,  ...,  1.1812, -0.6098,  0.2409],
          [-0.7312, -0.8936,  1.1560,  ...,  0.1052,  0.9125,  0.8941],
          [-0.4385,  0.5488, -0.0906,  ...,  0.5174, -0.7097,  1.2512]],
         [[-0.3881, -1.1083,  1.1543,  ..., -0.0057, -1.0371, -0.0032],
          [ 1.0984,  0.7420,  0.0899,  ..., -1.4393,  1.8812, -0.6361],
          [ 0.7815, -0.1293,  1.7944,  ...,  0.0747, -1.2661,  1.2634],
          ...,
          [ 0.1966, -0.6950,  0.2304,  ...,  1.6142,  0.0857,  0.4234],
          [ 0.2355, -0.3616, -1.0391,  ...,  0.2622,  0.6302, -0.1319],
          [-0.2151, -1.7872, -0.6336,  ...,  0.0716, -1.6525,  0.3336]],
         [[-0.1019, -0.1744, -0.9579,  ...,  0.0509,  0.3032, -0.9522],
          [ 0.5588, -0.2200, -1.1883,  ...,  0.0913,  0.0780, -0.2696],
          [-0.9466,  1.0140,  0.3099,  ..., -0.1496, -1.1897, -1.1879],
          ...,
          [ 1.0160,  0.5915,  0.5485,  ..., -0.8599, -0.1470,  2.8266],
          [ 0.0499,  0.6748,  0.3553,  ..., -0.0605,  1.1264,  0.2383],
          [-0.7020,  1.5827,  0.0464,  ...,  0.3458, -1.0875, -0.6159]]]]),)
Traceback (most recent call last):
  File "tools/pytorch2onnx.py", line 152, in <module>
    verify=args.verify)
  File "tools/pytorch2onnx.py", line 74, in pytorch2onnx
    opset_version=opset_version)
  File "/opt/conda/lib/python3.7/site-packages/torch/onnx/__init__.py", line 208, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py", line 92, in export
    use_external_data_format=use_external_data_format)
  File "/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py", line 530, in _export
    fixed_batch_size=fixed_batch_size)
  File "/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py", line 384, in _model_to_graph
    fixed_batch_size=fixed_batch_size, params_dict=params_dict)
  File "/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py", line 188, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/opt/conda/lib/python3.7/site-packages/torch/onnx/__init__.py", line 241, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py", line 791, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/onnx/symbolic.py", line 17, in symbolic_fn
    g, interpolate_mode, args)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/onnx/onnx_utils/symbolic_helper.py", line 253, in _get_interpolate_attributes
    scales = _interpolate_get_scales_if_available(g, scales)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/onnx/onnx_utils/symbolic_helper.py", line 232, in _interpolate_get_scales_if_available
    'fs') != -1 and not _is_none(scales[0])
  File "/opt/conda/lib/python3.7/site-packages/mmcv/onnx/onnx_utils/symbolic_helper.py", line 66, in _maybe_get_const
    return _parse_arg(value, desc)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/onnx/onnx_utils/symbolic_helper.py", line 43, in _parse_arg
    return [float(v) for v in tval]
  File "/opt/conda/lib/python3.7/site-packages/torch/tensor.py", line 450, in __iter__
    raise TypeError('iteration over a 0-d tensor')`

**Comment by HoBeom** [comment]
How about using this function. I think it was work.
https://github.com/open-mmlab/mmpose/blob/eaafaa7630b1a37226e306b36c82dae610c4fd06/mmpose/apis/inference.py#L17

**Comment by ccdsad** [comment]
It didn't work for me, I ran into exactly the same error.
`python3 tools/pytorch2onnx.py /mmpose/configs/top_down/hrnet/coco/hrnet_w48_coco_256x192.py /mmpose/data/hrnet_w48_coco_256x192-b9e0b3ab_20200708.pth --output-file /mmpose/data/hrnet_w48_coco_256x192-b9e0b3ab_20200708.onnx --show --verify`

_Traceback (most recent call last):
  File "tools/pytorch2onnx.py", line 150, in <module>
    verify=args.verify)
  File "tools/pytorch2onnx.py", line 75, in pytorch2onnx
    opset_version=opset_version)
  File "/opt/conda/lib/python3.7/site-packages/torch/onnx/__init__.py", line 208, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py", line 92, in export
    use_external_data_format=use_external_data_format)
  File "/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py", line 530, in _export
    fixed_batch_size=fixed_batch_size)
  File "/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py", line 384, in _model_to_graph
    fixed_batch_size=fixed_batch_size, params_dict=params_dict)
  File "/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py", line 188, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/opt/conda/lib/python3.7/site-packages/torch/onnx/__init__.py", line 241, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py", line 791, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/onnx/symbolic.py", line 17, in symbolic_fn
    g, interpolate_mode, args)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/onnx/onnx_utils/symbolic_helper.py", line 253, in _get_interpolate_attributes
    scales = _interpolate_get_scales_if_available(g, scales)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/onnx/onnx_utils/symbolic_helper.py", line 232, in _interpolate_get_scales_if_available
    'fs') != -1 and not _is_none(scales[0])
  File "/opt/conda/lib/python3.7/site-packages/mmcv/onnx/onnx_utils/symbolic_helper.py", line 66, in _maybe_get_const
    return _parse_arg(value, desc)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/onnx/onnx_utils/symbolic_helper.py", line 43, in _parse_arg
    return [float(v) for v in tval]
  File "/opt/conda/lib/python3.7/site-packages/torch/tensor.py", line 450, in __iter__
    raise TypeError('iteration over a 0-d tensor')
TypeError: iteration over a 0-d tensor 
(Occurred when translating upsample_nearest2d)._


I looked at the function code and it does the same thing as it was written before. Maybe I need to share some more information to help you?

**Comment by HoBeom** [comment]
I think you should upgrade the pytorch version. Put it up to version 1.7.0
Some operators may not be supported. (Latestly added layer of mmcv)

https://github.com/open-mmlab/mmcv/issues/690

**Comment by ccdsad** [comment]
Thank you, now it working on pytorch 1.7.0
