### ISSUE TITLE
About 3D dataset

### ISSUE THREAD

**Issue by NoLookDefense** [open-mmlab/mmpose#538]
Hello. Thanks for your excellent job.
I wonder whether mmpose will support training for 3D pose estimation models?

**Comment by jin-s13** [comment]
Yes, we are working on 3d pose estimation.

**Comment by NoLookDefense** [comment]
> Yes, we are working on 3d pose estimation.

Thank you! May I have the time schedule?

**Comment by innerlee** [comment]
We will update the iteration plan for April soon

**Comment by NoLookDefense** [comment]
> We will update the iteration plan for April soon

Thank you! BTW, I saw that 3D pose dataset like **human36m** and **MPI-INF-3DHP** are supported. But I didn't find a class similar to "3d human pose".
<img width="595" alt="Screenshot 2021-04-08 at 18 45 10" src="https://user-images.githubusercontent.com/81567453/114013841-91986000-989a-11eb-9d4f-c8263c2e7278.png">
I wonder how can I train a model with these two dataset?

**Comment by jin-s13** [comment]
For now, we support 3D human mesh recovery using these two datasets.
3D keypoint estimation is not supported yet. It is planned in April.

**Comment by jin-s13** [comment]
Hi, we have supported 3d human pose estimation, see https://github.com/open-mmlab/mmpose/tree/master/configs/body3d/simple_baseline

**Comment by NoLookDefense** [comment]
Thank you for your excellent work!

**Comment by NoLookDefense** [comment]
> For now, we support 3D human mesh recovery using these two datasets.
> 3D keypoint estimation is not supported yet. It is planned in April.

By the way, I still have some confusions about training with HMR. I found the config.py is different in HMR task is different, because it didn't need to assign the dataset type. It seems that the training will begin only when all the related datasets are well-prepared. 
But what should I do if I want to train HMR task with MPI-INF-3DHP dataset only?

**Comment by jin-s13** [comment]
> > For now, we support 3D human mesh recovery using these two datasets.
> > 3D keypoint estimation is not supported yet. It is planned in April.
> 
> By the way, I still have some confusions about training with HMR. I found the config.py is different in HMR task is different, because it didn't need to assign the dataset type. It seems that the training will begin only when all the related datasets are well-prepared.
> But what should I do if I want to train HMR task with MPI-INF-3DHP dataset only?

Please open another issue about training HMR.

**Comment by NoLookDefense** [comment]
OK
