### ISSUE TITLE
Conversion of HRNet model to ONNX gives circular import error

### ISSUE THREAD

**Issue by KulkarniKaustubh** [open-mmlab/mmpose#539]
On running the following command:
```
python tools/pytorch2onnx.py configs/top_down/hrnet/coco/hrnet_w32_coco_256x192.py  ../Working/models/pose/coco/hrnet_w48_coco_256x192-b9e0b3ab_20200708.pth --verify --show\
--output-file ../Working/models/pose/coco/hrnet_coco_256x192.onnx
```
Config file:
```
configs/top_down/hrnet/coco/hrnet_w32_coco_256x192.py
```

Here are outputs to some commands:
```pip freeze | grep mm```
Output:
```
mmcv-full==1.2.5
-e git+https://github.com/open-mmlab/mmdetection.git@2d2e5c6f42b6f4b8ab4f68985b1fd7823e3be505#egg=mmdet
-e git+git@github.com:open-mmlab/mmpose.git@eaafaa7630b1a37226e306b36c82dae610c4fd06#egg=mmpose
mmpycocotools==12.0.3
torchsummary==1.5.1
```

```pip freeze | grep torch```
Output:
```
torch==1.7.1+cu110
torchaudio==0.7.2
torchgeometry==0.1.2
torchsummary==1.5.1
torchvision==0.8.2+cu110
```

```pip freeze | grep onnx```
Output:
```
onnx==1.8.1
onnxruntime==1.7.0
```

This is the error I get after running the pytorch2onnx.py file:

```
Traceback (most recent call last):
  File "tools/pytorch2onnx.py", line 8, in <module>
    from mmpose.models import build_posenet
  File "/home/mmpose/mmpose/models/__init__.py", line 4, in <module>
    from .detectors import *  # noqa
  File "/home/mmpose/mmpose/models/detectors/__init__.py", line 1, in <module>
    from .bottom_up import BottomUp
  File "/home/mmpose/mmpose/models/detectors/bottom_up.py", line 11, in <module>
    from mmpose.core.evaluation import (aggregate_results, get_group_preds,
  File "/home/mmpose/mmpose/core/__init__.py", line 1, in <module>
    from .evaluation import *  # noqa: F401, F403
  File "/home/mmpose/mmpose/core/evaluation/__init__.py", line 1, in <module>
    from .bottom_up_eval import (aggregate_results, get_group_preds,
  File "/home/mmpose/mmpose/core/evaluation/bottom_up_eval.py", line 5, in <module>
    from mmpose.datasets.pipelines import get_warp_matrix, warp_affine_joints
  File "/home/mmpose/mmpose/datasets/__init__.py", line 2, in <module>
    from .datasets import (BottomUpCocoDataset, BottomUpCrowdPoseDataset,
  File "/home/mmpose/mmpose/datasets/datasets/__init__.py", line 3, in <module>
    from .body3d import Body3DH36MDataset
  File "/home/mmpose/mmpose/datasets/datasets/body3d/__init__.py", line 1, in <module>
    from .body3d_h36m_dataset import Body3DH36MDataset
  File "/home/mmpose/mmpose/datasets/datasets/body3d/body3d_h36m_dataset.py", line 7, in <module>
    from mmpose.core.evaluation import keypoint_mpjpe
ImportError: cannot import name 'keypoint_mpjpe' from partially initialized module 'mmpose.core.evaluation' (most likely due to a circular import) (/home/mmpose/mmpose/core/evaluation/__init__.py)
```

**Comment by jin-s13** [comment]
Thanks for reporting the bug. 
For now, you can safely comment the line7 in "/home/mmpose/mmpose/datasets/datasets/body3d/body3d_h36m_dataset.py".

We will fix this later. @ly015  Please check this `circular import` problem.

**Comment by ly015** [comment]
This problem should be fixed by #542

**Comment by KulkarniKaustubh** [comment]
The circular import error is solved but now I am getting an error like so:
```
NotImplementedError: please update mmcv to version>=1.0.4
```

But
```pip freeze | grep mmcv``` gives me:
```
mmcv==1.2.2
mmcv-full==1.2.5
```

**Comment by jin-s13** [comment]
You need to run pip uninstall mmcv first if you have mmcv installed. If mmcv and mmcv-full are both installed, there will be ModuleNotFoundError.

**Comment by jin-s13** [comment]
Yes, it is successfully converted.

**Comment by kingoo123** [comment]
I have the same situation in the branch 1.x . There is a conflict between the branch. When i install mmcv>=2.0.0rc0, “NotImplementedError: please update mmcv to version>=1.0.4” will occur. But I uninstall mmcv==2.0.0rc2, and then install mmcv==1.7.0, "MMCV==1.7.0 is used but incompatible. Please install mmcv>=2.0.0rc0, <=2.1.0." will occur. How to solve this please?

**Comment by ly015** [comment]
@kingoo123 Thanks for using MMPose 1.0. We recommend using a separate conda environment for MMPose 1.0 and its dependencies to avoid tangling with old versions. MMPose 1.0.0 requires MMCV>=2.0.0, please follow our [installation documents](https://mmpose.readthedocs.io/en/1.x/installation.html).

**Comment by kingoo123** [comment]
> @kingoo123 Thanks for using MMPose 1.0. We recommend using a separate conda environment for MMPose 1.0 and its dependencies to avoid tangling with old versions. MMPose 1.0.0 requires MMCV>=2.0.0, please follow our [installation documents](https://mmpose.readthedocs.io/en/1.x/installation.html).

Thanks for your prompt reply, that's what I'm doing now. But pytorch2onnx.py is not available on branch 1.x, some packages do not exist. Requires minor modifications to use, perhaps considering its code compatibility

**Comment by ly015** [comment]
@kingoo123 `pytorch2onnx.py` is deprecated in MMPose and removed from 1.x. The model export and deployment are supported by [MMDepoly](https://github.com/open-mmlab/mmdeploy). Please refer to MMDeploy's documents for details:

- MMDeploy 1.x for MMPose 1.x: https://mmdeploy.readthedocs.io/en/dev-1.x/04-supported-codebases/mmpose.html
- MMDeploy 0.x for MMPose 0.x: https://mmdeploy.readthedocs.io/en/latest/04-supported-codebases/mmpose.html

**Comment by kingoo123** [comment]
> @kingoo123 `pytorch2onnx.py` is deprecated in MMPose and removed from 1.x. The model export and deployment are supported by [MMDepoly](https://github.com/open-mmlab/mmdeploy). Please refer to MMDeploy's documents for details:
> 
> * MMDeploy 1.x for MMPose 1.x: https://mmdeploy.readthedocs.io/en/dev-1.x/04-supported-codebases/mmpose.html
> * MMDeploy 0.x for MMPose 0.x: https://mmdeploy.readthedocs.io/en/latest/04-supported-codebases/mmpose.html

Thanks a lot. this is a great project.

**Comment by kingoo123** [comment]
> @kingoo123 `pytorch2onnx.py` is deprecated in MMPose and removed from 1.x. The model export and deployment are supported by [MMDepoly](https://github.com/open-mmlab/mmdeploy). Please refer to MMDeploy's documents for details:
> 
> * MMDeploy 1.x for MMPose 1.x: https://mmdeploy.readthedocs.io/en/dev-1.x/04-supported-codebases/mmpose.html
> * MMDeploy 0.x for MMPose 0.x: https://mmdeploy.readthedocs.io/en/latest/04-supported-codebases/mmpose.html



> @kingoo123 `pytorch2onnx.py` is deprecated in MMPose and removed from 1.x. The model export and deployment are supported by [MMDepoly](https://github.com/open-mmlab/mmdeploy). Please refer to MMDeploy's documents for details:
> 
> * MMDeploy 1.x for MMPose 1.x: https://mmdeploy.readthedocs.io/en/dev-1.x/04-supported-codebases/mmpose.html
> * MMDeploy 0.x for MMPose 0.x: https://mmdeploy.readthedocs.io/en/latest/04-supported-codebases/mmpose.html

I tried MMDeploy 1.x, but some model in mmpose 1.x is not supported. for example [deeppose_mobilenetv2_rle_pretrained](file://configs/body_2d_keypoint/topdown_regression/coco/td-reg_mobilenetv2_rle-pretrained-8xb64-210e_coco-256x192.py)
