### ISSUE TITLE
Speed issue

### ISSUE THREAD

**Issue by MIMOS-Chien** [open-mmlab/mmpose#553]
I have tried mmpose botom_up case either using off-line video or on line camera capturing video, it is too slow (almost like no movement). How to improve the delay less than 2 second? TQ

BottomUpCocoDataset
__Python VERSION: 3.8.8 (default, Feb 24 2021, 15:54:32) [MSC v.1928 64 bit (AMD64)]
__pyTorch VERSION: 1.8.1+cu102
__CUDA VERSION
__CUDNN VERSION: 7605
__Number CUDA Devices: 2
__Devices
Active CUDA Device: GPU 0
Available devices  2
Current cuda device  0
Active CUDA Device: GPU 0
Available devices  2
Current cuda device  0

**Comment by HoBeom** [comment]
Some of the post-processing tasks are not yet optimized. Set the post-processing options to False.
https://github.com/open-mmlab/mmpose/blob/2a43cce78e8857c20e80f884e7be9f22f1520968/configs/bottom_up/higherhrnet/coco/higher_hrnet32_coco_512x512.py#L123

adjust=False,
refine=False,
flip_test=False.
I got 10 FPS with higherhrnetw32, 30 FPS with mobilenetv2 + AE in 3080

**Comment by MIMOS-Chien** [comment]
Wao Wao Wao! Just now I use 640x640 case, I have seen the speed improvement. TQVM HoBeom. BTW, how to see FPS on the command prompt when it runs?

**Comment by MIMOS-Chien** [comment]
FYI. tested w32 & w48 for 512x512 cases, they are much slower than w32 512x512. TQ

**Comment by MIMOS-Chien** [comment]
FYI. I have tried all 512x512 cases, they are fast now after modification. Cheers

**Comment by MIMOS-Chien** [comment]
Hi, FYI。 I've tested on-line video scene capturing for higherhrnet, hrnet, and etc in bottom-up case. Seems all these networks give same speed of motion of a man.  

BTW, I checked the mobilenetv2_coco_512x512.py, I found "with_ae=[True]", it is what you mean  "mobilenetv2 + AE"?. If so, it seems not much different from others for the delay I expereince from the on-line capturing. My GPU is RTX 2080 Ti. TQ

**Comment by HoBeom** [comment]
FPS can be calculated simply, try it!!
If you parallelize the camera input & draw & estimation, you'll get a more natural demo.

**Comment by innerlee** [comment]
Pls refer to https://github.com/open-mmlab/mmaction2/blob/master/demo/webcam_demo.py for a paralleled version

**Comment by MIMOS-Chien** [comment]
Many thanks for both you guys
