### ISSUE TITLE
example with using own detection boxes

### ISSUE THREAD

**Issue by nikky4D** [open-mmlab/mmpose#555]
Hi

I have a list of my own bounding boxes for each image. Is there an example that shows how I can pass my own detection boxes to the top-down mmpose models?

**Comment by jin-s13** [comment]
Please prepare the json_file, and run `top_down_img_demo.py`.

**Comment by nikky4D** [comment]
Thanks for getting back. I see you don't need a json but can also build with a list of dicts. I'll check it out.
