### ISSUE TITLE
(Bottom-up 2d) posetrack2018 dataset support

### ISSUE THREAD

**Issue by HoBeom** [open-mmlab/mmpose#573]
I'd like to experiment with bottom-up models on the Posetrack 2018 dataset.
https://github.com/open-mmlab/mmpose/blob/601aba3befbe8abd2b537225b868d14494319f6a/mmpose/datasets/datasets/top_down/topdown_posetrack18_dataset.py#L18

I think I need to work on this code as a base, but I don't know where to fix it to work correctly. I need your help.

**Comment by jin-s13** [comment]
Please compare `bottom_up/bottom_up_coco.py` and `top_down/topdown_coco_dataset.py` to see how to convert a top-down dataset to a bottom-up dataset.

**Comment by HoBeom** [comment]
I'm gonna start working on it. Thank you. :smile:
