### ISSUE TITLE
Question about validate during training, about valid_pipeline and bbox_file

### ISSUE THREAD

**Issue by palinorz** [open-mmlab/mmpose#58]
hi,
thx for your great work,

Im using configs/top_down/resnet/coco/res50_coco_256x192.py to train my own keypoint dataset(git mmpose at 2020.08.06), theres some questions i met:

[line72--73] have been changed to my own file:

bbox_file='data/person_detection_results/'
                'bbox_1000pic.json',

[line126--137] changed to:

        train=dict(
        type='TopDownCocoDataset',
        ann_file=f'{data_root}/annotations/person_keypoints_train_1000pic.json',
        img_prefix=f'{data_root}/train_1000pic/',
        data_cfg=data_cfg,
        pipeline=train_pipeline),

        val=dict(
        type='TopDownCocoDataset',
        ann_file=f'{data_root}/annotations/person_keypoints_train_1000pic.json',
        img_prefix=f'{data_root}/train_1000pic/',
        data_cfg=data_cfg,
        pipeline=valid_pipeline),

In this setting, everything is alright, train on 1000pic successfully, valid on 1000pic successfully, output result.json in work_dir successfully;

----

but when i change valid, for example, when valid part changed from:

        ann_file=f'{data_root}/annotations/person_keypoints_train_1000pic.json',
        img_prefix=f'{data_root}/train_1000pic/',

to

        ann_file=f'{data_root}/annotations/person_keypoints_valid_20pic.json'
        img_prefix=f'{data_root}/valid_20pic/',

it seems mmpose read bbox_1000pic.json from line72--73, and consider there should be 1000images to valid, then read valid dir from line135 to find it;

In other word, on my understanding, mmpose use image_id from bbox_1000pic.json which read at line72--73(for example image_id:21, btw, person_keypoints_valid_20pic.json only has 20images, doesnot has image_id:21), then, try to find it in valid dir
(try to find 000 000 000 021.jpg in {data_root}/valid_21pic/). Error showed as: FileNotFoundError: img file does not exist: data/valid_20pic/000000000021.jpg

So~  config file can be only put 1 train_1000_bbox.json in it, but there are 2 ,train_1000.json and valid_20.json, in train_pipeline,valid_pipeline,
Are there any way to change config file to provide valid_20_bbox.json for valid_pipeline, or teach it to read bbox info from valid_20.json.

----
Thankyou very much.

**Comment by jin-s13** [comment]
Thank you for reporting this issue. I would like to clarify this.

The bbox_file is **only** used for validation (not for training). During training, we use ground-truth bounding boxes.

Please change the following
```
bbox_file='data/person_detection_results/'
'bbox_1000pic.json',
```
to 
```
bbox_file='data/person_detection_results/'
'valid_20_bbox.json',
```

**Comment by palinorz** [comment]
Wow~
Really thank you for your quick reply~
Thanks very much!
