### ISSUE TITLE
lite-hrnet

### ISSUE THREAD

**Issue by pablovela5620** [open-mmlab/mmpose#583]
Any plans to bring in [Lite-HRNet](https://github.com/HRNet/Lite-HRNet) into the main repo? Its missing a lot of the useful tools you guys have built (demo/pytorch2onnx/analysis/different datasets). Would be great to see it be folded in since its already basically built on the mmpose framework

**Comment by jin-s13** [comment]
Good suggestions! We will consider adding Lite-HRNet. 
Please also request the feature here #9 to help us prioritize.

**Comment by pablovela5620** [comment]
WIll do

**Comment by 2050airobert** [comment]
Have you done the litehrnet demo building into mmpose？
