### ISSUE TITLE
Question about inference speed of bottom-up models

### ISSUE THREAD

**Issue by wuyuuu** [open-mmlab/mmpose#590]
Hello, 

Firstly thanks for your great work.

Recently I'm using your bottom_up_video_demo.py and I notice that the run time of HRNet and MobileNet is almost the same(about 5s per image on Titan V).  But obviously, their GFlops and number of parameters are quite different.

Both input image sizes are 512x512.

So I really wonder is it because the most run time is cost by post-processing (like grouping)?

**Comment by innerlee** [comment]
Yes post-processing takes time, especially when there are many people.
We have speed up plans in this iteration https://github.com/open-mmlab/mmpose/issues/556.
To speed up by tuning configs, see https://github.com/open-mmlab/mmpose/issues/553.
