### ISSUE TITLE
How to install mmpose on Google Colaboratory?

### ISSUE THREAD

**Issue by CHRIBUR0309** [open-mmlab/mmpose#591]
I'd like to use darkpose (wholebody) pose estimation on Google Colaboratory, but I couldn't undrstand how to install.... Could you tell me the code to install mmpose and run darkpose? Thanks.

**Comment by innerlee** [comment]
Checkout this notebook from mmaction2 https://github.com/open-mmlab/mmaction2/blob/master/demo/mmaction2_tutorial.ipynb, and also refer to the installation guide here https://github.com/open-mmlab/mmpose/blob/master/docs/install.md

**Comment by innerlee** [comment]
@ly015 we may provide a colab notebook later :)

**Comment by CHRIBUR0309** [comment]
Thanks. Now I'll try again.
