### ISSUE TITLE
demo with mpii pre-trained model report "The model and loaded state dict do not match exactly"

### ISSUE THREAD

**Issue by zxiaoyusq** [open-mmlab/mmpose#595]
Hello! I run demo:
python demo/top_down_video_demo_with_mmdet.py \
    demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py \
http://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \
    configs/top_down/hrnet/mpii/hrnet_w48_mpii_256x256.py \
    https://download.openmmlab.com/mmpose/pretrain_models/hrnet_w48-8ef0771d.pth \
    --video-path /home/lmd/zxy/mmpose/data/testdata/video6.mp4 \
    --out-video-root vis_results

but report:
![image](https://user-images.githubusercontent.com/29696398/115681491-2913ad80-a387-11eb-8f17-c5ffa860b904.png)

**Comment by innerlee** [comment]
dup https://github.com/open-mmlab/mmpose/issues/356
