### ISSUE TITLE
mmpose model

### ISSUE THREAD

**Issue by sunmengnan** [open-mmlab/mmpose#596]
Hi, where is the mmpose model you mentioned in the benchmark? Thx.

**Comment by jin-s13** [comment]
Please check in the [modelzoo](https://mmpose.readthedocs.io/en/latest/modelzoo.html#top-down-models)

**Comment by sunmengnan** [comment]
sry, I mean the mmpose(Associative embedding) model, it's not in the list

**Comment by innerlee** [comment]
![image](https://user-images.githubusercontent.com/9464825/115703665-fa083680-a39c-11eb-86ad-e44fcac13cab.png)

**Comment by sunmengnan** [comment]
Thx! Could you explain why the mAP of mmpose is higher than hrnet?

**Comment by innerlee** [comment]
You could train one if interest in. The lr etc. are not exactly the same.
