### ISSUE TITLE
saving checkpoint is slow

### ISSUE THREAD

**Issue by zxiaoyusq** [open-mmlab/mmpose#604]
After training,it will take two hours to save pth.   The pth file is about 760m in size, is this normal?

![image](https://user-images.githubusercontent.com/29696398/116206633-9782b200-a771-11eb-8c24-18b72f947f87.png)

**Comment by jin-s13** [comment]
The time cost is not for saving checkpoints.  It is for testing.
Too many bounding boxes here, so it may cost lots of time. 
You may check if you have used multi-batch testing, see https://github.com/open-mmlab/mmpose/blob/master/configs/top_down/resnet/coco/res50_coco_256x192.py#L121-L122

**Comment by zxiaoyusq** [comment]
thanks for your quick reply!
