### ISSUE TITLE
Demo for batch inference

### ISSUE THREAD

**Issue by zzh-tech** [open-mmlab/mmpose#608]
Hi, thank you for your great work!
I would like to integrate 2D pose estimation as part of my model to handle batches of images.
Is there any demo for batch inference (the batch inference version of top_down_img_demo_with_mmdet.py)?

**Comment by ly015** [comment]
Currently, the inference API uses a single image and its bboxes as the input.
You could consider extending this API to batched images by aggregating bboxes from multiple images before collating the batch. Please refer to [this function](https://github.com/open-mmlab/mmpose/blob/e7f929f21465a75b54a8e30b781b1bff5a146ecd/mmpose/apis/inference.py#L144).

**Comment by jin-s13** [comment]
Also see https://github.com/open-mmlab/mmpose/blob/e7f929f21465a75b54a8e30b781b1bff5a146ecd/mmpose/apis/inference.py#L299

**Comment by zzh-tech** [comment]
Got it.
Thanks.
