### ISSUE TITLE
training box

### ISSUE THREAD

**Issue by alicera** [open-mmlab/mmpose#617]
The image have two boxes, one is green, the other is blue.
The green box is compose of keypoints
The blue box is compose of entire person.

When training, which boxes are better for pose network?
Or both of them doesnt affect training trick.

![image](https://user-images.githubusercontent.com/59388989/116843676-4102f100-ac13-11eb-9496-d9ccb697bd0a.png)

**Comment by HoBeom** [comment]
Usually, 1.3x padded blue boxes are used.
