### ISSUE TITLE
Inconsistent results in the provided training logs and the Tables .

### ISSUE THREAD

**Issue by PkuRainBow** [open-mmlab/mmpose#618]
@jin-s13  Really great work!

According to Table (https://github.com/open-mmlab/mmpose/blob/master/configs/top_down/hrnet/README.md#results-on-coco-val2017-with-detector-having-human-ap-of-564-on-coco-val2017-dataset), we see that **pose_hrnet_w48** achieves AP=0.756 with input resolution as 256x192 while the results reported in the provided logs 
 (https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_coco_256x192_20200708.log.json) are (AP=0.77595):
`
"AP": 0.77597, "Ap .5": 0.93616, "AP .75": 0.84802, "AP (M)": 0.74732, "AP (L)": 0.81922, "AR": 0.80246, "AR .5": 0.94584, "AR .75": 0.86414, "AR (M)": 0.77053, "AR (L)": 0.85151} `

It would be great if you could help to clarify the reasons for the inconsistency 😅 😂 🤣

**Comment by jin-s13** [comment]
Because the log is reported using the ground-truth bounding boxes.

**Comment by PkuRainBow** [comment]
@jin-s13 Thanks. It would be great to share  **AP^M** and **AP^L** based on HRNet-W32 and HRNet-W48 with both 256x192 and 384x288 input sizes.
--


!

**Comment by jin-s13** [comment]
You may evaluate the model by yourself using the pre-trained models.

**Comment by PkuRainBow** [comment]
Thanks.
