### ISSUE TITLE
Running the pretrained horse model ?

### ISSUE THREAD

**Issue by basicvisual** [open-mmlab/mmpose#619]
Hi I am currently going through your documentation to run the horse model on my videos . I am following the guide here: [demo](https://github.com/open-mmlab/mmpose/blob/master/demo/docs/2d_animal_demo.md ) and I cannot find the pretrained model for horse ? what is the link to the model path exactly ? Can it be used to run for horse jumps etc ?

**Comment by jin-s13** [comment]
Please check [this](https://github.com/open-mmlab/mmpose/blob/master/demo/docs/2d_animal_demo.md#using-mmdetection-to-detect-animals) for running model.
Also the [ModelZOO](https://mmpose.readthedocs.io/en/latest/animal_models.html#results-on-horse-10-test-set).

This is one of the pre-trained horse models.
https://download.openmmlab.com/mmpose/animal/resnet/res50_horse10_256x256_split1-3a3dc37e_20210405.pth

**Comment by jin-s13** [comment]
Since the horse dataset for training does not include images for jumping horses, the pre-trained model may not work very well in this case.
