### ISSUE TITLE
About the annotation of 3d human pose estimation

### ISSUE THREAD

**Issue by FireMonkey796** [open-mmlab/mmpose#621]
Hello. I want to consult something about 3d pose estimation annotations. 
I know that the annotation of 2d pose estimation is the coordinate comparing with the whole image size. For example, when the image size is [1920, 1080], the coordinate of a keypoint may be something like [732, 244], which is the pixel value of the image. The zero point of the x and y axis is the top-left corner of the image
However, as for the 3d pose annotations, the keypoint will be the value between -1 and 1, which is completely different. I wonder that where is the zero point of the axis, and what's the actual meaning of the values?

**Comment by FireMonkey796** [comment]
Here's the screenshot. I wonder how to understand the meaning of these 3d values. Thank you.
![Uploading InkedScreenshot from 2021-05-05 17-59-11_LI.jpg…]()

**Comment by ly015** [comment]
Take [human3.6m](https://github.com/open-mmlab/mmpose/blob/master/docs/tasks/3d_body_keypoint.md#human36m) as an example. The 3D pose is annotated in the world space and the camera space in millimeters. In previous works, a common practice to preprocess the 3D pose is to zero-center the joint coordinates (around a root joint) and then do normalization. That's how you get the keypoint value in [-1,1].

**Comment by FireMonkey796** [comment]
> Take [human3.6m](https://github.com/open-mmlab/mmpose/blob/master/docs/tasks/3d_body_keypoint.md#human36m) as an example. The 3D pose is annotated in the world space and the camera space in millimeters. In previous works, a common practice to preprocess the 3D pose is to zero-center the joint coordinates (around a root joint) and then do normalization. That's how you get the keypoint value in [-1,1].

Thank you. I am still confused about some relevant concepts.
1. Where's the root joint? It is pelvis?
2. To normalize x/y coordinate, we only need to normalize (0, height) and (0, width) to [-1, 1]. Different from x and y, the z coordinate is infinity.
In the range [-1, 1], 0 means the location of the root joint, but what's the physical meaning of -1 or 1? It's the location of the furthest joints, or the deepest location of the room, or means the infinity location?

**Comment by ly015** [comment]
1. Yes, the pelvis is usually selected as the root joint when using human3.6m dataset.
2. This depends on your preprocessing method. For example in [simple 3D baseline](https://github.com/open-mmlab/mmpose/tree/master/configs/body3d/simple_baseline), the 3D pose is normalized by dividing the standard deviation along each axis (so the normalized value has an std of 1, instead of being in the range of [-1, 1]). [VideoPose3D](https://arxiv.org/abs/1811.11742) uses the zero-centered 3D pose in the camera space without normalization. To limit the coordinate value in [-1, 1], I guess the normalization should use the furthest joints or the space limitations of the data collection environment.  But these are really technical details and there may not be standard practice.

**Comment by FireMonkey796** [comment]
> 1. Yes, the pelvis is usually selected as the root joint when using human3.6m dataset.
> 2. This depends on your preprocessing method. For example in [simple 3D baseline](https://github.com/open-mmlab/mmpose/tree/master/configs/body3d/simple_baseline), the 3D pose is normalized by dividing the standard deviation along each axis (so the normalized value has an std of 1, instead of being in the range of [-1, 1]). [VideoPose3D](https://arxiv.org/abs/1811.11742) uses the zero-centered 3D pose in the camera space without normalization. To limit the coordinate value in [-1, 1], I guess the normalization should use the furthest joints or the space limitations of the data collection environment.  But these are really technical details and there may not be standard practice.

Thank you. From my personal understanding, the original annotation of z axis of all the dataset is the absolute distance value like meter of millimeter. They might be the distance with camera or root joint.  But how to normalize them will depend on how the author process, right?

**Comment by ly015** [comment]
You may need to refer to the documents of a dataset for its annotation details. Here we just take human3.6m as an example to show its annotation format and how the data is normalized in some previous works.
