### ISSUE TITLE
top_down_video

### ISSUE THREAD

**Issue by alicera** [open-mmlab/mmpose#623]
top_down_video_demo_full_frame_without_det.py  and
top_down_video_demo_with_mmdet.py

What are the different?

Thanks

**Comment by jin-s13** [comment]
`top_down_video_demo_full_frame_without_det.py` assumes that the object locates at the center of the frame, and the video frame is well-cropped. There is no need to run object detection, we simply use the whole video frame as the model input.

`top_down_video_demo_with_mmdet.py` will run object detection first, and crop the boxes.

**Comment by alicera** [comment]
where can I download the mmdet model ?

**Comment by jin-s13** [comment]
Please check mmdet [modelzoo](https://mmdetection.readthedocs.io/en/latest/model_zoo.html).

**Comment by alicera** [comment]
Could you provide the sample model link for demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py model.
Because the model link is so many. And I download some models for faster_rcnn_r50_fpn, but I fail.

Thanks .

**Comment by jin-s13** [comment]
Please see [mmpose demo](https://mmpose.readthedocs.io/en/latest/demo.html#using-mmdet-for-human-bounding-box-detection) for an example.

**Comment by alicera** [comment]
Thanks for your help.

Can the button-up network (res50_coco_512x512) design image size?
like (256x456), not (512x512)

**Comment by jin-s13** [comment]
Yes, you can try it.

**Comment by alicera** [comment]
Why the bottom_up_img_demo.py need to "--json-file" ?
But the bottom_up_video_demo.py dosent need.

**Comment by jin-s13** [comment]
Only filename in the json-file is required.

**Comment by innerlee** [comment]
@jin-s13 We may explain the difference between demo scripts in the demo's doc.

@alicera Could you please open a new issue for the visualization bug? We are trying to keep the topic in each issue focused.
In the new issue, you may provide a screenshot of the wrong result. Thanks!

**Comment by alicera** [comment]
Thanks for your help.
