### ISSUE TITLE
How do you produce the experimental results?

### ISSUE THREAD

**Issue by wuyuuu** [open-mmlab/mmpose#627]
Hello,

Firstly thanks for the excellent work. 

Recently I'm training networks with provided config (bottom-up MobileNet). However, my mAP value is slightly lower than the reported one. I don't know if it is just unlucky or actually common.

So I have a question about how do you get the mAP value in the BenchMark. Did you run the training code several times and pick the best or calculate the average? Or just train each network once and use the result?

Kind regards.

**Comment by jin-s13** [comment]
Aha, we just trained once : )
By the way, we find that the batchsize, number of gpu, will also slightly affect the performance.

**Comment by wuyuuu** [comment]
> Aha, we just trained once : )
> By the way, we find that the batchsize, number of gpu, will also slightly affect the performance.

Thanks for the quick reply!
