### ISSUE TITLE
How to interpret the result of a neural network execution?

### ISSUE THREAD

**Issue by Noortvel** [open-mmlab/mmpose#632]
I am trying to get the position of body parts. Took this model (hrnet_w32_coco_wholebody_256x192). Pass single image to the input and get the output (1, 133, 64, 48). How can i decipher the output and figure out which is which(nose, head, elbow, etc) and get position of it? I realized that (64,48) is a heatmap, but why there are 133 of them?

**Comment by Noortvel** [comment]
Ok i get it. Its 133 keypoints https://github.com/jin-s13/COCO-WholeBody/, (i expected 17). But i'm still confused, heatmaps look like this
<details>
  <summary>images</summary>

![layer_0](https://user-images.githubusercontent.com/15169003/117570494-fb429e80-b0d2-11eb-9a73-9c1bd20c96f8.png)
![layer_1](https://user-images.githubusercontent.com/15169003/117570496-fc73cb80-b0d2-11eb-87c2-c839cc62a507.png)
![layer_2](https://user-images.githubusercontent.com/15169003/117570497-fd0c6200-b0d2-11eb-9714-69523e942ce2.png)

</details>

**Comment by jin-s13** [comment]
You can refer to https://github.com/open-mmlab/mmpose/blob/master/demo/top_down_img_demo_with_mmdet.py. This will produce the final x-y coordinates.

**Comment by Noortvel** [comment]
I figured it out.
I converted the pth to onnix without specifying the path to the pth. Relied on default downloaded from  https://download.openmmlab.com/mmpose/pretrain_models/hrnet_w32-36af842e.pth  by `pytorch2onnx.py`

But this default downloaded model did not work correctly as you can see above.
Had to be downloaded by hand from https://mmpose.readthedocs.io/en/latest/top_down_models.html and using it.

![изображение](https://user-images.githubusercontent.com/15169003/117583637-ee44a000-b110-11eb-8c0d-097b9837a1d9.png)
Thanks.

**Comment by jin-s13** [comment]
https://download.openmmlab.com/mmpose/pretrain_models/hrnet_w32-36af842e.pth this is the pre-trained model (trained on imagenet for imagenet classification). So this does not work.

**Comment by jin-s13** [comment]
Note that it is the config for training. This means the model will load the imagenet-trained model to initialize, and then train on coco.
