### ISSUE TITLE
extrinsic parameter of 3d pose dataset

### ISSUE THREAD

**Issue by NoLookDefense** [open-mmlab/mmpose#633]
Hi. I found that the 3d dataset contains the extrinsic parameters of each camera. But where is the root of the world coordinate as for the human36m, 3dpw and hp3d dataset respectively?

**Comment by ly015** [comment]
Please refer to the papers or documents of these datasets for the definition of the world coordinates, including the origin position. Usually, the camera extrinsic parameters would give the necessary information about the world/camera coordinate system.

**Comment by innerlee** [comment]
@ly015 we may add this info to a place in documentation. FAQ maybe?

**Comment by NoLookDefense** [comment]
> Please refer to the papers or documents of these datasets for the definition of the world coordinates, including the origin position. Usually, the camera extrinsic parameters would give the necessary information about the world/camera coordinate system.

Thank you. BTW, are there any references to the papers?
