### ISSUE TITLE
What is required GPU memory to train HRNet_w48/coco-wholebody?

### ISSUE THREAD

**Issue by ioctl-user** [open-mmlab/mmpose#636]
I am interesting in minimum and recommended memory for single GPU.

**Comment by jin-s13** [comment]
About 12GB GPU memory required to train HRNet_w48_256x192

**Comment by jin-s13** [comment]
Of course you can use smaller batchsize. But I have not tried. Not sure if the performance will be affected.

**Comment by ioctl-user** [comment]
Can I estimate GPU memory consumption using the same training scripts on CPU?

I would like to buy new card for specific tasks.

For now video cards very expensive, especially with a lot of memory. So, I want understand exact memory requirements for needed tasks.

**Comment by jin-s13** [comment]
You may reduce the batchsize, and linearly scaling to estimate the GPU memory consumption. 
The training of coco-wholebody may consume lots of CPU memory and GPU memory.

**Comment by ioctl-user** [comment]
Ok. There is no problem in CPU memory.

Is it enough of 4G, 6G, 8G of GPU memory with lowest batchsize?

**Comment by jin-s13** [comment]
Yes. For example, you may set `samples_per_gpu=8` to reduce the gpu memory.

**Comment by ioctl-user** [comment]
Thanks!
