### ISSUE TITLE
MPII test set evaluation

### ISSUE THREAD

**Issue by carolchenyx** [open-mmlab/mmpose#640]
Dear all, MPII released the test set annotation https://nextcloud.mpi-klsb.mpg.de/index.php/s/Rmmn8PxJs7EB5Sg . Could we evaluate it through here? Thanks.

**Comment by jin-s13** [comment]
Thank you for the reminding. We will check it.

**Comment by carolchenyx** [comment]
Dear Jin, do you have any update of it? Thank you.

**Comment by jin-s13** [comment]
Sorry, we haven't had time to support MPII test set yet. Recently, we are refactoring the codes of the datasets. 
We will possibly start on this next month, after the code refactoring is finished.
