### ISSUE TITLE
Why does the predicted elbow link to two wrists (for bottom-up methods). 

### ISSUE THREAD

**Issue by alicera** [open-mmlab/mmpose#644]
I train my dataset.
Here is my image result :
I test my train data. A image has two person, and the ones right_wrist is connect to another right_wrist. But my data label is correct for json.
Do you know the reason?
Thanks

**Comment by jin-s13** [comment]
I can not see the image result..

**Comment by alicera** [comment]
Hi here is the image
![image](https://user-images.githubusercontent.com/59388989/118211505-cce00d00-b49e-11eb-85e7-8e54635cf4c3.png)

**Comment by innerlee** [comment]
Maybe the prediction is wrong

**Comment by alicera** [comment]
Hi , 
How can I prevent the status？
The man's left wrist should be one, but it detect two wrist.

**Comment by jin-s13** [comment]
In this case, there are two (almost the same, except for the left wrist) poses for the man in the prediction results. 
This problem can be solved by pose NMS.
In the latest mmpose (0.15.0), we use pose_nms as default. https://github.com/open-mmlab/mmpose/blob/1c1bcafc7a17c27383ee4d16a13202a44bcf6a52/demo/bottom_up_img_demo.py#L36

Please try the latest mmpose.

**Comment by alicera** [comment]
谢谢
但我又遇到另一个问题
如果照片中只有1人但他预测出多个脚踝 该如何避免
一个人应该只有一个脚踝

**Comment by jin-s13** [comment]
同样是nms的问题。可尝试调整 --pose-nms-thr

**Comment by alicera** [comment]
But the --pose-nms-thr default is 0.9.

**Comment by jin-s13** [comment]
try smaller `pose-nms-thr`, e.g. `pose-nms-thr=0.5`
