### ISSUE TITLE
Model Training with Customized Dataset

### ISSUE THREAD

**Issue by EricChan-OC** [open-mmlab/mmpose#658]
Hi, I want to use my cattle images dataset to detect customized keypoints on cattles. I looked over the documentation and couldn't find any tutorial or resource about this. Is model training using customized dataset avaliable in the current release?

**Comment by ly015** [comment]
I guess this tutorial would helpful: https://github.com/open-mmlab/mmpose/blob/master/docs/tutorials/1_finetune.md

**Comment by EricChan-OC** [comment]
Awesome, I can train with my own dataset now. The result is encouraging. Thanks a lot!
