### ISSUE TITLE
How the coordinates of pose results map back to original image?

### ISSUE THREAD

**Issue by deep-practice** [open-mmlab/mmpose#660]
TopDown model extracts features from cropped images，but how the coordinates of pose results map back to original image.
In test pipeline,I see TopDownAffine transform,but it dosen't act on pose results but input data.So I'm confused.

**Comment by jin-s13** [comment]
https://github.com/open-mmlab/mmpose/blob/ebaede6cdc10c1226f319c41b05fb82eff2ff568/mmpose/core/post_processing/post_transforms.py#L149

**Comment by deep-practice** [comment]
Thx,I miss this part.
