### ISSUE TITLE
PoseLifter

### ISSUE THREAD

**Issue by manansaxena** [open-mmlab/mmpose#661]
Which model is being implemented here ? 
https://mmpose.readthedocs.io/en/latest/api.html?highlight=poselifter#mmpose.models.detectors.PoseLifter

Is this from this paper ?
Chang, Ju Yong, Gyeongsik Moon, and Kyoung Mu Lee. "PoseLifter: Absolute 3D human pose lifting network from a single noisy 2D human pose." arXiv preprint arXiv:1910.12029 (2019).

Thanks a lot, great work

**Comment by jin-s13** [comment]
https://github.com/open-mmlab/mmpose/tree/master/configs/body3d/simple_baseline#a-simple-yet-effective-baseline-for-3d-human-pose-estimation

**Comment by jin-s13** [comment]
```
@inproceedings{martinez_2017_3dbaseline,
  title={A simple yet effective baseline for 3d human pose estimation},
  author={Martinez, Julieta and Hossain, Rayat and Romero, Javier and Little, James J.},
  booktitle={ICCV},
  year={2017}
}

```

**Comment by manansaxena** [comment]
Ok, thanks a lot.
