### ISSUE TITLE
Modulate Kernel number setting of HRNet and HRNet+DARK on COCO dataset.

### ISSUE THREAD

**Issue by FreddieRao** [open-mmlab/mmpose#664]
Dear MMPOSE team,

My confusion relates to your 'modulate_kernel' settings for HRNet and HRNet+DARK on the COCO dataset with the image resolution of 384x288. 

Here, for HRNetW48 with the image resolution of 384x288, you set the modulate_kernel number to 11. However, for HRNetW48+DARK with the same image resolution(384x288), you set the modulate_kernel number to 17. Would you provide a reason for the different modulate_kernel settings?

I hereby provide the link to your codebase on [HRNetW48](https://github.com/open-mmlab/mmpose/blob/ebaede6cdc10c1226f319c41b05fb82eff2ff568/configs/top_down/hrnet/coco/hrnet_w48_coco_384x288.py#L85) and [HRNetW48+DARK](https://github.com/open-mmlab/mmpose/blob/ebaede6cdc10c1226f319c41b05fb82eff2ff568/configs/top_down/darkpose/coco/hrnet_w48_coco_384x288_dark.py#L119) for your reference.

It will be greatly appreciated if answering my question.

Many thank!

**Comment by jin-s13** [comment]
Sorry for the confusion. 

1. In fact, `modulate_kernel` in HRNetW48 is not used. You can safely delete it.
`modulate_kernel` is only used when ` post_process='unbiased'`.
2. Theoretically, we should use `modulate_kernel=17` for `sigma=3`, and `modulate_kernel=11` for `sigma=2`. But in experiments, we find that it does not make much difference in AP.

**Comment by jin-s13** [comment]
@ly015 Maybe we should clean the configs, and remove those unnecessary settings.

**Comment by FreddieRao** [comment]
Thanks for answering my questions. I will close this issue. Wish you all the best!
