### ISSUE TITLE
why predicted joint coordinates are out of cropped bounding box?

### ISSUE THREAD

**Issue by deep-practice** [open-mmlab/mmpose#665]

**Comment by innerlee** [comment]
Please blur the faces in the image

**Comment by jin-s13** [comment]
1. We did not directly use bbox to crop the image. bbox will be transformed to center&scale, and then crop the image.
3. scale will be multiplied by a factor (1.25) to include some context.
4. If the ratio of width/height is different from that of model input (possibly 192/256), we will adjust the bbox.

**Comment by deep-practice** [comment]
Ok,I see.
Another question,does pixel_std can be any value as long as the encode and decode process use the same value?
scale = np.array([w / 200.0, h / 200.0], dtype=np.float32)

**Comment by jin-s13** [comment]
yes

**Comment by deep-practice** [comment]
But how to avoid predicting skeleton joints out of bbox?It's very weird when two bboxes are close. @jin-s13

**Comment by jin-s13** [comment]
The simplest way is to crop the image before running `inference_top_down_pose_model`, or you have to modify the data pre-processing pipeline.

**Comment by deep-practice** [comment]
Can you give more detail about how to modify the data preprocessing pipeline?

**Comment by deep-practice** [comment]
I crop the image before running inference_top_down_pose_model,but the result is still not good.Maybe I need collect data and retrain.

**Comment by jin-s13** [comment]
> I crop the image before running inference_top_down_pose_model,but the result is still not good. Maybe I need collect data and retrain.

Yes. If the data distribution is quite different, the data should be collected.
