### ISSUE TITLE
Temporal video analysis

### ISSUE THREAD

**Issue by MalteEbner** [open-mmlab/mmpose#67]
Does MMPose support a temporal analysis of videos yet, where the pose estimation is not done on a frame-by-frame basis, but rather using temporal information, like in this [paper on VideoPose3D ](https://github.com/facebookresearch/VideoPose3D)?
Supporting temporal frameworks would need the datasets to consist of an unordered set of videos, where each video is a sequential ordered list of frames. Furthermore, the splitting of training and validation set, the definition of batches and the input to the model would also need to work accordingly.

**Comment by jin-s13** [comment]
Currently, MMPose does not support video pose estimation yet.
Thank you for the suggestion. I will leave a comment in #9 and we may consider adding this feature in the following versions.

**Comment by FarzanehAskari** [comment]
Hello, 

I am wondering if the mmpose repo currently supports video pose estimation (by taking into account temporal information)?

Thanks

**Comment by innerlee** [comment]
Hi @FarzanehAskari , for now supported video methods, checkout https://mmpose.readthedocs.io/en/latest/topics/body(3d,kpt,vid).html 

We will add more in future, follow our monthly iteration plan for news!

**Comment by FarzanehAskari** [comment]
Hello, I am wondering where to find the update for which video methods are included as of now? Thank you for the great repo.

**Comment by ly015** [comment]
We currently support 3D video method (checkout [here](https://mmpose.readthedocs.io/en/latest/topics/body%283d%2Ckpt%2Csview%2Cvid%29.html)) VideoPose3D (CVPR'19) and 2D video method (checkout [here](https://mmpose.readthedocs.io/en/latest/topics/body%282d%2Ckpt%2Csview%2Cvid%29.html)) PoseWarper (NeurIPS'19). And we are also working on post-processing methods to improve temporal smoothness and robustness (checkout #1127).

Please follow our monthly iteration plan and release notes for updates.
