### ISSUE TITLE
Inference on Videos

### ISSUE THREAD

**Issue by EricChan-OC** [open-mmlab/mmpose#673]
I have trained models to detect keypoints on animals. I want to use the trained model to inference on videos. Does MMPose support this function? If so, would anyone mind to provide some basic examples or tutorials? I appreciate it.

**Comment by jin-s13** [comment]
Please check https://github.com/open-mmlab/mmpose/blob/master/demo/docs/2d_animal_demo.md#2d-animal-pose-video-demo.
