### ISSUE TITLE
Inquiring for image size of Macaque dataset

### ISSUE THREAD

**Issue by rubeea** [open-mmlab/mmpose#678]
Hi,

The config page here https://github.com/open-mmlab/mmpose/tree/master/configs/animal/hrnet mentions that the image size for training hrnet on macaque dataset should be 256x192. So do we have to resize the images in the macaque dataset for training and testing the HRNet? Also this size implies that width x height are 256x192 right?
Looking forward to hearing from you.

Thanks and Regards,
Rabeea

**Comment by jin-s13** [comment]
1. The input size (256x192) means the size of the neural network input (after all these pre-processing), instead of the original image. The original image can be of any size. 
2. MMPose pipeline will do all these pre-processing, i.e. cropping + resizing. You do not have to resize the image by yourself.
2. No. It means: width-192 & height-256

**Comment by rubeea** [comment]
> 1. The input size (256x192) means the size of the neural network input (after all these pre-processing), instead of the original image. The original image can be of any size.
> 2. MMPose pipeline will do all these pre-processing, i.e. cropping + resizing. You do not have to resize the image by yourself.
> 3. No. It means: width-192 & height-256

@jin-s13 Ok thanks a lot for your response :) . Just one more question though. Which image size did you use? As using the original image sizes makes the training quite slow because they are very large.

**Comment by jin-s13** [comment]
Do you mean the image sizes? I did not change the original image sizes :)

**Comment by rubeea** [comment]
> Do you mean the image sizes? I did not change the original image sizes :)

@jin-s13 yeah because the annotations are done for the original image sizes so we cannot change it I suppose. Thank you.
