### ISSUE TITLE
Training for 3d human pose estimation

### ISSUE THREAD

**Issue by FireMonkey796** [open-mmlab/mmpose#682]
Hello. Will 3dpw and hp3d dataset be supported for 3d human pose training? I only saw the human36m dataset

**Comment by jin-s13** [comment]
Thank you for the suggestion. I will leave a comment in #9 and we may consider adding this feature in the following versions.

**Comment by jin-s13** [comment]
Not sure what is hp3d.. Do you mean [MuCo-3DHP](http://gvv.mpi-inf.mpg.de/projects/SingleShotMultiPerson/) or [MPI-INF-3DHP](http://gvv.mpi-inf.mpg.de/3dhp-dataset/)?

By the way, MPI-INF-3DHP has been supported and will be merged into master soon #683 .

**Comment by FireMonkey796** [comment]
Oh, hp3d means  MPI-INF-3DHP. Thank you
