### ISSUE TITLE
buttom-up implementation

### ISSUE THREAD

**Issue by alicera** [open-mmlab/mmpose#699]
I find the project https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.1/configs/keypoint

Is the buttom-up easy to design a network?
Do you have the buttom-up implementation architecture and algorithm to reference ?

**Comment by innerlee** [comment]
We have implemented ae https://mmpose.readthedocs.io/en/latest/papers/algorithms.html#div-align-center-associative-embedding-nips-2017-div
More bot up models will coming soon. Follow our monthly iteration plan! https://github.com/open-mmlab/mmpose/issues/631

**Comment by alicera** [comment]
Do you have the architecture figure like this
![image](https://user-images.githubusercontent.com/59388989/120738747-eb2bac80-c522-11eb-97cb-ddbf5990d9f2.png)
https://medium.com/analytics-vidhya/exploring-other-face-detection-approaches-part-1-retinaface-9b00f453fd15

**Comment by jin-s13** [comment]
No. However we have provided the bibtex for each paper. You may check the original paper for more information.

**Comment by alicera** [comment]
Where can I get the "bot up" paper to ref?
Thanks.

**Comment by jin-s13** [comment]
For example, https://mmpose.readthedocs.io/en/latest/topics/body(2d,kpt,img).html#associative-embedding-higherhrnet-on-coco

<img width="740" alt="截屏2021-06-04 上午11 05 18" src="https://user-images.githubusercontent.com/11788150/120739916-c46e7580-c524-11eb-9324-0fee6e157b1b.png">

**Comment by alicera** [comment]
请问人脸keypoint 与人体keypoint实现上有何差别?
为何不用人脸keypoint 去实现人体keypoint

**Comment by ly015** [comment]
Please open a new issue for a different topic.

**Comment by alicera** [comment]
Thanks
