### ISSUE TITLE
demo演示的时候多人不能全部检测出人体姿态

### ISSUE THREAD

**Issue by APeiZou** [open-mmlab/mmpose#700]
![vis_2](https://user-images.githubusercontent.com/49524647/120736847-933f7680-c51f-11eb-9b59-9037a711f3bc.jpg)
为什么只能检测出来一个人的姿态?是代码问题还是模型问题啊

**Comment by jin-s13** [comment]
请更新到最新版的mmpose.
Please update to the latest version.

**Comment by jin-s13** [comment]
看起来和这个PR 有关 #671

**Comment by APeiZou** [comment]
您好,这么多人姿态估计模型整体的性能怎么样啊

**Comment by jin-s13** [comment]
可以看看 [model zoo](https://mmpose.readthedocs.io/en/latest/modelzoo.html)，里面汇总了所有模型的指标。

**Comment by innerlee** [comment]
Also, here is comparison on the same dataset, e.g. coco https://mmpose.readthedocs.io/en/latest/papers/datasets.html#div-align-center-coco-eccv-2014-div

**Comment by APeiZou** [comment]
@innerlee 模型的FPS性能怎么样啊?能达到实时性吗?

**Comment by ly015** [comment]
FPS取决于具体的模型和硬件环境. 我们计划添加推理速度的测试工具和benchmark, 可以关注一下近期的更新

**Comment by ly015** [comment]
可以先参考这个来自社区的topdown模型推理速度的demo

**Comment by APeiZou** [comment]
@ly015   您好，目前来说这个仓库里面的模型有部署在Iphone上的推理速度达到150FPS的吗？

**Comment by jin-s13** [comment]
目前没有。现在mmpose里面的提供的模型，主要是学术界常用的模型，暂时没考虑直接部署。

**Comment by APeiZou** [comment]
@jin-s13 您好，这个仓库有考虑做一些模型量化和模型压缩方面的工作吗？

**Comment by ly015** [comment]
OpenMMLab有这方面的整体计划, 但短期内mmpose不会单独做这方面的支持

**Comment by innerlee** [comment]
Please open separate issues for new topics :)
