### ISSUE TITLE
About evaluation for 3d pose and mesh

### ISSUE THREAD

**Issue by CheungBH** [open-mmlab/mmpose#702]
Hello. I saw that the 3d pose and mesh training are needed to specify the argument "--no-validation". I wonder whether the evaluation code of 3d tasks will be released? For example, Protocol 1-3 for human36m, etc.

**Comment by ly015** [comment]
For 3d keypoint, we do have the evaluation code. For Human3.6M, we follow the protocol 1 and 2. Please check it [here](https://github.com/open-mmlab/mmpose/blob/c4f7c1ff7b104c05fca81ae1828ad4405d902fff/mmpose/datasets/datasets/body3d/body3d_h36m_dataset.py#L204).
For 3d mesh, we are planning to add evaluation code in the next release.

**Comment by jin-s13** [comment]
For 3d mesh evaluation, please check [this](https://github.com/open-mmlab/mmpose/blob/c4f7c1ff7b104c05fca81ae1828ad4405d902fff/mmpose/datasets/datasets/mesh/mesh_h36m_dataset.py#L92).

**Comment by CheungBH** [comment]
Thank you for your great work. I have some confusion about the 3d pose evaluation metric.
As shown in 
https://github.com/open-mmlab/mmpose/blob/1c1bcafc7a17c27383ee4d16a13202a44bcf6a52/mmpose/core/evaluation/pose3d_eval.py#L18
, the invisible joint will be ignored for calculating accuracy.
However, in common sense, the predictions should be recognized as wrong if an invisible prediction is recognized as a visible one. Once ignored, related information will miss. 
I wonder whether it is a bug for evaluating the task, or there are another protocol to evaluate such a task?

**Comment by ly015** [comment]
This is not a bug. We follow the human3.6m official evaluation tool and some previous works. In fact, human3.6m doesn't provide keypoint visibility information (which is sort of meaningless for 3D groundtruth), so we just manually set it as 1.0 for all keypoints.

**Comment by CheungBH** [comment]
Thank you so much. Previously I saw this page, and I thought that the parameters with "visible" mean key-point visibility information.
https://github.com/open-mmlab/mmpose/blob/1c1bcafc7a17c27383ee4d16a13202a44bcf6a52/mmpose/datasets/datasets/body3d/body3d_base_dataset.py#L178
BTW, I also wonder that since the key-point visibility information isn't provided, what's the physical meaning of the "input_2d_visible", "input_3d_visible", and "target_visible"?

**Comment by ly015** [comment]
For the Human3.6M dataset, these "visible" domains are meaningless. They are included here because we hope to build a general interface for 3D keypoint datasets.

**Comment by CheungBH** [comment]
Interesting...I indeed find that all the key-point visibilities of human36m are 1...
But at the same time, I found that the key-point visibility of mpi-inf-3dhp varies. And 3DPW dataset doesn't contain a "visible" domain.
<img width="1130" alt="Screenshot 2021-06-10 at 10 00 13" src="https://user-images.githubusercontent.com/39186017/121453279-7f8a8900-c9d3-11eb-9e8b-13ee3685cf91.png">
Is the visibility for **mpi-inf-3dhp** dataset meaningful?

**Comment by cherryjm** [comment]
The visibility for MPI-INF-3DHP dataset is meaningful. `visibility == 1` means that the keypoint is outside of the image. We will follow the official evaluation protocol to evaluate on MPI-INF-3DHP dataset. ( Evaluate all keypoints regardless of their visibility )

**Comment by CheungBH** [comment]
Thanks for your answer. Have a nice day~
