### ISSUE TITLE
Bottom Up PyTorch 2 ONNX - 'BottomUp is not in the models registry'

### ISSUE THREAD

**Issue by lmarschall** [open-mmlab/mmpose#710]
Hey folks,

recently I'm trying to convert my bottom_up_higher_hr_net model to onnx, in order to use it on the tensorrt architecture.
Unfortunately, the following command
`python pytorch2onnx.py {cfg} {cpkt}`
resulted in the following error
`KeyError: 'BottomUp is not in the models registry`

I was wondering if this kind of model is simply not supported (would be a shame), or if there is a general bug.
I found the following fix in the commit history, https://github.com/open-mmlab/mmpose/commit/c25e7f3435a7c6be365ad3d9d3c9df48f2d1ad04 which seems to be related to this issue.

Best Regards,

Luke

**Comment by jin-s13** [comment]
In the latest mmpose, we rename `BottomUp -> AssociativeEmbedding`, see #667 .

**Comment by lmarschall** [comment]
Hey @jin-s13,

thank you for the fast response.
I renamed every configuration parameter according to https://github.com/open-mmlab/mmpose/pull/667 and it worked fine!
I was taking a look into the actual configs for the bottom up models: https://github.com/open-mmlab/mmpose/blob/master/configs/wholebody/2d_kpt_sview_rgb_img/associative_embedding/coco-wholebody/higherhrnet_w32_coco_wholebody_512x512.py and the parameter names seem to be outdated.

Cheers, Luke
