### ISSUE TITLE
Camera parameters

### ISSUE THREAD

**Issue by NoLookDefense** [open-mmlab/mmpose#711]
Hello. I find that the camera parameter contains lots of parameters, which I think is confusing.
<img width="875" alt="Screenshot 2021-06-10 at 08 51 27" src="https://user-images.githubusercontent.com/81567453/121447822-0e45d880-c9c9-11eb-9ccc-e6839717fc07.png">
Could you kindly explain the physical meaning and its unit for the top six attributes? Thank you and look forward to your reply.

**Comment by innerlee** [comment]
Sorry clicked the wrong button.
Some are pretty standard notations, like R for rotation, T for translation.

**Comment by jin-s13** [comment]
We have complete docstring
```
param (dict): camera parameters including:
            - R: 3x3, camera rotation matrix (camera-to-world)
            - T: 3x1, camera translation (camera-to-world)
            - K: (optional) 2x3, camera intrinsic matrix
            - k: (optional) nx1, camera radial distortion coefficients
            - p: (optional) mx1, camera tangential distortion coefficients
            - f: (optional) 2x1, camera focal length
            - c: (optional) 2x1, camera center
```

**Comment by NoLookDefense** [comment]
Thanks. What's the unit of T and f? Is it mm?

**Comment by ly015** [comment]
For human3.6m the unit is meters. 
We just found that the unit of "f" is not properly handled in the h36m preprocessing script, so we fixed it here (https://github.com/open-mmlab/mmpose/pull/713). You may need to manually correct the "f" in your `cameras.pkl`. Sorry for the inconvenience.

**Comment by NoLookDefense** [comment]
Thank you! I also wonder that whether the unit of dataset "human3.6m, 3DPW, 3DHP" are different? meter for human3.6m, and millimetre for 3DPW and 3DHP?

**Comment by ly015** [comment]
For 3DHP we also use meters. 3DPW has not been supported in mmpose.

**Comment by NoLookDefense** [comment]
Oh, thanks. I am clear about it now
