### ISSUE TITLE
Bottom Up Custom Data Testing - Metric Values Indecisive

### ISSUE THREAD

**Issue by lmarschall** [open-mmlab/mmpose#715]
Hey guys,

yet another problem on my side, this time it's about the tools/test.py algorithm which doesn't seem to work
with my customized dataset, annotated with https://github.com/jsbroks/coco-annotator.

I ran the script with the official data and got ok values, but with my dataset I get only -1 and 0 values :(
Maybe there is something wrong with the way I annotated the coco key point data.

Hopefully someone can figure this out, I observed the code carefully but nothing seems to work.

Cheers,

Luke

PS:
Command
```bash
python test.py higher_hrnet32_coco_512x512.py higher_hrnet32_coco_512x512-8ae85183_20200713.pth --eval 'mAP'
```

Test Output

```bash
`Average Precision  (AP) @[ IoU=0.50:0.95 | type=   all | maxDets= 20 ] = 0.000`
`Average Precision  (AP) @[ IoU=0.50      | type=   all | maxDets= 20 ] = 0.000`
`Average Precision  (AP) @[ IoU=0.75      | type=   all | maxDets= 20 ] = 0.000`
`Average Precision  (AP) @[ IoU=0.50:0.95 | type=medium | maxDets= 20 ] = -1.000`
`Average Precision  (AP) @[ IoU=0.50:0.95 | type= large | maxDets= 20 ] = -1.000`
`Average Recall     (AR) @[ IoU=0.50:0.95 | type=   all | maxDets= 20 ] = 0.000`
`Average Recall     (AR) @[ IoU=0.50      | type=   all | maxDets= 20 ] = 0.000`
`Average Recall     (AR) @[ IoU=0.75      | type=   all | maxDets= 20 ] = 0.000`
`Average Recall     (AR) @[ IoU=0.50:0.95 | type=medium | maxDets= 20 ] = -1.000`
`Average Recall     (AR) @[ IoU=0.50:0.95 | type= large | maxDets= 20 ] = -1.000`
`AP: 0.0`
`AP (L): -1.0`
`AP (M): -1.0`
`AP .5: 0.0`
`AP .75: 0.0`
`AR: 0.0`
`AR (L): -1.0`
`AR (M): -1.0`
`AR .5: 0.0`
`AR .75: 0.0`
```
Annotation.json
https://drive.google.com/file/d/1vXD4dEXTS8mwxefkZzaV7PqPL9EMPaoy/view?usp=sharing

Result.json
https://drive.google.com/file/d/10O0Jkv5GYLg0nhKh99Y4BOey_4B6eUVX/view?usp=sharing

Config.py
https://drive.google.com/file/d/1dAokiLv7BuV9dP-JAX-UoDd4CZ8dxypG/view?usp=sharing

**Comment by jin-s13** [comment]
In your annotation.json, `"area": 0, "bbox": [0, 0, 0, 0]`. However, they are used in evaluation.

**Comment by jin-s13** [comment]
Note: `area` can be simply estimated by `area=w * h`, the area of the bbox.

**Comment by lmarschall** [comment]
Hey @jin-s13,

thanks again for the fast response, yes indeed I did not segment the data,
but I debugged the test.py script and in /mmpose/datasets/datasets/bottom_up/bottom_up_coco.py, line 264 the area is calculated by the key point values.

**Comment by jin-s13** [comment]
Hi, Luke,
Yes, they may not affect our testing codes. In fact, the generated `results.json` also looks good. 
The problem is about the coco-eval function. 
In COCO eval, gt bboxes are required for AP evaluation.

**Comment by lmarschall** [comment]
Find this by debugging bottom_up_coco.py yet again. Looks like this could be the problem.

coco_eval.cocoGt.anns[5]
`{'id': 5, 'image_id': 2, 'category_id': 1, 'segmentation': [], 'area': 0, 'bbox': [0, 0, 0, 0], 'iscrowd': False, 'isbbox': False, 'color': '#dded6c', 'keypoints': [339, 339, 2, 0, 0, 0, 319, 314, 2, ...], 'metadata': {}, 'num_keypoints': 15}`

**Comment by lmarschall** [comment]
So I updated my valid.json file by setting the bbox to [0,0,w,h] and the area to w*h and now there are some results:

 Average Precision  (AP) @[ IoU=0.50:0.95 | type=   all | maxDets= 20 ] = 0.183
 Average Precision  (AP) @[ IoU=0.50      | type=   all | maxDets= 20 ] = 0.247
 Average Precision  (AP) @[ IoU=0.75      | type=   all | maxDets= 20 ] = 0.222
 Average Precision  (AP) @[ IoU=0.50:0.95 | type=medium | maxDets= 20 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | type= large | maxDets= 20 ] = 0.183
 Average Recall     (AR) @[ IoU=0.50:0.95 | type=   all | maxDets= 20 ] = 0.188
 Average Recall     (AR) @[ IoU=0.50      | type=   all | maxDets= 20 ] = 0.247
 Average Recall     (AR) @[ IoU=0.75      | type=   all | maxDets= 20 ] = 0.223
 Average Recall     (AR) @[ IoU=0.50:0.95 | type=medium | maxDets= 20 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | type= large | maxDets= 20 ] = 0.188
AP: 0.18250574468709224
AP (L): 0.18250574468709224
AP (M): -1.0
AP .5: 0.24732673267326732
AP .75: 0.22166762612601557
AR: 0.188
AR (L): 0.188
AR (M): -1.0
AR .5: 0.2475
AR .75: 0.2225

**Comment by lmarschall** [comment]
Maybe one last question, are the gt_bbox and the gt_area necessary for training with my custom dataset, because my recent created checkpoint files perform very bad.

**Comment by jin-s13** [comment]
I think it is not necessary for bottom-up methods. But not very sure about that.
