### ISSUE TITLE
Metric list , adding new metric module

### ISSUE THREAD

**Issue by gvreergo** [open-mmlab/mmpose#721]
Hi ! 

I'm currently trying to do a benchmark of the coco dataset with the folowing metrics : PDJ , OKS and PCK , but I haven't found a way to see if they were available in mmpose nor a if i could add a metric in mmpose as a module.

Thanks in advance for your help and thank you for developping this really useful toolbox.

greetings

**Comment by jin-s13** [comment]
Please check https://github.com/open-mmlab/mmpose/blob/c8ff23fa6014a9caab3f935e10a1acb9712f155c/mmpose/datasets/datasets/top_down/topdown_coco_dataset.py#L332

Currently, we only support AP for COCO.

**Comment by gvreergo** [comment]
Thank you for your help ! I'll try to carry on from here for the implementation :+1: 

I only have one question left : the value used for threshold to differenciate positive from negative for the mAP metric for coco is it the OKS metric ?

**Comment by jin-s13** [comment]
Yes, we used OKS metric.

**Comment by gvreergo** [comment]
Thanks a lot  !

**Comment by julianzille** [comment]
Hi @greg-is-kub 
I'm also trying to evaluate my custom dataset using PCK. Were you successful in adding this as an acceptable metric?
