### ISSUE TITLE
Realtime performance question

### ISSUE THREAD

**Issue by lachose1** [open-mmlab/mmpose#73]
Hello and first of all thanks for the great tool you have built.

I wanted to ask some questions, I run the pretrained model on a 1080 ti on a realtime video and obtain so-so performances : 
res50_coco_256x192: 12 FPS
mobilenetv2_coco_256x192: 15 FPS

Am I missing something or is it just that the GPU isn't strong enough. Thanks!

**Comment by innerlee** [comment]
which script was run? currently the inference code is not optimized yet. see https://github.com/open-mmlab/mmpose/issues/40. you may vote here https://github.com/open-mmlab/mmpose/issues/9 to help us prioritize tjings

**Comment by jin-s13** [comment]
Please set `flip_test=False` in the configs for higher speed.

**Comment by lachose1** [comment]
> 
> 
> hi, which script was run? currently the inference code is not optimized yet. see #40. you may vote here #9 to help us prioritize

Yes, I used pretty much the same settings as #40 



> 
> 
> Please set `flip_test=False` in the configs for higher speed.

This was already done, but thanks for clarifying. I guess you can close the thread if this is on the road map for the future, thanks a lot for your help!

**Comment by innerlee** [comment]
thanks! it would be great if people can help with profiling and identifying the bottleneck. here is some guide we wrote earlier:

![image](https://user-images.githubusercontent.com/9464825/90701875-608ffe80-e2bc-11ea-845b-13f5675a0a7c.png)

**Comment by fabro66** [comment]
Hi~
I found cv2.ellipse2Poly in top_dow.py/bottom_up.py highly slow the inference speed.
 Please replace it with cv2.line, hrnet_w48_wholebody_348×288_dark_pllus will speed up from **1.5fps** to **8.5fps** on a **1060**. There are other areas that can be further optimized.

https://github.com/open-mmlab/mmpose/blob/9703521a4d78cbb0804c49218a681f72319c55c1/mmpose/models/detectors/top_down.py#L256
```
    for kpts in pose_result:
        # draw each point on image
        if pose_kpt_color is not None:
            assert len(pose_kpt_color) == len(kpts)
            for kid, kpt in enumerate(kpts):
                x_coord, y_coord, kpt_score = int(kpt[0]), int(
                    kpt[1]), kpt[2]
                if kpt_score > kpt_score_thr:
                    r, g, b = pose_kpt_color[kid]
                    cv2.circle(img, (int(x_coord), int(y_coord)),
                               radius, (int(r), int(g), int(b)), -1)

        # draw limbs
        if skeleton is not None and pose_limb_color is not None:
            assert len(pose_limb_color) == len(skeleton)
            for sk_id, sk in enumerate(skeleton):
                pos1 = (int(kpts[sk[0] - 1, 0]), int(kpts[sk[0] - 1,
                                                          1]))
                pos2 = (int(kpts[sk[1] - 1, 0]), int(kpts[sk[1] - 1,
                                                          1]))
                if (pos1[0] > 0 and pos1[0] < img_w and pos1[1] > 0
                        and pos1[1] < img_h and pos2[0] > 0
                        and pos2[0] < img_w and pos2[1] > 0
                        and pos2[1] < img_h
                        and kpts[sk[0] - 1, 2] > kpt_score_thr
                        and kpts[sk[1] - 1, 2] > kpt_score_thr):

                    r, g, b = pose_limb_color[sk_id]
                    cv2.line(img, pos1, pos2, (int(r), int(g), int(b)), thickness=thickness)
```

**Comment by jin-s13** [comment]
Thanks for reporting @fabro66. Will try this out.

**Comment by jinfagang** [comment]
@fabro66 How many whole post-processing time did u measured for now?

**Comment by fabro66** [comment]
@jinfagang  I did not test the time it takes for post-processing. I just replace cv2.ellipse2Poly with cv2.line to speed up inference.

**Comment by jinfagang** [comment]
@fabro66 Did u able to run **realtime** with a detector (not from GT boxes). Such as with yolov5 and a pose model.

**Comment by fabro66** [comment]
@jinfagang It can reach 16fps inference on a 1060 when I combine hrnet_w32_wholebody_256×192_dark and yolov3 (from mmdetection) to estimate whole-body keypoints.

**Comment by jinfagang** [comment]
@fabro66 I tested with yolov5s detector and shufflenetv2 pose on coco, the speed is about 7fps in 2 person on GTX1080ti.

What's the reason why it's slow?

**Comment by innerlee** [comment]
If you have interest, please try to profile it and post the result, something like https://github.com/open-mmlab/mmpose/issues/344#issuecomment-752895676

**Comment by jinfagang** [comment]
@innerlee I dont know how to using cprofile. Did u guys get same performance when test a normal video with more than 2 person in it?

**Comment by jinfagang** [comment]
@innerlee I dont know how to using cprofile. Did u guys get same performance when test a normal video with more than 2 person in it?

**Comment by innerlee** [comment]
Step1. use cProfile to run the script for a period of time, say, 30 seconds.
![image](https://user-images.githubusercontent.com/9464825/105674653-d0b54700-5f22-11eb-8edd-a5594c194f77.png)
Step2. visualize the result by snakeviz
![image](https://user-images.githubusercontent.com/9464825/105674711-e62a7100-5f22-11eb-98c1-54373ec0cb4b.png)

Refer to the instruction in https://github.com/open-mmlab/mmpose/issues/73#issuecomment-676822565 for more details

**Comment by jinfagang** [comment]
@innerlee thanks. Do u have any insights about it?

![image](https://user-images.githubusercontent.com/21303438/105685487-16790c00-5f31-11eb-94a1-20ce913ddc45.png)

**Comment by innerlee** [comment]
Please expand shared_transformation section, by clicking on it

![image](https://user-images.githubusercontent.com/9464825/105686963-d9157e00-5f32-11eb-86cb-aed1dbdb7385.png)

**Comment by jinfagang** [comment]
@innerlee 
![image](https://user-images.githubusercontent.com/21303438/105688376-7b823100-5f34-11eb-9023-0c1c78c21d41.png)

**Comment by innerlee** [comment]
Please click on the shared_transform.py, and it should print more details on the bottom level.

Crop the image is not what I meant

**Comment by jinfagang** [comment]
@innerlee ok.....

**Comment by innerlee** [comment]
@jinfagang If you haven't deleted the profiling record, please post the result so that the bottleneck is visualized

**Comment by haseeb33** [comment]
@jinfagang Can you please share the config file for yolov5 for mmdet_model. I trained a yolov5s model independently and I want to use it as a detection model for pose estimation inference but I am having difficulties modifying the config file. 
Thanks in advance.

**Comment by jinfagang** [comment]
@haseeb33 you can take a look at this repo: https://github.com/jinfagang/yolov7 it provides various yolo model with pure python instead yaml config files. Also support a e2e keypoints model

**Comment by haseeb33** [comment]
@jinfagang Thank you very much!
