### ISSUE TITLE
implementation of keypoint

### ISSUE THREAD

**Issue by alicera** [open-mmlab/mmpose#737]
请问人脸keypoint 与人体keypoint实现上有何差别?
为何不用人脸keypoint 去实现人体keypoint

**Comment by jin-s13** [comment]
In mmpose, we aim to provide a unified toolbox for all kinds of keypoints (e.g. body, face). In our implementation, they are the same.

But previously, human pose estimation (body keypoint estimation) and face alignment (face keypoint estimation) are two different research areas.

**Comment by alicera** [comment]
So body and face use the heatmap method?

**Comment by jin-s13** [comment]
Both deeppose (xy-regression based methods) and topdown heatmap based methods can be used, for body and face.

**Comment by alicera** [comment]
1.
deeppose (xy-regression based methods) follows the top-down paradigm.
So the inference image have only one human in image, right?

2.
Why not use the retinaface method to regress the human body keypoint coordinates?
Maybe it can detect the keypoint of many people in one image

**Comment by jin-s13** [comment]
1. No. The input image can contain multiple people. We can use a human detector to detect human boxes. And then for each box, run the pose estimator (e.g. deeppose).
2. Do you mean single-stage pose estimation? They generally have lower accuracy.

**Comment by alicera** [comment]
For each box, run the pose estimator .
What is the input for top-down network?
1. input a image with multiple people and bbox information (person_num, x, y, w, h), then the network output the multiple people keypoint.
2. If the detector detect three person. It will input three images and then get the three images keypoint. So it forward third time. And it can make sure every input image have one person.

Which one is correct or all wrong?

**Comment by jin-s13** [comment]
Given the bbox information, the image will be cropped into smaller images (containing one person each) before pose estimation.

**Comment by jin-s13** [comment]
check https://github.com/open-mmlab/mmpose/blob/master/demo/top_down_img_demo.py for more information.

**Comment by alicera** [comment]
ok, I got it .
The input image can contain multiple people. It is for the detector.
The input image can contain one person each . It is for the pose estimation.
