### ISSUE TITLE
Bottom-up TensorRT

### ISSUE THREAD

**Issue by alicera** [open-mmlab/mmpose#738]
Does it have the Bottom-up implementation with TensorRT?

**Comment by jin-s13** [comment]
I think we have pytorch-to-onnx. You may find some other tools for onnx-to-TensorRT.

**Comment by alicera** [comment]
https://github.com/linghu8812/tensorrt_inference/tree/master/mmpose
This project is based on top-down.


关于转成Bottom-up onnx model后，可得到网路的输出，后续需要做什么decode之类的事吗

**Comment by jin-s13** [comment]
Yes, we need decoding.
Please refer to this demo file for pre-processing and post-processing.
https://github.com/open-mmlab/mmpose/blob/master/demo/bottom_up_img_demo.py

**Comment by alicera** [comment]
Is it easy to implementation?
The decode have do the match algorithm

**Comment by jin-s13** [comment]
Actually, I am not familiar with TensorRT. But I think it might be easy to rewrite the decoding part. 
It would be great if anyone can offer some help about this.

**Comment by alicera** [comment]
Does the decoding including self.parser.parse and get_group_preds?https://github.com/open-mmlab/mmpose/blob/202983d24665a909ae1c45f4025d66794b9e32fd/mmpose/models/detectors/associative_embedding.py#L274

**Comment by jin-s13** [comment]
MMDeploy will handle these problems about deployment.
