### ISSUE TITLE
buttom-up speed

### ISSUE THREAD

**Issue by alicera** [open-mmlab/mmpose#740]
https://github.com/open-mmlab/mmpose/tree/master/configs/body/2d_kpt_sview_rgb_img/associative_embedding/coco

How about your speed for buttom-up ? 
Does it archive the real-time?
like this 
https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch

**Comment by jin-s13** [comment]
I am afraid that our currently released pre-trained models do not achieve real-time on cpu. 

It seems a good idea to support lightweight-human-pose-estimation.pytorch in MMPose. You may vote in https://github.com/open-mmlab/mmpose/issues/9.

**Comment by alicera** [comment]
By the way,
Is the mobilenet pose slower than "light-human-pose"?
Both of them have the same AP.
https://github.com/open-mmlab/mmpose/blob/master/configs/body/2d_kpt_sview_rgb_img/associative_embedding/coco/mobilenetv2_coco.md

**Comment by jin-s13** [comment]
I have not tried lightweight-human-pose-estimation.pytorch before. We have scripts to benchmark inference time.
https://github.com/open-mmlab/mmpose/blob/master/tools/benchmark_inference.py
You may have a try.
