### ISSUE TITLE
How to use MobileNetv3 as the backbone?

### ISSUE THREAD

**Issue by APeiZou** [open-mmlab/mmpose#741]

**Comment by jin-s13** [comment]
Only 3 lines to modify.

1. If you do not have pre-trained model, you have to set pretrained=''
https://github.com/open-mmlab/mmpose/blob/202983d24665a909ae1c45f4025d66794b9e32fd/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/mobilenetv2_coco_256x192.py#L42

2. Use MobileNetv3
https://github.com/open-mmlab/mmpose/blob/202983d24665a909ae1c45f4025d66794b9e32fd/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/mobilenetv2_coco_256x192.py#L43

3. If the channel is different, you may need to change the number of channels.
https://github.com/open-mmlab/mmpose/blob/202983d24665a909ae1c45f4025d66794b9e32fd/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/mobilenetv2_coco_256x192.py#L46

**Comment by APeiZou** [comment]
1.set   pretrained='mmcls://mobilenet_v3'  is  ok？     
2. set   in_channels=1280  is  ok？

**Comment by jin-s13** [comment]
```
# model settings
model = dict(
    type='TopDown',
    pretrained=None,
    backbone=dict(type='MobileNetV3', arch='small', out_indices=(10, )),
    keypoint_head=dict(
        type='TopDownSimpleHead',
        in_channels=96,
        out_channels=channel_cfg['num_output_channels'],
        loss_keypoint=dict(type='JointsMSELoss', use_target_weight=True)),
    train_cfg=dict(),
    test_cfg=dict(
        flip_test=True,
        post_process='default',
        shift_heatmap=True,
        modulate_kernel=11))
```

or 
```
# model settings
model = dict(
    type='TopDown',
    pretrained=None,
    backbone=dict(type='MobileNetV3', arch='big', out_indices=(14, )),
    keypoint_head=dict(
        type='TopDownSimpleHead',
        in_channels=160,
        out_channels=channel_cfg['num_output_channels'],
        loss_keypoint=dict(type='JointsMSELoss', use_target_weight=True)),
    train_cfg=dict(),
    test_cfg=dict(
        flip_test=True,
        post_process='default',
        shift_heatmap=True,
        modulate_kernel=11))
```

**Comment by jin-s13** [comment]
_1. pretrained='mmcls://mobilenet_v3' is ok？_
No. Since MMClassification did not provide such a checkpoint, so we can't use it.
_2. set in_channels=1280 is ok？_
No. It should match the output of the MobileNetV3 backbone.

**Comment by jin-s13** [comment]
I notice that OpenMMLab has provided the link for pre-trained mobilenet_v3. Please try this.

  "contrib/mobilenet_v3_large": "https://download.openmmlab.com/pretrain/third_party/mobilenet_v3_large-bc2c3fd3.pth",
  "contrib/mobilenet_v3_small": "https://download.openmmlab.com/pretrain/third_party/mobilenet_v3_small-47085aa1.pth",

**Comment by rubeea** [comment]
> TopDownSimpleHead

@jin-s13 there is no keyoint_head with TopDownSimpleHead. So should we use the TopdownHeatmapSimpleHead instead for mobilenet v3 experiments?

**Comment by jin-s13** [comment]
Yes. see #667.

**Comment by rubeea** [comment]
> Yes. see #667.

Ok noted thanks a lot :)
