### ISSUE TITLE
mmcv version incompatibility

### ISSUE THREAD

**Issue by hrisk** [open-mmlab/mmpose#748]
I just noticed there is a version incompatibility issue for mmcv when trying to run the demo files. 
mmpose/__init__.py requires the mmcv version to be between 1.1.3 to 1.3 
![image](https://user-images.githubusercontent.com/63486544/123555093-e2976080-d7c6-11eb-9e44-8f74549efa6e.png)
where as mmdet/__init__.py requires the mmcv version to be between 1.3.2 to 1.4.0
![image](https://user-images.githubusercontent.com/63486544/123555117-11153b80-d7c7-11eb-9fcf-dcf87f6da886.png)
also, the instalation file just says it needs latest version on mmcv. 
![image](https://user-images.githubusercontent.com/63486544/123555160-52a5e680-d7c7-11eb-8a7c-aabe212f43ef.png)

can someone please fix the incompatibility?

**Comment by innerlee** [comment]
Please update mmpose to the latest version

**Comment by hrisk** [comment]
> Please update mmpose to the latest version

thank you. that worked. My bad
