### ISSUE TITLE
Error occurs when converting to onnx

### ISSUE THREAD

**Issue by SimonHuang135** [open-mmlab/mmpose#750]
![image](https://user-images.githubusercontent.com/54711980/123601501-56b72000-d82a-11eb-9793-23b457c78777.png)

The topdown_heatmap config file has this problem, due to the code shown below

![image](https://user-images.githubusercontent.com/54711980/123601892-c7f6d300-d82a-11eb-8aa0-dc80dcf4e513.png)
(pic from configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/onehand10k/res50_onehand10k_256x256.py)

it should change to **'TopdownHeatmapSimpleHead'**, OW the convertion would not work.

But I am curious that does the training skip the head? cuz the training and converting use the same config file.

So, does other config files which use the topdown_heatmap need to be changed?

**Comment by innerlee** [comment]
Pls checkout https://github.com/open-mmlab/mmpose/pull/734

**Comment by jin-s13** [comment]
It will not affect training/testing, 'TopDownSimpleHead' will work the same as 'TopdownHeatmapSimpleHead'.

see

https://github.com/open-mmlab/mmpose/blob/51b268f77f3f239dead86054ed05a212d62955c0/mmpose/deprecated.py#L100
