### ISSUE TITLE
if 'caption' in anns[0]: IndexError: list index out of range

### ISSUE THREAD

**Issue by luolugithub** [open-mmlab/mmpose#753]
1, ENV: ubuntu20.04, conda3.7; 2, DATA: custom  15 keypoints coco dataset; 3, try to fintuning on "https://download.openmmlab.com/mmpose/top_down/resnet/res50_coco_256x192-ec54d7f3_20200709.pth"; got this error:  File "/home/xkjs/NDisk/PycharmProjects/mmpose/mmpose/datasets/datasets/top_down/topdown_coco_dataset.py", line 442, in _do_python_keypoint_eval
    coco_det = self.coco.loadRes(res_file)
  File "/home/xkjs/anaconda3/envs/mmpose/lib/python3.7/site-packages/xtcocotools-1.8-py3.7-linux-x86_64.egg/xtcocotools/coco.py", line 341, in loadRes
    if 'caption' in anns[0]:
IndexError: list index out of range
Killing subprocess 842796
Killing subprocess 842797

**Comment by jin-s13** [comment]
Is the res_file empty?

**Comment by luolugithub** [comment]
yes, it's empty. how to solve it?

**Comment by jin-s13** [comment]
Please check  
1. https://github.com/open-mmlab/mmpose/blob/master/docs/tutorials/1_finetune.md for tutorials about finetuning.
2. https://github.com/open-mmlab/mmpose/blob/master/docs/tutorials/2_new_dataset.md for tutorials about adding new dataset.

**Comment by jin-s13** [comment]
Please notice that, to evaluate on custom datasets
We have two choices:
1. set `use_gt_bbox=True` in config or 2. providing `bbox_file` the detection results.
