### ISSUE TITLE
epoch num in checkpoint file is incorrect

### ISSUE THREAD

**Issue by canghaiyunfan** [open-mmlab/mmpose#756]
Thanks for your error report and we appreciate it a lot.
If you feel we have helped you, give us a STAR! :satisfied:

**Checklist**

1. I have searched related issues but cannot get the expected help.
1. The bug has not been fixed in the latest version.

**Describe the bug**

![image](https://user-images.githubusercontent.com/21115878/124053405-c0197780-da52-11eb-9d10-cce073386fbd.png)

**Comment by innerlee** [comment]
See https://github.com/open-mmlab/mmcv/pull/1108
