### ISSUE TITLE
multi datasets

### ISSUE THREAD

**Issue by syusukee** [open-mmlab/mmpose#757]
Hi，if I want to use several datasets for training in the meanwhile, how can I realize it? Hope you can show me a simple instruction. Thanks a lot!! @jin-s13

**Comment by innerlee** [comment]
See https://github.com/open-mmlab/mmpose/pull/387

**Comment by syusukee** [comment]
Another question, I can't find the relative code in master branch, is it  has been deleted  in later code and only in  the fuse_dataset branch？


> See #387

**Comment by jin-s13** [comment]
Using multiple datasets can be complicated, especially when the keypoint definition for these datasets are different. 
#387 is not fully completed, so we did not merge it. But `ConcatDataset` pipeline in #387 may be useful. Please check

**Comment by jin-s13** [comment]
Also related to the Discussion #662.

**Comment by syusukee** [comment]
Got it and thanks for your reply!!
