### ISSUE TITLE
mmcv toolkits can not import

### ISSUE THREAD

**Issue by ss24cs** [open-mmlab/mmpose#77]
Hi, buddies, In my virtual env, I run a test demo: ./tools/dist_test.sh configs/top_down/resnet/coco/res50_coco_256x192.py checkpoints/res50_coco_256x192-ec54d7f3_20200709.pth 2 --eval mAP
and I got a env problems: ImportError: cannot import name 'EpochBasedRunner' from 'mmcv.runner' (/home/stelo/anaconda3/envs/mmpose/lib/python3.7/site-packages/mmcv/runner/__init__.py)
should I rebuild my env? Or conda  remove mmcv packages and reinstall it?

**Comment by jin-s13** [comment]
Please try to install the latest version of MMCV and retry. Thanks.

**Comment by innerlee** [comment]
the change was made in mmcv v0.6.0. ref https://github.com/open-mmlab/mmcv/pull/290
