### ISSUE TITLE
重现实现body3d_two_stage_video_demo.py 代码的demo出现问题

### ISSUE THREAD

**Issue by 642802017** [open-mmlab/mmpose#790]
报错如下，  希望可以得到帮助
![A5EAC031-3713-49E9-A569-B0165593271A](https://user-images.githubusercontent.com/85287122/125883219-85e439f2-6a2f-4b8d-b41d-3707fcb3929d.png)

**Comment by jin-s13** [comment]
Please reinstall the latest mmcv-full.

**Comment by jin-s13** [comment]
Is the problem solved?

**Comment by 642802017** [comment]
解决了   谢谢聚聚
