### ISSUE TITLE
如何理解3d模型得到的关键点坐标值

### ISSUE THREAD

**Issue by 642802017** [open-mmlab/mmpose#791]
我知道2维关键点坐标值是 像素点坐标+置信度
但是三维坐标如下，在百度无果后，我有些难以理解这些数值，我想做的事情是检测人体左臂三个关键点之间的夹角变化
我希望得到一些帮助，如何理解和使用这些数据，或者给定一些关键词，使得我可以搜索到该知识点
![image](https://user-images.githubusercontent.com/85287122/125887926-aef3ce9c-1d46-469c-8347-df25c21b66be.png)

**Comment by ly015** [comment]
Each row is a keypoint coordinate represented as (x, y, z, confidence). The definition of axes depends on the dataset and preprocessing method. If you are using the human3.6m dataset and the default pipeline, the keypoint coordinate is in the camera space and z is the depth.

If you are only interested in the upper arm and lower arm angle, the coordinate space definition is not important here. You can find the keypoint order in mmpose/datasets/datasets/body3d/body3d_h36m_dataset.py.

**Comment by 642802017** [comment]
直接对         11: 'left_shoulder',12: 'left_elbow',13: 'left_wrist', 的三维坐标做差得到向量，然后求两个向量夹角来表示左臂夹角的方式得出的结果并不是很好，请问这是什么原因呢

**Comment by ly015** [comment]
You can use the demo script to check if the 3d keypoint prediction is reasonable on your data.

**Comment by hsp2454** [comment]
How do you output these keypoint coordinates？
