### ISSUE TITLE
performance question

### ISSUE THREAD

**Issue by johnlanbor** [open-mmlab/mmpose#8]
I followed get_start.md , download model form https://mmpose.readthedocs.io/en/latest/model_zoo.html model_name is pose_resnet_50 and img_size is 156*192
use 
`python -m torch.distributed.launch --nproc_per_node=8 tools/test.py configs/top_down/resnet/coco/res50_coco_256x192.py checkpoints/res50_coco_256x192-ec54d7f3_20200709.pth --launcher pytorch --eval mAP`

but got 
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = 0.735
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets= 20 ] = 0.925
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets= 20 ] = 0.814
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = 0.706
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = 0.779
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = 0.765
 Average Recall     (AR) @[ IoU=0.50      | area=   all | maxDets= 20 ] = 0.934
 Average Recall     (AR) @[ IoU=0.75      | area=   all | maxDets= 20 ] = 0.833
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = 0.733
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = 0.814
so whats wrong?

**Comment by Canwang-sjtu** [comment]
you should set `use_gt_bbox=False`  in  configs/top_down/resnet/coco/res50_coco_256x192.py

**Comment by Canwang-sjtu** [comment]
You can retrain or test with the updated config file

**Comment by johnlanbor** [comment]
ok,thanks
