### ISSUE TITLE
I don't have my_custom_config.py file in configs folder?

### ISSUE THREAD

**Issue by alankar66** [open-mmlab/mmpose#803]
As per the model documentation:-

After the data pre-processing, the users need to further modify the config files to use the dataset.

In configs/my_custom_config.py:

but I don't have  my_custom_config.py   file in configs folder, I am adding custom dataset

**Comment by innerlee** [comment]
`my_custom_config` is a placeholder. Typically your config is modified from an existing one. So pick a similar one from existing configs and modify it to fit your custom dataset.

**Comment by wangm-word** [comment]
how do you get your oun dayaset?canyou tell me ,than you very much@alankar66

**Comment by jin-s13** [comment]
We have updated the tutorial about adding new dataset. And I will close this issue for now.
