### ISSUE TITLE
Multi-GPU training return cuda memory error

### ISSUE THREAD

**Issue by ss24cs** [open-mmlab/mmpose#81]
Pardon me, buddies, I'm planed to training the wonderful frame, and used this command: ./tools/dist_train.sh configs/top_down/resnet/coco/res50_coco_256x192.py  **2** --no-validate;
So, I got a cuda memory problem: when I set gpu_num=2, it's return a cuda memory error. If I changed gpu_num =1, it's works, and begin training, no memory error return.
The Nvidia configuration (set gpu=1, it  has been running):
| NVIDIA-SMI 440.36       Driver Version: 440.36       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 2070    Off  | 00000000:01:00.0  On |                  N/A |
| 90%   71C    P2   170W / 175W |   7966MiB /  7979MiB |     97%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 2070    Off  | 00000000:03:00.0 Off |                  N/A |
| 50%   40C    P8     9W / 175W |     12MiB /  7982MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage     
 
Did my torch envs problem? Or system problem?

**Comment by innerlee** [comment]
could you post the full error log?

**Comment by ss24cs** [comment]
> could you post the full error log?

Ok, here is, and running command: ./tools/dist_train.sh configs/top_down/resnet/coco/res50_coco_256x192.py 2 --no-validate ;
error log:
RuntimeError: CUDA out of memory. Tried to allocate 192.00 MiB (GPU 0; 7.79 GiB total capacity; 6.33 GiB already allocated; 12.94 MiB free; 6.75 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "/home/stelo/anaconda3/envs/mmpose/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/stelo/anaconda3/envs/mmpose/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/stelo/anaconda3/envs/mmpose/lib/python3.7/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/stelo/anaconda3/envs/mmpose/lib/python3.7/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/stelo/anaconda3/envs/mmpose/bin/python', '-u', './tools/train.py', '--local_rank=1', 'configs/top_down/resnet/coco/res50_coco_256x192.py', '--launcher', 'pytorch', '--no-validate']' returned non-zero exit status 1.

**Comment by innerlee** [comment]
if you reduce the batch size, could it run?

**Comment by ss24cs** [comment]
> if you reduce the batch size, could it run?

Yeah, thanks buddy, it's works.
