### ISSUE TITLE
How to check pytorch2onnx correct

### ISSUE THREAD

**Issue by PeiqiWang** [open-mmlab/mmpose#821]
I use tools/deployment/pytorch2onnx.py to convert a checkpoint to the onnx model and use `--verify` to check the resulting model. If it turns out `The outputs are different between Pytorch and ONNX`, does this mean I get a wrong onnx model? What should I do to get a correct onnx model?   Thanks! 

**Command :**
```
python .ools/deployment/pytorch2onnx.py 
 configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/4xmspn50_coco_256x192.py checkpoints/4xmspn50_coco_256x192-7b837afb_20201123.pth --verify --shape 1 3 256 192

```

**Comment by jin-s13** [comment]
@grimoire  Could you offer some help?

**Comment by grimoire** [comment]
Hi,
We set the test threshold `atol=1.e-5` and `rtol=1.e-5` which is very small. The generated onnx model failed the test does not means it is a wrong model. Just test it on real image and see if it works as you expected.

**Comment by PeiqiWang** [comment]
> Hi,
> We set the test threshold `atol=1.e-5` and `rtol=1.e-5` which is very small. The generated onnx model failed the test does not means it is a wrong model. Just test it on real image and see if it works as you expected.

I try it on a real image and the results are correct. And The maximum diff value is 9e-05, which is also reasonable. Thanks!

**Comment by Blankit** [comment]
> I use tools/deployment/pytorch2onnx.py to convert a checkpoint to the onnx model and use `--verify` to check the resulting model. If it turns out `The outputs are different between Pytorch and ONNX`, does this mean I get a wrong onnx model? What should I do to get a correct onnx model? Thanks!
> 
> **Command :**
> 
> ```
> python .ools/deployment/pytorch2onnx.py 
>  configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/4xmspn50_coco_256x192.py checkpoints/4xmspn50_coco_256x192-7b837afb_20201123.pth --verify --shape 1 3 256 192
> ```

I met the same question when  I trans pytorch model to  onnx model

**Comment by YuanZi1501040205** [comment]
I am facing the same issue, the onnx generated by 

```
pose model
!python3 /content/mmpose/tools/deployment/pytorch2onnx.py /content/mmpose/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/aik/hrnet_w32_coco_256x192.py /content/epoch_40.pth --output-file /content/epoch_40.onnx

```

are output different keypoints results compared to the .pth file.
