### ISSUE TITLE
add 2d keypoints

### ISSUE THREAD

**Issue by li2058088** [open-mmlab/mmpose#822]
在原有coco 17个人体关键点基础上 + coco foot对应的6个脚部点(后跟、大脚趾、小脚趾)
配置文件修改
hrnet_w48_coco_256x192.py
`
channel_cfg = dict(
    num_output_channels=23,
    dataset_joints=23,
    dataset_channel=[
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
    ],
    inference_channel=[
        0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22
    ])
`

mmpose/datasets/datasets/top_down/topdown_coco_dataset.py
`
self.ann_info['flip_pairs'] = [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12], [13, 14], [15, 16],
                                       [17, 20], [18, 21], [19, 22]]

self.ann_info['upper_body_ids'] = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
self.ann_info['lower_body_ids'] = (11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22)
`

训练后的模型，预测结果容易出现脚部新加的6个点左右交叉，是否还有人体关键点骨骼定义需要修改？

**Comment by ly015** [comment]
请问模型指标AP/AR看起来正常么, 只是可视化结果不对?

**Comment by li2058088** [comment]
> 请问模型指标AP/AR看起来正常么, 只是可视化结果不对?

指标AP/AR还正常，可视化结果不对，可视化代码我重写了
![image](https://user-images.githubusercontent.com/29444731/127440155-52144931-9877-4f25-b345-a98f35a57749.png)
![image](https://user-images.githubusercontent.com/29444731/127440260-d96dad1f-871e-4b14-b11a-b7e9597452a9.png)
正确如下
![image](https://user-images.githubusercontent.com/29444731/127440337-cfd7cb05-4c1e-4527-a084-fbbbbc208061.png)

**Comment by jin-s13** [comment]
需要注意，可视化有两处需要修改：
https://github.com/open-mmlab/mmpose/blob/070110ea9c4ebfe6e44658f04423897423969582/mmpose/apis/inference.py#L186
https://github.com/open-mmlab/mmpose/blob/070110ea9c4ebfe6e44658f04423897423969582/mmpose/apis/inference.py#L566

**Comment by li2058088** [comment]
> 需要注意，可视化有两处需要修改：
> https://github.com/open-mmlab/mmpose/blob/070110ea9c4ebfe6e44658f04423897423969582/mmpose/apis/inference.py#L186
> 
> 
> https://github.com/open-mmlab/mmpose/blob/070110ea9c4ebfe6e44658f04423897423969582/mmpose/apis/inference.py#L566

可视化的代码是自己写的，没有使用mmpose的可视化代码，上面三张图都是预测出来的，脚部点左右交叉错误占很大一部分。
数据集中有标注6个脚部点(后跟、大脚趾、小脚趾)比较少，我将左右脚踝点数据部分清零，让标注脚踝的点和6个脚部点数量持平，训练后预测出来的脚踝点却没有出现左右交叉的情况

**Comment by 2050airobert** [comment]
@jin-s13  @ly015  请问下，如果我只想训练coco wholebody 133个关键点中的一部分子集比如88个点，请问如何修改不会影响模型效果，是否有相应文档链接指导呢？ 
如果没有，请问修改的文件和位置可否给出，多谢

**Comment by jin-s13** [comment]
@2050airobert 
相当于新增数据集   https://github.com/open-mmlab/mmpose/blob/master/docs/zh_cn/tutorials/2_new_dataset.md

**Comment by 2050airobert** [comment]
@jin-s13 
看起来，如果json格式基本不变，只是增加或者减少关键点数量，只需要添加这个文件即可，对吗？
![image](https://user-images.githubusercontent.com/8407513/186810058-52a40472-b1ed-46ee-ae23-1abc2bbd84f8.png)
有木有添加这个文件的书写格式 参考呢？ 比如具体该填写什么的一个参考实例？ 多谢

**Comment by jin-s13** [comment]
恩，对的。configs/_base_/datasets/  下面有很多数据集的例子，可以参考一个比较熟悉的 比如coco。
----
另外，如果有其他问题，建议新开一个issue讨论。保证我们每个issue，只讨论一个问题，会比较清晰。
