### ISSUE TITLE
可视化推理

### ISSUE THREAD

**Issue by wangm-word** [open-mmlab/mmpose#826]
你好，我可以用你们的可视化推理代码，去推理mmpose还没有的模型吗

**Comment by wangm-word** [comment]
![image](https://user-images.githubusercontent.com/72743278/127612726-d43d4dfb-b927-4f84-aca2-aa40ce206956.png)

**Comment by ly015** [comment]
你好, 欢迎使用mmpose中的代码. 如果是用在其他项目或产品中, 请参考license ([Apache 2.0](https://github.com/open-mmlab/mmpose/blob/master/LICENSE))中的相关要求.
