### ISSUE TITLE
Issue of generating COCO_val2017_detections_AP_H_56_person.json

### ISSUE THREAD

**Issue by acc15ms** [open-mmlab/mmpose#83]
![2020-08-24 19-18-25屏幕截图](https://user-images.githubusercontent.com/32274553/91039197-b22ee500-e63e-11ea-855c-831960dd0fe3.png)
Firstly, thanks for sharing the mmpose as open source project.

The code is successfully installed on my PC and the demo runs successfully. However, when I try to run scripts/test.py in order to check the mAP on mscoco dataset, the error happened with FileNotFoundError: [Errno 2] No such file or directory: 'data/coco/person_detection_results/COCO_val2017_detections_AP_H_56_person.json'. I thought when I the .json file should be generated when the demo run. Am I right ? Is there any suggestion that how can I find or generate this .json file ?

Thank you and Best wishes

**Comment by jin-s13** [comment]
Hi,
Please follow 
[Getting Started](https://github.com/open-mmlab/mmpose/blob/master/docs/getting_started.md) to prepare the data.
Please download the file from [this link](https://onedrive.live.com/?authkey=%21ANejPkF4WXyxYz4&id=56B9F9C97F261712%2110160&cid=56B9F9C97F261712)
