### ISSUE TITLE
Multi-view 3d pose estimation

### ISSUE THREAD

**Issue by CheungBH** [open-mmlab/mmpose#864]
Hello. Will multi-view-3d-pose-estimation be added in the repo?

**Comment by jin-s13** [comment]
Yes, we have plans to do that.

**Comment by jin-s13** [comment]
Do you have any recommended papers/codes? 
It would be much appreciated if you would like to contribute.

**Comment by CheungBH** [comment]
Yeah, certainly.
There are 3 baseline papers, two of which have runnable code provided, while the remaining one doesn't have training code.

Learnable Triangulation of Human Pose
https://github.com/karfly/learnable-triangulation-pytorch

Epipolar Transformers
https://github.com/yihui-he/epipolar-transformers

Cross view fusion for 3d human pose estimation
(This paper doesn't have code for training. Maybe you can reproduce this paper hhhh)
