### ISSUE TITLE
demo question

### ISSUE THREAD

**Issue by kobe233333** [open-mmlab/mmpose#882]
when i do the demo inference using top-down method, why should i offer the json file ? Is the gt bbox being using ?

**Comment by jin-s13** [comment]
See
https://mmpose.readthedocs.io/en/latest/demo.html#using-gt-human-bounding-boxes-as-input
https://mmpose.readthedocs.io/en/latest/demo.html#using-mmdet-for-human-bounding-box-detection

**Comment by kobe233333** [comment]
> See
> https://mmpose.readthedocs.io/en/latest/demo.html#using-gt-human-bounding-boxes-as-input
> https://mmpose.readthedocs.io/en/latest/demo.html#using-mmdet-for-human-bounding-box-detection

I wonder when we use topdown method to train my own model on own dataset, if we train the detector while we train the keypoint estimator ? Or we just use the mmdet pretrained model ?

**Comment by jin-s13** [comment]
We did not train the human detector. Just use the mmdet pretrained model.

**Comment by kobe233333** [comment]
> We did not train the human detector. Just use the mmdet pretrained model.

If the person in the picture is not detected, is the key information of the picture not used in the training？

**Comment by jin-s13** [comment]
We use gt bounding boxes (instead of detected box) to train the model.

**Comment by kobe233333** [comment]
Did you use all the information during training because GT was used, but during testing only detected boxes are using to get keypoints? Thanks

**Comment by jin-s13** [comment]
Yes.

**Comment by kobe233333** [comment]
Appreciate!
