### ISSUE TITLE
Issue with testing using distributed and mpii

### ISSUE THREAD

**Issue by pablovela5620** [open-mmlab/mmpose#89]
So I was trying to test the mpii dataset using both `test.py` and `./tool/dist_test.sh` and came across this small issue. It looks like mpii uses the evaluation metric `PCKh` rather than `mPA` so I changed the args as follows

For `test.py`
```\
 python tools/test.py configs/top_down/hrnet/mpii/hrnet_w32_mpii_256x256.py ~/0Dev/data/models/hrnet_w32_mpii_256x256-6c4f923f_20200812.pth --eval PCKh
```
for `./tools/dist_test.sh`
```\
./tools/dist_test.sh configs/top_down/hrnet/mpii/hrnet_w32_mpii_256x256.py ~/0Dev/data/models/hrnet_w32_mpii_256x256-6c4f923f_20200812.pth 2 --eval PCKh
```

I get the assertion error saying that metric != PCKh and modified the error so I could figure out what was going on and saw
```
assert metric == 'PCKh', f"got {metric}"
AssertionError: got ['PCKh']
```

I'm fairly new to this repo so I don't know the ins and outs enough to make a pull request, so I wanted to make you guys aware of this issue!

**Comment by jin-s13** [comment]
Thanks for reporting. I will check this.

**Comment by jin-s13** [comment]
Will be fixed in this [commit](https://github.com/open-mmlab/mmpose/pull/87/commits/5a46dfb06b3a27b649cdad464f982042aec6f0ed).

**Comment by pablovela5620** [comment]
I also just noticed that it looks like most mpii configs have their `evaluation = dict(interval=1, metric='mPA')` rather than 'PCKh` which will cause errors when evaluating

**Comment by jin-s13** [comment]
Thanks! Yes, It should be PCKh. 
We will fix the typos.

**Comment by jin-s13** [comment]
#93
