### ISSUE TITLE
Inference error when channel order is not rgb

### ISSUE THREAD

**Issue by yl-1993** [open-mmlab/mmpose#895]
https://github.com/open-mmlab/mmpose/blob/master/mmpose/apis/inference.py#L136

When `channel_order` is not equal to `'rgb'`, the variable `img` will be referenced before assignment in https://github.com/open-mmlab/mmpose/blob/master/mmpose/apis/inference.py#L142

**Comment by jin-s13** [comment]
Thanks for reporting this issue. We will fix it soon.

**Comment by jin-s13** [comment]
Fixed by #913
