### ISSUE TITLE
InterHand2.6M Annotations

### ISSUE THREAD

**Issue by Zhang-ze-peng** [open-mmlab/mmpose#899]
Thanks for your great work! 

The download link for the [InterHand2.6m annotation](https://github.com/facebookresearch/InterHand2.6M/releases/download/v0.0/InterHand2.6M.annotations.5.fps.zip) seems to failed, could you please fix it or give another link?

Thanks again!

**Comment by ly015** [comment]
@zengwang430521 Should it be `v1.0` now? If so, please update the links.

**Comment by zengwang430521** [comment]
I will update the link in [PR 913](https://github.com/open-mmlab/mmpose/pull/913).

**Comment by jin-s13** [comment]
Fixed by #913
