### ISSUE TITLE
ground truth keypoints question

### ISSUE THREAD

**Issue by zzz731621** [open-mmlab/mmpose#900]
Can I use keypoints exceed image size in training jsonfile?  or I need to adjust it
Thank you !!

**Comment by jin-s13** [comment]
Do not worry. These keypoints will not affect training.

**Comment by zzz731621** [comment]
So when I run demo.py, it is posible to get keypoint exceed image size with my model?

**Comment by jin-s13** [comment]
No. During training, these out-of-image keypoints will be ignored, and will not be trained. 
But, when you run demo, the detected keypoints will not exceed the image size.

**Comment by zzz731621** [comment]
Appreciate !!!!
