### ISSUE TITLE
json output

### ISSUE THREAD

**Issue by kobe233333** [open-mmlab/mmpose#907]
When i use the demo/bottom_up_img_demo.py to test on a list of imgs, where can i get the json file of keypoints of every single img ?

**Comment by ly015** [comment]
This JSON file follows the COCO annotation format and is only used to provide image information. You can create such a JSON file for your own images like:

```
{
"images": [
    {
         "file_name": image1.jpg",
         "height": 100,
         "width": 100,
         "id": 1
    },
    {
         "file_name": image2.jpg",
         "height": 100,
         "width": 100,
         "id": 2
    }]
}
```

**Comment by kobe233333** [comment]
> This JSON file follows the COCO annotation format and is only used to provide image information. You can create such a JSON file for your own images like:
> 
> ```
> {
> "images": [
>     {
>          "file_name": image1.jpg",
>          "height": 100,
>          "width": 100,
>          "id": 1
>     },
>     {
>          "file_name": image2.jpg",
>          "height": 100,
>          "width": 100,
>          "id": 2
>     }]
> }
> ```

sorry, I didn't make it clear. I want to know how to get the output keypoints predicted by models?

**Comment by ly015** [comment]
You can get the predicted keypoints in `pose_results` here: https://github.com/open-mmlab/mmpose/blob/8f005ac9c57f7e052f7805337ac9887f5b162620/demo/bottom_up_img_demo.py#L90

In the demo script, we only visualize the results. You can output them to a file if needed.

**Comment by kobe233333** [comment]
> You can get the predicted keypoints in `pose_results` here:
> 
> https://github.com/open-mmlab/mmpose/blob/8f005ac9c57f7e052f7805337ac9887f5b162620/demo/bottom_up_img_demo.py#L90
> 
> In the demo script, we only visualize the results. You can output them to a file if needed.

Appreciate
