### ISSUE TITLE
mpii dataset question

### ISSUE THREAD

**Issue by zzz731621** [open-mmlab/mmpose#911]
How do I generate the mat file in the annotations folder?
I want to use my own dataset but there is no mpii_gt_val.mat file
thank you!!

**Comment by jin-s13** [comment]
The official annotation file provided by MPII team is .mat.
We did not provide any scripts to generate it.
I would like to recommend using coco-json format.

**Comment by jin-s13** [comment]
BTW, to generate coco-json file, please refer to https://github.com/open-mmlab/mmpose/tree/master/tools/dataset

**Comment by zzz731621** [comment]
Thank you !
