### ISSUE TITLE
How to eliminate keypoint jittering in videos?

### ISSUE THREAD

**Issue by kobe233333** [open-mmlab/mmpose#912]
When I use video as input for prediction, the key points will be slightly jittery. Is there an algorithm to avoid it? (Assuming the camera is fixed)

**Comment by jin-s13** [comment]
You may try one euro filter.
https://github.com/open-mmlab/mmpose/blob/8f005ac9c57f7e052f7805337ac9887f5b162620/mmpose/core/post_processing/one_euro_filter.py

**Comment by kobe233333** [comment]
> You may try one euro filter.
> https://github.com/open-mmlab/mmpose/blob/8f005ac9c57f7e052f7805337ac9887f5b162620/mmpose/core/post_processing/one_euro_filter.py

I wonder how to use this function when i got keypoints of all frames of one video ?

**Comment by jin-s13** [comment]
Here is the test script. Please have a try.
https://github.com/open-mmlab/mmpose/blob/c85159da60f25bc6bbab763c37c2be1e49e4052f/tests/test_post_processing/test_filter.py
