### ISSUE TITLE
Associative Embedding + Hourglass

### ISSUE THREAD

**Issue by kobe233333** [open-mmlab/mmpose#914]
If there is model of Associative Embedding + Hourglass or Associative Embedding +CPN ?

**Comment by jin-s13** [comment]
Associative Embedding + Hourglass: Please can check #906 
Associative Embedding +CPN is not implemented.

**Comment by kobe233333** [comment]
thanks， and another question is that if there is a function provided to get PCK metric when my imgs contain only single person?

**Comment by jin-s13** [comment]
You may refer to https://github.com/open-mmlab/mmpose/blob/2e81fa61cc097ee34e6307c58111b273eaee8a13/mmpose/datasets/datasets/base/kpt_2d_sview_rgb_img_top_down_dataset.py#L239

**Comment by kobe233333** [comment]
> You may refer to
> 
> https://github.com/open-mmlab/mmpose/blob/2e81fa61cc097ee34e6307c58111b273eaee8a13/mmpose/datasets/datasets/base/kpt_2d_sview_rgb_img_top_down_dataset.py#L239

IF bottom up method can use this function?

**Comment by jin-s13** [comment]
If the image only contains a single person, I think this function is applicable.

**Comment by kobe233333** [comment]
okay, i would like to try. Appreciate
