### ISSUE TITLE
KeyError: 'use_different_joint_weights'

### ISSUE THREAD

**Issue by zzz731621** [open-mmlab/mmpose#915]
File "tools/train.py", line 170, in <module>
    main()
  File "tools/train.py", line 166, in main
    meta=meta)
  File "/home/lab602.10977028/mmpose/mmpose/apis/train.py", line 142, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/lab602.10977028/mmcv/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/lab602.10977028/mmcv/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/lab602.10977028/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/lab602.10977028/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/lab602.10977028/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/lab602.10977028/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/lab602.10977028/mmpose/mmpose/datasets/datasets/base/kpt_2d_sview_rgb_img_top_down_dataset.py", line 272, in __getitem__
    return self.pipeline(results)
  File "/home/lab602.10977028/mmpose/mmpose/datasets/pipelines/shared_transform.py", line 88, in __call__
    data = t(data)
  File "/home/lab602.10977028/mmpose/mmpose/datasets/pipelines/top_down_transform.py", line 547, in __call__
    self.sigma)
  File "/home/lab602.10977028/mmpose/mmpose/datasets/pipelines/top_down_transform.py", line 285, in _msra_generate_target
    use_different_joint_weights = cfg['use_different_joint_weights']
KeyError: 'use_different_joint_weights'

What is the cause of this error ?

**Comment by jin-s13** [comment]
What is the version of MMPose?

**Comment by zzz731621** [comment]
Sorry I don't know how to check the version, but I downloaded it today

**Comment by jin-s13** [comment]
@liqikai9 Could you check and reproduce this problem?

**Comment by liqikai9** [comment]
@zzz731621 Could you please offer the config file you used and the command script you run? And did you make any modifications on the code or config?

**Comment by liqikai9** [comment]
@zzz731621 You can run `python mmpose/utils/collect_env.py` to collect necessary environment information and paste it on the description.

**Comment by liqikai9** [comment]
@zzz731621 Are you using the `TopDownMpiiDataset` class? It seems that in the 
`__init__` part of the code  `mmpose/datasets/datasets/top_down/topdown_mpii_dataset.py`, there is not definition of something like this `self.ann_info['use_different_joint_weights'] = False`. We may add it in the base class `Kpt2dSviewRgbImgTopDownDataset`  in `mmpose/datasets/datasets/base/kpt_2d_sview_rgb_img_top_down_dataset.py` in case that we forget to assign this value.

**Comment by jin-s13** [comment]
Let's move it to mmpose/datasets/datasets/base/kpt_2d_sview_rgb_img_top_down_dataset.py

**Comment by zzz731621** [comment]
sys.platform: linux
Python: 3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0]
CUDA available: True
GPU 0: GeForce RTX 3090
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.2.r11.2/compiler.29618528_0
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.9.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.3-Product Build 20210617 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.10.0
OpenCV: 4.5.3
MMCV: 1.3.13
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: 11.2
MMPose: 0.18.0+2e81fa6

I got this after I run collect_env.py

**Comment by zzz731621** [comment]
I didn't change the config and I just type python tools/train.py config to run the training
But I am using my own images and json files
