### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by soltkreig** [open-mmlab/mmpose#917]
I created my own dataset (in COCO format) but got this error, attach the examples of annotation 5 images in txt format
[detector_test_data_3_val (copy).txt](https://github.com/open-mmlab/mmpose/files/7160111/detector_test_data_3_val.copy.txt)
[detector_test_data_2_train (copy).txt](https://github.com/open-mmlab/mmpose/files/7160112/detector_test_data_2_train.copy.txt)

```
Traceback (most recent call last):
  File "/home/kfour/mmcv/mmcv/utils/registry.py", line 51, in build_from_cfg
    return obj_cls(**args)
  File "/home/kfour/mmpose/mmpose/datasets/datasets/top_down/topdown_coco_dataset.py", line 117, in __init__
    self.db = self._get_db()
  File "/home/kfour/mmpose/mmpose/datasets/datasets/top_down/topdown_coco_dataset.py", line 150, in _get_db
    gt_db = self._load_coco_person_detection_results()
  File "/home/kfour/mmpose/mmpose/datasets/datasets/top_down/topdown_coco_dataset.py", line 274, in _load_coco_person_detection_results
    if det_res['category_id'] != 1:
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 169, in <module>
    main()
  File "tools/train.py", line 165, in main
    meta=meta)
  File "/home/kfour/mmpose/mmpose/apis/train.py", line 121, in train_model
    val_dataset = build_dataset(cfg.data.val, dict(test_mode=True))
  File "/home/kfour/mmpose/mmpose/datasets/builder.py", line 39, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/kfour/mmcv/mmcv/utils/registry.py", line 54, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: TopDownCocoDataset: string indices must be integers
```

**Comment by soltkreig** [comment]
I see a json (COCO_val2017_detections_AP_H_56_person.json' )which contains person bboxes has another format unlike COCO 
```
[{"bbox": [249.8199079291458, 175.21093805640606, 74.00419360691592, 55.626325589288854],
 "category_id": 1, "image_id": 532481, "score": 0.9992738366127014}, 
 {"bbox": [284.07836701140275, 370.43747059580454, 13.844297577440784, 17.42933096343188], 
 "category_id": 1, "image_id": 532481, "score": 0.983318567276001}, 
 {"bbox": [244.05099093550018, 170.61324112294565, 74.56380466590753, 73.94038239037835], 
 "category_id": 1, "image_id": 532481, "score": 0.47115205022441037}]
```

**Comment by jin-s13** [comment]
Yes, the detection box results are not in COCO-format.

**Comment by jin-s13** [comment]
You have to prepare a json file (containing detected box only) following COCO_val2017_detections_AP_H_56_person.json

**Comment by soltkreig** [comment]
Thanks, that's my wrong. I should set use_gt_bboxes = True in my config. I've noticed a lot information in FAQ but usually people include me use Getting Started. I mean maybe should move information from FAQ to Getting Started in step-by-step format? Thanks

**Comment by jin-s13** [comment]
Good idea. We will do that! @ly015

**Comment by alaa-shubbak** [comment]
> Thanks, that's my wrong. I should set use_gt_bboxes = True in my config. I've noticed a lot information in FAQ but usually people include me use Getting Started. I mean maybe should move information from FAQ to Getting Started in step-by-step format? Thanks

hello 
I am  just wondering,where shall i add this  `use_gt_bboxes = True` in the config to get rid from such error message 

`TypeError: TopDownCocoDataset: string indices must be integers`
although i used another approach with using BottomUpCocoDataset, 
so my error is like this 
`TypeError: BottomUpCocoDataset: string indices must be integers`

any help ? i will be so grateful.
