### ISSUE TITLE
Exception has occurred: KeyError

### ISSUE THREAD

**Issue by soltkreig** [open-mmlab/mmpose#922]
Hello again. I continue to explore mmpose. I got the KeyError
Traceback from debug mode:
```
Exception has occurred: KeyError
'/005810.jpg'
  File "/home/kfour/mmpose/mmpose/datasets/datasets/top_down/topdown_coco_dataset.py", line 349, in evaluate
    image_id = self.name2id[image_paths[i][len(self.img_prefix):]]
  File "/home/kfour/mmpose/mmpose/core/evaluation/eval_hooks.py", line 121, in evaluate
    results, runner.work_dir, logger=runner.logger, **self.eval_kwargs)
  File "/home/kfour/mmpose/mmpose/core/evaluation/eval_hooks.py", line 101, in after_train_epoch
    key_score = self.evaluate(runner, results)
  File "/home/kfour/mmcv/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/kfour/mmcv/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/home/kfour/mmcv/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/kfour/mmpose/mmpose/apis/train.py", line 140, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/kfour/mmpose/tools/train.py", line 165, in main
    meta=meta)
  File "/home/kfour/mmpose/tools/train.py", line 169, in <module>
    main()
```

My anno looks this:
```
{
  "images": [
    {
      "file_name": "/media/kfour/fe5700be-8ed1-40d8-9fe1-41fbecc7b84e/rzhd/detector_test_data_3/img_3/00581.jpg",
      "height": 1520,
      "width": 2688,
      "id": 0
    }
],
"annotations": [
    {
      "keypoints": [
        835,
        982,
        2,
        818,
        982,
        2,
        835,
        978,
        2,
        820,
        985,
        2,
        843,
        982,
        2,
        815,
        1004,
        2,
        858,
        1005,
        2,
        812,
        1027,
        2,
        879,
        1020,
        2,
        833,
        1027,
        2,
        879,
        1055,
        2,
        822,
        1067,
        2,
        854,
        1067,
        2,
        824,
        1040,
        2,
        878,
        1032,
        2,
        828,
        1068,
        2,
        875,
        1069,
        2
      ],
      "num_keypoints": 17,
      "area": 12642,
      "iscrowd": 0,
      "image_id": 0,
      "bbox": [
        795,
        951,
        98,
        129
      ],
      "category_id": 1,
      "id": 0
    }
    ],
"categories": [
    {
      "id": 1,
      "name": "person"
    }
  ]
}
```
It looks like in evaluate processing dataloader cannot find the key in dict. Thanks

**Comment by soltkreig** [comment]
00581.jpg in annotation has image_id = 0 but in dict has id = 1. Why?
{1: '/media/kfour/fe5700be-8ed1-40d8-9fe1-41fbecc7b84e/rzhd/detector_test_data_3/img_3/005810.jpg', 
2: '/media/kfour/fe5700be-8ed1-40d8-9fe1-41fbecc7b84e/rzhd/detector_test_data_3/img_3/004118.jpg', 
3: '/media/kfour/fe5700be-8ed1-40d8-9fe1-41fbecc7b84e/rzhd/detector_test_data_3/img_3/001184.jpg', 
4: '/media/kfour/fe5700be-8ed1-40d8-9fe1-41fbecc7b84e/rzhd/detector_test_data_3/img_3/000163.jpg', 
5: '/media/kfour/fe5700be-8ed1-40d8-9fe1-41fbecc7b84e/rzhd/detector_test_data_3/img_3/000211.jpg'}

**Comment by jin-s13** [comment]
It seems that the filename does not match exactly.
"/media/kfour/fe5700be-8ed1-40d8-9fe1-41fbecc7b84e/rzhd/detector_test_data_3/img_3/00581.jpg" and '/media/kfour/fe5700be-8ed1-40d8-9fe1-41fbecc7b84e/rzhd/detector_test_data_3/img_3/005810.jpg'

581.jpg and 5810.jpg

**Comment by soltkreig** [comment]
I've checked: I copied wrong from anno file - names are match.
I've noticed in top_down_coco_dataset.py in line 112:
```self.img_ids = self.coco.getImgIds()```
Has values: 1, 2, 3, 4, 5
It means this func load imgs from 1 not 0

**Comment by jin-s13** [comment]
No. All ids will be loaded. It is okay that the ids are not continuous or not sorted (e.g.   1000, 40, 352, 333 ...) 

The error occurs because `self.img_prefix` is wrong.

```
Exception has occurred: KeyError
'/005810.jpg'
```
This means the func did not find '/005810.jpg', I guess `self.img_prefix` should be empty in your case. Because the filename is the absolute path in your json.

**Comment by soltkreig** [comment]
Yes! I've noticed only now! As my previous issue I think should add the detail mini-guide about COCO annotation with explain every field in annotation json for all MMlab project because I didn't see something really good and simple in Internet. Thanks a lot for help!

**Comment by jin-s13** [comment]
Yes, we will try to improve our documentation. But unfortunately, we don't have enough manpower to complete all these details. We really need more help from the community. 

BTW, @soltkreig would you like to contribute?  e.g. help provide detailed or step-by-step guidance.

**Comment by soltkreig** [comment]
That's good idea, I'm starting next week from guide of COCO annotation format.

**Comment by jin-s13** [comment]
Thanks a lot for your help!

**Comment by YuktiADY** [comment]
Hello.
I am also facing the same issue.
I am getting the below error while training on my custom dataset.

Traceback from debug mode:
File "./mmpose/tools/train.py", line 170, in
main()
File "./mmpose/tools/train.py", line 166, in main
meta=meta)
File "/home/yukti/mmpose/mmpose/mmpose/apis/train.py", line 192, in train_model
runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
File "/home/yukti/mmpose/mmcv/mmcv/runner/epoch_based_runner.py", line 127, in run
epoch_runner(data_loaders[i], **kwargs)
File "/home/yukti/mmpose/mmcv/mmcv/runner/epoch_based_runner.py", line 54, in train
self.call_hook('after_train_epoch')
File "/home/yukti/mmpose/mmcv/mmcv/runner/base_runner.py", line 309, in call_hook
getattr(hook, fn_name)(self)
File "/home/yukti/mmpose/mmcv/mmcv/runner/hooks/evaluation.py", line 267, in after_train_epoch
self._do_evaluate(runner)
File "/home/yukti/mmpose/mmcv/mmcv/runner/hooks/evaluation.py", line 505, in _do_evaluate
key_score = self.evaluate(runner, results)
File "/home/yukti/mmpose/mmpose/mmpose/core/evaluation/eval_hooks.py", line 139, in evaluate
**self.eval_kwargs)
File "/home/yukti/mmpose/mmpose/mmpose/datasets/datasets/top_down/topdown_coco_dataset.py", line 274, in evaluate
image_id = self.name2id[image_paths[i][len(self.img_prefix):]]
KeyError: '/0000115_img.png'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 902238) of binary: /home/yukti/anaconda3/envs/open-mmlab/bin/python
ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed
INFO:torch.distributed.elastic.agent.server.api:[default] Worker group FAILED. 3/3 attempts left; will restart worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Stopping worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous'ing worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous complete for workers. Result:
restart_count=1
master_addr=127.0.0.1
master_port=29500
group_rank=0
group_world_size=1
local_ranks=[0, 1]
role_ranks=[0, 1]
global_ranks=[0, 1]
role_world_sizes=[2, 2]
global_world_sizes=[2, 2]
