### ISSUE TITLE
The Ipynb tutorial file for mmpose

### ISSUE THREAD

**Issue by TianQingX** [open-mmlab/mmpose#929]
May I ask Where is the Ipynb tutorial file for mmpose, I saw it once in this github pages, but cannot find this in master branch, if this file can be added to the tutorial folder will be helpful for those beginner.

**Comment by jin-s13** [comment]
https://github.com/open-mmlab/mmpose/blob/master/demo/MMPose_Tutorial.ipynb

**Comment by jin-s13** [comment]
@ly015  Maybe we should move it to a prominent place.
