### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by ac5113** [open-mmlab/mmpose#931]
When I try to run the MMPose_Tutorial file on colab, in the training block, I am getting a Type Error:
![Capture](https://user-images.githubusercontent.com/55910128/133921934-f24a7e0e-bbcc-4388-aa2a-eb6c0631dcff.PNG)
r

**Comment by jin-s13** [comment]
Did you use the latest version of MMPose?

**Comment by ac5113** [comment]
I used the MMPose_Tutorial.ipynb file, which clones the mmpose repository. So, I think I used the latest version.

**Comment by jin-s13** [comment]
@ly015 Could you offer some help?

**Comment by ly015** [comment]
The error was because that the colab demo used an out-of-date dataset interface, which has been deprecated by #901 . We updated the colab demo in #934 . It should work fine now.

**Comment by ac5113** [comment]
It's working now. Thank you.
