### ISSUE TITLE
模型问题

### ISSUE THREAD

**Issue by wangm-word** [open-mmlab/mmpose#933]
![image](https://user-images.githubusercontent.com/72743278/134335493-3e892036-626a-48ff-a5e1-94f5222c8665.png)
非常感谢你的工作，这个mobilenet的pose你们提供的config文件和权值文件，你们有github地址吗

**Comment by jin-s13** [comment]
没太理解您的问题。Arch那一列里面是config，ckpt那一列是权值文件。

**Comment by wangm-word** [comment]
> 没太理解您的问题。Arch那一列里面是config，ckpt那一列是权值文件。

嗯嗯，我想用自己的数据集跑一下这个模型，所以想问一下有没有这个工程的github地址
@jin-s13

**Comment by jin-s13** [comment]
这些模型都是在mmpose里面训练的，你直接用mmpose就可以run
