### ISSUE TITLE
what's the difference of TopdownHeatmapMultiStageHead and TopdownHeatmapSimpleHead？

### ISSUE THREAD

**Issue by kobe233333** [open-mmlab/mmpose#937]
I'm not very familiar with the algorithm of keypoint detection. Do the resnet, mobilenet, shufflenet, etc. involved in the model you provide follow the framework in Simplebaseline? And what's the difference of TopdownHeatmapMultiStageHead
and TopdownHeatmapSimpleHead？
Please forgive me for my rudimentary question.

**Comment by jin-s13** [comment]
Our config structure present the taxonomy of major algorithms for keypoint detection.
`configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/res50_coco_256x192.py` 
We also provide some description about the algorithm. see configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/README.md 

In topdown_heatmap, we can use different backbone networks, e.g. resnet, mobilenet, shufflenet.
Some backbone networks (e.g. hourglass) are multi-staged, and produce multiple outputs. We need to use TopdownHeatmapMultiStageHead for hourglass. And for resnet, we should use TopdownHeatmapSimpleHead.

**Comment by kobe233333** [comment]
In my opinion, when we use mobilenet or shufflenet, we just change the resnet backbone in SimpleBaseline2d into them ? And if we use other multi-staged backbone ,we should get custom head module to predict the kpts ?

**Comment by jin-s13** [comment]
The head should match the output of the backbone.
