### ISSUE TITLE
shuffle_v2 benchmark

### ISSUE THREAD

**Issue by flynnamy** [open-mmlab/mmpose#94]
Hi，how about the pose benchmark of using shufflenet_v2 as backbone?

**Comment by innerlee** [comment]
https://mmpose.readthedocs.io/en/latest/model_zoo.html#id51

**Comment by flynnamy** [comment]
It is shuffle_v1, right? How about shuffle_v2 and mobilenet_v3? @innerlee

**Comment by innerlee** [comment]
right they are not supported yet. you may request the feature here https://github.com/open-mmlab/mmpose/issues/9

**Comment by jin-s13** [comment]
I have added this feature request in our TODO list. Close this issue for now.
