### ISSUE TITLE
Top down scheme - how it works?

### ISSUE THREAD

**Issue by soltkreig** [open-mmlab/mmpose#944]
Hi. I want to understand how predictions of detector use in pose model?

**Comment by jin-s13** [comment]
Could you please specify the questions?

**Comment by soltkreig** [comment]
As I understand detector localize the coordinates of person then forward it to pose model. But I can't imagine how it looks - what we give to pose model?

**Comment by jin-s13** [comment]
Do you mean 'human detector'? 
The image will be cropped using the human bounding box. The cropped image is given to the pose model.

**Comment by soltkreig** [comment]
But if image contains any person - does it mean what batch of cropped image forward to pose model?
