### ISSUE TITLE
False 'segmentation' labeled in 'macaque_train/test.json'

### ISSUE THREAD

**Issue by chenxinfeng4** [open-mmlab/mmpose#947]
In general, the macaque dataset is missing parts of segmentation.

猴子的数据集：每当身体位置是分开的时候，‘'segmentation’ 的标注都有问题。我check了原始csv标注数据，是正确的；是你们制作的“macaque_train/test.json”出现了偏差。

![image](https://user-images.githubusercontent.com/17546446/135393754-c2539040-10d6-4e24-a3ca-b6bf721287ed.png)

**Comment by jin-s13** [comment]
Thanks for reporting this issue. We will check this later.

**Comment by jin-s13** [comment]
@chenxinfeng4 Could you please check if the problem is solved by #948 ?

**Comment by chenxinfeng4** [comment]
There is a small bug in : `mmpose/tools/dataset/parse_macaquepose_dataset.py :  161`

> 161: dataset_dir = '/data/macaque/'

Which should be
> 161: dataset_dir = 'data/macaque/'
