### ISSUE TITLE
maybe a little bug?  crowdpose config forget the dataset_info in 'test'

### ISSUE THREAD

**Issue by QingYuan-L** [open-mmlab/mmpose#962]
int  demo/top_down_img_demo.py line 63:
dataset_info = pose_model.cfg.data['**test**'].get('dataset_info', None)

but the config in   configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/crowdpose :
    **test**=dict(
        type='TopDownCrowdPoseDataset',
        ann_file=f'{data_root}/annotations/mmpose_crowdpose_test.json',
        img_prefix=f'{data_root}/images/',
        data_cfg=data_cfg,
        pipeline=test_pipeline))

the last line  not have **dataset_info**

when i add ' dataset_info ' to config ,it work,maybe to change the " dataset_info = pose_model.cfg.data['**test**'].get('dataset_info', None)"  to " dataset_info = pose_model.cfg.data['**train**'].get('dataset_info', None)"  is aslo work well?

**Comment by jin-s13** [comment]
Thanks for reporting this issue. I will fix it soon.
