### ISSUE TITLE
Add 3DMPPE POSENET

### ISSUE THREAD

**Issue by znoland3** [open-mmlab/mmpose#964]
**Steps**

1. Check if the feature has been requested in the [meta issue](https://github.com/open-mmlab/mmpose/issues/9), and if so, click thumb up button. - Not in list
1. Post the feature request in the [meta issue](https://github.com/open-mmlab/mmpose/issues/9), if it is new. - done

**Describe the feature**
We would like to add https://github.com/mks0601/3DMPPE_POSENET_RELEASE to MMPose. This is a "Camera Distance-aware Top-down Approach for 3D Multi-person Pose Estimation from a Single RGB Image (ICCV 2019)".

**Motivation**

We have found this model useful for a project, but would like to leverage MMPose.

**Related resources**

https://github.com/mks0601/3DMPPE_POSENET_RELEASE

**Additional context**

I would like to attempt to implement this feature myself. The contribution doc mentioned I should create an issue to discuss first. Let me know if there are any concerns with this.

**Comment by ly015** [comment]
Thank you very much! We sincerely appreciate contributions from the community. Please let us know if there is anything we can help with during implementing this paper.

**Comment by jin-s13** [comment]
Dear @znoland3, 
Hope you are well and healthy at his uncertain period. 
Is the project going well? If you have any problems, please let us know :)

**Comment by znoland3** [comment]
Hello, unfortunately I haven't had time to work on this recently and our project changed direction. I would still be interested in considering 3DMPPE POSENET via MMPose if someone else gets around to adding it.

**Comment by jin-s13** [comment]
Noted with thanks. And thank you again for your interest in MMPose. Wish you every success in your project!
