### ISSUE TITLE
Single keypoint regression on plants

### ISSUE THREAD

**Issue by joihn** [open-mmlab/mmpose#969]
I'm trying to adapt mmpose pose for object detection (plant) + single keypoint regression onto the object (stem).

- Is this idea doable ? 

- Which dataset family would be more appropriate to start form ? 

https://github.com/open-mmlab/mmpose/blob/master/docs/data_preparation.md

**Comment by jin-s13** [comment]
I think it is reasonable to use mmpose for plant keypoint detection.
