### ISSUE TITLE
Demo resources

### ISSUE THREAD

**Issue by ly015** [open-mmlab/mmpose#972]
A collection of images and videos that can be used in demo scripts.

**Comment by liqikai9** [comment]
This video demo is generated using webcam tools.

https://user-images.githubusercontent.com/87690686/149058010-37db8088-c331-4102-9a68-3ab13af1aaa4.mp4

https://user-images.githubusercontent.com/87690686/149058108-b370e6ee-a48d-4132-bf26-57f222586405.gif

**Comment by jin-s13** [comment]
https://user-images.githubusercontent.com/11788150/150138076-2192079f-068a-4d43-bf27-2f1fd708cabc.mp4

**Comment by liqikai9** [comment]
One of the test video file in PoseTrack18.

https://user-images.githubusercontent.com/87690686/163549037-3ca206c6-d4e9-4fea-aa76-9a7f79cc0386.mp4

**Comment by liqikai9** [comment]
One of the test video file in Human3.6m dataset.

https://user-images.githubusercontent.com/87690686/164969833-289459ce-ab4e-4d04-8a17-2953792ace96.mp4

**Comment by liqikai9** [comment]
A clip of the Vinegar Fly dataset video file.

https://user-images.githubusercontent.com/87690686/165095600-f68e0d42-830d-4c22-8940-c90c9f3bb817.mp4

**Comment by liqikai9** [comment]
A single person demo video for full_frame input:

https://user-images.githubusercontent.com/87690686/169808764-29e5678c-6762-4f43-8666-c3e60f94338f.mp4

Download from this link: https://www.youtube.com/watch?v=91sd4Jnwgjs

**Comment by ly015** [comment]
A sunglasses image for webcam demo. Download from: https://www.vecteezy.com/vector-art/1932353-summer-sunglasses-accessory-isolated-icon

![sunglasses](https://user-images.githubusercontent.com/15977946/170850839-acc59e26-c6b3-48c9-a9ec-87556edb99ed.jpg)
