### ISSUE TITLE
3d mesh model and state_dict keys do not match

### ISSUE THREAD

**Issue by sunmengnan** [open-mmlab/mmpose#978]
the trained model and default model seem not match, log is as followed.

unexpected key in source state_dict: joints_regressor, smpl.shapedirs, smpl.faces_tensor, smpl.v_template, smpl.J_regressor, smpl.posedirs, smpl.parents, smpl.lbs_weights, smpl.vertex_joint_selector.extra_joints_idxs

missing keys in source state_dict: smpl.joints_regressor, smpl.smpl_neutral.betas, smpl.smpl_neutral.shapedirs, smpl.smpl_neutral.faces_tensor, smpl.smpl_neutral.v_template, smpl.smpl_neutral.J_regressor, smpl.smpl_neutral.posedirs, smpl.smpl_neutral.parents

**Comment by luminxu** [comment]
Hi,

This warning is caused by the update of codes for SMPL model. We use a new structure for the human mesh model.
Don't worry, it has no effect on training or testing, because the parameters in SMPL models are not updated during training.
