### ISSUE TITLE
Training on Custom Dataset with 9 Keypoints (KeyError: 'XXXXX is not in the dataset registry')

### ISSUE THREAD

**Issue by Sifat-Ahmed** [open-mmlab/mmpose#981]
So, I am trying to run on a very different dataset where I am trying to identify 9 keypoints of a custom object. I have annotated the dataset with COCO annotator and it is in COCO format. 

So here is the edit afterwards:

1. Create a custom config file for the dataset. **datasets/custom.py**

```
dataset_info = dict(
    dataset_name='custom',
    ),
    keypoint_info={
        0:
        dict(name='top', id=0, color=[51, 153, 255], type='upper', swap='bottom'),
        1:
        dict(
            name='center',
            id=1,
            color=[51, 153, 255],
            type='upper',
            swap=''),
        2:
        dict(
            name='bottom',
            id=2,
            color=[51, 153, 255],
            type='lower',
            swap='top'),
        3:
        dict(
            name='right',
            id=3,
            color=[51, 153, 255],
            type='upper',
            swap='left'),
        4:
        dict(
            name='left',
            id=4,
            color=[51, 153, 255],
            type='upper',
            swap='right'),
        5:
        dict(
            name='top-right',
            id=5,
            color=[0, 255, 0],
            type='upper',
            swap='bottom-left'),
        6:
        dict(
            name='top-left',
            id=6,
            color=[255, 128, 0],
            type='upper',
            swap='bottom-right'),
        7:
        dict(
            name='bottom-right',
            id=7,
            color=[0, 255, 0],
            type='lower',
            swap='top-left'),
        8:
        dict(
            name='bottom-left',
            id=8,
            color=[255, 128, 0],
            type='upper',
            swap='top-right'),
        9:
        dict(
            name='left_wrist',
            id=9,
            color=[0, 255, 0],
            type='upper',
            swap='right_wrist'),
    },
    skeleton_info={
        0:
        dict(link=('top', 'center'), id=0, color=[0, 255, 0]),
        1:
        dict(link=('center', 'bottom'), id=1, color=[0, 255, 0]),
        2:
        dict(link=('center', 'right'), id=2, color=[255, 128, 0]),
        3:
        dict(link=('center', 'left'), id=3, color=[255, 128, 0]),
        4:
        dict(link=('center', 'top-right'), id=4, color=[51, 153, 255]),
        5:
        dict(link=('center', 'top-left'), id=5, color=[51, 153, 255]),
        6:
        dict(link=('center', 'bottom-right'), id=6, color=[51, 153, 255]),
        7:
        dict(
            link=('center', 'bottom-left'),
            id=7,
            color=[51, 153, 255]),
    },
    joint_weights=[
        1., 1., 1., 1., 1., 1., 1., 1., 1.
    ],
    sigmas=[
        0.026, 0.025, 0.025, 0.035, 0.035, 0.079, 0.079, 0.072, 0.072
    ])

```

2. create a custom config file. (I am using **configs/body/2d_kpt_sview_rgb_img/associative_embedding/coco/higherhrnet_w32_coco_512x512.py**)

```
data_root = 'data/coco'
classes = ('__background__', 'concrete')
data = dict(
    samples_per_gpu=24,
    workers_per_gpu=2,
    train=dict(
        type='custom',
        ann_file=f'{data_root}/annotations/ConcreteKeypoints_train.json',
        img_prefix=f'{data_root}/train/',
        data_cfg=data_cfg,
        pipeline=train_pipeline,
        dataset_info={{_base_.dataset_info}}),
    val=dict(
        type='custom',
        ann_file=f'{data_root}/annotations/ConcreteKeypoints_val.json',
        img_prefix=f'{data_root}/val/',
        data_cfg=data_cfg,
        pipeline=val_pipeline,
        dataset_info={{_base_.dataset_info}}),
    test=dict(
        type='custom',
        ann_file=f'{data_root}/annotations/ConcreteKeypoints_val.json',
        img_prefix=f'{data_root}/val/',
        data_cfg=data_cfg,
        pipeline=test_pipeline,
        dataset_info={{_base_.dataset_info}}),
)

```

After doing this, I get this error:

```
 File "train.py", line 145, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/workstaion/workspace/potatochips/AS_Garbage/mmpose/mmpose/mmpose/datasets/builder.py", line 44, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/workstaion/workspace/potatochips/AS_Garbage/mmpose/mmcv/mmcv/utils/registry.py", line 45, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'custom is not in the dataset registry'
```

So how do I include the custom definition of my dataset into the registry?

TIA.

**Comment by ly015** [comment]
Hi,

In mmpose, **Dataset** and **DatasetInfo** are two different concepts. DatasetInfo is a data structure to hold meta information like keypoint definition and order. And a Dataset is a class to store and pre-process samples and annotations, which usually takes a `DatasetInfo` instance as an initialization argument.

In your case, the file ` datasets/custom.py` actually defines a DatasetInfo instance.  You can still use the `BottomUpCOCODataset` (by setting `type='BottomUpCOCODataset'` in fields data.train, data.test and data.val in the config), and use your own DatasetInfo by setting `_base_` field as `datasets/custom.py`.

If you intend to implement a new Dataset class, you need to register it `DATASETS` registry (see [BottomUpCOCODataset](https://github.com/open-mmlab/mmpose/blob/master/mmpose/datasets/datasets/bottom_up/bottom_up_coco.py) for example). Then you can set `type` as the name of the custom dataset in configs to use it.

**Comment by rubeea** [comment]
Hi @Sifat-Ahmed,

I am also working with custom datasets. I have a general query regarding the custom dataset. You mentioned that your custom dataset has 9 key points, I wanted to ask that did you annotate the dataset yourself? If yes, then did you try annotating your objects with fewer key points (6 instead of 9) and then test the pose estimation models? Were there any changes in the results obtained? 
Looking forward to your reply.
Thanks and Regards

**Comment by Sifat-Ahmed** [comment]
@rubeea,

Yes, I have annotated the dataset by myself. But I didn't try annotating objects with fewer keypoints. For an example, I annotated a Stone/Rock with 9 keypoints but didn't try to evaluate with 6/7 instead of 9. I am not sure if it makes any sense. I am also not sure if it will work with repository. You might have to write custom evaluation metrics for that. It always expects same number of inputs and predictions.

Regards.

**Comment by rubeea** [comment]
> @rubeea,
> 
> Yes, I have annotated the dataset by myself. But I didn't try annotating objects with fewer keypoints. For an example, I annotated a Stone/Rock with 9 keypoints but didn't try to evaluate with 6/7 instead of 9. I am not sure if it makes any sense. I am also not sure if it will work with repository. You might have to write custom evaluation metrics for that. It always expects same number of inputs and predictions.
> 
> Regards.

@Sifat-Ahmed,

It does not require custom evaluation metrics. We just have to modify the data, inference and the output channels in the head to see the difference. I actually tested with few annotation schemes and observed a difference in the performance metrics so that is why just wanted to confirm if anyone has performed something similar and observed any difference.
